# 05 DQA Scene/Class Profile 5h

This notebook is the first DQA experiment aligned to the intended claim:

- server labeled data is limited to the cloudy/partly-cloudy server split
- clients are unlabeled scene domains: highway, city street, residential
- DQA should help when each client has different useful class evidence
- pseudo-label bbox damage is reduced with the best safe profile from the 02/ET probes

Default runtime target is about 5 hours by reusing an existing scene warmup and running a
shorter federated schedule.  For the later 12h run, change `PHASE1_ROUNDS` and
`PHASE2_ROUNDS` in the settings cell.

## 1. Paths

In [1]:
print("hello")

hello

In [2]:
from __future__ import annotations

import json
import os
import re
import shutil
import socket
import subprocess
import sys
from collections import deque
from pathlib import Path
from typing import Optional

import pandas as pd


def find_repo_root(start: Optional[Path] = None) -> Path:
    start = Path.cwd().resolve() if start is None else Path(start).resolve()
    required = (
        "dynamic_quality_aware_classwise_aggregation/run_dqa_cwa_fedsto_scene_v2_profiled.py",
        "dynamic_quality_aware_classwise_aggregation/evaluate_scene_protocol.py",
        "navigating_data_heterogeneity/setup_fedsto_scene_reproduction.py",
    )
    for base in (start, *start.parents):
        for candidate in (base, base / "Object_Detection"):
            if all((candidate / marker).exists() for marker in required):
                return candidate.resolve()
    raise FileNotFoundError("Could not locate /app/Object_Detection")


REPO_ROOT = find_repo_root()
DQA_ROOT = REPO_ROOT / "dynamic_quality_aware_classwise_aggregation"
RUN_SCRIPT = DQA_ROOT / "run_dqa_cwa_fedsto_scene_v2_profiled.py"
EVAL_SCRIPT = DQA_ROOT / "evaluate_scene_protocol.py"

WORK_ROOT = DQA_ROOT / "efficientteacher_dqa05_scene_class_profile_5h"
STATS_ROOT = DQA_ROOT / "stats_dqa05_scene_class_profile_5h"
RUNNER_LOG = DQA_ROOT / "dqa05_scene_class_profile_5h_runner.out"
TRAIN_LOG = DQA_ROOT / "dqa05_scene_class_profile_5h_train.log"
PID_PATH = DQA_ROOT / "dqa05_scene_class_profile_5h_runner.pid"

SOURCE_WARMUP = (
    DQA_ROOT
    / "efficientteacher_dqa_ver2_scene_12h"
    / "global_checkpoints"
    / "round000_warmup.pt"
)

preferred_python = Path("/root/micromamba/envs/al_yolov8/bin/python")
PYTHON_BIN = preferred_python if preferred_python.exists() else Path(sys.executable)

print("repo_root:", REPO_ROOT)
print("workspace:", WORK_ROOT)
print("stats_root:", STATS_ROOT)
print("python:", PYTHON_BIN)
print("source_warmup:", SOURCE_WARMUP)

repo_root: /app/Object_Detection
workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h
stats_root: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/stats_dqa05_scene_class_profile_5h
python: /root/micromamba/envs/al_yolov8/bin/python
source_warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa_ver2_scene_12h/global_checkpoints/round000_warmup.pt

## 2. Experiment Settings

In [ ]:
# 5h pilot.  For the later 12h run, use PHASE1_ROUNDS=20 and PHASE2_ROUNDS=35.
WARMUP_EPOCHS = 20
PHASE1_ROUNDS = 8
PHASE2_ROUNDS = 14
DQA_START_PHASE = 2

BATCH_SIZE = 160
WORKERS = 6
REQUESTED_GPUS = 2
# The runner deletes completed-round intermediates.  The earlier 70 GiB
# guard is useful for full clean reproductions, but too strict on this
# shared workspace where only ~14 GiB is currently free.
MIN_FREE_GIB = 8

# Loss profile selected by run_dqa_cwa_fedsto_scene_v2_profiled.py.
# strict_low_bbox was chosen because it reduced pseudo-bbox damage while keeping enough
# active classes for DQA.  objectness_only is available as a later ablation.
SSOD_PROFILE = "strict_low_bbox"
CLIENT_LR0 = 3e-4
SERVER_LR0 = 1e-3

SEED_WARMUP_FROM_SOURCE = True
APPEND_TRAIN_LOG = False
RUN_TRAINING = True
RUN_IN_BACKGROUND = False
STREAM_TRAIN_OUTPUT = True

try:
    import torch

    AVAILABLE_CUDA_GPUS = torch.cuda.device_count()
except Exception as exc:
    AVAILABLE_CUDA_GPUS = 0
    print("Could not inspect CUDA devices:", exc)

GPUS = min(REQUESTED_GPUS, AVAILABLE_CUDA_GPUS) if AVAILABLE_CUDA_GPUS else 1
if GPUS != REQUESTED_GPUS:
    print(f"Requested {REQUESTED_GPUS} GPU(s), visible={AVAILABLE_CUDA_GPUS}; using GPUS={GPUS}")


def find_free_port(preferred: int) -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind(("127.0.0.1", preferred))
            return preferred
        except OSError:
            pass
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


MASTER_PORT = find_free_port(29525)

os.environ["DQA05_SSOD_PROFILE"] = SSOD_PROFILE
os.environ["DQA05_CLIENT_LR0"] = str(CLIENT_LR0)
os.environ["DQA05_SERVER_LR0"] = str(SERVER_LR0)

{
    "phase1_rounds": PHASE1_ROUNDS,
    "phase2_rounds": PHASE2_ROUNDS,
    "dqa_start_phase": DQA_START_PHASE,
    "ssod_profile": SSOD_PROFILE,
    "client_lr0": CLIENT_LR0,
    "server_lr0": SERVER_LR0,
    "batch_size": BATCH_SIZE,
    "gpus": GPUS,
    "master_port": MASTER_PORT,
    "workspace": str(WORK_ROOT),
}

{'phase1_rounds': 8,
 'phase2_rounds': 14,
 'dqa_start_phase': 2,
 'ssod_profile': 'strict_low_bbox',
 'client_lr0': 0.0003,
 'server_lr0': 0.001,
 'batch_size': 128,
 'gpus': 2,
 'master_port': 29525,
 'workspace': '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h'}

## 3. Build Lists and Seed Warmup

The scene setup creates highway/citystreet/residential clients and scene-wise validation
lists.  The 5h pilot reuses the existing scene warmup so the budget is spent on DQA.

In [4]:
subprocess.run(
    [
        str(PYTHON_BIN),
        str(RUN_SCRIPT),
        "--setup-only",
        "--workspace-root",
        str(WORK_ROOT),
        "--stats-root",
        str(STATS_ROOT),
    ],
    cwd=REPO_ROOT,
    check=True,
    env=os.environ.copy(),
)

warmup_dst = WORK_ROOT / "global_checkpoints" / "round000_warmup.pt"
if SEED_WARMUP_FROM_SOURCE and SOURCE_WARMUP.exists() and not warmup_dst.exists():
    warmup_dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SOURCE_WARMUP, warmup_dst)
    print("Seeded warmup:", warmup_dst)
elif warmup_dst.exists():
    print("Warmup already present:", warmup_dst)
else:
    print("No warmup seed found; the runner will train warmup from scratch.")

manifest = json.loads((WORK_ROOT / "manifest.json").read_text(encoding="utf-8"))
server = manifest["server"]
clients = manifest["clients"]
eval_splits = manifest["paper_evaluation"]["splits"]

display(pd.DataFrame([server]))
display(pd.DataFrame(clients))
display(pd.DataFrame(eval_splits)[["name", "raw_scene", "images", "boxes"]])

{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "48b5cc25459cc3c30d8198067ccff981678f513b",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "48b5cc25459cc3c30d8198067ccff981678f513b",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_phase2_orthogonal.yaml"
  }
}
Warmup already present: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/round000_warmup.pt

,weather,train_list,val_list,source_val_list,train_images,val_images,source_val_images,validation_target
0,cloudy represented by BDD100K Kaggle weather='...,/app/Object_Detection/dynamic_quality_aware_cl...,/app/Object_Detection/dynamic_quality_aware_cl...,/app/Object_Detection/dynamic_quality_aware_cl...,4881,9864,738,scene_total

,id,weather,scene,list,images
0,0,highway,highway,/app/Object_Detection/dynamic_quality_aware_cl...,5000
1,1,citystreet,city street,/app/Object_Detection/dynamic_quality_aware_cl...,5000
2,2,residential,residential,/app/Object_Detection/dynamic_quality_aware_cl...,5000

          name    raw_scene  images   boxes
0      highway      highway    2499   36377
1   citystreet  city street    6112  127178
2  residential  residential    1253   20855

## 4. Dry Run

In [5]:
dry_cmd = [
    str(PYTHON_BIN),
    str(RUN_SCRIPT),
    "--dry-run",
    "--workspace-root",
    str(WORK_ROOT),
    "--stats-root",
    str(STATS_ROOT),
    "--warmup-epochs",
    str(WARMUP_EPOCHS),
    "--phase1-rounds",
    str(PHASE1_ROUNDS),
    "--phase2-rounds",
    str(PHASE2_ROUNDS),
    "--dqa-start-phase",
    str(DQA_START_PHASE),
    "--batch-size",
    str(BATCH_SIZE),
    "--workers",
    str(WORKERS),
    "--gpus",
    str(GPUS),
    "--master-port",
    str(MASTER_PORT),
    "--min-free-gib",
    str(MIN_FREE_GIB),
    "--classwise-blend",
    "0.35",
    "--server-anchor",
    "1.25",
    "--localize-bn",
    "--enable-dqa-guard",
    "--dqa-drop-ratio-threshold",
    "0.15",
    "--dqa-spike-ratio-threshold",
    "3.0",
]

subprocess.run(dry_cmd, cwd=REPO_ROOT, check=True, env=os.environ.copy())

{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "48b5cc25459cc3c30d8198067ccff981678f513b",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "48b5cc25459cc3c30d8198067ccff981678f513b",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_phase2_orthogonal.yaml"
  }
}
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 29525 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/runtime_server_warmup.yaml
Dry run complete. DQA-CWA workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/run_dqa_cwa_fedsto_scene_v2_profiled.py', '--dry-run', '--workspace-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h', '--stats-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/stats_dqa05_scene_class_profile_5h', '--warmup-epochs', '20', '--phase1-rounds', '8', '--phase2-rounds', '14', '--dqa-start-phase', '2', '--batch-size', '128', '--workers', '4', '--gpus', '2', '--master-port', '29525', '--min-free-gib', '8', '--classwise-blend', '0.35', '--server-anchor', '1.25', '--localize-bn', '--enable-dqa-guard', '--dqa-drop-ratio-threshold', '0.15', '--dqa-spike-ratio-threshold', '3.0'], returncode=0)

## 5. Start or Resume Training

In [6]:
def read_pid(path: Path) -> int | None:
    if not path.exists():
        return None
    try:
        return int(path.read_text(encoding="utf-8").strip())
    except ValueError:
        return None


def pid_state(pid: int | None) -> str:
    if pid is None:
        return "missing"
    result = subprocess.run(["ps", "-o", "stat=", "-p", str(pid)], capture_output=True, text=True)
    state = result.stdout.strip()
    if result.returncode != 0 or not state:
        return "missing"
    if "Z" in state:
        return "zombie"
    return state


train_cmd = [
    str(PYTHON_BIN),
    "-u",
    str(RUN_SCRIPT),
    "--workspace-root",
    str(WORK_ROOT),
    "--stats-root",
    str(STATS_ROOT),
    "--warmup-epochs",
    str(WARMUP_EPOCHS),
    "--phase1-rounds",
    str(PHASE1_ROUNDS),
    "--phase2-rounds",
    str(PHASE2_ROUNDS),
    "--dqa-start-phase",
    str(DQA_START_PHASE),
    "--batch-size",
    str(BATCH_SIZE),
    "--workers",
    str(WORKERS),
    "--gpus",
    str(GPUS),
    "--master-port",
    str(MASTER_PORT),
    "--min-free-gib",
    str(MIN_FREE_GIB),
    "--log-file",
    str(TRAIN_LOG),
    "--classwise-blend",
    "0.35",
    "--server-anchor",
    "1.25",
    "--localize-bn",
    "--enable-dqa-guard",
    "--dqa-drop-ratio-threshold",
    "0.15",
    "--dqa-spike-ratio-threshold",
    "3.0",
]
if APPEND_TRAIN_LOG:
    train_cmd.append("--append-train-log")
if STREAM_TRAIN_OUTPUT:
    train_cmd.append("--stream-train-output")

current_pid = read_pid(PID_PATH)
state = pid_state(current_pid)
print("existing pid:", current_pid, state)
print(" ".join(train_cmd))

if RUN_TRAINING and state not in {"missing", "zombie"}:
    print("Training already appears to be running.")
elif RUN_TRAINING and RUN_IN_BACKGROUND:
    env = os.environ.copy()
    RUNNER_LOG.parent.mkdir(parents=True, exist_ok=True)
    log_mode = "ab" if APPEND_TRAIN_LOG else "wb"
    with RUNNER_LOG.open(log_mode) as out:
        process = subprocess.Popen(
            train_cmd,
            cwd=REPO_ROOT,
            stdout=out,
            stderr=subprocess.STDOUT,
            env=env,
            start_new_session=True,
        )
    PID_PATH.write_text(str(process.pid), encoding="utf-8")
    print("Started PID:", process.pid)
    print("Runner log:", RUNNER_LOG)
    print("Train log:", TRAIN_LOG)
elif RUN_TRAINING:
    env = os.environ.copy()
    RUNNER_LOG.parent.mkdir(parents=True, exist_ok=True)
    log_mode = "a" if APPEND_TRAIN_LOG else "w"
    print("Running in foreground; progress will stream in this cell.")
    print("Runner log:", RUNNER_LOG)
    print("Train log:", TRAIN_LOG)
    with RUNNER_LOG.open(log_mode, encoding="utf-8", buffering=1) as runner_log:
        process = subprocess.Popen(
            train_cmd,
            cwd=REPO_ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            env=env,
        )
        PID_PATH.write_text(str(process.pid), encoding="utf-8")
        print("Started PID:", process.pid)
        runner_log.write(f"Started PID: {process.pid}\n")
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="")
            runner_log.write(line)
        return_code = process.wait()
    if PID_PATH.exists() and PID_PATH.read_text(encoding="utf-8").strip() == str(process.pid):
        PID_PATH.unlink()
    if return_code != 0:
        raise RuntimeError(f"Training failed with exit code {return_code}. See {RUNNER_LOG} and {TRAIN_LOG}.")
    print("Training completed.")
else:
    print("RUN_TRAINING=False, command was not launched.")

existing pid: None missing
/root/micromamba/envs/al_yolov8/bin/python -u /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/run_dqa_cwa_fedsto_scene_v2_profiled.py --workspace-root /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h --stats-root /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/stats_dqa05_scene_class_profile_5h --warmup-epochs 20 --phase1-rounds 8 --phase2-rounds 14 --dqa-start-phase 2 --batch-size 128 --workers 4 --gpus 2 --master-port 29525 --min-free-gib 8 --log-file /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/dqa05_scene_class_profile_5h_train.log --classwise-blend 0.35 --server-anchor 1.25 --localize-bn --enable-dqa-guard --dqa-drop-ratio-threshold 0.15 --dqa-spike-ratio-threshold 3.0 --stream-train-output
Running in foreground; progress will stream in this cell.
Runner log: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/dqa05_scene_class_profile_5h_runner.out
Train log: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/dqa05_scene_class_profile_5h_train.log
Started PID: 26216
{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "48b5cc25459cc3c30d8198067ccff981678f513b",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "48b5cc25459cc3c30d8198067ccff981678f513b",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/server_phase2_orthogonal.yaml"
  }
}
Reusing completed warm-up checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/round000_warmup.pt
Resuming DQA-CWA after 9 completed federated rounds from phase 2 round 2.
Current global checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/phase2_round001_global.pt
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 29525 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/configs/runtime_phase2_client_round2_dqa_phase2_round002_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
EfficientTeacher  48b5cc2 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/619 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/client_states/client_0_phase2_round002_start.pt
Scaled weight_decay = 0.001
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train' images and labels...:   0%|          | 0/4881 [00:00<?, ?it/s]
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train' images and labels...2292 found, 0 missing, 0 empty, 0 corrupted:  47%|████▋     | 2292/4881 [00:00<00:00, 22816.45it/s]
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train' images and labels...4574 found, 0 missing, 0 empty, 0 corrupted:  94%|█████████▎| 4574/4881 [00:00<00:00, 20985.62it/s]
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 21233.71it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
world_size: 2
rank: 0

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
world_size: 2
rank: 1

target: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target' images and labels...:   0%|          | 0/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target' images and labels...2652 found, 0 missing, 0 empty, 0 corrupted:  53%|█████▎    | 2652/5000 [00:00<00:00, 25165.03it/s]
target: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target' images and labels...5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<00:00, 28352.84it/s]
target: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target.cache

target: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/client_0_highway_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_val' images and labels...:   0%|          | 0/738 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_val' images and labels...484 found, 0 missing, 0 empty, 0 corrupted:  66%|██████▌   | 484/738 [00:00<00:00, 4751.72it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 5701.02it/s]
val: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982
Plotting labels...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round002_client0_highway
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:435: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:435: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W430 09:38:39.011059110 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W430 09:38:39.013281223 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:785: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:785: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:815: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:815: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:785: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):


## 6. Status

In [7]:
def tail_lines(path: Path, lines: int = 30) -> list[str]:
    if not path.exists():
        return []
    try:
        result = subprocess.run(["tail", "-n", str(lines), str(path)], capture_output=True, text=True, check=True)
        return result.stdout.splitlines()
    except Exception:
        with path.open(encoding="utf-8", errors="replace") as f:
            return [line.rstrip("\n") for line in deque(f, maxlen=lines)]


history_path = WORK_ROOT / "history.json"
history = json.loads(history_path.read_text(encoding="utf-8")) if history_path.exists() else []
pid = read_pid(PID_PATH)

completed_phase1 = sum(1 for row in history if int(row.get("phase", 0)) == 1)
completed_phase2 = sum(1 for row in history if int(row.get("phase", 0)) == 2)
latest_global = Path(history[-1]["global"]) if history else WORK_ROOT / "global_checkpoints" / "round000_warmup.pt"

display(
    pd.DataFrame(
        [
            {
                "pid": pid,
                "pid_state": pid_state(pid),
                "completed_phase1": f"{completed_phase1}/{PHASE1_ROUNDS}",
                "completed_phase2": f"{completed_phase2}/{PHASE2_ROUNDS}",
                "completed_total": f"{len(history)}/{PHASE1_ROUNDS + PHASE2_ROUNDS}",
                "latest_global": str(latest_global),
                "free_gib": round(shutil.disk_usage(WORK_ROOT).free / 1024**3, 2),
            }
        ]
    )
)

print("Runner log tail:")
for line in tail_lines(RUNNER_LOG, 35):
    print(line)
print("\nTrain log tail:")
for line in tail_lines(TRAIN_LOG, 35):
    print(line)

,pid,pid_state,completed_phase1,completed_phase2,completed_total,latest_global,free_gib
0,None,missing,8/8,14/14,22/22,/app/Object_Detection/dynamic_quality_aware_cl...,127.76

Runner log tail:
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:06<00:00,  1.01s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:06<00:00,  1.01s/it]
                 all        738      14937      0.638      0.431      0.443      0.257
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/6 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  17%|█▋        | 1/6 [00:00<00:03,  1.47it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  33%|███▎      | 2/6 [00:01<00:03,  1.33it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  50%|█████     | 3/6 [00:02<00:02,  1.23it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  67%|██████▋   | 4/6 [00:03<00:01,  1.23it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  83%|████████▎ | 5/6 [00:03<00:00,  1.30it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:04<00:00,  1.47it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:04<00:00,  1.37it/s]
                 all        738      14937      0.621      0.434       0.44      0.257
                   0        738       1052      0.562      0.515      0.508      0.239
                   1        738         44      0.584      0.341      0.369      0.218
                   2        738       8622      0.725      0.712      0.746      0.482
                   3        738        151      0.573      0.523      0.519      0.372
                   4        738        467      0.558      0.536      0.565      0.411
                   5        738         70      0.329      0.414      0.309      0.174
                   6        738         65      0.562      0.169      0.227      0.126
                   7        738       1619      0.644      0.573       0.59      0.243
                   8        738       2845       0.67      0.552      0.566      0.297
                   9        738          2          1          0    0.00414    0.00331
Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server

1 epochs completed in 0.031 hours.
Destroying process group...
[rank0]:[W430 11:36:29.463080353 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Completed DQA-CWA phase 2 round 14: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/phase2_round014_global.pt

Train log tail:
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  83%|████████▎ | 5/6 [00:04<00:00,  1.53it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:06<00:00,  1.01s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:06<00:00,  1.01s/it]
                 all        738      14937      0.638      0.431      0.443      0.257
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/6 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  17%|█▋        | 1/6 [00:00<00:03,  1.47it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  33%|███▎      | 2/6 [00:01<00:03,  1.33it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  50%|█████     | 3/6 [00:02<00:02,  1.23it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  67%|██████▋   | 4/6 [00:03<00:01,  1.23it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  83%|████████▎ | 5/6 [00:03<00:00,  1.30it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:04<00:00,  1.47it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 6/6 [00:04<00:00,  1.37it/s]
                 all        738      14937      0.621      0.434       0.44      0.257
                   0        738       1052      0.562      0.515      0.508      0.239
                   1        738         44      0.584      0.341      0.369      0.218
                   2        738       8622      0.725      0.712      0.746      0.482
                   3        738        151      0.573      0.523      0.519      0.372
                   4        738        467      0.558      0.536      0.565      0.411
                   5        738         70      0.329      0.414      0.309      0.174
                   6        738         65      0.562      0.169      0.227      0.126
                   7        738       1619      0.644      0.573       0.59      0.243
                   8        738       2845       0.67      0.552      0.566      0.297
                   9        738          2          1          0    0.00414    0.00331
Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/runs/dqa_phase2_round014_server

1 epochs completed in 0.031 hours.
Destroying process group...
[rank0]:[W430 11:36:29.463080353 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

## 7. Scene/Class Evaluation

After the run finishes, set `RUN_EVAL=True`.  This evaluates warmup, final phase 1,
and final phase 2 on highway/citystreet/residential/total, with per-class AP rows.

In [8]:
RUN_EVAL = False
EVAL_SPLITS = "highway,citystreet,residential,total"
EVAL_BATCH_SIZE = 16
EVAL_DEVICE = ""

history = json.loads((WORK_ROOT / "history.json").read_text(encoding="utf-8")) if (WORK_ROOT / "history.json").exists() else []
checkpoints: list[tuple[str, Path]] = []
warmup = WORK_ROOT / "global_checkpoints" / "round000_warmup.pt"
if warmup.exists():
    checkpoints.append(("warmup", warmup))
phase1 = [row for row in history if int(row.get("phase", 0)) == 1]
phase2 = [row for row in history if int(row.get("phase", 0)) == 2]
if phase1:
    checkpoints.append((f"phase1_round{int(phase1[-1]['round']):03d}", Path(phase1[-1]["global"])))
if phase2:
    checkpoints.append((f"phase2_round{int(phase2[-1]['round']):03d}", Path(phase2[-1]["global"])))

eval_cmd = [
    str(PYTHON_BIN),
    str(EVAL_SCRIPT),
    "--workspace",
    str(WORK_ROOT),
    "--splits",
    EVAL_SPLITS,
    "--batch-size",
    str(EVAL_BATCH_SIZE),
    "--no-plots",
    "--verbose",
]
if EVAL_DEVICE:
    eval_cmd.extend(["--device", EVAL_DEVICE])
for label, path in checkpoints:
    eval_cmd.extend(["--checkpoint", f"{label}={path}"])

print("checkpoints:", checkpoints)
print(" ".join(eval_cmd))
if RUN_EVAL and checkpoints:
    subprocess.run(eval_cmd, cwd=REPO_ROOT, check=True)
elif RUN_EVAL:
    print("No checkpoints found to evaluate.")
else:
    print("RUN_EVAL=False; set True after training finishes.")

checkpoints: [('warmup', PosixPath('/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/round000_warmup.pt')), ('phase1_round008', PosixPath('/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/phase1_round008_global.pt')), ('phase2_round014', PosixPath('/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/phase2_round014_global.pt'))]
/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/evaluate_scene_protocol.py --workspace /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h --splits highway,citystreet,residential,total --batch-size 16 --no-plots --verbose --checkpoint warmup=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/round000_warmup.pt --checkpoint phase1_round008=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/phase1_round008_global.pt --checkpoint phase2_round014=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/global_checkpoints/phase2_round014_global.pt
RUN_EVAL=False; set True after training finishes.

## 8. Read Evaluation Tables

In [9]:
summary_csv = WORK_ROOT / "validation_reports" / "paper_protocol_eval_summary.csv"
classwise_csv = WORK_ROOT / "validation_reports" / "paper_protocol_classwise_summary.csv"

if summary_csv.exists():
    summary = pd.read_csv(summary_csv)
    display(summary.sort_values(["checkpoint_label", "split"]))
else:
    print("No summary yet:", summary_csv)

if classwise_csv.exists():
    classwise = pd.read_csv(classwise_csv)
    display(classwise.sort_values(["split", "class", "map50_95"], ascending=[True, True, False]).head(80))
    pivot = classwise.pivot_table(
        index=["split", "class"],
        columns="checkpoint_label",
        values="map50_95",
        aggfunc="first",
    )
    display(pivot)
else:
    print("No classwise summary yet:", classwise_csv)

No summary yet: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/validation_reports/paper_protocol_eval_summary.csv
No classwise summary yet: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/efficientteacher_dqa05_scene_class_profile_5h/validation_reports/paper_protocol_classwise_summary.csv

## 9. DQA Stats Snapshot

In [10]:
state_path = WORK_ROOT / "dqa_cwa_state.json"
if state_path.exists():
    state = json.loads(state_path.read_text(encoding="utf-8"))
    guard = state.get("round_guard", {})
    display(pd.DataFrame(guard.get("history", [])).tail(20))
    alpha = state.get("alpha", {})
    if alpha:
        latest_key = sorted(alpha)[-1]
        alpha_df = pd.DataFrame(alpha[latest_key]).T
        alpha_df.columns = latest_key.split("|")
        alpha_df.insert(0, "class", manifest["classes"])
        display(alpha_df)
else:
    print("No DQA state yet:", state_path)

stats_files = sorted(STATS_ROOT.glob("phase*_round*.json"))
print("stats files:", len(stats_files), "root:", STATS_ROOT)

    active_classes  mean_quality  phase reason  round  total_count  used_dqa
0                8      0.766022      2             1     377893.0      True
1                8      0.766022      2             1     377893.0      True
2                8      0.766022      2             1     377893.0      True
3                9      0.772464      2             2     350870.0      True
4                9      0.773720      2             3     350531.0      True
5                9      0.774374      2             4     350622.0      True
6                9      0.773994      2             5     355755.0      True
7                9      0.773593      2             6     362512.0      True
8                9      0.773177      2             7     366324.0      True
9                9      0.772111      2             8     369580.0      True
10               9      0.770999      2             9     375327.0      True
11               9      0.770390      2            10     377557.0      True
12               9      0.769110      2            11     383075.0      True
13               9      0.768944      2            12     380992.0      True
14               9      0.768200      2            13     386338.0      True
15               9      0.768120      2            14     386315.0      True

           class  client:0  client:1  client:2  server
0         person  0.165563  0.198897  0.185539    0.45
1          rider  0.154832  0.208682  0.186486    0.45
2            car  0.179620  0.184119  0.186261    0.45
3            bus  0.181228  0.193606  0.175167    0.45
4          truck  0.183506  0.186340  0.180154    0.45
5           bike  0.146697  0.203854  0.199449    0.45
6          motor  0.119399  0.222034  0.208567    0.45
7  traffic light  0.176751  0.190549  0.182700    0.45
8   traffic sign  0.192244  0.180714  0.177042    0.45
9          train  0.250000  0.250000  0.250000    0.25

stats files: 56 root: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/stats_dqa05_scene_class_profile_5h