# 01 Best PseudoGT Learnability

This notebook separates pseudo-GT learning from DQA aggregation.
Every client starts from the copied 08_4 warmup checkpoint, then
candidate pseudo-GT training profiles are compared on the same
scene protocol used by the DQA experiments.

## Fixed condition

- Start checkpoint: `checkpoints/round000_warmup.pt`
- Output root: `output/`
- Clients: `highway`, `citystreet`, `residential`
- Evaluation: `highway`, `citystreet`, `residential`, `total`
- Main question: can pseudo-GT training itself produce useful
  client updates before DQA-style class-wise aggregation is added?

In [2]:
from pathlib import Path
import os
import subprocess
import sys

cwd = Path.cwd().resolve()
if cwd.name == "notebooks":
    PROJECT_ROOT = cwd.parent
elif (cwd / "pseudogt_learnability").exists():
    PROJECT_ROOT = cwd / "pseudogt_learnability"
else:
    PROJECT_ROOT = cwd
os.chdir(PROJECT_ROOT)
print(PROJECT_ROOT)
print((PROJECT_ROOT / "checkpoints" / "round000_warmup.pt").exists())

/app/Object_Detection/pseudogt_learnability
True

## Setup check

This creates/reuses scene data lists in `output/` and verifies that
the copied warmup checkpoint is visible from the new project.

In [3]:
subprocess.run([
    sys.executable,
    "scripts/run_pseudogt_learnability_01.py",
    "--setup-only",
], check=True)

{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/pseudogt_learnability/output/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/server_phase2_orthogonal.yaml"
  }
}
Project root: /app/Object_Detection/pseudogt_learnability
Workspace: /app/Object_Detection/pseudogt_learnability/output
Warmup: /app/Object_Detection/pseudogt_learnability/output/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "weather": "highway",
      "scene": "highway",
      "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.txt",
      "images": 5000
    },
    {
      "id": 1,
      "weather": "citystreet",
      "scene": "city street",
      "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.txt",
      "images": 5000
    },
    {
      "id": 2,
      "weather": "residential",
      "scene": "residential",
      "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.txt",
      "images": 5000
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_total_val.txt",
    "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9864,
    "source_val_images": 738,
    "validation_target": "scene_total"
  }
}
Setup complete.

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_pseudogt_learnability_01.py', '--setup-only'], returncode=0)

## Run 01

The default run tests three profiles:

- `backbone_obj_safe`
- `neck_head_high_precision`
- `all_consistency_lowlr`

It saves client checkpoints, aggregate checkpoints, one-epoch
server-repair checkpoints, and then evaluates them scene-wise.

In [4]:
cmd = [
    sys.executable,
    "scripts/run_pseudogt_learnability_01.py",
    "--variants", "backbone_obj_safe,neck_head_high_precision,all_consistency_lowlr",
    "--batch-size", "160",
    "--workers", "8",
    "--gpus", "2",
    "--master-port", "30341",
    "--server-repair-epochs", "1",
    "--evaluate",
    "--classwise",
    "--no-eval-plots",
]
print(" ".join(cmd))
subprocess.run(cmd, check=True)

/root/micromamba/envs/al_yolov8/bin/python scripts/run_pseudogt_learnability_01.py --variants backbone_obj_safe,neck_head_high_precision,all_consistency_lowlr --batch-size 160 --workers 8 --gpus 2 --master-port 30341 --server-repair-epochs 1 --evaluate --classwise --no-eval-plots
{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/pseudogt_learnability/output/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/pseudogt_learnability/output/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/pseudogt_learnability/output/configs/server_phase2_orthogonal.yaml"
  }
}
Project root: /app/Object_Detection/pseudogt_learnability
Workspace: /app/Object_Detection/pseudogt_learnability/output
Warmup: /app/Object_Detection/pseudogt_learnability/output/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "weather": "highway",
      "scene": "highway",
      "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.txt",
      "images": 5000
    },
    {
      "id": 1,
      "weather": "citystreet",
      "scene": "city street",
      "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.txt",
      "images": 5000
    },
    {
      "id": 2,
      "weather": "residential",
      "scene": "residential",
      "list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.txt",
      "images": 5000
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/paper_eval_scene_total_val.txt",
    "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9864,
    "source_val_images": 738,
    "validation_target": "scene_total"
  }
}

=== Running variant: backbone_obj_safe ===
{
  "name": "backbone_obj_safe",
  "train_scope": "backbone",
  "aggregate_scope": "backbone",
  "epochs": 3,
  "lr0": 0.003,
  "nms_conf": 0.36,
  "low": 0.38,
  "mid": 0.62,
  "high": 0.92,
  "teacher": 0.3,
  "box": 0.005,
  "obj": 0.32,
  "cls": 0.02,
  "low_mid_obj_weight": 0.4,
  "mid_high_obj_weight": 0.85,
  "pseudo_bbox_uncertain": false,
  "pseudo_cls_uncertain": false,
  "orthogonal_weight": 0.0,
  "note": "Phase-1-like feature adaptation with uncertain boxes used mainly as objectness signal."
}
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30341 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_backbone_obj_safe_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_backbone_obj_safe_client0_highway_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 24776.11it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target' images and labels...5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<00:00, 8212.19it/s]
target: New cache created: /app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.cache
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 1948.90it/s]
val: New cache created: /app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client0_highway
Starting training for 3 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:07:26.323195833 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 02:07:26.344236454 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2      6.2G      2799       640         0         0         0  0.001674   0.01119 0.0001183  0.001799         0    0.9368      13.9     0.025:   3%|▎         | 1/32 [00:25<12:59, 25.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2948       640         0         0         0  0.001175   0.01112 0.0001102  0.001359         0    0.9402     13.74   0.01875:   6%|▋         | 2/32 [00:26<05:28, 10.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2700       640         0         0         0  0.001065   0.01156 0.0001081  0.001439         0     0.941     14.38   0.02083:   9%|▉         | 3/32 [00:27<03:06,  6.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2664       640         0         0         0 0.0007991   0.01169 8.108e-05  0.001079         0     0.943     14.72   0.01562:  12%|█▎        | 4/32 [00:28<02:00,  4.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2460       640         0         0         0 0.0007201   0.01157 7.982e-05  0.001033         0    0.9444     14.72     0.015:  16%|█▌        | 5/32 [00:29<01:22,  3.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2724       640         0         0         0 0.0007911   0.01135 8.935e-05  0.001181         0    0.9459     14.44   0.01667:  19%|█▉        | 6/32 [00:29<00:59,  2.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2722       640         0         0         0 0.0008367   0.01125 9.415e-05  0.001432         0    0.9462      14.2   0.01964:  22%|██▏       | 7/32 [00:30<00:45,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2680       640         0         0         0  0.000873   0.01132 9.763e-05  0.001461         0    0.9454      14.3   0.02031:  25%|██▌       | 8/32 [00:31<00:35,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3082       640         0         0         0 0.0008899   0.01105 9.829e-05  0.001656         0    0.9458     14.01   0.02222:  28%|██▊       | 9/32 [00:32<00:29,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2671       640         0         0         0  0.001079   0.01097 9.898e-05  0.001598         0    0.9454     13.77   0.02125:  31%|███▏      | 10/32 [00:33<00:24,  1.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3074       640         0         0         0  0.001145   0.01083 0.0001019  0.001543         0    0.9466     13.66   0.02045:  34%|███▍      | 11/32 [00:33<00:21,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3060       640         0         0         0  0.001099   0.01072 0.0001014  0.001502         0    0.9479     13.52   0.01979:  38%|███▊      | 12/32 [00:34<00:19,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.528      0.252      0.258      0.147

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.96it/s]

                 all        738      14937      0.569      0.358      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2744       640         0         0         0         0  0.005232         0         0         0    0.9737     4.625         0:   3%|▎         | 1/32 [00:00<00:24,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2713       640         0         0         0 0.0003924  0.004623 5.181e-05  0.001873         0    0.9741     3.981   0.00625:   6%|▋         | 2/32 [00:01<00:23,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2732       640         0         0         0 0.0004644  0.004709 5.791e-05  0.003306         0    0.9737     4.004    0.0125:   9%|▉         | 3/32 [00:02<00:22,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2672       640         0         0         0 0.0003483  0.004659 4.343e-05   0.00248         0    0.9706     3.853  0.009375:  12%|█▎        | 4/32 [00:03<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2702       640         0         0         0 0.0004002  0.004612 5.462e-05  0.002662         0    0.9718      3.82      0.01:  16%|█▌        | 5/32 [00:04<00:22,  1.22it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2971       640         0         0         0 0.0006281  0.004499 6.401e-05  0.002927         0     0.971     3.673   0.01042:  19%|█▉        | 6/32 [00:04<00:20,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2511       640         0         0         0 0.0005384  0.004402 5.487e-05  0.002509         0    0.9726     3.541  0.008929:  22%|██▏       | 7/32 [00:05<00:20,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2759       640         0         0         0 0.0006282  0.004438 6.231e-05  0.003475         0    0.9703     3.556    0.0125:  25%|██▌       | 8/32 [00:06<00:19,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2791       640         0         0         0 0.0006498  0.004352 6.211e-05  0.003626         0     0.971     3.449    0.0125:  28%|██▊       | 9/32 [00:07<00:18,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2907       640         0         0         0 0.0005849  0.004208  5.59e-05  0.003263         0    0.9712     3.326   0.01125:  31%|███▏      | 10/32 [00:07<00:17,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2904       640         0         0         0 0.0005317  0.004122 5.081e-05  0.002967         0    0.9712     3.219   0.01023:  34%|███▍      | 11/32 [00:08<00:16,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2352       640         0         0         0 0.0005669  0.003993 5.309e-05  0.003346         0    0.9706      3.09   0.01042:  38%|███▊      | 12/32 [00:09<00:15,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      3135       640         0         0         0  0.000582    0.0039 5.974e-05  0.003685         0      0.97     2.976   0.01058:  41%|████      | 13/32 [00:10<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      3105       640         0         0         0 0.0005404  0.003825 5.547e-05  0.003422         0    0.9702     2.891  0.009821:  44%|████▍     | 14/32 [00:11<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.348     0.0766     0.0926     0.0549

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.72it/s]

                 all        738      14937      0.578      0.354       0.38      0.207

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2889       640         0         0         0         0   0.00133         0         0         0    0.9811      0.65         0:   3%|▎         | 1/32 [00:00<00:24,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2961       640         0         0         0         0  0.001229         0         0         0    0.9787    0.5813         0:   3%|▎         | 1/32 [00:01<00:24,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2961       640         0         0         0         0  0.001229         0         0         0    0.9787    0.5813         0:   6%|▋         | 2/32 [00:01<00:23,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2945       640         0         0         0         0  0.001368         0         0         0    0.9809    0.6667         0:   9%|▉         | 3/32 [00:02<00:22,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2838       640         0         0         0         0   0.00132         0         0         0    0.9759    0.6531         0:  12%|█▎        | 4/32 [00:03<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2637       640         0         0         0         0  0.001304         0         0         0    0.9776      0.68         0:  16%|█▌        | 5/32 [00:03<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2775       640         0         0         0         0  0.001341         0         0         0    0.9759    0.6917         0:  19%|█▉        | 6/32 [00:04<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      3075       640         0         0         0         0  0.001321         0         0         0    0.9771    0.7036         0:  22%|██▏       | 7/32 [00:05<00:19,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2538       640         0         0         0         0  0.001349         0         0         0      0.98    0.7266         0:  25%|██▌       | 8/32 [00:06<00:18,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2655       640         0         0         0 8.348e-05  0.001332 7.486e-06  0.001984         0    0.9822    0.7236  0.001389:  28%|██▊       | 9/32 [00:07<00:17,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2652       640         0         0         0 7.513e-05  0.001314 6.737e-06  0.001786         0    0.9821    0.7175   0.00125:  31%|███▏      | 10/32 [00:07<00:17,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2667       640         0         0         0  0.000121   0.00131 1.241e-05  0.003339         0    0.9837    0.7125  0.002273:  34%|███▍      | 11/32 [00:08<00:16,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2885       640         0         0         0 0.0001109  0.001296 1.138e-05   0.00306         0    0.9819    0.7062  0.002083:  38%|███▊      | 12/32 [00:09<00:15,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2691       640         0         0         0 0.0001024   0.00132  1.05e-05  0.002825         0    0.9833    0.7115  0.001923:  41%|████      | 13/32 [00:10<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2968       640         0         0         0 9.507e-05  0.001313 9.754e-06  0.002623         0    0.9833    0.7134  0.001786:  44%|████▍     | 14/32 [00:10<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.472      0.148      0.149     0.0856

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.91it/s]

                 all        738      14937      0.584      0.349       0.38      0.207
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client0_highway/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client0_highway/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.548      0.363      0.379      0.209
                   0        738       1052      0.563      0.515       0.52      0.236
                   1        738         44      0.403     0.0455      0.131      0.058
                   2        738       8622      0.675      0.711      0.739      0.462
                   3        738        151      0.579      0.282      0.348      0.267
                   4        738        467      0.552      0.505      0.528      0.372
                   5        738         70      0.282      0.371      0.242      0.126
                   6        738         65      0.322     0.0308      0.143     0.0504
                   7        738       1619      0.524      0.581      0.557      0.224
                   8        738       2845      0.577      0.586      0.578      0.292
                   9        738          2          1          0   0.000274   0.000274

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client0_highway

3 epochs completed in 0.043 hours.
Destroying process group...
[rank0]:[W505 02:10:00.190272470 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30342 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_backbone_obj_safe_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_backbone_obj_safe_client1_citystreet_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target' images and labels...5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<00:00, 11223.11it/s]
target: New cache created: /app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.cache
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client1_citystreet
Starting training for 3 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:10:20.826996185 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 02:10:20.959565843 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2      6.2G      2799       640         0         0         0         0   0.01597         0         0         0    0.9472     20.16         0:   3%|▎         | 1/32 [00:24<12:41, 24.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2948       640         0         0         0 0.0003692   0.01586 4.308e-05 0.0003043         0     0.949     20.35   0.00625:   6%|▋         | 2/32 [00:25<05:21, 10.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2700       640         0         0         0 0.0005234   0.01632  6.53e-05 0.0008153         0    0.9442     20.37   0.01667:   9%|▉         | 3/32 [00:26<03:03,  6.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2664       640         0         0         0 0.0006842   0.01606 7.834e-05  0.001101         0    0.9413     20.06   0.02187:  12%|█▎        | 4/32 [00:27<01:58,  4.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2460       640         0         0         0 0.0005474   0.01594 6.267e-05 0.0008811         0    0.9402      19.8    0.0175:  16%|█▌        | 5/32 [00:28<01:21,  3.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2724       640         0         0         0 0.0004561   0.01579 5.223e-05 0.0007342         0    0.9413     19.72   0.01458:  19%|█▉        | 6/32 [00:29<00:58,  2.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2722       640         0         0         0 0.0005582   0.01582 6.154e-05 0.0008995         0    0.9419     19.74   0.01786:  22%|██▏       | 7/32 [00:30<00:45,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2680       640         0         0         0 0.0006175   0.01565 6.471e-05 0.0009638         0    0.9423     19.48   0.01875:  25%|██▌       | 8/32 [00:31<00:35,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3082       640         0         0         0 0.0006851   0.01556 6.697e-05     0.001         0    0.9428     19.46   0.01944:  28%|██▊       | 9/32 [00:31<00:29,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2671       640         0         0         0 0.0007359   0.01541 7.322e-05 0.0009733         0    0.9428     19.23   0.01875:  31%|███▏      | 10/32 [00:32<00:25,  1.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3074       640         0         0         0 0.0007123   0.01519 7.356e-05 0.0009502         0    0.9432     19.06   0.01818:  34%|███▍      | 11/32 [00:33<00:22,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3060       640         0         0         0 0.0007333   0.01509 7.577e-05 0.0009935         0    0.9439     18.89   0.01875:  38%|███▊      | 12/32 [00:34<00:19,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.552      0.214      0.226      0.128

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.84it/s]

                 all        738      14937       0.57      0.357      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2744       640         0         0         0         0    0.0062         0         0         0    0.9688      4.65         0:   3%|▎         | 1/32 [00:00<00:24,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2713       640         0         0         0         0   0.00603         0         0         0    0.9762     4.588         0:   6%|▋         | 2/32 [00:01<00:23,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2732       640         0         0         0 0.0003172  0.005651 4.047e-05  0.002381         0    0.9783     4.225  0.008333:   9%|▉         | 3/32 [00:02<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2672       640         0         0         0 0.0004308  0.005524 6.033e-05  0.002672         0    0.9743      4.05  0.009375:  12%|█▎        | 4/32 [00:03<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2702       640         0         0         0 0.0006069  0.005272 7.065e-05  0.002938         0    0.9725     3.865      0.01:  16%|█▌        | 5/32 [00:03<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2971       640         0         0         0 0.0007496    0.0052 7.879e-05  0.003102         0    0.9708     3.752   0.01042:  19%|█▉        | 6/32 [00:04<00:20,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2511       640         0         0         0 0.0006425  0.005129 6.754e-05  0.002659         0    0.9732      3.65  0.008929:  22%|██▏       | 7/32 [00:05<00:19,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2759       640         0         0         0 0.0005622  0.004967 5.909e-05  0.002326         0    0.9736     3.509  0.007812:  25%|██▌       | 8/32 [00:06<00:18,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2791       640         0         0         0 0.0004997  0.004813 5.253e-05  0.002068         0     0.972      3.35  0.006944:  28%|██▊       | 9/32 [00:07<00:18,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2907       640         0         0         0 0.0004497  0.004613 4.727e-05  0.001861         0    0.9698     3.183   0.00625:  31%|███▏      | 10/32 [00:07<00:17,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2904       640         0         0         0 0.0005702   0.00444 5.462e-05  0.002402         0    0.9705     3.039  0.006818:  34%|███▍      | 11/32 [00:08<00:16,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2352       640         0         0         0 0.0005227  0.004312 5.007e-05  0.002202         0    0.9722     2.902   0.00625:  38%|███▊      | 12/32 [00:09<00:15,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      3135       640         0         0         0 0.0005338  0.004156 5.131e-05  0.003602         0    0.9721     2.773  0.007692:  41%|████      | 13/32 [00:10<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      3105       640         0         0         0 0.0004957  0.004023 4.764e-05  0.003345         0    0.9732     2.644  0.007143:  44%|████▍     | 14/32 [00:11<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2491       640         0         0         0 0.0004627  0.003882 4.447e-05  0.003122         0    0.9749     2.516  0.006667:  47%|████▋     | 15/32 [00:11<00:13,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937     0.0588     0.0271     0.0392     0.0244

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.72it/s]

                 all        738      14937      0.573      0.355       0.38      0.207

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2889       640         0         0         0         0 0.0004861         0         0         0         1     0.075         0:   3%|▎         | 1/32 [00:00<00:23,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2961       640         0         0         0         0 0.0005513         0         0         0    0.9583    0.1063         0:   6%|▋         | 2/32 [00:01<00:23,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2945       640         0         0         0         0 0.0005183         0         0         0    0.8611   0.07917         0:   9%|▉         | 3/32 [00:02<00:22,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2838       640         0         0         0         0 0.0005064         0         0         0    0.8731   0.09063         0:  12%|█▎        | 4/32 [00:03<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2637       640         0         0         0         0 0.0004933         0         0         0    0.8985       0.1         0:  16%|█▌        | 5/32 [00:03<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2775       640         0         0         0         0 0.0004697         0         0         0    0.8916   0.09583         0:  19%|█▉        | 6/32 [00:04<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      3075       640         0         0         0         0 0.0004555         0         0         0    0.9071   0.08929         0:  19%|█▉        | 6/32 [00:05<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      3075       640         0         0         0         0 0.0004555         0         0         0    0.9071   0.08929         0:  22%|██▏       | 7/32 [00:05<00:19,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2538       640         0         0         0         0 0.0004328         0         0         0    0.9187   0.08125         0:  22%|██▏       | 7/32 [00:06<00:19,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2538       640         0         0         0         0 0.0004328         0         0         0    0.9187   0.08125         0:  25%|██▌       | 8/32 [00:06<00:18,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2655       640         0         0         0         0  0.000418         0         0         0    0.9277   0.08056         0:  25%|██▌       | 8/32 [00:06<00:18,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2655       640         0         0         0         0  0.000418         0         0         0    0.9277   0.08056         0:  28%|██▊       | 9/32 [00:06<00:17,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2652       640         0         0         0         0 0.0004111         0         0         0     0.935    0.0775         0:  31%|███▏      | 10/32 [00:07<00:17,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2667       640         0         0         0         0 0.0003935         0         0         0    0.9409   0.07386         0:  34%|███▍      | 11/32 [00:08<00:16,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2885       640         0         0         0         0  0.000381         0         0         0    0.9458   0.07083         0:  38%|███▊      | 12/32 [00:09<00:15,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2691       640         0         0         0         0 0.0003836         0         0         0      0.95   0.07115         0:  41%|████      | 13/32 [00:10<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2968       640         0         0         0         0 0.0003696         0         0         0    0.9535   0.06696         0:  41%|████      | 13/32 [00:10<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2968       640         0         0         0         0 0.0003696         0         0         0    0.9535   0.06696         0:  44%|████▍     | 14/32 [00:10<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937     0.0347     0.0231     0.0246     0.0134

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.86it/s]

                 all        738      14937      0.485      0.399      0.379      0.206
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client1_citystreet/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client1_citystreet/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]

                 all        738      14937      0.556      0.361      0.379      0.209
                   0        738       1052      0.569       0.51      0.519      0.236
                   1        738         44      0.444     0.0455      0.131     0.0582
                   2        738       8622      0.678       0.71      0.739      0.462
                   3        738        151      0.576      0.279      0.348      0.267
                   4        738        467      0.556      0.501       0.53      0.372
                   5        738         70      0.296      0.371      0.242      0.125
                   6        738         65      0.332     0.0308      0.145     0.0509
                   7        738       1619      0.524      0.577      0.557      0.224
                   8        738       2845      0.582      0.582      0.577      0.291
                   9        738          2          1          0   0.000274   0.000274

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client1_citystreet

3 epochs completed in 0.043 hours.
Destroying process group...
[rank0]:[W505 02:12:55.423804971 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30343 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_backbone_obj_safe_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_backbone_obj_safe_client2_residential_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target' images and labels...5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<00:00, 15323.73it/s]
target: New cache created: /app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.cache
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client2_residential
Starting training for 3 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:13:14.842658822 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:13:14.021571543 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2      6.2G      2799       640         0         0         0  0.001148   0.01439 0.0001266 0.0006579         0    0.9554        19    0.0125:   3%|▎         | 1/32 [00:24<12:51, 24.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2948       640         0         0         0 0.0009874   0.01447 0.0001261 0.0006351         0    0.9541     19.71    0.0125:   6%|▋         | 2/32 [00:25<05:25, 10.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2700       640         0         0         0  0.001011   0.01485 0.0001133  0.001006         0    0.9528     20.29   0.02083:   9%|▉         | 3/32 [00:26<03:05,  6.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2664       640         0         0         0 0.0008959   0.01465 0.0001016 0.0009101         0    0.9517     20.24   0.01875:  12%|█▎        | 4/32 [00:27<01:59,  4.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2460       640         0         0         0 0.0009732   0.01482 0.0001016 0.0008494         0    0.9517     20.31    0.0175:  16%|█▌        | 5/32 [00:28<01:21,  3.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2724       640         0         0         0  0.001031   0.01469 0.0001003 0.0009301         0    0.9527     20.05   0.01875:  19%|█▉        | 6/32 [00:29<00:59,  2.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2722       640         0         0         0  0.001023   0.01471 0.0001018  0.001071         0    0.9529     19.99   0.02143:  22%|██▏       | 7/32 [00:30<00:45,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2680       640         0         0         0  0.001067   0.01472 0.0001013  0.001094         0    0.9522     19.97   0.02187:  25%|██▌       | 8/32 [00:31<00:35,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3082       640         0         0         0  0.001069   0.01464 9.823e-05  0.001245         0    0.9519     20.02     0.025:  28%|██▊       | 9/32 [00:32<00:29,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      2671       640         0         0         0  0.001068   0.01454 9.809e-05  0.001331         0    0.9525      19.8   0.02625:  31%|███▏      | 10/32 [00:32<00:25,  1.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3074       640         0         0         0  0.001064   0.01453 9.826e-05  0.001377         0    0.9522     19.86   0.02727:  34%|███▍      | 11/32 [00:33<00:22,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     44.1G      3060       640         0         0         0  0.001065   0.01451 9.991e-05  0.001541         0    0.9524     19.76   0.03021:  38%|███▊      | 12/32 [00:34<00:19,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.499      0.329      0.305      0.173

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.95it/s]

                 all        738      14937      0.565       0.36      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2744       640         0         0         0 0.0007892   0.01013 0.0001013  0.001148         0     0.971     10.89    0.0125:   3%|▎         | 1/32 [00:00<00:25,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2713       640         0         0         0 0.0003946  0.009869 5.064e-05 0.0005741         0    0.9716     10.26   0.00625:   6%|▋         | 2/32 [00:01<00:24,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2732       640         0         0         0 0.0005321  0.009663 6.137e-05 0.0008236         0    0.9742     9.987  0.008333:   9%|▉         | 3/32 [00:02<00:23,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2672       640         0         0         0 0.0006792  0.009305 6.215e-05  0.001015         0    0.9726     9.459  0.009375:  12%|█▎        | 4/32 [00:03<00:22,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2702       640         0         0         0 0.0007057  0.009135 6.983e-05   0.00111         0    0.9731     9.242      0.01:  16%|█▌        | 5/32 [00:04<00:21,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2971       640         0         0         0 0.0006229  0.009003 6.499e-05  0.001209         0    0.9724     8.927   0.01042:  19%|█▉        | 6/32 [00:04<00:20,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2511       640         0         0         0 0.0005339  0.008951  5.57e-05  0.001036         0    0.9719     8.762  0.008929:  22%|██▏       | 7/32 [00:05<00:20,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2759       640         0         0         0 0.0005625  0.008822 5.868e-05  0.001119         0    0.9721     8.584  0.009375:  25%|██▌       | 8/32 [00:06<00:19,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2791       640         0         0         0 0.0005517   0.00866 6.039e-05  0.001202         0    0.9714     8.375  0.009722:  28%|██▊       | 9/32 [00:07<00:18,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2907       640         0         0         0 0.0006033  0.008416 6.627e-05  0.001316         0    0.9726     8.072      0.01:  31%|███▏      | 10/32 [00:08<00:17,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2904       640         0         0         0 0.0006369   0.00827 7.065e-05  0.001393         0    0.9726     7.864   0.01023:  34%|███▍      | 11/32 [00:08<00:16,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      2352       640         0         0         0 0.0006753  0.008091 8.039e-05  0.001954         0    0.9731     7.593    0.0125:  38%|███▊      | 12/32 [00:09<00:16,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      3135       640         0         0         0 0.0006234  0.007917 7.421e-05  0.001804         0    0.9732     7.329   0.01154:  41%|████      | 13/32 [00:10<00:15,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     41.7G      3105       640         0         0         0 0.0006156  0.007748 7.423e-05   0.00188         0     0.972     7.116   0.01161:  44%|████▍     | 14/32 [00:11<00:14,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.291     0.0773     0.0972     0.0591

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.93it/s]

                 all        738      14937      0.569      0.357      0.381      0.207

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2889       640         0         0         0         0  0.001841         0         0         0    0.9802     1.238         0:   3%|▎         | 1/32 [00:00<00:24,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2961       640         0         0         0         0  0.002092         0         0         0     0.967     1.263         0:   6%|▋         | 2/32 [00:01<00:23,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2945       640         0         0         0         0  0.002062         0         0         0    0.9682     1.254         0:   9%|▉         | 3/32 [00:02<00:22,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2838       640         0         0         0         0  0.002011         0         0         0    0.9761     1.228         0:  12%|█▎        | 4/32 [00:03<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2637       640         0         0         0         0   0.00206         0         0         0    0.9769      1.23         0:  16%|█▌        | 5/32 [00:03<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2775       640         0         0         0         0  0.002041         0         0         0    0.9792     1.242         0:  19%|█▉        | 6/32 [00:04<00:20,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      3075       640         0         0         0         0  0.002055         0         0         0    0.9779     1.238         0:  22%|██▏       | 7/32 [00:05<00:19,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2538       640         0         0         0         0  0.002101         0         0         0    0.9757     1.273         0:  25%|██▌       | 8/32 [00:06<00:18,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2655       640         0         0         0         0   0.00213         0         0         0    0.9775     1.297         0:  28%|██▊       | 9/32 [00:07<00:18,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2652       640         0         0         0         0  0.002169         0         0         0    0.9797     1.324         0:  31%|███▏      | 10/32 [00:07<00:17,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2667       640         0         0         0         0   0.00219         0         0         0    0.9788     1.349         0:  34%|███▍      | 11/32 [00:08<00:16,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2885       640         0         0         0         0  0.002228         0         0         0    0.9789     1.387         0:  38%|███▊      | 12/32 [00:09<00:15,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2691       640         0         0         0         0  0.002242         0         0         0    0.9793     1.396         0:  41%|████      | 13/32 [00:10<00:15,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2       42G      2968       640         0         0         0         0  0.002309         0         0         0    0.9786      1.44         0:  44%|████▍     | 14/32 [00:11<00:14,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.473      0.214       0.21      0.114

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.91it/s]

                 all        738      14937      0.583       0.35       0.38      0.207
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client2_residential/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client2_residential/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.26it/s]

                 all        738      14937      0.555      0.361      0.379      0.209
                   0        738       1052      0.568      0.509      0.519      0.236
                   1        738         44      0.445     0.0455      0.131     0.0567
                   2        738       8622      0.677       0.71      0.739      0.462
                   3        738        151      0.577       0.28      0.348      0.267
                   4        738        467      0.557      0.503       0.53      0.373
                   5        738         70      0.292      0.371      0.243      0.125
                   6        738         65      0.322     0.0295      0.144     0.0506
                   7        738       1619      0.525      0.578      0.558      0.224
                   8        738       2845      0.583      0.584      0.578      0.292
                   9        738          2          1          0   0.000275   0.000275

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_client2_residential

3 epochs completed in 0.044 hours.
Destroying process group...
[rank0]:[W505 02:15:50.424472219 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30344 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_backbone_obj_safe_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/global_checkpoints/backbone_obj_safe_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:16:06.402549253 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 02:16:06.446616924 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2681       640   0.03906   0.04618  0.005887     7.291:   3%|▎         | 1/31 [00:31<15:48, 31.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2783       640   0.03937   0.04701   0.00609     7.398:   6%|▋         | 2/31 [00:32<06:30, 13.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2561       640   0.03897   0.04617  0.006014     7.292:  10%|▉         | 3/31 [00:33<03:34,  7.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2150       640   0.03815   0.04433    0.0058     7.063:  13%|█▎        | 4/31 [00:33<02:13,  4.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2553       640   0.03783   0.04456  0.005796     7.055:  16%|█▌        | 5/31 [00:34<01:27,  3.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2464       640    0.0377   0.04437  0.005848     7.034:  19%|█▉        | 6/31 [00:35<01:00,  2.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2385       640   0.03761   0.04398  0.005895     6.999:  23%|██▎       | 7/31 [00:35<00:43,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2600       640   0.03738     0.044  0.005902     6.983:  26%|██▌       | 8/31 [00:36<00:32,  1.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2531       640   0.03732   0.04388  0.005817     6.962:  29%|██▉       | 9/31 [00:36<00:25,  1.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2596       640   0.03717   0.04396  0.005783     6.953:  32%|███▏      | 10/31 [00:37<00:20,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2752       640   0.03702   0.04398  0.005796     6.944:  35%|███▌      | 11/31 [00:37<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2346       640   0.03681   0.04363  0.005757     6.896:  39%|███▊      | 12/31 [00:38<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2450       640   0.03671   0.04367  0.005686     6.885:  42%|████▏     | 13/31 [00:39<00:12,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2451       640   0.03666   0.04349  0.005641     6.864:  45%|████▌     | 14/31 [00:39<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2384       640    0.0366   0.04334  0.005667     6.849:  48%|████▊     | 15/31 [00:40<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2379       640   0.03653   0.04316  0.005637     6.826:  52%|█████▏    | 16/31 [00:40<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2502       640    0.0365   0.04316  0.005593      6.82:  55%|█████▍    | 17/31 [00:41<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2691       640   0.03648   0.04318  0.005547     6.816:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2311       640   0.03636   0.04298  0.005495     6.787:  61%|██████▏   | 19/31 [00:42<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2730       640   0.03629   0.04315  0.005494     6.795:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2658       640   0.03625   0.04312  0.005501      6.79:  68%|██████▊   | 21/31 [00:43<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2454       640   0.03622   0.04317  0.005462     6.789:  71%|███████   | 22/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2520       640   0.03615   0.04317  0.005447     6.781:  74%|███████▍  | 23/31 [00:44<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2724       640    0.0361   0.04322  0.005426      6.78:  77%|███████▋  | 24/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2401       640   0.03606    0.0431  0.005418     6.766:  81%|████████  | 25/31 [00:46<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2566       640   0.03606   0.04311    0.0054     6.766:  84%|████████▍ | 26/31 [00:46<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.476       0.44      0.402      0.223
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.473      0.431        0.4      0.224
                   0        738       1052       0.48      0.563      0.537      0.256
                   1        738         44      0.338      0.136      0.141     0.0557
                   2        738       8622      0.586      0.758      0.752      0.483
                   3        738        151      0.346      0.404      0.383      0.296
                   4        738        467      0.467      0.597      0.547      0.395
                   5        738         70      0.266      0.457      0.279      0.128
                   6        738         65       0.21      0.123       0.17     0.0658
                   7        738       1619      0.513      0.629      0.582      0.241
                   8        738       2845      0.529      0.642       0.61       0.32
                   9        738          2          1          0   0.000308   0.000277

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_backbone_obj_safe_server_repair

1 epochs completed in 0.027 hours.
Destroying process group...
[rank0]:[W505 02:17:42.965366479 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

=== Running variant: neck_head_high_precision ===
{
  "name": "neck_head_high_precision",
  "train_scope": "neck_head",
  "aggregate_scope": "all",
  "epochs": 2,
  "lr0": 0.001,
  "nms_conf": 0.42,
  "low": 0.55,
  "mid": 0.74,
  "high": 0.9,
  "teacher": 0.22,
  "box": 0.015,
  "obj": 0.22,
  "cls": 0.06,
  "low_mid_obj_weight": 0.35,
  "mid_high_obj_weight": 0.8,
  "pseudo_bbox_uncertain": false,
  "pseudo_cls_uncertain": false,
  "orthogonal_weight": 0.0,
  "note": "Higher precision pseudo boxes for head adaptation with backbone frozen."
}
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30345 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_neck_head_high_precision_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_neck_head_high_precision_client0_highway_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client0_highway
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:18:01.258503232 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:18:01.536997208 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     7.51G      2799       640         0         0         0   0.00408  0.007637 0.0003434   0.02286         0    0.7099      8.75       0.2:   3%|▎         | 1/32 [00:20<10:46, 20.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2948       640         0         0         0  0.003775  0.007602 0.0003649   0.02044         0    0.7228     8.881    0.1813:   6%|▋         | 2/32 [00:21<04:31,  9.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2700       640         0         0         0  0.003774  0.007903 0.0004003   0.02018         0     0.727     9.312    0.1875:   9%|▉         | 3/32 [00:22<02:32,  5.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2664       640         0         0         0  0.003958  0.008032 0.0004056   0.02063         0     0.726     9.544    0.1969:  12%|█▎        | 4/32 [00:23<01:37,  3.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2460       640         0         0         0  0.003952  0.007964 0.0003968   0.02042         0     0.727     9.552     0.195:  16%|█▌        | 5/32 [00:23<01:06,  2.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2724       640         0         0         0  0.003921  0.007821 0.0003954   0.01947         0    0.7262     9.375    0.1833:  19%|█▉        | 6/32 [00:24<00:47,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2722       640         0         0         0  0.003804  0.007787 0.0003869   0.01979         0    0.7302     9.268    0.1839:  22%|██▏       | 7/32 [00:24<00:35,  1.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2680       640         0         0         0   0.00374   0.00785  0.000398   0.01926         0    0.7325     9.416    0.1813:  25%|██▌       | 8/32 [00:25<00:27,  1.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3082       640         0         0         0  0.003689  0.007701 0.0003914   0.01858         0    0.7319     9.214    0.1722:  28%|██▊       | 9/32 [00:26<00:22,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2671       640         0         0         0  0.003673  0.007668 0.0003885   0.01886         0    0.7335     9.113    0.1725:  31%|███▏      | 10/32 [00:26<00:19,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3074       640         0         0         0  0.003716  0.007586 0.0003875   0.01844         0    0.7345     9.084    0.1682:  34%|███▍      | 11/32 [00:27<00:16,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3060       640         0         0         0  0.003645   0.00753 0.0003822   0.01805         0    0.7344     9.005    0.1635:  38%|███▊      | 12/32 [00:27<00:14,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.553      0.361      0.368      0.195

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.97it/s]

                 all        738      14937      0.565      0.359      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2744       640         0         0         0         0  0.004364         0         0         0      0.72     4.725         0:   3%|▎         | 1/32 [00:00<00:17,  1.74it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2713       640         0         0         0  0.000815  0.004012 0.0002316  0.003333         0    0.7048     4.237    0.0125:   6%|▋         | 2/32 [00:01<00:17,  1.73it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2732       640         0         0         0  0.001224  0.004012 0.0002146  0.004925         0    0.7263     4.367   0.02083:   9%|▉         | 3/32 [00:01<00:16,  1.72it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2672       640         0         0         0 0.0009183  0.004026  0.000161  0.003694         0    0.7307     4.309   0.01562:  12%|█▎        | 4/32 [00:02<00:16,  1.72it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2702       640         0         0         0  0.001045  0.004021 0.0001812  0.004114         0    0.7313      4.31    0.0175:  16%|█▌        | 5/32 [00:03<00:17,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2971       640         0         0         0  0.001487  0.003977 0.0002052  0.004514         0    0.7358     4.231   0.01875:  19%|█▉        | 6/32 [00:03<00:16,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2511       640         0         0         0   0.00148  0.003949 0.0002071  0.005209         0    0.7375     4.198   0.02143:  22%|██▏       | 7/32 [00:04<00:15,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2759       640         0         0         0  0.001634  0.003977 0.0002165  0.005241         0    0.7374     4.245   0.02187:  25%|██▌       | 8/32 [00:04<00:14,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2791       640         0         0         0  0.001634  0.003919 0.0002128  0.005047         0    0.7351     4.171   0.02083:  28%|██▊       | 9/32 [00:05<00:13,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2907       640         0         0         0   0.00147  0.003855 0.0001915  0.004542         0    0.7281     4.074   0.01875:  31%|███▏      | 10/32 [00:05<00:13,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2904       640         0         0         0  0.001538  0.003828 0.0001892  0.004723         0    0.7291     4.051   0.01932:  34%|███▍      | 11/32 [00:06<00:12,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      2352       640         0         0         0   0.00141  0.003772 0.0001734   0.00433         0    0.7269      3.96   0.01771:  38%|███▊      | 12/32 [00:07<00:11,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      3135       640         0         0         0  0.001302  0.003734 0.0001601  0.003997         0    0.7258     3.903   0.01635:  41%|████      | 13/32 [00:07<00:11,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.9G      3105       640         0         0         0  0.001271  0.003731 0.0001568  0.003956         0    0.7231     3.885   0.01607:  44%|████▍     | 14/32 [00:08<00:10,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.509      0.356      0.336      0.168

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.70it/s]

                 all        738      14937      0.569      0.357      0.381      0.208
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client0_highway/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client0_highway/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.05it/s]

                 all        738      14937      0.548      0.363      0.379      0.208
                   0        738       1052      0.558      0.512      0.519      0.236
                   1        738         44      0.407     0.0455      0.131      0.057
                   2        738       8622      0.672      0.712      0.739      0.462
                   3        738        151       0.58      0.284      0.348      0.266
                   4        738        467      0.555      0.507       0.53      0.372
                   5        738         70      0.283      0.371      0.243      0.125
                   6        738         65      0.325     0.0308      0.143     0.0504
                   7        738       1619      0.522      0.579      0.558      0.224
                   8        738       2845      0.578      0.587      0.578      0.292
                   9        738          2          1          0   0.000277   0.000277

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client0_highway

2 epochs completed in 0.029 hours.
Destroying process group...
[rank0]:[W505 02:19:45.632390419 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30346 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_neck_head_high_precision_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_neck_head_high_precision_client1_citystreet_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client1_citystreet
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:20:04.988652298 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 02:20:04.116307020 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     7.51G      2799       640         0         0         0  0.003946   0.01053 0.0003846   0.01927         0    0.6491     11.67     0.225:   3%|▎         | 1/32 [00:20<10:45, 20.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2948       640         0         0         0  0.003702   0.01052  0.000382    0.0202         0    0.6678     12.05    0.2438:   6%|▋         | 2/32 [00:21<04:30,  9.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2700       640         0         0         0  0.003581   0.01085 0.0003677   0.01815         0     0.675     12.19    0.2208:   9%|▉         | 3/32 [00:22<02:32,  5.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2664       640         0         0         0  0.003551   0.01069 0.0003891   0.01771         0    0.6759        12    0.2125:  12%|█▎        | 4/32 [00:23<01:37,  3.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2460       640         0         0         0  0.003817   0.01063 0.0003974    0.0159         0    0.6818     11.91      0.19:  16%|█▌        | 5/32 [00:23<01:06,  2.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2724       640         0         0         0  0.003788   0.01053 0.0003898   0.01559         0    0.6835     11.85    0.1854:  19%|█▉        | 6/32 [00:24<00:47,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2722       640         0         0         0  0.003651   0.01057 0.0003842   0.01473         0    0.6831     11.84     0.175:  22%|██▏       | 7/32 [00:25<00:35,  1.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2680       640         0         0         0  0.003624   0.01048 0.0003794   0.01463         0    0.6844     11.71    0.1719:  25%|██▌       | 8/32 [00:25<00:28,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3082       640         0         0         0  0.003646   0.01043 0.0003943   0.01471         0    0.6879     11.77    0.1736:  28%|██▊       | 9/32 [00:26<00:22,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2671       640         0         0         0  0.003689   0.01033 0.0003922   0.01432         0    0.6894     11.63    0.1675:  31%|███▏      | 10/32 [00:26<00:19,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3074       640         0         0         0  0.003691   0.01018 0.0003917   0.01358         0    0.6894     11.48     0.158:  34%|███▍      | 11/32 [00:27<00:16,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3060       640         0         0         0  0.003677   0.01012 0.0003914   0.01336         0    0.6912     11.39    0.1542:  38%|███▊      | 12/32 [00:28<00:14,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.531      0.373      0.365      0.182

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.88it/s]

                 all        738      14937      0.568      0.358      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2744       640         0         0         0         0  0.006201         0         0         0    0.7396     6.213         0:   3%|▎         | 1/32 [00:00<00:18,  1.72it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2713       640         0         0         0         0  0.005872         0         0         0     0.736     5.912         0:   6%|▋         | 2/32 [00:01<00:17,  1.72it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2732       640         0         0         0 0.0005713   0.00571 7.208e-05 0.0008071         0    0.7305     5.663  0.004167:   9%|▉         | 3/32 [00:01<00:16,  1.72it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2672       640         0         0         0  0.001065  0.005599 0.0001218  0.002533         0    0.7247     5.463    0.0125:  12%|█▎        | 4/32 [00:02<00:18,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2702       640         0         0         0  0.001242  0.005531 0.0001379  0.002505         0    0.7291     5.415    0.0125:  16%|█▌        | 5/32 [00:03<00:16,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2971       640         0         0         0  0.001035  0.005549 0.0001149  0.002088         0    0.7281     5.369   0.01042:  19%|█▉        | 6/32 [00:03<00:15,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2511       640         0         0         0  0.001086  0.005548 0.0001257   0.00211         0    0.7283     5.396   0.01071:  22%|██▏       | 7/32 [00:04<00:15,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2759       640         0         0         0  0.001207  0.005485 0.0001304  0.002157         0    0.7309     5.352   0.01094:  25%|██▌       | 8/32 [00:04<00:14,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2791       640         0         0         0  0.001073  0.005454 0.0001159  0.001917         0    0.7301     5.313  0.009722:  28%|██▊       | 9/32 [00:05<00:13,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2907       640         0         0         0 0.0009655  0.005338 0.0001043  0.001725         0    0.7287     5.188   0.00875:  31%|███▏      | 10/32 [00:06<00:13,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2904       640         0         0         0 0.0008777  0.005278  9.48e-05  0.001569         0    0.7298     5.133  0.007955:  34%|███▍      | 11/32 [00:06<00:12,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2352       640         0         0         0 0.0009007  0.005227 0.0001014  0.001671         0    0.7307     5.077  0.008333:  38%|███▊      | 12/32 [00:07<00:11,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      3135       640         0         0         0  0.001006   0.00516 0.0001092  0.001989         0    0.7317     5.018  0.009615:  41%|████      | 13/32 [00:07<00:11,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      3105       640         0         0         0  0.001243  0.005118 0.0001212  0.002057         0    0.7305     4.963  0.009821:  44%|████▍     | 14/32 [00:08<00:10,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.507      0.334      0.316      0.152

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.76it/s]

                 all        738      14937      0.573      0.357      0.381      0.208
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client1_citystreet/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client1_citystreet/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.553       0.36      0.379      0.209
                   0        738       1052      0.571      0.504       0.52      0.236
                   1        738         44        0.4     0.0455      0.134     0.0604
                   2        738       8622      0.682      0.707      0.739      0.459
                   3        738        151      0.578      0.285      0.348      0.267
                   4        738        467      0.551      0.503       0.53      0.372
                   5        738         70      0.295      0.371      0.243      0.127
                   6        738         65      0.324     0.0308      0.144     0.0504
                   7        738       1619      0.534      0.573      0.558      0.224
                   8        738       2845      0.597       0.58      0.579      0.292
                   9        738          2          1          0   0.000273   0.000273

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client1_citystreet

2 epochs completed in 0.030 hours.
Destroying process group...
[rank0]:[W505 02:21:50.091619287 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30347 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_neck_head_high_precision_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_neck_head_high_precision_client2_residential_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client2_residential
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:22:10.507960945 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 02:22:10.554894017 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     7.51G      2799       640         0         0         0  0.002978  0.009746 0.0003693   0.01771         0     0.709        12    0.2125:   3%|▎         | 1/32 [00:21<11:05, 21.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2948       640         0         0         0  0.003747    0.0098  0.000482   0.01795         0    0.7131     12.53     0.225:   6%|▋         | 2/32 [00:22<04:39,  9.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2700       640         0         0         0  0.003727   0.01008 0.0004551   0.01851         0     0.716     13.02    0.2417:   9%|▉         | 3/32 [00:23<02:37,  5.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2664       640         0         0         0   0.00389   0.00994 0.0004264   0.01784         0    0.7138     12.93    0.2313:  12%|█▎        | 4/32 [00:23<01:40,  3.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2460       640         0         0         0  0.003861   0.01003 0.0004153   0.01594         0    0.7161     13.04    0.2075:  16%|█▌        | 5/32 [00:24<01:08,  2.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2724       640         0         0         0  0.003759  0.009958 0.0004083   0.01545         0    0.7197     12.95       0.2:  19%|█▉        | 6/32 [00:25<00:48,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2722       640         0         0         0  0.003624  0.009976  0.000395   0.01501         0     0.723     12.97    0.1946:  22%|██▏       | 7/32 [00:25<00:36,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2680       640         0         0         0  0.003623  0.009966 0.0003911   0.01578         0    0.7229      12.9    0.2031:  25%|██▌       | 8/32 [00:26<00:28,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3082       640         0         0         0  0.003614  0.009901 0.0003883   0.01584         0    0.7217     12.83    0.2028:  28%|██▊       | 9/32 [00:26<00:23,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      2671       640         0         0         0  0.003612  0.009822 0.0003832   0.01584         0    0.7227     12.65       0.2:  31%|███▏      | 10/32 [00:27<00:19,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3074       640         0         0         0  0.003551  0.009809 0.0003829   0.01536         0    0.7242     12.69    0.1943:  34%|███▍      | 11/32 [00:28<00:16,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     14.6G      3060       640         0         0         0  0.003552  0.009787 0.0003825   0.01553         0    0.7242     12.59    0.1948:  38%|███▊      | 12/32 [00:28<00:14,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.548      0.381      0.376      0.197

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.94it/s]

                 all        738      14937      0.565       0.36      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2744       640         0         0         0         0  0.006494         0         0         0    0.7484       7.4         0:   3%|▎         | 1/32 [00:00<00:18,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2713       640         0         0         0         0  0.006311         0         0         0    0.7649     7.231         0:   6%|▋         | 2/32 [00:01<00:17,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2732       640         0         0         0 0.0006458  0.006256 7.355e-05 0.0006127         0    0.7553     7.087  0.004167:   9%|▉         | 3/32 [00:01<00:16,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2672       640         0         0         0  0.001254  0.006084 0.0001196  0.001004         0    0.7455      6.75   0.00625:  12%|█▎        | 4/32 [00:02<00:16,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2702       640         0         0         0  0.001319     0.006 0.0001675  0.001208         0    0.7374     6.635    0.0075:  16%|█▌        | 5/32 [00:02<00:15,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2971       640         0         0         0  0.002051   0.00595 0.0002965  0.001713         0    0.7387     6.512   0.01042:  19%|█▉        | 6/32 [00:03<00:15,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2511       640         0         0         0  0.001758  0.005906 0.0002541  0.001468         0    0.7338     6.441  0.008929:  22%|██▏       | 7/32 [00:04<00:14,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2759       640         0         0         0  0.001538  0.005875 0.0002223  0.001285         0    0.7323     6.409  0.007812:  25%|██▌       | 8/32 [00:04<00:14,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2791       640         0         0         0  0.001649  0.005831 0.0002192  0.001847         0    0.7281     6.354   0.01111:  28%|██▊       | 9/32 [00:05<00:13,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2907       640         0         0         0  0.001711  0.005746 0.0002163  0.001899         0    0.7275     6.246   0.01125:  31%|███▏      | 10/32 [00:05<00:12,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2904       640         0         0         0  0.001784  0.005688 0.0002185  0.002166         0    0.7246     6.149    0.0125:  34%|███▍      | 11/32 [00:06<00:12,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      2352       640         0         0         0  0.001636  0.005614 0.0002003  0.001985         0    0.7226     6.043   0.01146:  38%|███▊      | 12/32 [00:07<00:11,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      3135       640         0         0         0   0.00151  0.005537 0.0001849  0.001832         0    0.7212     5.944   0.01058:  41%|████      | 13/32 [00:07<00:11,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     14.8G      3105       640         0         0         0  0.001489  0.005494 0.0001865  0.001873         0    0.7203     5.891   0.01071:  44%|████▍     | 14/32 [00:08<00:10,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.557      0.337      0.344      0.172

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.73it/s]

                 all        738      14937      0.573      0.357      0.381      0.208
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client2_residential/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client2_residential/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]

                 all        738      14937      0.557      0.359      0.379      0.209
                   0        738       1052      0.572      0.505       0.52      0.236
                   1        738         44      0.439     0.0455      0.133      0.058
                   2        738       8622      0.685      0.707      0.739      0.462
                   3        738        151       0.58      0.285      0.348      0.267
                   4        738        467      0.554      0.505      0.529      0.372
                   5        738         70      0.285      0.357      0.242      0.125
                   6        738         65      0.331     0.0308      0.143     0.0501
                   7        738       1619       0.53      0.574      0.559      0.225
                   8        738       2845      0.594      0.582       0.58      0.293
                   9        738          2          1          0   0.000274   0.000274

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_client2_residential

2 epochs completed in 0.030 hours.
Destroying process group...
[rank0]:[W505 02:23:56.109183817 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30348 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_neck_head_high_precision_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/global_checkpoints/neck_head_high_precision_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:24:13.776793838 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 02:24:13.119671908 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2681       640   0.03909   0.04628  0.005906     7.302:   3%|▎         | 1/31 [00:34<17:00, 34.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2783       640    0.0394   0.04709  0.006099     7.407:   6%|▋         | 2/31 [00:34<06:59, 14.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2561       640   0.03899   0.04625  0.006022     7.301:  10%|▉         | 3/31 [00:35<03:49,  8.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2150       640   0.03817   0.04441  0.005811     7.071:  13%|█▎        | 4/31 [00:36<02:22,  5.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2553       640   0.03783   0.04463  0.005804     7.061:  16%|█▌        | 5/31 [00:36<01:32,  3.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2464       640    0.0377   0.04444  0.005854     7.039:  19%|█▉        | 6/31 [00:37<01:03,  2.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2385       640   0.03761   0.04405  0.005901     7.005:  23%|██▎       | 7/31 [00:38<00:45,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2600       640   0.03738   0.04406  0.005906     6.988:  26%|██▌       | 8/31 [00:38<00:34,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2531       640   0.03733   0.04394   0.00582     6.967:  29%|██▉       | 9/31 [00:39<00:26,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2596       640   0.03717   0.04401  0.005786     6.957:  32%|███▏      | 10/31 [00:39<00:21,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2752       640   0.03702   0.04404  0.005799     6.948:  35%|███▌      | 11/31 [00:40<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2346       640   0.03681   0.04368  0.005758       6.9:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2450       640   0.03671   0.04372  0.005686     6.889:  42%|████▏     | 13/31 [00:41<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2451       640   0.03666   0.04354  0.005641     6.867:  45%|████▌     | 14/31 [00:42<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2384       640    0.0366   0.04338  0.005667     6.852:  48%|████▊     | 15/31 [00:42<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2379       640   0.03653    0.0432  0.005636     6.829:  52%|█████▏    | 16/31 [00:43<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2502       640   0.03649   0.04319  0.005592     6.822:  55%|█████▍    | 17/31 [00:43<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2691       640   0.03648   0.04321  0.005546     6.819:  58%|█████▊    | 18/31 [00:44<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2311       640   0.03636   0.04302  0.005494      6.79:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2730       640   0.03629   0.04319  0.005492     6.798:  65%|██████▍   | 20/31 [00:45<00:06,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2658       640   0.03625   0.04316  0.005499     6.792:  68%|██████▊   | 21/31 [00:46<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2454       640   0.03623    0.0432   0.00546     6.791:  71%|███████   | 22/31 [00:46<00:05,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2520       640   0.03615    0.0432  0.005446     6.784:  74%|███████▍  | 23/31 [00:47<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2724       640    0.0361   0.04325  0.005424     6.782:  77%|███████▋  | 24/31 [00:47<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2401       640   0.03606   0.04313  0.005416     6.768:  81%|████████  | 25/31 [00:48<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2566       640   0.03606   0.04313  0.005398     6.768:  84%|████████▍ | 26/31 [00:49<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.473      0.443      0.401      0.223
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.22it/s]

                 all        738      14937      0.475      0.431        0.4      0.224
                   0        738       1052      0.481      0.558      0.536      0.255
                   1        738         44      0.338      0.136       0.14     0.0558
                   2        738       8622      0.588      0.757      0.751      0.483
                   3        738        151      0.352      0.411      0.384      0.295
                   4        738        467      0.464      0.593      0.546      0.394
                   5        738         70      0.267      0.457      0.277      0.128
                   6        738         65      0.207      0.121      0.171     0.0654
                   7        738       1619      0.515      0.631      0.583      0.242
                   8        738       2845      0.534      0.642       0.61       0.32
                   9        738          2          1          0   0.000314   0.000282

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_neck_head_high_precision_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 02:25:52.107069521 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

=== Running variant: all_consistency_lowlr ===
{
  "name": "all_consistency_lowlr",
  "train_scope": "all",
  "aggregate_scope": "all",
  "epochs": 2,
  "lr0": 0.0008,
  "nms_conf": 0.38,
  "low": 0.45,
  "mid": 0.68,
  "high": 0.88,
  "teacher": 0.24,
  "box": 0.012,
  "obj": 0.25,
  "cls": 0.05,
  "low_mid_obj_weight": 0.35,
  "mid_high_obj_weight": 0.8,
  "pseudo_bbox_uncertain": false,
  "pseudo_cls_uncertain": false,
  "orthogonal_weight": 0.0001,
  "note": "Conservative full-model adaptation with low LR and non-backbone orthogonal regularization."
}
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30349 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_all_consistency_lowlr_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_all_consistency_lowlr_client0_highway_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_0_highway_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client0_highway
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:26:13.331310147 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:26:13.584792805 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     7.87G      2799       640         0         0         0  0.003616  0.008645 0.0003366   0.05568         0    0.8237     11.45    0.6375:   3%|▎         | 1/32 [00:34<17:54, 34.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2948       640         0         0         0  0.003485  0.008596 0.0003328   0.05476         0    0.8282     11.41     0.625:   6%|▋         | 2/32 [00:36<07:42, 15.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2700       640         0         0         0  0.003452  0.008938 0.0003404   0.05542         0    0.8214     11.87    0.6583:   9%|▉         | 3/32 [00:38<04:22,  9.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2664       640         0         0         0  0.003482  0.009079 0.0003505    0.0548         0    0.8219     12.15    0.6656:  12%|█▎        | 4/32 [00:39<02:49,  6.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2460       640         0         0         0  0.003509  0.009012 0.0003584   0.05356         0    0.8247     12.19    0.6525:  16%|█▌        | 5/32 [00:40<01:56,  4.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2724       640         0         0         0  0.003499  0.008841 0.0003516   0.05222         0     0.824     11.94     0.625:  19%|█▉        | 6/32 [00:42<01:25,  3.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2722       640         0         0         0  0.003411  0.008787 0.0003456   0.05354         0    0.8246     11.75    0.6286:  22%|██▏       | 7/32 [00:43<01:05,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2680       640         0         0         0  0.003341  0.008844 0.0003479   0.05228         0    0.8273      11.9    0.6203:  25%|██▌       | 8/32 [00:44<00:52,  2.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3082       640         0         0         0  0.003312  0.008655 0.0003484   0.05257         0    0.8258     11.64    0.6097:  28%|██▊       | 9/32 [00:45<00:43,  1.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2671       640         0         0         0   0.00331  0.008602  0.000346   0.05284         0    0.8282     11.49     0.605:  31%|███▏      | 10/32 [00:47<00:37,  1.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3074       640         0         0         0   0.00332  0.008508 0.0003577   0.05174         0    0.8317     11.45    0.5909:  34%|███▍      | 11/32 [00:48<00:32,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3060       640         0         0         0  0.003258   0.00843 0.0003529   0.05225         0    0.8324     11.34    0.5906:  38%|███▊      | 12/32 [00:49<00:29,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.516      0.394      0.366        0.2

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.86it/s]

                 all        738      14937      0.564       0.36      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      2744       640         0         0         0  0.002176  0.004864 0.0002842   0.01895         0    0.8636     5.938    0.1125:   3%|▎         | 1/32 [00:01<00:44,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2713       640         0         0         0  0.002472  0.004485 0.0003055   0.02827         0    0.8545     5.463      0.15:   6%|▋         | 2/32 [00:02<00:40,  1.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2732       640         0         0         0  0.002529  0.004509 0.0003154   0.02924         0    0.8643     5.513    0.1583:   9%|▉         | 3/32 [00:03<00:37,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2672       640         0         0         0  0.002453  0.004537 0.0003098   0.02916         0    0.8657     5.431    0.1562:  12%|█▎        | 4/32 [00:05<00:35,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2702       640         0         0         0  0.002477  0.004559  0.000304    0.0286         0    0.8686     5.482     0.155:  16%|█▌        | 5/32 [00:06<00:34,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2971       640         0         0         0  0.002506  0.004504 0.0002991    0.0286         0     0.872     5.371    0.1521:  19%|█▉        | 6/32 [00:07<00:32,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2511       640         0         0         0  0.002448  0.004468 0.0002922   0.02694         0    0.8759     5.338    0.1429:  22%|██▏       | 7/32 [00:08<00:31,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2759       640         0         0         0  0.002513   0.00453 0.0002867   0.02591         0    0.8762     5.425    0.1391:  25%|██▌       | 8/32 [00:10<00:30,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2791       640         0         0         0  0.002461  0.004473 0.0002903    0.0253         0    0.8781     5.367    0.1347:  28%|██▊       | 9/32 [00:11<00:28,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2907       640         0         0         0  0.002585  0.004402 0.0002852   0.02439         0    0.8788     5.293    0.1288:  31%|███▏      | 10/32 [00:12<00:27,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2904       640         0         0         0  0.002558  0.004389 0.0002853   0.02356         0    0.8795     5.258    0.1239:  34%|███▍      | 11/32 [00:13<00:26,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      2352       640         0         0         0  0.002526  0.004328 0.0002861   0.02287         0    0.8791     5.159    0.1188:  38%|███▊      | 12/32 [00:15<00:24,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      3135       640         0         0         0  0.002488   0.00429 0.0002846   0.02222         0    0.8776     5.098    0.1144:  41%|████      | 13/32 [00:16<00:23,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     44.5G      3105       640         0         0         0  0.002447  0.004301 0.0002814   0.02185         0    0.8781       5.1    0.1125:  44%|████▍     | 14/32 [00:17<00:22,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.552      0.319      0.324      0.176

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.92it/s]

                 all        738      14937      0.568      0.358      0.381      0.208
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client0_highway/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client0_highway/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.29it/s]

                 all        738      14937      0.551      0.361      0.379      0.209
                   0        738       1052      0.563       0.51       0.52      0.236
                   1        738         44        0.4     0.0455      0.134     0.0588
                   2        738       8622      0.684      0.708      0.739      0.462
                   3        738        151       0.58      0.283      0.348      0.267
                   4        738        467      0.555      0.503      0.528      0.372
                   5        738         70      0.282      0.371       0.24      0.126
                   6        738         65      0.323     0.0308      0.142      0.049
                   7        738       1619      0.529      0.576      0.559      0.224
                   8        738       2845      0.595      0.581      0.578      0.292
                   9        738          2          1          0   0.000275   0.000275

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client0_highway

2 epochs completed in 0.048 hours.
Destroying process group...
[rank0]:[W505 02:29:05.083822562 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30350 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_all_consistency_lowlr_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_all_consistency_lowlr_client1_citystreet_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_1_citystreet_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client1_citystreet
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:29:25.466154134 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[rank0]:[W505 02:29:25.874395666 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     7.87G      2799       640         0         0         0  0.003359   0.01206 0.0003223   0.04758         0    0.8083     16.29     0.775:   3%|▎         | 1/32 [00:33<17:21, 33.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2948       640         0         0         0  0.003171   0.01201 0.0003131   0.04602         0    0.8092     16.44    0.7563:   6%|▋         | 2/32 [00:35<07:22, 14.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2700       640         0         0         0  0.003109   0.01242 0.0003083   0.04468         0    0.8114     16.51    0.7375:   9%|▉         | 3/32 [00:36<04:11,  8.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2664       640         0         0         0  0.003105   0.01225 0.0003214   0.04367         0    0.8112     16.23    0.7094:  12%|█▎        | 4/32 [00:38<02:43,  5.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2460       640         0         0         0  0.003209   0.01216 0.0003251   0.04265         0    0.8086     15.97    0.6825:  16%|█▌        | 5/32 [00:39<01:53,  4.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2724       640         0         0         0  0.003239   0.01205 0.0003298    0.0411         0    0.8108     15.87    0.6542:  19%|█▉        | 6/32 [00:40<01:23,  3.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2722       640         0         0         0  0.003175   0.01208 0.0003264   0.04077         0    0.8129      15.9      0.65:  22%|██▏       | 7/32 [00:41<01:04,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2680       640         0         0         0  0.003175   0.01196  0.000329   0.04185         0    0.8119     15.69    0.6563:  25%|██▌       | 8/32 [00:43<00:52,  2.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3082       640         0         0         0  0.003174   0.01189 0.0003362   0.04115         0    0.8149      15.7    0.6458:  28%|██▊       | 9/32 [00:44<00:44,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2671       640         0         0         0  0.003165   0.01176 0.0003322   0.04143         0    0.8144     15.49    0.6413:  31%|███▏      | 10/32 [00:45<00:37,  1.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3074       640         0         0         0   0.00314    0.0116 0.0003329   0.04198         0    0.8138     15.28    0.6398:  34%|███▍      | 11/32 [00:47<00:33,  1.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3060       640         0         0         0  0.003124   0.01152 0.0003319   0.04157         0     0.815     15.13    0.6281:  38%|███▊      | 12/32 [00:48<00:29,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.555      0.363      0.358      0.192

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.85it/s]

                 all        738      14937      0.566      0.359      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.8G      2744       640         0         0         0   0.00162  0.006684 0.0001987  0.004926         0     0.859     7.612    0.0375:   3%|▎         | 1/32 [00:01<00:44,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2713       640         0         0         0  0.001661  0.006378 0.0002167  0.009555         0    0.8729     7.331   0.06875:   6%|▋         | 2/32 [00:03<00:45,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2732       640         0         0         0  0.001759    0.0062 0.0002452  0.008293         0    0.8718     7.054   0.05833:   9%|▉         | 3/32 [00:04<00:40,  1.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2672       640         0         0         0  0.001819  0.006077 0.0002451  0.009275         0    0.8666     6.825    0.0625:  12%|█▎        | 4/32 [00:05<00:37,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2702       640         0         0         0  0.001768  0.006006 0.0002382  0.009328         0    0.8718      6.77    0.0625:  16%|█▌        | 5/32 [00:06<00:35,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2971       640         0         0         0  0.001883   0.00602 0.0002646   0.01069         0    0.8697     6.712   0.07083:  19%|█▉        | 6/32 [00:08<00:33,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2511       640         0         0         0  0.001939  0.006004 0.0002601   0.01073         0    0.8686     6.732   0.07143:  22%|██▏       | 7/32 [00:09<00:32,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2759       640         0         0         0  0.001929  0.005934 0.0002542   0.01091         0    0.8719     6.661   0.07187:  25%|██▌       | 8/32 [00:10<00:30,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2791       640         0         0         0  0.001883  0.005902 0.0002439   0.01014         0    0.8716     6.615   0.06667:  28%|██▊       | 9/32 [00:11<00:29,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2907       640         0         0         0  0.001805   0.00578 0.0002384  0.009881         0    0.8672     6.451   0.06375:  31%|███▏      | 10/32 [00:13<00:27,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2904       640         0         0         0  0.001809  0.005722  0.000238  0.009594         0    0.8666     6.372   0.06136:  34%|███▍      | 11/32 [00:14<00:26,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2352       640         0         0         0  0.001757  0.005672 0.0002317  0.009566         0    0.8673     6.291   0.06042:  38%|███▊      | 12/32 [00:15<00:25,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      3135       640         0         0         0   0.00179  0.005598 0.0002326  0.009948         0    0.8669     6.204   0.06154:  41%|████      | 13/32 [00:16<00:23,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      3105       640         0         0         0  0.001889  0.005566  0.000232  0.009556         0    0.8672     6.161   0.05893:  44%|████▍     | 14/32 [00:18<00:22,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.48      0.329      0.299       0.16

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.93it/s]

                 all        738      14937      0.573      0.356      0.381      0.208
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client1_citystreet/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client1_citystreet/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.555       0.36      0.379      0.209
                   0        738       1052      0.573      0.504      0.519      0.235
                   1        738         44      0.409     0.0455      0.133       0.06
                   2        738       8622      0.684      0.707      0.739      0.462
                   3        738        151      0.578      0.285      0.348      0.267
                   4        738        467      0.555      0.503       0.53      0.372
                   5        738         70      0.295      0.371       0.24      0.125
                   6        738         65      0.323     0.0308      0.144     0.0507
                   7        738       1619      0.535      0.573      0.558      0.224
                   8        738       2845      0.597       0.58      0.579      0.293
                   9        738          2          1          0   0.000273   0.000273

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client1_citystreet

2 epochs completed in 0.049 hours.
Destroying process group...
[rank0]:[W505 02:32:20.167353890 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30351 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_all_consistency_lowlr_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/
Model summary: 478 layers, 47566599 parameters, 47566599 gradients

Transferred 612/619 items from /app/Object_Detection/pseudogt_learnability/output/client_states/pl01_all_consistency_lowlr_client2_residential_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
target: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/client_2_residential_target.cache' for images and labels... 5000 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client2_residential
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:32:41.779666390 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:32:41.086188812 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/models/assigner/yolo_anchor_assigner.py:690: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  score = t[:,6].T
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     7.87G      2799       640         0         0         0   0.00291   0.01104  0.000337   0.04845         0    0.8277     15.74    0.7625:   3%|▎         | 1/32 [00:32<16:46, 32.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2948       640         0         0         0  0.003266   0.01112 0.0003632   0.05054         0    0.8264      16.3     0.825:   6%|▋         | 2/32 [00:34<07:09, 14.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2700       640         0         0         0  0.003336   0.01143 0.0003568    0.0501         0    0.8321     16.88    0.8458:   9%|▉         | 3/32 [00:35<04:05,  8.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2664       640         0         0         0  0.003416   0.01127 0.0003471   0.04973         0    0.8341     16.83    0.8375:  12%|█▎        | 4/32 [00:37<02:39,  5.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2460       640         0         0         0  0.003384   0.01139 0.0003441   0.04876         0    0.8363     16.92     0.825:  16%|█▌        | 5/32 [00:38<01:51,  4.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2724       640         0         0         0  0.003336   0.01129 0.0003382   0.04883         0    0.8387     16.73    0.8167:  19%|█▉        | 6/32 [00:39<01:22,  3.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2722       640         0         0         0  0.003267   0.01131 0.0003339   0.04841         0    0.8401     16.67    0.8071:  22%|██▏       | 7/32 [00:41<01:04,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2680       640         0         0         0  0.003241   0.01131 0.0003303   0.04805         0    0.8395     16.58    0.7969:  25%|██▌       | 8/32 [00:42<00:51,  2.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3082       640         0         0         0  0.003242   0.01124 0.0003266   0.04784         0    0.8372     16.51    0.7903:  28%|██▊       | 9/32 [00:43<00:43,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      2671       640         0         0         0  0.003228   0.01114 0.0003254   0.04821         0    0.8363     16.27    0.7837:  31%|███▏      | 10/32 [00:44<00:37,  1.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3074       640         0         0         0  0.003213   0.01112 0.0003279   0.04823         0    0.8377     16.29    0.7852:  34%|███▍      | 11/32 [00:46<00:32,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     44.2G      3060       640         0         0         0  0.003194    0.0111 0.0003336   0.04772         0    0.8379     16.17    0.7719:  38%|███▊      | 12/32 [00:47<00:29,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.577      0.363      0.374        0.2

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.95it/s]

                 all        738      14937      0.566      0.359      0.381      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1037: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss    ss_box    ss_obj    ss_cls        tp    fp_cls    fp_loc   pse_num    gt_num
  0%|          | 0/32 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.8G      2744       640         0         0         0  0.002447  0.007724 0.0002643  0.006579         0    0.8696       9.5    0.0625:   3%|▎         | 1/32 [00:01<00:44,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2713       640         0         0         0  0.002516  0.007545 0.0002629  0.008979         0    0.8769     9.144   0.08125:   6%|▋         | 2/32 [00:02<00:41,  1.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2732       640         0         0         0  0.002383  0.007438 0.0002458   0.01108         0    0.8802     9.096       0.1:   9%|▉         | 3/32 [00:04<00:38,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2672       640         0         0         0  0.002567  0.007251 0.0002586   0.01153         0    0.8784     8.759       0.1:  12%|█▎        | 4/32 [00:05<00:36,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2702       640         0         0         0  0.002531  0.007196 0.0002504   0.01069         0    0.8763     8.715    0.0925:  16%|█▌        | 5/32 [00:06<00:34,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2971       640         0         0         0  0.002522  0.007142 0.0002502   0.01077         0    0.8796     8.569   0.09167:  19%|█▉        | 6/32 [00:07<00:33,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2511       640         0         0         0  0.002519  0.007144  0.000247    0.0107         0    0.8773     8.557   0.09107:  22%|██▏       | 7/32 [00:09<00:31,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2759       640         0         0         0  0.002526  0.007128 0.0002401   0.01028         0    0.8779     8.559    0.0875:  25%|██▌       | 8/32 [00:10<00:30,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2791       640         0         0         0  0.002425  0.007109 0.0002307   0.01027         0    0.8776     8.557    0.0875:  28%|██▊       | 9/32 [00:11<00:28,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2907       640         0         0         0  0.002391  0.007033 0.0002289  0.009923         0    0.8781     8.441   0.08375:  31%|███▏      | 10/32 [00:12<00:27,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2904       640         0         0         0  0.002382  0.006988 0.0002274   0.01082         0    0.8765     8.364   0.08977:  34%|███▍      | 11/32 [00:14<00:26,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      2352       640         0         0         0  0.002318  0.006919 0.0002259   0.01157         0    0.8743     8.245   0.09375:  38%|███▊      | 12/32 [00:15<00:25,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      3135       640         0         0         0  0.002266  0.006847 0.0002257   0.01124         0    0.8734     8.139   0.09038:  41%|████      | 13/32 [00:16<00:24,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     43.4G      3105       640         0         0         0  0.002306  0.006819 0.0002765   0.01127         0    0.8729     8.094   0.09018:  44%|████▍     | 14/32 [00:17<00:22,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1423: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/ssod_trainer.py:1388: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.577      0.322      0.339      0.177

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:02<00:00,  1.92it/s]

                 all        738      14937      0.574      0.357      0.381      0.208
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client2_residential/weights/last.pt, 95.8MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client2_residential/weights/best.pt, 95.8MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 417 layers, 47549639 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.554      0.361      0.379      0.209
                   0        738       1052      0.567      0.506       0.52      0.237
                   1        738         44      0.422     0.0455      0.133     0.0577
                   2        738       8622      0.684      0.707      0.739      0.462
                   3        738        151      0.579      0.285      0.348      0.267
                   4        738        467      0.554      0.505       0.53      0.372
                   5        738         70       0.29      0.371      0.241      0.125
                   6        738         65      0.326     0.0308      0.142     0.0501
                   7        738       1619      0.528      0.574      0.559      0.224
                   8        738       2845      0.593      0.582      0.579      0.293
                   9        738          2          1          0   0.000274   0.000274

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_client2_residential

2 epochs completed in 0.047 hours.
Destroying process group...
[rank0]:[W505 02:35:30.578219444 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30352 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/configs/pl01_all_consistency_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/global_checkpoints/all_consistency_lowlr_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 02:35:47.835891740 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 02:35:47.847151137 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2681       640   0.03904   0.04625  0.005904     7.295:   3%|▎         | 1/31 [00:32<16:22, 32.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2783       640   0.03934   0.04707  0.006097     7.401:   6%|▋         | 2/31 [00:33<06:44, 13.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2561       640   0.03894   0.04622   0.00602     7.294:  10%|▉         | 3/31 [00:34<03:44,  8.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2150       640   0.03812   0.04439  0.005809     7.065:  13%|█▎        | 4/31 [00:35<02:19,  5.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2553       640   0.03779   0.04461  0.005802     7.056:  16%|█▌        | 5/31 [00:35<01:31,  3.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2464       640   0.03767   0.04442  0.005852     7.035:  19%|█▉        | 6/31 [00:36<01:02,  2.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2385       640   0.03758   0.04403  0.005899     7.001:  23%|██▎       | 7/31 [00:37<00:45,  1.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2600       640   0.03735   0.04404  0.005905     6.984:  26%|██▌       | 8/31 [00:37<00:33,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2531       640    0.0373   0.04392  0.005819     6.963:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2596       640   0.03715   0.04399  0.005785     6.954:  32%|███▏      | 10/31 [00:38<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2752       640     0.037   0.04402  0.005798     6.945:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2346       640   0.03679   0.04367  0.005757     6.897:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2450       640   0.03669    0.0437  0.005685     6.886:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2451       640   0.03664   0.04352   0.00564     6.864:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2384       640   0.03658   0.04337  0.005666      6.85:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2379       640   0.03652   0.04318  0.005636     6.827:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2502       640   0.03648   0.04318  0.005591      6.82:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2691       640   0.03647    0.0432  0.005545     6.817:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2311       640   0.03635     0.043  0.005493     6.788:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2730       640   0.03628   0.04317  0.005491     6.796:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2658       640   0.03624   0.04314  0.005499      6.79:  68%|██████▊   | 21/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2454       640   0.03621   0.04319   0.00546     6.789:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2520       640   0.03614   0.04319  0.005445     6.782:  74%|███████▍  | 23/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2724       640   0.03609   0.04324  0.005423     6.781:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2401       640   0.03605   0.04312  0.005415     6.767:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2566       640   0.03606   0.04313  0.005398     6.766:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.49       0.43      0.402      0.223
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.475      0.431        0.4      0.224
                   0        738       1052      0.481      0.559      0.536      0.255
                   1        738         44      0.337      0.136      0.142     0.0561
                   2        738       8622      0.588      0.756      0.751      0.483
                   3        738        151      0.351      0.411      0.384      0.294
                   4        738        467      0.465      0.593      0.547      0.394
                   5        738         70      0.268      0.457      0.277      0.128
                   6        738         65       0.21      0.123      0.171     0.0657
                   7        738       1619      0.514      0.631      0.584      0.242
                   8        738       2845      0.535      0.643      0.611       0.32
                   9        738          2          1          0   0.000307   0.000276

Results saved to /app/Object_Detection/pseudogt_learnability/output/runs/pl01_all_consistency_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 02:37:27.495293841 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Saved: /app/Object_Detection/pseudogt_learnability/output/stats/01_checkpoints.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/stats/01_manifest.json
/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/pseudogt_learnability/scripts/evaluate_scene_protocol.py --workspace /app/Object_Detection/pseudogt_learnability/output --splits highway,citystreet,residential,total --batch-size 16 --no-plots --verbose --checkpoint warmup_global=/app/Object_Detection/pseudogt_learnability/output/global_checkpoints/round000_warmup.pt --checkpoint backbone_obj_safe_client0_highway=/app/Object_Detection/pseudogt_learnability/output/checkpoints/backbone_obj_safe_client0_highway.pt --checkpoint backbone_obj_safe_client1_citystreet=/app/Object_Detection/pseudogt_learnability/output/checkpoints/backbone_obj_safe_client1_citystreet.pt --checkpoint backbone_obj_safe_client2_residential=/app/Object_Detection/pseudogt_learnability/output/checkpoints/backbone_obj_safe_client2_residential.pt --checkpoint backbone_obj_safe_aggregate_backbone=/app/Object_Detection/pseudogt_learnability/output/checkpoints/backbone_obj_safe_aggregate_backbone.pt --checkpoint backbone_obj_safe_server_repair=/app/Object_Detection/pseudogt_learnability/output/checkpoints/backbone_obj_safe_server_repair.pt --checkpoint neck_head_high_precision_client0_highway=/app/Object_Detection/pseudogt_learnability/output/checkpoints/neck_head_high_precision_client0_highway.pt --checkpoint neck_head_high_precision_client1_citystreet=/app/Object_Detection/pseudogt_learnability/output/checkpoints/neck_head_high_precision_client1_citystreet.pt --checkpoint neck_head_high_precision_client2_residential=/app/Object_Detection/pseudogt_learnability/output/checkpoints/neck_head_high_precision_client2_residential.pt --checkpoint neck_head_high_precision_aggregate_all=/app/Object_Detection/pseudogt_learnability/output/checkpoints/neck_head_high_precision_aggregate_all.pt --checkpoint neck_head_high_precision_server_repair=/app/Object_Detection/pseudogt_learnability/output/checkpoints/neck_head_high_precision_server_repair.pt --checkpoint all_consistency_lowlr_client0_highway=/app/Object_Detection/pseudogt_learnability/output/checkpoints/all_consistency_lowlr_client0_highway.pt --checkpoint all_consistency_lowlr_client1_citystreet=/app/Object_Detection/pseudogt_learnability/output/checkpoints/all_consistency_lowlr_client1_citystreet.pt --checkpoint all_consistency_lowlr_client2_residential=/app/Object_Detection/pseudogt_learnability/output/checkpoints/all_consistency_lowlr_client2_residential.pt --checkpoint all_consistency_lowlr_aggregate_all=/app/Object_Detection/pseudogt_learnability/output/checkpoints/all_consistency_lowlr_aggregate_all.pt --checkpoint all_consistency_lowlr_server_repair=/app/Object_Detection/pseudogt_learnability/output/checkpoints/all_consistency_lowlr_server_repair.pt
Saved: /app/Object_Detection/pseudogt_learnability/output/validation_reports/paper_protocol_eval_manifest.json
Saved: /app/Object_Detection/pseudogt_learnability/output/validation_reports/paper_protocol_eval_summary.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/validation_reports/paper_protocol_classwise_summary.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/validation_reports/paper_protocol_eval_summary.md

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_pseudogt_learnability_01.py', '--variants', 'backbone_obj_safe,neck_head_high_precision,all_consistency_lowlr', '--batch-size', '160', '--workers', '8', '--gpus', '2', '--master-port', '30341', '--server-repair-epochs', '1', '--evaluate', '--classwise', '--no-eval-plots'], returncode=0)

## Check generated checkpoints

In [5]:
import pandas as pd

checkpoint_table = PROJECT_ROOT / "output" / "stats" / "01_checkpoints.csv"
if checkpoint_table.exists():
    ckpts = pd.read_csv(checkpoint_table)
    display(ckpts)
else:
    print("No checkpoint table yet:", checkpoint_table)

,label,kind,variant,client,path
0,warmup_global,warmup,NaN,NaN,/app/Object_Detection/pseudogt_learnability/ou...
1,backbone_obj_safe_client0_highway,client,backbone_obj_safe,client0_highway,/app/Object_Detection/pseudogt_learnability/ou...
2,backbone_obj_safe_client1_citystreet,client,backbone_obj_safe,client1_citystreet,/app/Object_Detection/pseudogt_learnability/ou...
3,backbone_obj_safe_client2_residential,client,backbone_obj_safe,client2_residential,/app/Object_Detection/pseudogt_learnability/ou...
4,backbone_obj_safe_aggregate_backbone,aggregate,backbone_obj_safe,NaN,/app/Object_Detection/pseudogt_learnability/ou...
5,backbone_obj_safe_server_repair,server_repair,backbone_obj_safe,NaN,/app/Object_Detection/pseudogt_learnability/ou...
6,neck_head_high_precision_client0_highway,client,neck_head_high_precision,client0_highway,/app/Object_Detection/pseudogt_learnability/ou...
7,neck_head_high_precision_client1_citystreet,client,neck_head_high_precision,client1_citystreet,/app/Object_Detection/pseudogt_learnability/ou...
8,neck_head_high_precision_client2_residential,client,neck_head_high_precision,client2_residential,/app/Object_Detection/pseudogt_learnability/ou...
9,neck_head_high_precision_aggregate_all,aggregate,neck_head_high_precision,NaN,/app/Object_Detection/pseudogt_learnability/ou...
10,neck_head_high_precision_server_repair,server_repair,neck_head_high_precision,NaN,/app/Object_Detection/pseudogt_learnability/ou...
11,all_consistency_lowlr_client0_highway,client,all_consistency_lowlr,client0_highway,/app/Object_Detection/pseudogt_learnability/ou...
12,all_consistency_lowlr_client1_citystreet,client,all_consistency_lowlr,client1_citystreet,/app/Object_Detection/pseudogt_learnability/ou...
13,all_consistency_lowlr_client2_residential,client,all_consistency_lowlr,client2_residential,/app/Object_Detection/pseudogt_learnability/ou...
14,all_consistency_lowlr_aggregate_all,aggregate,all_consistency_lowlr,NaN,/app/Object_Detection/pseudogt_learnability/ou...
15,all_consistency_lowlr_server_repair,server_repair,all_consistency_lowlr,NaN,/app/Object_Detection/pseudogt_learnability/ou...

## Evaluation summary

The key metric is whether any pseudo-GT profile beats
`warmup_global` on `total` mAP@0.5:0.95, or at least improves the
matching client scene without damaging the total split.

In [6]:
import pandas as pd

summary_csv = PROJECT_ROOT / "output" / "validation_reports" / "paper_protocol_eval_summary.csv"
if not summary_csv.exists():
    print("Evaluation summary is not available yet:", summary_csv)
else:
    df = pd.read_csv(summary_csv)
    ok = df[df["status"].eq("ok")].copy()
    total = ok[ok["split"].isin(["total", "scene_total"])].copy()
    total = total.sort_values("map50_95", ascending=False)
    display(total[["checkpoint_label", "split", "precision", "recall", "map50", "map50_95"]])

    warm = total[total["checkpoint_label"].eq("warmup_global")]
    if not warm.empty:
        base = float(warm.iloc[0]["map50_95"])
        total["delta_map50_95_vs_warmup"] = total["map50_95"].astype(float) - base
        display(total[["checkpoint_label", "map50", "map50_95", "delta_map50_95_vs_warmup"]])

,checkpoint_label,split,precision,recall,map50,map50_95
23,backbone_obj_safe_server_repair,scene_total,0.491,0.393,0.376,0.208
63,all_consistency_lowlr_server_repair,scene_total,0.493,0.393,0.376,0.208
43,neck_head_high_precision_server_repair,scene_total,0.492,0.393,0.376,0.208
19,backbone_obj_safe_aggregate_backbone,scene_total,0.461,0.381,0.351,0.189
3,warmup_global,scene_total,0.532,0.337,0.352,0.189
39,neck_head_high_precision_aggregate_all,scene_total,0.534,0.337,0.352,0.189
59,all_consistency_lowlr_aggregate_all,scene_total,0.534,0.338,0.352,0.189

,checkpoint_label,map50,map50_95,delta_map50_95_vs_warmup
23,backbone_obj_safe_server_repair,0.376,0.208,0.019
63,all_consistency_lowlr_server_repair,0.376,0.208,0.019
43,neck_head_high_precision_server_repair,0.376,0.208,0.019
19,backbone_obj_safe_aggregate_backbone,0.351,0.189,0.000
3,warmup_global,0.352,0.189,0.000
39,neck_head_high_precision_aggregate_all,0.352,0.189,0.000
59,all_consistency_lowlr_aggregate_all,0.352,0.189,0.000

## Scene-specific client learnability

This view is useful even if the aggregate is weak.  If a client
improves its own scene split, pseudo-GT may still be learnable, and
the aggregation rule is the next target.  If no client improves its
own split, the pseudo-GT training recipe itself is the bottleneck.

In [7]:
if summary_csv.exists():
    ok = pd.read_csv(summary_csv)
    ok = ok[ok["status"].eq("ok")].copy()
    scene_rows = ok[ok["split"].isin(["highway", "citystreet", "residential"])].copy()
    display(scene_rows.sort_values(["split", "map50_95"], ascending=[True, False])[
        ["checkpoint_label", "split", "precision", "recall", "map50", "map50_95"]
    ])

,checkpoint_label,split,precision,recall,map50,map50_95
21,backbone_obj_safe_server_repair,citystreet,0.490,0.398,0.381,0.210
41,neck_head_high_precision_server_repair,citystreet,0.491,0.399,0.381,0.210
61,all_consistency_lowlr_server_repair,citystreet,0.490,0.400,0.381,0.210
1,warmup_global,citystreet,0.528,0.342,0.357,0.191
17,backbone_obj_safe_aggregate_backbone,citystreet,0.461,0.387,0.357,0.191
37,neck_head_high_precision_aggregate_all,citystreet,0.533,0.342,0.357,0.191
57,all_consistency_lowlr_aggregate_all,citystreet,0.533,0.342,0.357,0.191
20,backbone_obj_safe_server_repair,highway,0.514,0.341,0.336,0.186
40,neck_head_high_precision_server_repair,highway,0.519,0.340,0.336,0.186
60,all_consistency_lowlr_server_repair,highway,0.519,0.340,0.336,0.186
0,warmup_global,highway,0.581,0.298,0.308,0.168
36,neck_head_high_precision_aggregate_all,highway,0.581,0.298,0.309,0.168
56,all_consistency_lowlr_aggregate_all,highway,0.580,0.298,0.309,0.168
16,backbone_obj_safe_aggregate_backbone,highway,0.485,0.295,0.307,0.167
22,backbone_obj_safe_server_repair,residential,0.449,0.429,0.412,0.234
42,neck_head_high_precision_server_repair,residential,0.459,0.419,0.412,0.234
62,all_consistency_lowlr_server_repair,residential,0.453,0.426,0.412,0.234
2,warmup_global,residential,0.434,0.406,0.388,0.214
18,backbone_obj_safe_aggregate_backbone,residential,0.443,0.401,0.387,0.214
38,neck_head_high_precision_aggregate_all,residential,0.436,0.403,0.388,0.214
58,all_consistency_lowlr_aggregate_all,residential,0.435,0.404,0.388,0.214

## Discord notification

In [8]:
try:
    sys.path.insert(0, str(PROJECT_ROOT.parent))
    from notebook_notify import notify_discord

    msg = "PseudoGT Learnability 01 finished. Check output/validation_reports/paper_protocol_eval_summary.md"
    result = notify_discord(
        msg,
        title="PseudoGT Learnability 01",
        context={"project": str(PROJECT_ROOT)},
        fail_silently=True,
    )
    print(result)
except Exception as exc:
    print("Discord notification skipped:", exc)

DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)