# 02 Stable PseudoGT Learnability

01 still used the online EfficientTeacher confidence pipeline.  02
changes the pseudo-GT source itself: a single warmup teacher predicts
each target image under two views, identity and horizontal flip, and
only de-augmented boxes that remain spatially stable are written as
offline YOLO labels.

## Hypothesis

Phase2 gets worse because confidence is an insufficient localization
quality signal.  A pseudo box should supervise bbox regression only
when the teacher localizes it consistently under a label-preserving
augmentation.  The training set is therefore:

- source labeled cloudy images, as the same supervised anchor used by
  FedSTO/DQA clients
- stable target pseudo labels from the same scene-client target lists
- no second teacher and no GT-based checkpoint selection

In [1]:
from pathlib import Path
import os
import subprocess
import sys

cwd = Path.cwd().resolve()
if cwd.name == "notebooks":
    PROJECT_ROOT = cwd.parent
elif (cwd / "pseudogt_learnability").exists():
    PROJECT_ROOT = cwd / "pseudogt_learnability"
else:
    PROJECT_ROOT = cwd
os.chdir(PROJECT_ROOT)
WORKSPACE = PROJECT_ROOT / "output" / "02_stable_pseudogt"
print(PROJECT_ROOT)
print(WORKSPACE)
print((PROJECT_ROOT / "checkpoints" / "round000_warmup.pt").exists())

/app/Object_Detection/pseudogt_learnability
/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt
True

## Setup Check

This creates/reuses the scene-client lists and copies the warmup
checkpoint into the 02 workspace.

In [2]:
subprocess.run([
    sys.executable,
    "scripts/run_pseudogt_learnability_02.py",
    "--workspace-root", str(WORKSPACE),
    "--setup-only",
], check=True)

{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/server_phase2_orthogonal.yaml"
  }
}
Project root: /app/Object_Detection/pseudogt_learnability
Workspace: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt
Warmup: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "weather": "highway",
      "scene": "highway"
    },
    {
      "id": 1,
      "weather": "citystreet",
      "scene": "city street"
    },
    {
      "id": 2,
      "weather": "residential",
      "scene": "residential"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_total_val.txt",
    "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9864,
    "source_val_images": 738,
    "validation_target": "scene_total"
  }
}
Setup complete.

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_pseudogt_learnability_02.py', '--workspace-root', '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt', '--setup-only'], returncode=0)

## Run 02

`MAX_IMAGES_PER_CLIENT = 0` means the full 5000-image target list per
client.  For a short probe, set it to something like `1200` and rerun
with `--force-pseudo` when changing thresholds.

In [3]:
MAX_IMAGES_PER_CLIENT = 0
VARIANTS = "stable_mix_backbone,stable_mix_all_lowlr"

cmd = [
    sys.executable,
    "scripts/run_pseudogt_learnability_02.py",
    "--workspace-root", str(WORKSPACE),
    "--variants", VARIANTS,
    "--batch-size", "160",
    "--workers", "8",
    "--gpus", "2",
    "--master-port", "30421",
    "--server-repair-epochs", "1",
    "--evaluate",
    "--classwise",
    "--no-eval-plots",
]
if MAX_IMAGES_PER_CLIENT > 0:
    cmd.extend(["--max-images-per-client", str(MAX_IMAGES_PER_CLIENT)])
print(" ".join(cmd))
subprocess.run(cmd, check=True)

/root/micromamba/envs/al_yolov8/bin/python scripts/run_pseudogt_learnability_02.py --workspace-root /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt --variants stable_mix_backbone,stable_mix_all_lowlr --batch-size 160 --workers 8 --gpus 2 --master-port 30421 --server-repair-epochs 1 --evaluate --classwise --no-eval-plots
{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/server_phase2_orthogonal.yaml"
  }
}
Project root: /app/Object_Detection/pseudogt_learnability
Workspace: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt
Warmup: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "weather": "highway",
      "scene": "highway"
    },
    {
      "id": 1,
      "weather": "citystreet",
      "scene": "city street"
    },
    {
      "id": 2,
      "weather": "residential",
      "scene": "residential"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/paper_eval_scene_total_val.txt",
    "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9864,
    "source_val_images": 738,
    "validation_target": "scene_total"
  }
}

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

client0_highway: pseudo scan 1/5000 images, kept 7 boxes
client0_highway: pseudo scan 250/5000 images, kept 3146 boxes
client0_highway: pseudo scan 500/5000 images, kept 6202 boxes
client0_highway: pseudo scan 750/5000 images, kept 9345 boxes
client0_highway: pseudo scan 1000/5000 images, kept 12592 boxes
client0_highway: pseudo scan 1250/5000 images, kept 15709 boxes
client0_highway: pseudo scan 1500/5000 images, kept 18831 boxes
client0_highway: pseudo scan 1750/5000 images, kept 22087 boxes
client0_highway: pseudo scan 2000/5000 images, kept 25100 boxes
client0_highway: pseudo scan 2250/5000 images, kept 28147 boxes
client0_highway: pseudo scan 2500/5000 images, kept 31428 boxes
client0_highway: pseudo scan 2750/5000 images, kept 34443 boxes
client0_highway: pseudo scan 3000/5000 images, kept 37764 boxes
client0_highway: pseudo scan 3250/5000 images, kept 40912 boxes
client0_highway: pseudo scan 3500/5000 images, kept 44026 boxes
client0_highway: pseudo scan 3750/5000 images, kept 47083 boxes
client0_highway: pseudo scan 4000/5000 images, kept 49965 boxes
client0_highway: pseudo scan 4250/5000 images, kept 53039 boxes
client0_highway: pseudo scan 4500/5000 images, kept 56189 boxes
client0_highway: pseudo scan 4750/5000 images, kept 59394 boxes
client0_highway: pseudo scan 5000/5000 images, kept 62538 boxes
{
  "client": "client0_highway",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4984,
  "pseudo_boxes_kept": 56681,
  "boxes_per_kept_image": 11.372592295345104,
  "mean_conf": 0.5796814884945302,
  "mean_stability": 0.896062644291306,
  "mean_score": 0.5281277162950374,
  "class_counts": {
    "0": 777,
    "2": 34396,
    "3": 218,
    "4": 1402,
    "5": 69,
    "7": 4111,
    "8": 15708
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client0_highway_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/stats/02_client0_highway_stable_boxes.csv"
}
client1_citystreet: pseudo scan 1/5000 images, kept 7 boxes
client1_citystreet: pseudo scan 250/5000 images, kept 4438 boxes
client1_citystreet: pseudo scan 500/5000 images, kept 8953 boxes
client1_citystreet: pseudo scan 750/5000 images, kept 13629 boxes
client1_citystreet: pseudo scan 1000/5000 images, kept 18005 boxes
client1_citystreet: pseudo scan 1250/5000 images, kept 22508 boxes
client1_citystreet: pseudo scan 1500/5000 images, kept 27140 boxes
client1_citystreet: pseudo scan 1750/5000 images, kept 32019 boxes
client1_citystreet: pseudo scan 2000/5000 images, kept 36472 boxes
client1_citystreet: pseudo scan 2250/5000 images, kept 41090 boxes
client1_citystreet: pseudo scan 2500/5000 images, kept 45440 boxes
client1_citystreet: pseudo scan 2750/5000 images, kept 49847 boxes
client1_citystreet: pseudo scan 3000/5000 images, kept 54424 boxes
client1_citystreet: pseudo scan 3250/5000 images, kept 58901 boxes
client1_citystreet: pseudo scan 3500/5000 images, kept 63609 boxes
client1_citystreet: pseudo scan 3750/5000 images, kept 68340 boxes
client1_citystreet: pseudo scan 4000/5000 images, kept 72840 boxes
client1_citystreet: pseudo scan 4250/5000 images, kept 77650 boxes
client1_citystreet: pseudo scan 4500/5000 images, kept 82056 boxes
client1_citystreet: pseudo scan 4750/5000 images, kept 86583 boxes
client1_citystreet: pseudo scan 5000/5000 images, kept 91008 boxes
{
  "client": "client1_citystreet",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4998,
  "pseudo_boxes_kept": 91008,
  "boxes_per_kept_image": 18.20888355342137,
  "mean_conf": 0.5303256618371168,
  "mean_stability": 0.8803911310890441,
  "mean_score": 0.4757282054428157,
  "class_counts": {
    "0": 7596,
    "1": 1,
    "2": 47871,
    "3": 462,
    "4": 1692,
    "5": 509,
    "7": 14931,
    "8": 17946
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client1_citystreet_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/stats/02_client1_citystreet_stable_boxes.csv"
}
client2_residential: pseudo scan 1/5000 images, kept 10 boxes
client2_residential: pseudo scan 250/5000 images, kept 3828 boxes
client2_residential: pseudo scan 500/5000 images, kept 7750 boxes
client2_residential: pseudo scan 750/5000 images, kept 11566 boxes
client2_residential: pseudo scan 1000/5000 images, kept 15167 boxes
client2_residential: pseudo scan 1250/5000 images, kept 18730 boxes
client2_residential: pseudo scan 1500/5000 images, kept 22441 boxes
client2_residential: pseudo scan 1750/5000 images, kept 26203 boxes
client2_residential: pseudo scan 2000/5000 images, kept 29848 boxes
client2_residential: pseudo scan 2250/5000 images, kept 33710 boxes
client2_residential: pseudo scan 2500/5000 images, kept 37354 boxes
client2_residential: pseudo scan 2750/5000 images, kept 41093 boxes
client2_residential: pseudo scan 3000/5000 images, kept 45021 boxes
client2_residential: pseudo scan 3250/5000 images, kept 48674 boxes
client2_residential: pseudo scan 3500/5000 images, kept 52284 boxes
client2_residential: pseudo scan 3750/5000 images, kept 55931 boxes
client2_residential: pseudo scan 4000/5000 images, kept 59929 boxes
client2_residential: pseudo scan 4250/5000 images, kept 63808 boxes
client2_residential: pseudo scan 4500/5000 images, kept 67732 boxes
client2_residential: pseudo scan 4750/5000 images, kept 71538 boxes
client2_residential: pseudo scan 5000/5000 images, kept 75390 boxes
{
  "client": "client2_residential",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4994,
  "pseudo_boxes_kept": 59808,
  "boxes_per_kept_image": 11.975971165398478,
  "mean_conf": 0.6342728652751174,
  "mean_stability": 0.9002707910974629,
  "mean_score": 0.5785057248904588,
  "class_counts": {
    "0": 1889,
    "1": 1,
    "2": 41465,
    "3": 165,
    "4": 867,
    "5": 301,
    "7": 4807,
    "8": 10313
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client2_residential_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/stats/02_client2_residential_stable_boxes.csv"
}
Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/stats/02_pseudo_label_stats.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/stats/02_pseudo_label_stats.json

=== Running variant: stable_mix_backbone ===
{
  "name": "stable_mix_backbone",
  "train_scope": "backbone",
  "aggregate_scope": "backbone",
  "epochs": 3,
  "lr0": 0.0025,
  "pseudo_repeat": 1,
  "source_repeat": 1,
  "orthogonal_weight": 0.0,
  "note": "Source-anchored, Phase-1-like backbone adaptation with stable pseudo target boxes."
}
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30421 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_backbone_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/client_states/pl02_stable_mix_backbone_client0_highway_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client0_highway_stable_train' images and labels...5377 found, 4488 missing, 0 empty, 0 corrupted: 100%|██████████| 9865/9865 [00:00<00:00, 11601.49it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client0_highway_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.366421176219447
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client0_highway_stable_train.cache' images and labels... 5377 found, 4488 missing, 0 empty, 0 corrupted: 100%|██████████| 9865/9865 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 10721.96it/s]
val: New cache created: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client0_highway
Starting training for 3 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 02:58:01.894596030 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 02:58:01.898641259 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/59 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     4.99G      1368       640    0.0389   0.04341  0.004976     6.983:   2%|▏         | 1/59 [00:25<24:56, 25.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1314       640   0.03868   0.04308  0.005062     6.946:   3%|▎         | 2/59 [00:26<10:40, 11.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1345       640   0.03919   0.04287   0.00548     7.003:   5%|▌         | 3/59 [00:27<06:02,  6.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1202       640   0.03882   0.04223   0.00587     6.953:   7%|▋         | 4/59 [00:28<03:51,  4.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1406       640   0.03891   0.04165   0.00582      6.91:   8%|▊         | 5/59 [00:28<02:36,  2.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1275       640   0.03873   0.04065  0.005836     6.818:  10%|█         | 6/59 [00:29<01:50,  2.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1354       640   0.03865   0.03982  0.005875     6.748:  12%|█▏        | 7/59 [00:30<01:22,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1499       640   0.03848   0.03942   0.00579     6.695:  14%|█▎        | 8/59 [00:30<01:03,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1426       640   0.03851   0.03928  0.005803     6.687:  15%|█▌        | 9/59 [00:31<00:51,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1180       640   0.03841   0.03876  0.005809     6.638:  17%|█▋        | 10/59 [00:31<00:43,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1473       640   0.03833   0.03839  0.005804     6.603:  19%|█▊        | 11/59 [00:32<00:37,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1428       640   0.03833   0.03817  0.005796     6.583:  20%|██        | 12/59 [00:32<00:33,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1399       640   0.03828   0.03769  0.005809     6.543:  22%|██▏       | 13/59 [00:33<00:30,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1379       640   0.03832   0.03741  0.005881     6.529:  24%|██▎       | 14/59 [00:33<00:28,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1307       640   0.03823   0.03713  0.005891       6.5:  25%|██▌       | 15/59 [00:34<00:26,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1333       640    0.0381   0.03679  0.005871     6.461:  27%|██▋       | 16/59 [00:34<00:25,  1.72it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1250       640   0.03806   0.03638  0.005855     6.423:  29%|██▉       | 17/59 [00:35<00:23,  1.75it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1268       640   0.03809   0.03615  0.005886      6.41:  31%|███       | 18/59 [00:35<00:23,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1188       640   0.03802   0.03586  0.005866      6.38:  32%|███▏      | 19/59 [00:36<00:22,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1706       640   0.03807   0.03597  0.005865     6.392:  34%|███▍      | 20/59 [00:37<00:21,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1340       640   0.03798    0.0358  0.005863     6.372:  36%|███▌      | 21/59 [00:37<00:20,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1104       640    0.0379   0.03549  0.005853     6.339:  37%|███▋      | 22/59 [00:38<00:20,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1232       640   0.03787   0.03528   0.00583     6.319:  39%|███▉      | 23/59 [00:38<00:19,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1424       640   0.03793   0.03512  0.005843     6.312:  41%|████      | 24/59 [00:39<00:19,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1437       640   0.03784   0.03502  0.005836     6.295:  42%|████▏     | 25/59 [00:39<00:18,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1324       640   0.03782   0.03491  0.005818     6.283:  44%|████▍     | 26/59 [00:40<00:18,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.502      0.396      0.378      0.206

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/59 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1357       640   0.03633   0.02781  0.005765     5.592:   2%|▏         | 1/59 [00:00<00:31,  1.86it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1412       640   0.03673   0.02935  0.005857     5.755:   3%|▎         | 2/59 [00:01<00:30,  1.85it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1255       640   0.03664   0.02874  0.005624     5.681:   5%|▌         | 3/59 [00:01<00:30,  1.85it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1502       640   0.03678   0.02932  0.005691     5.743:   7%|▋         | 4/59 [00:02<00:29,  1.84it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1291       640   0.03663   0.02899   0.00561     5.699:   8%|▊         | 5/59 [00:02<00:29,  1.84it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1249       640   0.03671   0.02844  0.005657     5.665:  10%|█         | 6/59 [00:03<00:28,  1.84it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1422       640   0.03683   0.02872  0.005619     5.694:  12%|█▏        | 7/59 [00:03<00:28,  1.84it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1192       640   0.03688   0.02845  0.005545      5.67:  14%|█▎        | 8/59 [00:04<00:27,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1410       640   0.03687   0.02861  0.005562     5.684:  15%|█▌        | 9/59 [00:04<00:27,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1206       640   0.03682   0.02863  0.005485     5.675:  17%|█▋        | 10/59 [00:05<00:26,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1513       640   0.03685    0.0287  0.005496     5.684:  19%|█▊        | 11/59 [00:05<00:26,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1261       640   0.03691   0.02861  0.005489      5.68:  20%|██        | 12/59 [00:06<00:25,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1489       640   0.03684   0.02882  0.005511     5.694:  22%|██▏       | 13/59 [00:07<00:25,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1533       640   0.03686   0.02894  0.005482     5.702:  24%|██▎       | 14/59 [00:07<00:24,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1668       640   0.03681    0.0291  0.005429     5.707:  25%|██▌       | 15/59 [00:08<00:24,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1404       640   0.03682   0.02919  0.005467     5.718:  27%|██▋       | 16/59 [00:08<00:23,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1087       640   0.03674   0.02908  0.005454     5.702:  29%|██▉       | 17/59 [00:09<00:22,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1457       640   0.03668   0.02921  0.005436     5.706:  31%|███       | 18/59 [00:09<00:22,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1398       640   0.03668   0.02926  0.005454     5.712:  32%|███▏      | 19/59 [00:10<00:21,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1328       640   0.03668   0.02927  0.005425     5.709:  34%|███▍      | 20/59 [00:10<00:21,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1405       640   0.03661   0.02928  0.005373     5.701:  36%|███▌      | 21/59 [00:11<00:20,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1190       640   0.03663   0.02921  0.005361     5.696:  37%|███▋      | 22/59 [00:12<00:20,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1309       640    0.0366   0.02917  0.005382     5.692:  39%|███▉      | 23/59 [00:12<00:19,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1637       640   0.03663   0.02937  0.005387     5.711:  41%|████      | 24/59 [00:13<00:19,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1229       640   0.03664   0.02922  0.005372     5.698:  42%|████▏     | 25/59 [00:13<00:18,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1511       640   0.03676    0.0293  0.005391     5.716:  44%|████▍     | 26/59 [00:14<00:18,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1266       640    0.0368   0.02923  0.005398     5.714:  46%|████▌     | 27/59 [00:14<00:17,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1418       640   0.03684   0.02928   0.00542     5.723:  47%|████▋     | 28/59 [00:15<00:17,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1397       640   0.03686    0.0293  0.005434     5.727:  49%|████▉     | 29/59 [00:15<00:16,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.503      0.392      0.382      0.207

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/59 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1513       640   0.03687   0.02923  0.006625     5.818:   2%|▏         | 1/59 [00:00<00:32,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1413       640   0.03667   0.02873  0.006091      5.72:   3%|▎         | 2/59 [00:01<00:31,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1530       640   0.03621    0.0293  0.005979     5.719:   5%|▌         | 3/59 [00:01<00:31,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1184       640   0.03644   0.02856  0.005759     5.661:   7%|▋         | 4/59 [00:02<00:30,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1463       640   0.03627   0.02872   0.00561     5.648:   8%|▊         | 5/59 [00:02<00:30,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1330       640    0.0362   0.02869  0.005442     5.627:  10%|█         | 6/59 [00:03<00:29,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1569       640   0.03627   0.02904  0.005433      5.66:  12%|█▏        | 7/59 [00:03<00:29,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1272       640   0.03607   0.02863  0.005419     5.609:  14%|█▎        | 8/59 [00:04<00:28,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1373       640   0.03607   0.02856  0.005408     5.603:  15%|█▌        | 9/59 [00:05<00:28,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1230       640   0.03605   0.02823  0.005336     5.569:  17%|█▋        | 10/59 [00:05<00:27,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1161       640    0.0362   0.02792  0.005339     5.556:  19%|█▊        | 11/59 [00:06<00:26,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1390       640   0.03616   0.02804  0.005347     5.564:  20%|██        | 12/59 [00:06<00:26,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1395       640   0.03604   0.02817  0.005298      5.56:  22%|██▏       | 13/59 [00:07<00:25,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1243       640   0.03609     0.028  0.005329     5.554:  24%|██▎       | 14/59 [00:07<00:25,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1283       640   0.03609   0.02795  0.005292     5.546:  25%|██▌       | 15/59 [00:08<00:24,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1283       640   0.03608   0.02775  0.005253     5.527:  27%|██▋       | 16/59 [00:08<00:24,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1218       640   0.03603   0.02768  0.005194     5.512:  29%|██▉       | 17/59 [00:09<00:23,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1132       640   0.03603   0.02763  0.005216      5.51:  31%|███       | 18/59 [00:10<00:23,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1494       640   0.03606   0.02773  0.005207      5.52:  32%|███▏      | 19/59 [00:10<00:22,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1316       640   0.03602   0.02771  0.005257      5.52:  34%|███▍      | 20/59 [00:11<00:21,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1451       640   0.03596    0.0278  0.005264     5.522:  36%|███▌      | 21/59 [00:11<00:21,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1430       640    0.0359   0.02788  0.005299     5.526:  37%|███▋      | 22/59 [00:12<00:20,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1171       640   0.03589   0.02785  0.005342     5.527:  39%|███▉      | 23/59 [00:12<00:20,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1439       640   0.03598   0.02788  0.005343     5.536:  41%|████      | 24/59 [00:13<00:19,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1482       640   0.03598   0.02793  0.005342     5.541:  42%|████▏     | 25/59 [00:14<00:19,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1325       640   0.03593   0.02794  0.005339     5.537:  44%|████▍     | 26/59 [00:14<00:18,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1262       640    0.0359   0.02792  0.005354     5.534:  46%|████▌     | 27/59 [00:15<00:18,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1359       640   0.03592   0.02795  0.005358     5.538:  47%|████▋     | 28/59 [00:15<00:17,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1136       640   0.03591   0.02782  0.005328     5.525:  49%|████▉     | 29/59 [00:16<00:16,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.528      0.382      0.388      0.215
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client0_highway/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client0_highway/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.22it/s]

                 all        738      14937      0.512      0.383      0.387      0.216
                   0        738       1052      0.551      0.515      0.515      0.238
                   1        738         44       0.25     0.0682      0.165     0.0614
                   2        738       8622      0.651       0.71      0.733      0.458
                   3        738        151      0.412      0.404      0.415      0.328
                   4        738        467      0.469      0.542       0.51      0.365
                   5        738         70      0.287      0.371      0.254      0.136
                   6        738         65       0.31      0.108       0.15     0.0598
                   7        738       1619      0.539      0.578      0.557      0.223
                   8        738       2845      0.654      0.537      0.569      0.288
                   9        738          2          1          0   0.000322    0.00029

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client0_highway

3 epochs completed in 0.049 hours.
Destroying process group...
[rank0]:[W505 03:00:57.036414117 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30422 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_backbone_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/client_states/pl02_stable_mix_backbone_client1_citystreet_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client1_citystreet_stable_train' images and labels...:   0%|          | 0/9879 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client1_citystreet_stable_train' images and labels...5196 found, 4683 missing, 0 empty, 0 corrupted: 100%|██████████| 9879/9879 [00:00<00:00, 16781.90it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client1_citystreet_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.155060644081974
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client1_citystreet_stable_train.cache' images and labels... 5196 found, 4683 missing, 0 empty, 0 corrupted: 100%|██████████| 9879/9879 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client1_citystreet
Starting training for 3 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 03:01:14.180484598 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 03:01:14.185636571 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     4.99G      1034       640   0.03753   0.04888  0.005825     7.379:   2%|▏         | 1/60 [00:25<25:23, 25.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1305       640   0.03742   0.04862  0.005742     7.342:   3%|▎         | 2/60 [00:26<10:40, 11.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1496       640   0.03776   0.04843  0.005668     7.349:   5%|▌         | 3/60 [00:27<06:00,  6.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1352       640   0.03811    0.0471  0.005722     7.275:   7%|▋         | 4/60 [00:27<03:50,  4.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1231       640   0.03814   0.04609  0.005745     7.198:   8%|▊         | 5/60 [00:28<02:35,  2.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1434       640   0.03821   0.04559  0.005839     7.172:  10%|█         | 6/60 [00:29<01:50,  2.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1409       640   0.03825   0.04495  0.005854     7.124:  12%|█▏        | 7/60 [00:29<01:22,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1467       640   0.03842   0.04423  0.005858     7.081:  13%|█▎        | 8/60 [00:30<01:04,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1485       640   0.03856   0.04407  0.005839     7.077:  15%|█▌        | 9/60 [00:30<00:51,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1369       640   0.03847   0.04374  0.005818     7.042:  17%|█▋        | 10/60 [00:31<00:43,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1203       640   0.03834   0.04296  0.005777     6.966:  18%|█▊        | 11/60 [00:31<00:37,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1333       640   0.03841   0.04238  0.005809     6.928:  20%|██        | 12/60 [00:32<00:33,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1080       640   0.03822    0.0416  0.005767     6.847:  22%|██▏       | 13/60 [00:32<00:30,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1117       640   0.03828    0.0413  0.005787     6.829:  23%|██▎       | 14/60 [00:33<00:28,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1167       640   0.03819   0.04082  0.005831     6.787:  25%|██▌       | 15/60 [00:33<00:26,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1292       640   0.03817   0.04051  0.005816     6.759:  27%|██▋       | 16/60 [00:34<00:25,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1338       640    0.0383   0.04032  0.005936     6.765:  28%|██▊       | 17/60 [00:35<00:24,  1.75it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1521       640   0.03831   0.04011  0.005971     6.752:  30%|███       | 18/60 [00:35<00:23,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1054       640   0.03822   0.03981  0.005998     6.722:  32%|███▏      | 19/60 [00:36<00:22,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1428       640   0.03831   0.03976  0.006008     6.726:  33%|███▎      | 20/60 [00:36<00:22,  1.80it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1236       640   0.03828   0.03934  0.006001      6.69:  35%|███▌      | 21/60 [00:37<00:21,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1179       640    0.0383   0.03904  0.005974     6.664:  37%|███▋      | 22/60 [00:37<00:20,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1375       640   0.03824   0.03879  0.005971      6.64:  38%|███▊      | 23/60 [00:38<00:20,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1337       640    0.0383   0.03865  0.005969     6.633:  40%|████      | 24/60 [00:38<00:19,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1495       640   0.03826   0.03852  0.005958     6.619:  42%|████▏     | 25/60 [00:39<00:19,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1151       640   0.03823   0.03834  0.005973     6.603:  43%|████▎     | 26/60 [00:39<00:18,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.487      0.429      0.384       0.21

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1355       640   0.03605   0.03311  0.004844     5.921:   2%|▏         | 1/60 [00:00<00:32,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1135       640   0.03639    0.0326  0.005733     5.977:   3%|▎         | 2/60 [00:01<00:31,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1450       640   0.03674   0.03195  0.005578     5.941:   5%|▌         | 3/60 [00:01<00:31,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1179       640   0.03635    0.0313  0.005261     5.833:   7%|▋         | 4/60 [00:02<00:30,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1546       640   0.03641   0.03191  0.005368     5.896:   8%|▊         | 5/60 [00:02<00:30,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1145       640   0.03602   0.03157  0.005389     5.838:  10%|█         | 6/60 [00:03<00:29,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1466       640   0.03608   0.03163  0.005445     5.852:  12%|█▏        | 7/60 [00:03<00:28,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1435       640   0.03623   0.03211  0.005437     5.903:  13%|█▎        | 8/60 [00:04<00:28,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1276       640   0.03631   0.03203  0.005569     5.913:  15%|█▌        | 9/60 [00:04<00:27,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1292       640   0.03658   0.03201  0.005651     5.939:  17%|█▋        | 10/60 [00:05<00:27,  1.83it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1397       640   0.03663   0.03195  0.005608     5.935:  18%|█▊        | 11/60 [00:06<00:26,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1113       640   0.03665   0.03164  0.005659     5.916:  20%|██        | 12/60 [00:06<00:26,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1344       640   0.03659   0.03165  0.005626     5.909:  22%|██▏       | 13/60 [00:07<00:25,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1765       640   0.03665   0.03217  0.005632     5.956:  23%|██▎       | 14/60 [00:07<00:25,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1190       640   0.03671   0.03189  0.005613     5.937:  25%|██▌       | 15/60 [00:08<00:24,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1294       640   0.03675   0.03177  0.005601      5.93:  27%|██▋       | 16/60 [00:08<00:24,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1610       640   0.03684   0.03194   0.00558     5.948:  28%|██▊       | 17/60 [00:09<00:23,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1344       640   0.03685   0.03193  0.005597      5.95:  30%|███       | 18/60 [00:09<00:23,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1427       640   0.03679   0.03189  0.005542     5.938:  32%|███▏      | 19/60 [00:10<00:22,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1347       640   0.03683    0.0319   0.00555     5.942:  33%|███▎      | 20/60 [00:10<00:22,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1243       640   0.03675   0.03173  0.005544     5.922:  35%|███▌      | 21/60 [00:11<00:21,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1255       640   0.03673   0.03155   0.00551     5.904:  37%|███▋      | 22/60 [00:12<00:20,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1491       640   0.03673   0.03163  0.005509      5.91:  38%|███▊      | 23/60 [00:12<00:20,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1349       640   0.03671   0.03145   0.00551     5.894:  40%|████      | 24/60 [00:13<00:19,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1414       640   0.03666   0.03142  0.005506     5.888:  42%|████▏     | 25/60 [00:13<00:19,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1183       640   0.03665    0.0313  0.005531     5.879:  43%|████▎     | 26/60 [00:14<00:18,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1195       640   0.03665   0.03114  0.005559     5.868:  45%|████▌     | 27/60 [00:14<00:18,  1.80it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1260       640   0.03658   0.03107   0.00556     5.857:  47%|████▋     | 28/60 [00:15<00:17,  1.80it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1184       640    0.0366   0.03096  0.005565     5.851:  48%|████▊     | 29/60 [00:15<00:17,  1.80it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.472      0.412      0.377      0.208

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1459       640   0.03594   0.03041  0.004874     5.698:   2%|▏         | 1/60 [00:00<00:33,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1112       640   0.03588   0.02909  0.004918     5.591:   3%|▎         | 2/60 [00:01<00:32,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1555       640   0.03598   0.02994  0.005196     5.689:   5%|▌         | 3/60 [00:01<00:31,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1144       640   0.03596   0.02917  0.005068     5.616:   7%|▋         | 4/60 [00:02<00:31,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1151       640   0.03584   0.02885  0.005031     5.578:   8%|▊         | 5/60 [00:02<00:30,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1308       640   0.03561   0.02871  0.005101     5.554:  10%|█         | 6/60 [00:03<00:30,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1428       640   0.03562   0.02925  0.005166     5.603:  12%|█▏        | 7/60 [00:03<00:29,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1311       640   0.03569   0.02912  0.005152     5.597:  13%|█▎        | 8/60 [00:04<00:29,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1374       640   0.03573   0.02927  0.005197     5.615:  15%|█▌        | 9/60 [00:05<00:28,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1373       640   0.03565   0.02947  0.005171     5.623:  17%|█▋        | 10/60 [00:05<00:28,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1286       640   0.03569    0.0294   0.00522     5.625:  18%|█▊        | 11/60 [00:06<00:27,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1401       640   0.03569   0.02955  0.005275     5.641:  20%|██        | 12/60 [00:06<00:27,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1499       640   0.03572   0.02979  0.005351     5.669:  22%|██▏       | 13/60 [00:07<00:26,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1323       640   0.03559   0.02984  0.005311     5.659:  23%|██▎       | 14/60 [00:07<00:26,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1332       640   0.03565   0.02986  0.005318     5.667:  25%|██▌       | 15/60 [00:08<00:25,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1387       640   0.03571   0.02988  0.005283      5.67:  27%|██▋       | 16/60 [00:09<00:24,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1307       640   0.03569   0.02988   0.00524     5.665:  28%|██▊       | 17/60 [00:09<00:24,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1274       640   0.03565   0.02991  0.005267     5.666:  30%|███       | 18/60 [00:10<00:23,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1241       640   0.03575   0.02972  0.005327     5.664:  32%|███▏      | 19/60 [00:10<00:23,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1316       640   0.03588   0.02964  0.005332     5.668:  33%|███▎      | 20/60 [00:11<00:22,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1357       640    0.0359   0.02955  0.005336     5.663:  35%|███▌      | 21/60 [00:11<00:22,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1467       640   0.03597   0.02965  0.005352     5.678:  37%|███▋      | 22/60 [00:12<00:21,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1508       640   0.03596   0.02978  0.005333     5.686:  38%|███▊      | 23/60 [00:13<00:21,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1489       640   0.03603   0.02986  0.005348     5.699:  40%|████      | 24/60 [00:13<00:20,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1220       640   0.03604   0.02971  0.005328     5.687:  42%|████▏     | 25/60 [00:14<00:19,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1271       640   0.03609    0.0296   0.00532     5.681:  43%|████▎     | 26/60 [00:14<00:19,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1434       640   0.03607    0.0296  0.005324     5.679:  45%|████▌     | 27/60 [00:15<00:18,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1414       640   0.03605   0.02964  0.005319     5.681:  47%|████▋     | 28/60 [00:15<00:18,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1431       640   0.03603   0.02961  0.005313     5.676:  48%|████▊     | 29/60 [00:16<00:17,  1.75it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.495      0.413      0.382       0.21
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client1_citystreet/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client1_citystreet/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.478      0.423      0.382      0.211
                   0        738       1052      0.495      0.466      0.464       0.21
                   1        738         44      0.421       0.25      0.214     0.0808
                   2        738       8622       0.52      0.753      0.732      0.462
                   3        738        151      0.335       0.43      0.376      0.292
                   4        738        467      0.426      0.585       0.54      0.381
                   5        738         70      0.286      0.357        0.2     0.0905
                   6        738         65      0.319      0.154      0.165     0.0694
                   7        738       1619      0.482      0.603      0.548      0.223
                   8        738       2845       0.49      0.634      0.583      0.301
                   9        738          2          1          0   0.000203   0.000183

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client1_citystreet

3 epochs completed in 0.049 hours.
Destroying process group...
[rank0]:[W505 03:04:11.275301352 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30423 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_backbone_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/client_states/pl02_stable_mix_backbone_client2_residential_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client2_residential_stable_train' images and labels...5230 found, 4645 missing, 0 empty, 0 corrupted: 100%|██████████| 9875/9875 [00:00<00:00, 11375.31it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client2_residential_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.195570018895655
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client2_residential_stable_train.cache' images and labels... 5230 found, 4645 missing, 0 empty, 0 corrupted: 100%|██████████| 9875/9875 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client2_residential
Starting training for 3 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 03:04:28.712449415 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 03:04:28.737580888 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     4.99G      1181       640   0.03808   0.04705  0.005671     7.264:   2%|▏         | 1/60 [00:26<25:39, 26.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1669       640   0.03944   0.04863  0.005455     7.482:   3%|▎         | 2/60 [00:27<10:56, 11.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1149       640   0.03939   0.04797  0.005531     7.432:   5%|▌         | 3/60 [00:27<06:11,  6.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1337       640   0.03887   0.04738  0.005634     7.351:   7%|▋         | 4/60 [00:28<03:57,  4.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1171       640   0.03869   0.04658  0.005683     7.276:   8%|▊         | 5/60 [00:29<02:39,  2.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1136       640   0.03854   0.04548  0.005857     7.189:  10%|█         | 6/60 [00:29<01:53,  2.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1398       640   0.03848   0.04517  0.005889     7.163:  12%|█▏        | 7/60 [00:30<01:24,  1.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1282       640   0.03837   0.04466  0.005882     7.113:  13%|█▎        | 8/60 [00:30<01:05,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1386       640   0.03819   0.04429  0.005925     7.072:  15%|█▌        | 9/60 [00:31<00:52,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1522       640   0.03817   0.04421   0.00598     7.069:  17%|█▋        | 10/60 [00:31<00:44,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1702       640   0.03832   0.04414  0.005932     7.071:  18%|█▊        | 11/60 [00:32<00:38,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1346       640   0.03829   0.04379   0.00597     7.044:  20%|██        | 12/60 [00:32<00:34,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1227       640   0.03829   0.04345   0.00594     7.015:  22%|██▏       | 13/60 [00:33<00:30,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1425       640   0.03836   0.04301  0.005921     6.983:  23%|██▎       | 14/60 [00:34<00:28,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1428       640   0.03838   0.04278  0.005955      6.97:  25%|██▌       | 15/60 [00:34<00:27,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1172       640   0.03831   0.04224  0.005951      6.92:  27%|██▋       | 16/60 [00:35<00:25,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1220       640   0.03834   0.04175  0.005953     6.883:  28%|██▊       | 17/60 [00:35<00:24,  1.74it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1199       640   0.03834    0.0413  0.006036     6.855:  30%|███       | 18/60 [00:36<00:23,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1044       640   0.03826    0.0408  0.006043     6.808:  32%|███▏      | 19/60 [00:36<00:23,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1363       640   0.03822   0.04043   0.00599     6.772:  33%|███▎      | 20/60 [00:37<00:22,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1411       640   0.03822   0.04019  0.005982     6.752:  35%|███▌      | 21/60 [00:37<00:21,  1.80it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1030       640   0.03814   0.03969  0.005947     6.702:  37%|███▋      | 22/60 [00:38<00:21,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1515       640   0.03814   0.03964  0.005946     6.698:  38%|███▊      | 23/60 [00:38<00:20,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1263       640   0.03813   0.03937  0.005907     6.673:  40%|████      | 24/60 [00:39<00:19,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1429       640   0.03817   0.03926  0.005947      6.67:  42%|████▏     | 25/60 [00:40<00:19,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/2     42.6G      1288       640   0.03813   0.03903  0.005966      6.65:  43%|████▎     | 26/60 [00:40<00:18,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.533      0.365       0.38      0.206

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1306       640   0.03879   0.02971  0.006501         6:   2%|▏         | 1/60 [00:00<00:54,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1161       640   0.03796    0.0282  0.006435     5.808:   3%|▎         | 2/60 [00:01<00:40,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1206       640   0.03719   0.02871  0.005972     5.749:   5%|▌         | 3/60 [00:02<00:35,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1481       640   0.03698   0.02955  0.005681     5.777:   7%|▋         | 4/60 [00:02<00:33,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1444       640   0.03702   0.02943  0.005652     5.769:   8%|▊         | 5/60 [00:03<00:31,  1.73it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1355       640   0.03702   0.03011  0.005719     5.828:  10%|█         | 6/60 [00:03<00:30,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1493       640   0.03711   0.03028  0.005645     5.843:  12%|█▏        | 7/60 [00:04<00:29,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1334       640     0.037    0.0304  0.005624     5.842:  13%|█▎        | 8/60 [00:04<00:28,  1.80it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1119       640   0.03692   0.03001  0.005552     5.799:  15%|█▌        | 9/60 [00:05<00:28,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1428       640   0.03681   0.03008   0.00553     5.794:  17%|█▋        | 10/60 [00:05<00:27,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1233       640   0.03676   0.02992   0.00549     5.774:  18%|█▊        | 11/60 [00:06<00:26,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1340       640   0.03672    0.0297  0.005548     5.757:  20%|██        | 12/60 [00:06<00:26,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1313       640   0.03671   0.02963    0.0055     5.747:  22%|██▏       | 13/60 [00:07<00:25,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1467       640   0.03676   0.02972  0.005499     5.758:  23%|██▎       | 14/60 [00:08<00:25,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1310       640    0.0368   0.02965  0.005482     5.754:  25%|██▌       | 15/60 [00:08<00:24,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1197       640   0.03668   0.02951  0.005509     5.736:  27%|██▋       | 16/60 [00:09<00:24,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1433       640   0.03671   0.02959  0.005544     5.748:  28%|██▊       | 17/60 [00:09<00:23,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1284       640   0.03675   0.02941  0.005597      5.74:  30%|███       | 18/60 [00:10<00:23,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1444       640   0.03677   0.02939  0.005583     5.739:  32%|███▏      | 19/60 [00:10<00:22,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1322       640   0.03669   0.02945  0.005566     5.737:  33%|███▎      | 20/60 [00:11<00:22,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1460       640   0.03671   0.02948  0.005558     5.739:  35%|███▌      | 21/60 [00:11<00:21,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1378       640   0.03663   0.02958  0.005556     5.741:  37%|███▋      | 22/60 [00:12<00:20,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1309       640   0.03662    0.0296  0.005545     5.742:  38%|███▊      | 23/60 [00:12<00:20,  1.82it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1420       640   0.03666   0.02971  0.005516     5.751:  40%|████      | 24/60 [00:13<00:19,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1467       640   0.03662    0.0298  0.005537     5.757:  42%|████▏     | 25/60 [00:14<00:19,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1126       640   0.03657   0.02975  0.005521     5.747:  43%|████▎     | 26/60 [00:14<00:18,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1117       640   0.03648    0.0297  0.005477     5.733:  45%|████▌     | 27/60 [00:15<00:18,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1367       640   0.03648   0.02962  0.005459     5.724:  47%|████▋     | 28/60 [00:15<00:17,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/2     42.7G      1248       640    0.0365    0.0296  0.005432     5.722:  48%|████▊     | 29/60 [00:16<00:17,  1.81it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.559      0.372      0.392      0.216

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1400       640   0.03712   0.02804  0.004882     5.603:   2%|▏         | 1/60 [00:00<00:32,  1.80it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1218       640   0.03648   0.02741  0.004943     5.507:   3%|▎         | 2/60 [00:01<00:32,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1615       640   0.03668   0.02866  0.005497     5.667:   5%|▌         | 3/60 [00:01<00:31,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1163       640   0.03664     0.028  0.005406     5.603:   7%|▋         | 4/60 [00:02<00:31,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1390       640   0.03658   0.02798  0.005476     5.603:   8%|▊         | 5/60 [00:02<00:30,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1272       640   0.03642   0.02765  0.005467     5.564:  10%|█         | 6/60 [00:03<00:30,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1256       640   0.03644   0.02751  0.005566     5.562:  12%|█▏        | 7/60 [00:03<00:29,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1058       640   0.03625   0.02712  0.005445     5.505:  13%|█▎        | 8/60 [00:04<00:29,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1370       640    0.0363   0.02711  0.005447     5.508:  15%|█▌        | 9/60 [00:05<00:28,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1451       640   0.03627    0.0274  0.005355     5.522:  17%|█▋        | 10/60 [00:05<00:28,  1.79it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1115       640   0.03617   0.02727  0.005362     5.504:  18%|█▊        | 11/60 [00:06<00:27,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1444       640   0.03623   0.02752  0.005372      5.53:  20%|██        | 12/60 [00:06<00:26,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1617       640   0.03631   0.02798  0.005391     5.574:  22%|██▏       | 13/60 [00:07<00:26,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1623       640   0.03617   0.02837   0.00535     5.591:  23%|██▎       | 14/60 [00:07<00:25,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1180       640   0.03623   0.02829  0.005334     5.588:  25%|██▌       | 15/60 [00:08<00:25,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1232       640   0.03619   0.02821  0.005323     5.578:  27%|██▋       | 16/60 [00:08<00:24,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1350       640   0.03615   0.02822  0.005324     5.575:  28%|██▊       | 17/60 [00:09<00:24,  1.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1137       640    0.0361   0.02802   0.00531     5.555:  30%|███       | 18/60 [00:10<00:23,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1394       640   0.03614    0.0281  0.005335     5.566:  32%|███▏      | 19/60 [00:10<00:23,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1162       640   0.03606   0.02804  0.005318     5.553:  33%|███▎      | 20/60 [00:11<00:22,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1261       640   0.03605   0.02789  0.005306     5.539:  35%|███▌      | 21/60 [00:11<00:22,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1193       640   0.03599   0.02774   0.00527      5.52:  37%|███▋      | 22/60 [00:12<00:21,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1445       640   0.03601   0.02782  0.005274     5.528:  38%|███▊      | 23/60 [00:12<00:20,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1336       640   0.03604    0.0279  0.005286     5.538:  40%|████      | 24/60 [00:13<00:20,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1239       640   0.03605   0.02774  0.005293     5.527:  42%|████▏     | 25/60 [00:14<00:19,  1.77it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1327       640   0.03608   0.02774  0.005302      5.53:  43%|████▎     | 26/60 [00:14<00:19,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1375       640   0.03605    0.0278  0.005293     5.531:  45%|████▌     | 27/60 [00:15<00:18,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1627       640   0.03607   0.02792  0.005292     5.543:  47%|████▋     | 28/60 [00:15<00:18,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       2/2     44.7G      1390       640   0.03608   0.02787  0.005315     5.541:  48%|████▊     | 29/60 [00:16<00:17,  1.76it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.492        0.4      0.388      0.212
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client2_residential/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client2_residential/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.547      0.373      0.389      0.217
                   0        738       1052      0.562      0.518      0.527      0.241
                   1        738         44      0.327     0.0444       0.15     0.0692
                   2        738       8622      0.645      0.716      0.738      0.463
                   3        738        151      0.466      0.411      0.414      0.312
                   4        738        467      0.494      0.552      0.547      0.383
                   5        738         70      0.415      0.286      0.246      0.123
                   6        738         65      0.393     0.0462      0.121     0.0474
                   7        738       1619      0.549      0.577      0.561      0.229
                   8        738       2845      0.613      0.578      0.582      0.299
                   9        738          2          1          0   0.000258   0.000233

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_client2_residential

3 epochs completed in 0.050 hours.
Destroying process group...
[rank0]:[W505 03:07:26.326819860 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30424 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_backbone_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/global_checkpoints/stable_mix_backbone_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 14139.18it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 03:07:42.331078357 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 03:07:42.375481818 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03642   0.05832  0.005607     8.028:   3%|▎         | 1/31 [00:32<16:19, 32.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2744       640   0.03723   0.06056  0.005764     8.284:   6%|▋         | 2/31 [00:33<06:43, 13.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03674   0.05932  0.005686      8.14:  10%|▉         | 3/31 [00:34<03:41,  7.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03604   0.05447  0.005415     7.674:  13%|█▎        | 4/31 [00:35<02:17,  5.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.03583   0.05256  0.005388     7.503:  16%|█▌        | 5/31 [00:35<01:30,  3.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03587   0.05094  0.005415     7.377:  19%|█▉        | 6/31 [00:36<01:02,  2.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.03586   0.04951   0.00546     7.266:  23%|██▎       | 7/31 [00:36<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640    0.0357   0.04881  0.005466     7.199:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.03564   0.04811  0.005348     7.128:  29%|██▉       | 9/31 [00:37<00:26,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.03555   0.04772   0.00529     7.085:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.03545   0.04726  0.005285      7.04:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.03529   0.04663  0.005251     6.973:  39%|███▊      | 12/31 [00:39<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.03522   0.04635  0.005192     6.941:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.03519   0.04587  0.005151     6.897:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.03519   0.04553  0.005183     6.872:  48%|████▊     | 15/31 [00:41<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.03515   0.04518  0.005161      6.84:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.03515   0.04502  0.005116     6.823:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03515   0.04486  0.005066     6.807:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.03505   0.04455   0.00502      6.77:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03501   0.04462  0.005017     6.772:  65%|██████▍   | 20/31 [00:44<00:06,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03501    0.0445   0.00503     6.763:  68%|██████▊   | 21/31 [00:44<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03497   0.04447  0.004998     6.755:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03493   0.04438  0.004978     6.743:  74%|███████▍  | 23/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03491   0.04433  0.004955     6.736:  77%|███████▋  | 24/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03488   0.04416  0.004956      6.72:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640    0.0349   0.04407  0.004952     6.714:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.512      0.436      0.415      0.232
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.499      0.438      0.413      0.233
                   0        738       1052      0.544      0.554      0.543      0.256
                   1        738         44      0.309      0.159      0.138     0.0592
                   2        738       8622      0.624      0.748      0.757      0.487
                   3        738        151      0.382      0.457      0.445       0.34
                   4        738        467      0.506      0.587      0.573      0.409
                   5        738         70      0.229      0.457      0.304      0.148
                   6        738         65      0.259      0.167      0.156      0.056
                   7        738       1619      0.548      0.619      0.589      0.245
                   8        738       2845      0.585      0.633      0.622      0.328
                   9        738          2          1          0   0.000322    0.00029

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_backbone_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 03:09:22.364154777 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

=== Running variant: stable_mix_all_lowlr ===
{
  "name": "stable_mix_all_lowlr",
  "train_scope": "all",
  "aggregate_scope": "all",
  "epochs": 2,
  "lr0": 0.0007,
  "pseudo_repeat": 1,
  "source_repeat": 1,
  "orthogonal_weight": 0.0001,
  "note": "Low-LR full-model adaptation with source labels anchoring the detector."
}
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30425 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_all_lowlr_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/client_states/pl02_stable_mix_all_lowlr_client0_highway_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client0_highway_stable_train.cache' images and labels... 5377 found, 4488 missing, 0 empty, 0 corrupted: 100%|██████████| 9865/9865 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.366421176219447
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client0_highway_stable_train.cache' images and labels... 5377 found, 4488 missing, 0 empty, 0 corrupted: 100%|██████████| 9865/9865 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client0_highway
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 03:09:38.359299190 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 03:09:38.370677251 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/59 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     6.43G      1368       640    0.0389   0.04341  0.004976     6.983:   2%|▏         | 1/59 [00:31<30:46, 31.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.5G      1314       640   0.03873   0.04343  0.005057     6.978:   3%|▎         | 2/59 [00:32<13:03, 13.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1345       640    0.0393   0.04364  0.005483     7.074:   5%|▌         | 3/59 [00:34<07:26,  7.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1202       640   0.03876   0.04309   0.00588     7.018:   7%|▋         | 4/59 [00:35<04:48,  5.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1406       640   0.03853   0.04235  0.005828     6.937:   8%|▊         | 5/59 [00:35<03:18,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1275       640   0.03808   0.04118  0.005838     6.808:  10%|█         | 6/59 [00:36<02:24,  2.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1354       640   0.03778   0.04017  0.005877     6.706:  12%|█▏        | 7/59 [00:37<01:50,  2.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1499       640   0.03745   0.03965  0.005795     6.631:  14%|█▎        | 8/59 [00:38<01:28,  1.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1426       640   0.03742   0.03936  0.005806     6.607:  15%|█▌        | 9/59 [00:39<01:13,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1180       640   0.03728   0.03871  0.005801     6.543:  17%|█▋        | 10/59 [00:40<01:03,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1473       640   0.03716   0.03836  0.005797     6.505:  19%|█▊        | 11/59 [00:41<00:56,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1428       640   0.03711   0.03822  0.005785     6.489:  20%|██        | 12/59 [00:42<00:50,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1399       640   0.03703   0.03792  0.005787     6.459:  22%|██▏       | 13/59 [00:43<00:47,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1379       640   0.03699    0.0378  0.005852     6.452:  24%|██▎       | 14/59 [00:43<00:44,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1307       640   0.03687   0.03755  0.005848     6.422:  25%|██▌       | 15/59 [00:44<00:42,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1333       640    0.0367   0.03735  0.005817      6.39:  27%|██▋       | 16/59 [00:45<00:40,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1250       640   0.03663   0.03698  0.005792     6.352:  29%|██▉       | 17/59 [00:46<00:38,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1268       640   0.03661   0.03674    0.0058     6.331:  31%|███       | 18/59 [00:47<00:37,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1188       640   0.03651   0.03644  0.005779     6.299:  32%|███▏      | 19/59 [00:48<00:36,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1706       640   0.03655   0.03659  0.005771     6.313:  34%|███▍      | 20/59 [00:49<00:34,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1340       640   0.03645    0.0364  0.005765     6.289:  36%|███▌      | 21/59 [00:50<00:33,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1104       640   0.03635    0.0361  0.005757     6.257:  37%|███▋      | 22/59 [00:51<00:32,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1232       640   0.03632   0.03589  0.005732     6.236:  39%|███▉      | 23/59 [00:51<00:31,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1424       640   0.03637   0.03576   0.00574      6.23:  41%|████      | 24/59 [00:52<00:30,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1437       640   0.03626   0.03566  0.005724     6.211:  42%|████▏     | 25/59 [00:53<00:29,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1324       640   0.03623   0.03553  0.005697     6.197:  44%|████▍     | 26/59 [00:54<00:28,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.486      0.443       0.39      0.218

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/59 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1357       640   0.03437   0.02968  0.005259     5.545:   2%|▏         | 1/59 [00:00<00:52,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1412       640   0.03492   0.03174  0.005467      5.77:   3%|▎         | 2/59 [00:01<00:50,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1255       640   0.03489   0.03098  0.005203     5.686:   5%|▌         | 3/59 [00:02<00:50,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1502       640   0.03499   0.03117  0.005288     5.716:   7%|▋         | 4/59 [00:03<00:49,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1291       640   0.03486   0.03095  0.005214     5.682:   8%|▊         | 5/59 [00:04<00:48,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1249       640   0.03496   0.03056  0.005262     5.662:  10%|█         | 6/59 [00:05<00:47,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1422       640   0.03512   0.03078  0.005229      5.69:  12%|█▏        | 7/59 [00:06<00:46,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1192       640   0.03518   0.03051  0.005145     5.667:  14%|█▎        | 8/59 [00:07<00:45,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1410       640   0.03517   0.03071  0.005157     5.683:  15%|█▌        | 9/59 [00:08<00:44,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1206       640   0.03511   0.03068  0.005094     5.671:  17%|█▋        | 10/59 [00:08<00:43,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1513       640   0.03511   0.03071  0.005091     5.673:  19%|█▊        | 11/59 [00:09<00:42,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1261       640   0.03516   0.03067  0.005079     5.673:  20%|██        | 12/59 [00:10<00:42,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1489       640   0.03508   0.03089  0.005092     5.684:  22%|██▏       | 13/59 [00:11<00:41,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1533       640   0.03511   0.03103  0.005071     5.697:  24%|██▎       | 14/59 [00:12<00:40,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1668       640   0.03507   0.03122  0.005013     5.704:  25%|██▌       | 15/59 [00:13<00:40,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1404       640   0.03507    0.0313  0.005038     5.712:  27%|██▋       | 16/59 [00:14<00:38,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1087       640   0.03498   0.03104  0.005016     5.683:  29%|██▉       | 17/59 [00:15<00:38,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1457       640   0.03493   0.03115     0.005     5.686:  31%|███       | 18/59 [00:16<00:37,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1398       640   0.03493   0.03119  0.005027     5.692:  32%|███▏      | 19/59 [00:17<00:36,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1328       640   0.03494   0.03115  0.005009     5.688:  34%|███▍      | 20/59 [00:18<00:35,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1405       640   0.03487   0.03122  0.004958     5.684:  36%|███▌      | 21/59 [00:18<00:34,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1190       640   0.03489   0.03116  0.004964     5.681:  37%|███▋      | 22/59 [00:19<00:33,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1309       640   0.03487   0.03108  0.004991     5.676:  39%|███▉      | 23/59 [00:20<00:32,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1637       640    0.0349   0.03128   0.00499     5.693:  41%|████      | 24/59 [00:21<00:31,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1229       640   0.03491   0.03112  0.004979     5.681:  42%|████▏     | 25/59 [00:22<00:30,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1511       640   0.03504   0.03117     0.005     5.697:  44%|████▍     | 26/59 [00:23<00:29,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1266       640   0.03509   0.03108  0.005006     5.694:  46%|████▌     | 27/59 [00:24<00:28,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1418       640   0.03513   0.03117  0.005028     5.706:  47%|████▋     | 28/59 [00:25<00:28,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1397       640   0.03517   0.03113  0.005046     5.707:  49%|████▉     | 29/59 [00:26<00:27,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.497      0.435      0.399      0.222
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client0_highway/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client0_highway/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.464      0.458      0.396      0.222
                   0        738       1052      0.418      0.571      0.528      0.253
                   1        738         44      0.349      0.318      0.188     0.0782
                   2        738       8622        0.6       0.74      0.734      0.466
                   3        738        151        0.3      0.424       0.41      0.318
                   4        738        467      0.371      0.615      0.524      0.383
                   5        738         70      0.223      0.414      0.256       0.13
                   6        738         65      0.318      0.273      0.171     0.0671
                   7        738       1619      0.484      0.631      0.574      0.241
                   8        738       2845      0.576      0.594      0.578      0.288
                   9        738          2          1          0   0.000235   0.000211

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client0_highway

2 epochs completed in 0.053 hours.
Destroying process group...
[rank0]:[W505 03:12:48.545975304 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30426 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_all_lowlr_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/client_states/pl02_stable_mix_all_lowlr_client1_citystreet_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client1_citystreet_stable_train.cache' images and labels... 5196 found, 4683 missing, 0 empty, 0 corrupted: 100%|██████████| 9879/9879 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.155060644081974
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client1_citystreet_stable_train.cache' images and labels... 5196 found, 4683 missing, 0 empty, 0 corrupted: 100%|██████████| 9879/9879 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client1_citystreet
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 03:13:02.867707665 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 03:13:02.883634130 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     6.43G      1034       640   0.03754   0.04888  0.005825     7.379:   2%|▏         | 1/60 [00:32<32:14, 32.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.5G      1305       640   0.03745   0.04905  0.005749      7.38:   3%|▎         | 2/60 [00:34<13:48, 14.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1496       640   0.03784   0.04927  0.005671     7.422:   5%|▌         | 3/60 [00:35<07:52,  8.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1352       640   0.03801   0.04799  0.005725     7.338:   7%|▋         | 4/60 [00:36<05:04,  5.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1231       640   0.03776   0.04677  0.005737     7.221:   8%|▊         | 5/60 [00:37<03:29,  3.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1434       640   0.03753   0.04593  0.005834     7.143:  10%|█         | 6/60 [00:38<02:31,  2.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1409       640    0.0374   0.04502  0.005829     7.061:  12%|█▏        | 7/60 [00:39<01:55,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1467       640    0.0374   0.04418  0.005836     6.994:  13%|█▎        | 8/60 [00:39<01:32,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1485       640   0.03742   0.04383  0.005821     6.966:  15%|█▌        | 9/60 [00:40<01:16,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1369       640   0.03728   0.04354  0.005797      6.93:  17%|█▋        | 10/60 [00:41<01:05,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1203       640   0.03707   0.04272  0.005758     6.844:  18%|█▊        | 11/60 [00:42<00:57,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1333       640   0.03705   0.04226  0.005785     6.808:  20%|██        | 12/60 [00:43<00:52,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1080       640   0.03684   0.04162  0.005738     6.736:  22%|██▏       | 13/60 [00:44<00:48,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1117       640   0.03685   0.04124  0.005759     6.708:  23%|██▎       | 14/60 [00:45<00:45,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1167       640   0.03666   0.04084  0.005752      6.66:  25%|██▌       | 15/60 [00:46<00:43,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1292       640    0.0366   0.04068  0.005735     6.641:  27%|██▋       | 16/60 [00:47<00:41,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1338       640   0.03671   0.04056  0.005846     6.649:  28%|██▊       | 17/60 [00:47<00:39,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1521       640   0.03669   0.04053  0.005869     6.647:  30%|███       | 18/60 [00:48<00:38,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1054       640   0.03656   0.04016  0.005891      6.61:  32%|███▏      | 19/60 [00:49<00:36,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1428       640   0.03665   0.04015  0.005893     6.615:  33%|███▎      | 20/60 [00:50<00:35,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1236       640   0.03663   0.03981  0.005869     6.584:  35%|███▌      | 21/60 [00:51<00:34,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1179       640   0.03662   0.03948  0.005836     6.554:  37%|███▋      | 22/60 [00:52<00:33,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1375       640   0.03654   0.03928  0.005826     6.532:  38%|███▊      | 23/60 [00:53<00:32,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1337       640   0.03657   0.03914  0.005815     6.522:  40%|████      | 24/60 [00:54<00:31,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1495       640   0.03653   0.03908  0.005792     6.512:  42%|████▏     | 25/60 [00:54<00:30,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1151       640   0.03648   0.03887  0.005797     6.492:  43%|████▎     | 26/60 [00:55<00:29,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.524      0.406      0.394       0.22

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1355       640   0.03434   0.03461  0.004473     5.874:   2%|▏         | 1/60 [00:00<00:57,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1135       640   0.03483   0.03417  0.005362     5.949:   3%|▎         | 2/60 [00:01<00:53,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1450       640   0.03515    0.0341  0.005199     5.956:   5%|▌         | 3/60 [00:02<00:52,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1179       640   0.03474   0.03348  0.004928     5.852:   7%|▋         | 4/60 [00:03<00:51,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1546       640   0.03474   0.03413  0.005032     5.912:   8%|▊         | 5/60 [00:04<00:50,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1145       640   0.03434   0.03373  0.005003     5.846:  10%|█         | 6/60 [00:05<00:49,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1466       640   0.03442   0.03371  0.005086     5.858:  12%|█▏        | 7/60 [00:06<00:48,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1435       640   0.03456   0.03413  0.005069     5.901:  13%|█▎        | 8/60 [00:07<00:47,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1276       640   0.03463   0.03411  0.005199     5.915:  15%|█▌        | 9/60 [00:08<00:46,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1292       640   0.03489   0.03411  0.005268     5.942:  17%|█▋        | 10/60 [00:09<00:45,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1397       640    0.0349   0.03404  0.005198     5.932:  18%|█▊        | 11/60 [00:10<00:44,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1113       640   0.03492   0.03376  0.005254     5.914:  20%|██        | 12/60 [00:10<00:43,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1344       640   0.03484   0.03374  0.005214     5.904:  22%|██▏       | 13/60 [00:11<00:42,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1765       640   0.03488   0.03423   0.00521     5.946:  23%|██▎       | 14/60 [00:12<00:41,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1190       640   0.03496   0.03395  0.005191     5.928:  25%|██▌       | 15/60 [00:13<00:40,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1294       640   0.03501   0.03388  0.005177     5.926:  27%|██▋       | 16/60 [00:14<00:39,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1610       640   0.03509   0.03411   0.00516     5.949:  28%|██▊       | 17/60 [00:15<00:38,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1344       640    0.0351   0.03409  0.005177     5.949:  30%|███       | 18/60 [00:16<00:37,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1427       640   0.03504   0.03405  0.005128     5.937:  32%|███▏      | 19/60 [00:17<00:36,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1347       640   0.03508   0.03408  0.005144     5.944:  33%|███▎      | 20/60 [00:18<00:35,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1243       640     0.035   0.03396  0.005137     5.928:  35%|███▌      | 21/60 [00:19<00:35,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1255       640   0.03499   0.03381  0.005109     5.913:  37%|███▋      | 22/60 [00:19<00:34,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1491       640   0.03498   0.03388  0.005103     5.917:  38%|███▊      | 23/60 [00:20<00:33,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1349       640   0.03494   0.03366  0.005108     5.897:  40%|████      | 24/60 [00:21<00:32,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1414       640    0.0349   0.03366   0.00511     5.893:  42%|████▏     | 25/60 [00:22<00:31,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1183       640    0.0349   0.03355  0.005139     5.888:  43%|████▎     | 26/60 [00:23<00:30,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1195       640   0.03491   0.03339   0.00517     5.877:  45%|████▌     | 27/60 [00:24<00:29,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1260       640   0.03485   0.03335  0.005174      5.87:  47%|████▋     | 28/60 [00:25<00:28,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1     41.9G      1184       640   0.03487   0.03329  0.005186     5.868:  48%|████▊     | 29/60 [00:26<00:27,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.544      0.387      0.397       0.22
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client1_citystreet/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client1_citystreet/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.17it/s]

                 all        738      14937       0.55      0.381      0.395      0.221
                   0        738       1052      0.676      0.446      0.499       0.23
                   1        738         44      0.423     0.0682      0.193     0.0741
                   2        738       8622      0.635      0.726      0.735       0.46
                   3        738        151      0.387      0.411      0.409      0.319
                   4        738        467      0.437      0.595      0.535      0.388
                   5        738         70       0.38      0.343      0.254      0.121
                   6        738         65      0.372     0.0551       0.17     0.0714
                   7        738       1619      0.584       0.57      0.564      0.232
                   8        738       2845      0.606      0.593      0.589      0.308
                   9        738          2          1          0   0.000142   0.000114

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client1_citystreet

2 epochs completed in 0.055 hours.
Destroying process group...
[rank0]:[W505 03:16:17.164887653 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30427 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_all_lowlr_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/client_states/pl02_stable_mix_all_lowlr_client2_residential_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client2_residential_stable_train.cache' images and labels... 5230 found, 4645 missing, 0 empty, 0 corrupted: 100%|██████████| 9875/9875 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.195570018895655

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/pl02_client2_residential_stable_train.cache' images and labels... 5230 found, 4645 missing, 0 empty, 0 corrupted: 100%|██████████| 9875/9875 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client2_residential
Starting training for 2 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 03:16:33.775809917 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 03:16:33.790961496 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     6.62G      1181       640   0.03808   0.04704  0.005671     7.264:   2%|▏         | 1/60 [00:33<32:51, 33.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.5G      1669       640   0.03948    0.0489  0.005454     7.507:   3%|▎         | 2/60 [00:34<13:59, 14.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1149       640   0.03948   0.04861  0.005534      7.49:   5%|▌         | 3/60 [00:35<08:00,  8.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1337       640   0.03877   0.04791  0.005654     7.386:   7%|▋         | 4/60 [00:36<05:10,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1171       640   0.03835   0.04677  0.005699     7.265:   8%|▊         | 5/60 [00:37<03:32,  3.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1136       640   0.03791   0.04521   0.00587     7.119:  10%|█         | 6/60 [00:38<02:34,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1398       640   0.03773   0.04446  0.005886     7.045:  12%|█▏        | 7/60 [00:39<01:57,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1282       640   0.03754    0.0437  0.005893      6.97:  13%|█▎        | 8/60 [00:40<01:33,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1386       640   0.03723   0.04312  0.005928     6.902:  15%|█▌        | 9/60 [00:41<01:17,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1522       640   0.03707   0.04285  0.005976     6.872:  17%|█▋        | 10/60 [00:42<01:06,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1702       640   0.03717   0.04284   0.00594     6.876:  18%|█▊        | 11/60 [00:43<00:58,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1346       640   0.03708   0.04256  0.005981      6.85:  20%|██        | 12/60 [00:44<00:53,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1227       640     0.037   0.04223  0.005951     6.815:  22%|██▏       | 13/60 [00:45<00:48,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1425       640   0.03699   0.04196  0.005927      6.79:  23%|██▎       | 14/60 [00:45<00:46,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1428       640   0.03693   0.04182   0.00594     6.776:  25%|██▌       | 15/60 [00:46<00:43,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1172       640   0.03683   0.04135  0.005927     6.728:  27%|██▋       | 16/60 [00:47<00:41,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1220       640   0.03679   0.04102  0.005917     6.698:  28%|██▊       | 17/60 [00:48<00:39,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1199       640   0.03678   0.04055  0.005997     6.666:  30%|███       | 18/60 [00:49<00:38,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1044       640   0.03666   0.04007  0.005991     6.618:  32%|███▏      | 19/60 [00:50<00:37,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1363       640   0.03659   0.03983  0.005926     6.587:  33%|███▎      | 20/60 [00:51<00:35,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1411       640   0.03657   0.03966  0.005914     6.572:  35%|███▌      | 21/60 [00:52<00:34,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1030       640   0.03648   0.03921  0.005877     6.525:  37%|███▋      | 22/60 [00:52<00:33,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1515       640   0.03643   0.03927  0.005866     6.525:  38%|███▊      | 23/60 [00:53<00:32,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1263       640    0.0364   0.03903  0.005809     6.499:  40%|████      | 24/60 [00:54<00:31,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1429       640   0.03641   0.03897  0.005833     6.497:  42%|████▏     | 25/60 [00:55<00:30,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/1     42.6G      1288       640   0.03637   0.03884  0.005837     6.483:  43%|████▎     | 26/60 [00:56<00:30,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.466       0.43      0.388      0.215

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1306       640   0.03713   0.03297  0.005976     6.086:   2%|▏         | 1/60 [00:00<00:57,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1161       640   0.03625   0.03062  0.005972     5.827:   3%|▎         | 2/60 [00:01<00:54,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1206       640   0.03542   0.03126  0.005452     5.771:   5%|▌         | 3/60 [00:02<00:53,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1481       640   0.03522   0.03197   0.00518     5.789:   7%|▋         | 4/60 [00:03<00:51,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1444       640   0.03526   0.03208  0.005192     5.803:   8%|▊         | 5/60 [00:04<00:50,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1355       640   0.03529   0.03305  0.005286      5.89:  10%|█         | 6/60 [00:05<00:50,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1493       640   0.03535    0.0333  0.005202     5.908:  12%|█▏        | 7/60 [00:06<00:49,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1334       640   0.03529   0.03337  0.005183     5.907:  13%|█▎        | 8/60 [00:07<00:48,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1119       640    0.0352   0.03295  0.005117     5.861:  15%|█▌        | 9/60 [00:08<00:46,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1428       640   0.03508   0.03302  0.005113     5.857:  17%|█▋        | 10/60 [00:09<00:45,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1233       640   0.03504    0.0328  0.005082     5.834:  18%|█▊        | 11/60 [00:10<00:44,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1340       640   0.03501   0.03261  0.005135     5.821:  20%|██        | 12/60 [00:11<00:43,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1313       640   0.03498   0.03256  0.005098     5.812:  22%|██▏       | 13/60 [00:11<00:42,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1467       640   0.03505   0.03265  0.005105     5.824:  23%|██▎       | 14/60 [00:12<00:41,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1310       640   0.03509   0.03258  0.005108     5.822:  25%|██▌       | 15/60 [00:13<00:40,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1197       640   0.03498   0.03245  0.005134     5.805:  27%|██▋       | 16/60 [00:14<00:39,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1433       640     0.035   0.03259  0.005164      5.82:  28%|██▊       | 17/60 [00:15<00:38,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1284       640   0.03505   0.03243  0.005209     5.815:  30%|███       | 18/60 [00:16<00:37,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1444       640   0.03506   0.03238   0.00519      5.81:  32%|███▏      | 19/60 [00:17<00:37,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1322       640   0.03498   0.03241  0.005167     5.804:  33%|███▎      | 20/60 [00:18<00:36,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1460       640     0.035   0.03246  0.005156     5.809:  35%|███▌      | 21/60 [00:19<00:34,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1378       640   0.03492   0.03248  0.005152     5.805:  37%|███▋      | 22/60 [00:20<00:34,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1309       640   0.03492   0.03249  0.005139     5.804:  38%|███▊      | 23/60 [00:20<00:33,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1420       640   0.03495   0.03252  0.005106     5.806:  40%|████      | 24/60 [00:21<00:32,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1467       640   0.03491   0.03264  0.005134     5.815:  42%|████▏     | 25/60 [00:22<00:31,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1126       640   0.03486   0.03259  0.005113     5.805:  43%|████▎     | 26/60 [00:23<00:30,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1117       640   0.03477   0.03247   0.00507     5.784:  45%|████▌     | 27/60 [00:24<00:29,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1367       640   0.03476   0.03237  0.005055     5.776:  47%|████▋     | 28/60 [00:25<00:28,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       1/1       43G      1248       640   0.03478   0.03233  0.005033     5.771:  48%|████▊     | 29/60 [00:26<00:28,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.597      0.379      0.407      0.224
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client2_residential/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client2_residential/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937       0.59      0.378      0.404      0.225
                   0        738       1052      0.539      0.545      0.532      0.247
                   1        738         44       0.97     0.0455      0.206      0.081
                   2        738       8622      0.676       0.68      0.719      0.452
                   3        738        151      0.458      0.417      0.419      0.329
                   4        738        467      0.437       0.58      0.535      0.384
                   5        738         70      0.413      0.342        0.3      0.148
                   6        738         65      0.213     0.0154      0.174     0.0677
                   7        738       1619      0.568      0.583      0.577      0.237
                   8        738       2845      0.623      0.574      0.579      0.302
                   9        738          2          1          0   0.000153   0.000122

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_client2_residential

2 epochs completed in 0.055 hours.
Destroying process group...
[rank0]:[W505 03:19:48.097894940 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30428 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/configs/pl02_stable_mix_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/global_checkpoints/stable_mix_all_lowlr_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 03:20:05.136285164 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 03:20:05.188566359 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03428   0.05373  0.005131     7.451:   3%|▎         | 1/31 [00:33<16:56, 33.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03511   0.05475  0.005326     7.614:   6%|▋         | 2/31 [00:34<06:58, 14.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03458    0.0523  0.005218     7.368:  10%|▉         | 3/31 [00:35<03:49,  8.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03407   0.04889  0.004954     7.033:  13%|█▎        | 4/31 [00:36<02:21,  5.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.03407   0.04805  0.004964     6.966:  16%|█▌        | 5/31 [00:36<01:32,  3.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03427   0.04718  0.005029     6.918:  19%|█▉        | 6/31 [00:37<01:03,  2.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.03441   0.04634  0.005097     6.868:  23%|██▎       | 7/31 [00:37<00:45,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.03437   0.04605  0.005128     6.844:  26%|██▌       | 8/31 [00:38<00:34,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640    0.0344   0.04569  0.005014     6.809:  29%|██▉       | 9/31 [00:39<00:26,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.03438   0.04554  0.004986     6.793:  32%|███▏      | 10/31 [00:39<00:21,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.03435   0.04533  0.005008     6.775:  35%|███▌      | 11/31 [00:40<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.03425   0.04487  0.004995      6.73:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.03423   0.04475   0.00494     6.714:  42%|████▏     | 13/31 [00:41<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.03424   0.04439  0.004904     6.682:  45%|████▌     | 14/31 [00:42<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.03428   0.04414  0.004944     6.669:  48%|████▊     | 15/31 [00:42<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.03427   0.04386  0.004929     6.645:  52%|█████▏    | 16/31 [00:43<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640    0.0343   0.04377  0.004887     6.637:  55%|█████▍    | 17/31 [00:43<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03434   0.04369  0.004845      6.63:  58%|█████▊    | 18/31 [00:44<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.03426   0.04344   0.00481     6.601:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03424   0.04355  0.004808     6.608:  65%|██████▍   | 20/31 [00:45<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03426   0.04348  0.004825     6.605:  68%|██████▊   | 21/31 [00:46<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03425   0.04349  0.004794     6.603:  71%|███████   | 22/31 [00:46<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03423   0.04344  0.004779     6.596:  74%|███████▍  | 23/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03423   0.04343  0.004757     6.593:  77%|███████▋  | 24/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03422   0.04329  0.004767     6.583:  81%|████████  | 25/31 [00:48<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03426   0.04325  0.004765     6.582:  84%|████████▍ | 26/31 [00:49<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.494       0.45      0.412      0.232
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.482      0.452      0.411      0.234
                   0        738       1052      0.516      0.557      0.538      0.256
                   1        738         44       0.29      0.182      0.157     0.0694
                   2        738       8622      0.605      0.759      0.757      0.488
                   3        738        151      0.372       0.45      0.429       0.33
                   4        738        467      0.453      0.594       0.56      0.409
                   5        738         70      0.217      0.471      0.297      0.144
                   6        738         65      0.275      0.246      0.169     0.0657
                   7        738       1619      0.531      0.624      0.584      0.245
                   8        738       2845      0.563      0.639       0.62      0.328
                   9        738          2          1          0   0.000353   0.000318

Results saved to /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/runs/pl02_stable_mix_all_lowlr_server_repair

1 epochs completed in 0.029 hours.
Destroying process group...
[rank0]:[W505 03:21:46.143327404 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/stats/02_checkpoints.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/stats/02_manifest.json
/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/pseudogt_learnability/scripts/evaluate_scene_protocol.py --workspace /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt --splits highway,citystreet,residential,total --batch-size 16 --no-plots --verbose --checkpoint warmup_global=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/global_checkpoints/round000_warmup.pt --checkpoint stable_mix_backbone_client0_highway=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_backbone_client0_highway.pt --checkpoint stable_mix_backbone_client1_citystreet=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_backbone_client1_citystreet.pt --checkpoint stable_mix_backbone_client2_residential=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_backbone_client2_residential.pt --checkpoint stable_mix_backbone_aggregate_backbone=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_backbone_aggregate_backbone.pt --checkpoint stable_mix_backbone_server_repair=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_backbone_server_repair.pt --checkpoint stable_mix_all_lowlr_client0_highway=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_all_lowlr_client0_highway.pt --checkpoint stable_mix_all_lowlr_client1_citystreet=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_all_lowlr_client1_citystreet.pt --checkpoint stable_mix_all_lowlr_client2_residential=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_all_lowlr_client2_residential.pt --checkpoint stable_mix_all_lowlr_aggregate_all=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_all_lowlr_aggregate_all.pt --checkpoint stable_mix_all_lowlr_server_repair=/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/checkpoints/stable_mix_all_lowlr_server_repair.pt
Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/validation_reports/paper_protocol_eval_manifest.json
Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/validation_reports/paper_protocol_eval_summary.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/validation_reports/paper_protocol_classwise_summary.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt/validation_reports/paper_protocol_eval_summary.md

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_pseudogt_learnability_02.py', '--workspace-root', '/app/Object_Detection/pseudogt_learnability/output/02_stable_pseudogt', '--variants', 'stable_mix_backbone,stable_mix_all_lowlr', '--batch-size', '160', '--workers', '8', '--gpus', '2', '--master-port', '30421', '--server-repair-epochs', '1', '--evaluate', '--classwise', '--no-eval-plots'], returncode=0)

## Pseudo Label Stats

The first thing to inspect is not mAP, but whether each client keeps a
reasonable number of stable boxes without being dominated by one easy
class.

In [4]:
import json
import pandas as pd

stats_csv = WORKSPACE / "stats" / "02_pseudo_label_stats.csv"
stats_json = WORKSPACE / "stats" / "02_pseudo_label_stats.json"
if stats_csv.exists():
    stats = pd.read_csv(stats_csv)
    display(stats)
else:
    print("No pseudo-label stats yet:", stats_csv)

if stats_json.exists():
    payload = json.loads(stats_json.read_text())
    for client, row in payload.get("clients", {}).items():
        print(client, row.get("class_counts", {}))

,client,source_images_scanned,pseudo_images_kept,pseudo_boxes_kept,boxes_per_kept_image,mean_conf,mean_stability,mean_score,train_list
0,client0_highway,5000,4984,56681,11.3726,0.579681,0.896063,0.528128,/app/Object_Detection/pseudogt_learnability/ou...
1,client1_citystreet,5000,4998,91008,18.2089,0.530326,0.880391,0.475728,/app/Object_Detection/pseudogt_learnability/ou...
2,client2_residential,5000,4994,59808,11.9760,0.634273,0.900271,0.578506,/app/Object_Detection/pseudogt_learnability/ou...

client0_highway {'0': 777, '2': 34396, '3': 218, '4': 1402, '5': 69, '7': 4111, '8': 15708}
client1_citystreet {'0': 7596, '1': 1, '2': 47871, '3': 462, '4': 1692, '5': 509, '7': 14931, '8': 17946}
client2_residential {'0': 1889, '1': 1, '2': 41465, '3': 165, '4': 867, '5': 301, '7': 4807, '8': 10313}

## Evaluation Summary

Main success criterion: an aggregate or repaired checkpoint should
beat `warmup_global` on `total` mAP@0.5:0.95.  Secondary criterion:
a client checkpoint improves its matching scene split without a large
total collapse.

In [5]:
summary_csv = WORKSPACE / "validation_reports" / "paper_protocol_eval_summary.csv"
if not summary_csv.exists():
    print("Evaluation summary is not available yet:", summary_csv)
else:
    df = pd.read_csv(summary_csv)
    ok = df[df["status"].eq("ok")].copy()
    total = ok[ok["split"].isin(["total", "scene_total"])].copy()
    total = total.sort_values("map50_95", ascending=False)
    display(total[["checkpoint_label", "split", "precision", "recall", "map50", "map50_95"]])

    warm = total[total["checkpoint_label"].eq("warmup_global")]
    if not warm.empty:
        base = float(warm.iloc[0]["map50_95"])
        total["delta_map50_95_vs_warmup"] = total["map50_95"].astype(float) - base
        display(total[["checkpoint_label", "map50", "map50_95", "delta_map50_95_vs_warmup"]])

,checkpoint_label,split,precision,recall,map50,map50_95
43,stable_mix_all_lowlr_server_repair,scene_total,0.505,0.401,0.381,0.2120
23,stable_mix_backbone_server_repair,scene_total,0.493,0.400,0.377,0.2100
3,warmup_global,scene_total,0.532,0.337,0.352,0.1890
39,stable_mix_all_lowlr_aggregate_all,scene_total,0.492,0.331,0.308,0.1740
27,stable_mix_all_lowlr_client0_highway,scene_total,0.492,0.321,0.302,0.1700
35,stable_mix_all_lowlr_client2_residential,scene_total,0.480,0.324,0.304,0.1690
31,stable_mix_all_lowlr_client1_citystreet,scene_total,0.479,0.296,0.271,0.1520
7,stable_mix_backbone_client0_highway,scene_total,0.478,0.283,0.269,0.1470
15,stable_mix_backbone_client2_residential,scene_total,0.456,0.287,0.262,0.1420
19,stable_mix_backbone_aggregate_backbone,scene_total,0.474,0.274,0.253,0.1400
11,stable_mix_backbone_client1_citystreet,scene_total,0.423,0.199,0.180,0.0976

,checkpoint_label,map50,map50_95,delta_map50_95_vs_warmup
43,stable_mix_all_lowlr_server_repair,0.381,0.2120,0.0230
23,stable_mix_backbone_server_repair,0.377,0.2100,0.0210
3,warmup_global,0.352,0.1890,0.0000
39,stable_mix_all_lowlr_aggregate_all,0.308,0.1740,-0.0150
27,stable_mix_all_lowlr_client0_highway,0.302,0.1700,-0.0190
35,stable_mix_all_lowlr_client2_residential,0.304,0.1690,-0.0200
31,stable_mix_all_lowlr_client1_citystreet,0.271,0.1520,-0.0370
7,stable_mix_backbone_client0_highway,0.269,0.1470,-0.0420
15,stable_mix_backbone_client2_residential,0.262,0.1420,-0.0470
19,stable_mix_backbone_aggregate_backbone,0.253,0.1400,-0.0490
11,stable_mix_backbone_client1_citystreet,0.180,0.0976,-0.0914

## Scene-Specific View

In [6]:
if summary_csv.exists():
    scene_rows = ok[ok["split"].isin(["highway", "citystreet", "residential"])].copy()
    display(scene_rows.sort_values(["split", "map50_95"], ascending=[True, False])[
        ["checkpoint_label", "split", "precision", "recall", "map50", "map50_95"]
    ])

,checkpoint_label,split,precision,recall,map50,map50_95
41,stable_mix_all_lowlr_server_repair,citystreet,0.504,0.407,0.386,0.2150
21,stable_mix_backbone_server_repair,citystreet,0.493,0.406,0.382,0.2130
1,warmup_global,citystreet,0.528,0.342,0.357,0.1910
37,stable_mix_all_lowlr_aggregate_all,citystreet,0.493,0.335,0.312,0.1770
25,stable_mix_all_lowlr_client0_highway,citystreet,0.483,0.334,0.312,0.1760
33,stable_mix_all_lowlr_client2_residential,citystreet,0.482,0.332,0.311,0.1730
5,stable_mix_backbone_client0_highway,citystreet,0.473,0.297,0.280,0.1540
29,stable_mix_all_lowlr_client1_citystreet,citystreet,0.483,0.293,0.269,0.1500
13,stable_mix_backbone_client2_residential,citystreet,0.455,0.294,0.268,0.1460
17,stable_mix_backbone_aggregate_backbone,citystreet,0.473,0.277,0.256,0.1420
9,stable_mix_backbone_client1_citystreet,citystreet,0.423,0.190,0.174,0.0939
40,stable_mix_all_lowlr_server_repair,highway,0.560,0.333,0.340,0.1910
20,stable_mix_backbone_server_repair,highway,0.526,0.349,0.338,0.1890
0,warmup_global,highway,0.581,0.298,0.308,0.1680
32,stable_mix_all_lowlr_client2_residential,highway,0.475,0.297,0.277,0.1560
36,stable_mix_all_lowlr_aggregate_all,highway,0.478,0.303,0.272,0.1530
28,stable_mix_all_lowlr_client1_citystreet,highway,0.516,0.280,0.261,0.1480
12,stable_mix_backbone_client2_residential,highway,0.491,0.280,0.259,0.1420
24,stable_mix_all_lowlr_client0_highway,highway,0.539,0.248,0.247,0.1370
16,stable_mix_backbone_aggregate_backbone,highway,0.489,0.243,0.229,0.1280
4,stable_mix_backbone_client0_highway,highway,0.466,0.216,0.203,0.1090
8,stable_mix_backbone_client1_citystreet,highway,0.399,0.208,0.189,0.1070
42,stable_mix_all_lowlr_server_repair,residential,0.512,0.411,0.417,0.2390
22,stable_mix_backbone_server_repair,residential,0.533,0.394,0.412,0.2360
2,warmup_global,residential,0.434,0.406,0.388,0.2140
26,stable_mix_all_lowlr_client0_highway,residential,0.525,0.362,0.370,0.2120
38,stable_mix_all_lowlr_aggregate_all,residential,0.525,0.344,0.362,0.2090
30,stable_mix_all_lowlr_client1_citystreet,residential,0.486,0.332,0.337,0.1950
6,stable_mix_backbone_client0_highway,residential,0.471,0.329,0.324,0.1830
34,stable_mix_all_lowlr_client2_residential,residential,0.448,0.304,0.307,0.1770
18,stable_mix_backbone_aggregate_backbone,residential,0.403,0.302,0.279,0.1540
10,stable_mix_backbone_client1_citystreet,residential,0.387,0.243,0.222,0.1230
14,stable_mix_backbone_client2_residential,residential,0.395,0.233,0.217,0.1190

## Discord Notification

In [7]:
try:
    sys.path.insert(0, str(PROJECT_ROOT.parent))
    from notebook_notify import notify_discord

    msg = "PseudoGT Learnability 02 finished. Check output/02_stable_pseudogt/validation_reports/paper_protocol_eval_summary.md"
    result = notify_discord(
        msg,
        title="PseudoGT Learnability 02",
        context={"project": str(PROJECT_ROOT), "workspace": str(WORKSPACE)},
        fail_silently=True,
    )
    print(result)
except Exception as exc:
    print("Discord notification skipped:", exc)

DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)