# 03 Repair-Oriented Multi-Round PseudoGT

03 changes the objective.  The target is no longer "client pseudo-GT
training alone should beat warmup."  The target is:

> pseudo-GT client adaptation + aggregation + supervised server
> repair should produce a repaired global model that improves or
> plateaus across multiple rounds.

## Round Definition

Each round is:

1. generate stable pseudo labels from the current repaired global model
2. train each client with source cloudy GT plus strict target pseudo labels
3. aggregate client checkpoints
4. repair the aggregate on supervised source cloudy GT
5. evaluate the repaired global checkpoint
6. carry the repaired global checkpoint into the next round

The main checkpoint is the repaired global model, not the client or
aggregate checkpoint.

In [1]:
from pathlib import Path
import os
import subprocess
import sys

cwd = Path.cwd().resolve()
if cwd.name == "notebooks":
    PROJECT_ROOT = cwd.parent
elif (cwd / "pseudogt_learnability").exists():
    PROJECT_ROOT = cwd / "pseudogt_learnability"
else:
    PROJECT_ROOT = cwd
os.chdir(PROJECT_ROOT)
WORKSPACE = PROJECT_ROOT / "output" / "03_repair_oriented_multiround"
print(PROJECT_ROOT)
print(WORKSPACE)
print((PROJECT_ROOT / "checkpoints" / "round000_warmup.pt").exists())

/app/Object_Detection/pseudogt_learnability
/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround
True

## Setup Check

This creates/reuses the scene-client lists and copies the warmup
checkpoint into the 03 workspace.

In [2]:
subprocess.run([
    sys.executable,
    "scripts/run_pseudogt_learnability_03.py",
    "--workspace-root", str(WORKSPACE),
    "--setup-only",
], check=True)

{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/server_phase2_orthogonal.yaml"
  }
}
Project root: /app/Object_Detection/pseudogt_learnability
Workspace: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround
Warmup: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "weather": "highway",
      "scene": "highway"
    },
    {
      "id": 1,
      "weather": "citystreet",
      "scene": "city street"
    },
    {
      "id": 2,
      "weather": "residential",
      "scene": "residential"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_total_val.txt",
    "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9864,
    "source_val_images": 738,
    "validation_target": "scene_total"
  },
  "variant": {
    "name": "repair_oriented_all_lowlr",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_epochs": 1,
    "client_lr0": 0.0005,
    "source_repeat": 2,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "note": "Low-LR full-model client adaptation. Source GT is repeated to keep the detector close enough for server repair, while stricter stable pseudo boxes inject target-domain signal."
  }
}
Setup complete.

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_pseudogt_learnability_03.py', '--workspace-root', '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround', '--setup-only'], returncode=0)

## Run 03

Defaults are intentionally more conservative than 02:

- one client epoch per round
- source GT repeated twice in client training
- stricter stability/score thresholds
- max 12 pseudo boxes per image
- client checkpoints are not evaluated by default

For a short smoke test, set `MAX_IMAGES_PER_CLIENT = 1200` and
`ROUNDS = 2`.  For the real run, keep `MAX_IMAGES_PER_CLIENT = 0`.

In [3]:
ROUNDS = 3
MAX_IMAGES_PER_CLIENT = 0
EVAL_CLIENTS = False

cmd = [
    sys.executable,
    "scripts/run_pseudogt_learnability_03.py",
    "--workspace-root", str(WORKSPACE),
    "--variant", "repair_oriented_all_lowlr",
    "--rounds", str(ROUNDS),
    "--batch-size", "160",
    "--workers", "8",
    "--gpus", "2",
    "--master-port", "30531",
    "--server-repair-epochs", "1",
    "--evaluate",
    "--classwise",
    "--no-eval-plots",
]
if MAX_IMAGES_PER_CLIENT > 0:
    cmd.extend(["--max-images-per-client", str(MAX_IMAGES_PER_CLIENT)])
if EVAL_CLIENTS:
    cmd.append("--eval-clients")
print(" ".join(cmd))
subprocess.run(cmd, check=True)

/root/micromamba/envs/al_yolov8/bin/python scripts/run_pseudogt_learnability_03.py --workspace-root /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround --variant repair_oriented_all_lowlr --rounds 3 --batch-size 160 --workers 8 --gpus 2 --master-port 30531 --server-repair-epochs 1 --evaluate --classwise --no-eval-plots
{
  "manifest": {
    "paper": "Navigating Data Heterogeneity in Federated Learning: A Semi-Supervised Federated Object Detection",
    "variant": "scene clients: highway, city street, residential",
    "official_ssfod_repo": "https://github.com/Kthyeon/ssfod",
    "official_ssfod_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "efficientteacher_repo": "https://github.com/AlibabaResearch/efficientteacher",
    "efficientteacher_sha": "6f985a45c8432cc40a8362ed44d1f7a8498bd5d6",
    "server": {
      "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
      "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.txt",
      "val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_total_val.txt",
      "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.txt",
      "train_images": 4881,
      "val_images": 9864,
      "source_val_images": 738,
      "validation_target": "scene_total"
    },
    "clients": [
      {
        "id": 0,
        "weather": "highway",
        "scene": "highway",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/client_0_highway_target.txt",
        "images": 5000
      },
      {
        "id": 1,
        "weather": "citystreet",
        "scene": "city street",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/client_1_citystreet_target.txt",
        "images": 5000
      },
      {
        "id": 2,
        "weather": "residential",
        "scene": "residential",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/client_2_residential_target.txt",
        "images": 5000
      }
    ],
    "paper_evaluation": {
      "splits": [
        {
          "name": "highway",
          "raw_scene": "highway",
          "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_highway_val.txt",
          "images": 2499,
          "boxes": 36377,
          "class_counts": {
            "car": 22337,
            "traffic sign": 9278,
            "traffic light": 2808,
            "truck": 1040,
            "person": 449,
            "bus": 309,
            "rider": 52,
            "motor": 31,
            "bike": 63,
            "train": 10
          }
        },
        {
          "name": "citystreet",
          "raw_scene": "city street",
          "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_citystreet_val.txt",
          "images": 6112,
          "boxes": 127178,
          "class_counts": {
            "traffic sign": 22635,
            "traffic light": 22518,
            "car": 63950,
            "rider": 546,
            "motor": 361,
            "person": 12248,
            "bus": 1229,
            "truck": 2812,
            "bike": 874,
            "train": 5
          }
        },
        {
          "name": "residential",
          "raw_scene": "residential",
          "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_residential_val.txt",
          "images": 1253,
          "boxes": 20855,
          "class_counts": {
            "traffic light": 1442,
            "traffic sign": 2652,
            "person": 669,
            "rider": 59,
            "bike": 101,
            "car": 15396,
            "bus": 113,
            "truck": 359,
            "motor": 64
          }
        }
      ],
      "total": {
        "name": "scene_total",
        "list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_total_val.txt",
        "images": 9864,
        "source_splits": [
          "highway",
          "citystreet",
          "residential"
        ]
      }
    },
    "classes": [
      "person",
      "rider",
      "car",
      "bus",
      "truck",
      "bike",
      "motor",
      "traffic light",
      "traffic sign",
      "train"
    ],
    "paper_schedule": {
      "warmup_epochs": 50,
      "phase1_rounds": 100,
      "phase2_rounds": 150,
      "local_epochs": 1
    }
  },
  "configs": {
    "server_warmup": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/server_warmup_yolov5l_bdd100k.yaml",
    "client_0_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_0_highway_phase1.yaml",
    "client_0_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_0_highway_phase2.yaml",
    "client_1_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_1_citystreet_phase1.yaml",
    "client_1_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_1_citystreet_phase2.yaml",
    "client_2_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_2_residential_phase1.yaml",
    "client_2_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/client_2_residential_phase2.yaml",
    "server_phase1": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/server_phase1_backbone.yaml",
    "server_phase2": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/server_phase2_orthogonal.yaml"
  }
}
Project root: /app/Object_Detection/pseudogt_learnability
Workspace: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround
Warmup: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "weather": "highway",
      "scene": "highway"
    },
    {
      "id": 1,
      "weather": "citystreet",
      "scene": "city street"
    },
    {
      "id": 2,
      "weather": "residential",
      "scene": "residential"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/paper_eval_scene_total_val.txt",
    "source_val_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9864,
    "source_val_images": 738,
    "validation_target": "scene_total"
  },
  "variant": {
    "name": "repair_oriented_all_lowlr",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_epochs": 1,
    "client_lr0": 0.0005,
    "source_repeat": 2,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "note": "Low-LR full-model client adaptation. Source GT is repeated to keep the detector close enough for server repair, while stricter stable pseudo boxes inject target-domain signal."
  }
}

=== round001: pseudo labels from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round000_warmup.pt ===

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

round001 client0_highway: pseudo scan 1/5000 images, kept 4 boxes
round001 client0_highway: pseudo scan 250/5000 images, kept 2154 boxes
round001 client0_highway: pseudo scan 500/5000 images, kept 4237 boxes
round001 client0_highway: pseudo scan 750/5000 images, kept 6330 boxes
round001 client0_highway: pseudo scan 1000/5000 images, kept 8554 boxes
round001 client0_highway: pseudo scan 1250/5000 images, kept 10681 boxes
round001 client0_highway: pseudo scan 1500/5000 images, kept 12706 boxes
round001 client0_highway: pseudo scan 1750/5000 images, kept 14864 boxes
round001 client0_highway: pseudo scan 2000/5000 images, kept 16978 boxes
round001 client0_highway: pseudo scan 2250/5000 images, kept 19074 boxes
round001 client0_highway: pseudo scan 2500/5000 images, kept 21280 boxes
round001 client0_highway: pseudo scan 2750/5000 images, kept 23305 boxes
round001 client0_highway: pseudo scan 3000/5000 images, kept 25525 boxes
round001 client0_highway: pseudo scan 3250/5000 images, kept 27683 boxes
round001 client0_highway: pseudo scan 3500/5000 images, kept 29763 boxes
round001 client0_highway: pseudo scan 3750/5000 images, kept 31832 boxes
round001 client0_highway: pseudo scan 4000/5000 images, kept 33803 boxes
round001 client0_highway: pseudo scan 4250/5000 images, kept 35909 boxes
round001 client0_highway: pseudo scan 4500/5000 images, kept 38010 boxes
round001 client0_highway: pseudo scan 4750/5000 images, kept 40167 boxes
round001 client0_highway: pseudo scan 5000/5000 images, kept 42331 boxes
{
  "round": "round001",
  "client": "client0_highway",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4926,
  "pseudo_boxes_kept": 33794,
  "boxes_per_kept_image": 6.860332927324401,
  "mean_conf": 0.7145847252385393,
  "mean_stability": 0.9373526282336448,
  "mean_score": 0.6732649244324678,
  "class_counts": {
    "0": 396,
    "2": 19049,
    "3": 181,
    "4": 964,
    "5": 25,
    "7": 2053,
    "8": 11126
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client0_highway_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round001_client0_highway_stable_boxes.csv"
}
round001 client1_citystreet: pseudo scan 1/5000 images, kept 6 boxes
round001 client1_citystreet: pseudo scan 250/5000 images, kept 2577 boxes
round001 client1_citystreet: pseudo scan 500/5000 images, kept 5170 boxes
round001 client1_citystreet: pseudo scan 750/5000 images, kept 7786 boxes
round001 client1_citystreet: pseudo scan 1000/5000 images, kept 10274 boxes
round001 client1_citystreet: pseudo scan 1250/5000 images, kept 12832 boxes
round001 client1_citystreet: pseudo scan 1500/5000 images, kept 15404 boxes
round001 client1_citystreet: pseudo scan 1750/5000 images, kept 18096 boxes
round001 client1_citystreet: pseudo scan 2000/5000 images, kept 20611 boxes
round001 client1_citystreet: pseudo scan 2250/5000 images, kept 23183 boxes
round001 client1_citystreet: pseudo scan 2500/5000 images, kept 25668 boxes
round001 client1_citystreet: pseudo scan 2750/5000 images, kept 28169 boxes
round001 client1_citystreet: pseudo scan 3000/5000 images, kept 30820 boxes
round001 client1_citystreet: pseudo scan 3250/5000 images, kept 33405 boxes
round001 client1_citystreet: pseudo scan 3500/5000 images, kept 35989 boxes
round001 client1_citystreet: pseudo scan 3750/5000 images, kept 38562 boxes
round001 client1_citystreet: pseudo scan 4000/5000 images, kept 41138 boxes
round001 client1_citystreet: pseudo scan 4250/5000 images, kept 43786 boxes
round001 client1_citystreet: pseudo scan 4500/5000 images, kept 46378 boxes
round001 client1_citystreet: pseudo scan 4750/5000 images, kept 49012 boxes
round001 client1_citystreet: pseudo scan 5000/5000 images, kept 51538 boxes
{
  "round": "round001",
  "client": "client1_citystreet",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4969,
  "pseudo_boxes_kept": 44090,
  "boxes_per_kept_image": 8.873012678607365,
  "mean_conf": 0.7054348337924732,
  "mean_stability": 0.9334032468567037,
  "mean_score": 0.6620897776387787,
  "class_counts": {
    "0": 3218,
    "2": 23193,
    "3": 348,
    "4": 985,
    "5": 120,
    "7": 6444,
    "8": 9782
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client1_citystreet_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round001_client1_citystreet_stable_boxes.csv"
}
round001 client2_residential: pseudo scan 1/5000 images, kept 9 boxes
round001 client2_residential: pseudo scan 250/5000 images, kept 2524 boxes
round001 client2_residential: pseudo scan 500/5000 images, kept 5085 boxes
round001 client2_residential: pseudo scan 750/5000 images, kept 7615 boxes
round001 client2_residential: pseudo scan 1000/5000 images, kept 10061 boxes
round001 client2_residential: pseudo scan 1250/5000 images, kept 12530 boxes
round001 client2_residential: pseudo scan 1500/5000 images, kept 15022 boxes
round001 client2_residential: pseudo scan 1750/5000 images, kept 17468 boxes
round001 client2_residential: pseudo scan 2000/5000 images, kept 19918 boxes
round001 client2_residential: pseudo scan 2250/5000 images, kept 22389 boxes
round001 client2_residential: pseudo scan 2500/5000 images, kept 24823 boxes
round001 client2_residential: pseudo scan 2750/5000 images, kept 27331 boxes
round001 client2_residential: pseudo scan 3000/5000 images, kept 29881 boxes
round001 client2_residential: pseudo scan 3250/5000 images, kept 32349 boxes
round001 client2_residential: pseudo scan 3500/5000 images, kept 34789 boxes
round001 client2_residential: pseudo scan 3750/5000 images, kept 37301 boxes
round001 client2_residential: pseudo scan 4000/5000 images, kept 39881 boxes
round001 client2_residential: pseudo scan 4250/5000 images, kept 42418 boxes
round001 client2_residential: pseudo scan 4500/5000 images, kept 44987 boxes
round001 client2_residential: pseudo scan 4750/5000 images, kept 47493 boxes
round001 client2_residential: pseudo scan 5000/5000 images, kept 50011 boxes
{
  "round": "round001",
  "client": "client2_residential",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4959,
  "pseudo_boxes_kept": 32721,
  "boxes_per_kept_image": 6.598306110102843,
  "mean_conf": 0.7578452097788871,
  "mean_stability": 0.9480777836028836,
  "mean_score": 0.7216690847785451,
  "class_counts": {
    "0": 1028,
    "2": 22505,
    "3": 131,
    "4": 580,
    "5": 85,
    "7": 2095,
    "8": 6297
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client2_residential_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round001_client2_residential_stable_boxes.csv"
}
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round001_pseudo_label_stats.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round001_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30531 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round001_repair_oriented_all_lowlr_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round001_repair_oriented_all_lowlr_client0_highway_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client0_highway_stable_train' images and labels...10256 found, 4432 missing, 0 empty, 0 corrupted: 100%|██████████| 14688/14688 [00:00<00:00, 15186.71it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client0_highway_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.428755503060238
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client0_highway_stable_train.cache' images and labels... 10256 found, 4432 missing, 0 empty, 0 corrupted: 100%|██████████| 14688/14688 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 5215.88it/s]
val: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 04:55:09.489678417 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 04:55:09.515455152 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/59 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      1341       640   0.03797   0.04035  0.004934     6.661:   2%|▏         | 1/59 [00:34<33:19, 34.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1470       640   0.03933   0.04263   0.00534     6.984:   3%|▎         | 2/59 [00:35<14:10, 14.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1472       640    0.0397   0.04408  0.005632     7.153:   5%|▌         | 3/59 [00:36<08:04,  8.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1450       640   0.03947    0.0437  0.005642     7.105:   7%|▋         | 4/59 [00:37<05:10,  5.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1517       640   0.03916   0.04321  0.005584     7.036:   8%|▊         | 5/59 [00:38<03:32,  3.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1187       640   0.03851   0.04203  0.005667     6.896:  10%|█         | 6/59 [00:39<02:34,  2.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1321       640   0.03829   0.04125  0.005764     6.824:  12%|█▏        | 7/59 [00:40<01:57,  2.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1627       640   0.03804   0.04104  0.005855     6.795:  14%|█▎        | 8/59 [00:41<01:33,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1395       640   0.03779   0.04057  0.005842     6.737:  15%|█▌        | 9/59 [00:42<01:16,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1380       640    0.0376    0.0402  0.005844     6.692:  17%|█▋        | 10/59 [00:43<01:05,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1498       640    0.0375   0.04005  0.005806     6.668:  19%|█▊        | 11/59 [00:44<00:58,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1391       640   0.03744   0.03962  0.005815     6.631:  20%|██        | 12/59 [00:45<00:53,  1.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1404       640   0.03729   0.03931  0.005796     6.592:  22%|██▏       | 13/59 [00:46<00:52,  1.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1193       640   0.03714   0.03889    0.0058     6.546:  24%|██▎       | 14/59 [00:47<00:47,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1215       640   0.03709   0.03856  0.005882     6.523:  25%|██▌       | 15/59 [00:48<00:44,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1168       640     0.037   0.03829  0.005902     6.495:  27%|██▋       | 16/59 [00:49<00:41,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1285       640   0.03694    0.0381   0.00592     6.476:  29%|██▉       | 17/59 [00:49<00:39,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1160       640   0.03678    0.0377  0.005913     6.432:  31%|███       | 18/59 [00:50<00:38,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1207       640   0.03675   0.03735  0.005899       6.4:  32%|███▏      | 19/59 [00:51<00:36,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1386       640    0.0367    0.0373  0.005889     6.391:  34%|███▍      | 20/59 [00:52<00:35,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1288       640   0.03669   0.03712  0.005878     6.375:  36%|███▌      | 21/59 [00:53<00:33,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1106       640   0.03657   0.03681  0.005863     6.339:  37%|███▋      | 22/59 [00:54<00:32,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1250       640   0.03651   0.03662  0.005855     6.319:  39%|███▉      | 23/59 [00:55<00:31,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1312       640   0.03645   0.03644  0.005856       6.3:  41%|████      | 24/59 [00:56<00:31,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1316       640   0.03642   0.03628  0.005842     6.283:  42%|████▏     | 25/59 [00:57<00:30,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1214       640    0.0364   0.03608  0.005829     6.265:  44%|████▍     | 26/59 [00:57<00:29,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.503      0.434      0.396      0.219
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.494      0.428      0.393      0.219
                   0        738       1052      0.456      0.562      0.528      0.251
                   1        738         44      0.349      0.244      0.172     0.0663
                   2        738       8622       0.66      0.719       0.74      0.472
                   3        738        151      0.374      0.344      0.376      0.294
                   4        738        467      0.483      0.572      0.531       0.39
                   5        738         70      0.236      0.443       0.25      0.122
                   6        738         65      0.233      0.185      0.158     0.0622
                   7        738       1619      0.533      0.624      0.588      0.237
                   8        738       2845      0.621      0.587      0.588      0.294
                   9        738          2          1          0   0.000195   0.000156

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway

1 epochs completed in 0.038 hours.
Destroying process group...
[rank0]:[W505 04:57:24.832386500 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30532 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round001_repair_oriented_all_lowlr_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round001_repair_oriented_all_lowlr_client1_citystreet_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client1_citystreet_stable_train' images and labels...10077 found, 4654 missing, 0 empty, 0 corrupted: 100%|██████████| 14731/14731 [00:01<00:00, 9889.23it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client1_citystreet_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.185946512847405
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client1_citystreet_stable_train.cache' images and labels... 10077 found, 4654 missing, 0 empty, 0 corrupted: 100%|██████████| 14731/14731 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client1_citystreet
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 04:57:42.345094114 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 04:57:42.358177658 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      1213       640   0.03966   0.04534  0.006562     7.326:   2%|▏         | 1/60 [00:33<33:19, 33.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1332       640      0.04   0.04738  0.006265     7.491:   3%|▎         | 2/60 [00:35<14:08, 14.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1240       640   0.03931   0.04789  0.005924      7.45:   5%|▌         | 3/60 [00:36<08:05,  8.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1354       640   0.03886   0.04788  0.005861     7.408:   7%|▋         | 4/60 [00:37<05:14,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1375       640   0.03845    0.0473  0.005768     7.322:   8%|▊         | 5/60 [00:38<03:35,  3.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1169       640   0.03816   0.04605  0.005728     7.196:  10%|█         | 6/60 [00:39<02:35,  2.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1451       640    0.0376   0.04532  0.005683     7.088:  12%|█▏        | 7/60 [00:40<01:58,  2.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1279       640    0.0373   0.04439  0.005679     6.989:  13%|█▎        | 8/60 [00:41<01:34,  1.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1487       640   0.03722   0.04401  0.005664     6.952:  15%|█▌        | 9/60 [00:41<01:17,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1315       640   0.03713   0.04367  0.005684     6.919:  17%|█▋        | 10/60 [00:42<01:07,  1.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1460       640   0.03708   0.04342  0.005681     6.894:  18%|█▊        | 11/60 [00:43<00:59,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1273       640   0.03716   0.04294  0.005781     6.871:  20%|██        | 12/60 [00:44<00:53,  1.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1355       640   0.03704   0.04271  0.005819     6.846:  22%|██▏       | 13/60 [00:45<00:49,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1045       640    0.0369   0.04208  0.005804     6.783:  23%|██▎       | 14/60 [00:46<00:46,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1147       640   0.03682   0.04153  0.005799     6.732:  25%|██▌       | 15/60 [00:47<00:43,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1233       640   0.03675   0.04112  0.005811     6.694:  27%|██▋       | 16/60 [00:48<00:41,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1256       640   0.03669   0.04094  0.005869     6.679:  28%|██▊       | 17/60 [00:49<00:39,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1164       640   0.03655   0.04062  0.005895     6.646:  30%|███       | 18/60 [00:50<00:39,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1005       640   0.03642   0.04014   0.00582     6.591:  32%|███▏      | 19/60 [00:51<00:38,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1384       640   0.03644   0.04013  0.005808     6.591:  33%|███▎      | 20/60 [00:51<00:37,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1227       640   0.03642   0.03989  0.005794     6.569:  35%|███▌      | 21/60 [00:52<00:36,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1128       640   0.03635   0.03958  0.005774     6.537:  37%|███▋      | 22/60 [00:53<00:35,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1275       640   0.03633   0.03944  0.005773     6.524:  38%|███▊      | 23/60 [00:54<00:34,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1489       640   0.03633   0.03946  0.005741     6.523:  40%|████      | 24/60 [00:55<00:33,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1337       640   0.03632   0.03931  0.005728     6.508:  42%|████▏     | 25/60 [00:56<00:32,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1356       640   0.03626   0.03916  0.005737     6.493:  43%|████▎     | 26/60 [00:57<00:31,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.481      0.424      0.387      0.216
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client1_citystreet/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client1_citystreet/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.495      0.409      0.385      0.216
                   0        738       1052      0.611       0.49      0.513       0.24
                   1        738         44      0.338      0.136      0.153     0.0637
                   2        738       8622       0.58      0.745      0.737       0.46
                   3        738        151      0.286      0.417      0.369      0.292
                   4        738        467      0.413      0.625       0.53      0.384
                   5        738         70      0.276      0.371      0.237      0.116
                   6        738         65      0.335      0.108      0.156      0.062
                   7        738       1619       0.55      0.598      0.571      0.236
                   8        738       2845      0.562      0.599      0.583      0.307
                   9        738          2          1          0    0.00016   0.000128

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client1_citystreet

1 epochs completed in 0.039 hours.
Destroying process group...
[rank0]:[W505 05:00:00.690002906 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30533 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round001_repair_oriented_all_lowlr_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round001_repair_oriented_all_lowlr_client2_residential_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client2_residential_stable_train' images and labels...10110 found, 4611 missing, 0 empty, 0 corrupted: 100%|██████████| 14721/14721 [00:01<00:00, 10458.58it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client2_residential_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.232090181205226
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round001_client2_residential_stable_train.cache' images and labels... 10110 found, 4611 missing, 0 empty, 0 corrupted: 100%|██████████| 14721/14721 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client2_residential
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 05:00:18.480475332 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 05:00:18.515696533 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      1230       640    0.0389    0.0493  0.005622     7.506:   2%|▏         | 1/60 [00:33<33:23, 33.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1260       640   0.03951   0.04877  0.005343      7.49:   3%|▎         | 2/60 [00:35<14:09, 14.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1439       640   0.03933   0.04827  0.005665     7.462:   5%|▌         | 3/60 [00:36<08:01,  8.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1197       640   0.03894    0.0485  0.005653     7.448:   7%|▋         | 4/60 [00:37<05:09,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1459       640   0.03875   0.04768  0.005642     7.365:   8%|▊         | 5/60 [00:38<03:32,  3.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1073       640   0.03818   0.04622  0.005698     7.208:  10%|█         | 6/60 [00:38<02:33,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1294       640   0.03795   0.04566   0.00568     7.143:  12%|█▏        | 7/60 [00:39<01:57,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1382       640   0.03774   0.04495  0.005732     7.073:  13%|█▎        | 8/60 [00:40<01:32,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1337       640   0.03781   0.04459  0.005755     7.052:  15%|█▌        | 9/60 [00:41<01:16,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1368       640   0.03781   0.04398  0.005851     7.011:  17%|█▋        | 10/60 [00:42<01:05,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1322       640   0.03778   0.04356  0.005822     6.973:  18%|█▊        | 11/60 [00:43<00:58,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1317       640    0.0376   0.04305  0.005805     6.917:  20%|██        | 12/60 [00:44<00:52,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1213       640    0.0374   0.04241  0.005854     6.853:  22%|██▏       | 13/60 [00:45<00:48,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1124       640   0.03712   0.04201  0.005865       6.8:  23%|██▎       | 14/60 [00:46<00:45,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1198       640     0.037   0.04169  0.005896     6.767:  25%|██▌       | 15/60 [00:46<00:42,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1333       640   0.03707   0.04156  0.005896     6.762:  27%|██▋       | 16/60 [00:47<00:40,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1185       640   0.03698   0.04121  0.005867     6.725:  28%|██▊       | 17/60 [00:48<00:39,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1035       640   0.03689    0.0407  0.005852     6.675:  30%|███       | 18/60 [00:49<00:37,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1086       640   0.03679    0.0403  0.005826     6.633:  32%|███▏      | 19/60 [00:50<00:36,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1260       640   0.03676   0.04009  0.005809     6.613:  33%|███▎      | 20/60 [00:51<00:35,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1223       640    0.0367   0.03984  0.005817     6.588:  35%|███▌      | 21/60 [00:52<00:34,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1058       640   0.03656   0.03944  0.005769     6.542:  37%|███▋      | 22/60 [00:53<00:33,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1471       640   0.03648   0.03948  0.005751     6.537:  38%|███▊      | 23/60 [00:53<00:31,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1238       640   0.03644   0.03931  0.005735     6.519:  40%|████      | 24/60 [00:54<00:31,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1496       640   0.03638   0.03933   0.00575     6.516:  42%|████▏     | 25/60 [00:55<00:30,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1160       640   0.03634   0.03912   0.00575     6.497:  43%|████▎     | 26/60 [00:56<00:29,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.512      0.392      0.392      0.215
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client2_residential/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client2_residential/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]

                 all        738      14937      0.505      0.398       0.39      0.216
                   0        738       1052      0.505      0.543      0.526      0.247
                   1        738         44      0.356      0.114      0.151     0.0594
                   2        738       8622      0.675       0.69      0.721      0.449
                   3        738        151      0.375      0.397       0.39      0.298
                   4        738        467      0.468       0.58      0.539      0.386
                   5        738         70      0.252      0.357      0.263      0.119
                   6        738         65      0.282     0.0923      0.139     0.0546
                   7        738       1619      0.541      0.613      0.584      0.241
                   8        738       2845      0.592      0.598      0.588      0.305
                   9        738          2          1          0   0.000166   0.000149

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_client2_residential

1 epochs completed in 0.038 hours.
Destroying process group...
[rank0]:[W505 05:02:34.391169371 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30534 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round001_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round001_repair_oriented_all_lowlr_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 10924.37it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 05:02:52.503800149 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 05:02:52.506847954 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03493   0.05423   0.00543     7.567:   3%|▎         | 1/31 [00:33<16:43, 33.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03573   0.05429  0.005611     7.651:   6%|▋         | 2/31 [00:34<06:52, 14.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03521   0.05181  0.005523     7.403:  10%|▉         | 3/31 [00:34<03:46,  8.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03467   0.04864  0.005256     7.085:  13%|█▎        | 4/31 [00:35<02:20,  5.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03466     0.048  0.005258     7.033:  16%|█▌        | 5/31 [00:36<01:31,  3.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03487   0.04726  0.005323     6.996:  19%|█▉        | 6/31 [00:36<01:03,  2.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03501   0.04651   0.00539     6.953:  23%|██▎       | 7/31 [00:37<00:45,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03497    0.0463   0.00542     6.935:  26%|██▌       | 8/31 [00:38<00:33,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03501   0.04602  0.005309     6.907:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03498    0.0459  0.005279     6.893:  32%|███▏      | 10/31 [00:39<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03495   0.04573  0.005294     6.878:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03485   0.04531  0.005272     6.835:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03483   0.04521  0.005218     6.821:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03483   0.04485  0.005178     6.789:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03486   0.04462  0.005214     6.776:  48%|████▊     | 15/31 [00:42<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03485   0.04434  0.005196     6.751:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03488   0.04427  0.005152     6.744:  55%|█████▍    | 17/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03491   0.04419  0.005109     6.737:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03484   0.04394   0.00507     6.708:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03481   0.04405  0.005071     6.715:  65%|██████▍   | 20/31 [00:45<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03484   0.04398  0.005088     6.712:  68%|██████▊   | 21/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03482     0.044  0.005052      6.71:  71%|███████   | 22/31 [00:46<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03479   0.04395  0.005041     6.702:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03479   0.04394   0.00502       6.7:  77%|███████▋  | 24/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03478    0.0438  0.005027     6.689:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03482   0.04375  0.005022     6.687:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.493      0.447      0.409      0.227
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.482      0.449      0.408      0.229
                   0        738       1052      0.502      0.558       0.54      0.255
                   1        738         44      0.292      0.182      0.166     0.0661
                   2        738       8622      0.593      0.758      0.753      0.483
                   3        738        151      0.351      0.437      0.401      0.308
                   4        738        467      0.458      0.591      0.555      0.407
                   5        738         70       0.26        0.5      0.287      0.138
                   6        738         65      0.274      0.209      0.173     0.0611
                   7        738       1619      0.532      0.619      0.586      0.242
                   8        738       2845      0.556      0.639      0.618      0.326
                   9        738          2          1          0   0.000323   0.000291

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round001_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.029 hours.
Destroying process group...
[rank0]:[W505 05:04:34.025083853 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_checkpoints.csv

=== round002: pseudo labels from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt ===

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round002 client0_highway: pseudo scan 1/5000 images, kept 3 boxes
round002 client0_highway: pseudo scan 250/5000 images, kept 2078 boxes
round002 client0_highway: pseudo scan 500/5000 images, kept 4052 boxes
round002 client0_highway: pseudo scan 750/5000 images, kept 6068 boxes
round002 client0_highway: pseudo scan 1000/5000 images, kept 8213 boxes
round002 client0_highway: pseudo scan 1250/5000 images, kept 10278 boxes
round002 client0_highway: pseudo scan 1500/5000 images, kept 12213 boxes
round002 client0_highway: pseudo scan 1750/5000 images, kept 14300 boxes
round002 client0_highway: pseudo scan 2000/5000 images, kept 16346 boxes
round002 client0_highway: pseudo scan 2250/5000 images, kept 18364 boxes
round002 client0_highway: pseudo scan 2500/5000 images, kept 20502 boxes
round002 client0_highway: pseudo scan 2750/5000 images, kept 22451 boxes
round002 client0_highway: pseudo scan 3000/5000 images, kept 24594 boxes
round002 client0_highway: pseudo scan 3250/5000 images, kept 26659 boxes
round002 client0_highway: pseudo scan 3500/5000 images, kept 28690 boxes
round002 client0_highway: pseudo scan 3750/5000 images, kept 30703 boxes
round002 client0_highway: pseudo scan 4000/5000 images, kept 32604 boxes
round002 client0_highway: pseudo scan 4250/5000 images, kept 34607 boxes
round002 client0_highway: pseudo scan 4500/5000 images, kept 36620 boxes
round002 client0_highway: pseudo scan 4750/5000 images, kept 38711 boxes
round002 client0_highway: pseudo scan 5000/5000 images, kept 40823 boxes
{
  "round": "round002",
  "client": "client0_highway",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4885,
  "pseudo_boxes_kept": 32150,
  "boxes_per_kept_image": 6.5813715455475945,
  "mean_conf": 0.744332105284716,
  "mean_stability": 0.9499009026542978,
  "mean_score": 0.7103484734069003,
  "class_counts": {
    "0": 353,
    "2": 18371,
    "3": 216,
    "4": 1174,
    "5": 28,
    "7": 1563,
    "8": 10445
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client0_highway_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round002_client0_highway_stable_boxes.csv"
}
round002 client1_citystreet: pseudo scan 1/5000 images, kept 6 boxes
round002 client1_citystreet: pseudo scan 250/5000 images, kept 2498 boxes
round002 client1_citystreet: pseudo scan 500/5000 images, kept 4990 boxes
round002 client1_citystreet: pseudo scan 750/5000 images, kept 7498 boxes
round002 client1_citystreet: pseudo scan 1000/5000 images, kept 9913 boxes
round002 client1_citystreet: pseudo scan 1250/5000 images, kept 12365 boxes
round002 client1_citystreet: pseudo scan 1500/5000 images, kept 14844 boxes
round002 client1_citystreet: pseudo scan 1750/5000 images, kept 17466 boxes
round002 client1_citystreet: pseudo scan 2000/5000 images, kept 19911 boxes
round002 client1_citystreet: pseudo scan 2250/5000 images, kept 22422 boxes
round002 client1_citystreet: pseudo scan 2500/5000 images, kept 24799 boxes
round002 client1_citystreet: pseudo scan 2750/5000 images, kept 27229 boxes
round002 client1_citystreet: pseudo scan 3000/5000 images, kept 29805 boxes
round002 client1_citystreet: pseudo scan 3250/5000 images, kept 32287 boxes
round002 client1_citystreet: pseudo scan 3500/5000 images, kept 34772 boxes
round002 client1_citystreet: pseudo scan 3750/5000 images, kept 37277 boxes
round002 client1_citystreet: pseudo scan 4000/5000 images, kept 39754 boxes
round002 client1_citystreet: pseudo scan 4250/5000 images, kept 42295 boxes
round002 client1_citystreet: pseudo scan 4500/5000 images, kept 44798 boxes
round002 client1_citystreet: pseudo scan 4750/5000 images, kept 47348 boxes
round002 client1_citystreet: pseudo scan 5000/5000 images, kept 49796 boxes
{
  "round": "round002",
  "client": "client1_citystreet",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4952,
  "pseudo_boxes_kept": 41294,
  "boxes_per_kept_image": 8.338852988691437,
  "mean_conf": 0.737290830751646,
  "mean_stability": 0.9473008993330513,
  "mean_score": 0.7020182438206026,
  "class_counts": {
    "0": 3208,
    "2": 22409,
    "3": 404,
    "4": 1226,
    "5": 164,
    "7": 5296,
    "8": 8587
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client1_citystreet_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round002_client1_citystreet_stable_boxes.csv"
}
round002 client2_residential: pseudo scan 1/5000 images, kept 7 boxes
round002 client2_residential: pseudo scan 250/5000 images, kept 2501 boxes
round002 client2_residential: pseudo scan 500/5000 images, kept 5006 boxes
round002 client2_residential: pseudo scan 750/5000 images, kept 7510 boxes
round002 client2_residential: pseudo scan 1000/5000 images, kept 9926 boxes
round002 client2_residential: pseudo scan 1250/5000 images, kept 12346 boxes
round002 client2_residential: pseudo scan 1500/5000 images, kept 14781 boxes
round002 client2_residential: pseudo scan 1750/5000 images, kept 17172 boxes
round002 client2_residential: pseudo scan 2000/5000 images, kept 19607 boxes
round002 client2_residential: pseudo scan 2250/5000 images, kept 22072 boxes
round002 client2_residential: pseudo scan 2500/5000 images, kept 24469 boxes
round002 client2_residential: pseudo scan 2750/5000 images, kept 26921 boxes
round002 client2_residential: pseudo scan 3000/5000 images, kept 29449 boxes
round002 client2_residential: pseudo scan 3250/5000 images, kept 31891 boxes
round002 client2_residential: pseudo scan 3500/5000 images, kept 34307 boxes
round002 client2_residential: pseudo scan 3750/5000 images, kept 36799 boxes
round002 client2_residential: pseudo scan 4000/5000 images, kept 39358 boxes
round002 client2_residential: pseudo scan 4250/5000 images, kept 41868 boxes
round002 client2_residential: pseudo scan 4500/5000 images, kept 44398 boxes
round002 client2_residential: pseudo scan 4750/5000 images, kept 46893 boxes
round002 client2_residential: pseudo scan 5000/5000 images, kept 49352 boxes
{
  "round": "round002",
  "client": "client2_residential",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4932,
  "pseudo_boxes_kept": 31596,
  "boxes_per_kept_image": 6.406326034063261,
  "mean_conf": 0.7971677473789982,
  "mean_stability": 0.9584929060673378,
  "mean_score": 0.7670648645306065,
  "class_counts": {
    "0": 977,
    "2": 22209,
    "3": 160,
    "4": 755,
    "5": 125,
    "7": 1812,
    "8": 5558
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client2_residential_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round002_client2_residential_stable_boxes.csv"
}
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round002_pseudo_label_stats.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round002_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30535 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round002_repair_oriented_all_lowlr_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round002_repair_oriented_all_lowlr_client0_highway_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client0_highway_stable_train' images and labels...10257 found, 4390 missing, 0 empty, 0 corrupted: 100%|██████████| 14647/14647 [00:01<00:00, 11749.56it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client0_highway_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.476000431452917
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client0_highway_stable_train.cache' images and labels... 10257 found, 4390 missing, 0 empty, 0 corrupted: 100%|██████████| 14647/14647 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 05:08:19.643630773 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 05:08:19.668015002 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/58 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1380       640   0.03528   0.04244  0.004396     6.569:   2%|▏         | 1/58 [00:33<31:50, 33.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1292       640   0.03454   0.04239   0.00468     6.529:   3%|▎         | 2/58 [00:34<13:33, 14.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1459       640   0.03476   0.04209  0.004639     6.519:   5%|▌         | 3/58 [00:35<07:42,  8.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1337       640    0.0347   0.04155  0.004648     6.471:   7%|▋         | 4/58 [00:36<04:58,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1413       640   0.03467   0.04063  0.004778     6.406:   9%|▊         | 5/58 [00:37<03:24,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1248       640   0.03454   0.03999  0.004727     6.341:  10%|█         | 6/58 [00:38<02:28,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1418       640   0.03469   0.03948  0.004887     6.325:  12%|█▏        | 7/58 [00:39<01:53,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1317       640   0.03485   0.03919  0.004955      6.32:  14%|█▍        | 8/58 [00:40<01:29,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1539       640   0.03481   0.03915  0.004909     6.309:  16%|█▌        | 9/58 [00:41<01:14,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1268       640   0.03486   0.03868  0.004938     6.278:  17%|█▋        | 10/58 [00:42<01:03,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1370       640   0.03476   0.03841  0.004933     6.248:  19%|█▉        | 11/58 [00:43<00:56,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1341       640   0.03474    0.0382  0.004921     6.229:  21%|██        | 12/58 [00:44<00:50,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1233       640   0.03474   0.03781  0.004923     6.198:  22%|██▏       | 13/58 [00:45<00:46,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1388       640    0.0348   0.03775   0.00491     6.196:  24%|██▍       | 14/58 [00:45<00:43,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1107       640   0.03478   0.03729  0.004931     6.159:  26%|██▌       | 15/58 [00:46<00:41,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1403       640    0.0348   0.03722  0.004973      6.16:  28%|██▊       | 16/58 [00:47<00:39,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1410       640   0.03477   0.03721   0.00495     6.154:  29%|██▉       | 17/58 [00:48<00:38,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1076       640    0.0347   0.03684  0.004946     6.119:  31%|███       | 18/58 [00:49<00:36,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1028       640   0.03459   0.03639  0.004951     6.075:  33%|███▎      | 19/58 [00:50<00:35,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1301       640   0.03461   0.03627  0.004952     6.066:  34%|███▍      | 20/58 [00:51<00:34,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1229       640   0.03463   0.03609  0.004964     6.055:  36%|███▌      | 21/58 [00:52<00:33,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1266       640   0.03459   0.03582  0.004941     6.028:  38%|███▊      | 22/58 [00:53<00:32,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1429       640   0.03461   0.03579  0.004945     6.028:  40%|███▉      | 23/58 [00:54<00:31,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1400       640    0.0346   0.03573  0.004951     6.023:  41%|████▏     | 24/58 [00:54<00:30,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1406       640   0.03462   0.03573  0.004975     6.026:  43%|████▎     | 25/58 [00:55<00:29,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1209       640   0.03455   0.03558  0.004939     6.005:  45%|████▍     | 26/58 [00:56<00:28,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.597      0.388      0.406      0.227
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.587      0.389      0.403      0.227
                   0        738       1052      0.518      0.537      0.527      0.252
                   1        738         44       0.62      0.114      0.179     0.0683
                   2        738       8622      0.731      0.702      0.749      0.478
                   3        738        151      0.581      0.384      0.419      0.328
                   4        738        467      0.536       0.55      0.546        0.4
                   5        738         70      0.276      0.386       0.26      0.137
                   6        738         65      0.331     0.0615      0.165     0.0619
                   7        738       1619      0.567      0.609      0.593      0.243
                   8        738       2845      0.707      0.546      0.594        0.3
                   9        738          2          1          0   0.000215   0.000193

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway

1 epochs completed in 0.039 hours.
Destroying process group...
[rank0]:[W505 05:10:37.220135616 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30536 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round002_repair_oriented_all_lowlr_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  6f985a4 torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round002_repair_oriented_all_lowlr_client1_citystreet_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client1_citystreet_stable_train' images and labels...10077 found, 4637 missing, 0 empty, 0 corrupted: 100%|██████████| 14714/14714 [00:01<00:00, 10519.83it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client1_citystreet_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.204139525110318
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client1_citystreet_stable_train.cache' images and labels... 10077 found, 4637 missing, 0 empty, 0 corrupted: 100%|██████████| 14714/14714 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client1_citystreet
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 05:10:55.435054381 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 05:10:55.442153116 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1335       640   0.03507   0.05165  0.004918     7.331:   2%|▏         | 1/60 [00:34<34:13, 34.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1384       640   0.03468   0.04988  0.005039     7.168:   3%|▎         | 2/60 [00:36<14:32, 15.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1438       640   0.03466   0.04846  0.005134      7.06:   5%|▌         | 3/60 [00:37<08:16,  8.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1198       640   0.03445   0.04697  0.005036     6.917:   7%|▋         | 4/60 [00:38<05:19,  5.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1259       640   0.03444   0.04598  0.004899     6.826:   8%|▊         | 5/60 [00:39<03:38,  3.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1114       640   0.03425   0.04445  0.004886     6.686:  10%|█         | 6/60 [00:40<02:38,  2.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1237       640    0.0342   0.04328  0.004895      6.59:  12%|█▏        | 7/60 [00:40<02:00,  2.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1387       640   0.03436   0.04302  0.005107     6.599:  13%|█▎        | 8/60 [00:41<01:35,  1.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1385       640   0.03449    0.0427  0.005038     6.578:  15%|█▌        | 9/60 [00:42<01:19,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1298       640   0.03451   0.04235  0.005096     6.557:  17%|█▋        | 10/60 [00:43<01:07,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1261       640    0.0345   0.04191  0.005158     6.525:  18%|█▊        | 11/60 [00:44<00:59,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1243       640   0.03455    0.0413  0.005156     6.481:  20%|██        | 12/60 [00:45<00:53,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1290       640    0.0345   0.04098  0.005173     6.452:  22%|██▏       | 13/60 [00:46<00:49,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1164       640   0.03453   0.04064  0.005136     6.425:  23%|██▎       | 14/60 [00:47<00:45,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1125       640   0.03436   0.04017  0.005109     6.371:  25%|██▌       | 15/60 [00:48<00:43,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1318       640   0.03426   0.04001  0.005096      6.35:  27%|██▋       | 16/60 [00:49<00:41,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1223       640   0.03426   0.03974  0.005094     6.327:  28%|██▊       | 17/60 [00:49<00:39,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1325       640   0.03425   0.03954  0.005119     6.313:  30%|███       | 18/60 [00:50<00:38,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1124       640   0.03423   0.03916  0.005094     6.279:  32%|███▏      | 19/60 [00:51<00:37,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1203       640   0.03426   0.03899  0.005082     6.267:  33%|███▎      | 20/60 [00:52<00:35,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1106       640    0.0342   0.03881  0.005078     6.248:  35%|███▌      | 21/60 [00:53<00:34,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1043       640   0.03421   0.03852   0.00508     6.225:  37%|███▋      | 22/60 [00:54<00:34,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1363       640   0.03423    0.0385  0.005064     6.224:  38%|███▊      | 23/60 [00:55<00:32,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1562       640   0.03429   0.03855  0.005057     6.232:  40%|████      | 24/60 [00:56<00:31,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1439       640   0.03428   0.03852  0.005047     6.228:  42%|████▏     | 25/60 [00:57<00:30,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1250       640   0.03431   0.03838  0.005074     6.221:  43%|████▎     | 26/60 [00:57<00:30,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.517       0.41      0.397      0.221
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client1_citystreet/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client1_citystreet/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.507      0.414      0.397      0.222
                   0        738       1052      0.618       0.49      0.513      0.241
                   1        738         44      0.419      0.131      0.185     0.0689
                   2        738       8622      0.582      0.748      0.741      0.463
                   3        738        151      0.297      0.444      0.406      0.313
                   4        738        467      0.403      0.618      0.542      0.392
                   5        738         70      0.322      0.386      0.277      0.136
                   6        738         65      0.334      0.108      0.144     0.0611
                   7        738       1619      0.535      0.603      0.572      0.237
                   8        738       2845      0.559      0.609      0.592       0.31
                   9        738          2          1          0   0.000153   0.000123

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client1_citystreet

1 epochs completed in 0.038 hours.
Destroying process group...
[rank0]:[W505 05:13:11.955654835 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30537 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round002_repair_oriented_all_lowlr_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round002_repair_oriented_all_lowlr_client2_residential_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client2_residential_stable_train' images and labels...10110 found, 4584 missing, 0 empty, 0 corrupted: 100%|██████████| 14694/14694 [00:01<00:00, 11016.58it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client2_residential_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.261278394083465
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round002_client2_residential_stable_train.cache' images and labels... 10110 found, 4584 missing, 0 empty, 0 corrupted: 100%|██████████| 14694/14694 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client2_residential
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 05:13:30.307594283 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 05:13:30.329978876 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      1295       640   0.03582   0.04791  0.005526      7.14:   2%|▏         | 1/60 [00:34<34:16, 34.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1190       640   0.03441   0.04763  0.005421     6.997:   3%|▎         | 2/60 [00:36<14:34, 15.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1357       640    0.0346   0.04808  0.005519     7.056:   5%|▌         | 3/60 [00:37<08:18,  8.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1428       640   0.03503   0.04843  0.005464     7.114:   7%|▋         | 4/60 [00:38<05:19,  5.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1434       640   0.03505   0.04767  0.005335     7.044:   8%|▊         | 5/60 [00:39<03:39,  3.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1362       640    0.0351   0.04652  0.005254      6.95:  10%|█         | 6/60 [00:40<02:39,  2.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1370       640   0.03515   0.04574  0.005284     6.894:  12%|█▏        | 7/60 [00:41<02:00,  2.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1267       640   0.03496   0.04503  0.005232     6.818:  13%|█▎        | 8/60 [00:42<01:36,  1.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1367       640   0.03489   0.04446  0.005274      6.77:  15%|█▌        | 9/60 [00:42<01:19,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1444       640   0.03479   0.04384  0.005269     6.712:  17%|█▋        | 10/60 [00:43<01:08,  1.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1341       640   0.03471   0.04331  0.005218     6.659:  18%|█▊        | 11/60 [00:44<01:00,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1439       640   0.03475   0.04285  0.005179     6.622:  20%|██        | 12/60 [00:45<00:54,  1.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1428       640   0.03482   0.04254  0.005203     6.605:  22%|██▏       | 13/60 [00:46<00:49,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1304       640   0.03485   0.04214  0.005196     6.575:  23%|██▎       | 14/60 [00:47<00:46,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1510       640   0.03498   0.04208  0.005198     6.581:  25%|██▌       | 15/60 [00:48<00:43,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1185       640   0.03492   0.04163  0.005205     6.541:  27%|██▋       | 16/60 [00:49<00:41,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1211       640   0.03486   0.04128  0.005189     6.507:  28%|██▊       | 17/60 [00:50<00:39,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1376       640    0.0349   0.04118   0.00518     6.501:  30%|███       | 18/60 [00:50<00:38,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1204       640   0.03479   0.04072  0.005154     6.453:  32%|███▏      | 19/60 [00:51<00:36,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1402       640   0.03487   0.04067  0.005178     6.457:  33%|███▎      | 20/60 [00:52<00:35,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1327       640   0.03486   0.04047  0.005164     6.439:  35%|███▌      | 21/60 [00:53<00:34,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1084       640    0.0348   0.04007  0.005181     6.404:  37%|███▋      | 22/60 [00:54<00:33,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1272       640   0.03474   0.03983  0.005178      6.38:  38%|███▊      | 23/60 [00:55<00:32,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1200       640   0.03474   0.03944  0.005168     6.348:  40%|████      | 24/60 [00:56<00:32,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1333       640    0.0347   0.03927  0.005164     6.331:  42%|████▏     | 25/60 [00:57<00:31,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1261       640   0.03471   0.03908  0.005156     6.316:  43%|████▎     | 26/60 [00:58<00:30,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.504      0.414      0.402      0.223
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client2_residential/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client2_residential/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.529      0.399      0.402      0.224
                   0        738       1052       0.52      0.541      0.531       0.25
                   1        738         44      0.496      0.136      0.198     0.0821
                   2        738       8622      0.705      0.682      0.726      0.455
                   3        738        151      0.382      0.411       0.42      0.324
                   4        738        467       0.46      0.567      0.542      0.388
                   5        738         70      0.309      0.371      0.287      0.132
                   6        738         65      0.264     0.0609      0.138     0.0552
                   7        738       1619      0.551      0.618      0.584      0.243
                   8        738       2845      0.604        0.6      0.597      0.312
                   9        738          2          1          0    0.00017   0.000136

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_client2_residential

1 epochs completed in 0.038 hours.
Destroying process group...
[rank0]:[W505 05:15:46.752617796 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30538 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round002_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round002_repair_oriented_all_lowlr_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 05:16:02.649200578 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 05:16:02.676428878 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03383   0.05192  0.005019     7.261:   3%|▎         | 1/31 [00:33<16:46, 33.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03462   0.05206  0.005221     7.352:   6%|▋         | 2/31 [00:34<06:55, 14.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03412   0.04987  0.005129      7.13:  10%|▉         | 3/31 [00:35<03:47,  8.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03361   0.04696  0.004881     6.836:  13%|█▎        | 4/31 [00:35<02:21,  5.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03363   0.04646  0.004899     6.799:  16%|█▌        | 5/31 [00:36<01:32,  3.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03384    0.0458  0.004965     6.768:  19%|█▉        | 6/31 [00:37<01:03,  2.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03399   0.04509  0.005035     6.729:  23%|██▎       | 7/31 [00:37<00:45,  1.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03395   0.04489  0.005062     6.712:  26%|██▌       | 8/31 [00:38<00:34,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03401   0.04462  0.004958     6.687:  29%|██▉       | 9/31 [00:38<00:26,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640     0.034   0.04452   0.00493     6.676:  32%|███▏      | 10/31 [00:39<00:21,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03397   0.04436  0.004951     6.663:  35%|███▌      | 11/31 [00:40<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03388   0.04395  0.004934     6.621:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03386   0.04385   0.00488     6.608:  42%|████▏     | 13/31 [00:41<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03388   0.04353   0.00484      6.58:  45%|████▌     | 14/31 [00:41<00:11,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03392    0.0433  0.004878     6.567:  48%|████▊     | 15/31 [00:42<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03391   0.04304  0.004865     6.545:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03395   0.04298  0.004827      6.54:  55%|█████▍    | 17/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03398   0.04291  0.004786     6.535:  58%|█████▊    | 18/31 [00:44<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03392   0.04267   0.00475     6.507:  61%|██████▏   | 19/31 [00:44<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640    0.0339    0.0428  0.004751     6.516:  65%|██████▍   | 20/31 [00:45<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03393   0.04274   0.00477     6.515:  68%|██████▊   | 21/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03393   0.04276   0.00474     6.515:  71%|███████   | 22/31 [00:46<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03391   0.04272  0.004727     6.509:  74%|███████▍  | 23/31 [00:47<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03392   0.04273  0.004709     6.509:  77%|███████▋  | 24/31 [00:47<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03392    0.0426  0.004718       6.5:  81%|████████  | 25/31 [00:48<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03397   0.04257  0.004717       6.5:  84%|████████▍ | 26/31 [00:48<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.519      0.429      0.413      0.231
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.507       0.43      0.411      0.232
                   0        738       1052      0.539      0.551      0.542      0.256
                   1        738         44      0.368      0.159      0.161     0.0636
                   2        738       8622      0.629      0.751      0.756      0.487
                   3        738        151      0.401      0.444      0.428      0.326
                   4        738        467      0.492      0.578      0.559      0.406
                   5        738         70       0.24      0.443      0.291      0.146
                   6        738         65      0.236      0.133      0.171     0.0666
                   7        738       1619      0.559      0.615      0.587      0.243
                   8        738       2845      0.604      0.627      0.619      0.327
                   9        738          2          1          0   0.000326   0.000294

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round002_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 05:17:42.040851593 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_checkpoints.csv

=== round003: pseudo labels from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round003 client0_highway: pseudo scan 1/5000 images, kept 4 boxes
round003 client0_highway: pseudo scan 250/5000 images, kept 1976 boxes
round003 client0_highway: pseudo scan 500/5000 images, kept 3878 boxes
round003 client0_highway: pseudo scan 750/5000 images, kept 5808 boxes
round003 client0_highway: pseudo scan 1000/5000 images, kept 7868 boxes
round003 client0_highway: pseudo scan 1250/5000 images, kept 9841 boxes
round003 client0_highway: pseudo scan 1500/5000 images, kept 11671 boxes
round003 client0_highway: pseudo scan 1750/5000 images, kept 13697 boxes
round003 client0_highway: pseudo scan 2000/5000 images, kept 15671 boxes
round003 client0_highway: pseudo scan 2250/5000 images, kept 17618 boxes
round003 client0_highway: pseudo scan 2500/5000 images, kept 19656 boxes
round003 client0_highway: pseudo scan 2750/5000 images, kept 21492 boxes
round003 client0_highway: pseudo scan 3000/5000 images, kept 23558 boxes
round003 client0_highway: pseudo scan 3250/5000 images, kept 25544 boxes
round003 client0_highway: pseudo scan 3500/5000 images, kept 27504 boxes
round003 client0_highway: pseudo scan 3750/5000 images, kept 29452 boxes
round003 client0_highway: pseudo scan 4000/5000 images, kept 31255 boxes
round003 client0_highway: pseudo scan 4250/5000 images, kept 33165 boxes
round003 client0_highway: pseudo scan 4500/5000 images, kept 35095 boxes
round003 client0_highway: pseudo scan 4750/5000 images, kept 37110 boxes
round003 client0_highway: pseudo scan 5000/5000 images, kept 39137 boxes
{
  "round": "round003",
  "client": "client0_highway",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4813,
  "pseudo_boxes_kept": 30787,
  "boxes_per_kept_image": 6.396634115936006,
  "mean_conf": 0.75082703948594,
  "mean_stability": 0.9521089603120533,
  "mean_score": 0.7180646797160705,
  "class_counts": {
    "0": 352,
    "2": 17612,
    "3": 227,
    "4": 1177,
    "5": 32,
    "7": 1502,
    "8": 9885
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client0_highway_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round003_client0_highway_stable_boxes.csv"
}
round003 client1_citystreet: pseudo scan 1/5000 images, kept 6 boxes
round003 client1_citystreet: pseudo scan 250/5000 images, kept 2410 boxes
round003 client1_citystreet: pseudo scan 500/5000 images, kept 4789 boxes
round003 client1_citystreet: pseudo scan 750/5000 images, kept 7210 boxes
round003 client1_citystreet: pseudo scan 1000/5000 images, kept 9528 boxes
round003 client1_citystreet: pseudo scan 1250/5000 images, kept 11882 boxes
round003 client1_citystreet: pseudo scan 1500/5000 images, kept 14281 boxes
round003 client1_citystreet: pseudo scan 1750/5000 images, kept 16837 boxes
round003 client1_citystreet: pseudo scan 2000/5000 images, kept 19224 boxes
round003 client1_citystreet: pseudo scan 2250/5000 images, kept 21656 boxes
round003 client1_citystreet: pseudo scan 2500/5000 images, kept 23949 boxes
round003 client1_citystreet: pseudo scan 2750/5000 images, kept 26275 boxes
round003 client1_citystreet: pseudo scan 3000/5000 images, kept 28775 boxes
round003 client1_citystreet: pseudo scan 3250/5000 images, kept 31159 boxes
round003 client1_citystreet: pseudo scan 3500/5000 images, kept 33567 boxes
round003 client1_citystreet: pseudo scan 3750/5000 images, kept 36009 boxes
round003 client1_citystreet: pseudo scan 4000/5000 images, kept 38410 boxes
round003 client1_citystreet: pseudo scan 4250/5000 images, kept 40859 boxes
round003 client1_citystreet: pseudo scan 4500/5000 images, kept 43286 boxes
round003 client1_citystreet: pseudo scan 4750/5000 images, kept 45770 boxes
round003 client1_citystreet: pseudo scan 5000/5000 images, kept 48137 boxes
{
  "round": "round003",
  "client": "client1_citystreet",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4916,
  "pseudo_boxes_kept": 39867,
  "boxes_per_kept_image": 8.109641985353946,
  "mean_conf": 0.7423075035180411,
  "mean_stability": 0.9493548761887203,
  "mean_score": 0.7082868323735529,
  "class_counts": {
    "0": 3253,
    "2": 21662,
    "3": 421,
    "4": 1217,
    "5": 166,
    "7": 5151,
    "8": 7997
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client1_citystreet_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round003_client1_citystreet_stable_boxes.csv"
}
round003 client2_residential: pseudo scan 1/5000 images, kept 8 boxes
round003 client2_residential: pseudo scan 250/5000 images, kept 2456 boxes
round003 client2_residential: pseudo scan 500/5000 images, kept 4903 boxes
round003 client2_residential: pseudo scan 750/5000 images, kept 7374 boxes
round003 client2_residential: pseudo scan 1000/5000 images, kept 9725 boxes
round003 client2_residential: pseudo scan 1250/5000 images, kept 12101 boxes
round003 client2_residential: pseudo scan 1500/5000 images, kept 14489 boxes
round003 client2_residential: pseudo scan 1750/5000 images, kept 16841 boxes
round003 client2_residential: pseudo scan 2000/5000 images, kept 19244 boxes
round003 client2_residential: pseudo scan 2250/5000 images, kept 21659 boxes
round003 client2_residential: pseudo scan 2500/5000 images, kept 24015 boxes
round003 client2_residential: pseudo scan 2750/5000 images, kept 26431 boxes
round003 client2_residential: pseudo scan 3000/5000 images, kept 28916 boxes
round003 client2_residential: pseudo scan 3250/5000 images, kept 31319 boxes
round003 client2_residential: pseudo scan 3500/5000 images, kept 33674 boxes
round003 client2_residential: pseudo scan 3750/5000 images, kept 36117 boxes
round003 client2_residential: pseudo scan 4000/5000 images, kept 38621 boxes
round003 client2_residential: pseudo scan 4250/5000 images, kept 41078 boxes
round003 client2_residential: pseudo scan 4500/5000 images, kept 43563 boxes
round003 client2_residential: pseudo scan 4750/5000 images, kept 45983 boxes
round003 client2_residential: pseudo scan 5000/5000 images, kept 48411 boxes
{
  "round": "round003",
  "client": "client2_residential",
  "teacher": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 5000,
  "pseudo_images_kept": 4893,
  "pseudo_boxes_kept": 30919,
  "boxes_per_kept_image": 6.319027181688126,
  "mean_conf": 0.8009553597863199,
  "mean_stability": 0.9597838333393386,
  "mean_score": 0.7717622803670007,
  "class_counts": {
    "0": 986,
    "2": 21785,
    "3": 169,
    "4": 751,
    "5": 128,
    "7": 1776,
    "8": 5324
  },
  "train_list": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client2_residential_stable_train.txt",
  "box_table": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round003_client2_residential_stable_boxes.csv"
}
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round003_pseudo_label_stats.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round003_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30539 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round003_repair_oriented_all_lowlr_client0_highway.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round003_repair_oriented_all_lowlr_client0_highway_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client0_highway_stable_train' images and labels...10257 found, 4318 missing, 0 empty, 0 corrupted: 100%|██████████| 14575/14575 [00:01<00:00, 11980.39it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client0_highway_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.557995434286335
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client0_highway_stable_train.cache' images and labels... 10257 found, 4318 missing, 0 empty, 0 corrupted: 100%|██████████| 14575/14575 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 05:21:20.663860540 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 05:21:20.684140176 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/58 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1299       640   0.03452   0.04562  0.004727     6.789:   2%|▏         | 1/58 [00:33<31:42, 33.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1414       640   0.03565     0.044  0.004776     6.754:   3%|▎         | 2/58 [00:34<13:28, 14.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1524       640    0.0354   0.04375  0.004864     6.721:   5%|▌         | 3/58 [00:35<07:41,  8.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1381       640   0.03509   0.04253  0.004795     6.593:   7%|▋         | 4/58 [00:36<04:57,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1230       640   0.03477   0.04124  0.004703     6.457:   9%|▊         | 5/58 [00:37<03:23,  3.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1274       640   0.03455   0.04056  0.004722     6.387:  10%|█         | 6/58 [00:38<02:27,  2.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1442       640   0.03469   0.04022  0.004671     6.367:  12%|█▏        | 7/58 [00:39<01:53,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1301       640   0.03461   0.03957  0.004747     6.315:  14%|█▍        | 8/58 [00:40<01:30,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1509       640   0.03441    0.0392  0.004726     6.266:  16%|█▌        | 9/58 [00:41<01:14,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1215       640    0.0343   0.03844  0.004748     6.199:  17%|█▋        | 10/58 [00:42<01:03,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1494       640   0.03429   0.03807  0.004786     6.172:  19%|█▉        | 11/58 [00:43<00:56,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1365       640   0.03412   0.03772  0.004748     6.127:  21%|██        | 12/58 [00:44<00:50,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1271       640   0.03412   0.03744  0.004759     6.106:  22%|██▏       | 13/58 [00:44<00:46,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1377       640   0.03414   0.03712  0.004743      6.08:  24%|██▍       | 14/58 [00:45<00:43,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1356       640   0.03403   0.03684  0.004772     6.052:  26%|██▌       | 15/58 [00:46<00:40,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1259       640   0.03405   0.03663    0.0048     6.039:  28%|██▊       | 16/58 [00:47<00:38,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1329       640   0.03409   0.03639   0.00478      6.02:  29%|██▉       | 17/58 [00:48<00:37,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1166       640   0.03418   0.03611  0.004738     6.002:  31%|███       | 18/58 [00:49<00:36,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1106       640   0.03417   0.03568  0.004777      5.97:  33%|███▎      | 19/58 [00:50<00:34,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1293       640   0.03417   0.03556  0.004824     5.965:  34%|███▍      | 20/58 [00:50<00:33,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1262       640    0.0342   0.03536  0.004819      5.95:  36%|███▌      | 21/58 [00:51<00:32,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1087       640   0.03417   0.03505  0.004862     5.927:  38%|███▊      | 22/58 [00:52<00:31,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1175       640   0.03413   0.03489  0.004915     5.915:  40%|███▉      | 23/58 [00:53<00:30,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1324       640   0.03412   0.03472  0.004925     5.901:  41%|████▏     | 24/58 [00:54<00:30,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1340       640   0.03413   0.03463  0.004919     5.894:  43%|████▎     | 25/58 [00:55<00:29,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1185       640   0.03406   0.03452    0.0049     5.879:  45%|████▍     | 26/58 [00:56<00:28,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.515      0.428      0.411       0.23
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]

                 all        738      14937      0.509      0.423      0.408      0.231
                   0        738       1052      0.471      0.565      0.535      0.256
                   1        738         44      0.387      0.159      0.169     0.0691
                   2        738       8622      0.669      0.731       0.75      0.483
                   3        738        151      0.404      0.444      0.432       0.34
                   4        738        467      0.458      0.589      0.553      0.398
                   5        738         70      0.263        0.4      0.276      0.143
                   6        738         65      0.255      0.121      0.169     0.0675
                   7        738       1619      0.527      0.637      0.596      0.248
                   8        738       2845      0.654       0.58      0.599      0.307
                   9        738          2          1          0   0.000219   0.000197

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway

1 epochs completed in 0.038 hours.
Destroying process group...
[rank0]:[W505 05:23:36.359117241 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30540 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round003_repair_oriented_all_lowlr_client1_citystreet.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round003_repair_oriented_all_lowlr_client1_citystreet_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client1_citystreet_stable_train' images and labels...10077 found, 4601 missing, 0 empty, 0 corrupted: 100%|██████████| 14678/14678 [00:01<00:00, 10339.11it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client1_citystreet_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.242881248681712
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client1_citystreet_stable_train.cache' images and labels... 10077 found, 4601 missing, 0 empty, 0 corrupted: 100%|██████████| 14678/14678 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client1_citystreet
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 05:23:54.805488021 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 05:23:54.837384158 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/60 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1196       640   0.03436   0.04954  0.005622     7.162:   2%|▏         | 1/60 [00:33<32:44, 33.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1156       640   0.03376   0.04905  0.005292     7.048:   3%|▎         | 2/60 [00:34<13:59, 14.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1280       640   0.03398   0.04959  0.005469     7.123:   5%|▌         | 3/60 [00:35<08:00,  8.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1228       640   0.03417   0.04813  0.005505     7.024:   7%|▋         | 4/60 [00:36<05:10,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1340       640   0.03413   0.04634  0.005422     6.872:   8%|▊         | 5/60 [00:37<03:33,  3.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1157       640    0.0339   0.04478   0.00528     6.717:  10%|█         | 6/60 [00:38<02:36,  2.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1351       640   0.03395   0.04417  0.005218     6.667:  12%|█▏        | 7/60 [00:39<02:00,  2.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1390       640   0.03406   0.04344  0.005152     6.612:  13%|█▎        | 8/60 [00:40<01:35,  1.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1295       640   0.03406   0.04268  0.005205     6.555:  15%|█▌        | 9/60 [00:41<01:18,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1323       640   0.03415     0.042  0.005242     6.511:  17%|█▋        | 10/60 [00:42<01:07,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1401       640   0.03422   0.04154  0.005223     6.478:  18%|█▊        | 11/60 [00:43<00:58,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1132       640   0.03417   0.04091   0.00514     6.418:  20%|██        | 12/60 [00:44<00:52,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1334       640   0.03418   0.04067  0.005119     6.397:  22%|██▏       | 13/60 [00:45<00:48,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1065       640    0.0341   0.04019  0.005076     6.349:  23%|██▎       | 14/60 [00:46<00:45,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1095       640   0.03408   0.03964  0.005065     6.302:  25%|██▌       | 15/60 [00:46<00:42,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1322       640    0.0341    0.0396  0.005032     6.299:  27%|██▋       | 16/60 [00:47<00:40,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1112       640   0.03401   0.03926  0.005025     6.263:  28%|██▊       | 17/60 [00:48<00:39,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1326       640    0.0341   0.03911  0.005026     6.259:  30%|███       | 18/60 [00:49<00:37,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1033       640   0.03402   0.03855  0.004972     6.203:  32%|███▏      | 19/60 [00:50<00:36,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1467       640   0.03406   0.03858   0.00496     6.208:  33%|███▎      | 20/60 [00:51<00:35,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1262       640   0.03413   0.03838  0.004966     6.198:  35%|███▌      | 21/60 [00:52<00:34,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1160       640   0.03412   0.03813  0.004936     6.175:  37%|███▋      | 22/60 [00:53<00:33,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1306       640   0.03415   0.03818  0.004921      6.18:  38%|███▊      | 23/60 [00:53<00:32,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1146       640   0.03407   0.03799  0.004898     6.157:  40%|████      | 24/60 [00:54<00:31,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1284       640    0.0341   0.03785   0.00488     6.146:  42%|████▏     | 25/60 [00:55<00:30,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1281       640   0.03412   0.03776  0.004889     6.142:  43%|████▎     | 26/60 [00:56<00:30,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.527      0.411      0.402      0.226
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client1_citystreet/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client1_citystreet/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client1_citystreet/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937       0.52      0.414      0.401      0.226
                   0        738       1052      0.624      0.486      0.518      0.243
                   1        738         44      0.491      0.154      0.173     0.0713
                   2        738       8622      0.601      0.744      0.743      0.468
                   3        738        151      0.327      0.437      0.423      0.329
                   4        738        467      0.418       0.61      0.544      0.392
                   5        738         70      0.346      0.386      0.275      0.139
                   6        738         65      0.287     0.0923      0.158     0.0658
                   7        738       1619       0.54      0.618      0.581      0.239
                   8        738       2845      0.563      0.612      0.595      0.316
                   9        738          2          1          0          0          0

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client1_citystreet

1 epochs completed in 0.038 hours.
Destroying process group...
[rank0]:[W505 05:26:09.919132947 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30541 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round003_repair_oriented_all_lowlr_client2_residential.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/client_states/pl03_round003_repair_oriented_all_lowlr_client2_residential_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client2_residential_stable_train' images and labels...10110 found, 4545 missing, 0 empty, 0 corrupted: 100%|██████████| 14655/14655 [00:01<00:00, 8294.63it/s]
train: New cache created: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client2_residential_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 10.303734351792913
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/pl03_round003_client2_residential_stable_train.cache' images and labels... 10110 found, 4545 missing, 0 empty, 0 corrupted: 100%|██████████| 14655/14655 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client2_residential
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 05:26:27.870524463 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 05:26:27.891681819 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/59 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      1256       640   0.03558   0.05136  0.005371     7.385:   2%|▏         | 1/59 [00:33<32:40, 33.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1272       640   0.03485   0.05133  0.004721     7.273:   3%|▎         | 2/59 [00:34<13:51, 14.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1322       640   0.03417   0.05078  0.004729     7.174:   5%|▌         | 3/59 [00:36<07:54,  8.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1290       640   0.03381   0.04992  0.004765     7.079:   7%|▋         | 4/59 [00:37<05:06,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1300       640   0.03402   0.04876  0.004935     7.018:   8%|▊         | 5/59 [00:38<03:30,  3.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1231       640   0.03371   0.04689  0.004867     6.837:  10%|█         | 6/59 [00:39<02:32,  2.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1384       640   0.03394   0.04602  0.004881     6.788:  12%|█▏        | 7/59 [00:39<01:56,  2.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1203       640    0.0338   0.04489  0.004822     6.681:  14%|█▎        | 8/59 [00:40<01:32,  1.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1410       640   0.03391    0.0443   0.00486     6.646:  15%|█▌        | 9/59 [00:41<01:16,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1406       640    0.0341   0.04374  0.004941     6.623:  17%|█▋        | 10/59 [00:42<01:05,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1464       640   0.03415   0.04321  0.004954     6.585:  19%|█▊        | 11/59 [00:43<00:57,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1287       640   0.03408   0.04265  0.004947     6.534:  20%|██        | 12/59 [00:44<00:51,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1302       640   0.03411   0.04209  0.004939     6.491:  22%|██▏       | 13/59 [00:45<00:47,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1446       640   0.03417   0.04174  0.004976     6.471:  24%|██▎       | 14/59 [00:46<00:44,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1181       640   0.03421   0.04124  0.004967     6.433:  25%|██▌       | 15/59 [00:47<00:41,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1530       640   0.03431   0.04102  0.004949     6.422:  27%|██▋       | 16/59 [00:47<00:39,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1352       640   0.03429   0.04083  0.004944     6.405:  29%|██▉       | 17/59 [00:48<00:38,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1448       640   0.03432   0.04073  0.004968     6.401:  31%|███       | 18/59 [00:49<00:37,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1094       640   0.03428   0.04023  0.005001     6.361:  32%|███▏      | 19/59 [00:50<00:35,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1407       640   0.03439   0.04014   0.00504     6.365:  34%|███▍      | 20/59 [00:51<00:35,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1233       640   0.03433   0.03989  0.005035     6.341:  36%|███▌      | 21/59 [00:52<00:34,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1360       640   0.03435   0.03977  0.005023     6.332:  37%|███▋      | 22/59 [00:53<00:33,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1378       640   0.03435    0.0396  0.005037     6.319:  39%|███▉      | 23/59 [00:54<00:32,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1450       640   0.03438   0.03948  0.005021      6.31:  41%|████      | 24/59 [00:55<00:31,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1358       640   0.03444   0.03938  0.005021     6.307:  42%|████▏     | 25/59 [00:55<00:30,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1440       640   0.03444   0.03931  0.005025     6.301:  44%|████▍     | 26/59 [00:56<00:29,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.499       0.42      0.402      0.224
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client2_residential/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client2_residential/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client2_residential/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.477      0.431        0.4      0.224
                   0        738       1052      0.423       0.57      0.534      0.249
                   1        738         44      0.411      0.174      0.187     0.0755
                   2        738       8622      0.638      0.704       0.72      0.451
                   3        738        151      0.309      0.457      0.425      0.329
                   4        738        467      0.387       0.63      0.537      0.384
                   5        738         70      0.301      0.414      0.281      0.137
                   6        738         65      0.233      0.108      0.137     0.0535
                   7        738       1619      0.507      0.638      0.588      0.246
                   8        738       2845       0.56      0.617      0.591      0.312
                   9        738          2          1          0   0.000152   0.000121

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_client2_residential

1 epochs completed in 0.039 hours.
Destroying process group...
[rank0]:[W505 05:28:44.076910106 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30542 train.py --cfg /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/configs/pl03_round003_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round003_repair_oriented_all_lowlr_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 05:29:01.485461871 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 05:29:01.822430572 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03331   0.05092  0.004792     7.122:   3%|▎         | 1/31 [00:32<16:23, 32.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03406    0.0512  0.004999     7.221:   6%|▋         | 2/31 [00:33<06:44, 13.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03355   0.04905  0.004903         7:  10%|▉         | 3/31 [00:34<03:42,  7.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03303   0.04618  0.004665     6.709:  13%|█▎        | 4/31 [00:35<02:17,  5.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03306   0.04567  0.004692     6.673:  16%|█▌        | 5/31 [00:35<01:30,  3.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03327   0.04501  0.004752     6.642:  19%|█▉        | 6/31 [00:36<01:02,  2.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03341   0.04431  0.004816     6.602:  23%|██▎       | 7/31 [00:36<00:44,  1.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03337    0.0441  0.004839     6.584:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03343   0.04383  0.004737      6.56:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03343   0.04374  0.004708      6.55:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03339   0.04357  0.004732     6.536:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03331   0.04316  0.004717     6.495:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03328   0.04305  0.004662     6.479:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640    0.0333   0.04273  0.004621     6.452:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03333   0.04251  0.004662      6.44:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03334   0.04225  0.004652     6.419:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03337   0.04219  0.004617     6.414:  55%|█████▍    | 17/31 [00:42<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03342   0.04212  0.004577     6.409:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03335   0.04188  0.004542     6.382:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03334   0.04201   0.00454     6.391:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03338   0.04195  0.004559     6.391:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03338   0.04197   0.00453      6.39:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03336   0.04193  0.004511     6.385:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03337   0.04195  0.004495     6.385:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03338   0.04183  0.004504     6.377:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03343    0.0418  0.004506     6.379:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.583      0.398      0.415      0.233
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]

                 all        738      14937      0.572      0.399      0.412      0.233
                   0        738       1052      0.611      0.522      0.545      0.257
                   1        738         44      0.451     0.0937      0.167     0.0691
                   2        738       8622      0.696      0.729      0.755      0.487
                   3        738        151      0.572      0.417      0.436       0.33
                   4        738        467      0.548      0.555      0.565      0.409
                   5        738         70      0.279      0.429      0.284      0.138
                   6        738         65      0.306     0.0615      0.169     0.0661
                   7        738       1619        0.6      0.584      0.586      0.244
                   8        738       2845      0.656        0.6      0.617      0.328
                   9        738          2          1          0   0.000341   0.000341

Results saved to /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/runs/pl03_round003_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 05:30:40.850755663 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_checkpoints.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_checkpoints.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_manifest.json
/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/pseudogt_learnability/scripts/evaluate_scene_protocol.py --workspace /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround --splits highway,citystreet,residential,total --batch-size 16 --no-plots --verbose --checkpoint warmup_global=/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/global_checkpoints/round000_warmup.pt --checkpoint round001_aggregate_all=/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round001_repair_oriented_all_lowlr_aggregate_all.pt --checkpoint round001_server_repair=/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt --checkpoint round002_aggregate_all=/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round002_repair_oriented_all_lowlr_aggregate_all.pt --checkpoint round002_server_repair=/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt --checkpoint round003_aggregate_all=/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round003_repair_oriented_all_lowlr_aggregate_all.pt --checkpoint round003_server_repair=/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/checkpoints/round003_repair_oriented_all_lowlr_server_repair.pt
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/validation_reports/paper_protocol_eval_manifest.json
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/validation_reports/paper_protocol_eval_summary.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/validation_reports/paper_protocol_classwise_summary.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/validation_reports/paper_protocol_eval_summary.md
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round_metrics.csv
Saved: /app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round_metrics_summary.json

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_pseudogt_learnability_03.py', '--workspace-root', '/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround', '--variant', 'repair_oriented_all_lowlr', '--rounds', '3', '--batch-size', '160', '--workers', '8', '--gpus', '2', '--master-port', '30531', '--server-repair-epochs', '1', '--evaluate', '--classwise', '--no-eval-plots'], returncode=0)

## Round Metrics

Primary metrics are the repaired global model after each round.
`aggregate_mAP` and `repair_gain` are diagnostics for how destructive
the client update was and how much the source repair recovered.

In [4]:
import json
import pandas as pd

metrics_csv = WORKSPACE / "stats" / "03_round_metrics.csv"
metrics_json = WORKSPACE / "stats" / "03_round_metrics_summary.json"
if metrics_csv.exists():
    metrics = pd.read_csv(metrics_csv)
    display(metrics)
else:
    print("No round metrics yet:", metrics_csv)

if metrics_json.exists():
    print(json.dumps(json.loads(metrics_json.read_text()), indent=2, ensure_ascii=False))

,round,aggregate_map50,aggregate_map50_95,repaired_map50,repaired_map50_95,repair_gain_map50_95,retained_gain_map50_95,round_delta_map50_95,avg_client_map50_95,client_to_repair_gap_map50_95
0,1,0.320,0.182,0.377,0.210,0.028,0.021,NaN,NaN,NaN
1,2,0.331,0.188,0.378,0.211,0.023,0.022,0.001,NaN,NaN
2,3,0.320,0.182,0.377,0.210,0.028,0.021,-0.001,NaN,NaN

{
  "created_utc": "2026-05-05T05:43:05.607456+00:00",
  "warmup_map50": 0.352,
  "warmup_map50_95": 0.189,
  "last_n": 3,
  "final_repaired_map50_95": 0.21,
  "last_n_avg_repaired_map50_95": 0.21033333333333334,
  "last_n_min_repaired_map50_95": 0.21,
  "round_metrics_csv": "/app/Object_Detection/pseudogt_learnability/output/03_repair_oriented_multiround/stats/03_round_metrics.csv"
}

## Evaluation Summary

In [5]:
summary_csv = WORKSPACE / "validation_reports" / "paper_protocol_eval_summary.csv"
if not summary_csv.exists():
    print("Evaluation summary is not available yet:", summary_csv)
else:
    df = pd.read_csv(summary_csv)
    ok = df[df["status"].eq("ok")].copy()
    total = ok[ok["split"].isin(["total", "scene_total"])].copy()
    total = total.sort_values("map50_95", ascending=False)
    display(total[["checkpoint_label", "split", "precision", "recall", "map50", "map50_95"]])

          checkpoint_label        split  precision  recall  map50  map50_95
19  round002_server_repair  scene_total      0.520   0.391  0.378     0.211
27  round003_server_repair  scene_total      0.516   0.391  0.377     0.210
11  round001_server_repair  scene_total      0.511   0.388  0.377     0.210
3            warmup_global  scene_total      0.532   0.337  0.352     0.189
15  round002_aggregate_all  scene_total      0.490   0.350  0.331     0.188
7   round001_aggregate_all  scene_total      0.485   0.350  0.320     0.182
23  round003_aggregate_all  scene_total      0.511   0.326  0.320     0.182

## Pseudo Label Stats

In [6]:
stats_files = sorted((WORKSPACE / "stats").glob("03_round*_pseudo_label_stats.csv"))
if not stats_files:
    print("No pseudo-label stats yet")
else:
    stats = pd.concat([pd.read_csv(path) for path in stats_files], ignore_index=True)
    display(stats)

,round,client,source_images_scanned,pseudo_images_kept,pseudo_boxes_kept,boxes_per_kept_image,mean_conf,mean_stability,mean_score,train_list
0,round001,client0_highway,5000,4926,33794,6.8603,0.714585,0.937353,0.673265,/app/Object_Detection/pseudogt_learnability/ou...
1,round001,client1_citystreet,5000,4969,44090,8.8730,0.705435,0.933403,0.662090,/app/Object_Detection/pseudogt_learnability/ou...
2,round001,client2_residential,5000,4959,32721,6.5983,0.757845,0.948078,0.721669,/app/Object_Detection/pseudogt_learnability/ou...
3,round002,client0_highway,5000,4885,32150,6.5814,0.744332,0.949901,0.710348,/app/Object_Detection/pseudogt_learnability/ou...
4,round002,client1_citystreet,5000,4952,41294,8.3389,0.737291,0.947301,0.702018,/app/Object_Detection/pseudogt_learnability/ou...
5,round002,client2_residential,5000,4932,31596,6.4063,0.797168,0.958493,0.767065,/app/Object_Detection/pseudogt_learnability/ou...
6,round003,client0_highway,5000,4813,30787,6.3966,0.750827,0.952109,0.718065,/app/Object_Detection/pseudogt_learnability/ou...
7,round003,client1_citystreet,5000,4916,39867,8.1096,0.742308,0.949355,0.708287,/app/Object_Detection/pseudogt_learnability/ou...
8,round003,client2_residential,5000,4893,30919,6.3190,0.800955,0.959784,0.771762,/app/Object_Detection/pseudogt_learnability/ou...

## Discord Notification

In [7]:
try:
    sys.path.insert(0, str(PROJECT_ROOT.parent))
    from notebook_notify import notify_discord

    metric_line = ""
    if metrics_json.exists():
        payload = json.loads(metrics_json.read_text())
        metric_line = (
            f"final mAP50-95={payload.get('final_repaired_map50_95')}, "
            f"lastN avg={payload.get('last_n_avg_repaired_map50_95')}, "
            f"lastN min={payload.get('last_n_min_repaired_map50_95')}"
        )
    msg = "PseudoGT Learnability 03 finished. " + metric_line
    result = notify_discord(
        msg,
        title="PseudoGT Learnability 03",
        context={"project": str(PROJECT_ROOT), "workspace": str(WORKSPACE)},
        fail_silently=True,
    )
    print(result)
except Exception as exc:
    print("Discord notification skipped:", exc)

DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)