# 01_0 Repair Baseline Comparison

This notebook runs the control conditions needed to separate source repair effects from pseudoGT and DQA effects.

Conditions:
- `repair_only`: warmup -> source repair repeated for the same number of rounds.
- `pseudo_fedavg`: pseudoGT clients -> plain FedAvg -> source repair.
- `pseudo_dqa`: pseudoGT clients -> DQA-CWA v2 -> source repair.

The runner sends Discord notifications at start and finish when `--notify` is enabled.

In [1]:
from pathlib import Path
import subprocess
import sys

cwd = Path.cwd().resolve()
if cwd.name == "notebooks":
    PROJECT_ROOT = cwd.parent
elif (cwd / "dynamic_quality_aware_classwise_aggregation").exists():
    PROJECT_ROOT = cwd / "dynamic_quality_aware_classwise_aggregation" / "scene_daynight_dqa"
else:
    PROJECT_ROOT = cwd

REPO_ROOT = PROJECT_ROOT.parents[1]
WORKSPACE = PROJECT_ROOT / "output" / "01_0_repair_baseline_comparison"
print("PROJECT_ROOT", PROJECT_ROOT)
print("WORKSPACE", WORKSPACE)

PROJECT_ROOT /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa
WORKSPACE /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison

## Setup Only

Run this first if you only want to build the six client/eval lists and confirm paths.

In [2]:
CLIENT_LIMIT = 1500
subprocess.run([
    sys.executable,
    "scripts/run_scene_daynight_dqa_01_0.py",
    "--workspace-root", str(WORKSPACE),
    "--client-limit", str(CLIENT_LIMIT),
    "--conditions", "all",
    "--setup-only",
], cwd=PROJECT_ROOT, check=True)

######## condition=repair_only ########
Workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/repair_only
Warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/repair_only/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/repair_only/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/repair_only/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/repair_only/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "variant": {
    "name": "repair_oriented_all_lowlr",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_epochs": 1,
    "client_lr0": 0.0005,
    "source_repeat": 2,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "note": "Low-LR full-model client adaptation. Source GT is repeated to keep the detector close enough for server repair, while stricter stable pseudo boxes inject target-domain signal."
  }
}
Setup complete for repair_only.


######## condition=pseudo_fedavg ########
Workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg
Warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "variant": {
    "name": "repair_oriented_all_lowlr",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_epochs": 1,
    "client_lr0": 0.0005,
    "source_repeat": 2,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "note": "Low-LR full-model client adaptation. Source GT is repeated to keep the detector close enough for server repair, while stricter stable pseudo boxes inject target-domain signal."
  }
}
Setup complete for pseudo_fedavg.


######## condition=pseudo_dqa ########
Workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa
Warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "variant": {
    "name": "repair_oriented_all_lowlr",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_epochs": 1,
    "client_lr0": 0.0005,
    "source_repeat": 2,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "note": "Low-LR full-model client adaptation. Source GT is repeated to keep the detector close enough for server repair, while stricter stable pseudo boxes inject target-domain signal."
  }
}
Setup complete for pseudo_dqa.

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_scene_daynight_dqa_01_0.py', '--workspace-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison', '--client-limit', '1500', '--conditions', 'all', '--setup-only'], returncode=0)

## Run Baselines

Default is 3 rounds for all three conditions.  This can be long because `pseudo_fedavg` and `pseudo_dqa` each train six clients per round.

In [3]:
ROUNDS = 3
CONDITIONS = "all"  # repair_only,pseudo_fedavg,pseudo_dqa
MAX_IMAGES_PER_CLIENT = 0
EVAL_CLIENTS = False

cmd = [
    sys.executable,
    "scripts/run_scene_daynight_dqa_01_0.py",
    "--workspace-root", str(WORKSPACE),
    "--client-limit", str(CLIENT_LIMIT),
    "--conditions", CONDITIONS,
    "--rounds", str(ROUNDS),
    "--batch-size", "160",
    "--workers", "8",
    "--gpus", "2",
    "--master-port", "30741",
    "--server-repair-epochs", "1",
    "--evaluate",
    "--classwise",
    "--no-eval-plots",
    "--notify",
]
if MAX_IMAGES_PER_CLIENT > 0:
    cmd.extend(["--max-images-per-client", str(MAX_IMAGES_PER_CLIENT)])
if EVAL_CLIENTS:
    cmd.append("--eval-clients")

print(" ".join(cmd))
subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

/root/micromamba/envs/al_yolov8/bin/python scripts/run_scene_daynight_dqa_01_0.py --workspace-root /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison --client-limit 1500 --conditions all --rounds 3 --batch-size 160 --workers 8 --gpus 2 --master-port 30741 --server-repair-epochs 1 --evaluate --classwise --no-eval-plots --notify
DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)


######## condition=repair_only ########
Reusing completed condition metrics: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/repair_only/stats/01_0_condition_metrics.csv


######## condition=pseudo_fedavg ########
Workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg
Warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "variant": {
    "name": "repair_oriented_all_lowlr",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_epochs": 1,
    "client_lr0": 0.0005,
    "source_repeat": 2,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "note": "Low-LR full-model client adaptation. Source GT is repeated to keep the detector close enough for server repair, while stricter stable pseudo boxes inject target-domain signal."
  }
}

=== round001: pseudo labels from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

round001 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round001 client0_highway_day: pseudo scan 250/1500 images, kept 2318 boxes
round001 client0_highway_day: pseudo scan 500/1500 images, kept 4696 boxes
round001 client0_highway_day: pseudo scan 750/1500 images, kept 7005 boxes
round001 client0_highway_day: pseudo scan 1000/1500 images, kept 9304 boxes
round001 client0_highway_day: pseudo scan 1250/1500 images, kept 11580 boxes
round001 client0_highway_day: pseudo scan 1500/1500 images, kept 13881 boxes
{
  "round": "round001",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 10812,
  "boxes_per_kept_image": 7.266129032258065,
  "mean_conf": 0.7457716877548465,
  "mean_stability": 0.9449824729243165,
  "mean_score": 0.707788491927951,
  "class_counts": {
    "0": 150,
    "2": 6247,
    "3": 76,
    "4": 413,
    "5": 9,
    "7": 600,
    "8": 3317
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round001_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_client0_highway_day_stable_boxes.csv"
}
round001 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round001 client1_highway_night: pseudo scan 250/1500 images, kept 1790 boxes
round001 client1_highway_night: pseudo scan 500/1500 images, kept 3679 boxes
round001 client1_highway_night: pseudo scan 750/1500 images, kept 5547 boxes
round001 client1_highway_night: pseudo scan 1000/1500 images, kept 7377 boxes
round001 client1_highway_night: pseudo scan 1250/1500 images, kept 9229 boxes
round001 client1_highway_night: pseudo scan 1500/1500 images, kept 11039 boxes
{
  "round": "round001",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 9263,
  "boxes_per_kept_image": 6.2757452574525745,
  "mean_conf": 0.6454818118027807,
  "mean_stability": 0.9220161875161936,
  "mean_score": 0.5989198160330051,
  "class_counts": {
    "0": 54,
    "2": 4968,
    "3": 31,
    "4": 118,
    "5": 5,
    "7": 689,
    "8": 3398
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round001_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_client1_highway_night_stable_boxes.csv"
}
round001 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round001 client2_citystreet_day: pseudo scan 250/1500 images, kept 2691 boxes
round001 client2_citystreet_day: pseudo scan 500/1500 images, kept 5390 boxes
round001 client2_citystreet_day: pseudo scan 750/1500 images, kept 8121 boxes
round001 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10875 boxes
round001 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13593 boxes
round001 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16254 boxes
{
  "round": "round001",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13789,
  "boxes_per_kept_image": 9.217245989304812,
  "mean_conf": 0.7347438888736023,
  "mean_stability": 0.9405868294681854,
  "mean_score": 0.6943373476162771,
  "class_counts": {
    "0": 1331,
    "2": 7315,
    "3": 144,
    "4": 468,
    "5": 51,
    "7": 1669,
    "8": 2811
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round001_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_client2_citystreet_day_stable_boxes.csv"
}
round001 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round001 client3_citystreet_night: pseudo scan 250/1500 images, kept 2426 boxes
round001 client3_citystreet_night: pseudo scan 500/1500 images, kept 4816 boxes
round001 client3_citystreet_night: pseudo scan 750/1500 images, kept 7166 boxes
round001 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9450 boxes
round001 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11940 boxes
round001 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14338 boxes
{
  "round": "round001",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1484,
  "pseudo_boxes_kept": 12497,
  "boxes_per_kept_image": 8.421159029649596,
  "mean_conf": 0.646182291446385,
  "mean_stability": 0.9195552923073241,
  "mean_score": 0.5980796055061397,
  "class_counts": {
    "0": 515,
    "2": 6453,
    "3": 55,
    "4": 112,
    "5": 23,
    "7": 2226,
    "8": 3113
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round001_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_client3_citystreet_night_stable_boxes.csv"
}
round001 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round001 client4_residential_day: pseudo scan 250/1500 images, kept 2559 boxes
round001 client4_residential_day: pseudo scan 500/1500 images, kept 5142 boxes
round001 client4_residential_day: pseudo scan 750/1500 images, kept 7673 boxes
round001 client4_residential_day: pseudo scan 1000/1500 images, kept 10131 boxes
round001 client4_residential_day: pseudo scan 1250/1500 images, kept 12644 boxes
round001 client4_residential_day: pseudo scan 1500/1500 images, kept 15096 boxes
{
  "round": "round001",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9829,
  "boxes_per_kept_image": 6.605510752688172,
  "mean_conf": 0.7713916716212743,
  "mean_stability": 0.9511923203937447,
  "mean_score": 0.7369318894765382,
  "class_counts": {
    "0": 360,
    "2": 6794,
    "3": 41,
    "4": 228,
    "5": 27,
    "7": 556,
    "8": 1823
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round001_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_client4_residential_day_stable_boxes.csv"
}
round001 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round001 client5_residential_night: pseudo scan 250/1500 images, kept 2393 boxes
round001 client5_residential_night: pseudo scan 500/1500 images, kept 4739 boxes
round001 client5_residential_night: pseudo scan 750/1500 images, kept 7070 boxes
round001 client5_residential_night: pseudo scan 1000/1500 images, kept 9441 boxes
round001 client5_residential_night: pseudo scan 1250/1500 images, kept 11853 boxes
round001 client5_residential_night: pseudo scan 1500/1500 images, kept 14267 boxes
{
  "round": "round001",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1486,
  "pseudo_boxes_kept": 9287,
  "boxes_per_kept_image": 6.2496635262449525,
  "mean_conf": 0.7027750300574228,
  "mean_stability": 0.9328271249491495,
  "mean_score": 0.6585657579519052,
  "class_counts": {
    "0": 115,
    "2": 6421,
    "3": 28,
    "4": 69,
    "5": 15,
    "7": 735,
    "8": 1904
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round001_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round001_pseudo_label_stats.json
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_client0_highway_day.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_client1_highway_night.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_client2_citystreet_day.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_client3_citystreet_night.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_client4_residential_day.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_client5_residential_night.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_aggregate_all.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt

=== round002: pseudo labels from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round002 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round002 client0_highway_day: pseudo scan 250/1500 images, kept 2355 boxes
round002 client0_highway_day: pseudo scan 500/1500 images, kept 4781 boxes
round002 client0_highway_day: pseudo scan 750/1500 images, kept 7121 boxes
round002 client0_highway_day: pseudo scan 1000/1500 images, kept 9486 boxes
round002 client0_highway_day: pseudo scan 1250/1500 images, kept 11808 boxes
round002 client0_highway_day: pseudo scan 1500/1500 images, kept 14171 boxes
{
  "round": "round002",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1494,
  "pseudo_boxes_kept": 11016,
  "boxes_per_kept_image": 7.373493975903615,
  "mean_conf": 0.781026014937771,
  "mean_stability": 0.9540397161124146,
  "mean_score": 0.7482635167729255,
  "class_counts": {
    "0": 147,
    "2": 6377,
    "3": 96,
    "4": 515,
    "5": 7,
    "7": 568,
    "8": 3306
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round002_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_client0_highway_day_stable_boxes.csv"
}
round002 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round002 client1_highway_night: pseudo scan 250/1500 images, kept 1632 boxes
round002 client1_highway_night: pseudo scan 500/1500 images, kept 3377 boxes
round002 client1_highway_night: pseudo scan 750/1500 images, kept 5078 boxes
round002 client1_highway_night: pseudo scan 1000/1500 images, kept 6719 boxes
round002 client1_highway_night: pseudo scan 1250/1500 images, kept 8400 boxes
round002 client1_highway_night: pseudo scan 1500/1500 images, kept 10049 boxes
{
  "round": "round002",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1462,
  "pseudo_boxes_kept": 8197,
  "boxes_per_kept_image": 5.606703146374829,
  "mean_conf": 0.6791256494175679,
  "mean_stability": 0.9384764204872255,
  "mean_score": 0.6411161698761149,
  "class_counts": {
    "0": 55,
    "2": 4523,
    "3": 25,
    "4": 141,
    "5": 5,
    "7": 498,
    "8": 2950
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round002_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_client1_highway_night_stable_boxes.csv"
}
round002 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round002 client2_citystreet_day: pseudo scan 250/1500 images, kept 2689 boxes
round002 client2_citystreet_day: pseudo scan 500/1500 images, kept 5407 boxes
round002 client2_citystreet_day: pseudo scan 750/1500 images, kept 8124 boxes
round002 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10880 boxes
round002 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13589 boxes
round002 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16239 boxes
{
  "round": "round002",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13620,
  "boxes_per_kept_image": 9.10427807486631,
  "mean_conf": 0.7747086594414606,
  "mean_stability": 0.9516849154111398,
  "mean_score": 0.7405730896398693,
  "class_counts": {
    "0": 1381,
    "2": 7308,
    "3": 169,
    "4": 576,
    "5": 65,
    "7": 1566,
    "8": 2555
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round002_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_client2_citystreet_day_stable_boxes.csv"
}
round002 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round002 client3_citystreet_night: pseudo scan 250/1500 images, kept 2309 boxes
round002 client3_citystreet_night: pseudo scan 500/1500 images, kept 4583 boxes
round002 client3_citystreet_night: pseudo scan 750/1500 images, kept 6828 boxes
round002 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9011 boxes
round002 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11384 boxes
round002 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13623 boxes
{
  "round": "round002",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 11373,
  "boxes_per_kept_image": 7.726222826086956,
  "mean_conf": 0.677077690815324,
  "mean_stability": 0.9361370835152903,
  "mean_score": 0.6378484483756276,
  "class_counts": {
    "0": 502,
    "2": 6131,
    "3": 60,
    "4": 144,
    "5": 31,
    "7": 1831,
    "8": 2674
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round002_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_client3_citystreet_night_stable_boxes.csv"
}
round002 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round002 client4_residential_day: pseudo scan 250/1500 images, kept 2557 boxes
round002 client4_residential_day: pseudo scan 500/1500 images, kept 5154 boxes
round002 client4_residential_day: pseudo scan 750/1500 images, kept 7700 boxes
round002 client4_residential_day: pseudo scan 1000/1500 images, kept 10160 boxes
round002 client4_residential_day: pseudo scan 1250/1500 images, kept 12683 boxes
round002 client4_residential_day: pseudo scan 1500/1500 images, kept 15149 boxes
{
  "round": "round002",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9815,
  "boxes_per_kept_image": 6.587248322147651,
  "mean_conf": 0.8148667068640553,
  "mean_stability": 0.9601650824852883,
  "mean_score": 0.7854834466886756,
  "class_counts": {
    "0": 351,
    "2": 6818,
    "3": 50,
    "4": 306,
    "5": 38,
    "7": 537,
    "8": 1715
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round002_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_client4_residential_day_stable_boxes.csv"
}
round002 client5_residential_night: pseudo scan 1/1500 images, kept 10 boxes
round002 client5_residential_night: pseudo scan 250/1500 images, kept 2290 boxes
round002 client5_residential_night: pseudo scan 500/1500 images, kept 4529 boxes
round002 client5_residential_night: pseudo scan 750/1500 images, kept 6766 boxes
round002 client5_residential_night: pseudo scan 1000/1500 images, kept 9081 boxes
round002 client5_residential_night: pseudo scan 1250/1500 images, kept 11384 boxes
round002 client5_residential_night: pseudo scan 1500/1500 images, kept 13704 boxes
{
  "round": "round002",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1473,
  "pseudo_boxes_kept": 8425,
  "boxes_per_kept_image": 5.719619823489477,
  "mean_conf": 0.7534019593102995,
  "mean_stability": 0.948519767505125,
  "mean_score": 0.7173718294448881,
  "class_counts": {
    "0": 106,
    "2": 6167,
    "3": 29,
    "4": 91,
    "5": 15,
    "7": 562,
    "8": 1455
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round002_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round002_pseudo_label_stats.json
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_client0_highway_day.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_client1_highway_night.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_client2_citystreet_day.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_client3_citystreet_night.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_client4_residential_day.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_client5_residential_night.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_aggregate_all.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt

=== round003: pseudo labels from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round003 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round003 client0_highway_day: pseudo scan 250/1500 images, kept 2349 boxes
round003 client0_highway_day: pseudo scan 500/1500 images, kept 4770 boxes
round003 client0_highway_day: pseudo scan 750/1500 images, kept 7110 boxes
round003 client0_highway_day: pseudo scan 1000/1500 images, kept 9472 boxes
round003 client0_highway_day: pseudo scan 1250/1500 images, kept 11795 boxes
round003 client0_highway_day: pseudo scan 1500/1500 images, kept 14156 boxes
{
  "round": "round003",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1494,
  "pseudo_boxes_kept": 11041,
  "boxes_per_kept_image": 7.390227576974565,
  "mean_conf": 0.7882740138050179,
  "mean_stability": 0.9551828126848613,
  "mean_score": 0.756074503887304,
  "class_counts": {
    "0": 148,
    "2": 6371,
    "3": 102,
    "4": 521,
    "5": 7,
    "7": 561,
    "8": 3331
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_client0_highway_day_stable_boxes.csv"
}
round003 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round003 client1_highway_night: pseudo scan 250/1500 images, kept 1478 boxes
round003 client1_highway_night: pseudo scan 500/1500 images, kept 3074 boxes
round003 client1_highway_night: pseudo scan 750/1500 images, kept 4652 boxes
round003 client1_highway_night: pseudo scan 1000/1500 images, kept 6135 boxes
round003 client1_highway_night: pseudo scan 1250/1500 images, kept 7673 boxes
round003 client1_highway_night: pseudo scan 1500/1500 images, kept 9206 boxes
{
  "round": "round003",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1436,
  "pseudo_boxes_kept": 7570,
  "boxes_per_kept_image": 5.27158774373259,
  "mean_conf": 0.682436713182627,
  "mean_stability": 0.9419648920056685,
  "mean_score": 0.6465258023644656,
  "class_counts": {
    "0": 57,
    "2": 4143,
    "3": 25,
    "4": 131,
    "5": 6,
    "7": 493,
    "8": 2715
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_client1_highway_night_stable_boxes.csv"
}
round003 client2_citystreet_day: pseudo scan 1/1500 images, kept 7 boxes
round003 client2_citystreet_day: pseudo scan 250/1500 images, kept 2694 boxes
round003 client2_citystreet_day: pseudo scan 500/1500 images, kept 5412 boxes
round003 client2_citystreet_day: pseudo scan 750/1500 images, kept 8139 boxes
round003 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10900 boxes
round003 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13615 boxes
round003 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16261 boxes
{
  "round": "round003",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13606,
  "boxes_per_kept_image": 9.101003344481605,
  "mean_conf": 0.783638807251561,
  "mean_stability": 0.9530318980705522,
  "mean_score": 0.7501343190354721,
  "class_counts": {
    "0": 1400,
    "2": 7318,
    "3": 184,
    "4": 571,
    "5": 64,
    "7": 1538,
    "8": 2531
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_client2_citystreet_day_stable_boxes.csv"
}
round003 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round003 client3_citystreet_night: pseudo scan 250/1500 images, kept 2169 boxes
round003 client3_citystreet_night: pseudo scan 500/1500 images, kept 4307 boxes
round003 client3_citystreet_night: pseudo scan 750/1500 images, kept 6407 boxes
round003 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8479 boxes
round003 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10730 boxes
round003 client3_citystreet_night: pseudo scan 1500/1500 images, kept 12856 boxes
{
  "round": "round003",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1467,
  "pseudo_boxes_kept": 10797,
  "boxes_per_kept_image": 7.359918200408998,
  "mean_conf": 0.6753213089809955,
  "mean_stability": 0.9380344861059638,
  "mean_score": 0.6376480170324009,
  "class_counts": {
    "0": 505,
    "2": 5786,
    "3": 57,
    "4": 130,
    "5": 32,
    "7": 1819,
    "8": 2468
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_client3_citystreet_night_stable_boxes.csv"
}
round003 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round003 client4_residential_day: pseudo scan 250/1500 images, kept 2577 boxes
round003 client4_residential_day: pseudo scan 500/1500 images, kept 5166 boxes
round003 client4_residential_day: pseudo scan 750/1500 images, kept 7708 boxes
round003 client4_residential_day: pseudo scan 1000/1500 images, kept 10174 boxes
round003 client4_residential_day: pseudo scan 1250/1500 images, kept 12701 boxes
round003 client4_residential_day: pseudo scan 1500/1500 images, kept 15175 boxes
{
  "round": "round003",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9839,
  "boxes_per_kept_image": 6.612231182795699,
  "mean_conf": 0.8220363605227191,
  "mean_stability": 0.9610356536746595,
  "mean_score": 0.7931642759887199,
  "class_counts": {
    "0": 358,
    "2": 6829,
    "3": 52,
    "4": 304,
    "5": 43,
    "7": 539,
    "8": 1714
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_client4_residential_day_stable_boxes.csv"
}
round003 client5_residential_night: pseudo scan 1/1500 images, kept 7 boxes
round003 client5_residential_night: pseudo scan 250/1500 images, kept 2145 boxes
round003 client5_residential_night: pseudo scan 500/1500 images, kept 4224 boxes
round003 client5_residential_night: pseudo scan 750/1500 images, kept 6310 boxes
round003 client5_residential_night: pseudo scan 1000/1500 images, kept 8463 boxes
round003 client5_residential_night: pseudo scan 1250/1500 images, kept 10616 boxes
round003 client5_residential_night: pseudo scan 1500/1500 images, kept 12765 boxes
{
  "round": "round003",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1455,
  "pseudo_boxes_kept": 7874,
  "boxes_per_kept_image": 5.411683848797251,
  "mean_conf": 0.7494485364223392,
  "mean_stability": 0.9507811162218637,
  "mean_score": 0.7153726660602575,
  "class_counts": {
    "0": 106,
    "2": 5745,
    "3": 30,
    "4": 81,
    "5": 19,
    "7": 556,
    "8": 1337
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/stats/03_round003_pseudo_label_stats.json
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round003_repair_oriented_all_lowlr_client0_highway_day.pt
Reusing checkpoint: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round003_repair_oriented_all_lowlr_client1_highway_night.pt
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30841 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/configs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/client_states/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11257/11257 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11257/11257 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 9462.22it/s]
val: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 11:36:04.585741377 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 11:36:04.588986032 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1935       640   0.03453   0.05029  0.004853     7.174:   3%|▎         | 1/39 [00:32<20:37, 32.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2130       640   0.03442   0.05017  0.005012     7.168:   5%|▌         | 2/39 [00:33<08:43, 14.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1870       640   0.03414   0.04939  0.004928     7.076:   8%|▊         | 3/39 [00:34<04:55,  8.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2051       640   0.03404   0.04857  0.004997     7.009:  10%|█         | 4/39 [00:36<03:09,  5.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2170       640   0.03403   0.04802  0.004897     6.956:  13%|█▎        | 5/39 [00:36<02:08,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1572       640   0.03381   0.04649  0.004837     6.811:  15%|█▌        | 6/39 [00:37<01:32,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640   0.03409   0.04658  0.004974     6.851:  18%|█▊        | 7/39 [00:38<01:09,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1888       640   0.03395   0.04606  0.004928     6.796:  21%|██        | 8/39 [00:39<00:54,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2066       640   0.03404   0.04614  0.004868     6.804:  23%|██▎       | 9/39 [00:40<00:44,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1830       640    0.0339   0.04574   0.00482     6.757:  26%|██▌       | 10/39 [00:41<00:37,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2070       640   0.03394   0.04558   0.00483     6.748:  28%|██▊       | 11/39 [00:42<00:32,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1746       640   0.03398   0.04526  0.004882      6.73:  31%|███       | 12/39 [00:43<00:29,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2202       640   0.03408    0.0454  0.004855     6.747:  33%|███▎      | 13/39 [00:44<00:26,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2071       640   0.03417   0.04535  0.004827     6.748:  36%|███▌      | 14/39 [00:44<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2002       640   0.03419   0.04532  0.004839     6.748:  38%|███▊      | 15/39 [00:45<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2060       640   0.03422   0.04512  0.004857     6.736:  41%|████      | 16/39 [00:46<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1888       640   0.03423   0.04514  0.004864     6.739:  44%|████▎     | 17/39 [00:47<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2057       640   0.03415   0.04516  0.004844     6.733:  46%|████▌     | 18/39 [00:48<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1717       640   0.03413   0.04491    0.0048     6.707:  49%|████▊     | 19/39 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2180       640   0.03411   0.04498  0.004813     6.712:  51%|█████▏    | 20/39 [00:50<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1917       640   0.03404   0.04482  0.004786     6.692:  54%|█████▍    | 21/39 [00:51<00:16,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1948       640   0.03401   0.04487  0.004766     6.692:  56%|█████▋    | 22/39 [00:52<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1922       640     0.034   0.04473  0.004774     6.681:  59%|█████▉    | 23/39 [00:52<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2140       640   0.03399    0.0448  0.004753     6.684:  62%|██████▏   | 24/39 [00:53<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2077       640   0.03399   0.04473  0.004753     6.678:  64%|██████▍   | 25/39 [00:54<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1924       640   0.03399   0.04471  0.004766     6.677:  67%|██████▋   | 26/39 [00:55<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.502       0.44       0.41      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.501      0.434       0.41      0.233
                   0        738       1052      0.566      0.529      0.535      0.258
                   1        738         44      0.412      0.182      0.172     0.0767
                   2        738       8622      0.611      0.755      0.757      0.487
                   3        738        151      0.322      0.437      0.421      0.325
                   4        738        467      0.439      0.612      0.547      0.396
                   5        738         70      0.277      0.426      0.279      0.141
                   6        738         65      0.271      0.137      0.179     0.0715
                   7        738       1619      0.529      0.633      0.589      0.249
                   8        738       2845      0.584      0.626      0.615      0.324
                   9        738          2          1          0   0.000242   0.000217

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 11:38:01.004921356 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30842 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/configs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/client_states/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client3_citystreet_night_stable_train' images and labels...9763 found, 1466 missing, 0 empty, 0 corrupted: 100%|██████████| 11229/11229 [00:01<00:00, 10897.03it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.302190011028832
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache' images and labels... 9763 found, 1466 missing, 0 empty, 0 corrupted: 100%|██████████| 11229/11229 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 11:38:18.049644631 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 11:38:18.057135997 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2033       640   0.03356   0.04302  0.004783     6.509:   2%|▎         | 1/40 [00:32<21:13, 32.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1824       640   0.03315   0.04146  0.004614     6.338:   5%|▌         | 2/40 [00:33<08:56, 14.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1865       640   0.03332   0.04081  0.004611       6.3:   8%|▊         | 3/40 [00:34<05:02,  8.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1763       640   0.03316   0.04008  0.004701     6.235:  10%|█         | 4/40 [00:35<03:13,  5.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1869       640    0.0333   0.03968  0.004603     6.207:  12%|█▎        | 5/40 [00:36<02:11,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1796       640   0.03337   0.03934  0.004596     6.185:  15%|█▌        | 6/40 [00:37<01:34,  2.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1857       640   0.03327   0.03905  0.004554      6.15:  18%|█▊        | 7/40 [00:38<01:11,  2.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2083       640   0.03331   0.03928   0.00458     6.174:  20%|██        | 8/40 [00:39<00:56,  1.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1899       640   0.03331   0.03911  0.004562     6.159:  22%|██▎       | 9/40 [00:40<00:46,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1847       640   0.03344   0.03876  0.004608     6.145:  25%|██▌       | 10/40 [00:41<00:39,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2076       640    0.0335   0.03888  0.004646     6.162:  28%|██▊       | 11/40 [00:42<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2016       640    0.0336   0.03894  0.004677     6.178:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1948       640   0.03362   0.03879  0.004697     6.168:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2119       640   0.03376   0.03875  0.004738      6.18:  35%|███▌      | 14/40 [00:44<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1970       640   0.03389   0.03864  0.004756     6.182:  38%|███▊      | 15/40 [00:45<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1857       640   0.03385   0.03847  0.004757     6.166:  40%|████      | 16/40 [00:46<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1585       640   0.03392   0.03812  0.004757     6.144:  42%|████▎     | 17/40 [00:47<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1783       640   0.03386   0.03783  0.004773     6.117:  45%|████▌     | 18/40 [00:48<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1604       640   0.03389   0.03749  0.004779     6.093:  48%|████▊     | 19/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1942       640   0.03387   0.03744  0.004767     6.086:  50%|█████     | 20/40 [00:50<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2071       640   0.03394   0.03742  0.004764      6.09:  52%|█████▎    | 21/40 [00:51<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1832       640   0.03392   0.03721  0.004755     6.071:  55%|█████▌    | 22/40 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2113       640   0.03391   0.03723  0.004793     6.075:  57%|█████▊    | 23/40 [00:52<00:15,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1946       640    0.0339    0.0371  0.004793     6.063:  60%|██████    | 24/40 [00:53<00:14,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1912       640   0.03391   0.03699  0.004799     6.055:  62%|██████▎   | 25/40 [00:54<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640   0.03398   0.03701  0.004791     6.062:  65%|██████▌   | 26/40 [00:55<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.526      0.401      0.403      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.556      0.387      0.402      0.227
                   0        738       1052      0.613      0.493      0.514      0.243
                   1        738         44      0.425     0.0673      0.162     0.0654
                   2        738       8622      0.675      0.721      0.747      0.482
                   3        738        151      0.451      0.397      0.419      0.324
                   4        738        467      0.461      0.597      0.552      0.397
                   5        738         70      0.335      0.357       0.26      0.128
                   6        738         65      0.345     0.0615      0.174     0.0682
                   7        738       1619      0.592      0.596      0.588      0.244
                   8        738       2845      0.659      0.579      0.602      0.316
                   9        738          2          1          0   0.000182   0.000164

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 11:40:16.016734678 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30843 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/configs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/client_states/pl03_round003_repair_oriented_all_lowlr_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client4_residential_day_stable_train' images and labels...9921 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<00:00, 11585.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client4_residential_day_stable_train.cache' images and labels... 9921 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 11:40:33.979494874 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 11:40:33.000245882 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1912       640   0.03477   0.05011  0.004876     7.181:   3%|▎         | 1/39 [00:33<20:58, 33.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2152       640   0.03452    0.0509  0.004887     7.225:   5%|▌         | 2/39 [00:34<08:50, 14.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1851       640   0.03411   0.04837  0.004987     6.997:   8%|▊         | 3/39 [00:35<04:57,  8.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2029       640   0.03402   0.04694  0.004977     6.875:  10%|█         | 4/39 [00:36<03:10,  5.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03407   0.04645  0.004852     6.829:  13%|█▎        | 5/39 [00:37<02:09,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1677       640   0.03381     0.045  0.004726     6.683:  15%|█▌        | 6/39 [00:38<01:32,  2.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1884       640     0.034   0.04488  0.004834     6.697:  18%|█▊        | 7/39 [00:39<01:09,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2030       640   0.03393   0.04451  0.004807      6.66:  21%|██        | 8/39 [00:40<00:54,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2074       640   0.03393   0.04462  0.004687     6.659:  23%|██▎       | 9/39 [00:40<00:44,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1907       640   0.03392   0.04447  0.004716     6.649:  26%|██▌       | 10/39 [00:41<00:37,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640   0.03388    0.0441  0.004718     6.616:  28%|██▊       | 11/39 [00:42<00:33,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1865       640   0.03389   0.04386  0.004772     6.602:  31%|███       | 12/39 [00:43<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2110       640   0.03398   0.04395  0.004734     6.613:  33%|███▎      | 13/39 [00:44<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1875       640   0.03398   0.04359  0.004726     6.584:  36%|███▌      | 14/39 [00:45<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2104       640   0.03406   0.04364  0.004728     6.594:  38%|███▊      | 15/39 [00:46<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1925       640   0.03409    0.0434  0.004747     6.579:  41%|████      | 16/39 [00:47<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1967       640   0.03412   0.04336  0.004776      6.58:  44%|████▎     | 17/39 [00:48<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1944       640   0.03407   0.04324   0.00475     6.565:  46%|████▌     | 18/39 [00:48<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1848       640   0.03405   0.04302  0.004726     6.544:  49%|████▊     | 19/39 [00:49<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2079       640     0.034   0.04305  0.004739     6.543:  51%|█████▏    | 20/39 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1902       640   0.03395   0.04296  0.004745     6.532:  54%|█████▍    | 21/39 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1956       640   0.03395   0.04302  0.004725     6.536:  56%|█████▋    | 22/39 [00:52<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2070       640   0.03396   0.04298   0.00473     6.533:  59%|█████▉    | 23/39 [00:53<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1979       640   0.03394   0.04297  0.004718      6.53:  62%|██████▏   | 24/39 [00:54<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1885       640   0.03394   0.04287  0.004706     6.521:  64%|██████▍   | 25/39 [00:55<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640   0.03392   0.04286  0.004729      6.52:  67%|██████▋   | 26/39 [00:55<00:11,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.459      0.474      0.412      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.531      0.409      0.413      0.233
                   0        738       1052      0.537      0.542      0.541      0.258
                   1        738         44      0.451      0.112       0.19     0.0741
                   2        738       8622      0.686      0.725      0.752      0.484
                   3        738        151      0.407      0.444      0.437      0.331
                   4        738        467      0.458      0.591      0.548      0.398
                   5        738         70       0.26      0.386      0.279      0.142
                   6        738         65      0.301     0.0769      0.173     0.0674
                   7        738       1619      0.568      0.615      0.594      0.248
                   8        738       2845      0.638        0.6      0.613      0.322
                   9        738          2          1          0   0.000224   0.000201

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 11:42:32.249573800 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30844 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/configs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/client_states/pl03_round003_repair_oriented_all_lowlr_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client5_residential_night_stable_train' images and labels...9764 found, 1453 missing, 0 empty, 0 corrupted: 100%|██████████| 11217/11217 [00:01<00:00, 8975.20it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.333596463530155
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/pl03_round003_client5_residential_night_stable_train.cache' images and labels... 9764 found, 1453 missing, 0 empty, 0 corrupted: 100%|██████████| 11217/11217 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 11:42:49.752146354 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 11:42:49.769039569 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1836       640    0.0328   0.04016  0.004892     6.228:   2%|▎         | 1/40 [00:33<21:31, 33.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1901       640   0.03337   0.04079  0.004922     6.327:   5%|▌         | 2/40 [00:34<09:07, 14.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2027       640   0.03323   0.04131  0.004711      6.34:   8%|▊         | 3/40 [00:35<05:10,  8.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1912       640   0.03346    0.0412  0.004801     6.357:  10%|█         | 4/40 [00:36<03:18,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2057       640   0.03376   0.04103   0.00475     6.363:  12%|█▎        | 5/40 [00:37<02:15,  3.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1640       640   0.03376   0.04042  0.004829     6.321:  15%|█▌        | 6/40 [00:38<01:36,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1988       640   0.03396   0.04015  0.004744     6.308:  18%|█▊        | 7/40 [00:39<01:12,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1932       640    0.0341   0.03996  0.004749     6.305:  20%|██        | 8/40 [00:40<00:57,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2076       640   0.03408   0.03992  0.004716     6.297:  22%|██▎       | 9/40 [00:41<00:46,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1898       640   0.03411   0.03971  0.004679      6.28:  25%|██▌       | 10/40 [00:42<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2154       640   0.03418   0.03964  0.004713     6.283:  28%|██▊       | 11/40 [00:43<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1965       640   0.03416   0.03945  0.004764     6.269:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1992       640   0.03427   0.03931   0.00476     6.267:  32%|███▎      | 13/40 [00:44<00:27,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1962       640    0.0343   0.03904  0.004769     6.249:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1827       640   0.03426   0.03866  0.004774     6.215:  38%|███▊      | 15/40 [00:46<00:23,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1934       640    0.0343    0.0385  0.004771     6.205:  40%|████      | 16/40 [00:47<00:22,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1956       640   0.03431   0.03838  0.004791     6.198:  42%|████▎     | 17/40 [00:48<00:20,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2041       640   0.03436   0.03826  0.004825     6.196:  45%|████▌     | 18/40 [00:49<00:19,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1560       640    0.0343   0.03775  0.004824      6.15:  48%|████▊     | 19/40 [00:49<00:18,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1973       640   0.03426   0.03764  0.004822     6.137:  50%|█████     | 20/40 [00:50<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1922       640   0.03427   0.03752  0.004816     6.128:  52%|█████▎    | 21/40 [00:51<00:16,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1908       640   0.03428   0.03744  0.004836     6.125:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2129       640   0.03427   0.03738   0.00485     6.119:  57%|█████▊    | 23/40 [00:53<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2037       640   0.03429    0.0373  0.004864     6.116:  60%|██████    | 24/40 [00:54<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1925       640   0.03434   0.03714  0.004886     6.109:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1992       640   0.03434   0.03709  0.004887     6.105:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.523      0.414      0.408       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.508      0.416      0.404      0.229
                   0        738       1052      0.501      0.547      0.528      0.252
                   1        738         44      0.412      0.136      0.184     0.0732
                   2        738       8622      0.641      0.738       0.75      0.482
                   3        738        151      0.369       0.43      0.426      0.331
                   4        738        467      0.426      0.612      0.555      0.403
                   5        738         70      0.328      0.357      0.246      0.126
                   6        738         65      0.273     0.0923      0.155     0.0616
                   7        738       1619      0.538      0.631       0.59      0.245
                   8        738       2845      0.589      0.615      0.606      0.318
                   9        738          2          1          0   0.000187   0.000187

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 11:44:47.704609036 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30845 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/configs/pl03_round003_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round003_repair_oriented_all_lowlr_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 19717.44it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 11:45:05.344906532 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 11:45:05.350949304 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03326   0.04309  0.004716     6.486:   3%|▎         | 1/31 [00:32<16:11, 32.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03398   0.04386  0.004935     6.622:   6%|▋         | 2/31 [00:33<06:40, 13.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640    0.0335   0.04268   0.00486     6.483:  10%|▉         | 3/31 [00:33<03:39,  7.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03298   0.04084  0.004624     6.276:  13%|█▎        | 4/31 [00:34<02:16,  5.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03302   0.04099  0.004654     6.293:  16%|█▌        | 5/31 [00:35<01:29,  3.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03322   0.04089  0.004723     6.307:  19%|█▉        | 6/31 [00:35<01:01,  2.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03336    0.0406  0.004794       6.3:  23%|██▎       | 7/31 [00:36<00:44,  1.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03331   0.04068  0.004819     6.305:  26%|██▌       | 8/31 [00:37<00:33,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03337   0.04062  0.004721     6.297:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03336   0.04072  0.004702     6.303:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03333   0.04073  0.004728     6.303:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03324   0.04044  0.004719     6.271:  39%|███▊      | 12/31 [00:39<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03321   0.04046  0.004668     6.267:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03323   0.04026   0.00463      6.25:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03326   0.04016  0.004672     6.247:  48%|████▊     | 15/31 [00:41<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03326   0.04001  0.004662     6.234:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640    0.0333   0.04004  0.004627     6.238:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03334   0.04007  0.004588      6.24:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03328   0.03992  0.004554      6.22:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03328   0.04013  0.004555     6.237:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03331   0.04015  0.004574     6.242:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03331   0.04024  0.004546     6.248:  71%|███████   | 22/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640    0.0333   0.04027   0.00453     6.248:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03331   0.04034  0.004515     6.253:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03332   0.04028  0.004525      6.25:  81%|████████  | 25/31 [00:46<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03337    0.0403  0.004528     6.256:  84%|████████▍ | 26/31 [00:47<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.483       0.46      0.413      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.561      0.397      0.412      0.234
                   0        738       1052      0.605      0.527      0.546       0.26
                   1        738         44       0.41     0.0795       0.16     0.0673
                   2        738       8622      0.701      0.727      0.756      0.489
                   3        738        151       0.54      0.417      0.434      0.329
                   4        738        467      0.527      0.557      0.558      0.407
                   5        738         70      0.265      0.414      0.281      0.144
                   6        738         65      0.293     0.0615      0.172     0.0654
                   7        738       1619      0.607      0.586      0.591      0.245
                   8        738       2845      0.659      0.599      0.618      0.328
                   9        738          2          1          0   0.000351   0.000351

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/runs/pl03_round003_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 11:46:44.358569364 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/evaluate_scene_daynight_protocol.py --workspace /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg --splits highway_day,highway_night,citystreet_day,citystreet_night,residential_day,residential_night,total --batch-size 16 --no-plots --verbose --checkpoint warmup_global=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/global_checkpoints/round000_warmup.pt --checkpoint round001_aggregate_all=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_aggregate_all.pt --checkpoint round001_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round001_repair_oriented_all_lowlr_server_repair.pt --checkpoint round002_aggregate_all=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_aggregate_all.pt --checkpoint round002_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round002_repair_oriented_all_lowlr_server_repair.pt --checkpoint round003_aggregate_all=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round003_repair_oriented_all_lowlr_aggregate_all.pt --checkpoint round003_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/checkpoints/round003_repair_oriented_all_lowlr_server_repair.pt
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/validation_reports/paper_protocol_eval_manifest.json
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/validation_reports/paper_protocol_eval_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/validation_reports/paper_protocol_classwise_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_fedavg/validation_reports/paper_protocol_eval_summary.md


######## condition=pseudo_dqa ########
Workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa
Warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "variant": {
    "name": "repair_oriented_all_lowlr",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_epochs": 1,
    "client_lr0": 0.0005,
    "source_repeat": 2,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "note": "Low-LR full-model client adaptation. Source GT is repeated to keep the detector close enough for server repair, while stricter stable pseudo boxes inject target-domain signal."
  }
}

=== round001: DQA scene-daynight round ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round001 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round001 client0_highway_day: pseudo scan 250/1500 images, kept 2318 boxes
round001 client0_highway_day: pseudo scan 500/1500 images, kept 4696 boxes
round001 client0_highway_day: pseudo scan 750/1500 images, kept 7005 boxes
round001 client0_highway_day: pseudo scan 1000/1500 images, kept 9304 boxes
round001 client0_highway_day: pseudo scan 1250/1500 images, kept 11580 boxes
round001 client0_highway_day: pseudo scan 1500/1500 images, kept 13881 boxes
{
  "round": "round001",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 10812,
  "boxes_per_kept_image": 7.266129032258065,
  "mean_conf": 0.7457716877548465,
  "mean_stability": 0.9449824729243165,
  "mean_score": 0.707788491927951,
  "class_counts": {
    "0": 150,
    "2": 6247,
    "3": 76,
    "4": 413,
    "5": 9,
    "7": 600,
    "8": 3317
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_client0_highway_day_stable_boxes.csv"
}
round001 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round001 client1_highway_night: pseudo scan 250/1500 images, kept 1790 boxes
round001 client1_highway_night: pseudo scan 500/1500 images, kept 3679 boxes
round001 client1_highway_night: pseudo scan 750/1500 images, kept 5547 boxes
round001 client1_highway_night: pseudo scan 1000/1500 images, kept 7377 boxes
round001 client1_highway_night: pseudo scan 1250/1500 images, kept 9229 boxes
round001 client1_highway_night: pseudo scan 1500/1500 images, kept 11039 boxes
{
  "round": "round001",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 9263,
  "boxes_per_kept_image": 6.2757452574525745,
  "mean_conf": 0.6454818118027807,
  "mean_stability": 0.9220161875161936,
  "mean_score": 0.5989198160330051,
  "class_counts": {
    "0": 54,
    "2": 4968,
    "3": 31,
    "4": 118,
    "5": 5,
    "7": 689,
    "8": 3398
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_client1_highway_night_stable_boxes.csv"
}
round001 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round001 client2_citystreet_day: pseudo scan 250/1500 images, kept 2691 boxes
round001 client2_citystreet_day: pseudo scan 500/1500 images, kept 5390 boxes
round001 client2_citystreet_day: pseudo scan 750/1500 images, kept 8121 boxes
round001 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10875 boxes
round001 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13593 boxes
round001 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16254 boxes
{
  "round": "round001",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13789,
  "boxes_per_kept_image": 9.217245989304812,
  "mean_conf": 0.7347438888736023,
  "mean_stability": 0.9405868294681854,
  "mean_score": 0.6943373476162771,
  "class_counts": {
    "0": 1331,
    "2": 7315,
    "3": 144,
    "4": 468,
    "5": 51,
    "7": 1669,
    "8": 2811
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_client2_citystreet_day_stable_boxes.csv"
}
round001 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round001 client3_citystreet_night: pseudo scan 250/1500 images, kept 2426 boxes
round001 client3_citystreet_night: pseudo scan 500/1500 images, kept 4816 boxes
round001 client3_citystreet_night: pseudo scan 750/1500 images, kept 7166 boxes
round001 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9450 boxes
round001 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11940 boxes
round001 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14338 boxes
{
  "round": "round001",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1484,
  "pseudo_boxes_kept": 12497,
  "boxes_per_kept_image": 8.421159029649596,
  "mean_conf": 0.646182291446385,
  "mean_stability": 0.9195552923073241,
  "mean_score": 0.5980796055061397,
  "class_counts": {
    "0": 515,
    "2": 6453,
    "3": 55,
    "4": 112,
    "5": 23,
    "7": 2226,
    "8": 3113
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_client3_citystreet_night_stable_boxes.csv"
}
round001 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round001 client4_residential_day: pseudo scan 250/1500 images, kept 2559 boxes
round001 client4_residential_day: pseudo scan 500/1500 images, kept 5142 boxes
round001 client4_residential_day: pseudo scan 750/1500 images, kept 7673 boxes
round001 client4_residential_day: pseudo scan 1000/1500 images, kept 10131 boxes
round001 client4_residential_day: pseudo scan 1250/1500 images, kept 12644 boxes
round001 client4_residential_day: pseudo scan 1500/1500 images, kept 15096 boxes
{
  "round": "round001",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9829,
  "boxes_per_kept_image": 6.605510752688172,
  "mean_conf": 0.7713916716212743,
  "mean_stability": 0.9511923203937447,
  "mean_score": 0.7369318894765382,
  "class_counts": {
    "0": 360,
    "2": 6794,
    "3": 41,
    "4": 228,
    "5": 27,
    "7": 556,
    "8": 1823
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_client4_residential_day_stable_boxes.csv"
}
round001 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round001 client5_residential_night: pseudo scan 250/1500 images, kept 2393 boxes
round001 client5_residential_night: pseudo scan 500/1500 images, kept 4739 boxes
round001 client5_residential_night: pseudo scan 750/1500 images, kept 7070 boxes
round001 client5_residential_night: pseudo scan 1000/1500 images, kept 9441 boxes
round001 client5_residential_night: pseudo scan 1250/1500 images, kept 11853 boxes
round001 client5_residential_night: pseudo scan 1500/1500 images, kept 14267 boxes
{
  "round": "round001",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1486,
  "pseudo_boxes_kept": 9287,
  "boxes_per_kept_image": 6.2496635262449525,
  "mean_conf": 0.7027750300574228,
  "mean_stability": 0.9328271249491495,
  "mean_score": 0.6585657579519052,
  "class_counts": {
    "0": 115,
    "2": 6421,
    "3": 28,
    "4": 69,
    "5": 15,
    "7": 735,
    "8": 1904
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round001_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30941 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round001_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client0_highway_day_stable_train' images and labels...10001 found, 1249 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<00:00, 13901.68it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.843882544861337
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.cache' images and labels... 10001 found, 1249 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 9142.18it/s]
val: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 12:02:45.128645531 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 12:02:45.134650215 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2007       640   0.03829   0.04651  0.006387     7.295:   3%|▎         | 1/39 [00:33<21:14, 33.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1914       640   0.03919    0.0462  0.006055     7.316:   5%|▌         | 2/39 [00:34<08:57, 14.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2240       640   0.03927   0.04605  0.006186      7.32:   8%|▊         | 3/39 [00:36<05:08,  8.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1973       640   0.03882   0.04625  0.005967     7.283:  10%|█         | 4/39 [00:37<03:16,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2097       640   0.03838   0.04582  0.005733     7.195:  13%|█▎        | 5/39 [00:38<02:13,  3.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1828       640   0.03808   0.04522   0.00573     7.122:  15%|█▌        | 6/39 [00:39<01:35,  2.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1893       640    0.0377   0.04463  0.005656     7.039:  18%|█▊        | 7/39 [00:40<01:11,  2.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2178       640   0.03746   0.04448  0.005586     7.002:  21%|██        | 8/39 [00:40<00:56,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2177       640    0.0374   0.04454  0.005585     7.002:  23%|██▎       | 9/39 [00:41<00:46,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1891       640   0.03737   0.04441  0.005709         7:  26%|██▌       | 10/39 [00:42<00:39,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2046       640   0.03724   0.04439  0.005675     6.985:  28%|██▊       | 11/39 [00:43<00:34,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1922       640   0.03714   0.04417  0.005656     6.958:  31%|███       | 12/39 [00:44<00:30,  1.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1825       640   0.03692   0.04387   0.00564     6.914:  33%|███▎      | 13/39 [00:45<00:27,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2042       640   0.03681   0.04375  0.005593     6.893:  36%|███▌      | 14/39 [00:46<00:25,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2045       640   0.03685    0.0437   0.00562     6.894:  38%|███▊      | 15/39 [00:47<00:23,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1837       640   0.03679   0.04343  0.005622     6.867:  41%|████      | 16/39 [00:48<00:21,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1742       640   0.03671    0.0432  0.005626     6.843:  44%|████▎     | 17/39 [00:49<00:20,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1997       640   0.03662   0.04312  0.005615     6.829:  46%|████▌     | 18/39 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1673       640   0.03655   0.04291  0.005621     6.806:  49%|████▊     | 19/39 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2254       640    0.0365   0.04306  0.005613     6.814:  51%|█████▏    | 20/39 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2071       640    0.0365   0.04305  0.005608     6.812:  54%|█████▍    | 21/39 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1786       640   0.03648   0.04296  0.005642     6.807:  56%|█████▋    | 22/39 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2126       640   0.03639     0.043  0.005592     6.798:  59%|█████▉    | 23/39 [00:54<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2061       640   0.03629   0.04295  0.005572     6.785:  62%|██████▏   | 24/39 [00:55<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2155       640   0.03631   0.04298  0.005576     6.789:  64%|██████▍   | 25/39 [00:56<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2054       640   0.03625   0.04299  0.005575     6.786:  67%|██████▋   | 26/39 [00:57<00:11,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.473      0.434      0.396      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.462      0.438      0.395      0.223
                   0        738       1052       0.44      0.572       0.54      0.255
                   1        738         44      0.313      0.197      0.147     0.0632
                   2        738       8622      0.593      0.749      0.749      0.482
                   3        738        151       0.31      0.391      0.378      0.297
                   4        738        467       0.43      0.608       0.54      0.392
                   5        738         70       0.23      0.429      0.247      0.125
                   6        738         65       0.25      0.169      0.156     0.0577
                   7        738       1619      0.507      0.629      0.584      0.242
                   8        738       2845      0.545      0.634      0.606      0.313
                   9        738          2          1          0   0.000267   0.000241

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:04:42.336629128 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30942 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round001_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client1_highway_night_stable_train' images and labels...9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:01<00:00, 9173.07it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29496062992126
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.cache' images and labels... 9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:04:59.674476850 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:04:59.695173876 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2011       640   0.04001    0.0454  0.006483     7.351:   2%|▎         | 1/40 [00:33<21:49, 33.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1977       640   0.04028   0.04368  0.006124     7.207:   5%|▌         | 2/40 [00:34<09:08, 14.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1708       640   0.03918    0.0423  0.005712     6.976:   8%|▊         | 3/40 [00:35<05:12,  8.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2074       640   0.03873   0.04199  0.005625     6.908:  10%|█         | 4/40 [00:37<03:19,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1992       640   0.03837   0.04199  0.005619     6.878:  12%|█▎        | 5/40 [00:37<02:15,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1807       640   0.03788   0.04118  0.005618     6.774:  15%|█▌        | 6/40 [00:38<01:37,  2.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2020       640   0.03759   0.04086  0.005646     6.728:  18%|█▊        | 7/40 [00:39<01:13,  2.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1921       640   0.03729   0.04064  0.005625     6.684:  20%|██        | 8/40 [00:40<00:58,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1956       640   0.03722    0.0405   0.00562     6.666:  22%|██▎       | 9/40 [00:41<00:48,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1950       640   0.03716   0.04045  0.005655     6.661:  25%|██▌       | 10/40 [00:42<00:40,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2026       640   0.03706   0.04058  0.005595     6.658:  28%|██▊       | 11/40 [00:43<00:35,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1907       640   0.03694   0.04033  0.005568     6.627:  30%|███       | 12/40 [00:44<00:31,  1.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1850       640   0.03688   0.04002  0.005617     6.601:  32%|███▎      | 13/40 [00:45<00:28,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1864       640   0.03676   0.03973  0.005628     6.569:  35%|███▌      | 14/40 [00:46<00:26,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1872       640   0.03668   0.03954  0.005674     6.551:  38%|███▊      | 15/40 [00:47<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2017       640   0.03657   0.03958  0.005681     6.546:  40%|████      | 16/40 [00:47<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1696       640   0.03653   0.03928  0.005656     6.517:  42%|████▎     | 17/40 [00:48<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1982       640   0.03641   0.03922  0.005682     6.505:  45%|████▌     | 18/40 [00:49<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1652       640   0.03638   0.03897  0.005699     6.484:  48%|████▊     | 19/40 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1969       640    0.0363   0.03887  0.005684     6.468:  50%|█████     | 20/40 [00:51<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2002       640   0.03631   0.03884  0.005691     6.467:  52%|█████▎    | 21/40 [00:52<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2166       640   0.03626   0.03887  0.005659     6.463:  55%|█████▌    | 22/40 [00:53<00:15,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2059       640    0.0362   0.03895  0.005647     6.464:  57%|█████▊    | 23/40 [00:54<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1663       640   0.03618   0.03877  0.005656     6.448:  60%|██████    | 24/40 [00:54<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1978       640   0.03611   0.03869  0.005649     6.436:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1860       640   0.03604   0.03855  0.005643     6.418:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.452      0.449       0.39      0.218
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.496      0.405       0.39      0.219
                   0        738       1052      0.492      0.563      0.534      0.253
                   1        738         44      0.404      0.114      0.149     0.0592
                   2        738       8622      0.615      0.739      0.745      0.479
                   3        738        151      0.344      0.351      0.366      0.287
                   4        738        467      0.453      0.596      0.535       0.39
                   5        738         70      0.262      0.371      0.234      0.115
                   6        738         65      0.299     0.0923      0.163     0.0634
                   7        738       1619      0.519       0.61      0.575      0.239
                   8        738       2845      0.568      0.611      0.596      0.306
                   9        738          2          1          0   0.000225   0.000225

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:06:57.971355796 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30943 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round001_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train' images and labels...9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:01<00:00, 8923.24it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 12:07:15.280814136 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 12:07:15.290899807 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2061       640   0.03962   0.05109  0.006092     7.744:   3%|▎         | 1/39 [00:33<21:30, 33.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2096       640    0.0392   0.05122  0.006262     7.735:   5%|▌         | 2/39 [00:35<09:00, 14.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1974       640   0.03893    0.0503  0.006232     7.637:   8%|▊         | 3/39 [00:36<05:03,  8.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2004       640    0.0389   0.04916  0.006058      7.53:  10%|█         | 4/39 [00:37<03:12,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2113       640   0.03858   0.04896  0.005886     7.474:  13%|█▎        | 5/39 [00:37<02:10,  3.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1782       640   0.03793   0.04803  0.005888     7.348:  15%|█▌        | 6/39 [00:38<01:33,  2.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1994       640   0.03772   0.04786  0.005958     7.323:  18%|█▊        | 7/39 [00:39<01:09,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1873       640   0.03741   0.04746  0.005897     7.261:  21%|██        | 8/39 [00:40<00:54,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2042       640   0.03734   0.04736  0.005821     7.242:  23%|██▎       | 9/39 [00:41<00:44,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1802       640   0.03709    0.0472  0.005814     7.208:  26%|██▌       | 10/39 [00:42<00:37,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1993       640   0.03706     0.047  0.005814      7.19:  28%|██▊       | 11/39 [00:43<00:32,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1880       640   0.03704   0.04667   0.00581     7.161:  31%|███       | 12/39 [00:44<00:29,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2059       640   0.03703   0.04649  0.005748     7.141:  33%|███▎      | 13/39 [00:44<00:26,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2123       640   0.03703   0.04656  0.005711     7.144:  36%|███▌      | 14/39 [00:45<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1955       640   0.03697   0.04644  0.005687     7.128:  38%|███▊      | 15/39 [00:46<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1905       640    0.0368   0.04614  0.005683      7.09:  41%|████      | 16/39 [00:47<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1487       640   0.03668   0.04584  0.005709     7.058:  44%|████▎     | 17/39 [00:48<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1933       640   0.03654   0.04571  0.005687     7.035:  46%|████▌     | 18/39 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1723       640    0.0365   0.04542  0.005662     7.007:  49%|████▊     | 19/39 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2087       640    0.0364   0.04548  0.005638     7.001:  51%|█████▏    | 20/39 [00:51<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1847       640   0.03628   0.04527  0.005617     6.973:  54%|█████▍    | 21/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1766       640    0.0362   0.04519  0.005607      6.96:  56%|█████▋    | 22/39 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1791       640    0.0361   0.04501  0.005594     6.936:  59%|█████▉    | 23/39 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1874       640   0.03603   0.04492  0.005581     6.922:  62%|██████▏   | 24/39 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1747       640   0.03594   0.04483  0.005563     6.907:  64%|██████▍   | 25/39 [00:55<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2013       640   0.03585   0.04477  0.005549     6.893:  67%|██████▋   | 26/39 [00:56<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.399      0.399      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.527      0.406        0.4      0.225
                   0        738       1052      0.619       0.53      0.545      0.256
                   1        738         44      0.479      0.159      0.166     0.0655
                   2        738       8622       0.62      0.742      0.752      0.482
                   3        738        151       0.34      0.364       0.37      0.294
                   4        738        467      0.461      0.587       0.54      0.392
                   5        738         70      0.269      0.371      0.261      0.135
                   6        738         65       0.35     0.0769      0.179     0.0669
                   7        738       1619      0.543      0.611       0.58      0.241
                   8        738       2845      0.587      0.618      0.603      0.315
                   9        738          2          1          0   0.000259   0.000233

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:09:13.971763876 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30944 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round001_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train' images and labels...9763 found, 1483 missing, 0 empty, 0 corrupted: 100%|██████████| 11246/11246 [00:01<00:00, 9617.91it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.261313639220615
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.cache' images and labels... 9763 found, 1483 missing, 0 empty, 0 corrupted: 100%|██████████| 11246/11246 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:09:31.958887449 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:09:31.985522592 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      1823       640   0.03895   0.04437  0.005301     7.089:   2%|▎         | 1/40 [00:33<21:42, 33.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1963       640   0.03872   0.04614  0.005328     7.215:   5%|▌         | 2/40 [00:34<09:12, 14.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1880       640    0.0391   0.04562   0.00529     7.201:   8%|▊         | 3/40 [00:35<05:12,  8.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2068       640   0.03887   0.04496  0.005393     7.138:  10%|█         | 4/40 [00:37<03:19,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2042       640   0.03856    0.0447  0.005415     7.094:  12%|█▎        | 5/40 [00:37<02:15,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1893       640   0.03848   0.04407  0.005561     7.049:  15%|█▌        | 6/40 [00:38<01:37,  2.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1921       640   0.03798   0.04361  0.005554     6.972:  18%|█▊        | 7/40 [00:39<01:13,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2009       640   0.03775   0.04357  0.005481     6.944:  20%|██        | 8/40 [00:40<00:57,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2080       640   0.03751   0.04366  0.005464     6.931:  22%|██▎       | 9/40 [00:41<00:46,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1704       640   0.03735   0.04327  0.005586     6.897:  25%|██▌       | 10/40 [00:42<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2025       640   0.03729   0.04316  0.005617     6.886:  28%|██▊       | 11/40 [00:43<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1687       640   0.03712   0.04273  0.005602     6.836:  30%|███       | 12/40 [00:44<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2028       640   0.03705   0.04261  0.005604     6.821:  32%|███▎      | 13/40 [00:45<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2011       640   0.03699   0.04247  0.005602     6.804:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1879       640   0.03692   0.04243  0.005658     6.801:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2014       640   0.03695   0.04225  0.005658     6.789:  40%|████      | 16/40 [00:47<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1656       640   0.03687   0.04187   0.00568     6.754:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2124       640   0.03682   0.04176  0.005665      6.74:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1755       640   0.03685   0.04151  0.005679     6.723:  48%|████▊     | 19/40 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2122       640   0.03678    0.0415  0.005651     6.714:  50%|█████     | 20/40 [00:51<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2030       640   0.03679   0.04139  0.005668     6.708:  52%|█████▎    | 21/40 [00:52<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1941       640   0.03678   0.04132  0.005664     6.701:  55%|█████▌    | 22/40 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1881       640   0.03671   0.04112  0.005664      6.68:  57%|█████▊    | 23/40 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2078       640   0.03669   0.04108  0.005665     6.675:  60%|██████    | 24/40 [00:54<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1937       640   0.03667   0.04094   0.00565     6.661:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1918       640   0.03661   0.04082  0.005629     6.645:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.485      0.424      0.389      0.216
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.469      0.427      0.386      0.217
                   0        738       1052      0.505      0.535      0.524      0.246
                   1        738         44      0.311      0.136      0.128     0.0556
                   2        738       8622      0.585      0.743      0.742       0.47
                   3        738        151      0.295      0.391      0.373      0.288
                   4        738        467      0.396      0.618      0.532      0.384
                   5        738         70      0.251      0.429      0.249       0.12
                   6        738         65      0.305      0.169      0.149      0.058
                   7        738       1619      0.501      0.631      0.577      0.238
                   8        738       2845       0.54      0.615      0.587      0.308
                   9        738          2          1          0   0.000194   0.000194

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:11:29.992487323 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30945 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round001_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client4_residential_day_stable_train' images and labels...9921 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:01<00:00, 9036.02it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.cache' images and labels... 9921 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:11:47.157326661 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:11:47.226477585 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2090       640   0.03885   0.05009  0.005952     7.592:   3%|▎         | 1/39 [00:34<22:09, 34.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2144       640   0.03871   0.05003  0.005966     7.576:   5%|▌         | 2/39 [00:36<09:17, 15.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1953       640   0.03861   0.04922  0.005828     7.493:   8%|▊         | 3/39 [00:37<05:12,  8.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2117       640   0.03846   0.04863  0.005948     7.444:  10%|█         | 4/39 [00:38<03:19,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2267       640   0.03822   0.04847  0.005805       7.4:  13%|█▎        | 5/39 [00:39<02:14,  3.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1698       640   0.03769   0.04688  0.005756     7.226:  15%|█▌        | 6/39 [00:40<01:36,  2.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2021       640   0.03764   0.04683  0.005806     7.223:  18%|█▊        | 7/39 [00:40<01:12,  2.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2155       640   0.03747   0.04652  0.005783     7.182:  21%|██        | 8/39 [00:41<00:56,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2153       640   0.03728   0.04661   0.00569     7.167:  23%|██▎       | 9/39 [00:42<00:46,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1848       640   0.03713   0.04638  0.005679     7.135:  26%|██▌       | 10/39 [00:43<00:39,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1852       640   0.03701   0.04588  0.005676     7.085:  28%|██▊       | 11/39 [00:44<00:34,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2037       640   0.03692    0.0456  0.005697     7.057:  31%|███       | 12/39 [00:45<00:30,  1.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2121       640   0.03695    0.0457  0.005636     7.063:  33%|███▎      | 13/39 [00:46<00:27,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1844       640   0.03681   0.04535  0.005588     7.019:  36%|███▌      | 14/39 [00:47<00:25,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1945       640   0.03675    0.0452  0.005592     7.003:  38%|███▊      | 15/39 [00:48<00:23,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2079       640    0.0367   0.04503  0.005616     6.988:  41%|████      | 16/39 [00:49<00:22,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2008       640   0.03668   0.04501  0.005637     6.986:  44%|████▎     | 17/39 [00:50<00:20,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1983       640   0.03657   0.04494  0.005605     6.969:  46%|████▌     | 18/39 [00:51<00:19,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1846       640   0.03647   0.04467  0.005546     6.935:  49%|████▊     | 19/39 [00:51<00:18,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2068       640   0.03638   0.04462  0.005539     6.923:  51%|█████▏    | 20/39 [00:52<00:17,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1890       640   0.03629    0.0445  0.005526     6.905:  54%|█████▍    | 21/39 [00:53<00:16,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2102       640   0.03626    0.0446  0.005516      6.91:  56%|█████▋    | 22/39 [00:54<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1913       640   0.03622   0.04452  0.005527     6.902:  59%|█████▉    | 23/39 [00:55<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2044       640   0.03614   0.04453  0.005512     6.895:  62%|██████▏   | 24/39 [00:56<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1974       640   0.03612   0.04444  0.005492     6.884:  64%|██████▍   | 25/39 [00:57<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2081       640   0.03608   0.04438   0.00551     6.877:  67%|██████▋   | 26/39 [00:58<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53       0.41      0.403      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.502       0.41      0.399      0.223
                   0        738       1052      0.523      0.543      0.536      0.255
                   1        738         44      0.405      0.136      0.156     0.0625
                   2        738       8622       0.65      0.732      0.749      0.479
                   3        738        151      0.369      0.384      0.382      0.292
                   4        738        467      0.456      0.593      0.548      0.396
                   5        738         70      0.239        0.4      0.255      0.128
                   6        738         65      0.248     0.0769      0.174     0.0623
                   7        738       1619      0.535      0.616      0.584      0.244
                   8        738       2845      0.594      0.614      0.604      0.314
                   9        738          2          1          0   0.000238   0.000214

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 12:13:48.271789677 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30946 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round001_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client5_residential_night_stable_train' images and labels...9764 found, 1484 missing, 0 empty, 0 corrupted: 100%|██████████| 11248/11248 [00:01<00:00, 8688.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.258915946582874
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.cache' images and labels... 9764 found, 1484 missing, 0 empty, 0 corrupted: 100%|██████████| 11248/11248 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 12:14:05.995681153 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 12:14:05.996154867 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2144       640   0.03917   0.04361  0.005932     7.097:   2%|▎         | 1/40 [00:32<21:25, 32.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1761       640   0.03858   0.04312  0.005865     7.006:   5%|▌         | 2/40 [00:34<09:04, 14.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1973       640   0.03846   0.04365  0.005621     7.019:   8%|▊         | 3/40 [00:35<05:08,  8.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1984       640   0.03815   0.04366  0.005413     6.978:  10%|█         | 4/40 [00:36<03:17,  5.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1953       640   0.03759   0.04357  0.005368     6.922:  12%|█▎        | 5/40 [00:37<02:14,  3.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1797       640   0.03748   0.04307  0.005386     6.875:  15%|█▌        | 6/40 [00:38<01:36,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2171       640   0.03751   0.04341  0.005439     6.909:  18%|█▊        | 7/40 [00:39<01:13,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2026       640   0.03748   0.04329  0.005463     6.899:  20%|██        | 8/40 [00:40<00:57,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1993       640   0.03722   0.04307  0.005439     6.858:  22%|██▎       | 9/40 [00:41<00:47,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1917       640   0.03697   0.04294  0.005473     6.831:  25%|██▌       | 10/40 [00:42<00:39,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2020       640   0.03692    0.0426  0.005456     6.798:  28%|██▊       | 11/40 [00:42<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1814       640   0.03685    0.0424  0.005452     6.776:  30%|███       | 12/40 [00:43<00:30,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1950       640   0.03675   0.04226  0.005449     6.757:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2051       640   0.03669   0.04225   0.00544      6.75:  35%|███▌      | 14/40 [00:45<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1935       640   0.03655    0.0421  0.005446     6.728:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1866       640    0.0365   0.04193  0.005454      6.71:  40%|████      | 16/40 [00:47<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1835       640   0.03647   0.04171  0.005442      6.69:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2002       640   0.03648   0.04162  0.005471     6.686:  45%|████▌     | 18/40 [00:49<00:19,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1711       640   0.03642   0.04126  0.005481     6.653:  48%|████▊     | 19/40 [00:49<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2085       640    0.0364   0.04114  0.005488     6.642:  50%|█████     | 20/40 [00:50<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1919       640   0.03644   0.04091  0.005523      6.63:  52%|█████▎    | 21/40 [00:51<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1959       640   0.03641   0.04078  0.005495     6.615:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1778       640   0.03637   0.04065  0.005496     6.601:  57%|█████▊    | 23/40 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1973       640    0.0363   0.04051  0.005529     6.587:  60%|██████    | 24/40 [00:54<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2052       640   0.03626   0.04041  0.005527     6.576:  62%|██████▎   | 25/40 [00:55<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1924       640   0.03624   0.04025  0.005518      6.56:  65%|██████▌   | 26/40 [00:56<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.48      0.423      0.392      0.218
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.497      0.407       0.39      0.218
                   0        738       1052      0.504      0.541      0.527      0.249
                   1        738         44      0.443      0.136      0.143     0.0556
                   2        738       8622      0.611      0.736      0.742      0.473
                   3        738        151      0.333      0.351      0.377      0.294
                   4        738        467      0.439      0.602      0.542      0.391
                   5        738         70      0.248      0.386      0.246      0.112
                   6        738         65      0.284     0.0923      0.146     0.0592
                   7        738       1619      0.535      0.619      0.584       0.24
                   8        738       2845       0.57      0.611      0.596      0.309
                   9        738          2          1          0   0.000192   0.000154

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:16:03.942386051 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30947 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round001_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round001_dqa_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train' images and labels...:   0%|          | 0/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 11067.12it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:16:20.083756646 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:16:20.140887389 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03851   0.04572   0.00573     7.197:   3%|▎         | 1/31 [00:33<16:31, 33.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2744       640   0.03902   0.04672  0.005945     7.334:   6%|▋         | 2/31 [00:33<06:47, 14.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03855   0.04577  0.005901     7.218:  10%|▉         | 3/31 [00:34<03:43,  7.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03788    0.0441  0.005696     7.014:  13%|█▎        | 4/31 [00:35<02:18,  5.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.03756   0.04424  0.005707         7:  16%|█▌        | 5/31 [00:35<01:30,  3.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03747   0.04418  0.005763     6.993:  19%|█▉        | 6/31 [00:36<01:02,  2.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.03742   0.04383  0.005827     6.966:  23%|██▎       | 7/31 [00:37<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.03724    0.0439  0.005859      6.96:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.03716    0.0438  0.005766     6.938:  29%|██▉       | 9/31 [00:38<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.03701   0.04388  0.005737      6.93:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.03688   0.04387  0.005743     6.919:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.03668   0.04355  0.005716     6.876:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.03657   0.04358  0.005656     6.864:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640    0.0365   0.04332  0.005612     6.835:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.03646   0.04321  0.005638     6.824:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.03638   0.04302  0.005616     6.802:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.03635   0.04303  0.005567     6.796:  55%|█████▍    | 17/31 [00:42<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03633   0.04304  0.005519     6.791:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640    0.0362   0.04286  0.005472     6.762:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03613   0.04305  0.005471     6.772:  65%|██████▍   | 20/31 [00:44<00:06,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03611   0.04303  0.005479     6.769:  68%|██████▊   | 21/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03605   0.04311  0.005436     6.768:  71%|███████   | 22/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03599    0.0431   0.00542     6.761:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03596   0.04314  0.005394     6.759:  77%|███████▋  | 24/31 [00:46<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03591   0.04304  0.005392     6.748:  81%|████████  | 25/31 [00:47<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03592   0.04304  0.005381     6.747:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.462      0.453        0.4      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.471      0.439      0.399      0.224
                   0        738       1052      0.458      0.575      0.543      0.254
                   1        738         44      0.334      0.159      0.152     0.0581
                   2        738       8622      0.577      0.759      0.751      0.484
                   3        738        151      0.325      0.391      0.371      0.286
                   4        738        467      0.446      0.595      0.547      0.399
                   5        738         70       0.25      0.443      0.274      0.132
                   6        738         65      0.292      0.184       0.16     0.0626
                   7        738       1619       0.51      0.629      0.579       0.24
                   8        738       2845       0.52      0.652      0.613       0.32
                   9        738          2          1          0   0.000306   0.000275

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 12:17:59.891107759 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

=== round002: DQA scene-daynight round ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round002 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round002 client0_highway_day: pseudo scan 250/1500 images, kept 2367 boxes
round002 client0_highway_day: pseudo scan 500/1500 images, kept 4803 boxes
round002 client0_highway_day: pseudo scan 750/1500 images, kept 7153 boxes
round002 client0_highway_day: pseudo scan 1000/1500 images, kept 9513 boxes
round002 client0_highway_day: pseudo scan 1250/1500 images, kept 11838 boxes
round002 client0_highway_day: pseudo scan 1500/1500 images, kept 14204 boxes
{
  "round": "round002",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1492,
  "pseudo_boxes_kept": 11061,
  "boxes_per_kept_image": 7.413538873994638,
  "mean_conf": 0.7782305761607277,
  "mean_stability": 0.9526066582970912,
  "mean_score": 0.7444941972457755,
  "class_counts": {
    "0": 152,
    "2": 6392,
    "3": 84,
    "4": 490,
    "5": 6,
    "7": 569,
    "8": 3368
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_client0_highway_day_stable_boxes.csv"
}
round002 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round002 client1_highway_night: pseudo scan 250/1500 images, kept 1779 boxes
round002 client1_highway_night: pseudo scan 500/1500 images, kept 3663 boxes
round002 client1_highway_night: pseudo scan 750/1500 images, kept 5526 boxes
round002 client1_highway_night: pseudo scan 1000/1500 images, kept 7330 boxes
round002 client1_highway_night: pseudo scan 1250/1500 images, kept 9158 boxes
round002 client1_highway_night: pseudo scan 1500/1500 images, kept 10971 boxes
{
  "round": "round002",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 8986,
  "boxes_per_kept_image": 6.088075880758808,
  "mean_conf": 0.6826010422924964,
  "mean_stability": 0.9336230146932676,
  "mean_score": 0.6412868338041081,
  "class_counts": {
    "0": 60,
    "2": 4937,
    "3": 26,
    "4": 143,
    "5": 6,
    "7": 578,
    "8": 3236
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_client1_highway_night_stable_boxes.csv"
}
round002 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round002 client2_citystreet_day: pseudo scan 250/1500 images, kept 2698 boxes
round002 client2_citystreet_day: pseudo scan 500/1500 images, kept 5417 boxes
round002 client2_citystreet_day: pseudo scan 750/1500 images, kept 8150 boxes
round002 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10911 boxes
round002 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13630 boxes
round002 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16285 boxes
{
  "round": "round002",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13703,
  "boxes_per_kept_image": 9.15975935828877,
  "mean_conf": 0.7725580963615709,
  "mean_stability": 0.9502725896109441,
  "mean_score": 0.7374440576962856,
  "class_counts": {
    "0": 1403,
    "2": 7329,
    "3": 150,
    "4": 563,
    "5": 49,
    "7": 1556,
    "8": 2653
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_client2_citystreet_day_stable_boxes.csv"
}
round002 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round002 client3_citystreet_night: pseudo scan 250/1500 images, kept 2442 boxes
round002 client3_citystreet_night: pseudo scan 500/1500 images, kept 4849 boxes
round002 client3_citystreet_night: pseudo scan 750/1500 images, kept 7232 boxes
round002 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9564 boxes
round002 client3_citystreet_night: pseudo scan 1250/1500 images, kept 12040 boxes
round002 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14446 boxes
{
  "round": "round002",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1480,
  "pseudo_boxes_kept": 12149,
  "boxes_per_kept_image": 8.208783783783783,
  "mean_conf": 0.6876841051920578,
  "mean_stability": 0.9325806667740153,
  "mean_score": 0.6453785006247917,
  "class_counts": {
    "0": 525,
    "2": 6501,
    "3": 54,
    "4": 152,
    "5": 23,
    "7": 1954,
    "8": 2940
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_client3_citystreet_night_stable_boxes.csv"
}
round002 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round002 client4_residential_day: pseudo scan 250/1500 images, kept 2574 boxes
round002 client4_residential_day: pseudo scan 500/1500 images, kept 5165 boxes
round002 client4_residential_day: pseudo scan 750/1500 images, kept 7722 boxes
round002 client4_residential_day: pseudo scan 1000/1500 images, kept 10192 boxes
round002 client4_residential_day: pseudo scan 1250/1500 images, kept 12725 boxes
round002 client4_residential_day: pseudo scan 1500/1500 images, kept 15212 boxes
{
  "round": "round002",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9893,
  "boxes_per_kept_image": 6.63514419852448,
  "mean_conf": 0.812038309416515,
  "mean_stability": 0.958903028294301,
  "mean_score": 0.7818435179283876,
  "class_counts": {
    "0": 368,
    "2": 6846,
    "3": 39,
    "4": 293,
    "5": 28,
    "7": 537,
    "8": 1782
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_client4_residential_day_stable_boxes.csv"
}
round002 client5_residential_night: pseudo scan 1/1500 images, kept 11 boxes
round002 client5_residential_night: pseudo scan 250/1500 images, kept 2430 boxes
round002 client5_residential_night: pseudo scan 500/1500 images, kept 4796 boxes
round002 client5_residential_night: pseudo scan 750/1500 images, kept 7165 boxes
round002 client5_residential_night: pseudo scan 1000/1500 images, kept 9601 boxes
round002 client5_residential_night: pseudo scan 1250/1500 images, kept 12029 boxes
round002 client5_residential_night: pseudo scan 1500/1500 images, kept 14483 boxes
{
  "round": "round002",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 9075,
  "boxes_per_kept_image": 6.127616475354491,
  "mean_conf": 0.7630851506300209,
  "mean_stability": 0.9453893730725795,
  "mean_score": 0.7242095520877337,
  "class_counts": {
    "0": 125,
    "2": 6518,
    "3": 26,
    "4": 94,
    "5": 14,
    "7": 627,
    "8": 1671
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round002_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30948 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round002_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client0_highway_day_stable_train' images and labels...10002 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 11254/11254 [00:01<00:00, 10557.09it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.cache' images and labels... 10002 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 11254/11254 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 12:20:17.404942607 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 12:20:17.431885774 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2076       640   0.03639   0.04428  0.005217     6.871:   3%|▎         | 1/39 [00:33<21:17, 33.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1843       640    0.0355   0.04196   0.00488     6.587:   5%|▌         | 2/39 [00:34<08:56, 14.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1952       640   0.03561   0.04251   0.00503     6.652:   8%|▊         | 3/39 [00:35<05:02,  8.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1955       640   0.03577   0.04308  0.005176     6.722:  10%|█         | 4/39 [00:36<03:12,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1961       640   0.03542   0.04316  0.005107     6.695:  13%|█▎        | 5/39 [00:37<02:10,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1579       640   0.03495   0.04218  0.005006     6.571:  15%|█▌        | 6/39 [00:38<01:34,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2046       640   0.03495   0.04203  0.005012     6.559:  18%|█▊        | 7/39 [00:39<01:10,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2018       640   0.03501     0.042  0.005069     6.566:  21%|██        | 8/39 [00:40<00:55,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03514   0.04225  0.005111       6.6:  23%|██▎       | 9/39 [00:41<00:45,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2199       640   0.03524   0.04268  0.005114     6.643:  26%|██▌       | 10/39 [00:42<00:38,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640   0.03521   0.04254  0.005128      6.63:  28%|██▊       | 11/39 [00:43<00:33,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2077       640   0.03512   0.04261  0.005213     6.636:  31%|███       | 12/39 [00:44<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1786       640   0.03495   0.04237  0.005219     6.603:  33%|███▎      | 13/39 [00:44<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2260       640   0.03495   0.04263  0.005177     6.621:  36%|███▌      | 14/39 [00:45<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640   0.03496   0.04261  0.005157     6.618:  38%|███▊      | 15/39 [00:46<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1971       640   0.03496   0.04254   0.00513      6.61:  41%|████      | 16/39 [00:47<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1887       640   0.03497   0.04248  0.005164     6.609:  44%|████▎     | 17/39 [00:48<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1927       640   0.03497   0.04231  0.005177     6.597:  46%|████▌     | 18/39 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1758       640   0.03488   0.04213  0.005164     6.573:  49%|████▊     | 19/39 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2261       640   0.03486   0.04225  0.005198     6.585:  51%|█████▏    | 20/39 [00:51<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1874       640   0.03481   0.04228  0.005198     6.583:  54%|█████▍    | 21/39 [00:51<00:15,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1896       640    0.0348   0.04219  0.005193     6.575:  56%|█████▋    | 22/39 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1981       640   0.03477   0.04208  0.005164     6.561:  59%|█████▉    | 23/39 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1979       640   0.03477   0.04209  0.005159     6.562:  62%|██████▏   | 24/39 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2120       640   0.03475   0.04206  0.005156     6.558:  64%|██████▍   | 25/39 [00:55<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640   0.03475   0.04199  0.005151     6.551:  67%|██████▋   | 26/39 [00:56<00:11,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.481      0.451      0.405      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.467      0.455      0.403      0.227
                   0        738       1052      0.421      0.587      0.541       0.26
                   1        738         44      0.298      0.205      0.155     0.0604
                   2        738       8622      0.601      0.753      0.751      0.484
                   3        738        151      0.317      0.424      0.397      0.308
                   4        738        467       0.43      0.617      0.555      0.403
                   5        738         70       0.24       0.45      0.266      0.142
                   6        738         65      0.285      0.246      0.158     0.0568
                   7        738       1619      0.506      0.646      0.596      0.245
                   8        738       2845      0.571      0.624      0.607      0.315
                   9        738          2          1          0   0.000281   0.000252

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:22:12.897129620 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30949 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round002_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client1_highway_night_stable_train' images and labels...9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:01<00:00, 10707.55it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29496062992126
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.cache' images and labels... 9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 12:22:29.170023759 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 12:22:29.180913008 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1990       640   0.03648    0.0438  0.005405     6.855:   2%|▎         | 1/40 [00:32<21:22, 32.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1813       640   0.03599   0.04095  0.005369     6.585:   5%|▌         | 2/40 [00:34<09:04, 14.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1804       640   0.03513   0.03984  0.005066     6.402:   8%|▊         | 3/40 [00:35<05:08,  8.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2114       640   0.03486   0.04024  0.004998     6.409:  10%|█         | 4/40 [00:36<03:17,  5.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03495    0.0402  0.005041     6.415:  12%|█▎        | 5/40 [00:37<02:14,  3.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1857       640   0.03478   0.03963  0.005089      6.36:  15%|█▌        | 6/40 [00:38<01:36,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03476   0.03909  0.005098     6.316:  18%|█▊        | 7/40 [00:39<01:12,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1964       640   0.03461   0.03892  0.005058     6.287:  20%|██        | 8/40 [00:40<00:57,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1837       640   0.03463   0.03873  0.005037     6.272:  22%|██▎       | 9/40 [00:41<00:46,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1838       640   0.03465   0.03863  0.005054     6.266:  25%|██▌       | 10/40 [00:41<00:39,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1926       640   0.03467   0.03855  0.005024     6.259:  28%|██▊       | 11/40 [00:42<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640   0.03461   0.03841  0.004986     6.241:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1910       640   0.03468   0.03824  0.005049     6.238:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1828       640   0.03468    0.0381  0.005067     6.228:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1827       640   0.03471   0.03796   0.00511     6.223:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1842       640   0.03467   0.03787  0.005108     6.212:  40%|████      | 16/40 [00:47<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1999       640   0.03472   0.03777  0.005081     6.206:  42%|████▎     | 17/40 [00:48<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1846       640   0.03467   0.03778  0.005118     6.205:  45%|████▌     | 18/40 [00:49<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1617       640   0.03466   0.03754  0.005129     6.187:  48%|████▊     | 19/40 [00:49<00:19,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1958       640   0.03465   0.03747  0.005118     6.179:  50%|█████     | 20/40 [00:50<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2008       640   0.03469   0.03745  0.005108     6.179:  52%|█████▎    | 21/40 [00:51<00:17,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2150       640   0.03468   0.03748  0.005084      6.18:  55%|█████▌    | 22/40 [00:52<00:16,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2056       640   0.03466   0.03752  0.005076     6.181:  57%|█████▊    | 23/40 [00:53<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1606       640   0.03464   0.03736  0.005106     6.169:  60%|██████    | 24/40 [00:54<00:14,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1881       640   0.03459   0.03729  0.005117      6.16:  62%|██████▎   | 25/40 [00:55<00:13,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1917       640   0.03459    0.0372   0.00512     6.153:  65%|██████▌   | 26/40 [00:56<00:12,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.465      0.452      0.401      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.545       0.39        0.4      0.226
                   0        738       1052      0.547      0.547      0.541      0.257
                   1        738         44       0.57     0.0909      0.163     0.0618
                   2        738       8622      0.667      0.723      0.747      0.481
                   3        738        151      0.441      0.351        0.4      0.307
                   4        738        467      0.476      0.585      0.544      0.398
                   5        738         70      0.274       0.35      0.238      0.128
                   6        738         65      0.268     0.0615      0.171     0.0697
                   7        738       1619      0.562      0.606       0.59      0.243
                   8        738       2845      0.645      0.588      0.605       0.31
                   9        738          2          1          0   0.000239   0.000215

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:24:28.796300872 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30950 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round002_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train' images and labels...9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:01<00:00, 10995.11it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:24:45.705574381 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:24:45.778531400 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2066       640    0.0361   0.05077  0.005331     7.376:   3%|▎         | 1/39 [00:33<20:59, 33.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2187       640   0.03561   0.05046   0.00561     7.334:   5%|▌         | 2/39 [00:34<08:52, 14.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1974       640   0.03527   0.04973  0.005632      7.25:   8%|▊         | 3/39 [00:35<05:00,  8.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640   0.03538   0.04893  0.005532     7.188:  10%|█         | 4/39 [00:36<03:12,  5.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2145       640   0.03531    0.0484  0.005414      7.13:  13%|█▎        | 5/39 [00:37<02:10,  3.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1780       640    0.0349   0.04739  0.005365     7.013:  15%|█▌        | 6/39 [00:38<01:33,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1960       640   0.03498   0.04724  0.005443     7.013:  18%|█▊        | 7/39 [00:39<01:10,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1897       640   0.03485   0.04685  0.005386     6.967:  21%|██        | 8/39 [00:40<00:55,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2025       640   0.03498   0.04688  0.005323     6.974:  23%|██▎       | 9/39 [00:41<00:45,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1808       640   0.03481    0.0466  0.005305     6.937:  26%|██▌       | 10/39 [00:42<00:38,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1991       640   0.03483   0.04651  0.005309     6.932:  28%|██▊       | 11/39 [00:42<00:33,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1792       640   0.03487   0.04604  0.005319     6.899:  31%|███       | 12/39 [00:43<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03494    0.0459  0.005277     6.889:  33%|███▎      | 13/39 [00:44<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03504   0.04594  0.005247     6.898:  36%|███▌      | 14/39 [00:45<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1930       640   0.03504   0.04581  0.005224     6.886:  38%|███▊      | 15/39 [00:46<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1894       640   0.03493   0.04551  0.005219     6.853:  41%|████      | 16/39 [00:47<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1504       640   0.03485   0.04527  0.005246     6.829:  44%|████▎     | 17/39 [00:48<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1920       640   0.03477   0.04519  0.005233     6.815:  46%|████▌     | 18/39 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1718       640   0.03478   0.04489  0.005208      6.79:  49%|████▊     | 19/39 [00:49<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03472   0.04489  0.005191     6.784:  51%|█████▏    | 20/39 [00:50<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1849       640   0.03465   0.04472  0.005174     6.763:  54%|█████▍    | 21/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1707       640    0.0346   0.04463  0.005162     6.752:  56%|█████▋    | 22/39 [00:52<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03453   0.04452  0.005161     6.737:  59%|█████▉    | 23/39 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1900       640    0.0345   0.04445  0.005154     6.728:  62%|██████▏   | 24/39 [00:54<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1848       640   0.03445   0.04434  0.005149     6.716:  64%|██████▍   | 25/39 [00:55<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640   0.03439   0.04432  0.005137     6.708:  67%|██████▋   | 26/39 [00:56<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.445      0.488      0.406      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.531      0.399      0.406      0.229
                   0        738       1052      0.642      0.516      0.544      0.257
                   1        738         44      0.381      0.114      0.169     0.0731
                   2        738       8622      0.644      0.742      0.756      0.485
                   3        738        151      0.381      0.383      0.399      0.307
                   4        738        467       0.48      0.589       0.55        0.4
                   5        738         70      0.287      0.357      0.261      0.133
                   6        738         65      0.312     0.0769      0.183     0.0715
                   7        738       1619      0.567      0.608      0.588      0.245
                   8        738       2845      0.618      0.602      0.605      0.319
                   9        738          2          1          0   0.000268   0.000241

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:26:43.147835990 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30951 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round002_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train' images and labels...9763 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11242/11242 [00:01<00:00, 10286.18it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.cache' images and labels... 9763 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11242/11242 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:27:01.483270032 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:27:01.488494445 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1819       640   0.03577   0.04476  0.005092      6.85:   2%|▎         | 1/40 [00:34<22:07, 34.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1854       640   0.03615   0.04563   0.00524     6.961:   5%|▌         | 2/40 [00:35<09:18, 14.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1942       640   0.03557   0.04475  0.005425      6.86:   8%|▊         | 3/40 [00:36<05:14,  8.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1921       640   0.03529   0.04393  0.005176     6.751:  10%|█         | 4/40 [00:37<03:21,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1799       640   0.03503   0.04308  0.005077     6.655:  12%|█▎        | 5/40 [00:38<02:16,  3.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1818       640   0.03509   0.04255  0.004969     6.608:  15%|█▌        | 6/40 [00:39<01:37,  2.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1927       640   0.03508   0.04203  0.004918     6.562:  18%|█▊        | 7/40 [00:40<01:13,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1861       640   0.03501   0.04174  0.004959     6.537:  20%|██        | 8/40 [00:40<00:57,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03488   0.04201  0.004914     6.545:  22%|██▎       | 9/40 [00:41<00:46,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1974       640   0.03492   0.04192  0.004958     6.544:  25%|██▌       | 10/40 [00:42<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1981       640   0.03488   0.04188  0.005017     6.542:  28%|██▊       | 11/40 [00:43<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1781       640   0.03482   0.04162  0.004994     6.515:  30%|███       | 12/40 [00:44<00:30,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2118       640   0.03484   0.04162  0.005022     6.519:  32%|███▎      | 13/40 [00:45<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2183       640   0.03486   0.04175  0.005028     6.531:  35%|███▌      | 14/40 [00:46<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1949       640   0.03484   0.04162  0.005035      6.52:  38%|███▊      | 15/40 [00:47<00:24,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1679       640   0.03484   0.04121  0.004994     6.483:  40%|████      | 16/40 [00:48<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1455       640   0.03471   0.04069   0.00502     6.433:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2058       640   0.03478   0.04066  0.005055      6.44:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1657       640   0.03479   0.04031  0.005059     6.413:  48%|████▊     | 19/40 [00:50<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1969       640   0.03474   0.04023  0.005073     6.404:  50%|█████     | 20/40 [00:51<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1945       640   0.03475   0.04011  0.005058     6.393:  52%|█████▎    | 21/40 [00:52<00:16,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1910       640   0.03476   0.04001  0.005038     6.384:  55%|█████▌    | 22/40 [00:53<00:15,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2200       640   0.03481   0.04008  0.005047     6.395:  57%|█████▊    | 23/40 [00:54<00:14,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2143       640   0.03483   0.04008  0.005059     6.398:  60%|██████    | 24/40 [00:55<00:13,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1799       640   0.03482   0.03993  0.005035     6.382:  62%|██████▎   | 25/40 [00:55<00:13,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2092       640   0.03479   0.03982  0.005048     6.373:  65%|██████▌   | 26/40 [00:56<00:12,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.472      0.435      0.394      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]

                 all        738      14937      0.554      0.382      0.392      0.222
                   0        738       1052      0.582      0.513      0.518      0.247
                   1        738         44      0.495     0.0682      0.147     0.0675
                   2        738       8622      0.661      0.718      0.741      0.473
                   3        738        151      0.468      0.331      0.387      0.299
                   4        738        467      0.478       0.58      0.544      0.396
                   5        738         70      0.305      0.383      0.244      0.122
                   6        738         65      0.327     0.0615      0.159     0.0642
                   7        738       1619      0.576      0.587      0.578      0.242
                   8        738       2845      0.646      0.582      0.601      0.313
                   9        738          2          1          0   0.000165   0.000132

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 12:29:01.164703833 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30952 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round002_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client4_residential_day_stable_train' images and labels...9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:00<00:00, 11670.99it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.cache' images and labels... 9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 12:29:18.095835776 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 12:29:18.099905099 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2084       640   0.03491   0.04992   0.00457     7.152:   3%|▎         | 1/39 [00:32<20:17, 32.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2054       640   0.03536   0.04981  0.005364     7.243:   5%|▌         | 2/39 [00:33<08:32, 13.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640   0.03475   0.04823  0.005294     7.062:   8%|▊         | 3/39 [00:34<04:49,  8.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1904       640    0.0349   0.04748  0.005405     7.023:  10%|█         | 4/39 [00:35<03:05,  5.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1942       640   0.03465   0.04636  0.005348     6.909:  13%|█▎        | 5/39 [00:36<02:06,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1735       640   0.03473   0.04509  0.005434      6.82:  15%|█▌        | 6/39 [00:37<01:31,  2.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1985       640   0.03485   0.04483  0.005444      6.81:  18%|█▊        | 7/39 [00:38<01:09,  2.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1947       640   0.03491   0.04458  0.005374     6.789:  21%|██        | 8/39 [00:39<00:54,  1.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2072       640   0.03483   0.04459  0.005425     6.787:  23%|██▎       | 9/39 [00:39<00:44,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03491   0.04458  0.005392     6.791:  26%|██▌       | 10/39 [00:40<00:37,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2139       640   0.03489   0.04453  0.005381     6.784:  28%|██▊       | 11/39 [00:41<00:32,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2120       640   0.03487   0.04445  0.005368     6.775:  31%|███       | 12/39 [00:42<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640   0.03495   0.04454  0.005343     6.787:  33%|███▎      | 13/39 [00:43<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2027       640   0.03503   0.04448  0.005334     6.788:  36%|███▌      | 14/39 [00:44<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1824       640   0.03508   0.04421  0.005343     6.771:  38%|███▊      | 15/39 [00:45<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1768       640   0.03507   0.04399  0.005342     6.752:  41%|████      | 16/39 [00:46<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1747       640   0.03494   0.04379  0.005311     6.723:  44%|████▎     | 17/39 [00:47<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2019       640   0.03489   0.04378  0.005275     6.715:  46%|████▌     | 18/39 [00:47<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1602       640   0.03482   0.04348  0.005267     6.686:  49%|████▊     | 19/39 [00:48<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2209       640   0.03483    0.0435  0.005259     6.687:  51%|█████▏    | 20/39 [00:49<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1896       640   0.03482   0.04345  0.005243     6.681:  54%|█████▍    | 21/39 [00:50<00:16,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1996       640    0.0348   0.04345  0.005244      6.68:  56%|█████▋    | 22/39 [00:51<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2001       640   0.03481   0.04347  0.005264     6.684:  59%|█████▉    | 23/39 [00:52<00:14,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03479   0.04339  0.005258     6.675:  62%|██████▏   | 24/39 [00:53<00:13,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2030       640   0.03478   0.04338  0.005258     6.674:  64%|██████▍   | 25/39 [00:54<00:12,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1772       640   0.03478   0.04319  0.005245     6.656:  67%|██████▋   | 26/39 [00:55<00:11,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.468      0.466      0.408      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.454       0.47      0.407      0.228
                   0        738       1052      0.427      0.583      0.541      0.257
                   1        738         44      0.276      0.227      0.163     0.0637
                   2        738       8622      0.585       0.76      0.753      0.482
                   3        738        151      0.284      0.464       0.41      0.317
                   4        738        467      0.397      0.651      0.558      0.405
                   5        738         70      0.258      0.471      0.285      0.131
                   6        738         65      0.297      0.262       0.17     0.0602
                   7        738       1619      0.484      0.645      0.587      0.246
                   8        738       2845      0.528      0.641      0.605      0.318
                   9        738          2          1          0   0.000255   0.000255

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:31:16.809460180 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30953 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round002_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client5_residential_night_stable_train' images and labels...9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:01<00:00, 10181.32it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.cache' images and labels... 9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:31:34.384098635 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:31:34.403008984 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2028       640   0.03628   0.04526  0.005062     6.928:   2%|▎         | 1/40 [00:33<21:30, 33.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1983       640   0.03611   0.04539  0.005259     6.941:   5%|▌         | 2/40 [00:34<09:06, 14.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2058       640   0.03563    0.0452  0.005069     6.872:   8%|▊         | 3/40 [00:35<05:08,  8.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2174       640   0.03543   0.04502  0.005076     6.842:  10%|█         | 4/40 [00:36<03:16,  5.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1883       640   0.03525   0.04472   0.00502     6.799:  12%|█▎        | 5/40 [00:37<02:13,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03534   0.04409  0.004987     6.754:  15%|█▌        | 6/40 [00:38<01:36,  2.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1702       640   0.03507    0.0432   0.00502     6.664:  18%|█▊        | 7/40 [00:39<01:12,  2.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2052       640   0.03513   0.04292  0.004954      6.64:  20%|██        | 8/40 [00:40<00:57,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1793       640     0.035   0.04245  0.004928      6.59:  22%|██▎       | 9/40 [00:41<00:46,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1823       640   0.03513   0.04214  0.005034     6.584:  25%|██▌       | 10/40 [00:41<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2374       640   0.03521   0.04224  0.005072     6.602:  28%|██▊       | 11/40 [00:42<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1790       640   0.03503   0.04173  0.005071     6.546:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1871       640   0.03492   0.04136  0.005059     6.507:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2073       640   0.03497   0.04136  0.005133     6.517:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1989       640     0.035   0.04115  0.005111     6.501:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1764       640   0.03494   0.04077  0.005087     6.464:  40%|████      | 16/40 [00:47<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03492   0.04066  0.005123     6.456:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1986       640   0.03496   0.04048  0.005181      6.45:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1692       640     0.035   0.04011  0.005164     6.421:  48%|████▊     | 19/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2135       640   0.03506    0.0401  0.005183     6.427:  50%|█████     | 20/40 [00:50<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1985       640   0.03507    0.0399  0.005187     6.413:  52%|█████▎    | 21/40 [00:51<00:17,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1788       640   0.03505   0.03967  0.005188     6.393:  55%|█████▌    | 22/40 [00:52<00:16,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2131       640   0.03505   0.03962  0.005204      6.39:  57%|█████▊    | 23/40 [00:53<00:15,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1939       640   0.03504   0.03947  0.005204     6.377:  60%|██████    | 24/40 [00:54<00:14,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1889       640   0.03504   0.03928  0.005186      6.36:  62%|██████▎   | 25/40 [00:55<00:13,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1705       640   0.03502   0.03906  0.005203     6.342:  65%|██████▌   | 26/40 [00:56<00:12,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.531      0.404        0.4      0.224
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.02it/s]

                 all        738      14937      0.514      0.408      0.397      0.224
                   0        738       1052      0.514      0.542      0.524      0.253
                   1        738         44      0.433      0.136      0.153     0.0588
                   2        738       8622      0.628      0.733      0.744      0.477
                   3        738        151      0.405      0.391      0.397      0.311
                   4        738        467      0.469      0.597      0.552        0.4
                   5        738         70      0.267      0.371      0.247      0.121
                   6        738         65      0.274     0.0923      0.165     0.0645
                   7        738       1619      0.549       0.61      0.588      0.244
                   8        738       2845      0.597      0.607      0.601      0.315
                   9        738          2          1          0   0.000179   0.000143

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 12:33:34.994292443 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30954 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round002_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round002_dqa_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509

self imgsz: 640

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:33:52.472259540 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:33:52.540106437 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03482   0.04347  0.005217      6.68:   3%|▎         | 1/31 [00:33<16:58, 33.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03547   0.04453  0.005424     6.834:   6%|▋         | 2/31 [00:34<06:59, 14.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03487   0.04336  0.005307     6.683:  10%|▉         | 3/31 [00:35<03:50,  8.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03429   0.04164  0.005066      6.48:  13%|█▎        | 4/31 [00:36<02:22,  5.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03426   0.04182   0.00509     6.494:  16%|█▌        | 5/31 [00:36<01:33,  3.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03444   0.04178  0.005159     6.511:  19%|█▉        | 6/31 [00:37<01:04,  2.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03455    0.0415  0.005227     6.502:  23%|██▎       | 7/31 [00:38<00:45,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03447   0.04159  0.005258     6.506:  26%|██▌       | 8/31 [00:38<00:34,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640    0.0345   0.04152  0.005165     6.495:  29%|██▉       | 9/31 [00:39<00:26,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03447   0.04163  0.005145       6.5:  32%|███▏      | 10/31 [00:39<00:21,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03443   0.04167  0.005163     6.501:  35%|███▌      | 11/31 [00:40<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03433   0.04139  0.005149     6.469:  39%|███▊      | 12/31 [00:41<00:15,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0343   0.04144  0.005098     6.467:  42%|████▏     | 13/31 [00:41<00:13,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640    0.0343   0.04124  0.005061     6.448:  45%|████▌     | 14/31 [00:42<00:11,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03433   0.04115  0.005098     6.446:  48%|████▊     | 15/31 [00:42<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03432   0.04101  0.005084     6.433:  52%|█████▏    | 16/31 [00:43<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03435   0.04105  0.005044     6.435:  55%|█████▍    | 17/31 [00:43<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03438   0.04109  0.005001     6.438:  58%|█████▊    | 18/31 [00:44<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03431   0.04095  0.004964     6.418:  61%|██████▏   | 19/31 [00:45<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640    0.0343   0.04116  0.004968     6.434:  65%|██████▍   | 20/31 [00:45<00:06,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03432   0.04119  0.004984     6.439:  68%|██████▊   | 21/31 [00:46<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03431   0.04129   0.00495     6.444:  71%|███████   | 22/31 [00:46<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03429   0.04132  0.004941     6.444:  74%|███████▍  | 23/31 [00:47<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640    0.0343   0.04139  0.004923     6.448:  77%|███████▋  | 24/31 [00:48<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03429   0.04132  0.004931     6.444:  81%|████████  | 25/31 [00:48<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03434   0.04135  0.004928     6.449:  84%|████████▍ | 26/31 [00:49<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.487      0.446      0.408      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.459      0.465      0.406      0.228
                   0        738       1052      0.446       0.58      0.542      0.257
                   1        738         44      0.268      0.205      0.165     0.0598
                   2        738       8622      0.566      0.766      0.754      0.487
                   3        738        151      0.309      0.444      0.403      0.308
                   4        738        467      0.425       0.61      0.556      0.405
                   5        738         70      0.247      0.479      0.274      0.133
                   6        738         65      0.295      0.277      0.169      0.062
                   7        738       1619      0.502      0.641      0.586      0.244
                   8        738       2845      0.526      0.653      0.615      0.326
                   9        738          2          1          0   0.000308   0.000308

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 12:35:32.054057484 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

=== round003: DQA scene-daynight round ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round003 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round003 client0_highway_day: pseudo scan 250/1500 images, kept 2388 boxes
round003 client0_highway_day: pseudo scan 500/1500 images, kept 4832 boxes
round003 client0_highway_day: pseudo scan 750/1500 images, kept 7194 boxes
round003 client0_highway_day: pseudo scan 1000/1500 images, kept 9578 boxes
round003 client0_highway_day: pseudo scan 1250/1500 images, kept 11914 boxes
round003 client0_highway_day: pseudo scan 1500/1500 images, kept 14296 boxes
{
  "round": "round003",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 11133,
  "boxes_per_kept_image": 7.446822742474916,
  "mean_conf": 0.786993062995166,
  "mean_stability": 0.954124562231494,
  "mean_score": 0.7540835868496545,
  "class_counts": {
    "0": 155,
    "2": 6434,
    "3": 96,
    "4": 512,
    "5": 6,
    "7": 557,
    "8": 3373
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_client0_highway_day_stable_boxes.csv"
}
round003 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round003 client1_highway_night: pseudo scan 250/1500 images, kept 1789 boxes
round003 client1_highway_night: pseudo scan 500/1500 images, kept 3713 boxes
round003 client1_highway_night: pseudo scan 750/1500 images, kept 5603 boxes
round003 client1_highway_night: pseudo scan 1000/1500 images, kept 7415 boxes
round003 client1_highway_night: pseudo scan 1250/1500 images, kept 9271 boxes
round003 client1_highway_night: pseudo scan 1500/1500 images, kept 11091 boxes
{
  "round": "round003",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 8942,
  "boxes_per_kept_image": 6.062372881355932,
  "mean_conf": 0.6959296117204063,
  "mean_stability": 0.9358098257963782,
  "mean_score": 0.6552396820383308,
  "class_counts": {
    "0": 58,
    "2": 4991,
    "3": 26,
    "4": 137,
    "5": 6,
    "7": 552,
    "8": 3172
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_client1_highway_night_stable_boxes.csv"
}
round003 client2_citystreet_day: pseudo scan 1/1500 images, kept 7 boxes
round003 client2_citystreet_day: pseudo scan 250/1500 images, kept 2698 boxes
round003 client2_citystreet_day: pseudo scan 500/1500 images, kept 5415 boxes
round003 client2_citystreet_day: pseudo scan 750/1500 images, kept 8156 boxes
round003 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10925 boxes
round003 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13655 boxes
round003 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16302 boxes
{
  "round": "round003",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13659,
  "boxes_per_kept_image": 9.130347593582888,
  "mean_conf": 0.7834608662297763,
  "mean_stability": 0.9520892308479051,
  "mean_score": 0.7492073916894086,
  "class_counts": {
    "0": 1411,
    "2": 7336,
    "3": 165,
    "4": 567,
    "5": 60,
    "7": 1528,
    "8": 2592
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_client2_citystreet_day_stable_boxes.csv"
}
round003 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round003 client3_citystreet_night: pseudo scan 250/1500 images, kept 2468 boxes
round003 client3_citystreet_night: pseudo scan 500/1500 images, kept 4889 boxes
round003 client3_citystreet_night: pseudo scan 750/1500 images, kept 7287 boxes
round003 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9632 boxes
round003 client3_citystreet_night: pseudo scan 1250/1500 images, kept 12131 boxes
round003 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14542 boxes
{
  "round": "round003",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 12043,
  "boxes_per_kept_image": 8.131667792032411,
  "mean_conf": 0.7003863292863715,
  "mean_stability": 0.935242661490033,
  "mean_score": 0.6590914214405412,
  "class_counts": {
    "0": 543,
    "2": 6544,
    "3": 61,
    "4": 153,
    "5": 31,
    "7": 1908,
    "8": 2803
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_client3_citystreet_night_stable_boxes.csv"
}
round003 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round003 client4_residential_day: pseudo scan 250/1500 images, kept 2579 boxes
round003 client4_residential_day: pseudo scan 500/1500 images, kept 5185 boxes
round003 client4_residential_day: pseudo scan 750/1500 images, kept 7740 boxes
round003 client4_residential_day: pseudo scan 1000/1500 images, kept 10221 boxes
round003 client4_residential_day: pseudo scan 1250/1500 images, kept 12764 boxes
round003 client4_residential_day: pseudo scan 1500/1500 images, kept 15244 boxes
{
  "round": "round003",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9891,
  "boxes_per_kept_image": 6.633802816901408,
  "mean_conf": 0.8222505703497651,
  "mean_stability": 0.960181396936288,
  "mean_score": 0.7926676515279001,
  "class_counts": {
    "0": 375,
    "2": 6860,
    "3": 49,
    "4": 308,
    "5": 37,
    "7": 531,
    "8": 1731
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_client4_residential_day_stable_boxes.csv"
}
round003 client5_residential_night: pseudo scan 1/1500 images, kept 11 boxes
round003 client5_residential_night: pseudo scan 250/1500 images, kept 2440 boxes
round003 client5_residential_night: pseudo scan 500/1500 images, kept 4816 boxes
round003 client5_residential_night: pseudo scan 750/1500 images, kept 7191 boxes
round003 client5_residential_night: pseudo scan 1000/1500 images, kept 9651 boxes
round003 client5_residential_night: pseudo scan 1250/1500 images, kept 12065 boxes
round003 client5_residential_night: pseudo scan 1500/1500 images, kept 14522 boxes
{
  "round": "round003",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 8940,
  "boxes_per_kept_image": 6.036461850101283,
  "mean_conf": 0.7797423178550914,
  "mean_stability": 0.9488910678649108,
  "mean_score": 0.7425100788078858,
  "class_counts": {
    "0": 123,
    "2": 6535,
    "3": 27,
    "4": 92,
    "5": 15,
    "7": 599,
    "8": 1549
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/stats/03_round003_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30955 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round003_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client0_highway_day_stable_train' images and labels...:   0%|          | 0/11257 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client0_highway_day_stable_train' images and labels...10002 found, 1255 missing, 0 empty, 0 corrupted: 100%|██████████| 11257/11257 [00:00<00:00, 12333.94it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.828389830508474
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.cache' images and labels... 10002 found, 1255 missing, 0 empty, 0 corrupted: 100%|██████████| 11257/11257 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:37:49.014269695 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:37:49.015494840 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1976       640   0.03452   0.04471  0.006043     6.822:   3%|▎         | 1/39 [00:32<20:28, 32.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1844       640   0.03406   0.04355  0.005561     6.653:   5%|▌         | 2/39 [00:33<08:38, 14.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640   0.03474   0.04505  0.005579     6.829:   8%|▊         | 3/39 [00:34<04:52,  8.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1995       640   0.03448   0.04487  0.005439     6.783:  10%|█         | 4/39 [00:35<03:08,  5.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1924       640   0.03453   0.04439  0.005475     6.751:  13%|█▎        | 5/39 [00:36<02:08,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1922       640   0.03447   0.04383  0.005428     6.698:  15%|█▌        | 6/39 [00:37<01:32,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1997       640   0.03429   0.04309  0.005405     6.623:  18%|█▊        | 7/39 [00:38<01:09,  2.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2222       640    0.0343   0.04342  0.005341     6.645:  21%|██        | 8/39 [00:39<00:54,  1.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2165       640   0.03447   0.04363  0.005329     6.675:  23%|██▎       | 9/39 [00:40<00:44,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2088       640   0.03453   0.04384  0.005308     6.694:  26%|██▌       | 10/39 [00:41<00:37,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640   0.03452   0.04352  0.005235     6.662:  28%|██▊       | 11/39 [00:42<00:32,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2043       640   0.03452   0.04353  0.005272     6.666:  31%|███       | 12/39 [00:42<00:29,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1933       640   0.03455   0.04331  0.005255     6.649:  33%|███▎      | 13/39 [00:43<00:26,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640    0.0346   0.04336  0.005242     6.656:  36%|███▌      | 14/39 [00:44<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2008       640   0.03458   0.04319  0.005182     6.636:  38%|███▊      | 15/39 [00:45<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640    0.0346   0.04326  0.005157     6.642:  41%|████      | 16/39 [00:46<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1787       640   0.03464   0.04302  0.005164     6.626:  44%|████▎     | 17/39 [00:47<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2071       640   0.03468   0.04286  0.005117     6.613:  46%|████▌     | 18/39 [00:48<00:19,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1735       640   0.03467   0.04265  0.005118     6.595:  49%|████▊     | 19/39 [00:49<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2326       640   0.03461   0.04278  0.005129     6.602:  51%|█████▏    | 20/39 [00:50<00:17,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2017       640   0.03469   0.04274  0.005139     6.606:  54%|█████▍    | 21/39 [00:50<00:16,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1705       640   0.03458   0.04254  0.005093     6.576:  56%|█████▋    | 22/39 [00:51<00:15,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2057       640   0.03451   0.04247  0.005067     6.564:  59%|█████▉    | 23/39 [00:52<00:14,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2321       640   0.03455   0.04253  0.005044     6.569:  62%|██████▏   | 24/39 [00:53<00:13,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1970       640   0.03458   0.04249  0.005061      6.57:  64%|██████▍   | 25/39 [00:54<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2069       640   0.03454   0.04251   0.00503     6.567:  67%|██████▋   | 26/39 [00:55<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.481      0.446      0.408       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.563      0.397      0.409      0.231
                   0        738       1052      0.559      0.564      0.552      0.263
                   1        738         44       0.56     0.0872      0.167      0.063
                   2        738       8622      0.695      0.727      0.755      0.487
                   3        738        151      0.489      0.391      0.417      0.319
                   4        738        467      0.516      0.572      0.555      0.406
                   5        738         70      0.273      0.371      0.266       0.14
                   6        738         65      0.299     0.0615      0.168     0.0663
                   7        738       1619      0.571      0.612      0.596      0.245
                   8        738       2845      0.665       0.59      0.611      0.319
                   9        738          2          1          0   0.000297   0.000267

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day

1 epochs completed in 0.032 hours.
Destroying process group...
[rank0]:[W505 12:39:43.712640628 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30956 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round003_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client1_highway_night_stable_train' images and labels...9769 found, 1468 missing, 0 empty, 0 corrupted: 100%|██████████| 11237/11237 [00:00<00:00, 14459.35it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.297369664514097
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.cache' images and labels... 9769 found, 1468 missing, 0 empty, 0 corrupted: 100%|██████████| 11237/11237 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:40:00.656789809 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:40:00.756268375 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1933       640   0.03418   0.04079  0.005007     6.398:   2%|▎         | 1/40 [00:32<21:15, 32.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1982       640   0.03481    0.0402  0.005003     6.402:   5%|▌         | 2/40 [00:33<09:00, 14.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1773       640   0.03432   0.03986  0.004846     6.323:   8%|▊         | 3/40 [00:35<05:05,  8.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1971       640   0.03416   0.03995  0.004738     6.308:  10%|█         | 4/40 [00:36<03:14,  5.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1795       640   0.03427   0.03971  0.004799     6.302:  12%|█▎        | 5/40 [00:37<02:12,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1766       640   0.03418   0.03915  0.004894     6.258:  15%|█▌        | 6/40 [00:37<01:35,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1690       640   0.03419    0.0383  0.004861     6.188:  18%|█▊        | 7/40 [00:38<01:12,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1878       640   0.03416   0.03811  0.004868     6.171:  20%|██        | 8/40 [00:39<00:56,  1.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1920       640   0.03422   0.03805  0.004843     6.169:  22%|██▎       | 9/40 [00:40<00:46,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1874       640   0.03429   0.03806  0.004848     6.176:  25%|██▌       | 10/40 [00:41<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1995       640   0.03429   0.03809  0.004892     6.181:  28%|██▊       | 11/40 [00:42<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1838       640    0.0342   0.03787  0.004881     6.156:  30%|███       | 12/40 [00:43<00:30,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1975       640   0.03422   0.03779  0.004927     6.155:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640   0.03428   0.03772  0.004946     6.155:  35%|███▌      | 14/40 [00:45<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1890       640   0.03427   0.03762  0.004953     6.147:  38%|███▊      | 15/40 [00:46<00:23,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1795       640    0.0342   0.03746  0.004936     6.128:  40%|████      | 16/40 [00:46<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640   0.03432   0.03758  0.004965     6.149:  42%|████▎     | 17/40 [00:47<00:20,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2102       640   0.03431   0.03766  0.004999     6.157:  45%|████▌     | 18/40 [00:48<00:19,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1587       640   0.03432   0.03739  0.005027     6.139:  48%|████▊     | 19/40 [00:49<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2035       640   0.03438   0.03738  0.005035     6.144:  50%|█████     | 20/40 [00:50<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2105       640   0.03447   0.03748  0.005077     6.162:  52%|█████▎    | 21/40 [00:51<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640   0.03454   0.03754  0.005078     6.172:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640    0.0345   0.03746  0.005063     6.162:  57%|█████▊    | 23/40 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1787       640   0.03449   0.03732  0.005042     6.148:  60%|██████    | 24/40 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1737       640   0.03446   0.03717  0.005028     6.132:  62%|██████▎   | 25/40 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1852       640   0.03442   0.03703  0.004998     6.116:  65%|██████▌   | 26/40 [00:55<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.501      0.426      0.402      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.534      0.397        0.4      0.227
                   0        738       1052      0.562      0.528      0.538      0.256
                   1        738         44      0.444     0.0909       0.16     0.0656
                   2        738       8622      0.657      0.729       0.75      0.483
                   3        738        151      0.453      0.391      0.407      0.312
                   4        738        467       0.46      0.602      0.546      0.399
                   5        738         70      0.276      0.357      0.247      0.125
                   6        738         65      0.309     0.0615      0.164     0.0685
                   7        738       1619      0.554      0.616      0.588      0.246
                   8        738       2845      0.629      0.595      0.601      0.313
                   9        738          2          1          0   0.000255   0.000229

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:41:57.802039408 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30957 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round003_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train' images and labels...9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<00:00, 16428.43it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:42:14.921839314 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:42:14.994771606 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2066       640   0.03583   0.05089  0.005151     7.349:   3%|▎         | 1/39 [00:32<20:51, 32.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2187       640   0.03532    0.0505  0.005459     7.302:   5%|▌         | 2/39 [00:34<08:46, 14.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1974       640   0.03496   0.04972  0.005471     7.212:   8%|▊         | 3/39 [00:35<04:56,  8.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640   0.03505   0.04889  0.005364     7.144:  10%|█         | 4/39 [00:36<03:09,  5.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2145       640   0.03498   0.04832  0.005256     7.085:  13%|█▎        | 5/39 [00:37<02:08,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1780       640   0.03457   0.04731  0.005206     6.967:  15%|█▌        | 6/39 [00:38<01:32,  2.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1960       640   0.03465   0.04712   0.00528     6.964:  18%|█▊        | 7/39 [00:38<01:09,  2.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1897       640   0.03453   0.04674  0.005224      6.92:  21%|██        | 8/39 [00:39<00:54,  1.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2025       640   0.03466   0.04676  0.005166     6.927:  23%|██▎       | 9/39 [00:40<00:44,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1808       640   0.03449   0.04648  0.005147      6.89:  26%|██▌       | 10/39 [00:41<00:37,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1991       640   0.03451   0.04639  0.005148     6.883:  28%|██▊       | 11/39 [00:42<00:32,  1.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1792       640   0.03454   0.04592  0.005157     6.849:  31%|███       | 12/39 [00:43<00:29,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03462   0.04577  0.005116      6.84:  33%|███▎      | 13/39 [00:44<00:26,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03472   0.04581  0.005085     6.849:  36%|███▌      | 14/39 [00:44<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1930       640   0.03472   0.04568  0.005065     6.837:  38%|███▊      | 15/39 [00:45<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1894       640   0.03462   0.04536  0.005059     6.804:  41%|████      | 16/39 [00:46<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1504       640   0.03453   0.04513  0.005087      6.78:  44%|████▎     | 17/39 [00:47<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1920       640   0.03446   0.04505  0.005074     6.767:  46%|████▌     | 18/39 [00:48<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1718       640   0.03447   0.04475  0.005052     6.742:  49%|████▊     | 19/39 [00:49<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03442   0.04475  0.005039     6.737:  51%|█████▏    | 20/39 [00:50<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1849       640   0.03434   0.04458  0.005022     6.716:  54%|█████▍    | 21/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1707       640    0.0343    0.0445  0.005011     6.705:  56%|█████▋    | 22/39 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03423   0.04438  0.005011      6.69:  59%|█████▉    | 23/39 [00:52<00:13,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1900       640    0.0342   0.04432  0.005002     6.681:  62%|██████▏   | 24/39 [00:53<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1848       640   0.03416   0.04421  0.004997     6.669:  64%|██████▍   | 25/39 [00:54<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640    0.0341   0.04418  0.004986     6.661:  67%|██████▋   | 26/39 [00:55<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937        0.5       0.43      0.407      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.497      0.428      0.407      0.231
                   0        738       1052      0.574      0.535      0.544      0.257
                   1        738         44      0.377      0.159      0.165     0.0758
                   2        738       8622      0.602      0.758      0.758      0.487
                   3        738        151      0.308      0.424      0.408      0.313
                   4        738        467      0.444      0.615       0.55      0.398
                   5        738         70      0.265      0.414      0.268      0.138
                   6        738         65      0.294      0.123       0.18     0.0731
                   7        738       1619      0.528      0.628      0.584      0.246
                   8        738       2845      0.581      0.622       0.61       0.32
                   9        738          2          1          0   0.000273   0.000246

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:44:12.045634936 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30958 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round003_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train' images and labels...9763 found, 1480 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<00:00, 12254.57it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.26851124037101
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache' images and labels... 9763 found, 1480 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:44:29.089067493 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:44:29.096354477 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2025       640   0.03523     0.045  0.005396      6.85:   2%|▎         | 1/40 [00:32<21:24, 32.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1899       640   0.03537   0.04527  0.005263     6.872:   5%|▌         | 2/40 [00:34<09:01, 14.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1967       640   0.03537   0.04472  0.005416     6.841:   8%|▊         | 3/40 [00:35<05:07,  8.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1714       640   0.03513   0.04378  0.005201     6.729:  10%|█         | 4/40 [00:36<03:16,  5.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1919       640   0.03468   0.04308  0.005086     6.627:  12%|█▎        | 5/40 [00:37<02:13,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1735       640   0.03445   0.04217  0.005029     6.532:  15%|█▌        | 6/40 [00:38<01:36,  2.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1955       640    0.0345   0.04174  0.004999     6.499:  18%|█▊        | 7/40 [00:39<01:12,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1927       640   0.03446   0.04136  0.004969     6.463:  20%|██        | 8/40 [00:40<00:56,  1.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2024       640   0.03433   0.04153  0.004924     6.463:  22%|██▎       | 9/40 [00:40<00:46,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1989       640   0.03429   0.04157  0.004954     6.466:  25%|██▌       | 10/40 [00:41<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2003       640   0.03428   0.04151  0.005016     6.464:  28%|██▊       | 11/40 [00:42<00:34,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1850       640   0.03432   0.04132   0.00503     6.453:  30%|███       | 12/40 [00:43<00:31,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2202       640   0.03435    0.0413  0.005058     6.457:  32%|███▎      | 13/40 [00:44<00:27,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2101       640   0.03433   0.04135  0.005019     6.456:  35%|███▌      | 14/40 [00:45<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1954       640   0.03433   0.04127  0.004992     6.447:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1907       640   0.03434   0.04104   0.00497     6.428:  40%|████      | 16/40 [00:47<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1668       640    0.0343   0.04061  0.005005     6.394:  42%|████▎     | 17/40 [00:48<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2080       640    0.0344   0.04051  0.005025     6.395:  45%|████▌     | 18/40 [00:48<00:19,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1509       640   0.03444   0.04018  0.005032     6.372:  48%|████▊     | 19/40 [00:49<00:18,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2141       640    0.0344   0.04007   0.00502     6.359:  50%|█████     | 20/40 [00:50<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1883       640   0.03441   0.03998   0.00503     6.353:  52%|█████▎    | 21/40 [00:51<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1760       640   0.03446   0.03979  0.005021     6.342:  55%|█████▌    | 22/40 [00:52<00:15,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2205       640    0.0345   0.03978  0.005027     6.344:  57%|█████▊    | 23/40 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1940       640    0.0345   0.03977  0.005024     6.344:  60%|██████    | 24/40 [00:54<00:13,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1792       640   0.03443   0.03962  0.004998     6.324:  62%|██████▎   | 25/40 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2108       640   0.03442   0.03955  0.004997     6.317:  65%|██████▌   | 26/40 [00:55<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.564      0.374      0.398      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.569       0.38      0.397      0.224
                   0        738       1052      0.644      0.487      0.519      0.248
                   1        738         44      0.381     0.0455      0.151     0.0575
                   2        738       8622      0.685      0.714      0.745      0.477
                   3        738        151      0.511      0.364      0.405       0.31
                   4        738        467      0.468      0.587      0.548      0.397
                   5        738         70      0.328      0.386      0.263      0.129
                   6        738         65      0.397     0.0609      0.154     0.0634
                   7        738       1619      0.599      0.582      0.582      0.243
                   8        738       2845      0.677      0.571        0.6      0.315
                   9        738          2          1          0    0.00018    0.00018

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 12:46:28.164293667 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30959 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round003_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client4_residential_day_stable_train' images and labels...9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:01<00:00, 8899.55it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.cache' images and labels... 9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:46:46.453822542 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:46:46.510718420 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2084       640   0.03463   0.04982  0.004432     7.111:   3%|▎         | 1/39 [00:33<21:26, 33.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2054       640   0.03505   0.04969  0.005227     7.197:   5%|▌         | 2/39 [00:34<08:59, 14.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640   0.03445   0.04804  0.005168     7.013:   8%|▊         | 3/39 [00:36<05:02,  8.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1904       640   0.03459   0.04728  0.005277     6.972:  10%|█         | 4/39 [00:37<03:13,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1942       640   0.03433   0.04614  0.005225     6.855:  13%|█▎        | 5/39 [00:37<02:10,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1735       640    0.0344   0.04486  0.005307     6.765:  15%|█▌        | 6/39 [00:38<01:34,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1985       640   0.03453    0.0446  0.005311     6.755:  18%|█▊        | 7/39 [00:39<01:10,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1947       640   0.03459   0.04435  0.005239     6.734:  21%|██        | 8/39 [00:40<00:55,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2072       640   0.03451   0.04436  0.005292     6.733:  23%|██▎       | 9/39 [00:41<00:45,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03459   0.04435   0.00526     6.736:  26%|██▌       | 10/39 [00:42<00:38,  1.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2139       640   0.03458   0.04429   0.00525      6.73:  28%|██▊       | 11/39 [00:43<00:33,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2120       640   0.03455   0.04422  0.005232     6.721:  31%|███       | 12/39 [00:44<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640   0.03464   0.04432  0.005209     6.733:  33%|███▎      | 13/39 [00:45<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2027       640   0.03471   0.04426  0.005199     6.734:  36%|███▌      | 14/39 [00:46<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1824       640   0.03476   0.04399  0.005206     6.717:  38%|███▊      | 15/39 [00:46<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1768       640   0.03475   0.04377  0.005204     6.698:  41%|████      | 16/39 [00:47<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1747       640   0.03462   0.04357  0.005173     6.669:  44%|████▎     | 17/39 [00:48<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2019       640   0.03458   0.04356  0.005137     6.662:  46%|████▌     | 18/39 [00:49<00:18,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1602       640   0.03451   0.04326   0.00513     6.632:  49%|████▊     | 19/39 [00:50<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2209       640   0.03452   0.04328   0.00512     6.633:  51%|█████▏    | 20/39 [00:51<00:16,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1896       640   0.03452   0.04323  0.005102     6.628:  54%|█████▍    | 21/39 [00:52<00:15,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1996       640    0.0345   0.04324  0.005103     6.627:  56%|█████▋    | 22/39 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2001       640   0.03451   0.04325  0.005125     6.631:  59%|█████▉    | 23/39 [00:53<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03448   0.04317  0.005118     6.622:  62%|██████▏   | 24/39 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2030       640   0.03448   0.04316  0.005118     6.621:  64%|██████▍   | 25/39 [00:55<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1772       640   0.03448   0.04297  0.005105     6.604:  67%|██████▋   | 26/39 [00:56<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.483      0.458       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.466      0.461      0.409       0.23
                   0        738       1052      0.451      0.582      0.545      0.259
                   1        738         44       0.33      0.227      0.176     0.0689
                   2        738       8622      0.603      0.755      0.754      0.484
                   3        738        151      0.287       0.45       0.42      0.325
                   4        738        467        0.4       0.64      0.556      0.405
                   5        738         70      0.263      0.471       0.28      0.137
                   6        738         65      0.282      0.215      0.167     0.0581
                   7        738       1619      0.498      0.639      0.586      0.245
                   8        738       2845       0.55      0.634      0.606      0.321
                   9        738          2          1          0   0.000264   0.000264

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:48:44.782536686 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30960 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/client_states/dqa01_round003_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client5_residential_night_stable_train' images and labels...9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<00:00, 11548.25it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.cache' images and labels... 9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:49:01.588488105 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:49:01.615441944 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2077       640   0.03517   0.04548  0.004906     6.845:   2%|▎         | 1/40 [00:32<20:52, 32.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1843       640   0.03502   0.04465  0.005045     6.778:   5%|▌         | 2/40 [00:33<08:48, 13.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2137       640   0.03478   0.04455  0.004658     6.719:   8%|▊         | 3/40 [00:34<04:58,  8.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1972       640   0.03491   0.04381  0.004625     6.668:  10%|█         | 4/40 [00:35<03:12,  5.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1986       640   0.03487   0.04373  0.004657     6.661:  12%|█▎        | 5/40 [00:36<02:10,  3.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1851       640    0.0347   0.04272  0.004638     6.565:  15%|█▌        | 6/40 [00:37<01:34,  2.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1847       640   0.03455   0.04211  0.004669     6.506:  18%|█▊        | 7/40 [00:38<01:11,  2.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2128       640   0.03457   0.04211  0.004732     6.513:  20%|██        | 8/40 [00:39<00:56,  1.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2229       640   0.03464   0.04228  0.004757     6.535:  22%|██▎       | 9/40 [00:40<00:46,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2044       640   0.03456   0.04216  0.004806     6.522:  25%|██▌       | 10/40 [00:40<00:39,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2018       640   0.03453   0.04185  0.004804     6.495:  28%|██▊       | 11/40 [00:41<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1751       640    0.0345   0.04125  0.004805     6.444:  30%|███       | 12/40 [00:42<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1972       640   0.03446   0.04103  0.004831     6.426:  32%|███▎      | 13/40 [00:43<00:27,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1992       640   0.03451   0.04091  0.004858     6.422:  35%|███▌      | 14/40 [00:44<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1981       640   0.03446   0.04084  0.004871     6.414:  38%|███▊      | 15/40 [00:45<00:23,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1799       640   0.03446    0.0405  0.004887     6.388:  40%|████      | 16/40 [00:46<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1967       640   0.03451   0.04041  0.004902     6.386:  42%|████▎     | 17/40 [00:47<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1967       640   0.03455   0.04028  0.004929     6.381:  45%|████▌     | 18/40 [00:47<00:19,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1861       640   0.03457   0.04003  0.004914     6.361:  48%|████▊     | 19/40 [00:48<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1803       640    0.0346    0.0398  0.004927     6.346:  50%|█████     | 20/40 [00:49<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2279       640   0.03467    0.0398  0.004925     6.352:  52%|█████▎    | 21/40 [00:50<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1868       640   0.03466   0.03961  0.004929     6.336:  55%|█████▌    | 22/40 [00:51<00:15,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1924       640   0.03464   0.03947  0.004937     6.324:  57%|█████▊    | 23/40 [00:52<00:14,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2063       640   0.03464   0.03937  0.004952     6.317:  60%|██████    | 24/40 [00:53<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1813       640   0.03463   0.03917  0.004961     6.301:  62%|██████▎   | 25/40 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03465     0.039  0.004959     6.289:  65%|██████▌   | 26/40 [00:54<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.404      0.404      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.527      0.408      0.404      0.226
                   0        738       1052      0.533      0.546       0.53      0.252
                   1        738         44      0.544      0.135      0.177     0.0679
                   2        738       8622      0.642      0.733      0.747      0.479
                   3        738        151      0.394      0.396      0.413      0.319
                   4        738        467      0.454      0.593      0.553      0.402
                   5        738         70      0.268      0.371      0.262      0.118
                   6        738         65      0.274     0.0769      0.157     0.0596
                   7        738       1619      0.557      0.623      0.593      0.244
                   8        738       2845      0.607      0.603      0.604      0.316
                   9        738          2          1          0   0.000177   0.000141

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 12:50:59.201777660 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30961 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/configs/pl03_round003_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round003_dqa_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 12:51:17.303480845 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 12:51:17.366859411 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03398   0.04232  0.004928     6.498:   3%|▎         | 1/31 [00:32<16:03, 32.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03464   0.04328  0.005128     6.643:   6%|▋         | 2/31 [00:32<06:36, 13.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03406   0.04215  0.005029       6.5:  10%|▉         | 3/31 [00:33<03:37,  7.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03349   0.04045   0.00479     6.299:  13%|█▎        | 4/31 [00:34<02:14,  5.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03349   0.04064   0.00482     6.316:  16%|█▌        | 5/31 [00:34<01:28,  3.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03368   0.04062  0.004887     6.335:  19%|█▉        | 6/31 [00:35<01:01,  2.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640    0.0338   0.04036   0.00496     6.329:  23%|██▎       | 7/31 [00:36<00:44,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03373   0.04045  0.004986     6.334:  26%|██▌       | 8/31 [00:36<00:32,  1.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03378   0.04039  0.004892     6.325:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03376   0.04051  0.004874     6.331:  32%|███▏      | 10/31 [00:37<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03373   0.04054  0.004896     6.333:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03363   0.04027  0.004889     6.303:  39%|███▊      | 12/31 [00:39<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0336   0.04032  0.004839       6.3:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03361   0.04014  0.004805     6.284:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03364   0.04006  0.004844     6.284:  48%|████▊     | 15/31 [00:40<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03364   0.03993  0.004834     6.272:  52%|█████▏    | 16/31 [00:41<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03367   0.03999  0.004797     6.276:  55%|█████▍    | 17/31 [00:41<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03371   0.04004  0.004756     6.281:  58%|█████▊    | 18/31 [00:42<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03365   0.03991  0.004721     6.262:  61%|██████▏   | 19/31 [00:43<00:07,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03364   0.04014  0.004725      6.28:  65%|██████▍   | 20/31 [00:43<00:06,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03367   0.04017  0.004743     6.287:  68%|██████▊   | 21/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03367   0.04028  0.004713     6.293:  71%|███████   | 22/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03366   0.04033  0.004701     6.295:  74%|███████▍  | 23/31 [00:45<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03367   0.04041  0.004685     6.301:  77%|███████▋  | 24/31 [00:46<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03367   0.04036  0.004696     6.298:  81%|████████  | 25/31 [00:46<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03372   0.04039  0.004697     6.305:  84%|████████▍ | 26/31 [00:47<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.457      0.491       0.41      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.442      0.495      0.409       0.23
                   0        738       1052      0.405       0.59      0.541      0.258
                   1        738         44      0.248      0.295      0.155      0.061
                   2        738       8622      0.543      0.771      0.753      0.487
                   3        738        151      0.279      0.464      0.418      0.317
                   4        738        467      0.406      0.621      0.556      0.404
                   5        738         70      0.244      0.514      0.287      0.138
                   6        738         65      0.298      0.385      0.176     0.0632
                   7        738       1619      0.488       0.65       0.59      0.243
                   8        738       2845      0.507      0.665      0.617      0.327
                   9        738          2          1          0   0.000325   0.000293

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 12:52:55.696364158 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/evaluate_scene_daynight_protocol.py --workspace /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa --splits highway_day,highway_night,citystreet_day,citystreet_night,residential_day,residential_night,total --batch-size 16 --no-plots --verbose --checkpoint warmup_global=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/global_checkpoints/round000_warmup.pt --checkpoint round001_dqa_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_cwa_v2_aggregate.pt --checkpoint round001_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round001_dqa_server_repair.pt --checkpoint round002_dqa_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_cwa_v2_aggregate.pt --checkpoint round002_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round002_dqa_server_repair.pt --checkpoint round003_dqa_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round003_dqa_cwa_v2_aggregate.pt --checkpoint round003_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/checkpoints/round003_dqa_server_repair.pt
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/validation_reports/paper_protocol_eval_manifest.json
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/validation_reports/paper_protocol_eval_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/validation_reports/paper_protocol_classwise_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/pseudo_dqa/validation_reports/paper_protocol_eval_summary.md
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison/stats/01_0_all_condition_metrics.csv
DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_scene_daynight_dqa_01_0.py', '--workspace-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_0_repair_baseline_comparison', '--client-limit', '1500', '--conditions', 'all', '--rounds', '3', '--batch-size', '160', '--workers', '8', '--gpus', '2', '--master-port', '30741', '--server-repair-epochs', '1', '--evaluate', '--classwise', '--no-eval-plots', '--notify'], returncode=0)

## Combined Metrics

In [4]:
import pandas as pd

metrics_csv = WORKSPACE / "stats" / "01_0_all_condition_metrics.csv"
if metrics_csv.exists():
    df = pd.read_csv(metrics_csv)
    display(df)
else:
    print("No combined metrics yet:", metrics_csv)

,condition,round,aggregate_map50,aggregate_map50_95,repaired_map50,repaired_map50_95,repair_gain_map50_95,retained_gain_map50_95,round_delta_map50_95,worst_split,worst_split_map50_95,day_avg_map50_95,night_avg_map50_95,day_night_gap_map50_95
0,repair_only,1,NaN,NaN,0.373,0.206,NaN,0.018,NaN,highway_night,0.148,0.226333,0.167667,0.058667
1,repair_only,2,NaN,NaN,0.379,0.210,NaN,0.022,0.004,highway_night,0.151,0.230000,0.172333,0.057667
2,repair_only,3,NaN,NaN,0.381,0.212,NaN,0.024,0.002,highway_night,0.152,0.232333,0.173333,0.059000
3,pseudo_fedavg,1,0.350,0.196,0.377,0.209,0.013,0.021,NaN,highway_night,0.148,0.230000,0.167667,0.062333
4,pseudo_fedavg,2,0.349,0.198,0.379,0.211,0.013,0.023,0.002,highway_night,0.146,0.234000,0.167333,0.066667
5,pseudo_fedavg,3,0.345,0.196,0.379,0.212,0.016,0.024,0.001,highway_night,0.143,0.235667,0.163667,0.072000
6,pseudo_dqa,1,0.351,0.189,0.373,0.206,0.017,0.018,NaN,highway_night,0.148,0.226333,0.167333,0.059000
7,pseudo_dqa,2,0.373,0.206,0.379,0.210,0.004,0.022,0.004,highway_night,0.151,0.230000,0.172333,0.057667
8,pseudo_dqa,3,0.378,0.210,0.381,0.211,0.001,0.023,0.001,highway_night,0.151,0.232667,0.172667,0.060000

## Final-Round Comparison

In [5]:
if metrics_csv.exists():
    df = pd.read_csv(metrics_csv)
    final = df.sort_values("round").groupby("condition").tail(1)
    display(final[[
        "condition", "round", "aggregate_map50", "aggregate_map50_95",
        "repaired_map50", "repaired_map50_95", "retained_gain_map50_95",
        "worst_split", "worst_split_map50_95", "day_night_gap_map50_95",
    ]].sort_values("repaired_map50_95", ascending=False))

,condition,round,aggregate_map50,aggregate_map50_95,repaired_map50,repaired_map50_95,retained_gain_map50_95,worst_split,worst_split_map50_95,day_night_gap_map50_95
2,repair_only,3,NaN,NaN,0.381,0.212,0.024,highway_night,0.152,0.059
5,pseudo_fedavg,3,0.345,0.196,0.379,0.212,0.024,highway_night,0.143,0.072
8,pseudo_dqa,3,0.378,0.210,0.381,0.211,0.023,highway_night,0.151,0.060

## Split-Level Evaluation

In [6]:
rows = []
for condition in ["repair_only", "pseudo_fedavg", "pseudo_dqa"]:
    path = WORKSPACE / condition / "validation_reports" / "paper_protocol_eval_summary.csv"
    if not path.exists():
        continue
    part = pd.read_csv(path)
    part["condition"] = condition
    rows.append(part)
if rows:
    eval_df = pd.concat(rows, ignore_index=True)
    ok = eval_df[eval_df["status"].eq("ok")].copy()
    final_rows = ok[ok["checkpoint_label"].eq("round003_server_repair")]
    display(final_rows[["condition", "split", "precision", "recall", "map50", "map50_95"]].sort_values(["split", "condition"]))
else:
    print("No evaluation summaries yet.")

         condition                 split  precision  recall  map50  map50_95
121     pseudo_dqa        citystreet_day      0.508   0.428  0.412     0.233
72   pseudo_fedavg        citystreet_day      0.517   0.430  0.416     0.236
23     repair_only        citystreet_day      0.510   0.426  0.412     0.233
122     pseudo_dqa      citystreet_night      0.468   0.353  0.327     0.174
73   pseudo_fedavg      citystreet_night      0.507   0.328  0.313     0.167
24     repair_only      citystreet_night      0.471   0.352  0.327     0.174
119     pseudo_dqa           highway_day      0.562   0.376  0.375     0.211
70   pseudo_fedavg           highway_day      0.588   0.373  0.379     0.215
21     repair_only           highway_day      0.563   0.375  0.376     0.211
120     pseudo_dqa         highway_night      0.479   0.265  0.276     0.151
71   pseudo_fedavg         highway_night      0.443   0.274  0.260     0.143
22     repair_only         highway_night      0.584   0.264  0.276     0.152
123     pseudo_dqa       residential_day      0.492   0.442  0.434     0.254
74   pseudo_fedavg       residential_day      0.522   0.446  0.440     0.256
25     repair_only       residential_day      0.491   0.442  0.434     0.253
124     pseudo_dqa     residential_night      0.381   0.392  0.368     0.193
75   pseudo_fedavg     residential_night      0.443   0.332  0.340     0.181
26     repair_only     residential_night      0.388   0.383  0.369     0.194
125     pseudo_dqa  scene_daynight_total      0.504   0.397  0.381     0.211
76   pseudo_fedavg  scene_daynight_total      0.528   0.385  0.379     0.212
27     repair_only  scene_daynight_total      0.500   0.400  0.381     0.212

## PseudoGT Stats

In [7]:
pseudo_rows = []
for condition in ["pseudo_fedavg", "pseudo_dqa"]:
    stats_dir = WORKSPACE / condition / "stats"
    for path in sorted(stats_dir.glob("03_round*_pseudo_label_stats.csv")):
        part = pd.read_csv(path)
        part["condition"] = condition
        pseudo_rows.append(part)
if pseudo_rows:
    pseudo_df = pd.concat(pseudo_rows, ignore_index=True)
    display(pseudo_df[[
        "condition", "round", "client", "pseudo_images_kept", "pseudo_boxes_kept",
        "boxes_per_kept_image", "mean_conf", "mean_stability", "mean_score",
    ]])
else:
    print("No pseudoGT stats yet.")

,condition,round,client,pseudo_images_kept,pseudo_boxes_kept,boxes_per_kept_image,mean_conf,mean_stability,mean_score
0,pseudo_fedavg,round001,client0_highway_day,1488,10812,7.2661,0.745772,0.944982,0.707788
1,pseudo_fedavg,round001,client1_highway_night,1476,9263,6.2757,0.645482,0.922016,0.598920
2,pseudo_fedavg,round001,client2_citystreet_day,1496,13789,9.2172,0.734744,0.940587,0.694337
3,pseudo_fedavg,round001,client3_citystreet_night,1484,12497,8.4212,0.646182,0.919555,0.598080
4,pseudo_fedavg,round001,client4_residential_day,1488,9829,6.6055,0.771392,0.951192,0.736932
5,pseudo_fedavg,round001,client5_residential_night,1486,9287,6.2497,0.702775,0.932827,0.658566
6,pseudo_fedavg,round002,client0_highway_day,1494,11016,7.3735,0.781026,0.954040,0.748264
7,pseudo_fedavg,round002,client1_highway_night,1462,8197,5.6067,0.679126,0.938476,0.641116
8,pseudo_fedavg,round002,client2_citystreet_day,1496,13620,9.1043,0.774709,0.951685,0.740573
9,pseudo_fedavg,round002,client3_citystreet_night,1472,11373,7.7262,0.677078,0.936137,0.637848
10,pseudo_fedavg,round002,client4_residential_day,1490,9815,6.5872,0.814867,0.960165,0.785483
11,pseudo_fedavg,round002,client5_residential_night,1473,8425,5.7196,0.753402,0.948520,0.717372
12,pseudo_fedavg,round003,client0_highway_day,1494,11041,7.3902,0.788274,0.955183,0.756075
13,pseudo_fedavg,round003,client1_highway_night,1436,7570,5.2716,0.682437,0.941965,0.646526
14,pseudo_fedavg,round003,client2_citystreet_day,1495,13606,9.1010,0.783639,0.953032,0.750134
15,pseudo_fedavg,round003,client3_citystreet_night,1467,10797,7.3599,0.675321,0.938034,0.637648
16,pseudo_fedavg,round003,client4_residential_day,1488,9839,6.6122,0.822036,0.961036,0.793164
17,pseudo_fedavg,round003,client5_residential_night,1455,7874,5.4117,0.749449,0.950781,0.715373
18,pseudo_dqa,round001,client0_highway_day,1488,10812,7.2661,0.745772,0.944982,0.707788
19,pseudo_dqa,round001,client1_highway_night,1476,9263,6.2757,0.645482,0.922016,0.598920
20,pseudo_dqa,round001,client2_citystreet_day,1496,13789,9.2172,0.734744,0.940587,0.694337
21,pseudo_dqa,round001,client3_citystreet_night,1484,12497,8.4212,0.646182,0.919555,0.598080
22,pseudo_dqa,round001,client4_residential_day,1488,9829,6.6055,0.771392,0.951192,0.736932
23,pseudo_dqa,round001,client5_residential_night,1486,9287,6.2497,0.702775,0.932827,0.658566
24,pseudo_dqa,round002,client0_highway_day,1492,11061,7.4135,0.778231,0.952607,0.744494
25,pseudo_dqa,round002,client1_highway_night,1476,8986,6.0881,0.682601,0.933623,0.641287
26,pseudo_dqa,round002,client2_citystreet_day,1496,13703,9.1598,0.772558,0.950273,0.737444
27,pseudo_dqa,round002,client3_citystreet_night,1480,12149,8.2088,0.687684,0.932581,0.645379
28,pseudo_dqa,round002,client4_residential_day,1491,9893,6.6351,0.812038,0.958903,0.781844
29,pseudo_dqa,round002,client5_residential_night,1481,9075,6.1276,0.763085,0.945389,0.724210
30,pseudo_dqa,round003,client0_highway_day,1495,11133,7.4468,0.786993,0.954125,0.754084
31,pseudo_dqa,round003,client1_highway_night,1475,8942,6.0624,0.695930,0.935810,0.655240
32,pseudo_dqa,round003,client2_citystreet_day,1496,13659,9.1303,0.783461,0.952089,0.749207
33,pseudo_dqa,round003,client3_citystreet_night,1481,12043,8.1317,0.700386,0.935243,0.659091
34,pseudo_dqa,round003,client4_residential_day,1491,9891,6.6338,0.822251,0.960181,0.792668
35,pseudo_dqa,round003,client5_residential_night,1481,8940,6.0365,0.779742,0.948891,0.742510