# 01 Repair-Oriented Scene-Daynight DQA

This notebook starts the new organized DQA line.  It keeps the old
top-level DQA notebooks untouched and runs the next experiment under
`scene_daynight_dqa/output`.

## Objective

We move from 3 scene clients to 6 clients:

- highway_day / highway_night
- citystreet_day / citystreet_night
- residential_day / residential_night

The method is repair-oriented: client pseudoGT adaptation is allowed
to be imperfect, but the repaired global checkpoint after supervised
source repair is the main score.

In [1]:
from pathlib import Path
import os
import subprocess
import sys

cwd = Path.cwd().resolve()
if cwd.name == "notebooks":
    PROJECT_ROOT = cwd.parent
elif (cwd / "dynamic_quality_aware_classwise_aggregation").exists():
    PROJECT_ROOT = cwd / "dynamic_quality_aware_classwise_aggregation" / "scene_daynight_dqa"
else:
    PROJECT_ROOT = cwd
os.chdir(PROJECT_ROOT)
WORKSPACE = PROJECT_ROOT / "output" / "01_repair_oriented_scene_daynight_dqa"
print(PROJECT_ROOT)
print(WORKSPACE)

/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa
/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa

## Setup Check

This builds the six client lists and the six validation splits.  The
default client cap is 1500 images per client to keep clients balanced.

In [2]:
CLIENT_LIMIT = 1500
subprocess.run([
    sys.executable,
    "scripts/run_scene_daynight_dqa_01.py",
    "--workspace-root", str(WORKSPACE),
    "--client-limit", str(CLIENT_LIMIT),
    "--setup-only",
], check=True)

Project root: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa
Workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa
Warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "dqa": {
    "num_classes": 10,
    "count_ema": 0.65,
    "quality_ema": 0.65,
    "alpha_ema": 0.4,
    "temperature": 2.5,
    "uniform_mix": 0.05,
    "classwise_blend": 0.08,
    "stability_lambda": 0.7,
    "min_effective_count": 5.0,
    "min_quality": 0.1,
    "max_quality": 1.0,
    "server_anchor": 20.0,
    "localize_bn": true,
    "min_server_alpha": 0.82,
    "residual_blend": 0.05
  }
}
Setup complete.

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_scene_daynight_dqa_01.py', '--workspace-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa', '--client-limit', '1500', '--setup-only'], returncode=0)

## Run 01

Defaults:

- 3 rounds
- 6 clients
- repair-oriented stable pseudoGT
- DQA-CWA v2 aggregation
- supervised server repair after every aggregate

For a quick smoke test, set `MAX_IMAGES_PER_CLIENT = 300` and
`ROUNDS = 1`.

In [3]:
ROUNDS = 3
MAX_IMAGES_PER_CLIENT = 0
EVAL_CLIENTS = False

cmd = [
    sys.executable,
    "scripts/run_scene_daynight_dqa_01.py",
    "--workspace-root", str(WORKSPACE),
    "--client-limit", str(CLIENT_LIMIT),
    "--rounds", str(ROUNDS),
    "--batch-size", "160",
    "--workers", "8",
    "--gpus", "2",
    "--master-port", "30641",
    "--server-repair-epochs", "1",
    "--evaluate",
    "--classwise",
    "--no-eval-plots",
]
if MAX_IMAGES_PER_CLIENT > 0:
    cmd.extend(["--max-images-per-client", str(MAX_IMAGES_PER_CLIENT)])
if EVAL_CLIENTS:
    cmd.append("--eval-clients")
print(" ".join(cmd))
subprocess.run(cmd, check=True)

/root/micromamba/envs/al_yolov8/bin/python scripts/run_scene_daynight_dqa_01.py --workspace-root /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa --client-limit 1500 --rounds 3 --batch-size 160 --workers 8 --gpus 2 --master-port 30641 --server-repair-epochs 1 --evaluate --classwise --no-eval-plots
Project root: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa
Workspace: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa
Warmup: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt
{
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "dqa": {
    "num_classes": 10,
    "count_ema": 0.65,
    "quality_ema": 0.65,
    "alpha_ema": 0.4,
    "temperature": 2.5,
    "uniform_mix": 0.05,
    "classwise_blend": 0.08,
    "stability_lambda": 0.7,
    "min_effective_count": 5.0,
    "min_quality": 0.1,
    "max_quality": 1.0,
    "server_anchor": 20.0,
    "localize_bn": true,
    "min_server_alpha": 0.82,
    "residual_blend": 0.05
  }
}

=== round001: DQA scene-daynight round ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

round001 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round001 client0_highway_day: pseudo scan 250/1500 images, kept 2318 boxes
round001 client0_highway_day: pseudo scan 500/1500 images, kept 4696 boxes
round001 client0_highway_day: pseudo scan 750/1500 images, kept 7005 boxes
round001 client0_highway_day: pseudo scan 1000/1500 images, kept 9304 boxes
round001 client0_highway_day: pseudo scan 1250/1500 images, kept 11580 boxes
round001 client0_highway_day: pseudo scan 1500/1500 images, kept 13881 boxes
{
  "round": "round001",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 10812,
  "boxes_per_kept_image": 7.266129032258065,
  "mean_conf": 0.7457716877548465,
  "mean_stability": 0.9449824729243165,
  "mean_score": 0.707788491927951,
  "class_counts": {
    "0": 150,
    "2": 6247,
    "3": 76,
    "4": 413,
    "5": 9,
    "7": 600,
    "8": 3317
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_client0_highway_day_stable_boxes.csv"
}
round001 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round001 client1_highway_night: pseudo scan 250/1500 images, kept 1790 boxes
round001 client1_highway_night: pseudo scan 500/1500 images, kept 3679 boxes
round001 client1_highway_night: pseudo scan 750/1500 images, kept 5547 boxes
round001 client1_highway_night: pseudo scan 1000/1500 images, kept 7377 boxes
round001 client1_highway_night: pseudo scan 1250/1500 images, kept 9229 boxes
round001 client1_highway_night: pseudo scan 1500/1500 images, kept 11039 boxes
{
  "round": "round001",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 9263,
  "boxes_per_kept_image": 6.2757452574525745,
  "mean_conf": 0.6454818118027807,
  "mean_stability": 0.9220161875161936,
  "mean_score": 0.5989198160330051,
  "class_counts": {
    "0": 54,
    "2": 4968,
    "3": 31,
    "4": 118,
    "5": 5,
    "7": 689,
    "8": 3398
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_client1_highway_night_stable_boxes.csv"
}
round001 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round001 client2_citystreet_day: pseudo scan 250/1500 images, kept 2691 boxes
round001 client2_citystreet_day: pseudo scan 500/1500 images, kept 5390 boxes
round001 client2_citystreet_day: pseudo scan 750/1500 images, kept 8121 boxes
round001 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10875 boxes
round001 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13593 boxes
round001 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16254 boxes
{
  "round": "round001",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13789,
  "boxes_per_kept_image": 9.217245989304812,
  "mean_conf": 0.7347438888736023,
  "mean_stability": 0.9405868294681854,
  "mean_score": 0.6943373476162771,
  "class_counts": {
    "0": 1331,
    "2": 7315,
    "3": 144,
    "4": 468,
    "5": 51,
    "7": 1669,
    "8": 2811
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_client2_citystreet_day_stable_boxes.csv"
}
round001 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round001 client3_citystreet_night: pseudo scan 250/1500 images, kept 2426 boxes
round001 client3_citystreet_night: pseudo scan 500/1500 images, kept 4816 boxes
round001 client3_citystreet_night: pseudo scan 750/1500 images, kept 7166 boxes
round001 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9450 boxes
round001 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11940 boxes
round001 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14338 boxes
{
  "round": "round001",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1484,
  "pseudo_boxes_kept": 12497,
  "boxes_per_kept_image": 8.421159029649596,
  "mean_conf": 0.646182291446385,
  "mean_stability": 0.9195552923073241,
  "mean_score": 0.5980796055061397,
  "class_counts": {
    "0": 515,
    "2": 6453,
    "3": 55,
    "4": 112,
    "5": 23,
    "7": 2226,
    "8": 3113
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_client3_citystreet_night_stable_boxes.csv"
}
round001 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round001 client4_residential_day: pseudo scan 250/1500 images, kept 2559 boxes
round001 client4_residential_day: pseudo scan 500/1500 images, kept 5142 boxes
round001 client4_residential_day: pseudo scan 750/1500 images, kept 7673 boxes
round001 client4_residential_day: pseudo scan 1000/1500 images, kept 10131 boxes
round001 client4_residential_day: pseudo scan 1250/1500 images, kept 12644 boxes
round001 client4_residential_day: pseudo scan 1500/1500 images, kept 15096 boxes
{
  "round": "round001",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9829,
  "boxes_per_kept_image": 6.605510752688172,
  "mean_conf": 0.7713916716212743,
  "mean_stability": 0.9511923203937447,
  "mean_score": 0.7369318894765382,
  "class_counts": {
    "0": 360,
    "2": 6794,
    "3": 41,
    "4": 228,
    "5": 27,
    "7": 556,
    "8": 1823
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_client4_residential_day_stable_boxes.csv"
}
round001 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round001 client5_residential_night: pseudo scan 250/1500 images, kept 2393 boxes
round001 client5_residential_night: pseudo scan 500/1500 images, kept 4739 boxes
round001 client5_residential_night: pseudo scan 750/1500 images, kept 7070 boxes
round001 client5_residential_night: pseudo scan 1000/1500 images, kept 9441 boxes
round001 client5_residential_night: pseudo scan 1250/1500 images, kept 11853 boxes
round001 client5_residential_night: pseudo scan 1500/1500 images, kept 14267 boxes
{
  "round": "round001",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1486,
  "pseudo_boxes_kept": 9287,
  "boxes_per_kept_image": 6.2496635262449525,
  "mean_conf": 0.7027750300574228,
  "mean_stability": 0.9328271249491495,
  "mean_score": 0.6585657579519052,
  "class_counts": {
    "0": 115,
    "2": 6421,
    "3": 28,
    "4": 69,
    "5": 15,
    "7": 735,
    "8": 1904
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round001_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30641 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round001_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.cache' images and labels... 10001 found, 1249 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.843882544861337
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.cache' images and labels... 10001 found, 1249 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 6368.59it/s]
val: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:03:18.265824901 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:03:18.312865649 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2007       640   0.03829   0.04651  0.006387     7.295:   3%|▎         | 1/39 [00:32<20:30, 32.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1914       640   0.03919    0.0462  0.006055     7.316:   5%|▌         | 2/39 [00:33<08:38, 14.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2240       640   0.03927   0.04605  0.006186      7.32:   8%|▊         | 3/39 [00:34<04:52,  8.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1973       640   0.03882   0.04624  0.005967     7.283:  10%|█         | 4/39 [00:35<03:06,  5.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2097       640   0.03838   0.04582  0.005733     7.194:  13%|█▎        | 5/39 [00:36<02:07,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1828       640   0.03808   0.04522   0.00573     7.122:  15%|█▌        | 6/39 [00:37<01:31,  2.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1893       640    0.0377   0.04463  0.005656     7.039:  18%|█▊        | 7/39 [00:38<01:09,  2.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2178       640   0.03746   0.04448  0.005586     7.002:  21%|██        | 8/39 [00:39<00:54,  1.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2177       640    0.0374   0.04454  0.005585     7.002:  23%|██▎       | 9/39 [00:40<00:44,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1891       640   0.03737   0.04441  0.005709         7:  26%|██▌       | 10/39 [00:41<00:37,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2046       640   0.03724   0.04439  0.005675     6.985:  28%|██▊       | 11/39 [00:41<00:32,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1922       640   0.03714   0.04417  0.005656     6.958:  31%|███       | 12/39 [00:42<00:29,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1825       640   0.03692   0.04387   0.00564     6.914:  33%|███▎      | 13/39 [00:43<00:26,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2042       640   0.03681   0.04375  0.005593     6.893:  36%|███▌      | 14/39 [00:44<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2045       640   0.03685    0.0437  0.005619     6.894:  38%|███▊      | 15/39 [00:45<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1837       640   0.03679   0.04343  0.005622     6.867:  41%|████      | 16/39 [00:46<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1742       640   0.03671    0.0432  0.005626     6.843:  44%|████▎     | 17/39 [00:47<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1997       640   0.03662   0.04312  0.005615     6.829:  46%|████▌     | 18/39 [00:48<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1673       640   0.03655   0.04291  0.005621     6.806:  49%|████▊     | 19/39 [00:48<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2254       640    0.0365   0.04306  0.005613     6.814:  51%|█████▏    | 20/39 [00:49<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2071       640    0.0365   0.04305  0.005608     6.812:  54%|█████▍    | 21/39 [00:50<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1786       640   0.03648   0.04296  0.005642     6.807:  56%|█████▋    | 22/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2126       640   0.03639     0.043  0.005592     6.798:  59%|█████▉    | 23/39 [00:52<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2061       640   0.03629   0.04295  0.005572     6.785:  62%|██████▏   | 24/39 [00:53<00:13,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2155       640   0.03631   0.04298  0.005576     6.789:  64%|██████▍   | 25/39 [00:54<00:12,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2054       640   0.03625   0.04299  0.005576     6.786:  67%|██████▋   | 26/39 [00:55<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.473      0.434      0.396      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.461      0.439      0.395      0.223
                   0        738       1052      0.439      0.574       0.54      0.255
                   1        738         44      0.315      0.205      0.146     0.0632
                   2        738       8622      0.592      0.751      0.749      0.482
                   3        738        151      0.307      0.391      0.378      0.297
                   4        738        467      0.429       0.61       0.54      0.393
                   5        738         70       0.23      0.429      0.248      0.124
                   6        738         65      0.247      0.169      0.153      0.057
                   7        738       1619      0.504       0.63      0.585      0.243
                   8        738       2845      0.544      0.635      0.605      0.313
                   9        738          2          1          0   0.000268   0.000241

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client0_highway_day

1 epochs completed in 0.032 hours.
Destroying process group...
[rank0]:[W505 06:05:13.501386537 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30642 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round001_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client1_highway_night_stable_train' images and labels...9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:01<00:00, 9826.74it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29496062992126
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.cache' images and labels... 9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:05:30.372655859 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:05:30.414969042 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2011       640   0.04001    0.0454  0.006483     7.351:   2%|▎         | 1/40 [00:33<21:59, 33.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1977       640   0.04028   0.04368  0.006124     7.207:   5%|▌         | 2/40 [00:34<09:14, 14.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1708       640   0.03918   0.04231  0.005712     6.976:   8%|▊         | 3/40 [00:35<05:11,  8.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2074       640   0.03873     0.042  0.005625     6.908:  10%|█         | 4/40 [00:37<03:18,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1992       640   0.03837   0.04199  0.005619     6.878:  12%|█▎        | 5/40 [00:38<02:15,  3.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1807       640   0.03788   0.04118  0.005618     6.775:  15%|█▌        | 6/40 [00:38<01:37,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2020       640   0.03759   0.04086  0.005646     6.728:  18%|█▊        | 7/40 [00:39<01:13,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1921       640   0.03729   0.04064  0.005625     6.684:  20%|██        | 8/40 [00:40<00:57,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1956       640   0.03722    0.0405   0.00562     6.667:  22%|██▎       | 9/40 [00:41<00:46,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1950       640   0.03716   0.04045  0.005655     6.661:  25%|██▌       | 10/40 [00:42<00:39,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2026       640   0.03705   0.04058  0.005595     6.659:  28%|██▊       | 11/40 [00:43<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1907       640   0.03694   0.04033  0.005568     6.628:  30%|███       | 12/40 [00:44<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1850       640   0.03688   0.04002  0.005617     6.601:  32%|███▎      | 13/40 [00:45<00:27,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1864       640   0.03676   0.03973  0.005629      6.57:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1872       640   0.03668   0.03954  0.005674     6.551:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2017       640   0.03657   0.03958  0.005682     6.546:  40%|████      | 16/40 [00:47<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1696       640   0.03653   0.03928  0.005656     6.517:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1982       640   0.03641   0.03922  0.005683     6.505:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1652       640   0.03638   0.03898    0.0057     6.484:  48%|████▊     | 19/40 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1969       640    0.0363   0.03888  0.005684     6.468:  50%|█████     | 20/40 [00:51<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2002       640   0.03631   0.03884  0.005691     6.467:  52%|█████▎    | 21/40 [00:52<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2166       640   0.03625   0.03887  0.005659     6.463:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2059       640    0.0362   0.03895  0.005647     6.464:  57%|█████▊    | 23/40 [00:53<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1663       640   0.03618   0.03877  0.005656     6.448:  60%|██████    | 24/40 [00:54<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1978       640   0.03611   0.03869   0.00565     6.436:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1860       640   0.03604   0.03855  0.005643     6.418:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.45      0.452       0.39      0.218
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.465      0.426       0.39      0.219
                   0        738       1052      0.448      0.578      0.535      0.252
                   1        738         44      0.349      0.159      0.149     0.0588
                   2        738       8622       0.58      0.748      0.745      0.479
                   3        738        151      0.317      0.384      0.366      0.287
                   4        738        467      0.425      0.607      0.535       0.39
                   5        738         70      0.233      0.371      0.234      0.115
                   6        738         65       0.28      0.154      0.163     0.0634
                   7        738       1619      0.491      0.627      0.575      0.239
                   8        738       2845      0.529      0.627      0.596      0.306
                   9        738          2          1          0   0.000225   0.000225

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client1_highway_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:07:29.660585279 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30643 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round001_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train' images and labels...9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:01<00:00, 8299.70it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:07:47.452394399 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:07:47.544672776 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2061       640   0.03962   0.05109  0.006093     7.744:   3%|▎         | 1/39 [00:33<21:30, 33.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2096       640    0.0392   0.05122  0.006262     7.735:   5%|▌         | 2/39 [00:35<09:02, 14.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1974       640   0.03893    0.0503  0.006232     7.637:   8%|▊         | 3/39 [00:36<05:07,  8.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2004       640   0.03891   0.04916  0.006058      7.53:  10%|█         | 4/39 [00:37<03:17,  5.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2113       640   0.03858   0.04896  0.005886     7.474:  13%|█▎        | 5/39 [00:38<02:14,  3.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1782       640   0.03793   0.04803  0.005887     7.348:  15%|█▌        | 6/39 [00:39<01:36,  2.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1994       640   0.03772   0.04786  0.005958     7.323:  18%|█▊        | 7/39 [00:40<01:12,  2.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1873       640   0.03741   0.04746  0.005897     7.261:  21%|██        | 8/39 [00:41<00:56,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2042       640   0.03734   0.04736  0.005821     7.242:  23%|██▎       | 9/39 [00:42<00:45,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1802       640   0.03709    0.0472  0.005814     7.208:  26%|██▌       | 10/39 [00:42<00:38,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1993       640   0.03706     0.047  0.005814      7.19:  28%|██▊       | 11/39 [00:43<00:33,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1880       640   0.03704   0.04667   0.00581     7.161:  31%|███       | 12/39 [00:44<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2059       640   0.03703   0.04649  0.005748     7.141:  33%|███▎      | 13/39 [00:45<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2123       640   0.03703   0.04656  0.005711     7.144:  36%|███▌      | 14/39 [00:46<00:24,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1955       640   0.03697   0.04644  0.005687     7.128:  38%|███▊      | 15/39 [00:47<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1905       640    0.0368   0.04614  0.005683      7.09:  41%|████      | 16/39 [00:48<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1487       640   0.03668   0.04584  0.005709     7.058:  44%|████▎     | 17/39 [00:49<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1933       640   0.03654   0.04571  0.005687     7.035:  46%|████▌     | 18/39 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1723       640   0.03651   0.04542  0.005662     7.007:  49%|████▊     | 19/39 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2087       640    0.0364   0.04548  0.005638     7.001:  51%|█████▏    | 20/39 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1847       640   0.03628   0.04527  0.005617     6.973:  54%|█████▍    | 21/39 [00:52<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1766       640    0.0362   0.04519  0.005607      6.96:  56%|█████▋    | 22/39 [00:53<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1791       640    0.0361   0.04501  0.005594     6.936:  59%|█████▉    | 23/39 [00:54<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1874       640   0.03603   0.04492  0.005581     6.923:  62%|██████▏   | 24/39 [00:55<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1747       640   0.03594   0.04483  0.005563     6.907:  64%|██████▍   | 25/39 [00:56<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2013       640   0.03585   0.04477  0.005549     6.893:  67%|██████▋   | 26/39 [00:57<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.537      0.399      0.399      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.527      0.406        0.4      0.225
                   0        738       1052       0.62       0.53      0.545      0.256
                   1        738         44      0.479      0.159      0.166     0.0651
                   2        738       8622      0.621      0.742      0.752      0.482
                   3        738        151       0.34      0.364       0.37      0.295
                   4        738        467      0.461      0.587       0.54      0.392
                   5        738         70      0.269      0.371      0.262      0.134
                   6        738         65      0.351     0.0769      0.179     0.0675
                   7        738       1619      0.544       0.61      0.579      0.241
                   8        738       2845      0.586      0.617      0.603      0.315
                   9        738          2          1          0   0.000259   0.000233

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client2_citystreet_day

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:09:46.841879842 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30644 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round001_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train' images and labels...9763 found, 1483 missing, 0 empty, 0 corrupted: 100%|██████████| 11246/11246 [00:01<00:00, 10403.85it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.261313639220615
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.cache' images and labels... 9763 found, 1483 missing, 0 empty, 0 corrupted: 100%|██████████| 11246/11246 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:10:04.390985251 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:10:04.396705660 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      1823       640   0.03895   0.04437    0.0053     7.089:   2%|▎         | 1/40 [00:33<21:40, 33.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1963       640   0.03872   0.04614  0.005328     7.215:   5%|▌         | 2/40 [00:34<09:11, 14.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1880       640    0.0391   0.04562   0.00529     7.201:   8%|▊         | 3/40 [00:35<05:10,  8.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2068       640   0.03887   0.04496  0.005393     7.138:  10%|█         | 4/40 [00:36<03:18,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2042       640   0.03856    0.0447  0.005415     7.094:  12%|█▎        | 5/40 [00:37<02:14,  3.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1893       640   0.03848   0.04407  0.005561     7.049:  15%|█▌        | 6/40 [00:38<01:36,  2.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1921       640   0.03798   0.04361  0.005554     6.971:  18%|█▊        | 7/40 [00:39<01:12,  2.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2009       640   0.03775   0.04357  0.005481     6.944:  20%|██        | 8/40 [00:40<00:57,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2080       640   0.03751   0.04366  0.005464     6.931:  22%|██▎       | 9/40 [00:41<00:46,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1704       640   0.03735   0.04327  0.005586     6.896:  25%|██▌       | 10/40 [00:42<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2025       640   0.03729   0.04316  0.005617     6.885:  28%|██▊       | 11/40 [00:43<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1687       640   0.03712   0.04273  0.005602     6.836:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2028       640   0.03705   0.04261  0.005604     6.821:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2011       640   0.03699   0.04247  0.005602     6.804:  35%|███▌      | 14/40 [00:45<00:25,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1879       640   0.03692   0.04243  0.005658     6.801:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2014       640   0.03695   0.04225  0.005658     6.789:  40%|████      | 16/40 [00:47<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1656       640   0.03687   0.04187   0.00568     6.754:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2124       640   0.03682   0.04176  0.005665      6.74:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1755       640   0.03685   0.04151  0.005679     6.723:  48%|████▊     | 19/40 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2122       640   0.03678    0.0415  0.005651     6.714:  50%|█████     | 20/40 [00:51<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2030       640   0.03679   0.04139  0.005668     6.708:  52%|█████▎    | 21/40 [00:51<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1941       640   0.03678   0.04132  0.005664     6.701:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1881       640   0.03671   0.04112  0.005664      6.68:  57%|█████▊    | 23/40 [00:53<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2078       640   0.03669   0.04108  0.005664     6.675:  60%|██████    | 24/40 [00:54<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1937       640   0.03667   0.04094   0.00565     6.661:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1918       640   0.03661   0.04082  0.005629     6.645:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.485      0.424      0.389      0.216
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.469      0.427      0.387      0.217
                   0        738       1052      0.507      0.536      0.526      0.246
                   1        738         44      0.311      0.136       0.13     0.0556
                   2        738       8622      0.585      0.743      0.741       0.47
                   3        738        151      0.294      0.391      0.373      0.289
                   4        738        467      0.397      0.619      0.532      0.384
                   5        738         70      0.249      0.429      0.249       0.12
                   6        738         65      0.304      0.169      0.149      0.058
                   7        738       1619      0.501      0.631      0.578      0.238
                   8        738       2845       0.54      0.615      0.587      0.308
                   9        738          2          1          0   0.000194   0.000194

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client3_citystreet_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:12:04.533184246 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30645 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round001_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client4_residential_day_stable_train' images and labels...9921 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:01<00:00, 9582.28it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.cache' images and labels... 9921 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 11250/11250 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:12:21.937708691 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:12:21.033490974 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2090       640   0.03885    0.0501  0.005952     7.592:   3%|▎         | 1/39 [00:33<21:01, 33.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2144       640   0.03871   0.05003  0.005966     7.576:   5%|▌         | 2/39 [00:34<08:54, 14.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1953       640   0.03861   0.04923  0.005828     7.493:   8%|▊         | 3/39 [00:35<05:01,  8.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2117       640   0.03846   0.04864  0.005948     7.444:  10%|█         | 4/39 [00:36<03:12,  5.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2267       640   0.03822   0.04847  0.005805       7.4:  13%|█▎        | 5/39 [00:37<02:11,  3.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1698       640   0.03769   0.04688  0.005756     7.226:  15%|█▌        | 6/39 [00:38<01:34,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2021       640   0.03764   0.04683  0.005806     7.222:  18%|█▊        | 7/39 [00:39<01:10,  2.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2155       640   0.03747   0.04652  0.005783     7.182:  21%|██        | 8/39 [00:40<00:55,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2153       640   0.03728   0.04661   0.00569     7.167:  23%|██▎       | 9/39 [00:41<00:45,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1848       640   0.03713   0.04638  0.005679     7.135:  26%|██▌       | 10/39 [00:42<00:38,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1852       640   0.03701   0.04588  0.005676     7.085:  28%|██▊       | 11/39 [00:43<00:33,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2037       640   0.03692    0.0456  0.005697     7.057:  31%|███       | 12/39 [00:43<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2121       640   0.03695    0.0457  0.005636     7.063:  33%|███▎      | 13/39 [00:44<00:26,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1844       640   0.03681   0.04535  0.005588     7.019:  36%|███▌      | 14/39 [00:45<00:24,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1945       640   0.03675    0.0452  0.005592     7.003:  38%|███▊      | 15/39 [00:46<00:23,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2079       640    0.0367   0.04503  0.005616     6.988:  41%|████      | 16/39 [00:47<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2008       640   0.03668   0.04501  0.005637     6.986:  44%|████▎     | 17/39 [00:48<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1983       640   0.03657   0.04494  0.005605     6.969:  46%|████▌     | 18/39 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1846       640   0.03647   0.04467  0.005546     6.935:  49%|████▊     | 19/39 [00:50<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2068       640   0.03638   0.04462  0.005539     6.923:  51%|█████▏    | 20/39 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1890       640   0.03629    0.0445  0.005526     6.905:  54%|█████▍    | 21/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2102       640   0.03626    0.0446  0.005516      6.91:  56%|█████▋    | 22/39 [00:52<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1913       640   0.03622   0.04452  0.005527     6.902:  59%|█████▉    | 23/39 [00:53<00:13,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2044       640   0.03614   0.04453  0.005513     6.895:  62%|██████▏   | 24/39 [00:54<00:13,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1974       640   0.03612   0.04444  0.005492     6.884:  64%|██████▍   | 25/39 [00:55<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2081       640   0.03608   0.04438   0.00551     6.877:  67%|██████▋   | 26/39 [00:56<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53       0.41      0.403      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]

                 all        738      14937      0.503      0.408      0.398      0.223
                   0        738       1052      0.526      0.543      0.537      0.255
                   1        738         44      0.409      0.136      0.151     0.0621
                   2        738       8622      0.651      0.731      0.748      0.479
                   3        738        151      0.368      0.377      0.382      0.292
                   4        738        467      0.458      0.593      0.548      0.396
                   5        738         70      0.242        0.4      0.255      0.125
                   6        738         65      0.243     0.0743      0.165     0.0614
                   7        738       1619      0.536      0.615      0.584      0.244
                   8        738       2845      0.595      0.614      0.605      0.314
                   9        738          2          1          0   0.000238   0.000214

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client4_residential_day

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:14:21.392455522 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30646 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round001_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client5_residential_night_stable_train' images and labels...9764 found, 1484 missing, 0 empty, 0 corrupted: 100%|██████████| 11248/11248 [00:01<00:00, 10456.78it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.258915946582874
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.cache' images and labels... 9764 found, 1484 missing, 0 empty, 0 corrupted: 100%|██████████| 11248/11248 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:14:38.120103677 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:14:38.130305875 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.43G      2144       640   0.03917   0.04362  0.005932     7.098:   2%|▎         | 1/40 [00:33<22:00, 33.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      1761       640   0.03858   0.04313  0.005864     7.006:   5%|▌         | 2/40 [00:35<09:20, 14.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1973       640   0.03846   0.04366  0.005621     7.019:   8%|▊         | 3/40 [00:36<05:17,  8.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1984       640   0.03815   0.04366  0.005413     6.978:  10%|█         | 4/40 [00:37<03:22,  5.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1953       640   0.03759   0.04358  0.005368     6.922:  12%|█▎        | 5/40 [00:38<02:16,  3.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1797       640   0.03748   0.04307  0.005386     6.875:  15%|█▌        | 6/40 [00:39<01:38,  2.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2171       640   0.03751   0.04341  0.005439     6.909:  18%|█▊        | 7/40 [00:40<01:13,  2.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2026       640   0.03748    0.0433  0.005463       6.9:  20%|██        | 8/40 [00:41<00:57,  1.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1993       640   0.03722   0.04307  0.005439     6.858:  22%|██▎       | 9/40 [00:42<00:47,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1917       640   0.03697   0.04294  0.005473     6.831:  25%|██▌       | 10/40 [00:42<00:39,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2020       640   0.03692    0.0426  0.005456     6.798:  28%|██▊       | 11/40 [00:43<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1814       640   0.03685    0.0424  0.005452     6.776:  30%|███       | 12/40 [00:44<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1950       640   0.03675   0.04226  0.005449     6.757:  32%|███▎      | 13/40 [00:45<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2051       640   0.03669   0.04225   0.00544      6.75:  35%|███▌      | 14/40 [00:46<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1935       640   0.03655    0.0421  0.005446     6.728:  38%|███▊      | 15/40 [00:47<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1866       640    0.0365   0.04193  0.005454      6.71:  40%|████      | 16/40 [00:48<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1835       640   0.03647   0.04171  0.005442      6.69:  42%|████▎     | 17/40 [00:49<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2002       640   0.03648   0.04162  0.005471     6.686:  45%|████▌     | 18/40 [00:49<00:19,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1711       640   0.03642   0.04126  0.005481     6.653:  48%|████▊     | 19/40 [00:50<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2085       640    0.0364   0.04114  0.005488     6.642:  50%|█████     | 20/40 [00:51<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1919       640   0.03644   0.04091  0.005523     6.631:  52%|█████▎    | 21/40 [00:52<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1959       640   0.03642   0.04078  0.005495     6.615:  55%|█████▌    | 22/40 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1778       640   0.03637   0.04065  0.005496     6.601:  57%|█████▊    | 23/40 [00:54<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1973       640    0.0363   0.04051  0.005529     6.587:  60%|██████    | 24/40 [00:55<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2052       640   0.03627   0.04041  0.005527     6.576:  62%|██████▎   | 25/40 [00:56<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      1924       640   0.03624   0.04025  0.005518     6.561:  65%|██████▌   | 26/40 [00:56<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.48      0.423      0.392      0.218
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.497      0.407       0.39      0.218
                   0        738       1052      0.503      0.541      0.527      0.249
                   1        738         44      0.443      0.136      0.143     0.0557
                   2        738       8622      0.611      0.736      0.743      0.473
                   3        738        151      0.333      0.351      0.377      0.294
                   4        738        467      0.439      0.602      0.542       0.39
                   5        738         70      0.248      0.386      0.245      0.113
                   6        738         65      0.284     0.0923      0.147     0.0593
                   7        738       1619      0.535      0.618      0.584       0.24
                   8        738       2845       0.57      0.612      0.596       0.31
                   9        738          2          1          0   0.000193   0.000154

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_client5_residential_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:16:39.609811664 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30647 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round001_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round001_dqa_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 14990.67it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:16:57.766260726 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:16:57.770331724 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03851   0.04572   0.00573     7.197:   3%|▎         | 1/31 [00:32<16:25, 32.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2744       640   0.03902   0.04672  0.005945     7.335:   6%|▋         | 2/31 [00:33<06:45, 13.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03855   0.04578  0.005901     7.218:  10%|▉         | 3/31 [00:34<03:42,  7.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03788    0.0441  0.005696     7.014:  13%|█▎        | 4/31 [00:35<02:17,  5.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.03756   0.04424  0.005707         7:  16%|█▌        | 5/31 [00:35<01:30,  3.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03747   0.04418  0.005763     6.993:  19%|█▉        | 6/31 [00:36<01:02,  2.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.03742   0.04383  0.005827     6.966:  23%|██▎       | 7/31 [00:36<00:44,  1.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.03724    0.0439  0.005859      6.96:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.03716    0.0438  0.005766     6.938:  29%|██▉       | 9/31 [00:38<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.03701   0.04388  0.005737      6.93:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.03688   0.04387  0.005743     6.919:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.03668   0.04355  0.005716     6.876:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.03657   0.04358  0.005656     6.865:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640    0.0365   0.04333  0.005612     6.835:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.03646   0.04321  0.005638     6.825:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.03638   0.04303  0.005616     6.802:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.03635   0.04304  0.005567     6.796:  55%|█████▍    | 17/31 [00:42<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03633   0.04304  0.005519     6.791:  58%|█████▊    | 18/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640    0.0362   0.04286  0.005472     6.762:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03613   0.04305  0.005471     6.772:  65%|██████▍   | 20/31 [00:44<00:06,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03611   0.04303  0.005479     6.769:  68%|██████▊   | 21/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03605   0.04311  0.005436     6.768:  71%|███████   | 22/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03599    0.0431   0.00542     6.761:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03596   0.04314  0.005394     6.759:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03591   0.04304  0.005392     6.748:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03592   0.04304   0.00538     6.747:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.459      0.456        0.4      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.469      0.439      0.399      0.224
                   0        738       1052      0.456      0.575      0.543      0.255
                   1        738         44      0.327      0.159      0.153      0.058
                   2        738       8622      0.576      0.759      0.751      0.484
                   3        738        151      0.327      0.396      0.372      0.287
                   4        738        467      0.445      0.596      0.547      0.398
                   5        738         70       0.25      0.443      0.274       0.13
                   6        738         65      0.284      0.185       0.16     0.0626
                   7        738       1619      0.509       0.63      0.579       0.24
                   8        738       2845      0.518      0.652      0.613       0.32
                   9        738          2          1          0   0.000306   0.000276

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round001_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 06:18:37.389631033 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

=== round002: DQA scene-daynight round ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round002 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round002 client0_highway_day: pseudo scan 250/1500 images, kept 2364 boxes
round002 client0_highway_day: pseudo scan 500/1500 images, kept 4799 boxes
round002 client0_highway_day: pseudo scan 750/1500 images, kept 7146 boxes
round002 client0_highway_day: pseudo scan 1000/1500 images, kept 9502 boxes
round002 client0_highway_day: pseudo scan 1250/1500 images, kept 11828 boxes
round002 client0_highway_day: pseudo scan 1500/1500 images, kept 14196 boxes
{
  "round": "round002",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1492,
  "pseudo_boxes_kept": 11050,
  "boxes_per_kept_image": 7.406166219839142,
  "mean_conf": 0.7784627227033425,
  "mean_stability": 0.9527668127323168,
  "mean_score": 0.7448289262072173,
  "class_counts": {
    "0": 152,
    "2": 6389,
    "3": 84,
    "4": 489,
    "5": 6,
    "7": 566,
    "8": 3364
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_client0_highway_day_stable_boxes.csv"
}
round002 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round002 client1_highway_night: pseudo scan 250/1500 images, kept 1776 boxes
round002 client1_highway_night: pseudo scan 500/1500 images, kept 3660 boxes
round002 client1_highway_night: pseudo scan 750/1500 images, kept 5523 boxes
round002 client1_highway_night: pseudo scan 1000/1500 images, kept 7328 boxes
round002 client1_highway_night: pseudo scan 1250/1500 images, kept 9160 boxes
round002 client1_highway_night: pseudo scan 1500/1500 images, kept 10974 boxes
{
  "round": "round002",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 8986,
  "boxes_per_kept_image": 6.088075880758808,
  "mean_conf": 0.682560352149637,
  "mean_stability": 0.9336198167375858,
  "mean_score": 0.641235466276727,
  "class_counts": {
    "0": 60,
    "2": 4939,
    "3": 26,
    "4": 142,
    "5": 6,
    "7": 577,
    "8": 3236
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_client1_highway_night_stable_boxes.csv"
}
round002 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round002 client2_citystreet_day: pseudo scan 250/1500 images, kept 2698 boxes
round002 client2_citystreet_day: pseudo scan 500/1500 images, kept 5416 boxes
round002 client2_citystreet_day: pseudo scan 750/1500 images, kept 8150 boxes
round002 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10911 boxes
round002 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13627 boxes
round002 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16283 boxes
{
  "round": "round002",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13700,
  "boxes_per_kept_image": 9.157754010695188,
  "mean_conf": 0.7724611783680254,
  "mean_stability": 0.9502816717119983,
  "mean_score": 0.7373599356019598,
  "class_counts": {
    "0": 1403,
    "2": 7328,
    "3": 150,
    "4": 563,
    "5": 49,
    "7": 1551,
    "8": 2656
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_client2_citystreet_day_stable_boxes.csv"
}
round002 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round002 client3_citystreet_night: pseudo scan 250/1500 images, kept 2446 boxes
round002 client3_citystreet_night: pseudo scan 500/1500 images, kept 4855 boxes
round002 client3_citystreet_night: pseudo scan 750/1500 images, kept 7237 boxes
round002 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9569 boxes
round002 client3_citystreet_night: pseudo scan 1250/1500 images, kept 12048 boxes
round002 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14452 boxes
{
  "round": "round002",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1480,
  "pseudo_boxes_kept": 12154,
  "boxes_per_kept_image": 8.212162162162162,
  "mean_conf": 0.6875158183415194,
  "mean_stability": 0.932471315008805,
  "mean_score": 0.645154727342809,
  "class_counts": {
    "0": 525,
    "2": 6504,
    "3": 54,
    "4": 151,
    "5": 23,
    "7": 1955,
    "8": 2942
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_client3_citystreet_night_stable_boxes.csv"
}
round002 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round002 client4_residential_day: pseudo scan 250/1500 images, kept 2575 boxes
round002 client4_residential_day: pseudo scan 500/1500 images, kept 5165 boxes
round002 client4_residential_day: pseudo scan 750/1500 images, kept 7721 boxes
round002 client4_residential_day: pseudo scan 1000/1500 images, kept 10190 boxes
round002 client4_residential_day: pseudo scan 1250/1500 images, kept 12720 boxes
round002 client4_residential_day: pseudo scan 1500/1500 images, kept 15207 boxes
{
  "round": "round002",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9893,
  "boxes_per_kept_image": 6.63514419852448,
  "mean_conf": 0.8118786173246151,
  "mean_stability": 0.9588962718400075,
  "mean_score": 0.781690528792611,
  "class_counts": {
    "0": 369,
    "2": 6844,
    "3": 39,
    "4": 293,
    "5": 29,
    "7": 540,
    "8": 1779
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_client4_residential_day_stable_boxes.csv"
}
round002 client5_residential_night: pseudo scan 1/1500 images, kept 11 boxes
round002 client5_residential_night: pseudo scan 250/1500 images, kept 2430 boxes
round002 client5_residential_night: pseudo scan 500/1500 images, kept 4799 boxes
round002 client5_residential_night: pseudo scan 750/1500 images, kept 7169 boxes
round002 client5_residential_night: pseudo scan 1000/1500 images, kept 9603 boxes
round002 client5_residential_night: pseudo scan 1250/1500 images, kept 12030 boxes
round002 client5_residential_night: pseudo scan 1500/1500 images, kept 14482 boxes
{
  "round": "round002",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 9069,
  "boxes_per_kept_image": 6.12356515867657,
  "mean_conf": 0.7631528865957171,
  "mean_stability": 0.9454047096605035,
  "mean_score": 0.7243069082632272,
  "class_counts": {
    "0": 125,
    "2": 6517,
    "3": 26,
    "4": 95,
    "5": 14,
    "7": 629,
    "8": 1663
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round002_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30648 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round002_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client0_highway_day_stable_train' images and labels...10002 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 11254/11254 [00:00<00:00, 12315.07it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.cache' images and labels... 10002 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 11254/11254 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:20:53.148313095 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:20:53.161784824 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2076       640   0.03639   0.04427  0.005217     6.871:   3%|▎         | 1/39 [00:32<20:26, 32.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1843       640    0.0355   0.04195   0.00488     6.587:   5%|▌         | 2/39 [00:33<08:40, 14.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1952       640   0.03561   0.04251   0.00503     6.652:   8%|▊         | 3/39 [00:34<04:55,  8.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1955       640   0.03577   0.04308  0.005176     6.722:  10%|█         | 4/39 [00:35<03:08,  5.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1961       640   0.03542   0.04317  0.005107     6.696:  13%|█▎        | 5/39 [00:36<02:08,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1579       640   0.03495   0.04218  0.005006     6.571:  15%|█▌        | 6/39 [00:37<01:32,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2046       640   0.03495   0.04203  0.005012      6.56:  18%|█▊        | 7/39 [00:38<01:09,  2.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2018       640   0.03501     0.042  0.005069     6.566:  21%|██        | 8/39 [00:39<00:54,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03514   0.04226  0.005111       6.6:  23%|██▎       | 9/39 [00:40<00:44,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2199       640   0.03524   0.04269  0.005114     6.644:  26%|██▌       | 10/39 [00:41<00:37,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640   0.03521   0.04254  0.005128      6.63:  28%|██▊       | 11/39 [00:42<00:33,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2077       640   0.03512   0.04261  0.005213     6.636:  31%|███       | 12/39 [00:43<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1786       640   0.03495   0.04237  0.005219     6.603:  33%|███▎      | 13/39 [00:43<00:26,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2260       640   0.03495   0.04263  0.005177     6.621:  36%|███▌      | 14/39 [00:44<00:24,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640   0.03496   0.04261  0.005157     6.618:  38%|███▊      | 15/39 [00:45<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1971       640   0.03496   0.04254   0.00513      6.61:  41%|████      | 16/39 [00:46<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1887       640   0.03497   0.04248  0.005164      6.61:  44%|████▎     | 17/39 [00:47<00:20,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1927       640   0.03497   0.04231  0.005177     6.597:  46%|████▌     | 18/39 [00:48<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1758       640   0.03488   0.04213  0.005164     6.573:  49%|████▊     | 19/39 [00:49<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2261       640   0.03486   0.04226  0.005198     6.585:  51%|█████▏    | 20/39 [00:50<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1874       640   0.03481   0.04229  0.005198     6.583:  54%|█████▍    | 21/39 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1896       640    0.0348   0.04219  0.005193     6.575:  56%|█████▋    | 22/39 [00:51<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1981       640   0.03477   0.04208  0.005164     6.561:  59%|█████▉    | 23/39 [00:52<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1979       640   0.03477    0.0421  0.005159     6.562:  62%|██████▏   | 24/39 [00:53<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2120       640   0.03475   0.04206  0.005156     6.558:  64%|██████▍   | 25/39 [00:54<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640   0.03475   0.04199  0.005151     6.551:  67%|██████▋   | 26/39 [00:55<00:11,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.481      0.451      0.405      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.466      0.454      0.402      0.227
                   0        738       1052      0.419      0.586      0.541       0.26
                   1        738         44      0.298      0.205      0.155     0.0614
                   2        738       8622      0.601      0.753      0.751      0.484
                   3        738        151      0.314      0.424      0.397      0.308
                   4        738        467      0.429      0.617      0.555      0.403
                   5        738         70      0.234      0.442      0.262      0.139
                   6        738         65      0.285      0.246      0.158      0.057
                   7        738       1619      0.505      0.647      0.596      0.245
                   8        738       2845       0.57      0.624      0.607      0.316
                   9        738          2          1          0    0.00028   0.000252

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client0_highway_day

1 epochs completed in 0.032 hours.
Destroying process group...
[rank0]:[W505 06:22:47.525532638 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30649 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round002_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client1_highway_night_stable_train' images and labels...9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:00<00:00, 11965.72it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29496062992126
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.cache' images and labels... 9769 found, 1469 missing, 0 empty, 0 corrupted: 100%|██████████| 11238/11238 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:23:04.347497942 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:23:04.394320539 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1990       640   0.03648    0.0438  0.005406     6.855:   2%|▎         | 1/40 [00:33<21:52, 33.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1813       640   0.03599   0.04094  0.005369     6.585:   5%|▌         | 2/40 [00:34<09:12, 14.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1804       640   0.03513   0.03983  0.005066     6.402:   8%|▊         | 3/40 [00:35<05:12,  8.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2114       640   0.03486   0.04024  0.004999     6.408:  10%|█         | 4/40 [00:37<03:20,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03495    0.0402  0.005041     6.415:  12%|█▎        | 5/40 [00:38<02:16,  3.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1857       640   0.03478   0.03963  0.005089      6.36:  15%|█▌        | 6/40 [00:38<01:37,  2.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03476   0.03909  0.005098     6.316:  18%|█▊        | 7/40 [00:39<01:13,  2.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1964       640   0.03461   0.03892  0.005058     6.287:  20%|██        | 8/40 [00:40<00:58,  1.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1837       640   0.03463   0.03873  0.005037     6.272:  22%|██▎       | 9/40 [00:41<00:47,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1838       640   0.03465   0.03863  0.005054     6.266:  25%|██▌       | 10/40 [00:42<00:40,  1.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1926       640   0.03467   0.03855  0.005024     6.259:  28%|██▊       | 11/40 [00:43<00:34,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640   0.03461   0.03841  0.004986     6.241:  30%|███       | 12/40 [00:44<00:30,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1910       640   0.03468   0.03824  0.005049     6.237:  32%|███▎      | 13/40 [00:45<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1828       640   0.03468    0.0381  0.005067     6.228:  35%|███▌      | 14/40 [00:46<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1827       640   0.03471   0.03796   0.00511     6.222:  38%|███▊      | 15/40 [00:47<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1842       640   0.03467   0.03787  0.005108     6.212:  40%|████      | 16/40 [00:47<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1999       640   0.03472   0.03777  0.005081     6.206:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1846       640   0.03467   0.03778  0.005118     6.205:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1617       640   0.03466   0.03754  0.005129     6.186:  48%|████▊     | 19/40 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1958       640   0.03465   0.03747  0.005118     6.179:  50%|█████     | 20/40 [00:51<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2008       640   0.03469   0.03744  0.005108     6.179:  52%|█████▎    | 21/40 [00:52<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2150       640   0.03468   0.03748  0.005083      6.18:  55%|█████▌    | 22/40 [00:53<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2056       640   0.03466   0.03752  0.005076     6.181:  57%|█████▊    | 23/40 [00:54<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1606       640   0.03464   0.03736  0.005106     6.168:  60%|██████    | 24/40 [00:55<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1881       640   0.03459   0.03729  0.005117      6.16:  62%|██████▎   | 25/40 [00:55<00:13,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1917       640   0.03459   0.03719   0.00512     6.153:  65%|██████▌   | 26/40 [00:56<00:12,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.465      0.452      0.401      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.545       0.39        0.4      0.225
                   0        738       1052      0.547      0.548      0.542      0.256
                   1        738         44      0.567     0.0909      0.163     0.0617
                   2        738       8622      0.667      0.723      0.747      0.481
                   3        738        151      0.441      0.351        0.4      0.307
                   4        738        467      0.476      0.585      0.544      0.398
                   5        738         70      0.274       0.35      0.237      0.127
                   6        738         65       0.27     0.0615      0.169     0.0685
                   7        738       1619      0.562      0.606       0.59      0.243
                   8        738       2845      0.646      0.587      0.605       0.31
                   9        738          2          1          0   0.000239   0.000215

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client1_highway_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:25:03.418295951 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30650 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round002_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train' images and labels...9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:01<00:00, 9809.78it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:25:20.752882665 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:25:20.784696626 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2066       640    0.0361   0.05077   0.00533     7.375:   3%|▎         | 1/39 [00:33<21:16, 33.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2187       640    0.0356   0.05045   0.00561     7.333:   5%|▌         | 2/39 [00:34<08:59, 14.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1974       640   0.03527   0.04972  0.005632      7.25:   8%|▊         | 3/39 [00:36<05:04,  8.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640   0.03538   0.04893  0.005532     7.188:  10%|█         | 4/39 [00:37<03:13,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2145       640   0.03531    0.0484  0.005414      7.13:  13%|█▎        | 5/39 [00:38<02:11,  3.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1780       640    0.0349   0.04739  0.005365     7.012:  15%|█▌        | 6/39 [00:38<01:34,  2.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1960       640   0.03498   0.04723  0.005443     7.012:  18%|█▊        | 7/39 [00:39<01:11,  2.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1897       640   0.03485   0.04684  0.005386     6.967:  21%|██        | 8/39 [00:40<00:56,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2025       640   0.03498   0.04687  0.005323     6.974:  23%|██▎       | 9/39 [00:41<00:46,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1808       640   0.03481   0.04659  0.005305     6.937:  26%|██▌       | 10/39 [00:42<00:39,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1991       640   0.03483    0.0465  0.005309     6.932:  28%|██▊       | 11/39 [00:43<00:34,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1792       640   0.03487   0.04604  0.005319     6.898:  31%|███       | 12/39 [00:44<00:30,  1.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03494    0.0459  0.005277     6.889:  33%|███▎      | 13/39 [00:45<00:27,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03504   0.04594  0.005247     6.898:  36%|███▌      | 14/39 [00:46<00:25,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1930       640   0.03504   0.04581  0.005224     6.886:  38%|███▊      | 15/39 [00:47<00:23,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1894       640   0.03493    0.0455  0.005219     6.853:  41%|████      | 16/39 [00:48<00:21,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1504       640   0.03485   0.04526  0.005246     6.829:  44%|████▎     | 17/39 [00:48<00:20,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1920       640   0.03477   0.04519  0.005233     6.815:  46%|████▌     | 18/39 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1718       640   0.03478   0.04489  0.005208      6.79:  49%|████▊     | 19/39 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03472   0.04489  0.005191     6.784:  51%|█████▏    | 20/39 [00:51<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1849       640   0.03465   0.04472  0.005174     6.763:  54%|█████▍    | 21/39 [00:52<00:16,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1707       640    0.0346   0.04463  0.005162     6.752:  56%|█████▋    | 22/39 [00:53<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03453   0.04451  0.005161     6.736:  59%|█████▉    | 23/39 [00:54<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1900       640    0.0345   0.04445  0.005154     6.728:  62%|██████▏   | 24/39 [00:55<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1848       640   0.03445   0.04434  0.005148     6.716:  64%|██████▍   | 25/39 [00:56<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640   0.03439   0.04432  0.005137     6.708:  67%|██████▋   | 26/39 [00:56<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.445      0.488      0.406      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]

                 all        738      14937      0.531      0.399      0.406      0.229
                   0        738       1052      0.643      0.518      0.544      0.257
                   1        738         44      0.381      0.114      0.168      0.073
                   2        738       8622      0.644      0.742      0.756      0.485
                   3        738        151      0.381      0.384      0.399      0.306
                   4        738        467       0.48      0.589       0.55      0.399
                   5        738         70      0.286      0.357      0.262      0.134
                   6        738         65      0.312     0.0769      0.183     0.0715
                   7        738       1619      0.566      0.609      0.588      0.245
                   8        738       2845      0.617      0.602      0.605      0.319
                   9        738          2          1          0   0.000269   0.000242

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client2_citystreet_day

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:27:20.058432474 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30651 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round002_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train' images and labels...9763 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11242/11242 [00:01<00:00, 9258.93it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.cache' images and labels... 9763 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11242/11242 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:27:38.683970748 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:27:38.693487088 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1819       640   0.03577   0.04475  0.005092     6.849:   2%|▎         | 1/40 [00:32<21:17, 32.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1854       640   0.03615   0.04562   0.00524     6.961:   5%|▌         | 2/40 [00:33<08:57, 14.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1942       640   0.03557   0.04475  0.005424     6.859:   8%|▊         | 3/40 [00:34<05:02,  8.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1921       640   0.03529   0.04392  0.005176     6.751:  10%|█         | 4/40 [00:36<03:13,  5.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1799       640   0.03503   0.04308  0.005077     6.654:  12%|█▎        | 5/40 [00:36<02:11,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1818       640   0.03509   0.04255  0.004969     6.608:  15%|█▌        | 6/40 [00:37<01:34,  2.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1927       640   0.03508   0.04203  0.004918     6.562:  18%|█▊        | 7/40 [00:38<01:11,  2.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1861       640   0.03501   0.04174  0.004959     6.536:  20%|██        | 8/40 [00:39<00:56,  1.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03488   0.04201  0.004914     6.545:  22%|██▎       | 9/40 [00:40<00:46,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1974       640   0.03492   0.04192  0.004958     6.544:  25%|██▌       | 10/40 [00:41<00:39,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1981       640   0.03488   0.04188  0.005017     6.542:  28%|██▊       | 11/40 [00:42<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1781       640   0.03482   0.04162  0.004994     6.515:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2118       640   0.03485   0.04162  0.005022     6.519:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2183       640   0.03486   0.04175  0.005028      6.53:  35%|███▌      | 14/40 [00:44<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1949       640   0.03484   0.04162  0.005035      6.52:  38%|███▊      | 15/40 [00:45<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1679       640   0.03484   0.04121  0.004994     6.483:  40%|████      | 16/40 [00:46<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1455       640   0.03471   0.04068   0.00502     6.433:  42%|████▎     | 17/40 [00:47<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2058       640   0.03478   0.04066  0.005055      6.44:  45%|████▌     | 18/40 [00:48<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1657       640   0.03479   0.04031  0.005059     6.413:  48%|████▊     | 19/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1969       640   0.03474   0.04023  0.005073     6.404:  50%|█████     | 20/40 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1945       640   0.03475   0.04011  0.005058     6.393:  52%|█████▎    | 21/40 [00:51<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1910       640   0.03476   0.04001  0.005038     6.384:  55%|█████▌    | 22/40 [00:52<00:16,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2200       640   0.03481   0.04008  0.005047     6.395:  57%|█████▊    | 23/40 [00:52<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2143       640   0.03483   0.04008  0.005059     6.398:  60%|██████    | 24/40 [00:53<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1799       640   0.03482   0.03993  0.005035     6.382:  62%|██████▎   | 25/40 [00:54<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2092       640   0.03479   0.03982  0.005048     6.373:  65%|██████▌   | 26/40 [00:55<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.472      0.435      0.393      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]

                 all        738      14937      0.547      0.383      0.392      0.222
                   0        738       1052      0.579      0.515      0.518      0.247
                   1        738         44      0.463     0.0682      0.149     0.0682
                   2        738       8622      0.659      0.719      0.741      0.473
                   3        738        151      0.454      0.331      0.386      0.299
                   4        738        467      0.477       0.58      0.544      0.396
                   5        738         70      0.303      0.386      0.244      0.121
                   6        738         65      0.319     0.0615      0.159     0.0643
                   7        738       1619      0.574      0.587      0.576      0.242
                   8        738       2845      0.643      0.583      0.601      0.313
                   9        738          2          1          0   0.000165   0.000132

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client3_citystreet_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:29:37.854658802 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30652 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round002_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client4_residential_day_stable_train' images and labels...9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:01<00:00, 10001.13it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.cache' images and labels... 9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:29:54.812924100 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:29:54.819488740 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2084       640   0.03491   0.04991   0.00457     7.152:   3%|▎         | 1/39 [00:33<21:17, 33.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2054       640   0.03536   0.04981  0.005364     7.242:   5%|▌         | 2/39 [00:34<08:57, 14.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640   0.03475   0.04823  0.005294     7.062:   8%|▊         | 3/39 [00:35<05:03,  8.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1904       640    0.0349   0.04747  0.005405     7.023:  10%|█         | 4/39 [00:37<03:14,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1942       640   0.03465   0.04636  0.005348     6.908:  13%|█▎        | 5/39 [00:37<02:11,  3.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1735       640   0.03473   0.04509  0.005434      6.82:  15%|█▌        | 6/39 [00:38<01:34,  2.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1985       640   0.03485   0.04483  0.005444      6.81:  18%|█▊        | 7/39 [00:39<01:11,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1947       640   0.03491   0.04458  0.005374     6.789:  21%|██        | 8/39 [00:40<00:55,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2072       640   0.03483   0.04459  0.005425     6.787:  23%|██▎       | 9/39 [00:41<00:45,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03491   0.04458  0.005392     6.791:  26%|██▌       | 10/39 [00:42<00:38,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2139       640   0.03489   0.04453  0.005381     6.784:  28%|██▊       | 11/39 [00:43<00:33,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2120       640   0.03487   0.04445  0.005368     6.775:  31%|███       | 12/39 [00:44<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640   0.03495   0.04454  0.005343     6.787:  33%|███▎      | 13/39 [00:45<00:27,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2027       640   0.03503   0.04448  0.005334     6.788:  36%|███▌      | 14/39 [00:46<00:24,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1824       640   0.03507   0.04421  0.005343      6.77:  38%|███▊      | 15/39 [00:46<00:22,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1768       640   0.03507   0.04399  0.005342     6.752:  41%|████      | 16/39 [00:47<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1747       640   0.03494   0.04379  0.005311     6.723:  44%|████▎     | 17/39 [00:48<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2019       640   0.03489   0.04378  0.005275     6.715:  46%|████▌     | 18/39 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1602       640   0.03482   0.04348  0.005267     6.686:  49%|████▊     | 19/39 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2209       640   0.03483    0.0435  0.005259     6.687:  51%|█████▏    | 20/39 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1896       640   0.03482   0.04345  0.005243     6.681:  54%|█████▍    | 21/39 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1996       640    0.0348   0.04345  0.005244      6.68:  56%|█████▋    | 22/39 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2001       640   0.03481   0.04347  0.005264     6.684:  59%|█████▉    | 23/39 [00:53<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03479   0.04339  0.005259     6.675:  62%|██████▏   | 24/39 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2030       640   0.03479   0.04338  0.005259     6.674:  64%|██████▍   | 25/39 [00:55<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1772       640   0.03478   0.04319  0.005246     6.657:  67%|██████▋   | 26/39 [00:56<00:11,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.469      0.465      0.408      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.454      0.469      0.406      0.228
                   0        738       1052      0.428      0.584      0.542      0.257
                   1        738         44      0.277      0.227      0.161     0.0623
                   2        738       8622      0.589      0.759      0.753      0.482
                   3        738        151      0.284      0.457      0.409      0.316
                   4        738        467      0.394      0.642      0.557      0.406
                   5        738         70      0.257      0.471      0.282       0.13
                   6        738         65      0.292      0.262      0.167     0.0582
                   7        738       1619      0.487      0.646      0.587      0.246
                   8        738       2845      0.531       0.64      0.604      0.318
                   9        738          2          1          0   0.000254   0.000254

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client4_residential_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 06:31:52.796596222 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30653 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round002_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client5_residential_night_stable_train' images and labels...9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<00:00, 12036.91it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.cache' images and labels... 9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:32:09.875119939 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:32:09.952865960 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2028       640   0.03628   0.04525  0.005061     6.927:   2%|▎         | 1/40 [00:33<21:28, 33.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1983       640   0.03611   0.04538  0.005259      6.94:   5%|▌         | 2/40 [00:34<09:09, 14.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2058       640   0.03563   0.04519  0.005069     6.871:   8%|▊         | 3/40 [00:35<05:09,  8.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2174       640   0.03543   0.04501  0.005076     6.841:  10%|█         | 4/40 [00:36<03:18,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1883       640   0.03525   0.04471   0.00502     6.798:  12%|█▎        | 5/40 [00:37<02:14,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03534   0.04409  0.004987     6.753:  15%|█▌        | 6/40 [00:38<01:37,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1702       640   0.03507   0.04319   0.00502     6.663:  18%|█▊        | 7/40 [00:39<01:13,  2.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2052       640   0.03513   0.04292  0.004954      6.64:  20%|██        | 8/40 [00:40<00:57,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1793       640     0.035   0.04245  0.004928      6.59:  22%|██▎       | 9/40 [00:41<00:47,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1823       640   0.03513   0.04213  0.005034     6.584:  25%|██▌       | 10/40 [00:42<00:39,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2374       640   0.03521   0.04223  0.005071     6.601:  28%|██▊       | 11/40 [00:43<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1790       640   0.03503   0.04173  0.005071     6.546:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1871       640   0.03492   0.04135  0.005059     6.507:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2073       640   0.03497   0.04136  0.005133     6.517:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1989       640     0.035   0.04115   0.00511     6.501:  38%|███▊      | 15/40 [00:46<00:23,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1764       640   0.03494   0.04076  0.005086     6.463:  40%|████      | 16/40 [00:47<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03492   0.04066  0.005123     6.456:  42%|████▎     | 17/40 [00:48<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1986       640   0.03496   0.04048  0.005181     6.449:  45%|████▌     | 18/40 [00:49<00:19,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1692       640   0.03499   0.04011  0.005164     6.421:  48%|████▊     | 19/40 [00:50<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2135       640   0.03506    0.0401  0.005182     6.427:  50%|█████     | 20/40 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1985       640   0.03507    0.0399  0.005187     6.412:  52%|█████▎    | 21/40 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1788       640   0.03505   0.03967  0.005187     6.392:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2131       640   0.03505   0.03962  0.005204      6.39:  57%|█████▊    | 23/40 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1939       640   0.03504   0.03946  0.005204     6.376:  60%|██████    | 24/40 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1889       640   0.03504   0.03928  0.005185      6.36:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1705       640   0.03502   0.03905  0.005203     6.342:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.526      0.401      0.399      0.224
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:05<00:00,  1.03s/it]

                 all        738      14937      0.513      0.408      0.398      0.225
                   0        738       1052      0.515      0.542      0.525      0.252
                   1        738         44      0.433      0.136      0.158     0.0602
                   2        738       8622      0.628      0.733      0.744      0.477
                   3        738        151      0.405      0.391      0.397      0.311
                   4        738        467      0.468      0.598      0.552        0.4
                   5        738         70      0.267      0.371      0.246       0.12
                   6        738         65      0.269     0.0923      0.165      0.065
                   7        738       1619      0.549      0.611      0.588      0.244
                   8        738       2845      0.597      0.607      0.601      0.316
                   9        738          2          1          0   0.000179   0.000143

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_client5_residential_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:34:08.056269256 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30654 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round002_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round002_dqa_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:34:26.585615166 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:34:26.593460575 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03482   0.04347  0.005217      6.68:   3%|▎         | 1/31 [00:33<16:52, 33.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03547   0.04453  0.005424     6.834:   6%|▋         | 2/31 [00:34<06:56, 14.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03487   0.04336  0.005307     6.683:  10%|▉         | 3/31 [00:35<03:47,  8.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03429   0.04164  0.005066      6.48:  13%|█▎        | 4/31 [00:36<02:20,  5.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03426   0.04183   0.00509     6.494:  16%|█▌        | 5/31 [00:36<01:32,  3.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03444   0.04179  0.005159     6.511:  19%|█▉        | 6/31 [00:37<01:03,  2.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03455    0.0415  0.005227     6.502:  23%|██▎       | 7/31 [00:37<00:45,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03447   0.04159  0.005258     6.506:  26%|██▌       | 8/31 [00:38<00:33,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640    0.0345   0.04152  0.005165     6.495:  29%|██▉       | 9/31 [00:38<00:26,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03447   0.04163  0.005145       6.5:  32%|███▏      | 10/31 [00:39<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03443   0.04167  0.005163     6.501:  35%|███▌      | 11/31 [00:40<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03433   0.04139  0.005149     6.469:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0343   0.04144  0.005097     6.467:  42%|████▏     | 13/31 [00:41<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640    0.0343   0.04124  0.005061     6.448:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03433   0.04115  0.005097     6.446:  48%|████▊     | 15/31 [00:42<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03432   0.04101  0.005084     6.433:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03435   0.04105  0.005044     6.435:  55%|█████▍    | 17/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03438   0.04109  0.005001     6.438:  58%|█████▊    | 18/31 [00:44<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03431   0.04095  0.004964     6.418:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640    0.0343   0.04117  0.004968     6.434:  65%|██████▍   | 20/31 [00:45<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03432   0.04119  0.004984     6.439:  68%|██████▊   | 21/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03431   0.04129   0.00495     6.444:  71%|███████   | 22/31 [00:46<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03429   0.04132  0.004941     6.444:  74%|███████▍  | 23/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640    0.0343   0.04139  0.004923     6.448:  77%|███████▋  | 24/31 [00:47<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03429   0.04132  0.004931     6.444:  81%|████████  | 25/31 [00:48<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03434   0.04135  0.004928     6.449:  84%|████████▍ | 26/31 [00:48<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.47      0.464      0.409      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.468      0.454      0.407      0.228
                   0        738       1052      0.463      0.576      0.542      0.257
                   1        738         44      0.294      0.182      0.165     0.0604
                   2        738       8622      0.579      0.762      0.753      0.487
                   3        738        151      0.317       0.43      0.403      0.308
                   4        738        467      0.436      0.608      0.556      0.405
                   5        738         70      0.251      0.471      0.274      0.132
                   6        738         65      0.288      0.231      0.171     0.0622
                   7        738       1619      0.513      0.636      0.585      0.244
                   8        738       2845      0.538      0.644      0.615      0.326
                   9        738          2          1          0   0.000309   0.000309

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round002_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W505 06:36:06.000833159 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

=== round003: DQA scene-daynight round ===

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round003 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round003 client0_highway_day: pseudo scan 250/1500 images, kept 2387 boxes
round003 client0_highway_day: pseudo scan 500/1500 images, kept 4835 boxes
round003 client0_highway_day: pseudo scan 750/1500 images, kept 7195 boxes
round003 client0_highway_day: pseudo scan 1000/1500 images, kept 9582 boxes
round003 client0_highway_day: pseudo scan 1250/1500 images, kept 11918 boxes
round003 client0_highway_day: pseudo scan 1500/1500 images, kept 14299 boxes
{
  "round": "round003",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 11142,
  "boxes_per_kept_image": 7.452842809364548,
  "mean_conf": 0.7868068395862886,
  "mean_stability": 0.9541035195887142,
  "mean_score": 0.7539032314326334,
  "class_counts": {
    "0": 155,
    "2": 6435,
    "3": 96,
    "4": 511,
    "5": 7,
    "7": 557,
    "8": 3381
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_client0_highway_day_stable_boxes.csv"
}
round003 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round003 client1_highway_night: pseudo scan 250/1500 images, kept 1784 boxes
round003 client1_highway_night: pseudo scan 500/1500 images, kept 3703 boxes
round003 client1_highway_night: pseudo scan 750/1500 images, kept 5589 boxes
round003 client1_highway_night: pseudo scan 1000/1500 images, kept 7405 boxes
round003 client1_highway_night: pseudo scan 1250/1500 images, kept 9258 boxes
round003 client1_highway_night: pseudo scan 1500/1500 images, kept 11079 boxes
{
  "round": "round003",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 8936,
  "boxes_per_kept_image": 6.058305084745763,
  "mean_conf": 0.6959556859676979,
  "mean_stability": 0.93574319705834,
  "mean_score": 0.6552445990701876,
  "class_counts": {
    "0": 58,
    "2": 4986,
    "3": 26,
    "4": 137,
    "5": 6,
    "7": 556,
    "8": 3167
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_client1_highway_night_stable_boxes.csv"
}
round003 client2_citystreet_day: pseudo scan 1/1500 images, kept 7 boxes
round003 client2_citystreet_day: pseudo scan 250/1500 images, kept 2698 boxes
round003 client2_citystreet_day: pseudo scan 500/1500 images, kept 5417 boxes
round003 client2_citystreet_day: pseudo scan 750/1500 images, kept 8158 boxes
round003 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10927 boxes
round003 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13657 boxes
round003 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16303 boxes
{
  "round": "round003",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13670,
  "boxes_per_kept_image": 9.13770053475936,
  "mean_conf": 0.7831865367395824,
  "mean_stability": 0.9520951337114947,
  "mean_score": 0.7489445058093075,
  "class_counts": {
    "0": 1409,
    "2": 7337,
    "3": 166,
    "4": 565,
    "5": 63,
    "7": 1535,
    "8": 2595
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_client2_citystreet_day_stable_boxes.csv"
}
round003 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round003 client3_citystreet_night: pseudo scan 250/1500 images, kept 2465 boxes
round003 client3_citystreet_night: pseudo scan 500/1500 images, kept 4884 boxes
round003 client3_citystreet_night: pseudo scan 750/1500 images, kept 7283 boxes
round003 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9622 boxes
round003 client3_citystreet_night: pseudo scan 1250/1500 images, kept 12125 boxes
round003 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14536 boxes
{
  "round": "round003",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1482,
  "pseudo_boxes_kept": 12044,
  "boxes_per_kept_image": 8.12685560053981,
  "mean_conf": 0.7001922988725319,
  "mean_stability": 0.9353471071329753,
  "mean_score": 0.6589659333845785,
  "class_counts": {
    "0": 537,
    "2": 6542,
    "3": 61,
    "4": 155,
    "5": 31,
    "7": 1909,
    "8": 2809
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_client3_citystreet_night_stable_boxes.csv"
}
round003 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round003 client4_residential_day: pseudo scan 250/1500 images, kept 2578 boxes
round003 client4_residential_day: pseudo scan 500/1500 images, kept 5186 boxes
round003 client4_residential_day: pseudo scan 750/1500 images, kept 7740 boxes
round003 client4_residential_day: pseudo scan 1000/1500 images, kept 10219 boxes
round003 client4_residential_day: pseudo scan 1250/1500 images, kept 12760 boxes
round003 client4_residential_day: pseudo scan 1500/1500 images, kept 15239 boxes
{
  "round": "round003",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9889,
  "boxes_per_kept_image": 6.632461435278337,
  "mean_conf": 0.8221737894102734,
  "mean_stability": 0.9601349918265376,
  "mean_score": 0.7925641959440406,
  "class_counts": {
    "0": 372,
    "2": 6858,
    "3": 49,
    "4": 309,
    "5": 37,
    "7": 532,
    "8": 1732
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_client4_residential_day_stable_boxes.csv"
}
round003 client5_residential_night: pseudo scan 1/1500 images, kept 11 boxes
round003 client5_residential_night: pseudo scan 250/1500 images, kept 2444 boxes
round003 client5_residential_night: pseudo scan 500/1500 images, kept 4824 boxes
round003 client5_residential_night: pseudo scan 750/1500 images, kept 7205 boxes
round003 client5_residential_night: pseudo scan 1000/1500 images, kept 9662 boxes
round003 client5_residential_night: pseudo scan 1250/1500 images, kept 12075 boxes
round003 client5_residential_night: pseudo scan 1500/1500 images, kept 14533 boxes
{
  "round": "round003",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 8953,
  "boxes_per_kept_image": 6.0452397029034435,
  "mean_conf": 0.7791691599685254,
  "mean_stability": 0.9489065113646031,
  "mean_score": 0.7419908388297336,
  "class_counts": {
    "0": 123,
    "2": 6540,
    "3": 27,
    "4": 92,
    "5": 15,
    "7": 606,
    "8": 1550
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/03_round003_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30655 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round003_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client0_highway_day_stable_train' images and labels...10002 found, 1255 missing, 0 empty, 0 corrupted: 100%|██████████| 11257/11257 [00:01<00:00, 10787.34it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.828389830508474
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.cache' images and labels... 10002 found, 1255 missing, 0 empty, 0 corrupted: 100%|██████████| 11257/11257 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:38:30.849373892 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:38:30.861411735 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1976       640   0.03452   0.04471  0.006042     6.821:   3%|▎         | 1/39 [00:33<20:59, 33.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1844       640   0.03406   0.04355  0.005561     6.653:   5%|▌         | 2/39 [00:34<08:52, 14.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640   0.03474   0.04505  0.005579     6.829:   8%|▊         | 3/39 [00:35<05:01,  8.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1995       640   0.03447   0.04487  0.005439     6.783:  10%|█         | 4/39 [00:36<03:12,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1924       640   0.03453   0.04439  0.005475     6.751:  13%|█▎        | 5/39 [00:37<02:10,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1922       640   0.03447   0.04383  0.005428     6.698:  15%|█▌        | 6/39 [00:38<01:34,  2.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1997       640   0.03429   0.04309  0.005405     6.623:  18%|█▊        | 7/39 [00:39<01:11,  2.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2222       640    0.0343   0.04342  0.005341     6.645:  21%|██        | 8/39 [00:40<00:55,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2165       640   0.03447   0.04363  0.005329     6.675:  23%|██▎       | 9/39 [00:41<00:45,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2088       640   0.03453   0.04384  0.005308     6.694:  26%|██▌       | 10/39 [00:42<00:38,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640   0.03452   0.04351  0.005235     6.662:  28%|██▊       | 11/39 [00:43<00:33,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2043       640   0.03452   0.04353  0.005272     6.666:  31%|███       | 12/39 [00:43<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1933       640   0.03454   0.04331  0.005255     6.649:  33%|███▎      | 13/39 [00:44<00:26,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640    0.0346   0.04336  0.005242     6.656:  36%|███▌      | 14/39 [00:45<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2008       640   0.03458   0.04319  0.005182     6.636:  38%|███▊      | 15/39 [00:46<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640    0.0346   0.04326  0.005157     6.642:  41%|████      | 16/39 [00:47<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1787       640   0.03464   0.04302  0.005164     6.626:  44%|████▎     | 17/39 [00:48<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2071       640   0.03468   0.04286  0.005117     6.613:  46%|████▌     | 18/39 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1735       640   0.03467   0.04265  0.005118     6.595:  49%|████▊     | 19/39 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2326       640   0.03461   0.04278  0.005129     6.601:  51%|█████▏    | 20/39 [00:50<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2017       640   0.03469   0.04274  0.005139     6.605:  54%|█████▍    | 21/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1705       640   0.03458   0.04253  0.005093     6.576:  56%|█████▋    | 22/39 [00:52<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2057       640   0.03451   0.04246  0.005067     6.563:  59%|█████▉    | 23/39 [00:53<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2321       640   0.03455   0.04253  0.005044     6.569:  62%|██████▏   | 24/39 [00:54<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1970       640   0.03458   0.04249  0.005061      6.57:  64%|██████▍   | 25/39 [00:55<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2069       640   0.03454   0.04251   0.00503     6.567:  67%|██████▋   | 26/39 [00:56<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.481      0.446      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.562      0.397      0.409      0.231
                   0        738       1052      0.556      0.564      0.552      0.263
                   1        738         44      0.559      0.087      0.167     0.0633
                   2        738       8622      0.694      0.726      0.754      0.487
                   3        738        151      0.487      0.391      0.417       0.32
                   4        738        467      0.516      0.572      0.554      0.406
                   5        738         70      0.273      0.371      0.266      0.141
                   6        738         65      0.299     0.0615      0.169     0.0658
                   7        738       1619       0.57      0.612      0.595      0.245
                   8        738       2845      0.665      0.589      0.611      0.319
                   9        738          2          1          0   0.000296   0.000267

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client0_highway_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 06:40:28.413669048 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30656 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round003_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client1_highway_night_stable_train' images and labels...9769 found, 1468 missing, 0 empty, 0 corrupted: 100%|██████████| 11237/11237 [00:00<00:00, 12198.83it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.297369664514097
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.cache' images and labels... 9769 found, 1468 missing, 0 empty, 0 corrupted: 100%|██████████| 11237/11237 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:40:45.707572679 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:40:45.742791249 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1933       640   0.03418   0.04078  0.005007     6.398:   2%|▎         | 1/40 [00:32<20:58, 32.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1982       640   0.03481    0.0402  0.005004     6.402:   5%|▌         | 2/40 [00:33<08:50, 13.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1773       640   0.03432   0.03987  0.004846     6.323:   8%|▊         | 3/40 [00:34<05:01,  8.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1971       640   0.03417   0.03995  0.004738     6.309:  10%|█         | 4/40 [00:35<03:13,  5.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1795       640   0.03427   0.03971  0.004799     6.302:  12%|█▎        | 5/40 [00:36<02:11,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1766       640   0.03418   0.03915  0.004894     6.258:  15%|█▌        | 6/40 [00:37<01:35,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1690       640   0.03419    0.0383  0.004861     6.188:  18%|█▊        | 7/40 [00:38<01:12,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1878       640   0.03416   0.03811  0.004868     6.171:  20%|██        | 8/40 [00:39<00:57,  1.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1920       640   0.03422   0.03805  0.004843     6.169:  22%|██▎       | 9/40 [00:40<00:47,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1874       640   0.03429   0.03806  0.004848     6.176:  25%|██▌       | 10/40 [00:41<00:40,  1.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1995       640   0.03429   0.03809  0.004893     6.182:  28%|██▊       | 11/40 [00:42<00:35,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1838       640   0.03421   0.03787  0.004882     6.157:  30%|███       | 12/40 [00:43<00:32,  1.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1975       640   0.03422   0.03779  0.004927     6.155:  32%|███▎      | 13/40 [00:44<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640   0.03428   0.03772  0.004946     6.156:  35%|███▌      | 14/40 [00:45<00:27,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1890       640   0.03427   0.03762  0.004953     6.147:  38%|███▊      | 15/40 [00:46<00:25,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1795       640    0.0342   0.03746  0.004936     6.128:  40%|████      | 16/40 [00:47<00:24,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640   0.03432   0.03758  0.004965     6.149:  42%|████▎     | 17/40 [00:48<00:22,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2102       640   0.03431   0.03766  0.004999     6.157:  45%|████▌     | 18/40 [00:49<00:21,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1587       640   0.03432   0.03739  0.005027     6.139:  48%|████▊     | 19/40 [00:50<00:20,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2035       640   0.03438   0.03738  0.005036     6.144:  50%|█████     | 20/40 [00:51<00:19,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2105       640   0.03447   0.03748  0.005077     6.162:  52%|█████▎    | 21/40 [00:52<00:18,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640   0.03454   0.03754  0.005079     6.172:  55%|█████▌    | 22/40 [00:52<00:17,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640   0.03451   0.03746  0.005063     6.162:  57%|█████▊    | 23/40 [00:53<00:16,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1787       640   0.03449   0.03732  0.005042     6.148:  60%|██████    | 24/40 [00:54<00:15,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1737       640   0.03446   0.03717  0.005028     6.132:  62%|██████▎   | 25/40 [00:55<00:14,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1852       640   0.03442   0.03703  0.004998     6.116:  65%|██████▌   | 26/40 [00:56<00:13,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937        0.5      0.426      0.401      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:09<00:00,  2.00s/it]

                 all        738      14937      0.541      0.396        0.4      0.227
                   0        738       1052      0.562      0.528      0.538      0.256
                   1        738         44      0.495     0.0894      0.159     0.0653
                   2        738       8622      0.659      0.729      0.749      0.483
                   3        738        151      0.457       0.39      0.407      0.313
                   4        738        467      0.461      0.602      0.546      0.399
                   5        738         70      0.279      0.357      0.248      0.125
                   6        738         65       0.31     0.0615      0.159     0.0669
                   7        738       1619      0.555      0.615      0.589      0.246
                   8        738       2845      0.631      0.593        0.6      0.313
                   9        738          2          1          0   0.000255   0.000229

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client1_highway_night

1 epochs completed in 0.036 hours.
Destroying process group...
[rank0]:[W505 06:42:53.396325445 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30657 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round003_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train' images and labels...9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<00:00, 13945.68it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache' images and labels... 9928 found, 1330 missing, 0 empty, 0 corrupted: 100%|██████████| 11258/11258 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:43:09.907843505 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:43:09.908598667 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2066       640   0.03583   0.05088   0.00515     7.349:   3%|▎         | 1/39 [00:33<21:23, 33.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2187       640   0.03532   0.05049  0.005459     7.302:   5%|▌         | 2/39 [00:35<09:02, 14.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1974       640   0.03496   0.04971  0.005471     7.211:   8%|▊         | 3/39 [00:36<05:06,  8.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640   0.03505   0.04888  0.005364     7.144:  10%|█         | 4/39 [00:37<03:15,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2145       640   0.03498   0.04832  0.005256     7.084:  13%|█▎        | 5/39 [00:38<02:12,  3.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1780       640   0.03457    0.0473  0.005205     6.966:  15%|█▌        | 6/39 [00:39<01:35,  2.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1960       640   0.03465   0.04712  0.005279     6.964:  18%|█▊        | 7/39 [00:40<01:11,  2.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1897       640   0.03453   0.04674  0.005224     6.919:  21%|██        | 8/39 [00:41<00:56,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2025       640   0.03466   0.04676  0.005166     6.927:  23%|██▎       | 9/39 [00:41<00:45,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1808       640   0.03449   0.04648  0.005147     6.889:  26%|██▌       | 10/39 [00:42<00:38,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1991       640   0.03451   0.04639  0.005148     6.883:  28%|██▊       | 11/39 [00:43<00:33,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1792       640   0.03455   0.04591  0.005157     6.849:  31%|███       | 12/39 [00:44<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03462   0.04577  0.005116      6.84:  33%|███▎      | 13/39 [00:45<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2134       640   0.03472   0.04581  0.005085     6.849:  36%|███▌      | 14/39 [00:46<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1930       640   0.03472   0.04567  0.005065     6.837:  38%|███▊      | 15/39 [00:47<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1894       640   0.03462   0.04536  0.005059     6.803:  41%|████      | 16/39 [00:48<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1504       640   0.03454   0.04512  0.005088      6.78:  44%|████▎     | 17/39 [00:48<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1920       640   0.03446   0.04505  0.005074     6.767:  46%|████▌     | 18/39 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1718       640   0.03447   0.04475  0.005053     6.742:  49%|████▊     | 19/39 [00:50<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03442   0.04475  0.005039     6.737:  51%|█████▏    | 20/39 [00:51<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1849       640   0.03434   0.04458  0.005022     6.716:  54%|█████▍    | 21/39 [00:52<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1707       640    0.0343    0.0445  0.005011     6.704:  56%|█████▋    | 22/39 [00:53<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1860       640   0.03423   0.04438  0.005011      6.69:  59%|█████▉    | 23/39 [00:54<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1900       640    0.0342   0.04432  0.005002     6.681:  62%|██████▏   | 24/39 [00:55<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1848       640   0.03416   0.04421  0.004997     6.669:  64%|██████▍   | 25/39 [00:56<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640    0.0341   0.04418  0.004986     6.661:  67%|██████▋   | 26/39 [00:56<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.501      0.432      0.407       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]

                 all        738      14937      0.485      0.437      0.407      0.231
                   0        738       1052      0.557      0.543      0.545      0.258
                   1        738         44      0.349      0.182       0.16     0.0746
                   2        738       8622       0.59      0.763      0.758      0.487
                   3        738        151      0.303       0.43      0.408      0.312
                   4        738        467      0.429      0.619       0.55      0.398
                   5        738         70      0.279      0.443      0.271      0.138
                   6        738         65      0.264      0.138       0.18     0.0735
                   7        738       1619      0.517      0.629      0.584      0.246
                   8        738       2845      0.566      0.628       0.61      0.321
                   9        738          2          1          0   0.000273   0.000245

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client2_citystreet_day

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:45:09.626718630 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30658 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round003_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train' images and labels...9763 found, 1481 missing, 0 empty, 0 corrupted: 100%|██████████| 11244/11244 [00:01<00:00, 9714.73it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.266111285759195
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache' images and labels... 9763 found, 1481 missing, 0 empty, 0 corrupted: 100%|██████████| 11244/11244 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:45:27.443497611 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:45:27.444976338 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1951       640   0.03513   0.04416  0.004905     6.736:   2%|▎         | 1/40 [00:35<23:06, 35.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2030       640   0.03565    0.0453  0.005094     6.884:   5%|▌         | 2/40 [00:36<09:43, 15.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2007       640    0.0354   0.04495  0.005143      6.84:   8%|▊         | 3/40 [00:37<05:27,  8.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1919       640   0.03525   0.04411     0.005     6.749:  10%|█         | 4/40 [00:38<03:28,  5.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1794       640   0.03471   0.04297  0.004944      6.61:  12%|█▎        | 5/40 [00:39<02:20,  4.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1837       640   0.03469   0.04246  0.004954     6.568:  15%|█▌        | 6/40 [00:40<01:40,  2.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1791       640   0.03453   0.04173  0.004955     6.497:  18%|█▊        | 7/40 [00:41<01:15,  2.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1895       640   0.03435   0.04154  0.004915     6.464:  20%|██        | 8/40 [00:42<00:58,  1.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2039       640   0.03431   0.04158  0.004929     6.466:  22%|██▎       | 9/40 [00:43<00:47,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1918       640   0.03435   0.04146  0.004956     6.461:  25%|██▌       | 10/40 [00:44<00:40,  1.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2167       640   0.03443   0.04142  0.004942     6.464:  28%|██▊       | 11/40 [00:45<00:34,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1918       640   0.03439   0.04139  0.004977      6.46:  30%|███       | 12/40 [00:46<00:30,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2023       640   0.03434    0.0412  0.005019     6.445:  32%|███▎      | 13/40 [00:46<00:28,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1982       640   0.03424   0.04104  0.004983     6.421:  35%|███▌      | 14/40 [00:47<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1989       640   0.03421    0.0409  0.004989     6.408:  38%|███▊      | 15/40 [00:48<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1809       640   0.03429   0.04064  0.004988     6.393:  40%|████      | 16/40 [00:49<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1738       640    0.0343   0.04029  0.005026      6.37:  42%|████▎     | 17/40 [00:50<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1981       640   0.03434   0.04016  0.005054     6.365:  45%|████▌     | 18/40 [00:51<00:19,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1579       640   0.03434   0.03983  0.005067     6.338:  48%|████▊     | 19/40 [00:52<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2152       640   0.03433   0.03982  0.005049     6.336:  50%|█████     | 20/40 [00:53<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1796       640   0.03436   0.03964  0.005076     6.326:  52%|█████▎    | 21/40 [00:53<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1615       640   0.03437   0.03936  0.005073     6.304:  55%|█████▌    | 22/40 [00:54<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1890       640   0.03438   0.03926   0.00509     6.299:  57%|█████▊    | 23/40 [00:55<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1949       640    0.0344   0.03914  0.005104     6.292:  60%|██████    | 24/40 [00:56<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1955       640   0.03438   0.03901  0.005117     6.281:  62%|██████▎   | 25/40 [00:57<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2040       640   0.03438   0.03894  0.005103     6.274:  65%|██████▌   | 26/40 [00:58<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.567      0.379      0.397      0.224
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:05<00:00,  1.07s/it]

                 all        738      14937      0.555      0.382      0.395      0.225
                   0        738       1052      0.611      0.497      0.521      0.249
                   1        738         44       0.35     0.0379      0.154      0.065
                   2        738       8622      0.673      0.714      0.741      0.475
                   3        738        151      0.499      0.384      0.404      0.311
                   4        738        467      0.471      0.589       0.55        0.4
                   5        738         70       0.33      0.386      0.253      0.127
                   6        738         65       0.37     0.0615      0.151     0.0614
                   7        738       1619       0.59      0.578      0.576      0.242
                   8        738       2845      0.657      0.574      0.597      0.314
                   9        738          2          1          0   0.000188    0.00015

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client3_citystreet_night

1 epochs completed in 0.035 hours.
Destroying process group...
[rank0]:[W505 06:47:31.380875232 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30659 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round003_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client4_residential_day_stable_train' images and labels...9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:01<00:00, 9396.41it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.cache' images and labels... 9921 found, 1332 missing, 0 empty, 0 corrupted: 100%|██████████| 11253/11253 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:47:48.841935766 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:47:48.872895370 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2084       640   0.03463   0.04982  0.004431      7.11:   3%|▎         | 1/39 [00:33<21:10, 33.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2054       640   0.03505   0.04969  0.005227     7.197:   5%|▌         | 2/39 [00:34<08:54, 14.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640   0.03445   0.04804  0.005167     7.012:   8%|▊         | 3/39 [00:35<05:00,  8.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1904       640   0.03459   0.04728  0.005277     6.971:  10%|█         | 4/39 [00:36<03:12,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1942       640   0.03433   0.04614  0.005225     6.855:  13%|█▎        | 5/39 [00:37<02:11,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1735       640    0.0344   0.04486  0.005307     6.765:  15%|█▌        | 6/39 [00:38<01:34,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1985       640   0.03453   0.04459  0.005311     6.754:  18%|█▊        | 7/39 [00:39<01:10,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1947       640   0.03459   0.04435  0.005239     6.734:  21%|██        | 8/39 [00:40<00:55,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2072       640   0.03451   0.04435  0.005292     6.732:  23%|██▎       | 9/39 [00:41<00:45,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03459   0.04434   0.00526     6.735:  26%|██▌       | 10/39 [00:42<00:38,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2139       640   0.03458   0.04429   0.00525     6.729:  28%|██▊       | 11/39 [00:43<00:33,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2120       640   0.03455   0.04422  0.005232      6.72:  31%|███       | 12/39 [00:44<00:29,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640   0.03464   0.04431  0.005209     6.733:  33%|███▎      | 13/39 [00:44<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2027       640   0.03471   0.04426  0.005199     6.734:  36%|███▌      | 14/39 [00:45<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1824       640   0.03476   0.04399  0.005206     6.716:  38%|███▊      | 15/39 [00:46<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1768       640   0.03475   0.04377  0.005204     6.698:  41%|████      | 16/39 [00:47<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1747       640   0.03462   0.04357  0.005173     6.669:  44%|████▎     | 17/39 [00:48<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2019       640   0.03458   0.04356  0.005137     6.662:  46%|████▌     | 18/39 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1602       640   0.03451   0.04326   0.00513     6.632:  49%|████▊     | 19/39 [00:50<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2209       640   0.03452   0.04328   0.00512     6.633:  51%|█████▏    | 20/39 [00:51<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1896       640   0.03452   0.04323  0.005102     6.628:  54%|█████▍    | 21/39 [00:52<00:16,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1996       640    0.0345   0.04323  0.005103     6.627:  56%|█████▋    | 22/39 [00:52<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2001       640   0.03451   0.04325  0.005125     6.631:  59%|█████▉    | 23/39 [00:53<00:14,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2032       640   0.03448   0.04317  0.005118     6.622:  62%|██████▏   | 24/39 [00:54<00:13,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2030       640   0.03448   0.04316  0.005119     6.621:  64%|██████▍   | 25/39 [00:55<00:12,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1772       640   0.03448   0.04297  0.005105     6.604:  67%|██████▋   | 26/39 [00:56<00:11,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.483      0.458       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:05<00:00,  1.13s/it]

                 all        738      14937      0.466      0.461      0.409       0.23
                   0        738       1052       0.45      0.582      0.545      0.259
                   1        738         44      0.331      0.227      0.176     0.0691
                   2        738       8622      0.602      0.755      0.753      0.484
                   3        738        151      0.283      0.444      0.416      0.325
                   4        738        467        0.4       0.64      0.556      0.404
                   5        738         70      0.263      0.471       0.28      0.134
                   6        738         65      0.282      0.215      0.167     0.0583
                   7        738       1619      0.498      0.639      0.586      0.245
                   8        738       2845      0.551      0.636      0.607      0.321
                   9        738          2          1          0   0.000263   0.000263

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client4_residential_day

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W505 06:49:47.192799641 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30660 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/client_states/dqa01_round003_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client5_residential_night_stable_train' images and labels...9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:01<00:00, 9777.68it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.cache' images and labels... 9764 found, 1479 missing, 0 empty, 0 corrupted: 100%|██████████| 11243/11243 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W505 06:50:05.539813201 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W505 06:50:05.543561286 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2077       640   0.03517   0.04548  0.004906     6.845:   2%|▎         | 1/40 [00:33<21:35, 33.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1843       640   0.03502   0.04465  0.005045     6.778:   5%|▌         | 2/40 [00:34<09:11, 14.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2137       640   0.03478   0.04455  0.004658     6.719:   8%|▊         | 3/40 [00:35<05:09,  8.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1972       640   0.03491   0.04381  0.004625     6.668:  10%|█         | 4/40 [00:36<03:17,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1986       640   0.03487   0.04373  0.004657     6.661:  12%|█▎        | 5/40 [00:37<02:14,  3.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1851       640    0.0347   0.04272  0.004638     6.564:  15%|█▌        | 6/40 [00:38<01:36,  2.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1847       640   0.03455    0.0421  0.004669     6.506:  18%|█▊        | 7/40 [00:39<01:12,  2.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2128       640   0.03457   0.04211  0.004732     6.513:  20%|██        | 8/40 [00:40<00:57,  1.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2229       640   0.03464   0.04228  0.004757     6.535:  22%|██▎       | 9/40 [00:41<00:46,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2044       640   0.03456   0.04216  0.004806     6.522:  25%|██▌       | 10/40 [00:42<00:39,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2018       640   0.03453   0.04185  0.004804     6.495:  28%|██▊       | 11/40 [00:42<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1751       640    0.0345   0.04125  0.004805     6.444:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1972       640   0.03446   0.04103  0.004831     6.426:  32%|███▎      | 13/40 [00:44<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1992       640   0.03451   0.04091  0.004858     6.422:  35%|███▌      | 14/40 [00:45<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1981       640   0.03446   0.04084  0.004871     6.414:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1799       640   0.03446    0.0405  0.004887     6.388:  40%|████      | 16/40 [00:47<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1967       640   0.03451   0.04041  0.004902     6.386:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1967       640   0.03455   0.04028  0.004929     6.381:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1861       640   0.03457   0.04003  0.004914     6.361:  48%|████▊     | 19/40 [00:50<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1803       640    0.0346    0.0398  0.004927     6.346:  50%|█████     | 20/40 [00:51<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2279       640   0.03467    0.0398  0.004925     6.352:  52%|█████▎    | 21/40 [00:51<00:17,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1868       640   0.03466   0.03961  0.004929     6.336:  55%|█████▌    | 22/40 [00:52<00:16,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1924       640   0.03464   0.03947  0.004937     6.324:  57%|█████▊    | 23/40 [00:53<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2063       640   0.03464   0.03937  0.004952     6.317:  60%|██████    | 24/40 [00:54<00:14,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1813       640   0.03463   0.03917  0.004961     6.301:  62%|██████▎   | 25/40 [00:55<00:13,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640   0.03465   0.03901  0.004959     6.289:  65%|██████▌   | 26/40 [00:56<00:12,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.535      0.403      0.403      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]

                 all        738      14937      0.527      0.407      0.404      0.226
                   0        738       1052      0.533      0.546      0.529      0.252
                   1        738         44       0.54      0.136      0.177     0.0679
                   2        738       8622      0.642      0.732      0.747      0.479
                   3        738        151      0.392      0.392      0.413       0.32
                   4        738        467      0.454      0.593      0.553      0.402
                   5        738         70      0.269      0.371      0.262      0.119
                   6        738         65      0.273     0.0769      0.159     0.0604
                   7        738       1619      0.556      0.622      0.593      0.244
                   8        738       2845      0.608      0.603      0.603      0.316
                   9        738          2          1          0   0.000176   0.000141

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_client5_residential_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W505 06:52:02.018114820 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 30661 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/configs/pl03_round003_repair_oriented_all_lowlr_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  e8b42eb torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round003_dqa_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W505 06:52:19.560129729 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W505 06:52:19.563786164 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03397   0.04231  0.004928     6.497:   3%|▎         | 1/31 [00:32<16:19, 32.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03464   0.04328  0.005128     6.643:   6%|▋         | 2/31 [00:33<06:47, 14.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03406   0.04215  0.005029       6.5:  10%|▉         | 3/31 [00:34<03:44,  8.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03349   0.04045   0.00479     6.299:  13%|█▎        | 4/31 [00:35<02:19,  5.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03349   0.04064   0.00482     6.316:  16%|█▌        | 5/31 [00:35<01:31,  3.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03368   0.04062  0.004887     6.335:  19%|█▉        | 6/31 [00:36<01:03,  2.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640    0.0338   0.04036  0.004959     6.329:  23%|██▎       | 7/31 [00:37<00:46,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03373   0.04045  0.004986     6.334:  26%|██▌       | 8/31 [00:37<00:34,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03378   0.04039  0.004892     6.325:  29%|██▉       | 9/31 [00:38<00:27,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03376   0.04051  0.004874     6.332:  32%|███▏      | 10/31 [00:39<00:22,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03372   0.04055  0.004896     6.334:  35%|███▌      | 11/31 [00:39<00:18,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03363   0.04028  0.004889     6.303:  39%|███▊      | 12/31 [00:40<00:15,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0336   0.04032  0.004839     6.301:  42%|████▏     | 13/31 [00:41<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03361   0.04014  0.004805     6.284:  45%|████▌     | 14/31 [00:41<00:12,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03364   0.04007  0.004844     6.284:  48%|████▊     | 15/31 [00:42<00:11,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03364   0.03994  0.004834     6.272:  52%|█████▏    | 16/31 [00:42<00:10,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03367   0.03999  0.004797     6.277:  55%|█████▍    | 17/31 [00:43<00:09,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03371   0.04004  0.004756     6.281:  58%|█████▊    | 18/31 [00:44<00:08,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03365   0.03991   0.00472     6.262:  61%|██████▏   | 19/31 [00:44<00:07,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03364   0.04014  0.004725      6.28:  65%|██████▍   | 20/31 [00:45<00:07,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03367   0.04017  0.004743     6.287:  68%|██████▊   | 21/31 [00:46<00:06,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03367   0.04028  0.004713     6.293:  71%|███████   | 22/31 [00:46<00:05,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03366   0.04033  0.004701     6.295:  74%|███████▍  | 23/31 [00:47<00:05,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03367   0.04041  0.004685     6.301:  77%|███████▋  | 24/31 [00:48<00:04,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03367   0.04036  0.004696     6.298:  81%|████████  | 25/31 [00:48<00:03,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03372   0.04039  0.004697     6.305:  84%|████████▍ | 26/31 [00:49<00:03,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.457      0.491      0.411      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:10<00:00,  2.03s/it]

                 all        738      14937      0.442      0.495       0.41       0.23
                   0        738       1052      0.405      0.589      0.541      0.258
                   1        738         44      0.248      0.295      0.158     0.0624
                   2        738       8622      0.543      0.771      0.754      0.487
                   3        738        151      0.279      0.463      0.418      0.317
                   4        738        467      0.406       0.62      0.556      0.404
                   5        738         70      0.244      0.514      0.287      0.139
                   6        738         65        0.3      0.385      0.176     0.0633
                   7        738       1619      0.489       0.65       0.59      0.243
                   8        738       2845      0.508      0.664      0.617      0.327
                   9        738          2          1          0   0.000325   0.000293

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/runs/pl03_round003_repair_oriented_all_lowlr_server_repair

1 epochs completed in 0.031 hours.
Destroying process group...
[rank0]:[W505 06:54:08.492502772 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/01_manifest.json
/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/evaluate_scene_daynight_protocol.py --workspace /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa --splits highway_day,highway_night,citystreet_day,citystreet_night,residential_day,residential_night,total --batch-size 16 --no-plots --verbose --checkpoint warmup_global=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/global_checkpoints/round000_warmup.pt --checkpoint round001_dqa_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_cwa_v2_aggregate.pt --checkpoint round001_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round001_dqa_server_repair.pt --checkpoint round002_dqa_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_cwa_v2_aggregate.pt --checkpoint round002_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round002_dqa_server_repair.pt --checkpoint round003_dqa_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round003_dqa_cwa_v2_aggregate.pt --checkpoint round003_server_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/checkpoints/round003_dqa_server_repair.pt
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/validation_reports/paper_protocol_eval_manifest.json
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/validation_reports/paper_protocol_eval_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/validation_reports/paper_protocol_classwise_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/validation_reports/paper_protocol_eval_summary.md
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/01_round_metrics.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/01_round_metrics_summary.json

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', 'scripts/run_scene_daynight_dqa_01.py', '--workspace-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa', '--client-limit', '1500', '--rounds', '3', '--batch-size', '160', '--workers', '8', '--gpus', '2', '--master-port', '30641', '--server-repair-epochs', '1', '--evaluate', '--classwise', '--no-eval-plots'], returncode=0)

## Round Metrics

In [4]:
import json
import pandas as pd

metrics_csv = WORKSPACE / "stats" / "01_round_metrics.csv"
metrics_json = WORKSPACE / "stats" / "01_round_metrics_summary.json"
if metrics_csv.exists():
    display(pd.read_csv(metrics_csv))
else:
    print("No metrics yet:", metrics_csv)
if metrics_json.exists():
    print(json.dumps(json.loads(metrics_json.read_text()), indent=2, ensure_ascii=False))

,round,aggregate_map50_95,repaired_map50,repaired_map50_95,repair_gain_map50_95,retained_gain_map50_95,round_delta_map50_95
0,1,0.189,0.373,0.206,0.017,0.018,NaN
1,2,0.206,0.379,0.210,0.004,0.022,0.004
2,3,0.210,0.381,0.212,0.002,0.024,0.002

{
  "created_utc": "2026-05-05T07:12:21.946915+00:00",
  "warmup_map50_95": 0.188,
  "final_repaired_map50_95": 0.212,
  "last_n": 3,
  "last_n_avg_repaired_map50_95": 0.20933333333333334,
  "last_n_min_repaired_map50_95": 0.206,
  "metrics_csv": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/01_repair_oriented_scene_daynight_dqa/stats/01_round_metrics.csv"
}

## Evaluation Summary

In [5]:
summary_csv = WORKSPACE / "validation_reports" / "paper_protocol_eval_summary.csv"
if summary_csv.exists():
    df = pd.read_csv(summary_csv)
    ok = df[df["status"].eq("ok")].copy()
    total = ok[ok["split"].isin(["total", "scene_daynight_total"])].copy()
    display(total.sort_values("map50_95", ascending=False)[
        ["checkpoint_label", "split", "precision", "recall", "map50", "map50_95"]
    ])
    scene = ok[~ok["split"].isin(["total", "scene_daynight_total"])].copy()
    display(scene.sort_values(["split", "map50_95"], ascending=[True, False])[
        ["checkpoint_label", "split", "precision", "recall", "map50", "map50_95"]
    ])
else:
    print("No evaluation summary yet:", summary_csv)

,checkpoint_label,split,precision,recall,map50,map50_95
48,round003_server_repair,scene_daynight_total,0.504,0.397,0.381,0.212
34,round002_server_repair,scene_daynight_total,0.490,0.401,0.379,0.210
41,round003_dqa_aggregate,scene_daynight_total,0.491,0.400,0.378,0.210
20,round001_server_repair,scene_daynight_total,0.475,0.400,0.373,0.206
27,round002_dqa_aggregate,scene_daynight_total,0.478,0.399,0.373,0.206
13,round001_dqa_aggregate,scene_daynight_total,0.531,0.338,0.351,0.189
6,warmup_global,scene_daynight_total,0.531,0.336,0.350,0.188

,checkpoint_label,split,precision,recall,map50,map50_95
44,round003_server_repair,citystreet_day,0.512,0.426,0.412,0.233
37,round003_dqa_aggregate,citystreet_day,0.497,0.429,0.410,0.232
30,round002_server_repair,citystreet_day,0.498,0.429,0.410,0.231
16,round001_server_repair,citystreet_day,0.485,0.426,0.402,0.227
23,round002_dqa_aggregate,citystreet_day,0.486,0.426,0.403,0.227
9,round001_dqa_aggregate,citystreet_day,0.561,0.336,0.384,0.210
2,warmup_global,citystreet_day,0.558,0.336,0.383,0.209
45,round003_server_repair,citystreet_night,0.469,0.352,0.327,0.174
31,round002_server_repair,citystreet_night,0.463,0.356,0.326,0.173
38,round003_dqa_aggregate,citystreet_night,0.472,0.350,0.325,0.173
17,round001_server_repair,citystreet_night,0.450,0.357,0.321,0.169
24,round002_dqa_aggregate,citystreet_night,0.455,0.353,0.320,0.168
10,round001_dqa_aggregate,citystreet_night,0.502,0.298,0.293,0.150
3,warmup_global,citystreet_night,0.462,0.314,0.293,0.149
42,round003_server_repair,highway_day,0.565,0.375,0.375,0.212
28,round002_server_repair,highway_day,0.551,0.365,0.371,0.208
35,round003_dqa_aggregate,highway_day,0.553,0.365,0.371,0.208
14,round001_server_repair,highway_day,0.508,0.389,0.364,0.205
21,round002_dqa_aggregate,highway_day,0.511,0.388,0.365,0.205
7,round001_dqa_aggregate,highway_day,0.722,0.311,0.339,0.188
0,warmup_global,highway_day,0.710,0.314,0.337,0.187
43,round003_server_repair,highway_night,0.485,0.263,0.276,0.152
29,round002_server_repair,highway_night,0.457,0.272,0.275,0.151
36,round003_dqa_aggregate,highway_night,0.457,0.271,0.274,0.151
15,round001_server_repair,highway_night,0.436,0.281,0.273,0.148
22,round002_dqa_aggregate,highway_night,0.438,0.281,0.272,0.148
8,round001_dqa_aggregate,highway_night,0.525,0.254,0.246,0.131
1,warmup_global,highway_night,0.625,0.255,0.246,0.130
46,round003_server_repair,residential_day,0.492,0.442,0.434,0.254
32,round002_server_repair,residential_day,0.481,0.448,0.432,0.251
39,round003_dqa_aggregate,residential_day,0.479,0.447,0.432,0.251
18,round001_server_repair,residential_day,0.451,0.443,0.424,0.247
25,round002_dqa_aggregate,residential_day,0.457,0.445,0.426,0.247
11,round001_dqa_aggregate,residential_day,0.452,0.424,0.408,0.229
4,warmup_global,residential_day,0.453,0.423,0.407,0.228
33,round002_server_repair,residential_night,0.379,0.385,0.367,0.193
47,round003_server_repair,residential_night,0.380,0.392,0.368,0.193
40,round003_dqa_aggregate,residential_night,0.378,0.379,0.366,0.192
19,round001_server_repair,residential_night,0.355,0.388,0.354,0.186
26,round002_dqa_aggregate,residential_night,0.361,0.382,0.353,0.185
12,round001_dqa_aggregate,residential_night,0.726,0.269,0.339,0.172
5,warmup_global,residential_night,0.732,0.268,0.336,0.171

## DQA State

In [6]:
state_path = WORKSPACE / "stats" / "01_dqa_state.json"
if state_path.exists():
    state = json.loads(state_path.read_text())
    print(json.dumps({
        "last_sources": state.get("last_sources"),
        "last_active_classes": state.get("last_active_classes"),
        "config": state.get("config"),
    }, indent=2, ensure_ascii=False))
else:
    print("No DQA state yet:", state_path)

{
  "last_sources": [
    "client:client0_highway_day",
    "client:client1_highway_night",
    "client:client2_citystreet_day",
    "client:client3_citystreet_night",
    "client:client4_residential_day",
    "client:client5_residential_night",
    "server"
  ],
  "last_active_classes": [
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    false
  ],
  "config": {
    "alpha_ema": 0.4,
    "classwise_blend": 0.08,
    "count_ema": 0.65,
    "implementation": "dqa_ver2_server_residual_anchor",
    "localize_bn": true,
    "max_quality": 1.0,
    "min_effective_count": 5.0,
    "min_quality": 0.1,
    "min_server_alpha": 0.82,
    "num_classes": 10,
    "quality_ema": 0.65,
    "residual_blend": 0.05,
    "server_anchor": 20.0,
    "stability_lambda": 0.7,
    "temperature": 2.5,
    "uniform_mix": 0.05
  }
}

## Discord Notification

In [7]:
try:
    sys.path.insert(0, str(PROJECT_ROOT.parents[1]))
    from notebook_notify import notify_discord

    metric_line = ""
    if metrics_json.exists():
        payload = json.loads(metrics_json.read_text())
        metric_line = (
            f"final mAP50-95={payload.get('final_repaired_map50_95')}, "
            f"lastN avg={payload.get('last_n_avg_repaired_map50_95')}, "
            f"lastN min={payload.get('last_n_min_repaired_map50_95')}"
        )
    result = notify_discord(
        "Scene-Daynight DQA 01 finished. " + metric_line,
        title="Scene-Daynight DQA 01",
        context={"project": str(PROJECT_ROOT), "workspace": str(WORKSPACE)},
        fail_silently=True,
    )
    print(result)
except Exception as exc:
    print("Discord notification skipped:", exc)

DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)