# 02 Head-to-Full Long DQA

This notebook tests the new FedSTO-style DQA schedule:

- **Phase 1:** long head/neck-only DQA adaptation, default 30 rounds.
- **Phase 2:** short full-model low-LR DQA burst, default 2 rounds.
- **Evaluation:** final-focused paper-protocol evaluation only, so the
  long run stays practical.

The design goal is not to keep learning pseudoGT forever.  Phase 1
creates stable client/class/domain differences for DQA, and Phase 2
briefly lets that target signal reach the full detector.

In [1]:
from pathlib import Path
import importlib.util
import subprocess
import sys

import pandas as pd

cwd = Path.cwd().resolve()
if cwd.name == "notebooks":
    PROJECT_ROOT = cwd.parent
elif (cwd / "dynamic_quality_aware_classwise_aggregation").exists():
    PROJECT_ROOT = cwd / "dynamic_quality_aware_classwise_aggregation" / "scene_daynight_dqa"
else:
    PROJECT_ROOT = cwd

WORKSPACE = PROJECT_ROOT / "output" / "02_head_to_full_long_dqa"
RUNNER = PROJECT_ROOT / "scripts" / "run_scene_daynight_dqa_02_head_to_full.py"

print("PROJECT_ROOT", PROJECT_ROOT)
print("WORKSPACE", WORKSPACE)
print("RUNNER", RUNNER)

PROJECT_ROOT /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa
WORKSPACE /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa
RUNNER /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/run_scene_daynight_dqa_02_head_to_full.py

## Schedule And Runtime Estimate

In [2]:
PHASE1_ROUNDS = 30
PHASE2_ROUNDS = 2
PHASE1_MIN_PER_ROUND = 19.0
PHASE2_MIN_PER_ROUND = 23.0
FINAL_EVAL_MIN = 60.0

estimate = pd.DataFrame([
    {
        "stage": "Phase1 head-only",
        "rounds": PHASE1_ROUNDS,
        "minutes_per_round": PHASE1_MIN_PER_ROUND,
        "estimated_minutes": PHASE1_ROUNDS * PHASE1_MIN_PER_ROUND,
    },
    {
        "stage": "Phase2 full burst",
        "rounds": PHASE2_ROUNDS,
        "minutes_per_round": PHASE2_MIN_PER_ROUND,
        "estimated_minutes": PHASE2_ROUNDS * PHASE2_MIN_PER_ROUND,
    },
    {
        "stage": "final-focused paper eval",
        "rounds": 0,
        "minutes_per_round": None,
        "estimated_minutes": FINAL_EVAL_MIN,
    },
])
total_minutes = float(estimate["estimated_minutes"].sum())
display(estimate)
print(f"Estimated total: {total_minutes / 60:.2f} hours ({total_minutes:.0f} minutes)")

                      stage  rounds  minutes_per_round  estimated_minutes
0          Phase1 head-only      30               19.0              570.0
1         Phase2 full burst       2               23.0               46.0
2  final-focused paper eval       0                NaN               60.0

Estimated total: 11.27 hours (676 minutes)

## Runner Defaults

In [3]:
spec = importlib.util.spec_from_file_location("run_scene_daynight_dqa_02_head_to_full", RUNNER)
runner = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = runner
spec.loader.exec_module(runner)

args = runner.parse_args([])
phase1 = runner.default_phase1_spec(args)
phase2 = runner.default_phase2_spec(args)
display(pd.DataFrame([
    {"phase": "phase1", **runner.asdict(phase1)},
    {"phase": "phase2", **runner.asdict(phase2)},
]))

,phase,name,display_name,note,train_scope,aggregate_scope,client_lr0,source_repeat,pseudo_repeat,orthogonal_weight,loss_box,dqa_min_server_alpha,dqa_server_anchor,dqa_residual_blend,dqa_classwise_blend
0,phase1,phase1_head,Phase 1 head-only DQA,Long head/neck-only source-anchored pseudoGT a...,neck_head,all,0.0008,1,2,0.0001,0.005,0.70,10.0,0.14,0.16
1,phase2,phase2_full,Phase 2 full-model burst DQA,Short full-model low-LR target burst. The goal...,all,all,0.0003,1,1,0.0001,0.010,0.76,14.0,0.10,0.12

## Setup Only

In [4]:
subprocess.run([
    sys.executable,
    str(RUNNER),
    "--workspace-root", str(WORKSPACE),
    "--client-limit", "1500",
    "--phase1-rounds", str(PHASE1_ROUNDS),
    "--phase2-rounds", str(PHASE2_ROUNDS),
    "--setup-only",
], cwd=PROJECT_ROOT, check=True)

{
  "protocol": "scene_daynight_dqa_02_head_to_full_long_v1",
  "workspace": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa",
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "phase1": {
    "name": "phase1_head",
    "display_name": "Phase 1 head-only DQA",
    "note": "Long head/neck-only source-anchored pseudoGT adaptation. The goal is stable client/class/domain differentiation, not large bbox movement.",
    "train_scope": "neck_head",
    "aggregate_scope": "all",
    "client_lr0": 0.0008,
    "source_repeat": 1,
    "pseudo_repeat": 2,
    "orthogonal_weight": 0.0001,
    "loss_box": 0.005,
    "dqa_min_server_alpha": 0.7,
    "dqa_server_anchor": 10.0,
    "dqa_residual_blend": 0.14,
    "dqa_classwise_blend": 0.16
  },
  "phase2": {
    "name": "phase2_full",
    "display_name": "Phase 2 full-model burst DQA",
    "note": "Short full-model low-LR target burst. The goal is to let the Phase-1 target signal touch backbone/neck/head while keeping the pseudoGT exposure short.",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_lr0": 0.0003,
    "source_repeat": 1,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "loss_box": 0.01,
    "dqa_min_server_alpha": 0.76,
    "dqa_server_anchor": 14.0,
    "dqa_residual_blend": 0.1,
    "dqa_classwise_blend": 0.12
  },
  "total_rounds": 32,
  "estimated_runtime": "10h16m00s",
  "final_focused_evaluation": false
}
Setup complete.

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/run_scene_daynight_dqa_02_head_to_full.py', '--workspace-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa', '--client-limit', '1500', '--phase1-rounds', '30', '--phase2-rounds', '2', '--setup-only'], returncode=0)

## Run Phase1 30 / Phase2 2

The runner uses `tqdm` internally and writes live progress to:

```text
output/02_head_to_full_long_dqa/stats/02_head_to_full_progress.csv
```

Default evaluation is final-focused: warmup, Phase1 final aggregate,
Phase1 final repair, Phase2 final aggregate, and Phase2 final repair.

In [5]:
CLIENT_LIMIT = 1500
BATCH_SIZE = 160
WORKERS = 8
GPUS = 2
DEVICE = ""
MAX_IMAGES_PER_CLIENT = 0

cmd = [
    sys.executable,
    str(RUNNER),
    "--workspace-root", str(WORKSPACE),
    "--client-limit", str(CLIENT_LIMIT),
    "--phase1-rounds", str(PHASE1_ROUNDS),
    "--phase2-rounds", str(PHASE2_ROUNDS),
    "--batch-size", str(BATCH_SIZE),
    "--workers", str(WORKERS),
    "--gpus", str(GPUS),
    "--device", DEVICE,
    "--master-port", "31141",
    "--max-images-per-client", str(MAX_IMAGES_PER_CLIENT),
    "--estimated-phase1-round-minutes", str(PHASE1_MIN_PER_ROUND),
    "--estimated-phase2-round-minutes", str(PHASE2_MIN_PER_ROUND),
    "--estimated-eval-minutes", str(FINAL_EVAL_MIN),
    "--evaluate",
    "--classwise",
    "--no-eval-plots",
    "--notify",
]

print(" ".join(cmd))
subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/run_scene_daynight_dqa_02_head_to_full.py --workspace-root /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa --client-limit 1500 --phase1-rounds 30 --phase2-rounds 2 --batch-size 160 --workers 8 --gpus 2 --device  --master-port 31141 --max-images-per-client 0 --estimated-phase1-round-minutes 19.0 --estimated-phase2-round-minutes 23.0 --estimated-eval-minutes 60.0 --evaluate --classwise --no-eval-plots --notify
DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)
{
  "protocol": "scene_daynight_dqa_02_head_to_full_long_v1",
  "workspace": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa",
  "clients": [
    {
      "id": 0,
      "name": "highway_day",
      "weather": "highway_day",
      "scene": "highway",
      "timeofday": "daytime"
    },
    {
      "id": 1,
      "name": "highway_night",
      "weather": "highway_night",
      "scene": "highway",
      "timeofday": "night"
    },
    {
      "id": 2,
      "name": "citystreet_day",
      "weather": "citystreet_day",
      "scene": "city street",
      "timeofday": "daytime"
    },
    {
      "id": 3,
      "name": "citystreet_night",
      "weather": "citystreet_night",
      "scene": "city street",
      "timeofday": "night"
    },
    {
      "id": 4,
      "name": "residential_day",
      "weather": "residential_day",
      "scene": "residential",
      "timeofday": "daytime"
    },
    {
      "id": 5,
      "name": "residential_night",
      "weather": "residential_night",
      "scene": "residential",
      "timeofday": "night"
    }
  ],
  "server": {
    "weather": "cloudy represented by BDD100K Kaggle weather='partly cloudy'",
    "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.txt",
    "val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/paper_eval_scene_daynight_total_val.txt",
    "source_val_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.txt",
    "train_images": 4881,
    "val_images": 9087,
    "source_val_images": 738,
    "validation_target": "scene_daynight_total"
  },
  "phase1": {
    "name": "phase1_head",
    "display_name": "Phase 1 head-only DQA",
    "note": "Long head/neck-only source-anchored pseudoGT adaptation. The goal is stable client/class/domain differentiation, not large bbox movement.",
    "train_scope": "neck_head",
    "aggregate_scope": "all",
    "client_lr0": 0.0008,
    "source_repeat": 1,
    "pseudo_repeat": 2,
    "orthogonal_weight": 0.0001,
    "loss_box": 0.005,
    "dqa_min_server_alpha": 0.7,
    "dqa_server_anchor": 10.0,
    "dqa_residual_blend": 0.14,
    "dqa_classwise_blend": 0.16
  },
  "phase2": {
    "name": "phase2_full",
    "display_name": "Phase 2 full-model burst DQA",
    "note": "Short full-model low-LR target burst. The goal is to let the Phase-1 target signal touch backbone/neck/head while keeping the pseudoGT exposure short.",
    "train_scope": "all",
    "aggregate_scope": "all",
    "client_lr0": 0.0003,
    "source_repeat": 1,
    "pseudo_repeat": 1,
    "orthogonal_weight": 0.0001,
    "loss_box": 0.01,
    "dqa_min_server_alpha": 0.76,
    "dqa_server_anchor": 14.0,
    "dqa_residual_blend": 0.1,
    "dqa_classwise_blend": 0.12
  },
  "total_rounds": 32,
  "estimated_runtime": "11h16m00s",
  "final_focused_evaluation": true
}

=== Phase 1 head-only DQA: round001 phase_round=1 ===

02 head-to-full DQA:   0%|          | 0/32 [00:00<?, ?round/s]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
/root/micromamba/envs/al_yolov8/lib/python3.10/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4322.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

round001 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round001 client0_highway_day: pseudo scan 250/1500 images, kept 2318 boxes
round001 client0_highway_day: pseudo scan 500/1500 images, kept 4696 boxes
round001 client0_highway_day: pseudo scan 750/1500 images, kept 7005 boxes
round001 client0_highway_day: pseudo scan 1000/1500 images, kept 9304 boxes
round001 client0_highway_day: pseudo scan 1250/1500 images, kept 11580 boxes
round001 client0_highway_day: pseudo scan 1500/1500 images, kept 13881 boxes
{
  "round": "round001",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 10812,
  "boxes_per_kept_image": 7.266129032258065,
  "mean_conf": 0.7457716877548465,
  "mean_stability": 0.9449824729243165,
  "mean_score": 0.707788491927951,
  "class_counts": {
    "0": 150,
    "2": 6247,
    "3": 76,
    "4": 413,
    "5": 9,
    "7": 600,
    "8": 3317
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_client0_highway_day_stable_boxes.csv"
}
round001 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round001 client1_highway_night: pseudo scan 250/1500 images, kept 1790 boxes
round001 client1_highway_night: pseudo scan 500/1500 images, kept 3679 boxes
round001 client1_highway_night: pseudo scan 750/1500 images, kept 5547 boxes
round001 client1_highway_night: pseudo scan 1000/1500 images, kept 7377 boxes
round001 client1_highway_night: pseudo scan 1250/1500 images, kept 9229 boxes
round001 client1_highway_night: pseudo scan 1500/1500 images, kept 11039 boxes
{
  "round": "round001",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 9263,
  "boxes_per_kept_image": 6.2757452574525745,
  "mean_conf": 0.6454818118027807,
  "mean_stability": 0.9220161875161936,
  "mean_score": 0.5989198160330051,
  "class_counts": {
    "0": 54,
    "2": 4968,
    "3": 31,
    "4": 118,
    "5": 5,
    "7": 689,
    "8": 3398
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_client1_highway_night_stable_boxes.csv"
}
round001 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round001 client2_citystreet_day: pseudo scan 250/1500 images, kept 2691 boxes
round001 client2_citystreet_day: pseudo scan 500/1500 images, kept 5390 boxes
round001 client2_citystreet_day: pseudo scan 750/1500 images, kept 8121 boxes
round001 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10875 boxes
round001 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13593 boxes
round001 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16254 boxes
{
  "round": "round001",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13789,
  "boxes_per_kept_image": 9.217245989304812,
  "mean_conf": 0.7347438888736023,
  "mean_stability": 0.9405868294681854,
  "mean_score": 0.6943373476162771,
  "class_counts": {
    "0": 1331,
    "2": 7315,
    "3": 144,
    "4": 468,
    "5": 51,
    "7": 1669,
    "8": 2811
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_client2_citystreet_day_stable_boxes.csv"
}
round001 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round001 client3_citystreet_night: pseudo scan 250/1500 images, kept 2426 boxes
round001 client3_citystreet_night: pseudo scan 500/1500 images, kept 4816 boxes
round001 client3_citystreet_night: pseudo scan 750/1500 images, kept 7166 boxes
round001 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9450 boxes
round001 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11940 boxes
round001 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14338 boxes
{
  "round": "round001",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1484,
  "pseudo_boxes_kept": 12497,
  "boxes_per_kept_image": 8.421159029649596,
  "mean_conf": 0.646182291446385,
  "mean_stability": 0.9195552923073241,
  "mean_score": 0.5980796055061397,
  "class_counts": {
    "0": 515,
    "2": 6453,
    "3": 55,
    "4": 112,
    "5": 23,
    "7": 2226,
    "8": 3113
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_client3_citystreet_night_stable_boxes.csv"
}
round001 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round001 client4_residential_day: pseudo scan 250/1500 images, kept 2559 boxes
round001 client4_residential_day: pseudo scan 500/1500 images, kept 5142 boxes
round001 client4_residential_day: pseudo scan 750/1500 images, kept 7673 boxes
round001 client4_residential_day: pseudo scan 1000/1500 images, kept 10131 boxes
round001 client4_residential_day: pseudo scan 1250/1500 images, kept 12644 boxes
round001 client4_residential_day: pseudo scan 1500/1500 images, kept 15096 boxes
{
  "round": "round001",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9829,
  "boxes_per_kept_image": 6.605510752688172,
  "mean_conf": 0.7713916716212743,
  "mean_stability": 0.9511923203937447,
  "mean_score": 0.7369318894765382,
  "class_counts": {
    "0": 360,
    "2": 6794,
    "3": 41,
    "4": 228,
    "5": 27,
    "7": 556,
    "8": 1823
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_client4_residential_day_stable_boxes.csv"
}
round001 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round001 client5_residential_night: pseudo scan 250/1500 images, kept 2393 boxes
round001 client5_residential_night: pseudo scan 500/1500 images, kept 4739 boxes
round001 client5_residential_night: pseudo scan 750/1500 images, kept 7070 boxes
round001 client5_residential_night: pseudo scan 1000/1500 images, kept 9441 boxes
round001 client5_residential_night: pseudo scan 1250/1500 images, kept 11853 boxes
round001 client5_residential_night: pseudo scan 1500/1500 images, kept 14267 boxes
{
  "round": "round001",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/round000_warmup.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1486,
  "pseudo_boxes_kept": 9287,
  "boxes_per_kept_image": 6.2496635262449525,
  "mean_conf": 0.7027750300574228,
  "mean_stability": 0.9328271249491495,
  "mean_score": 0.6585657579519052,
  "class_counts": {
    "0": 115,
    "2": 6421,
    "3": 28,
    "4": 69,
    "5": 15,
    "7": 735,
    "8": 1904
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round001_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31141 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round001_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round001_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7857 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client0_highway_day_stable_train' images and labels...5359 found, 2498 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<00:00, 18467.28it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.843882544861337
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2498 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val' images and labels...738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<00:00, 8358.32it/s]
val: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:09:33.899823936 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:09:33.907301631 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2007       640  0.003829   0.04652  0.006387     4.539:   3%|▎         | 1/39 [00:21<13:30, 21.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1914       640  0.003914   0.04594  0.006058     4.473:   5%|▌         | 2/39 [00:22<05:43,  9.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2240       640  0.003915   0.04563  0.006191     4.459:   8%|▊         | 3/39 [00:23<03:15,  5.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1973       640  0.003881   0.04567  0.005979     4.443:  10%|█         | 4/39 [00:23<02:06,  3.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2097       640  0.003855   0.04524  0.005749     4.387:  13%|█▎        | 5/39 [00:24<01:27,  2.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1828       640  0.003843    0.0446  0.005747     4.335:  15%|█▌        | 6/39 [00:25<01:03,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1893       640   0.00382   0.04406  0.005675     4.285:  18%|█▊        | 7/39 [00:25<00:47,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2178       640  0.003807   0.04404  0.005604     4.276:  21%|██        | 8/39 [00:26<00:37,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2177       640   0.00381   0.04418  0.005606     4.288:  23%|██▎       | 9/39 [00:27<00:31,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1891       640  0.003806   0.04409  0.005729      4.29:  26%|██▌       | 10/39 [00:27<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2046       640  0.003788   0.04412  0.005691     4.288:  28%|██▊       | 11/39 [00:28<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1922       640  0.003774   0.04393  0.005669      4.27:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1825       640  0.003749   0.04364  0.005649     4.243:  33%|███▎      | 13/39 [00:29<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2042       640  0.003736   0.04354  0.005598      4.23:  36%|███▌      | 14/39 [00:30<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2045       640  0.003739    0.0435  0.005625     4.229:  38%|███▊      | 15/39 [00:30<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1837       640  0.003731   0.04324  0.005622     4.207:  41%|████      | 16/39 [00:31<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1742       640  0.003723   0.04303  0.005624     4.191:  44%|████▎     | 17/39 [00:32<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1997       640  0.003713   0.04296  0.005614     4.183:  46%|████▌     | 18/39 [00:32<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1673       640  0.003706   0.04277  0.005616     4.168:  49%|████▊     | 19/39 [00:33<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2254       640  0.003702   0.04293   0.00561     4.179:  51%|█████▏    | 20/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2071       640  0.003703   0.04293  0.005601     4.179:  54%|█████▍    | 21/39 [00:34<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1786       640  0.003702   0.04286  0.005633     4.176:  56%|█████▋    | 22/39 [00:35<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2126       640  0.003692    0.0429   0.00558     4.174:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2061       640  0.003684   0.04287  0.005559     4.169:  62%|██████▏   | 24/39 [00:36<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2155       640  0.003686    0.0429  0.005563     4.172:  64%|██████▍   | 25/39 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2054       640  0.003682   0.04293  0.005562     4.174:  67%|██████▋   | 26/39 [00:38<00:08,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.467      0.441      0.395      0.219
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.515      0.398      0.394       0.22
                   0        738       1052      0.505      0.547      0.532       0.25
                   1        738         44      0.382      0.114      0.151     0.0667
                   2        738       8622      0.675      0.722      0.745      0.476
                   3        738        151      0.413      0.344      0.376       0.29
                   4        738        467      0.496      0.563      0.539      0.384
                   5        738         70      0.279      0.443      0.268      0.134
                   6        738         65      0.231     0.0615      0.148     0.0499
                   7        738       1619      0.547      0.599      0.585      0.239
                   8        738       2845      0.626      0.585      0.595      0.305
                   9        738          2          1          0   0.000284   0.000284

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:10:58.934320432 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31142 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round001_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round001_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client1_highway_night_stable_train' images and labels...4895 found, 2938 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<00:00, 10168.57it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29496062992126
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2938 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:11:15.572425358 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:11:15.630077430 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2011       640  0.004001    0.0454  0.006483     4.471:   2%|▎         | 1/40 [00:21<14:07, 21.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.004024   0.04349  0.006125     4.291:   5%|▌         | 2/40 [00:22<06:00,  9.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1708       640  0.003907   0.04183  0.005717     4.116:   8%|▊         | 3/40 [00:23<03:25,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2074       640  0.003871   0.04147   0.00563     4.078:  10%|█         | 4/40 [00:24<02:13,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003852   0.04143  0.005625     4.073:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1807       640  0.003822   0.04063  0.005626     4.006:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2020       640  0.003811    0.0404  0.005655     3.989:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640   0.00379   0.04025  0.005633     3.974:  20%|██        | 8/40 [00:27<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003787   0.04014  0.005628     3.965:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1950       640  0.003782   0.04016  0.005663     3.968:  25%|██▌       | 10/40 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2026       640  0.003766   0.04036    0.0056     3.978:  28%|██▊       | 11/40 [00:28<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1907       640  0.003751   0.04016   0.00557     3.958:  30%|███       | 12/40 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003741   0.03988   0.00562     3.939:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003727   0.03961  0.005631     3.917:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003717   0.03944  0.005678     3.907:  38%|███▊      | 15/40 [00:31<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003705    0.0395  0.005683     3.911:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1696       640    0.0037   0.03923  0.005658     3.887:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640   0.00369   0.03919  0.005682     3.885:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1652       640  0.003688   0.03899  0.005696      3.87:  48%|████▊     | 19/40 [00:33<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1969       640   0.00368   0.03891  0.005678     3.862:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640  0.003682   0.03891  0.005687     3.862:  52%|█████▎    | 21/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2166       640  0.003677   0.03897  0.005654     3.864:  55%|█████▌    | 22/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2059       640  0.003674   0.03908   0.00564     3.872:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1663       640  0.003671   0.03893  0.005649      3.86:  60%|██████    | 24/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1978       640  0.003666   0.03887   0.00564     3.854:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640   0.00366   0.03875  0.005634     3.844:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.49      0.423      0.393      0.217
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.472      0.426      0.391      0.217
                   0        738       1052      0.445      0.569      0.526      0.247
                   1        738         44       0.41      0.159      0.156     0.0671
                   2        738       8622      0.591      0.745      0.743      0.472
                   3        738        151      0.341      0.371      0.375      0.283
                   4        738        467       0.42      0.604       0.54      0.388
                   5        738         70      0.244      0.443      0.264      0.132
                   6        738         65      0.235      0.123       0.14     0.0472
                   7        738       1619      0.498      0.626      0.575      0.236
                   8        738       2845       0.54      0.617      0.589      0.298
                   9        738          2          1          0   0.000278    0.00025

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:12:41.926751815 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31143 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round001_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round001_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train' images and labels...:   0%|          | 0/7873 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 9472.22it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:12:57.144605350 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:12:57.155708347 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2061       640  0.003962   0.05109  0.006092     4.891:   3%|▎         | 1/39 [00:22<14:18, 22.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2096       640  0.003915    0.0509  0.006264     4.886:   5%|▌         | 2/39 [00:23<06:03,  9.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003882   0.04967  0.006237     4.783:   8%|▊         | 3/39 [00:24<03:26,  5.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2004       640   0.00389   0.04838  0.006069     4.667:  10%|█         | 4/39 [00:25<02:13,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003875   0.04814  0.005901     4.633:  13%|█▎        | 5/39 [00:25<01:30,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1782       640  0.003832   0.04721  0.005905     4.555:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1994       640  0.003828   0.04706   0.00598     4.549:  18%|█▊        | 7/39 [00:27<00:50,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1873       640  0.003805   0.04672  0.005922     4.516:  21%|██        | 8/39 [00:27<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003806   0.04669  0.005847     4.508:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003781   0.04657  0.005842     4.496:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1993       640  0.003774   0.04647  0.005845     4.487:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1880       640  0.003766   0.04619  0.005836     4.464:  31%|███       | 12/39 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2059       640  0.003761   0.04609  0.005775      4.45:  33%|███▎      | 13/39 [00:31<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640  0.003759   0.04619  0.005733     4.454:  36%|███▌      | 14/39 [00:31<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003752   0.04609  0.005702     4.444:  38%|███▊      | 15/39 [00:32<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1905       640  0.003735   0.04581  0.005697      4.42:  41%|████      | 16/39 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1487       640  0.003721   0.04555  0.005716     4.399:  44%|████▎     | 17/39 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003706   0.04543  0.005692     4.386:  46%|████▌     | 18/39 [00:34<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1723       640  0.003702   0.04517   0.00566     4.363:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2087       640  0.003691   0.04525  0.005633     4.366:  51%|█████▏    | 20/39 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1847       640   0.00368   0.04505  0.005612     4.348:  54%|█████▍    | 21/39 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003674   0.04499    0.0056     4.341:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1791       640  0.003665   0.04483  0.005586     4.326:  59%|█████▉    | 23/39 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003658   0.04476  0.005573     4.319:  62%|██████▏   | 24/39 [00:38<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640  0.003651   0.04469  0.005554     4.311:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003642   0.04463  0.005538     4.305:  67%|██████▋   | 26/39 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.508      0.408      0.395      0.218
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.502      0.414      0.396       0.22
                   0        738       1052      0.566      0.539      0.536       0.25
                   1        738         44      0.436      0.158      0.159     0.0677
                   2        738       8622      0.612      0.746      0.749      0.475
                   3        738        151      0.319      0.371      0.374      0.289
                   4        738        467      0.441      0.591      0.541      0.386
                   5        738         70       0.28      0.414      0.264      0.126
                   6        738         65       0.27     0.0923      0.157     0.0567
                   7        738       1619      0.525      0.616      0.579      0.238
                   8        738       2845       0.57      0.611      0.597      0.309
                   9        738          2          1          0   0.000254   0.000229

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:14:24.601901177 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31144 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round001_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round001_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train' images and labels...4883 found, 2966 missing, 0 empty, 0 corrupted: 100%|██████████| 7849/7849 [00:00<00:00, 10445.63it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.261313639220615
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2966 missing, 0 empty, 0 corrupted: 100%|██████████| 7849/7849 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:14:40.123840693 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:14:40.128945989 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1823       640  0.003895   0.04437    0.0053     4.285:   2%|▎         | 1/40 [00:21<14:09, 21.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003867   0.04578   0.00533     4.398:   5%|▌         | 2/40 [00:22<05:59,  9.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1880       640  0.003899   0.04496    0.0053     4.333:   8%|▊         | 3/40 [00:23<03:24,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2068       640  0.003886   0.04413  0.005407     4.274:  10%|█         | 4/40 [00:24<02:12,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003871   0.04388  0.005432     4.254:  12%|█▎        | 5/40 [00:25<01:30,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003881   0.04324   0.00558     4.216:  15%|█▌        | 6/40 [00:25<01:05,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003844   0.04288  0.005575     4.184:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2009       640  0.003833   0.04292  0.005501     4.181:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003816   0.04311  0.005483     4.193:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1704       640  0.003802   0.04275  0.005604     4.172:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003793   0.04272  0.005633     4.172:  28%|██▊       | 11/40 [00:28<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1687       640  0.003772   0.04234  0.005616     4.138:  30%|███       | 12/40 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640   0.00376   0.04226  0.005614     4.131:  32%|███▎      | 13/40 [00:30<00:20,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2011       640  0.003751   0.04218  0.005609     4.123:  35%|███▌      | 14/40 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003741   0.04218  0.005661     4.126:  38%|███▊      | 15/40 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003745   0.04203  0.005656     4.114:  40%|████      | 16/40 [00:32<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1656       640  0.003736    0.0417  0.005676     4.089:  42%|████▎     | 17/40 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2124       640  0.003732   0.04161  0.005655      4.08:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1755       640  0.003734   0.04141   0.00567     4.065:  48%|████▊     | 19/40 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2122       640  0.003727   0.04141  0.005637     4.062:  50%|█████     | 20/40 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640   0.00373   0.04136  0.005655      4.06:  52%|█████▎    | 21/40 [00:35<00:12,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640   0.00373   0.04134   0.00565     4.057:  55%|█████▌    | 22/40 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003724   0.04118   0.00565     4.045:  57%|█████▊    | 23/40 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2078       640  0.003723   0.04119  0.005648     4.045:  60%|██████    | 24/40 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003722    0.0411  0.005635     4.036:  62%|██████▎   | 25/40 [00:38<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003716     0.041  0.005611     4.026:  65%|██████▌   | 26/40 [00:38<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.466      0.441       0.39      0.215
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.496      0.404      0.388      0.215
                   0        738       1052      0.538      0.518      0.518      0.243
                   1        738         44      0.436      0.136      0.148     0.0645
                   2        738       8622      0.624      0.729      0.737      0.462
                   3        738        151      0.357      0.351      0.378      0.287
                   4        738        467       0.44      0.597      0.542      0.387
                   5        738         70      0.266      0.429      0.261      0.124
                   6        738         65      0.217     0.0769      0.138     0.0469
                   7        738       1619      0.518      0.605      0.568      0.233
                   8        738       2845      0.563      0.603      0.586      0.305
                   9        738          2          1          0   0.000234   0.000234

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:16:08.309305748 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31145 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round001_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round001_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client4_residential_day_stable_train' images and labels...5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<00:00, 9491.24it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:16:25.249526925 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:16:25.251526010 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2090       640  0.003885   0.05011  0.005952     4.795:   3%|▎         | 1/39 [00:21<13:53, 21.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2144       640  0.003867   0.04978   0.00597     4.769:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1953       640  0.003851   0.04871   0.00584     4.672:   8%|▊         | 3/39 [00:23<03:20,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2117       640  0.003846   0.04804  0.005962     4.627:  10%|█         | 4/39 [00:24<02:09,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2267       640  0.003838    0.0479  0.005823     4.605:  13%|█▎        | 5/39 [00:25<01:28,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1698       640  0.003805   0.04629  0.005779      4.47:  15%|█▌        | 6/39 [00:25<01:03,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003816   0.04623   0.00583      4.47:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2155       640  0.003806   0.04601  0.005809      4.45:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2153       640  0.003797   0.04613  0.005719     4.452:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003784   0.04592   0.00571     4.433:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003768   0.04545  0.005706     4.394:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003754   0.04525  0.005726     4.378:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2121       640  0.003754    0.0454  0.005661     4.385:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003738   0.04507  0.005609     4.353:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003731   0.04494  0.005607     4.342:  38%|███▊      | 15/39 [00:31<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2079       640  0.003725   0.04479  0.005629     4.332:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003722   0.04478  0.005646     4.332:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1983       640  0.003711   0.04472  0.005612     4.323:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003701   0.04446  0.005547     4.296:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2068       640  0.003691   0.04441  0.005537     4.291:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003683   0.04431  0.005522     4.282:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2102       640  0.003682   0.04442  0.005511     4.289:  56%|█████▋    | 22/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003678   0.04436  0.005523     4.285:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2044       640  0.003671   0.04439  0.005505     4.285:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640   0.00367    0.0443  0.005484     4.276:  64%|██████▍   | 25/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003667   0.04425  0.005499     4.274:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.466      0.441      0.395      0.218
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.454      0.448      0.395      0.218
                   0        738       1052      0.437      0.569       0.53      0.248
                   1        738         44      0.296      0.205      0.149     0.0637
                   2        738       8622      0.593      0.749      0.744      0.471
                   3        738        151      0.318      0.424      0.387      0.292
                   4        738        467      0.398      0.623      0.544      0.386
                   5        738         70      0.236      0.443      0.268      0.125
                   6        738         65       0.25        0.2      0.153     0.0502
                   7        738       1619      0.481      0.636      0.582      0.241
                   8        738       2845      0.529      0.628      0.596      0.307
                   9        738          2          1          0   0.000235   0.000212

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:17:49.724830925 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31146 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round001_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round001_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client5_residential_night_stable_train' images and labels...4885 found, 2968 missing, 0 empty, 0 corrupted: 100%|██████████| 7853/7853 [00:00<00:00, 10635.97it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.258915946582874
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round001_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2968 missing, 0 empty, 0 corrupted: 100%|██████████| 7853/7853 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:18:06.405649675 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:18:06.462617391 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2144       640  0.003917   0.04362  0.005932     4.277:   2%|▎         | 1/40 [00:22<14:52, 22.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1761       640  0.003854   0.04286  0.005866     4.206:   5%|▌         | 2/40 [00:23<06:19,  9.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1973       640  0.003835   0.04315  0.005627     4.209:   8%|▊         | 3/40 [00:24<03:35,  5.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1984       640  0.003812   0.04296  0.005423     4.176:  10%|█         | 4/40 [00:25<02:19,  3.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1953       640  0.003772   0.04281  0.005383     4.157:  12%|█▎        | 5/40 [00:26<01:39,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1797       640   0.00378   0.04231  0.005402     4.119:  15%|█▌        | 6/40 [00:27<01:12,  2.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2171       640  0.003796   0.04276  0.005458     4.161:  18%|█▊        | 7/40 [00:28<00:54,  1.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2026       640  0.003802    0.0427  0.005482     4.159:  20%|██        | 8/40 [00:28<00:43,  1.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1993       640  0.003783   0.04253  0.005458     4.142:  22%|██▎       | 9/40 [00:29<00:35,  1.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1917       640   0.00376   0.04246   0.00549     4.137:  25%|██▌       | 10/40 [00:30<00:29,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2020       640  0.003751    0.0422  0.005472     4.114:  28%|██▊       | 11/40 [00:30<00:25,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1814       640  0.003741   0.04204   0.00546     4.099:  30%|███       | 12/40 [00:31<00:22,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1950       640  0.003727   0.04195  0.005455     4.091:  32%|███▎      | 13/40 [00:31<00:20,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2051       640   0.00372   0.04198  0.005445     4.092:  35%|███▌      | 14/40 [00:32<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003703   0.04186  0.005447     4.081:  38%|███▊      | 15/40 [00:33<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1866       640  0.003697   0.04172  0.005453     4.069:  40%|████      | 16/40 [00:33<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1835       640  0.003694   0.04153  0.005438     4.053:  42%|████▎     | 17/40 [00:34<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640  0.003695   0.04147  0.005468     4.051:  45%|████▌     | 18/40 [00:35<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003689   0.04116  0.005473     4.026:  48%|████▊     | 19/40 [00:35<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2085       640  0.003687   0.04108  0.005474     4.019:  50%|█████     | 20/40 [00:36<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1919       640  0.003692   0.04092  0.005508     4.009:  52%|█████▎    | 21/40 [00:37<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1959       640   0.00369   0.04083  0.005474         4:  55%|█████▌    | 22/40 [00:37<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1778       640  0.003686   0.04075   0.00547     3.993:  57%|█████▊    | 23/40 [00:38<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1973       640  0.003681   0.04066  0.005506     3.988:  60%|██████    | 24/40 [00:38<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2052       640  0.003678    0.0406  0.005504     3.983:  62%|██████▎   | 25/40 [00:39<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1924       640  0.003676   0.04048    0.0055     3.972:  65%|██████▌   | 26/40 [00:40<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.514      0.401      0.392      0.217
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.497      0.403      0.389      0.217
                   0        738       1052      0.504      0.536      0.525      0.244
                   1        738         44      0.498      0.159      0.168     0.0722
                   2        738       8622      0.623      0.731      0.735      0.462
                   3        738        151      0.359      0.351      0.381      0.289
                   4        738        467      0.451      0.585      0.543      0.388
                   5        738         70      0.248      0.386      0.262       0.13
                   6        738         65      0.206     0.0615      0.121     0.0429
                   7        738       1619      0.522       0.61      0.571      0.235
                   8        738       2845      0.558      0.611      0.589      0.305
                   9        738          2          1          0   0.000192   0.000173

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:19:34.756999239 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31147 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round001_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round001_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train' images and labels...4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<00:00, 12249.51it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:19:52.915740578 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:19:52.922063240 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03814   0.04558  0.005682     7.152:   3%|▎         | 1/31 [00:32<16:09, 32.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.5G      2744       640   0.03867   0.04658  0.005903     7.292:   6%|▋         | 2/31 [00:33<06:39, 13.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640    0.0382   0.04563  0.005854     7.175:  10%|▉         | 3/31 [00:33<03:39,  7.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03754   0.04395  0.005646     6.971:  13%|█▎        | 4/31 [00:34<02:16,  5.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.03726   0.04411  0.005657     6.962:  16%|█▌        | 5/31 [00:35<01:29,  3.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03722   0.04406  0.005714     6.959:  19%|█▉        | 6/31 [00:35<01:01,  2.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640    0.0372   0.04372  0.005778     6.936:  23%|██▎       | 7/31 [00:36<00:44,  1.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.03704    0.0438   0.00581     6.932:  26%|██▌       | 8/31 [00:36<00:33,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.03697    0.0437  0.005717     6.911:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.03683   0.04379  0.005689     6.905:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.03671   0.04378  0.005696     6.895:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.03653   0.04346  0.005671     6.853:  39%|███▊      | 12/31 [00:39<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.03643    0.0435  0.005611     6.843:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.03637   0.04325  0.005568     6.815:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.03633   0.04313  0.005595     6.805:  48%|████▊     | 15/31 [00:41<00:12,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.03626   0.04295  0.005574     6.783:  52%|█████▏    | 16/31 [00:41<00:10,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.03623   0.04297  0.005525     6.778:  55%|█████▍    | 17/31 [00:42<00:09,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03622   0.04298  0.005478     6.774:  58%|█████▊    | 18/31 [00:43<00:08,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640    0.0361    0.0428  0.005433     6.746:  61%|██████▏   | 19/31 [00:43<00:07,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03603   0.04299  0.005432     6.756:  65%|██████▍   | 20/31 [00:44<00:06,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03601   0.04297  0.005441     6.754:  68%|██████▊   | 21/31 [00:44<00:06,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03597   0.04305  0.005399     6.753:  71%|███████   | 22/31 [00:45<00:05,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03591   0.04305  0.005384     6.747:  74%|███████▍  | 23/31 [00:46<00:04,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03588   0.04309  0.005358     6.746:  77%|███████▋  | 24/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03584   0.04299  0.005357     6.735:  81%|████████  | 25/31 [00:47<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03585   0.04299  0.005346     6.735:  84%|████████▍ | 26/31 [00:47<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.462      0.452        0.4      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]

                 all        738      14937      0.459       0.45      0.399      0.224
                   0        738       1052      0.444      0.579      0.543      0.254
                   1        738         44      0.302      0.182      0.153      0.058
                   2        738       8622      0.566      0.764      0.752      0.484
                   3        738        151      0.314      0.411      0.373      0.288
                   4        738        467      0.432      0.608      0.547      0.398
                   5        738         70      0.253      0.471      0.274      0.132
                   6        738         65      0.277        0.2      0.157     0.0615
                   7        738       1619      0.496      0.631      0.578       0.24
                   8        738       2845      0.505      0.655      0.613      0.321
                   9        738          2          1          0   0.000306   0.000275

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round001_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 14:21:33.334654080 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round002 phase_round=2 ===

02 head-to-full DQA:   3%|▎         | 1/32 [14:14<7:21:33, 854.63s/round, elapsed=14m14s, eta=7h21m33s, phase=phase1_head, round=1]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round002 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round002 client0_highway_day: pseudo scan 250/1500 images, kept 2371 boxes
round002 client0_highway_day: pseudo scan 500/1500 images, kept 4808 boxes
round002 client0_highway_day: pseudo scan 750/1500 images, kept 7162 boxes
round002 client0_highway_day: pseudo scan 1000/1500 images, kept 9521 boxes
round002 client0_highway_day: pseudo scan 1250/1500 images, kept 11846 boxes
round002 client0_highway_day: pseudo scan 1500/1500 images, kept 14217 boxes
{
  "round": "round002",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round001_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11075,
  "boxes_per_kept_image": 7.417950435365037,
  "mean_conf": 0.7783135750169948,
  "mean_stability": 0.9525503536971375,
  "mean_score": 0.7445040404348245,
  "class_counts": {
    "0": 152,
    "2": 6398,
    "3": 84,
    "4": 496,
    "5": 6,
    "7": 569,
    "8": 3370
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_client0_highway_day_stable_boxes.csv"
}
round002 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round002 client1_highway_night: pseudo scan 250/1500 images, kept 1753 boxes
round002 client1_highway_night: pseudo scan 500/1500 images, kept 3621 boxes
round002 client1_highway_night: pseudo scan 750/1500 images, kept 5466 boxes
round002 client1_highway_night: pseudo scan 1000/1500 images, kept 7262 boxes
round002 client1_highway_night: pseudo scan 1250/1500 images, kept 9082 boxes
round002 client1_highway_night: pseudo scan 1500/1500 images, kept 10882 boxes
{
  "round": "round002",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round001_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 8932,
  "boxes_per_kept_image": 6.051490514905149,
  "mean_conf": 0.6813852704671056,
  "mean_stability": 0.93400158739469,
  "mean_score": 0.6403870995367117,
  "class_counts": {
    "0": 59,
    "2": 4897,
    "3": 26,
    "4": 145,
    "5": 6,
    "7": 565,
    "8": 3234
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_client1_highway_night_stable_boxes.csv"
}
round002 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round002 client2_citystreet_day: pseudo scan 250/1500 images, kept 2697 boxes
round002 client2_citystreet_day: pseudo scan 500/1500 images, kept 5415 boxes
round002 client2_citystreet_day: pseudo scan 750/1500 images, kept 8149 boxes
round002 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10910 boxes
round002 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13632 boxes
round002 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16285 boxes
{
  "round": "round002",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round001_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13722,
  "boxes_per_kept_image": 9.172459893048128,
  "mean_conf": 0.7725388906801638,
  "mean_stability": 0.9501025252822815,
  "mean_score": 0.7373142941304802,
  "class_counts": {
    "0": 1401,
    "2": 7329,
    "3": 151,
    "4": 568,
    "5": 50,
    "7": 1567,
    "8": 2656
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_client2_citystreet_day_stable_boxes.csv"
}
round002 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round002 client3_citystreet_night: pseudo scan 250/1500 images, kept 2438 boxes
round002 client3_citystreet_night: pseudo scan 500/1500 images, kept 4841 boxes
round002 client3_citystreet_night: pseudo scan 750/1500 images, kept 7215 boxes
round002 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9534 boxes
round002 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11995 boxes
round002 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14387 boxes
{
  "round": "round002",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round001_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1480,
  "pseudo_boxes_kept": 12114,
  "boxes_per_kept_image": 8.185135135135136,
  "mean_conf": 0.6859760488001687,
  "mean_stability": 0.9324678375822533,
  "mean_score": 0.643761195297755,
  "class_counts": {
    "0": 527,
    "2": 6475,
    "3": 55,
    "4": 156,
    "5": 24,
    "7": 1942,
    "8": 2935
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_client3_citystreet_night_stable_boxes.csv"
}
round002 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round002 client4_residential_day: pseudo scan 250/1500 images, kept 2577 boxes
round002 client4_residential_day: pseudo scan 500/1500 images, kept 5163 boxes
round002 client4_residential_day: pseudo scan 750/1500 images, kept 7724 boxes
round002 client4_residential_day: pseudo scan 1000/1500 images, kept 10197 boxes
round002 client4_residential_day: pseudo scan 1250/1500 images, kept 12731 boxes
round002 client4_residential_day: pseudo scan 1500/1500 images, kept 15212 boxes
{
  "round": "round002",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round001_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9896,
  "boxes_per_kept_image": 6.637156270959088,
  "mean_conf": 0.8118307226387936,
  "mean_stability": 0.9587857674810322,
  "mean_score": 0.7815817068405366,
  "class_counts": {
    "0": 368,
    "2": 6846,
    "3": 39,
    "4": 293,
    "5": 28,
    "7": 537,
    "8": 1785
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_client4_residential_day_stable_boxes.csv"
}
round002 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round002 client5_residential_night: pseudo scan 250/1500 images, kept 2409 boxes
round002 client5_residential_night: pseudo scan 500/1500 images, kept 4770 boxes
round002 client5_residential_night: pseudo scan 750/1500 images, kept 7136 boxes
round002 client5_residential_night: pseudo scan 1000/1500 images, kept 9567 boxes
round002 client5_residential_night: pseudo scan 1250/1500 images, kept 11986 boxes
round002 client5_residential_night: pseudo scan 1500/1500 images, kept 14433 boxes
{
  "round": "round002",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round001_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1480,
  "pseudo_boxes_kept": 9051,
  "boxes_per_kept_image": 6.1155405405405405,
  "mean_conf": 0.760896747865778,
  "mean_stability": 0.9454105147840226,
  "mean_score": 0.7222021281718457,
  "class_counts": {
    "0": 124,
    "2": 6495,
    "3": 25,
    "4": 95,
    "5": 13,
    "7": 626,
    "8": 1673
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round002_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31148 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round002_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round002_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client0_highway_day_stable_train' images and labels...5361 found, 2506 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 12273.01it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.83355070101076
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2506 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:23:50.189313405 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:23:50.217904958 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1957       640  0.003578   0.04252  0.005085     4.095:   3%|▎         | 1/39 [00:22<14:02, 22.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2149       640  0.003552   0.04279  0.004908       4.1:   5%|▌         | 2/39 [00:23<05:56,  9.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2119       640  0.003549   0.04376  0.004903     4.177:   8%|▊         | 3/39 [00:23<03:22,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1964       640  0.003516   0.04367  0.005005     4.175:  10%|█         | 4/39 [00:24<02:11,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1859       640  0.003518    0.0432  0.004919     4.131:  13%|█▎        | 5/39 [00:25<01:30,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1608       640  0.003474   0.04205  0.004833     4.028:  15%|█▌        | 6/39 [00:26<01:05,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2226       640  0.003481   0.04218  0.004879     4.044:  18%|█▊        | 7/39 [00:26<00:50,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2226       640  0.003489   0.04262  0.004943     4.084:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1973       640  0.003496   0.04259  0.004967     4.084:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2122       640  0.003517   0.04288  0.005018     4.113:  26%|██▌       | 10/39 [00:28<00:27,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2010       640  0.003506   0.04258  0.005015     4.088:  28%|██▊       | 11/39 [00:29<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2047       640  0.003501   0.04254  0.005054     4.088:  31%|███       | 12/39 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003493   0.04239  0.005032     4.073:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2361       640  0.003499   0.04271  0.005004     4.097:  36%|███▌      | 14/39 [00:31<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2043       640  0.003495   0.04267  0.004988     4.092:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2001       640  0.003497   0.04268  0.004989     4.093:  41%|████      | 16/39 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1807       640  0.003498   0.04241  0.005009     4.073:  44%|████▎     | 17/39 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2050       640    0.0035   0.04241  0.005047     4.077:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1707       640  0.003489   0.04226  0.005054     4.064:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2082       640  0.003484   0.04228  0.005046     4.065:  51%|█████▏    | 20/39 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1849       640  0.003476   0.04214  0.005029     4.052:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1877       640  0.003473   0.04208  0.005003     4.044:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2101       640  0.003471   0.04204  0.004979     4.039:  59%|█████▉    | 23/39 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2139       640  0.003472    0.0421  0.004984     4.044:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2108       640  0.003474   0.04205  0.004996     4.042:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2055       640  0.003469   0.04198  0.005004     4.036:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.489      0.448      0.406      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.14it/s]

                 all        738      14937      0.477      0.447      0.403      0.225
                   0        738       1052      0.448      0.567      0.537      0.255
                   1        738         44      0.322      0.205      0.162     0.0642
                   2        738       8622      0.611      0.749      0.748       0.48
                   3        738        151      0.363      0.412      0.402       0.31
                   4        738        467      0.446      0.602       0.55      0.401
                   5        738         70       0.23      0.443      0.263       0.13
                   6        738         65      0.276      0.229      0.171     0.0583
                   7        738       1619        0.5      0.641       0.59      0.241
                   8        738       2845       0.57      0.625      0.607      0.315
                   9        738          2          1          0   0.000297   0.000267

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:25:15.172194747 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31149 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round002_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round002_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client1_highway_night_stable_train' images and labels...4895 found, 2938 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<00:00, 11104.14it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29496062992126
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2938 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:25:32.943952511 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:25:32.955549661 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1990       640  0.003649   0.04373  0.005391     4.221:   2%|▎         | 1/40 [00:22<14:34, 22.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1813       640  0.003601   0.04085  0.005356     3.985:   5%|▌         | 2/40 [00:23<06:10,  9.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1804       640  0.003515   0.03971  0.005054     3.862:   8%|▊         | 3/40 [00:24<03:30,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2114       640  0.003489   0.04012  0.004989     3.888:  10%|█         | 4/40 [00:24<02:15,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003497   0.04006  0.005032     3.887:  12%|█▎        | 5/40 [00:25<01:32,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1857       640  0.003481    0.0395   0.00508     3.845:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003481   0.03898  0.005091     3.804:  18%|█▊        | 7/40 [00:26<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003467   0.03886  0.005053      3.79:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1837       640  0.003469   0.03869  0.005031     3.775:  22%|██▎       | 9/40 [00:28<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1838       640   0.00347   0.03862  0.005047     3.771:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1926       640  0.003473   0.03858  0.005017     3.765:  28%|██▊       | 11/40 [00:29<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003468   0.03847  0.004979     3.753:  30%|███       | 12/40 [00:30<00:21,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003475   0.03831   0.00504     3.746:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1828       640  0.003475   0.03818  0.005056     3.737:  35%|███▌      | 14/40 [00:31<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1827       640  0.003478   0.03805    0.0051     3.731:  38%|███▊      | 15/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1842       640  0.003475   0.03798  0.005098     3.725:  40%|████      | 16/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1999       640   0.00348    0.0379  0.005068     3.716:  42%|████▎     | 17/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003475   0.03792  0.005106      3.72:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1617       640  0.003475   0.03771  0.005116     3.704:  48%|████▊     | 19/40 [00:34<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1958       640  0.003475   0.03765  0.005103     3.698:  50%|█████     | 20/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003479   0.03764  0.005091     3.697:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2150       640  0.003479    0.0377  0.005066     3.699:  55%|█████▌    | 22/40 [00:36<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640  0.003477   0.03777  0.005057     3.704:  57%|█████▊    | 23/40 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1606       640  0.003474   0.03762  0.005086     3.695:  60%|██████    | 24/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003469   0.03757  0.005094      3.69:  62%|██████▎   | 25/40 [00:38<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1917       640  0.003469   0.03748  0.005097     3.683:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.487      0.433      0.401      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]

                 all        738      14937      0.501      0.413      0.397      0.223
                   0        738       1052      0.503      0.553      0.535      0.253
                   1        738         44      0.455      0.136      0.156      0.066
                   2        738       8622      0.636      0.734      0.745      0.477
                   3        738        151        0.4      0.377        0.4      0.306
                   4        738        467       0.46      0.593      0.547      0.397
                   5        738         70      0.251      0.429      0.262      0.134
                   6        738         65      0.178     0.0769      0.145     0.0544
                   7        738       1619      0.523      0.622      0.583      0.238
                   8        738       2845      0.606      0.604      0.599      0.307
                   9        738          2          1          0   0.000266   0.000239

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:26:59.492028054 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31150 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round002_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round002_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 11930.45it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:27:15.136231801 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:27:15.190678056 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2066       640  0.003609   0.05077  0.005318     4.776:   3%|▎         | 1/39 [00:22<14:06, 22.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003561   0.05035  0.005598     4.761:   5%|▌         | 2/39 [00:23<05:59,  9.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003528   0.04953  0.005623     4.694:   8%|▊         | 3/39 [00:24<03:23,  5.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640   0.00354   0.04867  0.005524     4.619:  10%|█         | 4/39 [00:24<02:11,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003534   0.04813  0.005408     4.566:  13%|█▎        | 5/39 [00:25<01:30,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003495    0.0471  0.005359     4.476:  15%|█▌        | 6/39 [00:26<01:05,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003504   0.04692  0.005439     4.469:  18%|█▊        | 7/39 [00:26<00:49,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003493   0.04656  0.005383     4.435:  21%|██        | 8/39 [00:27<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003507   0.04659  0.005321     4.434:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003491   0.04635  0.005303     4.412:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003494   0.04629  0.005307     4.407:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003499   0.04584  0.005318     4.373:  31%|███       | 12/39 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003507   0.04573  0.005277     4.361:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003518   0.04579  0.005244     4.364:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003518   0.04566  0.005222     4.352:  38%|███▊      | 15/39 [00:32<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003508   0.04536  0.005216     4.327:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003501   0.04513  0.005242      4.31:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003492   0.04506  0.005228     4.303:  46%|████▌     | 18/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003494   0.04478  0.005204     4.278:  49%|████▊     | 19/39 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003489   0.04478  0.005184     4.276:  51%|█████▏    | 20/39 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003481   0.04462  0.005166     4.261:  54%|█████▍    | 21/39 [00:35<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003477   0.04454  0.005151     4.254:  56%|█████▋    | 22/39 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640   0.00347   0.04443  0.005147     4.244:  59%|█████▉    | 23/39 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003467   0.04437  0.005141     4.238:  62%|██████▏   | 24/39 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003463   0.04426  0.005136     4.229:  64%|██████▍   | 25/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003457   0.04424  0.005124     4.225:  67%|██████▋   | 26/39 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.512      0.426      0.404      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.497      0.427      0.402      0.226
                   0        738       1052      0.567      0.532      0.538      0.252
                   1        738         44      0.417      0.182      0.155     0.0665
                   2        738       8622      0.603       0.75      0.752      0.479
                   3        738        151      0.322      0.416      0.396      0.307
                   4        738        467      0.457      0.621      0.549      0.397
                   5        738         70      0.278      0.414      0.265      0.136
                   6        738         65      0.225      0.108      0.176     0.0673
                   7        738       1619      0.525      0.629      0.583       0.24
                   8        738       2845      0.571      0.622      0.606      0.319
                   9        738          2          1          0   0.000258   0.000232

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client2_citystreet_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:28:42.659127804 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31151 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round002_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round002_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train' images and labels...4883 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<00:00, 11387.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:28:59.581100681 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:28:59.595288512 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1843       640  0.003572   0.04345   0.00514     4.173:   2%|▎         | 1/40 [00:22<14:38, 22.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1861       640  0.003616   0.04489  0.005285     4.303:   5%|▌         | 2/40 [00:23<06:12,  9.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003552   0.04422  0.005431     4.256:   8%|▊         | 3/40 [00:24<03:31,  5.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003526   0.04353  0.005159     4.178:  10%|█         | 4/40 [00:25<02:16,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1800       640  0.003502   0.04265  0.005062     4.097:  12%|█▎        | 5/40 [00:25<01:32,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1833       640  0.003508   0.04213  0.004957     4.048:  15%|█▌        | 6/40 [00:26<01:07,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640   0.00351   0.04179  0.004906     4.017:  18%|█▊        | 7/40 [00:27<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1888       640  0.003504    0.0416  0.004947     4.005:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003492   0.04197  0.004903     4.029:  22%|██▎       | 9/40 [00:28<00:33,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1966       640  0.003498   0.04197  0.004951     4.034:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1973       640  0.003494   0.04195  0.005006     4.036:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1770       640   0.00349   0.04174  0.004988     4.017:  30%|███       | 12/40 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2098       640  0.003492   0.04173  0.005016     4.019:  32%|███▎      | 13/40 [00:30<00:20,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003492   0.04184  0.005015     4.028:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003492    0.0418  0.005021     4.025:  38%|███▊      | 15/40 [00:32<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1693       640  0.003492   0.04142  0.004978     3.991:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1488       640   0.00348     0.041  0.005006     3.959:  42%|████▎     | 17/40 [00:33<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2022       640  0.003487   0.04099  0.005039     3.961:  45%|████▌     | 18/40 [00:34<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1706       640  0.003491   0.04072  0.005041      3.94:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003485   0.04066  0.005048     3.935:  50%|█████     | 20/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003485   0.04056  0.005029     3.926:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003487   0.04049  0.005002     3.918:  55%|█████▌    | 22/40 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003492    0.0406  0.005009     3.928:  57%|█████▊    | 23/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640  0.003493   0.04061   0.00502      3.93:  60%|██████    | 24/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1791       640  0.003492   0.04048  0.004998     3.918:  62%|██████▎   | 25/40 [00:38<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003489   0.04036  0.005007     3.909:  65%|██████▌   | 26/40 [00:39<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.47      0.447      0.398      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.512      0.403      0.396      0.222
                   0        738       1052      0.561       0.53      0.529       0.25
                   1        738         44      0.416      0.114       0.16     0.0668
                   2        738       8622      0.635      0.728      0.738      0.466
                   3        738        151      0.424      0.377      0.404      0.311
                   4        738        467      0.461      0.602      0.549      0.395
                   5        738         70      0.275      0.414      0.269      0.132
                   6        738         65       0.21     0.0615       0.14     0.0536
                   7        738       1619      0.536      0.603      0.573      0.238
                   8        738       2845      0.606        0.6      0.599      0.313
                   9        738          2          1          0   0.000218   0.000175

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:30:25.328697341 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31152 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round002_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round002_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client4_residential_day_stable_train' images and labels...:   0%|          | 0/7863 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 18725.21it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:30:41.495854058 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:30:41.570956141 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2084       640  0.003491   0.04991  0.004557     4.636:   3%|▎         | 1/39 [00:23<14:34, 23.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003536   0.04969  0.005352     4.686:   5%|▌         | 2/39 [00:23<06:11, 10.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003476   0.04803  0.005285     4.543:   8%|▊         | 3/39 [00:24<03:31,  5.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003493    0.0472  0.005399     4.487:  10%|█         | 4/39 [00:25<02:16,  3.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003468   0.04607  0.005342     4.391:  13%|█▎        | 5/39 [00:26<01:32,  2.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640  0.003476   0.04481  0.005432     4.297:  15%|█▌        | 6/39 [00:27<01:07,  2.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640   0.00349   0.04457  0.005445     4.281:  18%|█▊        | 7/39 [00:27<00:50,  1.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640  0.003498   0.04435   0.00538     4.258:  21%|██        | 8/39 [00:28<00:40,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003491   0.04437  0.005429     4.263:  23%|██▎       | 9/39 [00:29<00:33,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640    0.0035   0.04439  0.005398     4.263:  26%|██▌       | 10/39 [00:29<00:28,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2139       640  0.003499   0.04437  0.005389     4.261:  28%|██▊       | 11/39 [00:30<00:24,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640  0.003498   0.04434  0.005377     4.257:  31%|███       | 12/39 [00:31<00:21,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003508   0.04442  0.005352     4.263:  33%|███▎      | 13/39 [00:31<00:19,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003517   0.04437  0.005342     4.259:  36%|███▌      | 14/39 [00:32<00:18,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003522   0.04411  0.005349     4.238:  38%|███▊      | 15/39 [00:33<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640  0.003521   0.04388  0.005347      4.22:  41%|████      | 16/39 [00:33<00:16,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640  0.003508   0.04368  0.005314       4.2:  44%|████▎     | 17/39 [00:34<00:15,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003504   0.04366  0.005277     4.195:  46%|████▌     | 18/39 [00:35<00:14,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1602       640  0.003497   0.04338  0.005267     4.172:  49%|████▊     | 19/39 [00:35<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2209       640  0.003498   0.04339  0.005256     4.172:  51%|█████▏    | 20/39 [00:36<00:12,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003498   0.04336  0.005237     4.168:  54%|█████▍    | 21/39 [00:37<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003496   0.04336  0.005233     4.167:  56%|█████▋    | 22/39 [00:37<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640  0.003497   0.04339  0.005253     4.171:  59%|█████▉    | 23/39 [00:38<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003495   0.04331  0.005245     4.164:  62%|██████▏   | 24/39 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640  0.003495   0.04331  0.005245     4.164:  64%|██████▍   | 25/39 [00:39<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003494   0.04312   0.00523     4.148:  67%|██████▋   | 26/39 [00:40<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.489      0.441      0.406      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.472      0.441      0.402      0.226
                   0        738       1052      0.462       0.56      0.529      0.251
                   1        738         44      0.345      0.182      0.151     0.0629
                   2        738       8622      0.617      0.749       0.75      0.477
                   3        738        151      0.321       0.43      0.411      0.317
                   4        738        467      0.432       0.63      0.552        0.4
                   5        738         70      0.239      0.421      0.273       0.13
                   6        738         65      0.245      0.169      0.167     0.0574
                   7        738       1619      0.506      0.641      0.584      0.243
                   8        738       2845      0.559      0.629      0.607      0.319
                   9        738          2          1          0   0.000244   0.000219

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client4_residential_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:32:10.277068197 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31153 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round002_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round002_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client5_residential_night_stable_train' images and labels...4885 found, 2956 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<00:00, 10991.02it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.273313414058814
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round002_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2956 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:32:26.865482733 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:32:26.932452108 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1883       640  0.003522   0.04162  0.005133     4.022:   2%|▎         | 1/40 [00:22<14:48, 22.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1962       640  0.003524   0.04271  0.005385      4.13:   5%|▌         | 2/40 [00:23<06:15,  9.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003538   0.04295  0.005114     4.128:   8%|▊         | 3/40 [00:24<03:34,  5.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2058       640  0.003512   0.04309  0.005102     4.136:  10%|█         | 4/40 [00:25<02:19,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2018       640  0.003526   0.04283  0.005042     4.112:  12%|█▎        | 5/40 [00:26<01:35,  2.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1839       640   0.00354   0.04237  0.005136     4.084:  15%|█▌        | 6/40 [00:26<01:09,  2.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003537   0.04186  0.005265     4.053:  18%|█▊        | 7/40 [00:27<00:52,  1.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003525    0.0417  0.005285     4.041:  20%|██        | 8/40 [00:28<00:41,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003519   0.04186  0.005213     4.048:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1694       640  0.003523   0.04142  0.005205     4.012:  25%|██▌       | 10/40 [00:29<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2287       640  0.003524   0.04173  0.005264     4.042:  28%|██▊       | 11/40 [00:30<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003518   0.04151  0.005247     4.022:  30%|███       | 12/40 [00:30<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640   0.00351   0.04117  0.005161     3.988:  32%|███▎      | 13/40 [00:31<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1944       640  0.003512   0.04112  0.005164     3.983:  35%|███▌      | 14/40 [00:32<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003509   0.04091  0.005205      3.97:  38%|███▊      | 15/40 [00:32<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003509   0.04072  0.005165     3.951:  40%|████      | 16/40 [00:33<00:16,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003511    0.0407  0.005222     3.955:  42%|████▎     | 17/40 [00:33<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003512   0.04064  0.005253     3.953:  45%|████▌     | 18/40 [00:34<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1589       640  0.003516   0.04028  0.005226     3.922:  48%|████▊     | 19/40 [00:35<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2159       640  0.003517   0.04034  0.005202     3.925:  50%|█████     | 20/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003521   0.04017  0.005206     3.912:  52%|█████▎    | 21/40 [00:36<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1857       640  0.003523   0.04008  0.005252     3.908:  55%|█████▌    | 22/40 [00:37<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2026       640  0.003521   0.04006  0.005261     3.907:  57%|█████▊    | 23/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003516   0.03992  0.005266     3.896:  60%|██████    | 24/40 [00:38<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003517   0.03977  0.005277     3.885:  62%|██████▎   | 25/40 [00:39<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1723       640  0.003512   0.03959  0.005268      3.87:  65%|██████▌   | 26/40 [00:39<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.468      0.451      0.399      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.517      0.402      0.396      0.223
                   0        738       1052      0.534      0.534      0.524       0.25
                   1        738         44      0.435      0.114      0.158      0.071
                   2        738       8622      0.644      0.724      0.737      0.466
                   3        738        151      0.445      0.377      0.397      0.304
                   4        738        467      0.472      0.585       0.55      0.394
                   5        738         70      0.286      0.414      0.265      0.132
                   6        738         65      0.209     0.0615      0.149      0.056
                   7        738       1619      0.544      0.603      0.575       0.24
                   8        738       2845      0.599       0.61      0.601      0.314
                   9        738          2          1          0   0.000165   0.000132

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:33:56.046279519 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31154 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round002_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round002_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:34:13.216531455 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:34:13.228746733 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640    0.0348   0.04347  0.005198     6.678:   3%|▎         | 1/31 [00:34<17:23, 34.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03547   0.04453  0.005407     6.833:   6%|▋         | 2/31 [00:35<07:08, 14.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03487   0.04336  0.005288     6.681:  10%|▉         | 3/31 [00:36<03:54,  8.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03429   0.04163  0.005046     6.478:  13%|█▎        | 4/31 [00:37<02:24,  5.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03426   0.04182   0.00507     6.492:  16%|█▌        | 5/31 [00:37<01:34,  3.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03444   0.04178  0.005139     6.508:  19%|█▉        | 6/31 [00:38<01:04,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03454   0.04149  0.005206     6.499:  23%|██▎       | 7/31 [00:38<00:46,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03447   0.04159  0.005236     6.504:  26%|██▌       | 8/31 [00:39<00:34,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640    0.0345   0.04151  0.005142     6.493:  29%|██▉       | 9/31 [00:39<00:26,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03447   0.04162  0.005123     6.497:  32%|███▏      | 10/31 [00:40<00:21,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03443   0.04166  0.005141     6.499:  35%|███▌      | 11/31 [00:41<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03433   0.04138  0.005127     6.467:  39%|███▊      | 12/31 [00:41<00:15,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0343   0.04143  0.005075     6.464:  42%|████▏     | 13/31 [00:42<00:13,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640    0.0343   0.04123  0.005039     6.446:  45%|████▌     | 14/31 [00:42<00:11,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03433   0.04114  0.005075     6.444:  48%|████▊     | 15/31 [00:43<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03432     0.041  0.005062      6.43:  52%|█████▏    | 16/31 [00:43<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03435   0.04104  0.005022     6.433:  55%|█████▍    | 17/31 [00:44<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03439   0.04108  0.004979     6.436:  58%|█████▊    | 18/31 [00:45<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03431   0.04094  0.004941     6.415:  61%|██████▏   | 19/31 [00:45<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640    0.0343   0.04116  0.004946     6.432:  65%|██████▍   | 20/31 [00:46<00:06,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03432   0.04118  0.004962     6.437:  68%|██████▊   | 21/31 [00:46<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03431   0.04128  0.004928     6.442:  71%|███████   | 22/31 [00:47<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03429   0.04131  0.004919     6.442:  74%|███████▍  | 23/31 [00:48<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640    0.0343   0.04138  0.004901     6.446:  77%|███████▋  | 24/31 [00:48<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03429   0.04131  0.004909     6.441:  81%|████████  | 25/31 [00:49<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03434   0.04134  0.004907     6.447:  84%|████████▍ | 26/31 [00:49<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.473       0.46      0.409      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937       0.46      0.464      0.408      0.229
                   0        738       1052      0.452      0.582      0.544      0.257
                   1        738         44      0.271      0.205      0.166      0.061
                   2        738       8622      0.568      0.765      0.754      0.487
                   3        738        151      0.311      0.444      0.405      0.309
                   4        738        467      0.428       0.61      0.556      0.405
                   5        738         70      0.248      0.486       0.28      0.134
                   6        738         65      0.291      0.262       0.18      0.063
                   7        738       1619      0.506      0.639      0.586      0.244
                   8        738       2845      0.528       0.65      0.614      0.326
                   9        738          2          1          0   0.000311    0.00028

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round002_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 14:35:54.337130814 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round003 phase_round=3 ===

02 head-to-full DQA:   6%|▋         | 2/32 [28:35<7:09:12, 858.41s/round, elapsed=28m35s, eta=7h08m55s, phase=phase1_head, round=2]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round003 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round003 client0_highway_day: pseudo scan 250/1500 images, kept 2385 boxes
round003 client0_highway_day: pseudo scan 500/1500 images, kept 4840 boxes
round003 client0_highway_day: pseudo scan 750/1500 images, kept 7204 boxes
round003 client0_highway_day: pseudo scan 1000/1500 images, kept 9589 boxes
round003 client0_highway_day: pseudo scan 1250/1500 images, kept 11922 boxes
round003 client0_highway_day: pseudo scan 1500/1500 images, kept 14300 boxes
{
  "round": "round003",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round002_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 11155,
  "boxes_per_kept_image": 7.461538461538462,
  "mean_conf": 0.7863834354734272,
  "mean_stability": 0.9539097595834668,
  "mean_score": 0.7533717861977658,
  "class_counts": {
    "0": 155,
    "2": 6435,
    "3": 96,
    "4": 514,
    "5": 5,
    "7": 564,
    "8": 3386
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_client0_highway_day_stable_boxes.csv"
}
round003 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round003 client1_highway_night: pseudo scan 250/1500 images, kept 1745 boxes
round003 client1_highway_night: pseudo scan 500/1500 images, kept 3620 boxes
round003 client1_highway_night: pseudo scan 750/1500 images, kept 5464 boxes
round003 client1_highway_night: pseudo scan 1000/1500 images, kept 7230 boxes
round003 client1_highway_night: pseudo scan 1250/1500 images, kept 9053 boxes
round003 client1_highway_night: pseudo scan 1500/1500 images, kept 10837 boxes
{
  "round": "round003",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round002_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 8777,
  "boxes_per_kept_image": 5.962635869565218,
  "mean_conf": 0.6943289904248352,
  "mean_stability": 0.9365787904803379,
  "mean_score": 0.6542725101129776,
  "class_counts": {
    "0": 57,
    "2": 4877,
    "3": 26,
    "4": 138,
    "5": 6,
    "7": 539,
    "8": 3134
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_client1_highway_night_stable_boxes.csv"
}
round003 client2_citystreet_day: pseudo scan 1/1500 images, kept 7 boxes
round003 client2_citystreet_day: pseudo scan 250/1500 images, kept 2697 boxes
round003 client2_citystreet_day: pseudo scan 500/1500 images, kept 5417 boxes
round003 client2_citystreet_day: pseudo scan 750/1500 images, kept 8159 boxes
round003 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10923 boxes
round003 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13656 boxes
round003 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16302 boxes
{
  "round": "round003",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round002_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13656,
  "boxes_per_kept_image": 9.128342245989305,
  "mean_conf": 0.7832179025871823,
  "mean_stability": 0.9519118435667772,
  "mean_score": 0.7488533077890478,
  "class_counts": {
    "0": 1404,
    "2": 7336,
    "3": 166,
    "4": 564,
    "5": 62,
    "7": 1539,
    "8": 2585
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_client2_citystreet_day_stable_boxes.csv"
}
round003 client3_citystreet_night: pseudo scan 1/1500 images, kept 9 boxes
round003 client3_citystreet_night: pseudo scan 250/1500 images, kept 2448 boxes
round003 client3_citystreet_night: pseudo scan 500/1500 images, kept 4845 boxes
round003 client3_citystreet_night: pseudo scan 750/1500 images, kept 7207 boxes
round003 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9524 boxes
round003 client3_citystreet_night: pseudo scan 1250/1500 images, kept 12004 boxes
round003 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14396 boxes
{
  "round": "round003",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round002_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1479,
  "pseudo_boxes_kept": 11943,
  "boxes_per_kept_image": 8.075050709939148,
  "mean_conf": 0.696796392789091,
  "mean_stability": 0.9355706232562093,
  "mean_score": 0.6560114725993621,
  "class_counts": {
    "0": 543,
    "2": 6479,
    "3": 62,
    "4": 153,
    "5": 31,
    "7": 1872,
    "8": 2803
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_client3_citystreet_night_stable_boxes.csv"
}
round003 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round003 client4_residential_day: pseudo scan 250/1500 images, kept 2579 boxes
round003 client4_residential_day: pseudo scan 500/1500 images, kept 5189 boxes
round003 client4_residential_day: pseudo scan 750/1500 images, kept 7740 boxes
round003 client4_residential_day: pseudo scan 1000/1500 images, kept 10217 boxes
round003 client4_residential_day: pseudo scan 1250/1500 images, kept 12760 boxes
round003 client4_residential_day: pseudo scan 1500/1500 images, kept 15241 boxes
{
  "round": "round003",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round002_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9887,
  "boxes_per_kept_image": 6.631120053655265,
  "mean_conf": 0.8219249384871288,
  "mean_stability": 0.9601780919969848,
  "mean_score": 0.792358017847533,
  "class_counts": {
    "0": 368,
    "2": 6859,
    "3": 49,
    "4": 308,
    "5": 38,
    "7": 534,
    "8": 1731
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_client4_residential_day_stable_boxes.csv"
}
round003 client5_residential_night: pseudo scan 1/1500 images, kept 10 boxes
round003 client5_residential_night: pseudo scan 250/1500 images, kept 2423 boxes
round003 client5_residential_night: pseudo scan 500/1500 images, kept 4778 boxes
round003 client5_residential_night: pseudo scan 750/1500 images, kept 7140 boxes
round003 client5_residential_night: pseudo scan 1000/1500 images, kept 9571 boxes
round003 client5_residential_night: pseudo scan 1250/1500 images, kept 11970 boxes
round003 client5_residential_night: pseudo scan 1500/1500 images, kept 14399 boxes
{
  "round": "round003",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round002_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 8866,
  "boxes_per_kept_image": 5.9864956110735985,
  "mean_conf": 0.7756249694006184,
  "mean_stability": 0.9491310489519224,
  "mean_score": 0.7388339095761699,
  "class_counts": {
    "0": 121,
    "2": 6480,
    "3": 27,
    "4": 92,
    "5": 16,
    "7": 595,
    "8": 1535
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round003_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31155 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round003_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round003_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client0_highway_day_stable_train' images and labels...5361 found, 2510 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 11935.17it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.828389830508474
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2510 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:38:11.881992065 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:38:11.908775299 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1976       640  0.003452   0.04469  0.006031     4.334:   3%|▎         | 1/39 [00:21<13:47, 21.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003408   0.04346  0.005551     4.193:   5%|▌         | 2/39 [00:22<05:52,  9.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003475   0.04486  0.005566     4.312:   8%|▊         | 3/39 [00:23<03:20,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003449   0.04466   0.00543     4.283:  10%|█         | 4/39 [00:24<02:10,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1924       640  0.003455   0.04418  0.005471     4.248:  13%|█▎        | 5/39 [00:25<01:29,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1922       640   0.00345   0.04361  0.005424     4.199:  15%|█▌        | 6/39 [00:25<01:04,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003434   0.04291  0.005402      4.14:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2222       640  0.003435   0.04327  0.005337     4.164:  21%|██        | 8/39 [00:27<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2165       640  0.003453    0.0435  0.005327     4.182:  23%|██▎       | 9/39 [00:27<00:32,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640   0.00346   0.04371  0.005305     4.198:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640   0.00346   0.04341  0.005233     4.168:  28%|██▊       | 11/39 [00:29<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2043       640   0.00346   0.04343  0.005269     4.173:  31%|███       | 12/39 [00:29<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003463   0.04321  0.005252     4.154:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003469   0.04326  0.005237     4.157:  36%|███▌      | 14/39 [00:31<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003467    0.0431  0.005176      4.14:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640   0.00347   0.04318   0.00515     4.144:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1787       640  0.003474   0.04295  0.005156     4.126:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2071       640  0.003478   0.04279  0.005108      4.11:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640  0.003478   0.04259  0.005109     4.094:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2326       640  0.003472   0.04271  0.005118     4.104:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640   0.00348   0.04268  0.005127     4.103:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1705       640  0.003469   0.04248  0.005081     4.082:  56%|█████▋    | 22/39 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2057       640  0.003463   0.04241  0.005053     4.074:  59%|█████▉    | 23/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2321       640  0.003467   0.04247  0.005029     4.077:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640   0.00347   0.04244  0.005044     4.076:  64%|██████▍   | 25/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2069       640  0.003467   0.04246  0.005012     4.075:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.488      0.459      0.408      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]

                 all        738      14937      0.473      0.461      0.406      0.229
                   0        738       1052      0.441      0.579      0.537      0.258
                   1        738         44      0.327       0.25      0.172     0.0664
                   2        738       8622      0.607      0.754      0.751      0.483
                   3        738        151      0.354      0.444      0.413      0.316
                   4        738        467       0.43      0.602      0.546      0.401
                   5        738         70      0.238      0.457      0.272      0.147
                   6        738         65      0.271      0.246      0.165     0.0604
                   7        738       1619      0.493      0.647      0.594      0.242
                   8        738       2845       0.57      0.629       0.61      0.317
                   9        738          2          1          0   0.000305   0.000305

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:39:37.716098294 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31156 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round003_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round003_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client1_highway_night_stable_train' images and labels...4895 found, 2930 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<00:00, 9591.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.304601323668452
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2930 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:39:54.483512423 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:39:54.540997841 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1936       640  0.003487   0.04189  0.004519     3.991:   2%|▎         | 1/40 [00:21<14:06, 21.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1821       640  0.003454   0.03994  0.004478      3.83:   5%|▌         | 2/40 [00:22<06:00,  9.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003432   0.03959  0.004587     3.808:   8%|▊         | 3/40 [00:23<03:25,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003443   0.03971  0.004836     3.839:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1981       640  0.003475   0.03973  0.004972     3.854:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1771       640  0.003471    0.0392  0.005022     3.815:  15%|█▌        | 6/40 [00:25<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003461   0.03882  0.004985     3.781:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640  0.003447   0.03866   0.00495     3.764:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003452   0.03853  0.004962     3.755:  22%|██▎       | 9/40 [00:27<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640   0.00344   0.03845  0.004931     3.746:  25%|██▌       | 10/40 [00:28<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2111       640  0.003449   0.03866  0.005013      3.77:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1833       640  0.003441   0.03833  0.005008     3.743:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640   0.00345   0.03853  0.004986     3.757:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1938       640  0.003453    0.0385  0.004967     3.754:  35%|███▌      | 14/40 [00:31<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003459   0.03846  0.004996     3.753:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003457   0.03838  0.004996     3.747:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003463   0.03834  0.005008     3.745:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003466   0.03825  0.005011     3.738:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1506       640  0.003465   0.03788  0.005035      3.71:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1817       640   0.00346   0.03777  0.005017       3.7:  50%|█████     | 20/40 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1967       640  0.003462   0.03774  0.005003     3.696:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003455   0.03779  0.004983     3.698:  55%|█████▌    | 22/40 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003453   0.03776  0.004983     3.696:  57%|█████▊    | 23/40 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2035       640  0.003456   0.03774  0.004963     3.693:  60%|██████    | 24/40 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003456   0.03769  0.004931     3.686:  62%|██████▎   | 25/40 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640   0.00346   0.03781  0.004933     3.696:  65%|██████▌   | 26/40 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.517      0.415      0.406      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.502      0.416      0.403      0.227
                   0        738       1052       0.52      0.547      0.532      0.254
                   1        738         44      0.466      0.158      0.182      0.083
                   2        738       8622      0.632      0.737      0.746      0.477
                   3        738        151      0.372        0.4       0.41      0.314
                   4        738        467      0.445        0.6      0.548      0.398
                   5        738         70      0.261      0.414      0.267      0.136
                   6        738         65      0.195     0.0769      0.164     0.0597
                   7        738       1619      0.536      0.619      0.583      0.241
                   8        738       2845      0.598      0.608      0.602       0.31
                   9        738          2          1          0   0.000269   0.000242

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client1_highway_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:41:21.925619894 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31157 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round003_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round003_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 10943.75it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:41:38.857993568 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:41:38.869710859 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003583   0.05086  0.005136     4.766:   3%|▎         | 1/39 [00:22<14:02, 22.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003533   0.05036  0.005445     4.747:   5%|▌         | 2/39 [00:23<05:58,  9.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003497   0.04948  0.005459     4.675:   8%|▊         | 3/39 [00:23<03:23,  5.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003508   0.04858  0.005355     4.595:  10%|█         | 4/39 [00:24<02:12,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003502   0.04802  0.005247     4.542:  13%|█▎        | 5/39 [00:25<01:30,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003463   0.04699  0.005197     4.452:  15%|█▌        | 6/39 [00:26<01:05,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003472   0.04678  0.005272     4.442:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003461   0.04643  0.005218     4.409:  21%|██        | 8/39 [00:27<00:38,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003475   0.04646  0.005161     4.408:  23%|██▎       | 9/39 [00:28<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003459   0.04621  0.005142     4.385:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003462   0.04614  0.005144      4.38:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003467   0.04569  0.005153     4.344:  31%|███       | 12/39 [00:30<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003474   0.04558  0.005114     4.333:  33%|███▎      | 13/39 [00:30<00:19,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003485   0.04563  0.005081     4.335:  36%|███▌      | 14/39 [00:31<00:18,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003486   0.04549  0.005061     4.323:  38%|███▊      | 15/39 [00:32<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003476   0.04519  0.005054     4.297:  41%|████      | 16/39 [00:32<00:15,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003468   0.04496  0.005081     4.281:  44%|████▎     | 17/39 [00:33<00:14,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640   0.00346   0.04489  0.005067     4.273:  46%|████▌     | 18/39 [00:34<00:14,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003462   0.04461  0.005046      4.25:  49%|████▊     | 19/39 [00:34<00:13,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003457   0.04461   0.00503     4.248:  51%|█████▏    | 20/39 [00:35<00:12,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003449   0.04445  0.005012     4.233:  54%|█████▍    | 21/39 [00:36<00:12,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003445   0.04437  0.004997     4.225:  56%|█████▋    | 22/39 [00:36<00:11,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003438   0.04426  0.004995     4.215:  59%|█████▉    | 23/39 [00:37<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003435   0.04419  0.004986     4.209:  62%|██████▏   | 24/39 [00:38<00:10,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003431   0.04409  0.004982       4.2:  64%|██████▍   | 25/39 [00:38<00:09,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003426   0.04406   0.00497     4.196:  67%|██████▋   | 26/39 [00:39<00:08,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.544      0.412      0.409      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.25it/s]

                 all        738      14937      0.529      0.414      0.407      0.229
                   0        738       1052      0.617      0.515      0.537      0.253
                   1        738         44      0.464      0.159      0.165     0.0702
                   2        738       8622      0.636      0.744      0.754      0.481
                   3        738        151      0.372      0.424      0.411      0.314
                   4        738        467      0.464      0.601      0.551      0.398
                   5        738         70      0.282        0.4       0.27       0.14
                   6        738         65      0.295     0.0769      0.184      0.068
                   7        738       1619      0.553      0.615      0.586      0.241
                   8        738       2845      0.612      0.609      0.608      0.321
                   9        738          2          1          0   0.000264   0.000264

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client2_citystreet_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:43:05.053522568 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31158 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round003_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round003_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train' images and labels...4883 found, 2956 missing, 0 empty, 0 corrupted: 100%|██████████| 7839/7839 [00:00<00:00, 9484.19it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.273313414058814
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2956 missing, 0 empty, 0 corrupted: 100%|██████████| 7839/7839 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:43:22.944627535 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:43:22.013922936 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1932       640  0.003556   0.04262  0.005008     4.094:   2%|▎         | 1/40 [00:21<14:12, 21.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1610       640   0.00352   0.04222    0.0049     4.051:   5%|▌         | 2/40 [00:22<06:01,  9.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1786       640  0.003478   0.04191  0.004938     4.026:   8%|▊         | 3/40 [00:23<03:25,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003467   0.04169  0.004913     4.005:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003421   0.04113  0.004736     3.943:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003414   0.04072  0.004709     3.907:  15%|█▌        | 6/40 [00:25<01:05,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003412   0.04037  0.004729     3.881:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003405   0.04057  0.004768       3.9:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640  0.003413   0.04082  0.004747     3.918:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003417   0.04089   0.00481      3.93:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2018       640  0.003427   0.04093  0.004824     3.934:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003432   0.04109  0.004793     3.945:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003433   0.04114  0.004827     3.952:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2132       640  0.003431   0.04114  0.004805      3.95:  35%|███▌      | 14/40 [00:30<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003432   0.04106   0.00482     3.945:  38%|███▊      | 15/40 [00:31<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003438   0.04092  0.004793     3.933:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1552       640  0.003434   0.04057  0.004825     3.906:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2160       640   0.00344   0.04059   0.00485      3.91:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1701       640   0.00344   0.04029  0.004876     3.888:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003437   0.04034  0.004904     3.894:  50%|█████     | 20/40 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1979       640  0.003444   0.04027  0.004941     3.893:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1801       640  0.003442   0.04011   0.00493     3.879:  55%|█████▌    | 22/40 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2309       640  0.003447    0.0403  0.004948     3.895:  57%|█████▊    | 23/40 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003446   0.04019  0.004953     3.887:  60%|██████    | 24/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1931       640  0.003443   0.04014  0.004965     3.884:  62%|██████▎   | 25/40 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003438   0.04001  0.004965     3.873:  65%|██████▌   | 26/40 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.483      0.444      0.402      0.224
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.14it/s]

                 all        738      14937      0.511       0.41      0.401      0.225
                   0        738       1052      0.562      0.524      0.528       0.25
                   1        738         44      0.446      0.129      0.165     0.0719
                   2        738       8622       0.63      0.733       0.74      0.469
                   3        738        151      0.418      0.391      0.414      0.315
                   4        738        467      0.455      0.595      0.547      0.395
                   5        738         70      0.262      0.429      0.273      0.138
                   6        738         65      0.206     0.0769      0.159     0.0592
                   7        738       1619      0.545      0.613      0.578       0.24
                   8        738       2845      0.589      0.614      0.604      0.315
                   9        738          2          1          0   0.000202   0.000162

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:44:49.723922304 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31159 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round003_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round003_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 9519.36it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:45:06.962115908 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:45:06.972797616 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2084       640  0.003464    0.0498  0.004416     4.614:   3%|▎         | 1/39 [00:21<13:45, 21.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003506   0.04953  0.005214      4.66:   5%|▌         | 2/39 [00:22<05:48,  9.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003446    0.0478  0.005156     4.512:   8%|▊         | 3/39 [00:23<03:18,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003462   0.04696  0.005269     4.456:  10%|█         | 4/39 [00:24<02:08,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003436   0.04582  0.005216     4.358:  13%|█▎        | 5/39 [00:24<01:28,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640  0.003444   0.04455  0.005303     4.264:  15%|█▌        | 6/39 [00:25<01:03,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003458   0.04432  0.005309     4.247:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640  0.003466    0.0441   0.00524     4.225:  21%|██        | 8/39 [00:26<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003459   0.04412  0.005292      4.23:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003468   0.04414  0.005262      4.23:  26%|██▌       | 10/39 [00:28<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2139       640  0.003467   0.04413  0.005253     4.228:  28%|██▊       | 11/39 [00:28<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640  0.003466    0.0441  0.005235     4.224:  31%|███       | 12/39 [00:29<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003475   0.04418  0.005212      4.23:  33%|███▎      | 13/39 [00:29<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003484   0.04414    0.0052     4.226:  36%|███▌      | 14/39 [00:30<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003489   0.04387  0.005204     4.205:  38%|███▊      | 15/39 [00:31<00:16,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640  0.003488   0.04364  0.005201     4.186:  41%|████      | 16/39 [00:31<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640  0.003475   0.04344  0.005168     4.167:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003471   0.04342  0.005131     4.162:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1602       640  0.003465   0.04315  0.005122     4.139:  49%|████▊     | 19/39 [00:33<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2209       640  0.003466   0.04315   0.00511     4.138:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003466   0.04312  0.005089     4.134:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003464   0.04313  0.005086     4.134:  56%|█████▋    | 22/39 [00:35<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640  0.003466   0.04316  0.005107     4.138:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003463   0.04308  0.005099     4.131:  62%|██████▏   | 24/39 [00:36<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640  0.003463   0.04307  0.005099     4.131:  64%|██████▍   | 25/39 [00:37<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003462   0.04289  0.005085     4.115:  67%|██████▋   | 26/39 [00:38<00:08,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.519      0.423       0.41      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.506      0.426      0.408       0.23
                   0        738       1052      0.506      0.552      0.534      0.253
                   1        738         44      0.463      0.157      0.176     0.0691
                   2        738       8622      0.654      0.737      0.751      0.479
                   3        738        151      0.388       0.45      0.425      0.324
                   4        738        467      0.448      0.612      0.553      0.405
                   5        738         70      0.267      0.414      0.276      0.137
                   6        738         65        0.2     0.0923      0.172     0.0626
                   7        738       1619      0.534      0.628      0.583      0.242
                   8        738       2845      0.604      0.614      0.609      0.322
                   9        738          2          1          0   0.000256   0.000231

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client4_residential_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:46:33.590858498 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31160 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round003_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round003_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client5_residential_night_stable_train' images and labels...4885 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7843/7843 [00:00<00:00, 9945.37it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round003_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7843/7843 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:46:50.598409251 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:46:50.621167649 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2031       640  0.003425   0.04514  0.004666     4.258:   2%|▎         | 1/40 [00:21<14:12, 21.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1775       640  0.003455   0.04368  0.004807     4.155:   5%|▌         | 2/40 [00:22<06:00,  9.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2165       640   0.00344   0.04376  0.004604     4.144:   8%|▊         | 3/40 [00:23<03:24,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1938       640  0.003451    0.0431  0.004684     4.099:  10%|█         | 4/40 [00:24<02:12,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003448   0.04307  0.004676     4.095:  12%|█▎        | 5/40 [00:25<01:30,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1611       640  0.003427   0.04211  0.004591      4.01:  15%|█▌        | 6/40 [00:25<01:05,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1771       640  0.003421    0.0414  0.004661     3.959:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1981       640  0.003427    0.0414  0.004753     3.966:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2104       640  0.003435   0.04159  0.004783     3.985:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2222       640  0.003438   0.04179  0.004824     4.004:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2049       640  0.003439   0.04155  0.004818     3.984:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1809       640  0.003438   0.04117  0.004779     3.951:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003434   0.04094  0.004803     3.934:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2147       640  0.003439   0.04107  0.004842     3.948:  35%|███▌      | 14/40 [00:30<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1919       640  0.003433   0.04084  0.004863     3.931:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1723       640  0.003431   0.04048  0.004887     3.903:  40%|████      | 16/40 [00:32<00:16,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2034       640  0.003438   0.04051  0.004884     3.907:  42%|████▎     | 17/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003444   0.04041  0.004911     3.901:  45%|████▌     | 18/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1778       640  0.003442   0.04013  0.004919     3.879:  48%|████▊     | 19/40 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003452   0.04006  0.004931     3.876:  50%|█████     | 20/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2319       640  0.003459   0.04007  0.004952     3.879:  52%|█████▎    | 21/40 [00:35<00:12,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003459   0.03991  0.004962     3.867:  55%|█████▌    | 22/40 [00:36<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640   0.00346   0.03989  0.004969     3.865:  57%|█████▊    | 23/40 [00:36<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003459   0.03983   0.00496      3.86:  60%|██████    | 24/40 [00:37<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1786       640  0.003455   0.03962   0.00494     3.841:  62%|██████▎   | 25/40 [00:38<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003457   0.03953  0.004932     3.834:  65%|██████▌   | 26/40 [00:38<00:09,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.408      0.405      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.521       0.41      0.403      0.226
                   0        738       1052      0.551       0.53      0.526      0.249
                   1        738         44      0.447      0.136      0.177     0.0818
                   2        738       8622      0.654      0.724       0.74       0.47
                   3        738        151      0.425      0.384      0.413      0.313
                   4        738        467      0.476      0.593      0.554      0.396
                   5        738         70      0.276      0.429      0.269      0.132
                   6        738         65      0.221     0.0769      0.156     0.0592
                   7        738       1619      0.553      0.618      0.587      0.243
                   8        738       2845      0.611       0.61      0.604      0.318
                   9        738          2          1          0   0.000174   0.000139

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:48:18.727484194 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31161 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round003_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round003_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:48:35.954958400 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:48:35.991899945 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03397   0.04233   0.00491     6.497:   3%|▎         | 1/31 [00:32<16:11, 32.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03465    0.0433  0.005109     6.644:   6%|▋         | 2/31 [00:33<06:45, 13.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03407   0.04217  0.005008       6.5:  10%|▉         | 3/31 [00:34<03:42,  7.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640    0.0335   0.04046  0.004767     6.298:  13%|█▎        | 4/31 [00:35<02:18,  5.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640    0.0335   0.04065  0.004797     6.316:  16%|█▌        | 5/31 [00:35<01:30,  3.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03369   0.04063  0.004864     6.335:  19%|█▉        | 6/31 [00:36<01:02,  2.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640    0.0338   0.04037  0.004937     6.328:  23%|██▎       | 7/31 [00:36<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03374   0.04046  0.004963     6.333:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03378   0.04039  0.004867     6.324:  29%|██▉       | 9/31 [00:37<00:26,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03376   0.04051   0.00485      6.33:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03373   0.04054  0.004873     6.332:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03363   0.04027  0.004866     6.302:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0336   0.04032  0.004815     6.299:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03362   0.04013  0.004781     6.283:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03365   0.04006   0.00482     6.282:  48%|████▊     | 15/31 [00:41<00:10,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03364   0.03993   0.00481     6.271:  52%|█████▏    | 16/31 [00:42<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03368   0.03998  0.004773     6.275:  55%|█████▍    | 17/31 [00:42<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03372   0.04004  0.004732     6.279:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03365    0.0399  0.004697      6.26:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03365   0.04013  0.004702     6.279:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03368   0.04017   0.00472     6.285:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03368   0.04028   0.00469     6.292:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03366   0.04032  0.004678     6.293:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03368    0.0404  0.004662     6.299:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03368   0.04035  0.004673     6.296:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03373   0.04039  0.004674     6.303:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.458      0.492      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.443      0.496       0.41      0.231
                   0        738       1052      0.406      0.591       0.54      0.258
                   1        738         44      0.248      0.295      0.159     0.0628
                   2        738       8622      0.543      0.771      0.753      0.487
                   3        738        151      0.283       0.47      0.421      0.319
                   4        738        467      0.404      0.619      0.555      0.403
                   5        738         70      0.242      0.514      0.293      0.142
                   6        738         65      0.305      0.384      0.175     0.0633
                   7        738       1619      0.488      0.652       0.59      0.244
                   8        738       2845      0.508      0.664      0.617      0.327
                   9        738          2          1          0   0.000321   0.000289

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round003_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 14:50:14.398668468 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round004 phase_round=4 ===

02 head-to-full DQA:   9%|▉         | 3/32 [42:55<6:55:14, 859.12s/round, elapsed=42m55s, eta=6h54m57s, phase=phase1_head, round=3]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round004 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round004 client0_highway_day: pseudo scan 250/1500 images, kept 2377 boxes
round004 client0_highway_day: pseudo scan 500/1500 images, kept 4824 boxes
round004 client0_highway_day: pseudo scan 750/1500 images, kept 7184 boxes
round004 client0_highway_day: pseudo scan 1000/1500 images, kept 9569 boxes
round004 client0_highway_day: pseudo scan 1250/1500 images, kept 11900 boxes
round004 client0_highway_day: pseudo scan 1500/1500 images, kept 14286 boxes
{
  "round": "round004",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round003_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 11124,
  "boxes_per_kept_image": 7.440802675585284,
  "mean_conf": 0.7930753310510728,
  "mean_stability": 0.9544608857146445,
  "mean_score": 0.7601854874528507,
  "class_counts": {
    "0": 149,
    "2": 6429,
    "3": 102,
    "4": 512,
    "5": 7,
    "7": 557,
    "8": 3368
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_client0_highway_day_stable_boxes.csv"
}
round004 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round004 client1_highway_night: pseudo scan 250/1500 images, kept 1717 boxes
round004 client1_highway_night: pseudo scan 500/1500 images, kept 3570 boxes
round004 client1_highway_night: pseudo scan 750/1500 images, kept 5393 boxes
round004 client1_highway_night: pseudo scan 1000/1500 images, kept 7126 boxes
round004 client1_highway_night: pseudo scan 1250/1500 images, kept 8921 boxes
round004 client1_highway_night: pseudo scan 1500/1500 images, kept 10664 boxes
{
  "round": "round004",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round003_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 8611,
  "boxes_per_kept_image": 5.849864130434782,
  "mean_conf": 0.7024719353828844,
  "mean_stability": 0.9379386837896937,
  "mean_score": 0.6628687536707336,
  "class_counts": {
    "0": 63,
    "2": 4799,
    "3": 27,
    "4": 134,
    "5": 6,
    "7": 542,
    "8": 3040
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_client1_highway_night_stable_boxes.csv"
}
round004 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round004 client2_citystreet_day: pseudo scan 250/1500 images, kept 2695 boxes
round004 client2_citystreet_day: pseudo scan 500/1500 images, kept 5424 boxes
round004 client2_citystreet_day: pseudo scan 750/1500 images, kept 8172 boxes
round004 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10942 boxes
round004 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13669 boxes
round004 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16316 boxes
{
  "round": "round004",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round003_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13698,
  "boxes_per_kept_image": 9.156417112299465,
  "mean_conf": 0.7890519223098843,
  "mean_stability": 0.9521168200033984,
  "mean_score": 0.7547473737173733,
  "class_counts": {
    "0": 1430,
    "2": 7343,
    "3": 180,
    "4": 573,
    "5": 64,
    "7": 1530,
    "8": 2578
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_client2_citystreet_day_stable_boxes.csv"
}
round004 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round004 client3_citystreet_night: pseudo scan 250/1500 images, kept 2428 boxes
round004 client3_citystreet_night: pseudo scan 500/1500 images, kept 4804 boxes
round004 client3_citystreet_night: pseudo scan 750/1500 images, kept 7169 boxes
round004 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9471 boxes
round004 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11930 boxes
round004 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14316 boxes
{
  "round": "round004",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round003_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1480,
  "pseudo_boxes_kept": 11877,
  "boxes_per_kept_image": 8.025,
  "mean_conf": 0.7022992036123212,
  "mean_stability": 0.9361484227602436,
  "mean_score": 0.6616671026243954,
  "class_counts": {
    "0": 542,
    "2": 6443,
    "3": 65,
    "4": 156,
    "5": 34,
    "7": 1896,
    "8": 2741
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_client3_citystreet_night_stable_boxes.csv"
}
round004 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round004 client4_residential_day: pseudo scan 250/1500 images, kept 2582 boxes
round004 client4_residential_day: pseudo scan 500/1500 images, kept 5199 boxes
round004 client4_residential_day: pseudo scan 750/1500 images, kept 7755 boxes
round004 client4_residential_day: pseudo scan 1000/1500 images, kept 10239 boxes
round004 client4_residential_day: pseudo scan 1250/1500 images, kept 12779 boxes
round004 client4_residential_day: pseudo scan 1500/1500 images, kept 15256 boxes
{
  "round": "round004",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round003_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9902,
  "boxes_per_kept_image": 6.641180415828303,
  "mean_conf": 0.8279389420005437,
  "mean_stability": 0.9605109713831662,
  "mean_score": 0.7984847126561343,
  "class_counts": {
    "0": 373,
    "2": 6866,
    "3": 53,
    "4": 307,
    "5": 42,
    "7": 534,
    "8": 1727
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_client4_residential_day_stable_boxes.csv"
}
round004 client5_residential_night: pseudo scan 1/1500 images, kept 10 boxes
round004 client5_residential_night: pseudo scan 250/1500 images, kept 2398 boxes
round004 client5_residential_night: pseudo scan 500/1500 images, kept 4748 boxes
round004 client5_residential_night: pseudo scan 750/1500 images, kept 7098 boxes
round004 client5_residential_night: pseudo scan 1000/1500 images, kept 9511 boxes
round004 client5_residential_night: pseudo scan 1250/1500 images, kept 11912 boxes
round004 client5_residential_night: pseudo scan 1500/1500 images, kept 14331 boxes
{
  "round": "round004",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round003_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1480,
  "pseudo_boxes_kept": 8800,
  "boxes_per_kept_image": 5.945945945945946,
  "mean_conf": 0.7824939103864811,
  "mean_stability": 0.9497081809626384,
  "mean_score": 0.7459108972454291,
  "class_counts": {
    "0": 122,
    "2": 6449,
    "3": 28,
    "4": 88,
    "5": 19,
    "7": 594,
    "8": 1500
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round004_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31162 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round004_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round004_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7871 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client0_highway_day_stable_train' images and labels...5361 found, 2510 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 12347.83it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.828389830508474
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2510 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:52:31.414918213 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:52:31.422518664 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1976       640  0.003437   0.04471  0.005955     4.328:   3%|▎         | 1/39 [00:22<14:02, 22.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003391   0.04346  0.005452     4.184:   5%|▌         | 2/39 [00:23<05:56,  9.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003459   0.04486  0.005467     4.303:   8%|▊         | 3/39 [00:23<03:22,  5.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003433   0.04462  0.005334     4.271:  10%|█         | 4/39 [00:24<02:10,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1924       640  0.003439   0.04412  0.005381     4.236:  13%|█▎        | 5/39 [00:25<01:29,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1922       640  0.003434   0.04355  0.005335     4.186:  15%|█▌        | 6/39 [00:26<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003418   0.04285  0.005315     4.126:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2222       640  0.003419   0.04319   0.00525     4.149:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2165       640  0.003437   0.04342  0.005238     4.168:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003444   0.04364  0.005213     4.184:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003444   0.04333  0.005141     4.153:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2043       640  0.003444   0.04335  0.005178     4.158:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003447   0.04313  0.005162     4.139:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003453   0.04317  0.005148     4.141:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003452   0.04301  0.005086     4.124:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003454   0.04308  0.005062     4.128:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1787       640  0.003459   0.04285  0.005068      4.11:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2071       640  0.003463   0.04268  0.005019     4.093:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640  0.003462   0.04248  0.005022     4.077:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2326       640  0.003456    0.0426  0.005031     4.087:  51%|█████▏    | 20/39 [00:34<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003464   0.04257  0.005039     4.086:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1705       640  0.003454   0.04237  0.004994     4.065:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2057       640  0.003448    0.0423  0.004967     4.057:  59%|█████▉    | 23/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2321       640  0.003451   0.04236  0.004943      4.06:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003454   0.04232  0.004957     4.059:  64%|██████▍   | 25/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2069       640  0.003451   0.04235  0.004926     4.058:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.488      0.458      0.411      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.526      0.414      0.408      0.231
                   0        738       1052      0.517      0.554      0.539      0.257
                   1        738         44      0.405      0.136      0.177     0.0747
                   2        738       8622      0.678      0.732      0.752      0.484
                   3        738        151      0.486      0.417      0.422      0.322
                   4        738        467      0.495      0.571       0.55        0.4
                   5        738         70       0.26      0.414       0.27      0.147
                   6        738         65      0.228     0.0923      0.163     0.0608
                   7        738       1619      0.542      0.623      0.589      0.241
                   8        738       2845       0.65      0.601      0.613      0.319
                   9        738          2          1          0   0.000308   0.000308

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:53:55.404627491 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31163 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round004_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round004_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client1_highway_night_stable_train' images and labels...4895 found, 2930 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<00:00, 12139.56it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.304601323668452
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2930 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:54:12.626495070 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:54:12.627322984 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1922       640  0.003493   0.04185  0.004687     4.003:   2%|▎         | 1/40 [00:22<14:36, 22.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1818       640  0.003446   0.03992  0.004604     3.838:   5%|▌         | 2/40 [00:23<06:10,  9.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640   0.00342   0.03958  0.004633      3.81:   8%|▊         | 3/40 [00:24<03:30,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2035       640  0.003426   0.03975  0.004847     3.842:  10%|█         | 4/40 [00:25<02:15,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003456   0.03946  0.004981     3.832:  12%|█▎        | 5/40 [00:25<01:32,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1779       640  0.003448     0.039  0.004979     3.794:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1878       640  0.003434   0.03862  0.004939     3.759:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003423   0.03856  0.004896      3.75:  20%|██        | 8/40 [00:27<00:41,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003428   0.03838  0.004918     3.738:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003419   0.03844  0.004904     3.741:  25%|██▌       | 10/40 [00:29<00:28,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2168       640  0.003428   0.03865  0.004988     3.765:  28%|██▊       | 11/40 [00:29<00:25,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003422   0.03825   0.00499     3.733:  30%|███       | 12/40 [00:30<00:22,  1.23it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2022       640   0.00343   0.03834  0.004969     3.739:  32%|███▎      | 13/40 [00:31<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1984       640  0.003435   0.03834  0.004945     3.737:  35%|███▌      | 14/40 [00:31<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003441   0.03827  0.004956     3.733:  38%|███▊      | 15/40 [00:32<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1926       640   0.00344    0.0382  0.004953     3.728:  40%|████      | 16/40 [00:33<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1744       640  0.003446   0.03807   0.00497     3.719:  42%|████▎     | 17/40 [00:33<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1838       640   0.00345   0.03798  0.004967     3.712:  45%|████▌     | 18/40 [00:34<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003448   0.03761  0.005007     3.685:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003442   0.03752  0.004998     3.676:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003447   0.03749  0.004993     3.674:  52%|█████▎    | 21/40 [00:36<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640   0.00344   0.03751  0.004982     3.674:  55%|█████▌    | 22/40 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2137       640  0.003439   0.03761  0.004964     3.681:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1959       640   0.00344   0.03756   0.00494     3.675:  60%|██████    | 24/40 [00:38<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003438   0.03747  0.004913     3.665:  62%|██████▎   | 25/40 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2247       640  0.003442    0.0376  0.004909     3.676:  65%|██████▌   | 26/40 [00:39<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.544      0.411      0.409      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.29it/s]

                 all        738      14937      0.523      0.412      0.406      0.229
                   0        738       1052      0.549      0.535      0.532      0.255
                   1        738         44      0.487      0.136      0.194     0.0879
                   2        738       8622      0.647      0.733      0.746      0.477
                   3        738        151      0.421      0.417      0.422      0.319
                   4        738        467      0.461      0.595      0.549      0.398
                   5        738         70      0.264       0.41      0.271      0.137
                   6        738         65      0.237     0.0769      0.164     0.0632
                   7        738       1619       0.55      0.618      0.587      0.241
                   8        738       2845      0.615      0.602        0.6       0.31
                   9        738          2          1          0   0.000262   0.000236

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:55:37.264349802 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31164 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round004_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round004_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 16457.37it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:55:53.937349454 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 14:55:53.012909877 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003566     0.051  0.005022     4.767:   3%|▎         | 1/39 [00:21<13:51, 21.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003518   0.05045  0.005352     4.746:   5%|▌         | 2/39 [00:22<05:53,  9.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003481   0.04952  0.005359     4.669:   8%|▊         | 3/39 [00:23<03:21,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003491   0.04859  0.005249     4.587:  10%|█         | 4/39 [00:24<02:10,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003485   0.04802  0.005148     4.532:  13%|█▎        | 5/39 [00:25<01:29,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003446   0.04697  0.005099     4.441:  15%|█▌        | 6/39 [00:25<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003455   0.04675  0.005173     4.431:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003445   0.04639  0.005118     4.396:  21%|██        | 8/39 [00:27<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003459   0.04641  0.005061     4.395:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003443   0.04615  0.005044     4.371:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003446   0.04608  0.005043     4.366:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003451   0.04562  0.005054      4.33:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003458    0.0455  0.005017     4.318:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003469   0.04555  0.004985      4.32:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640   0.00347    0.0454  0.004963     4.307:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640   0.00346    0.0451  0.004956     4.281:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003452   0.04487  0.004983     4.265:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003444    0.0448  0.004969     4.257:  46%|████▌     | 18/39 [00:33<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003446   0.04452  0.004949     4.233:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003441   0.04452  0.004935     4.232:  51%|█████▏    | 20/39 [00:34<00:12,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003433   0.04436  0.004917     4.216:  54%|█████▍    | 21/39 [00:35<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003429   0.04428  0.004903     4.209:  56%|█████▋    | 22/39 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003422   0.04416  0.004901     4.199:  59%|█████▉    | 23/39 [00:36<00:10,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003418    0.0441  0.004891     4.193:  62%|██████▏   | 24/39 [00:37<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003415   0.04399  0.004888     4.183:  64%|██████▍   | 25/39 [00:38<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003409   0.04396  0.004875     4.179:  67%|██████▋   | 26/39 [00:38<00:08,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.465      0.481       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.504      0.427      0.408       0.23
                   0        738       1052      0.582      0.527       0.54      0.254
                   1        738         44      0.381      0.154      0.162     0.0729
                   2        738       8622       0.62      0.751      0.754      0.483
                   3        738        151      0.338      0.444      0.422       0.32
                   4        738        467      0.441      0.615      0.551      0.397
                   5        738         70      0.269      0.414      0.273      0.141
                   6        738         65      0.283      0.123      0.178     0.0694
                   7        738       1619      0.534      0.625      0.585      0.242
                   8        738       2845      0.595      0.619      0.609      0.322
                   9        738          2          1          0    0.00026   0.000234

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 14:57:19.630643745 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31165 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round004_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round004_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7841 [00:00<?, ?it/s]

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client3_citystreet_night_stable_train' images and labels...4883 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<00:00, 9361.48it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 14:57:36.816403024 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:57:36.002400674 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1926       640  0.003545   0.04384  0.004921     4.185:   2%|▎         | 1/40 [00:22<14:30, 22.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1880       640  0.003539   0.04413  0.004812     4.198:   5%|▌         | 2/40 [00:23<06:09,  9.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1941       640  0.003485   0.04373  0.004998     4.177:   8%|▊         | 3/40 [00:24<03:30,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1935       640  0.003463   0.04276  0.004799     4.081:  10%|█         | 4/40 [00:25<02:16,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1856       640  0.003443    0.0422  0.004719     4.029:  12%|█▎        | 5/40 [00:25<01:34,  2.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1833       640  0.003448   0.04161  0.004682     3.979:  15%|█▌        | 6/40 [00:26<01:08,  2.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1930       640  0.003453   0.04125  0.004633     3.947:  18%|█▊        | 7/40 [00:27<00:52,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1929       640  0.003446   0.04102  0.004694     3.933:  20%|██        | 8/40 [00:27<00:41,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2097       640  0.003436    0.0413  0.004638      3.95:  22%|██▎       | 9/40 [00:28<00:34,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2137       640  0.003441   0.04149  0.004675     3.969:  25%|██▌       | 10/40 [00:29<00:29,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2084       640  0.003441   0.04154  0.004729     3.977:  28%|██▊       | 11/40 [00:29<00:25,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003436   0.04136  0.004714     3.961:  30%|███       | 12/40 [00:30<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2022       640  0.003436    0.0413  0.004733     3.957:  32%|███▎      | 13/40 [00:31<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2204       640  0.003437   0.04134  0.004749     3.962:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1984       640  0.003436   0.04126  0.004755     3.956:  38%|███▊      | 15/40 [00:32<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1739       640  0.003436   0.04097  0.004714      3.93:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1561       640  0.003427   0.04057  0.004762     3.901:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2086       640  0.003434   0.04058    0.0048     3.905:  45%|████▌     | 18/40 [00:34<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1653       640  0.003435   0.04026  0.004804      3.88:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2020       640  0.003429   0.04016  0.004796     3.871:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1982       640   0.00343   0.04009  0.004794     3.865:  52%|█████▎    | 21/40 [00:36<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1762       640  0.003428   0.03992  0.004756     3.849:  55%|█████▌    | 22/40 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2225       640  0.003434      0.04  0.004758     3.855:  57%|█████▊    | 23/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2076       640  0.003434   0.03999  0.004776     3.856:  60%|██████    | 24/40 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1853       640  0.003435   0.03989  0.004757     3.846:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2108       640  0.003433   0.03978  0.004774     3.839:  65%|██████▌   | 26/40 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.542      0.402      0.404      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.539      0.405      0.405      0.228
                   0        738       1052      0.587      0.514      0.531      0.251
                   1        738         44      0.552      0.114      0.181     0.0861
                   2        738       8622      0.642      0.733      0.742       0.47
                   3        738        151      0.449      0.411      0.424       0.32
                   4        738        467      0.456      0.591      0.549      0.396
                   5        738         70      0.286      0.414      0.269      0.137
                   6        738         65      0.254     0.0615      0.167     0.0631
                   7        738       1619      0.547      0.611      0.582      0.241
                   8        738       2845      0.613      0.605      0.604      0.317
                   9        738          2          1          0   0.000218   0.000174

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 14:59:04.843878243 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31166 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round004_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round004_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 12734.76it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 14:59:21.922784021 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 14:59:21.959431943 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2084       640  0.003448   0.04988  0.004317     4.611:   3%|▎         | 1/39 [00:21<13:40, 21.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640   0.00349   0.04958  0.005127     4.656:   5%|▌         | 2/39 [00:22<05:48,  9.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003431   0.04777  0.005068     4.501:   8%|▊         | 3/39 [00:23<03:19,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003446   0.04693  0.005187     4.445:  10%|█         | 4/39 [00:24<02:09,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003421   0.04576  0.005135     4.345:  13%|█▎        | 5/39 [00:24<01:28,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640  0.003428   0.04448  0.005218      4.25:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003441   0.04425   0.00522     4.233:  18%|█▊        | 7/39 [00:26<00:48,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640   0.00345   0.04403  0.005152      4.21:  21%|██        | 8/39 [00:26<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003443   0.04404  0.005205     4.215:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003452   0.04406  0.005177     4.215:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2139       640  0.003452   0.04405  0.005167     4.213:  28%|██▊       | 11/39 [00:28<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640   0.00345   0.04401  0.005147     4.208:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640   0.00346   0.04409  0.005126     4.214:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003468   0.04404  0.005115      4.21:  36%|███▌      | 14/39 [00:30<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003473   0.04377  0.005115     4.188:  38%|███▊      | 15/39 [00:31<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640  0.003472   0.04353  0.005112     4.169:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640   0.00346   0.04333   0.00508      4.15:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003456   0.04331  0.005044     4.145:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1602       640  0.003449   0.04304  0.005035     4.122:  49%|████▊     | 19/39 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2209       640   0.00345   0.04304  0.005022     4.121:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640   0.00345   0.04301     0.005     4.117:  54%|█████▍    | 21/39 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003448   0.04301  0.004997     4.117:  56%|█████▋    | 22/39 [00:35<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640   0.00345   0.04304   0.00502     4.121:  59%|█████▉    | 23/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003448   0.04296  0.005011     4.113:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640  0.003447   0.04296  0.005012     4.113:  64%|██████▍   | 25/39 [00:37<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003447   0.04277  0.004998     4.097:  67%|██████▋   | 26/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.476       0.46       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.464      0.461      0.409      0.231
                   0        738       1052      0.444      0.569      0.534      0.254
                   1        738         44      0.329      0.223      0.174     0.0703
                   2        738       8622      0.607      0.757      0.752       0.48
                   3        738        151      0.292       0.47      0.433      0.329
                   4        738        467      0.396       0.63      0.554      0.404
                   5        738         70      0.255      0.457       0.28      0.139
                   6        738         65      0.268      0.215      0.171     0.0637
                   7        738       1619      0.495      0.647      0.586      0.242
                   8        738       2845      0.559       0.64      0.611      0.323
                   9        738          2          1          0   0.000263   0.000236

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:00:47.690502452 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31167 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round004_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round004_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client5_residential_night_stable_train' images and labels...4885 found, 2956 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<00:00, 10793.53it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.273313414058814
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round004_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2956 missing, 0 empty, 0 corrupted: 100%|██████████| 7841/7841 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:01:04.464932728 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:01:04.472732465 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1885       640  0.003377   0.04167  0.004482     3.963:   2%|▎         | 1/40 [00:23<15:04, 23.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003459   0.04194  0.004719      4.01:   5%|▌         | 2/40 [00:24<06:21, 10.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2035       640  0.003436   0.04246  0.004585     4.039:   8%|▊         | 3/40 [00:24<03:36,  5.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1862       640  0.003446   0.04249   0.00467     4.049:  10%|█         | 4/40 [00:25<02:19,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003434   0.04221  0.004649     4.023:  12%|█▎        | 5/40 [00:26<01:35,  2.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003444   0.04162  0.004594     3.973:  15%|█▌        | 6/40 [00:27<01:08,  2.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1838       640   0.00344     0.041  0.004671     3.929:  18%|█▊        | 7/40 [00:27<00:52,  1.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003443   0.04139  0.004779     3.969:  20%|██        | 8/40 [00:28<00:41,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2099       640  0.003439   0.04143  0.004701     3.965:  22%|██▎       | 9/40 [00:29<00:33,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1983       640  0.003427   0.04133  0.004743      3.96:  25%|██▌       | 10/40 [00:29<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2082       640  0.003421   0.04113  0.004738     3.943:  28%|██▊       | 11/40 [00:30<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003417   0.04098  0.004709     3.928:  30%|███       | 12/40 [00:31<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640  0.003419   0.04082  0.004731     3.918:  32%|███▎      | 13/40 [00:31<00:20,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003422   0.04086  0.004764     3.923:  35%|███▌      | 14/40 [00:32<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003427   0.04072  0.004754     3.912:  38%|███▊      | 15/40 [00:32<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1696       640  0.003425   0.04037  0.004733     3.882:  40%|████      | 16/40 [00:33<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640   0.00343   0.04018  0.004787     3.872:  42%|████▎     | 17/40 [00:34<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640   0.00343   0.03996  0.004816     3.857:  45%|████▌     | 18/40 [00:34<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1648       640  0.003435   0.03971  0.004815     3.837:  48%|████▊     | 19/40 [00:35<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2003       640  0.003442   0.03971  0.004845      3.84:  50%|█████     | 20/40 [00:36<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2181       640  0.003453   0.03965  0.004844     3.835:  52%|█████▎    | 21/40 [00:36<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1759       640  0.003454   0.03952  0.004839     3.825:  55%|█████▌    | 22/40 [00:37<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2138       640  0.003453    0.0395  0.004848     3.824:  57%|█████▊    | 23/40 [00:38<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003447   0.03936  0.004861     3.813:  60%|██████    | 24/40 [00:38<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003444   0.03916  0.004865     3.797:  62%|██████▎   | 25/40 [00:39<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1724       640  0.003448   0.03896   0.00488     3.783:  65%|██████▌   | 26/40 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.412      0.408      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.524      0.415      0.406      0.228
                   0        738       1052      0.551      0.535      0.531      0.253
                   1        738         44       0.46      0.136      0.179     0.0826
                   2        738       8622      0.647      0.728      0.742      0.472
                   3        738        151      0.421      0.417      0.418       0.32
                   4        738        467      0.464      0.597       0.55      0.396
                   5        738         70      0.285      0.414      0.276      0.134
                   6        738         65      0.259     0.0769      0.168     0.0638
                   7        738       1619      0.545      0.624      0.588      0.243
                   8        738       2845      0.604      0.616      0.607      0.319
                   9        738          2          1          0   0.000172   0.000138

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:02:33.452101278 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31168 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round004_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round004_phase1_head_server_repair_start.pt

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:02:50.443951632 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:02:50.492810911 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03343   0.04144  0.004697     6.366:   3%|▎         | 1/31 [00:32<16:10, 32.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03408   0.04234  0.004901     6.506:   6%|▋         | 2/31 [00:33<06:39, 13.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03352   0.04122  0.004807     6.363:  10%|▉         | 3/31 [00:33<03:39,  7.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03295   0.03953  0.004571     6.164:  13%|█▎        | 4/31 [00:34<02:16,  5.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03296   0.03973  0.004608     6.184:  16%|█▌        | 5/31 [00:35<01:29,  3.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03316   0.03973  0.004673     6.205:  19%|█▉        | 6/31 [00:35<01:01,  2.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03327   0.03948  0.004745       6.2:  23%|██▎       | 7/31 [00:36<00:44,  1.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03322   0.03957   0.00477     6.205:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03327    0.0395  0.004671     6.195:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03325   0.03963  0.004652     6.203:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03322   0.03967  0.004677     6.205:  35%|███▌      | 11/31 [00:38<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03313    0.0394  0.004674     6.176:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0331   0.03944  0.004624     6.173:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03312   0.03927   0.00459     6.158:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03315    0.0392  0.004632     6.159:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03315   0.03908  0.004624     6.148:  52%|█████▏    | 16/31 [00:41<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03319   0.03914  0.004589     6.153:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03323    0.0392  0.004551     6.159:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03317   0.03907  0.004518     6.141:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03317   0.03931  0.004521      6.16:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640    0.0332   0.03935   0.00454     6.167:  68%|██████▊   | 21/31 [00:44<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03321   0.03946  0.004511     6.175:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640    0.0332   0.03951  0.004497     6.177:  74%|███████▍  | 23/31 [00:45<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03321    0.0396  0.004483     6.184:  77%|███████▋  | 24/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03322   0.03956  0.004495     6.183:  81%|████████  | 25/31 [00:46<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03328   0.03961  0.004498     6.191:  84%|████████▍ | 26/31 [00:47<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.487      0.452      0.413      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.563      0.399      0.411      0.232
                   0        738       1052      0.577      0.529      0.542      0.259
                   1        738         44      0.497     0.0909      0.161     0.0693
                   2        738       8622      0.689       0.73      0.754      0.488
                   3        738        151      0.528      0.411      0.428       0.32
                   4        738        467      0.519      0.561      0.556      0.402
                   5        738         70      0.271      0.414      0.282      0.143
                   6        738         65      0.307     0.0612      0.183     0.0657
                   7        738       1619      0.596      0.587      0.588      0.245
                   8        738       2845      0.651      0.602      0.616      0.327
                   9        738          2          1          0   0.000333     0.0003

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round004_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 15:04:28.600830428 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round005 phase_round=5 ===

02 head-to-full DQA:  12%|█▎        | 4/32 [57:09<6:40:01, 857.18s/round, elapsed=57m09s, eta=6h40m08s, phase=phase1_head, round=4]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round005 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round005 client0_highway_day: pseudo scan 250/1500 images, kept 2374 boxes
round005 client0_highway_day: pseudo scan 500/1500 images, kept 4816 boxes
round005 client0_highway_day: pseudo scan 750/1500 images, kept 7178 boxes
round005 client0_highway_day: pseudo scan 1000/1500 images, kept 9573 boxes
round005 client0_highway_day: pseudo scan 1250/1500 images, kept 11905 boxes
round005 client0_highway_day: pseudo scan 1500/1500 images, kept 14287 boxes
{
  "round": "round005",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round004_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11139,
  "boxes_per_kept_image": 7.460817146684528,
  "mean_conf": 0.7969410908116249,
  "mean_stability": 0.9546483288398604,
  "mean_score": 0.7640104384640004,
  "class_counts": {
    "0": 151,
    "2": 6430,
    "3": 109,
    "4": 523,
    "5": 8,
    "7": 555,
    "8": 3363
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_client0_highway_day_stable_boxes.csv"
}
round005 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round005 client1_highway_night: pseudo scan 250/1500 images, kept 1697 boxes
round005 client1_highway_night: pseudo scan 500/1500 images, kept 3526 boxes
round005 client1_highway_night: pseudo scan 750/1500 images, kept 5335 boxes
round005 client1_highway_night: pseudo scan 1000/1500 images, kept 7045 boxes
round005 client1_highway_night: pseudo scan 1250/1500 images, kept 8822 boxes
round005 client1_highway_night: pseudo scan 1500/1500 images, kept 10549 boxes
{
  "round": "round005",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round004_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1470,
  "pseudo_boxes_kept": 8535,
  "boxes_per_kept_image": 5.8061224489795915,
  "mean_conf": 0.7066614490890615,
  "mean_stability": 0.9384784810502556,
  "mean_score": 0.6671998567285842,
  "class_counts": {
    "0": 61,
    "2": 4748,
    "3": 27,
    "4": 137,
    "5": 7,
    "7": 534,
    "8": 3021
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_client1_highway_night_stable_boxes.csv"
}
round005 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round005 client2_citystreet_day: pseudo scan 250/1500 images, kept 2696 boxes
round005 client2_citystreet_day: pseudo scan 500/1500 images, kept 5421 boxes
round005 client2_citystreet_day: pseudo scan 750/1500 images, kept 8172 boxes
round005 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10937 boxes
round005 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13664 boxes
round005 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16312 boxes
{
  "round": "round005",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round004_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13722,
  "boxes_per_kept_image": 9.172459893048128,
  "mean_conf": 0.7929130696230459,
  "mean_stability": 0.9522637439406556,
  "mean_score": 0.7585307020610268,
  "class_counts": {
    "0": 1462,
    "2": 7341,
    "3": 182,
    "4": 577,
    "5": 65,
    "7": 1522,
    "8": 2573
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_client2_citystreet_day_stable_boxes.csv"
}
round005 client3_citystreet_night: pseudo scan 1/1500 images, kept 8 boxes
round005 client3_citystreet_night: pseudo scan 250/1500 images, kept 2413 boxes
round005 client3_citystreet_night: pseudo scan 500/1500 images, kept 4777 boxes
round005 client3_citystreet_night: pseudo scan 750/1500 images, kept 7116 boxes
round005 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9399 boxes
round005 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11854 boxes
round005 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14218 boxes
{
  "round": "round005",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round004_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1478,
  "pseudo_boxes_kept": 11812,
  "boxes_per_kept_image": 7.991880920162382,
  "mean_conf": 0.7058202440314603,
  "mean_stability": 0.9362419387808179,
  "mean_score": 0.6650962344796161,
  "class_counts": {
    "0": 545,
    "2": 6399,
    "3": 67,
    "4": 152,
    "5": 36,
    "7": 1885,
    "8": 2728
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_client3_citystreet_night_stable_boxes.csv"
}
round005 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round005 client4_residential_day: pseudo scan 250/1500 images, kept 2585 boxes
round005 client4_residential_day: pseudo scan 500/1500 images, kept 5195 boxes
round005 client4_residential_day: pseudo scan 750/1500 images, kept 7748 boxes
round005 client4_residential_day: pseudo scan 1000/1500 images, kept 10236 boxes
round005 client4_residential_day: pseudo scan 1250/1500 images, kept 12767 boxes
round005 client4_residential_day: pseudo scan 1500/1500 images, kept 15246 boxes
{
  "round": "round005",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round004_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9914,
  "boxes_per_kept_image": 6.649228705566734,
  "mean_conf": 0.8310869412332479,
  "mean_stability": 0.9604729263621856,
  "mean_score": 0.8015435338241347,
  "class_counts": {
    "0": 377,
    "2": 6861,
    "3": 58,
    "4": 303,
    "5": 44,
    "7": 541,
    "8": 1730
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_client4_residential_day_stable_boxes.csv"
}
round005 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round005 client5_residential_night: pseudo scan 250/1500 images, kept 2384 boxes
round005 client5_residential_night: pseudo scan 500/1500 images, kept 4727 boxes
round005 client5_residential_night: pseudo scan 750/1500 images, kept 7064 boxes
round005 client5_residential_night: pseudo scan 1000/1500 images, kept 9466 boxes
round005 client5_residential_night: pseudo scan 1250/1500 images, kept 11855 boxes
round005 client5_residential_night: pseudo scan 1500/1500 images, kept 14279 boxes
{
  "round": "round005",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round004_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1478,
  "pseudo_boxes_kept": 8780,
  "boxes_per_kept_image": 5.940460081190798,
  "mean_conf": 0.7851454518345059,
  "mean_stability": 0.9499668811136063,
  "mean_score": 0.748682141556188,
  "class_counts": {
    "0": 127,
    "2": 6426,
    "3": 29,
    "4": 92,
    "5": 21,
    "7": 596,
    "8": 1489
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round005_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31169 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round005_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round005_phase1_head_client0_highway_day_start.pt

self imgsz: 640
self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 16108.39it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:06:43.086020513 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:06:43.165031111 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2068       640  0.003455   0.04158  0.004818     3.988:   3%|▎         | 1/39 [00:21<13:44, 21.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2014       640  0.003459   0.04202  0.004548     4.002:   5%|▌         | 2/39 [00:22<05:57,  9.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2013       640  0.003495   0.04284   0.00467      4.08:   8%|▊         | 3/39 [00:23<03:23,  5.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2081       640  0.003455   0.04299  0.004827     4.102:  10%|█         | 4/39 [00:24<02:11,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1852       640  0.003441   0.04237  0.004856     4.053:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1711       640  0.003435   0.04151  0.004811     3.981:  15%|█▌        | 6/39 [00:25<01:04,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1997       640  0.003429   0.04156  0.004783     3.982:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2084       640  0.003422    0.0419  0.004846     4.014:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2135       640  0.003427   0.04246  0.004914     4.064:  23%|██▎       | 9/39 [00:27<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2169       640  0.003439    0.0428  0.004922     4.093:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2061       640  0.003427   0.04271  0.004858     4.079:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1868       640  0.003429   0.04255  0.004879     4.069:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2072       640  0.003434   0.04241  0.004874     4.057:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2233       640  0.003441    0.0426  0.004837      4.07:  36%|███▌      | 14/39 [00:31<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1954       640  0.003432   0.04246  0.004808     4.056:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2042       640  0.003438   0.04239  0.004814     4.051:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1766       640  0.003437   0.04212  0.004813      4.03:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1986       640   0.00344    0.0421  0.004814     4.028:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1720       640  0.003436   0.04192   0.00482     4.014:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2386       640   0.00344   0.04204  0.004825     4.024:  51%|█████▏    | 20/39 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2046       640  0.003441   0.04209  0.004809     4.027:  54%|█████▍    | 21/39 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1853       640  0.003442   0.04197  0.004784     4.016:  56%|█████▋    | 22/39 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2251       640  0.003442   0.04202  0.004755     4.017:  59%|█████▉    | 23/39 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2088       640  0.003444   0.04199  0.004748     4.015:  62%|██████▏   | 24/39 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2046       640   0.00344    0.0419  0.004736     4.006:  64%|██████▍   | 25/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2154       640  0.003438    0.0419   0.00473     4.005:  67%|██████▋   | 26/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.541      0.418      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.543      0.408      0.408      0.231
                   0        738       1052      0.528      0.552       0.54      0.256
                   1        738         44      0.447      0.114      0.169     0.0711
                   2        738       8622      0.691      0.729      0.753      0.484
                   3        738        151      0.531      0.417      0.429      0.326
                   4        738        467      0.489      0.572      0.551        0.4
                   5        738         70      0.265        0.4      0.275      0.148
                   6        738         65      0.265     0.0769      0.162     0.0603
                   7        738       1619      0.556       0.62      0.591      0.242
                   8        738       2845      0.658      0.602      0.614      0.321
                   9        738          2          1          0   0.000316   0.000284

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:08:10.290191986 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31170 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round005_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round005_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client1_highway_night_stable_train' images and labels...4895 found, 2926 missing, 0 empty, 0 corrupted: 100%|██████████| 7821/7821 [00:00<00:00, 11756.49it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.309426229508198
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2926 missing, 0 empty, 0 corrupted: 100%|██████████| 7821/7821 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:08:26.225958660 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:08:26.232050258 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1957       640  0.003487   0.04047  0.005233     3.936:   2%|▎         | 1/40 [00:22<14:19, 22.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003505    0.0405  0.005095     3.928:   5%|▌         | 2/40 [00:22<06:05,  9.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003445   0.03992  0.004726     3.847:   8%|▊         | 3/40 [00:23<03:27,  5.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640   0.00342   0.03966  0.004737     3.826:  10%|█         | 4/40 [00:24<02:13,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003442   0.03888  0.004655     3.758:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003449   0.03916  0.004817     3.794:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003453   0.03893  0.004862      3.78:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003446   0.03887  0.004801      3.77:  20%|██        | 8/40 [00:27<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003458   0.03903  0.004828     3.785:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003453   0.03899  0.004791     3.779:  25%|██▌       | 10/40 [00:28<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640   0.00345   0.03902  0.004799     3.781:  28%|██▊       | 11/40 [00:29<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2004       640  0.003445   0.03898  0.004827      3.78:  30%|███       | 12/40 [00:29<00:21,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640  0.003447   0.03895  0.004825     3.778:  32%|███▎      | 13/40 [00:30<00:19,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003449   0.03875   0.00482     3.761:  35%|███▌      | 14/40 [00:30<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1738       640  0.003442   0.03847  0.004803     3.737:  38%|███▊      | 15/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003435   0.03829  0.004788     3.721:  40%|████      | 16/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003437   0.03812  0.004784     3.707:  42%|████▎     | 17/40 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1946       640  0.003443   0.03801  0.004805     3.701:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1726       640  0.003441   0.03775  0.004847     3.683:  48%|████▊     | 19/40 [00:34<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003441   0.03777  0.004818     3.683:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2016       640  0.003449   0.03776   0.00483     3.683:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640  0.003447   0.03773  0.004872     3.684:  55%|█████▌    | 22/40 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640   0.00344   0.03771   0.00488     3.683:  57%|█████▊    | 23/40 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2186       640  0.003438   0.03772    0.0049     3.684:  60%|██████    | 24/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1842       640  0.003437    0.0376   0.00491     3.675:  62%|██████▎   | 25/40 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003433   0.03757  0.004884     3.671:  65%|██████▌   | 26/40 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.551      0.411      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937       0.55      0.408       0.41      0.231
                   0        738       1052      0.576      0.531      0.536      0.256
                   1        738         44      0.598      0.135        0.2     0.0889
                   2        738       8622       0.67      0.729      0.748      0.478
                   3        738        151      0.493      0.412      0.432      0.331
                   4        738        467      0.475      0.582      0.549      0.398
                   5        738         70       0.27      0.429       0.28       0.14
                   6        738         65      0.214     0.0615      0.162     0.0626
                   7        738       1619      0.562      0.612      0.585       0.24
                   8        738       2845      0.638      0.588      0.603      0.311
                   9        738          2          1          0   0.000286   0.000257

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:09:53.665335227 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31171 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round005_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round005_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 9193.36it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:10:10.545293260 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:10:10.567140925 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2066       640  0.003555    0.0511  0.004943     4.768:   3%|▎         | 1/39 [00:22<14:13, 22.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003508   0.05049  0.005281     4.742:   5%|▌         | 2/39 [00:23<06:02,  9.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640   0.00347   0.04954  0.005285     4.664:   8%|▊         | 3/39 [00:24<03:25,  5.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003481    0.0486  0.005173      4.58:  10%|█         | 4/39 [00:25<02:13,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003475   0.04801  0.005078     4.525:  13%|█▎        | 5/39 [00:25<01:31,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003436   0.04695   0.00503     4.433:  15%|█▌        | 6/39 [00:26<01:05,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003445   0.04672  0.005102     4.422:  18%|█▊        | 7/39 [00:27<00:49,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003435   0.04635  0.005048     4.387:  21%|██        | 8/39 [00:27<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003449   0.04637   0.00499     4.385:  23%|██▎       | 9/39 [00:28<00:32,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003433   0.04611  0.004974     4.362:  26%|██▌       | 10/39 [00:29<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003436   0.04604  0.004972     4.356:  28%|██▊       | 11/39 [00:29<00:24,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003441   0.04557  0.004983      4.32:  31%|███       | 12/39 [00:30<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003449   0.04545  0.004947     4.307:  33%|███▎      | 13/39 [00:31<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003459   0.04549  0.004915     4.309:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640   0.00346   0.04534  0.004893     4.295:  38%|███▊      | 15/39 [00:32<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640   0.00345   0.04503  0.004884     4.269:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003441    0.0448  0.004911     4.252:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003434   0.04473  0.004897     4.245:  46%|████▌     | 18/39 [00:34<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003436   0.04445  0.004878     4.221:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003431   0.04445  0.004865      4.22:  51%|█████▏    | 20/39 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003423   0.04428  0.004847     4.204:  54%|█████▍    | 21/39 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003418    0.0442  0.004834     4.196:  56%|█████▋    | 22/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003411   0.04409  0.004833     4.187:  59%|█████▉    | 23/39 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003408   0.04403  0.004822      4.18:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003404   0.04392  0.004819     4.171:  64%|██████▍   | 25/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003399   0.04388  0.004805     4.167:  67%|██████▋   | 26/39 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.464      0.483       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.523      0.418      0.407      0.231
                   0        738       1052      0.618       0.52      0.538      0.255
                   1        738         44      0.378      0.125      0.158     0.0733
                   2        738       8622      0.639      0.744      0.753      0.482
                   3        738        151       0.37      0.444      0.425      0.321
                   4        738        467      0.454      0.608      0.549      0.397
                   5        738         70      0.293      0.414      0.269      0.143
                   6        738         65       0.31     0.0923      0.186     0.0725
                   7        738       1619      0.552      0.619      0.586      0.242
                   8        738       2845      0.614      0.608       0.61      0.322
                   9        738          2          1          0   0.000261   0.000261

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:11:34.700219081 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31172 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round005_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round005_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client3_citystreet_night_stable_train' images and labels...4883 found, 2954 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<00:00, 10586.56it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.275715633847122
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2954 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:11:51.355772892 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:11:51.391857000 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1803       640  0.003473   0.04194  0.005269     4.054:   2%|▎         | 1/40 [00:23<15:26, 23.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1615       640  0.003453   0.04209  0.005214      4.06:   5%|▌         | 2/40 [00:24<06:33, 10.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003451   0.04262  0.005075     4.092:   8%|▊         | 3/40 [00:25<03:42,  6.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640   0.00343    0.0422  0.004982     4.049:  10%|█         | 4/40 [00:26<02:22,  3.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1777       640  0.003411   0.04127  0.004845     3.962:  12%|█▎        | 5/40 [00:27<01:37,  2.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1607       640  0.003379   0.04035  0.004734     3.877:  15%|█▌        | 6/40 [00:27<01:09,  2.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2031       640  0.003389   0.04039  0.004722      3.88:  18%|█▊        | 7/40 [00:28<00:52,  1.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003375    0.0403  0.004706     3.871:  20%|██        | 8/40 [00:29<00:41,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003384   0.04043  0.004701     3.882:  22%|██▎       | 9/40 [00:29<00:33,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003392   0.04053  0.004697      3.89:  25%|██▌       | 10/40 [00:30<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1826       640  0.003401   0.04026  0.004686     3.867:  28%|██▊       | 11/40 [00:30<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1958       640  0.003398   0.04028   0.00464     3.866:  30%|███       | 12/40 [00:31<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2203       640  0.003395   0.04041  0.004648     3.876:  32%|███▎      | 13/40 [00:32<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1946       640   0.00339   0.04029  0.004645     3.866:  35%|███▌      | 14/40 [00:32<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003382   0.04014  0.004631     3.852:  38%|███▊      | 15/40 [00:33<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2140       640  0.003392   0.04014  0.004621     3.852:  40%|████      | 16/40 [00:34<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1749       640  0.003395   0.03992   0.00461     3.834:  42%|████▎     | 17/40 [00:34<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640  0.003399   0.03981  0.004622     3.827:  45%|████▌     | 18/40 [00:35<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1908       640  0.003407   0.03972  0.004625      3.82:  48%|████▊     | 19/40 [00:35<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003402   0.03964  0.004645     3.815:  50%|█████     | 20/40 [00:36<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003414   0.03955  0.004672     3.811:  52%|█████▎    | 21/40 [00:37<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1981       640  0.003416   0.03946  0.004668     3.804:  55%|█████▌    | 22/40 [00:37<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640   0.00342   0.03944  0.004675     3.803:  57%|█████▊    | 23/40 [00:38<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2012       640  0.003421   0.03937  0.004682     3.798:  60%|██████    | 24/40 [00:39<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2016       640  0.003421   0.03932  0.004692     3.794:  62%|██████▎   | 25/40 [00:39<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003417   0.03925  0.004694     3.789:  65%|██████▌   | 26/40 [00:40<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.566      0.403      0.409      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.552      0.404      0.406      0.229
                   0        738       1052      0.596      0.511      0.528      0.251
                   1        738         44      0.484      0.114      0.196     0.0876
                   2        738       8622      0.651      0.731      0.743      0.472
                   3        738        151      0.493      0.411      0.428      0.323
                   4        738        467      0.464      0.589      0.553      0.394
                   5        738         70      0.279      0.414      0.271      0.137
                   6        738         65      0.332     0.0764      0.164     0.0639
                   7        738       1619      0.567      0.603       0.58       0.24
                   8        738       2845      0.655      0.589      0.602      0.317
                   9        738          2          1          0   0.000206   0.000206

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:13:17.058444397 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31173 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round005_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round005_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client4_residential_day_stable_train' images and labels...:   0%|          | 0/7863 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 18563.49it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:13:33.172455727 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:13:33.197957641 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2084       640  0.003439   0.04994  0.004249      4.61:   3%|▎         | 1/39 [00:22<14:11, 22.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003479   0.04961  0.005062     4.652:   5%|▌         | 2/39 [00:23<06:01,  9.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640   0.00342   0.04773  0.005005     4.493:   8%|▊         | 3/39 [00:24<03:25,  5.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003435   0.04688  0.005127     4.436:  10%|█         | 4/39 [00:25<02:12,  3.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640   0.00341   0.04571  0.005079     4.336:  13%|█▎        | 5/39 [00:25<01:30,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640  0.003418   0.04443  0.005161      4.24:  15%|█▌        | 6/39 [00:26<01:05,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003431   0.04419   0.00516     4.222:  18%|█▊        | 7/39 [00:27<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640   0.00344   0.04396  0.005091       4.2:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003433   0.04397  0.005146     4.204:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003442   0.04399  0.005118     4.204:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2139       640  0.003442   0.04398  0.005108     4.202:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640  0.003441   0.04394  0.005085     4.197:  31%|███       | 12/39 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640   0.00345   0.04402  0.005065     4.203:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003458   0.04397  0.005053     4.199:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003463   0.04369  0.005052     4.177:  38%|███▊      | 15/39 [00:32<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640  0.003462   0.04345  0.005048     4.157:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640   0.00345   0.04325  0.005016     4.137:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003446   0.04323  0.004981     4.132:  46%|████▌     | 18/39 [00:34<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1602       640  0.003439   0.04295  0.004973     4.109:  49%|████▊     | 19/39 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2209       640   0.00344   0.04295  0.004959     4.108:  51%|█████▏    | 20/39 [00:35<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640   0.00344   0.04292  0.004935     4.103:  54%|█████▍    | 21/39 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003438   0.04292  0.004933     4.103:  56%|█████▋    | 22/39 [00:36<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640   0.00344   0.04295  0.004956     4.108:  59%|█████▉    | 23/39 [00:37<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003437   0.04287  0.004947       4.1:  62%|██████▏   | 24/39 [00:38<00:10,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640  0.003437   0.04286  0.004948       4.1:  64%|██████▍   | 25/39 [00:38<00:09,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003437   0.04268  0.004934     4.084:  67%|██████▋   | 26/39 [00:39<00:08,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.481      0.458      0.411      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.24it/s]

                 all        738      14937      0.466      0.459      0.409      0.231
                   0        738       1052      0.452      0.576      0.539      0.254
                   1        738         44      0.344      0.227      0.165     0.0692
                   2        738       8622       0.61      0.755      0.751       0.48
                   3        738        151      0.289       0.47      0.438      0.331
                   4        738        467      0.397      0.628      0.555      0.403
                   5        738         70      0.247      0.441       0.28       0.14
                   6        738         65      0.259       0.21      0.168     0.0632
                   7        738       1619      0.496      0.641       0.58      0.242
                   8        738       2845      0.565      0.639      0.612      0.323
                   9        738          2          1          0   0.000269   0.000242

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:14:59.065608546 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31174 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round005_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round005_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client5_residential_night_stable_train' images and labels...4885 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<00:00, 10922.01it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.278118609406953
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round005_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:15:14.185064538 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:15:14.208990059 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1875       640  0.003474   0.04293  0.004863     4.102:   2%|▎         | 1/40 [00:22<14:27, 22.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003496   0.04253   0.00495     4.078:   5%|▌         | 2/40 [00:23<06:08,  9.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1892       640  0.003441   0.04228  0.004803     4.042:   8%|▊         | 3/40 [00:24<03:29,  5.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003419   0.04255  0.004712     4.054:  10%|█         | 4/40 [00:24<02:15,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2116       640  0.003441   0.04269   0.00469     4.065:  12%|█▎        | 5/40 [00:25<01:32,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1761       640  0.003434   0.04201   0.00471     4.013:  15%|█▌        | 6/40 [00:26<01:07,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1953       640  0.003443    0.0417    0.0048     3.995:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003456   0.04161  0.004828     3.992:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640  0.003461   0.04155  0.004776     3.983:  22%|██▎       | 9/40 [00:28<00:33,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003461   0.04144  0.004809     3.977:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003467   0.04157  0.004876     3.993:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1729       640  0.003457   0.04117   0.00484     3.957:  30%|███       | 12/40 [00:30<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003448    0.0409  0.004788     3.931:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003448    0.0406  0.004833     3.911:  35%|███▌      | 14/40 [00:31<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003448   0.04044  0.004849     3.899:  38%|███▊      | 15/40 [00:32<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003445   0.04021  0.004836      3.88:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2102       640  0.003448   0.04029  0.004821     3.885:  42%|████▎     | 17/40 [00:33<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003455   0.04019  0.004832     3.878:  45%|████▌     | 18/40 [00:34<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003463    0.0399  0.004854     3.857:  48%|████▊     | 19/40 [00:34<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003461   0.03972  0.004859     3.843:  50%|█████     | 20/40 [00:35<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003462    0.0395  0.004859     3.826:  52%|█████▎    | 21/40 [00:35<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003466   0.03934  0.004878     3.815:  55%|█████▌    | 22/40 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003467   0.03933  0.004894     3.815:  57%|█████▊    | 23/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003465   0.03927  0.004887     3.809:  60%|██████    | 24/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003467   0.03923  0.004898     3.808:  62%|██████▎   | 25/40 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640   0.00347   0.03904  0.004885     3.791:  65%|██████▌   | 26/40 [00:39<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.562      0.408       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.553      0.411      0.409      0.231
                   0        738       1052      0.561      0.532       0.53      0.255
                   1        738         44      0.491      0.136        0.2     0.0933
                   2        738       8622      0.662      0.724      0.742      0.474
                   3        738        151      0.474      0.411      0.423      0.323
                   4        738        467      0.475      0.591      0.551      0.396
                   5        738         70      0.309      0.421      0.277      0.137
                   6        738         65      0.351     0.0749      0.167      0.066
                   7        738       1619      0.569      0.618      0.592      0.243
                   8        738       2845      0.638      0.601      0.608      0.319
                   9        738          2          1          0   0.000187   0.000187

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:16:41.403665381 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31175 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round005_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round005_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:16:57.091586831 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:16:57.101065502 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03298   0.04064  0.004536     6.252:   3%|▎         | 1/31 [00:33<16:49, 33.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03361    0.0415  0.004731     6.387:   6%|▋         | 2/31 [00:34<07:00, 14.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03306   0.04038  0.004644     6.246:  10%|▉         | 3/31 [00:35<03:50,  8.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03249   0.03871  0.004412     6.049:  13%|█▎        | 4/31 [00:36<02:23,  5.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03251   0.03891  0.004453      6.07:  16%|█▌        | 5/31 [00:36<01:33,  3.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03271   0.03892  0.004517     6.091:  19%|█▉        | 6/31 [00:37<01:04,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03283   0.03868  0.004586     6.088:  23%|██▎       | 7/31 [00:38<00:46,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03277   0.03878  0.004609     6.093:  26%|██▌       | 8/31 [00:38<00:34,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03283   0.03871   0.00451     6.084:  29%|██▉       | 9/31 [00:39<00:26,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03282   0.03884  0.004489     6.092:  32%|███▏      | 10/31 [00:39<00:21,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03279   0.03888  0.004515     6.095:  35%|███▌      | 11/31 [00:40<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640    0.0327   0.03862  0.004513     6.067:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03267   0.03866  0.004463     6.063:  42%|████▏     | 13/31 [00:41<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03269    0.0385  0.004428      6.05:  45%|████▌     | 14/31 [00:42<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03272   0.03844  0.004472     6.051:  48%|████▊     | 15/31 [00:42<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03272   0.03833  0.004465     6.041:  52%|█████▏    | 16/31 [00:43<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03277   0.03839  0.004434     6.047:  55%|█████▍    | 17/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03282   0.03846  0.004398     6.054:  58%|█████▊    | 18/31 [00:44<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03276   0.03834  0.004366     6.037:  61%|██████▏   | 19/31 [00:45<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03276   0.03857  0.004369     6.056:  65%|██████▍   | 20/31 [00:45<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640    0.0328   0.03862  0.004388     6.064:  68%|██████▊   | 21/31 [00:46<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03281   0.03874   0.00436     6.072:  71%|███████   | 22/31 [00:46<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640    0.0328   0.03879  0.004344     6.075:  74%|███████▍  | 23/31 [00:47<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03282   0.03889  0.004331     6.083:  77%|███████▋  | 24/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03283   0.03886  0.004344     6.083:  81%|████████  | 25/31 [00:48<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03289   0.03891   0.00435     6.092:  84%|████████▍ | 26/31 [00:49<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.485      0.462      0.413      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.16it/s]

                 all        738      14937      0.467      0.465       0.41      0.232
                   0        738       1052       0.46      0.587      0.544      0.261
                   1        738         44      0.294      0.227      0.157     0.0687
                   2        738       8622      0.589      0.764      0.754      0.488
                   3        738        151      0.304       0.45      0.431      0.325
                   4        738        467      0.437      0.612      0.553        0.4
                   5        738         70      0.228      0.457      0.288      0.145
                   6        738         65       0.29      0.277      0.175     0.0643
                   7        738       1619      0.515      0.634      0.585      0.244
                   8        738       2845      0.554      0.643      0.613      0.326
                   9        738          2          1          0    0.00034   0.000306

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round005_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 15:18:38.779805948 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round006 phase_round=6 ===

02 head-to-full DQA:  16%|█▌        | 5/32 [1:11:20<6:24:37, 854.71s/round, elapsed=1h11m20s, eta=6h25m12s, phase=phase1_head, round=5]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round006 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round006 client0_highway_day: pseudo scan 250/1500 images, kept 2374 boxes
round006 client0_highway_day: pseudo scan 500/1500 images, kept 4824 boxes
round006 client0_highway_day: pseudo scan 750/1500 images, kept 7191 boxes
round006 client0_highway_day: pseudo scan 1000/1500 images, kept 9588 boxes
round006 client0_highway_day: pseudo scan 1250/1500 images, kept 11923 boxes
round006 client0_highway_day: pseudo scan 1500/1500 images, kept 14303 boxes
{
  "round": "round006",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round005_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11191,
  "boxes_per_kept_image": 7.495646349631614,
  "mean_conf": 0.7989922561734774,
  "mean_stability": 0.9541482840676418,
  "mean_score": 0.7656249325864295,
  "class_counts": {
    "0": 156,
    "2": 6437,
    "3": 113,
    "4": 534,
    "5": 6,
    "7": 557,
    "8": 3388
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_client0_highway_day_stable_boxes.csv"
}
round006 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round006 client1_highway_night: pseudo scan 250/1500 images, kept 1677 boxes
round006 client1_highway_night: pseudo scan 500/1500 images, kept 3488 boxes
round006 client1_highway_night: pseudo scan 750/1500 images, kept 5288 boxes
round006 client1_highway_night: pseudo scan 1000/1500 images, kept 6989 boxes
round006 client1_highway_night: pseudo scan 1250/1500 images, kept 8763 boxes
round006 client1_highway_night: pseudo scan 1500/1500 images, kept 10476 boxes
{
  "round": "round006",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round005_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1466,
  "pseudo_boxes_kept": 8511,
  "boxes_per_kept_image": 5.805593451568895,
  "mean_conf": 0.7100922516448113,
  "mean_stability": 0.9383486553933811,
  "mean_score": 0.6703974726647941,
  "class_counts": {
    "0": 63,
    "2": 4715,
    "3": 28,
    "4": 138,
    "5": 7,
    "7": 546,
    "8": 3014
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_client1_highway_night_stable_boxes.csv"
}
round006 client2_citystreet_day: pseudo scan 1/1500 images, kept 5 boxes
round006 client2_citystreet_day: pseudo scan 250/1500 images, kept 2696 boxes
round006 client2_citystreet_day: pseudo scan 500/1500 images, kept 5418 boxes
round006 client2_citystreet_day: pseudo scan 750/1500 images, kept 8173 boxes
round006 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10941 boxes
round006 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13670 boxes
round006 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16325 boxes
{
  "round": "round006",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round005_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13724,
  "boxes_per_kept_image": 9.17379679144385,
  "mean_conf": 0.7966836325800374,
  "mean_stability": 0.9521161569855158,
  "mean_score": 0.7620881301043203,
  "class_counts": {
    "0": 1457,
    "2": 7347,
    "3": 185,
    "4": 580,
    "5": 68,
    "7": 1513,
    "8": 2574
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_client2_citystreet_day_stable_boxes.csv"
}
round006 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round006 client3_citystreet_night: pseudo scan 250/1500 images, kept 2394 boxes
round006 client3_citystreet_night: pseudo scan 500/1500 images, kept 4757 boxes
round006 client3_citystreet_night: pseudo scan 750/1500 images, kept 7092 boxes
round006 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9361 boxes
round006 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11799 boxes
round006 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14162 boxes
{
  "round": "round006",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round005_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 11801,
  "boxes_per_kept_image": 7.995257452574526,
  "mean_conf": 0.708672485920486,
  "mean_stability": 0.9360074507372933,
  "mean_score": 0.6676755122033422,
  "class_counts": {
    "0": 550,
    "2": 6373,
    "3": 68,
    "4": 152,
    "5": 36,
    "7": 1912,
    "8": 2710
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_client3_citystreet_night_stable_boxes.csv"
}
round006 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round006 client4_residential_day: pseudo scan 250/1500 images, kept 2585 boxes
round006 client4_residential_day: pseudo scan 500/1500 images, kept 5197 boxes
round006 client4_residential_day: pseudo scan 750/1500 images, kept 7752 boxes
round006 client4_residential_day: pseudo scan 1000/1500 images, kept 10237 boxes
round006 client4_residential_day: pseudo scan 1250/1500 images, kept 12765 boxes
round006 client4_residential_day: pseudo scan 1500/1500 images, kept 15246 boxes
{
  "round": "round006",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round005_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9932,
  "boxes_per_kept_image": 6.66130114017438,
  "mean_conf": 0.8339410527064298,
  "mean_stability": 0.9603955883246201,
  "mean_score": 0.804290800812441,
  "class_counts": {
    "0": 381,
    "2": 6861,
    "3": 62,
    "4": 302,
    "5": 44,
    "7": 541,
    "8": 1741
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_client4_residential_day_stable_boxes.csv"
}
round006 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round006 client5_residential_night: pseudo scan 250/1500 images, kept 2371 boxes
round006 client5_residential_night: pseudo scan 500/1500 images, kept 4707 boxes
round006 client5_residential_night: pseudo scan 750/1500 images, kept 7035 boxes
round006 client5_residential_night: pseudo scan 1000/1500 images, kept 9443 boxes
round006 client5_residential_night: pseudo scan 1250/1500 images, kept 11831 boxes
round006 client5_residential_night: pseudo scan 1500/1500 images, kept 14251 boxes
{
  "round": "round006",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round005_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1478,
  "pseudo_boxes_kept": 8781,
  "boxes_per_kept_image": 5.941136671177267,
  "mean_conf": 0.7867862382676089,
  "mean_stability": 0.9499624596751506,
  "mean_score": 0.7502242504099289,
  "class_counts": {
    "0": 130,
    "2": 6413,
    "3": 30,
    "4": 92,
    "5": 22,
    "7": 611,
    "8": 1483
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round006_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31176 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round006_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round006_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 22278.72it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:20:54.524111664 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:20:54.588284552 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2068       640  0.003446   0.04165  0.004757     3.988:   3%|▎         | 1/39 [00:22<14:00, 22.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2014       640  0.003451   0.04204  0.004489     3.999:   5%|▌         | 2/39 [00:23<05:56,  9.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2013       640  0.003486   0.04285   0.00461     4.076:   8%|▊         | 3/39 [00:23<03:22,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2081       640  0.003448   0.04299  0.004773     4.097:  10%|█         | 4/39 [00:24<02:11,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1852       640  0.003434   0.04237  0.004806     4.049:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1711       640  0.003427    0.0415   0.00476     3.975:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1997       640  0.003422   0.04155  0.004732     3.976:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2084       640  0.003415   0.04189  0.004796     4.008:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2135       640   0.00342   0.04245  0.004864     4.059:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2169       640  0.003432   0.04279   0.00487     4.087:  26%|██▌       | 10/39 [00:28<00:27,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2061       640   0.00342   0.04268  0.004805     4.073:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1868       640  0.003422   0.04253  0.004825     4.062:  31%|███       | 12/39 [00:30<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2072       640  0.003427   0.04238   0.00482      4.05:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2233       640  0.003434   0.04256  0.004782     4.062:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1954       640  0.003425   0.04242  0.004753     4.048:  38%|███▊      | 15/39 [00:31<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2042       640   0.00343   0.04235  0.004761     4.043:  41%|████      | 16/39 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1766       640   0.00343   0.04208  0.004761     4.022:  44%|████▎     | 17/39 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1986       640  0.003433   0.04206   0.00476      4.02:  46%|████▌     | 18/39 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1720       640  0.003429   0.04187  0.004767     4.006:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2386       640  0.003432   0.04199  0.004773     4.016:  51%|█████▏    | 20/39 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2046       640  0.003434   0.04204  0.004756     4.018:  54%|█████▍    | 21/39 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1853       640  0.003435   0.04192  0.004731     4.007:  56%|█████▋    | 22/39 [00:36<00:11,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2251       640  0.003435   0.04197  0.004703     4.008:  59%|█████▉    | 23/39 [00:37<00:10,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2088       640  0.003437   0.04194  0.004695     4.006:  62%|██████▏   | 24/39 [00:37<00:09,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2046       640  0.003432   0.04184  0.004683     3.997:  64%|██████▍   | 25/39 [00:38<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2154       640  0.003431   0.04184  0.004678     3.996:  67%|██████▋   | 26/39 [00:39<00:08,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.553      0.414      0.413      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.14it/s]

                 all        738      14937      0.541      0.412       0.41      0.231
                   0        738       1052      0.525      0.557      0.544      0.256
                   1        738         44      0.454      0.114      0.174     0.0755
                   2        738       8622       0.69      0.729      0.752      0.484
                   3        738        151      0.531      0.424      0.432      0.327
                   4        738        467      0.489      0.582      0.554      0.398
                   5        738         70      0.272       0.41      0.276      0.148
                   6        738         65      0.244     0.0795      0.165     0.0608
                   7        738       1619      0.556      0.619      0.591      0.241
                   8        738       2845      0.654      0.602      0.613      0.321
                   9        738          2          1          0   0.000319   0.000287

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:22:20.367003633 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31177 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round006_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round006_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client1_highway_night_stable_train' images and labels...4895 found, 2918 missing, 0 empty, 0 corrupted: 100%|██████████| 7813/7813 [00:00<00:00, 9665.14it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.319085173501577
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2918 missing, 0 empty, 0 corrupted: 100%|██████████| 7813/7813 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:22:37.384781448 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:22:37.414410417 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1734       640  0.003347   0.03899  0.003629     3.677:   2%|▎         | 1/40 [00:21<14:17, 21.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003414   0.03969  0.004023      3.77:   5%|▌         | 2/40 [00:22<06:04,  9.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2074       640  0.003402   0.04076  0.004223     3.871:   8%|▊         | 3/40 [00:23<03:27,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003392   0.03997  0.004381      3.82:  10%|█         | 4/40 [00:24<02:14,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003386    0.0394   0.00433     3.769:  12%|█▎        | 5/40 [00:25<01:32,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1737       640  0.003387   0.03861  0.004337     3.707:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003393   0.03856  0.004376     3.707:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2000       640  0.003391   0.03865  0.004403     3.716:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2102       640  0.003405   0.03885  0.004442     3.735:  22%|██▎       | 9/40 [00:27<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003407   0.03875  0.004452     3.729:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2041       640  0.003418   0.03881  0.004492     3.738:  28%|██▊       | 11/40 [00:29<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003417   0.03842  0.004504     3.708:  30%|███       | 12/40 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2141       640  0.003418   0.03859  0.004495      3.72:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003407    0.0384  0.004537     3.707:  35%|███▌      | 14/40 [00:31<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1831       640  0.003412   0.03821  0.004564     3.695:  38%|███▊      | 15/40 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003419   0.03819  0.004539     3.692:  40%|████      | 16/40 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1691       640  0.003423   0.03791  0.004566     3.672:  42%|████▎     | 17/40 [00:33<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003414   0.03772   0.00458     3.657:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1619       640  0.003416   0.03738  0.004631     3.634:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640   0.00342   0.03736  0.004635     3.633:  50%|█████     | 20/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1794       640  0.003419   0.03725  0.004685     3.628:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1684       640  0.003422    0.0371  0.004707     3.618:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1990       640  0.003422   0.03701  0.004708     3.612:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1866       640  0.003417   0.03687  0.004701     3.599:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2049       640  0.003423   0.03686  0.004717       3.6:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003421   0.03683  0.004716     3.597:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.564      0.411      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.552      0.412       0.41      0.231
                   0        738       1052      0.583      0.527      0.537      0.258
                   1        738         44      0.522      0.136      0.204     0.0913
                   2        738       8622      0.664      0.731      0.749      0.479
                   3        738        151      0.491       0.43      0.433       0.33
                   4        738        467      0.473      0.587       0.55      0.398
                   5        738         70      0.267      0.414      0.274      0.141
                   6        738         65      0.313     0.0923      0.164     0.0639
                   7        738       1619      0.567      0.613      0.588      0.241
                   8        738       2845      0.638      0.593        0.6      0.313
                   9        738          2          1          0    0.00026   0.000234

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client1_highway_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:24:04.605659251 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31178 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round006_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round006_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 12684.91it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:24:21.693528345 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:24:21.710468204 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003548   0.05123  0.004873     4.772:   3%|▎         | 1/39 [00:21<13:41, 21.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2187       640    0.0035   0.05057   0.00522     4.743:   5%|▌         | 2/39 [00:22<05:48,  9.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1974       640  0.003462   0.04959  0.005225     4.663:   8%|▊         | 3/39 [00:23<03:18,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1957       640  0.003472   0.04863  0.005116     4.578:  10%|█         | 4/39 [00:24<02:08,  3.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2145       640  0.003467   0.04804  0.005024     4.522:  13%|█▎        | 5/39 [00:24<01:27,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1780       640  0.003429   0.04696  0.004979      4.43:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1960       640  0.003438   0.04673  0.005049     4.417:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1897       640  0.003428   0.04635  0.004995     4.382:  21%|██        | 8/39 [00:26<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2025       640  0.003442   0.04637  0.004935      4.38:  23%|██▎       | 9/39 [00:27<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003426    0.0461   0.00492     4.356:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003429   0.04602  0.004917      4.35:  28%|██▊       | 11/39 [00:28<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1792       640  0.003434   0.04555  0.004929     4.313:  31%|███       | 12/39 [00:29<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2094       640  0.003442   0.04542  0.004893     4.301:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2134       640  0.003452   0.04546  0.004861     4.302:  36%|███▌      | 14/39 [00:30<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1930       640  0.003452    0.0453  0.004837     4.287:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1894       640  0.003443   0.04499  0.004829     4.261:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1504       640  0.003434   0.04476  0.004854     4.244:  44%|████▎     | 17/39 [00:32<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1920       640  0.003427   0.04469  0.004841     4.237:  46%|████▌     | 18/39 [00:33<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1718       640  0.003429   0.04441  0.004822     4.213:  49%|████▊     | 19/39 [00:34<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640  0.003423   0.04441   0.00481     4.212:  51%|█████▏    | 20/39 [00:34<00:12,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1849       640  0.003415   0.04424  0.004792     4.196:  54%|█████▍    | 21/39 [00:35<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1707       640  0.003411   0.04416  0.004779     4.188:  56%|█████▋    | 22/39 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1860       640  0.003404   0.04405  0.004779     4.178:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1900       640    0.0034   0.04398  0.004768     4.172:  62%|██████▏   | 24/39 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1848       640  0.003397   0.04387  0.004765     4.163:  64%|██████▍   | 25/39 [00:37<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2050       640  0.003391   0.04384  0.004751     4.158:  67%|██████▋   | 26/39 [00:38<00:08,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.518      0.432      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.34it/s]

                 all        738      14937      0.501      0.435      0.409      0.232
                   0        738       1052      0.571      0.532      0.541      0.256
                   1        738         44      0.399      0.182      0.171     0.0785
                   2        738       8622      0.612      0.752      0.753      0.482
                   3        738        151       0.33      0.457      0.427      0.323
                   4        738        467      0.435      0.623      0.548      0.394
                   5        738         70      0.275      0.429      0.276      0.146
                   6        738         65      0.259      0.123      0.185     0.0718
                   7        738       1619      0.532      0.629      0.585      0.242
                   8        738       2845      0.596      0.624      0.609      0.323
                   9        738          2          1          0   0.000262   0.000236

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:25:45.504392494 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31179 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round006_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round006_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7833 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client3_citystreet_night_stable_train' images and labels...4883 found, 2950 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<00:00, 14117.27it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.280522341095029
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2950 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:26:01.655459450 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:26:01.656555661 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1937       640  0.003523   0.04315  0.004682     4.108:   2%|▎         | 1/40 [00:22<14:21, 22.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1880       640  0.003545   0.04399  0.004734     4.181:   5%|▌         | 2/40 [00:22<06:05,  9.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640    0.0035   0.04406   0.00461     4.174:   8%|▊         | 3/40 [00:23<03:27,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1927       640  0.003487   0.04314  0.004846     4.118:  10%|█         | 4/40 [00:24<02:14,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1822       640  0.003465   0.04243    0.0048     4.056:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1746       640  0.003455   0.04199  0.004696     4.012:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640   0.00345   0.04166  0.004643      3.98:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1891       640  0.003436   0.04135  0.004711      3.96:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003434   0.04127  0.004693     3.952:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003438   0.04102  0.004701     3.932:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003434    0.0408  0.004657     3.911:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1703       640  0.003422   0.04032  0.004633      3.87:  30%|███       | 12/40 [00:29<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003422   0.04019  0.004694     3.864:  32%|███▎      | 13/40 [00:30<00:20,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003412   0.04009  0.004705     3.856:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1827       640    0.0034   0.03988  0.004659     3.835:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003403   0.03983  0.004664     3.832:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1558       640  0.003403   0.03958   0.00467     3.812:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003406   0.03952  0.004679     3.809:  45%|████▌     | 18/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1596       640  0.003403   0.03912  0.004663     3.775:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1927       640  0.003403   0.03907  0.004659      3.77:  50%|█████     | 20/40 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003408   0.03904  0.004673      3.77:  52%|█████▎    | 21/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640  0.003414   0.03896  0.004669     3.764:  55%|█████▌    | 22/40 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003412   0.03891  0.004695     3.761:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640  0.003412   0.03882  0.004703     3.755:  60%|██████    | 24/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003409   0.03867  0.004677     3.741:  62%|██████▎   | 25/40 [00:38<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003406   0.03862   0.00467     3.736:  65%|██████▌   | 26/40 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.567      0.405      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.555      0.408      0.409       0.23
                   0        738       1052      0.606      0.505      0.528      0.252
                   1        738         44      0.548      0.114      0.197     0.0914
                   2        738       8622      0.662      0.728      0.743      0.473
                   3        738        151      0.466       0.43      0.429      0.324
                   4        738        467      0.444      0.599      0.545       0.39
                   5        738         70      0.298      0.429       0.28      0.138
                   6        738         65      0.311     0.0769      0.177     0.0683
                   7        738       1619       0.56      0.608      0.589      0.242
                   8        738       2845      0.653      0.588      0.603      0.318
                   9        738          2          1          0   0.000226   0.000226

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:27:29.431674497 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31180 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round006_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round006_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 10047.16it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:27:45.513285778 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:27:45.633835462 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2084       640  0.003432   0.05003    0.0042     4.613:   3%|▎         | 1/39 [00:23<14:46, 23.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003471   0.04968  0.005008     4.653:   5%|▌         | 2/39 [00:24<06:13, 10.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003413   0.04775  0.004954     4.489:   8%|▊         | 3/39 [00:25<03:32,  5.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003427   0.04688  0.005078     4.431:  10%|█         | 4/39 [00:25<02:16,  3.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003402   0.04569  0.005034      4.33:  13%|█▎        | 5/39 [00:26<01:33,  2.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640   0.00341    0.0444  0.005114     4.234:  15%|█▌        | 6/39 [00:27<01:07,  2.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003424   0.04417  0.005113     4.216:  18%|█▊        | 7/39 [00:27<00:50,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640  0.003433   0.04393  0.005043     4.193:  21%|██        | 8/39 [00:28<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003426   0.04393  0.005099     4.197:  23%|██▎       | 9/39 [00:29<00:32,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003435   0.04395  0.005071     4.197:  26%|██▌       | 10/39 [00:29<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2139       640  0.003435   0.04395   0.00506     4.195:  28%|██▊       | 11/39 [00:30<00:24,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640  0.003434    0.0439  0.005036      4.19:  31%|███       | 12/39 [00:31<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003443   0.04398  0.005017     4.195:  33%|███▎      | 13/39 [00:31<00:19,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003452   0.04393  0.005005     4.191:  36%|███▌      | 14/39 [00:32<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003456   0.04365  0.005003     4.168:  38%|███▊      | 15/39 [00:33<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640  0.003455    0.0434  0.004997     4.148:  41%|████      | 16/39 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640  0.003443    0.0432  0.004966     4.129:  44%|████▎     | 17/39 [00:34<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003439   0.04317  0.004931     4.124:  46%|████▌     | 18/39 [00:35<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1602       640  0.003432   0.04289  0.004923       4.1:  49%|████▊     | 19/39 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2209       640  0.003433   0.04289  0.004909     4.099:  51%|█████▏    | 20/39 [00:36<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003433   0.04286  0.004884     4.094:  54%|█████▍    | 21/39 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003431   0.04286  0.004881     4.094:  56%|█████▋    | 22/39 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640  0.003433   0.04289  0.004906     4.098:  59%|█████▉    | 23/39 [00:38<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640   0.00343    0.0428  0.004897     4.091:  62%|██████▏   | 24/39 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640   0.00343    0.0428  0.004898      4.09:  64%|██████▍   | 25/39 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003429   0.04261  0.004884     4.074:  67%|██████▋   | 26/39 [00:40<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.47      0.474      0.413      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.23it/s]

                 all        738      14937      0.455      0.476      0.411      0.232
                   0        738       1052      0.427      0.587      0.539      0.255
                   1        738         44      0.288       0.25      0.173     0.0718
                   2        738       8622      0.593      0.759      0.752       0.48
                   3        738        151      0.269      0.477      0.441      0.335
                   4        738        467      0.378       0.64      0.554      0.403
                   5        738         70      0.235      0.443      0.282      0.147
                   6        738         65      0.322      0.308      0.174     0.0652
                   7        738       1619      0.483      0.647      0.583      0.242
                   8        738       2845      0.551      0.648      0.611      0.325
                   9        738          2          1          0   0.000271   0.000244

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:29:11.258626361 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31181 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round006_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round006_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client5_residential_night_stable_train' images and labels...4885 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<00:00, 23025.56it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.278118609406953
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round006_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:29:27.481503131 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:29:27.483755787 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1875       640  0.003465   0.04289  0.004799     4.092:   2%|▎         | 1/40 [00:21<14:10, 21.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003487   0.04246  0.004883     4.066:   5%|▌         | 2/40 [00:22<06:01,  9.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1892       640  0.003433   0.04219  0.004738     4.029:   8%|▊         | 3/40 [00:23<03:26,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640   0.00341   0.04245  0.004648     4.041:  10%|█         | 4/40 [00:24<02:14,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2116       640  0.003432   0.04258  0.004631     4.051:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1761       640  0.003427    0.0419  0.004654     3.998:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1953       640  0.003436   0.04158  0.004748     3.981:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003449   0.04149  0.004774     3.977:  20%|██        | 8/40 [00:27<00:40,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640  0.003454   0.04142  0.004721     3.968:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003454    0.0413  0.004755     3.961:  25%|██▌       | 10/40 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640   0.00346   0.04142  0.004823     3.977:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1729       640   0.00345   0.04102  0.004785      3.94:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003442   0.04073  0.004731     3.912:  32%|███▎      | 13/40 [00:30<00:20,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003441   0.04042  0.004778     3.891:  35%|███▌      | 14/40 [00:31<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003441   0.04026  0.004794     3.879:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003438   0.04002  0.004781     3.859:  40%|████      | 16/40 [00:32<00:16,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2102       640  0.003441   0.04009  0.004765     3.863:  42%|████▎     | 17/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003448   0.03998  0.004776     3.857:  45%|████▌     | 18/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003456   0.03969  0.004798     3.836:  48%|████▊     | 19/40 [00:34<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003454   0.03951  0.004803     3.821:  50%|█████     | 20/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003455   0.03928  0.004803     3.803:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003459   0.03912  0.004823     3.792:  55%|█████▌    | 22/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640   0.00346    0.0391  0.004838     3.792:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003458   0.03903  0.004831     3.786:  60%|██████    | 24/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640   0.00346   0.03899  0.004843     3.784:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640  0.003463    0.0388   0.00483     3.767:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.564      0.411      0.411      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.553      0.414       0.41      0.232
                   0        738       1052      0.562      0.531      0.532      0.255
                   1        738         44      0.492      0.136      0.202     0.0962
                   2        738       8622      0.665      0.725      0.744      0.475
                   3        738        151      0.482       0.43      0.427      0.324
                   4        738        467      0.467      0.589      0.551      0.396
                   5        738         70      0.318      0.429      0.279       0.14
                   6        738         65      0.349     0.0769      0.168     0.0682
                   7        738       1619      0.565      0.618      0.592      0.244
                   8        738       2845      0.634      0.602      0.606       0.32
                   9        738          2          1          0   0.000195   0.000195

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:30:52.141417837 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31182 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round006_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round006_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:31:10.591513465 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:31:10.611129027 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640    0.0326   0.03992  0.004407     6.154:   3%|▎         | 1/31 [00:33<16:44, 33.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03322   0.04074  0.004599     6.285:   6%|▋         | 2/31 [00:34<06:53, 14.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03268   0.03963  0.004512     6.145:  10%|▉         | 3/31 [00:35<03:47,  8.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640    0.0321   0.03798  0.004283      5.95:  13%|█▎        | 4/31 [00:35<02:21,  5.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03213   0.03818  0.004327     5.971:  16%|█▌        | 5/31 [00:36<01:32,  3.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03232   0.03819  0.004387     5.992:  19%|█▉        | 6/31 [00:37<01:03,  2.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03244   0.03797  0.004454     5.989:  23%|██▎       | 7/31 [00:37<00:45,  1.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03239   0.03806  0.004474     5.994:  26%|██▌       | 8/31 [00:38<00:34,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03245     0.038  0.004376     5.986:  29%|██▉       | 9/31 [00:38<00:26,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03244   0.03813  0.004353     5.993:  32%|███▏      | 10/31 [00:39<00:21,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03241   0.03818  0.004379     5.997:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03232   0.03791  0.004376     5.969:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0323   0.03795  0.004325     5.966:  42%|████▏     | 13/31 [00:41<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03232    0.0378  0.004289     5.953:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03235   0.03774  0.004334     5.954:  48%|████▊     | 15/31 [00:42<00:10,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03235   0.03764  0.004329     5.946:  52%|█████▏    | 16/31 [00:42<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640    0.0324    0.0377  0.004301     5.952:  55%|█████▍    | 17/31 [00:43<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03245   0.03777  0.004266     5.959:  58%|█████▊    | 18/31 [00:44<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640    0.0324   0.03766  0.004236     5.944:  61%|██████▏   | 19/31 [00:44<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640    0.0324    0.0379  0.004237     5.963:  65%|██████▍   | 20/31 [00:45<00:06,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03244   0.03795  0.004257     5.972:  68%|██████▊   | 21/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03245   0.03807  0.004229      5.98:  71%|███████   | 22/31 [00:46<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03245   0.03813  0.004212     5.983:  74%|███████▍  | 23/31 [00:47<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03247   0.03823  0.004201     5.992:  77%|███████▋  | 24/31 [00:47<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03249   0.03821  0.004214     5.993:  81%|████████  | 25/31 [00:48<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03255   0.03827  0.004221     6.003:  84%|████████▍ | 26/31 [00:48<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.484      0.467      0.412      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.469      0.468       0.41      0.232
                   0        738       1052      0.458      0.587      0.544       0.26
                   1        738         44      0.322       0.25       0.16     0.0714
                   2        738       8622      0.592      0.763      0.754      0.488
                   3        738        151      0.301       0.45      0.434      0.327
                   4        738        467      0.428      0.615      0.553      0.398
                   5        738         70      0.227      0.457      0.283      0.145
                   6        738         65      0.285      0.277      0.174     0.0639
                   7        738       1619      0.517      0.637      0.586      0.245
                   8        738       2845      0.558      0.644      0.612      0.324
                   9        738          2          1          0   0.000348   0.000348

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round006_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 15:32:50.310648327 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round007 phase_round=7 ===

02 head-to-full DQA:  19%|█▉        | 6/32 [1:25:31<6:09:52, 853.56s/round, elapsed=1h25m31s, eta=6h10m36s, phase=phase1_head, round=6]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round007 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round007 client0_highway_day: pseudo scan 250/1500 images, kept 2372 boxes
round007 client0_highway_day: pseudo scan 500/1500 images, kept 4819 boxes
round007 client0_highway_day: pseudo scan 750/1500 images, kept 7175 boxes
round007 client0_highway_day: pseudo scan 1000/1500 images, kept 9571 boxes
round007 client0_highway_day: pseudo scan 1250/1500 images, kept 11904 boxes
round007 client0_highway_day: pseudo scan 1500/1500 images, kept 14288 boxes
{
  "round": "round007",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round006_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11207,
  "boxes_per_kept_image": 7.506363027461487,
  "mean_conf": 0.8010801953673522,
  "mean_stability": 0.9537662616739352,
  "mean_score": 0.7673339517091244,
  "class_counts": {
    "0": 158,
    "2": 6430,
    "3": 113,
    "4": 545,
    "5": 7,
    "7": 555,
    "8": 3399
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_client0_highway_day_stable_boxes.csv"
}
round007 client1_highway_night: pseudo scan 1/1500 images, kept 4 boxes
round007 client1_highway_night: pseudo scan 250/1500 images, kept 1676 boxes
round007 client1_highway_night: pseudo scan 500/1500 images, kept 3479 boxes
round007 client1_highway_night: pseudo scan 750/1500 images, kept 5268 boxes
round007 client1_highway_night: pseudo scan 1000/1500 images, kept 6950 boxes
round007 client1_highway_night: pseudo scan 1250/1500 images, kept 8709 boxes
round007 client1_highway_night: pseudo scan 1500/1500 images, kept 10408 boxes
{
  "round": "round007",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round006_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1463,
  "pseudo_boxes_kept": 8484,
  "boxes_per_kept_image": 5.7990430622009566,
  "mean_conf": 0.7124264163159638,
  "mean_stability": 0.9380333558504788,
  "mean_score": 0.6724043553032538,
  "class_counts": {
    "0": 64,
    "2": 4684,
    "3": 29,
    "4": 137,
    "5": 7,
    "7": 551,
    "8": 3012
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_client1_highway_night_stable_boxes.csv"
}
round007 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round007 client2_citystreet_day: pseudo scan 250/1500 images, kept 2699 boxes
round007 client2_citystreet_day: pseudo scan 500/1500 images, kept 5425 boxes
round007 client2_citystreet_day: pseudo scan 750/1500 images, kept 8177 boxes
round007 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10940 boxes
round007 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13666 boxes
round007 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16324 boxes
{
  "round": "round007",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round006_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13749,
  "boxes_per_kept_image": 9.190508021390375,
  "mean_conf": 0.7992910093628751,
  "mean_stability": 0.9517446371830804,
  "mean_score": 0.7642296697725177,
  "class_counts": {
    "0": 1467,
    "2": 7346,
    "3": 191,
    "4": 595,
    "5": 66,
    "7": 1519,
    "8": 2565
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_client2_citystreet_day_stable_boxes.csv"
}
round007 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round007 client3_citystreet_night: pseudo scan 250/1500 images, kept 2396 boxes
round007 client3_citystreet_night: pseudo scan 500/1500 images, kept 4761 boxes
round007 client3_citystreet_night: pseudo scan 750/1500 images, kept 7080 boxes
round007 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9337 boxes
round007 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11763 boxes
round007 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14115 boxes
{
  "round": "round007",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round006_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1474,
  "pseudo_boxes_kept": 11812,
  "boxes_per_kept_image": 8.013568521031207,
  "mean_conf": 0.7106371211311271,
  "mean_stability": 0.9351870363803383,
  "mean_score": 0.6689963357733141,
  "class_counts": {
    "0": 549,
    "2": 6352,
    "3": 67,
    "4": 156,
    "5": 35,
    "7": 1939,
    "8": 2714
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_client3_citystreet_night_stable_boxes.csv"
}
round007 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round007 client4_residential_day: pseudo scan 250/1500 images, kept 2592 boxes
round007 client4_residential_day: pseudo scan 500/1500 images, kept 5205 boxes
round007 client4_residential_day: pseudo scan 750/1500 images, kept 7759 boxes
round007 client4_residential_day: pseudo scan 1000/1500 images, kept 10240 boxes
round007 client4_residential_day: pseudo scan 1250/1500 images, kept 12763 boxes
round007 client4_residential_day: pseudo scan 1500/1500 images, kept 15239 boxes
{
  "round": "round007",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round006_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9941,
  "boxes_per_kept_image": 6.671812080536912,
  "mean_conf": 0.8360719418797907,
  "mean_stability": 0.9600883763736552,
  "mean_score": 0.8061622714864501,
  "class_counts": {
    "0": 382,
    "2": 6858,
    "3": 60,
    "4": 304,
    "5": 49,
    "7": 535,
    "8": 1753
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_client4_residential_day_stable_boxes.csv"
}
round007 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round007 client5_residential_night: pseudo scan 250/1500 images, kept 2354 boxes
round007 client5_residential_night: pseudo scan 500/1500 images, kept 4684 boxes
round007 client5_residential_night: pseudo scan 750/1500 images, kept 7003 boxes
round007 client5_residential_night: pseudo scan 1000/1500 images, kept 9407 boxes
round007 client5_residential_night: pseudo scan 1250/1500 images, kept 11795 boxes
round007 client5_residential_night: pseudo scan 1500/1500 images, kept 14199 boxes
{
  "round": "round007",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round006_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1479,
  "pseudo_boxes_kept": 8778,
  "boxes_per_kept_image": 5.935091277890466,
  "mean_conf": 0.787724584541361,
  "mean_stability": 0.949414439714968,
  "mean_score": 0.7508025247940179,
  "class_counts": {
    "0": 131,
    "2": 6390,
    "3": 31,
    "4": 95,
    "5": 23,
    "7": 630,
    "8": 1478
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round007_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31183 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round007_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round007_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 22205.75it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:35:04.032474476 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:35:04.083832098 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2068       640  0.003441   0.04171  0.004717     3.989:   3%|▎         | 1/39 [00:22<14:09, 22.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003447   0.04209  0.004448     3.999:   5%|▌         | 2/39 [00:23<06:00,  9.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003481   0.04288  0.004566     4.074:   8%|▊         | 3/39 [00:24<03:24,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003443     0.043  0.004735     4.094:  10%|█         | 4/39 [00:24<02:12,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003429   0.04239  0.004766     4.047:  13%|█▎        | 5/39 [00:25<01:30,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003422   0.04151  0.004719     3.972:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003417   0.04156  0.004693     3.974:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640   0.00341    0.0419  0.004757     4.005:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003416   0.04246  0.004824     4.056:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003427   0.04279  0.004829     4.083:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003416   0.04268  0.004764     4.069:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003418   0.04251  0.004781     4.057:  31%|███       | 12/39 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003422   0.04236  0.004775     4.045:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003429   0.04255  0.004737     4.057:  36%|███▌      | 14/39 [00:31<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640   0.00342    0.0424  0.004709     4.042:  38%|███▊      | 15/39 [00:32<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003426   0.04233  0.004719     4.038:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003425   0.04206  0.004718     4.016:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003428   0.04203  0.004717     4.014:  46%|████▌     | 18/39 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003424   0.04185  0.004724         4:  49%|████▊     | 19/39 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003428   0.04197   0.00473      4.01:  51%|█████▏    | 20/39 [00:35<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003429   0.04201  0.004712     4.012:  54%|█████▍    | 21/39 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640   0.00343    0.0419  0.004687     4.001:  56%|█████▋    | 22/39 [00:36<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003431   0.04194  0.004659     4.002:  59%|█████▉    | 23/39 [00:37<00:10,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003432   0.04191  0.004651     3.999:  62%|██████▏   | 24/39 [00:38<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003428   0.04181  0.004639      3.99:  64%|██████▍   | 25/39 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640  0.003427   0.04181  0.004633     3.989:  67%|██████▋   | 26/39 [00:39<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.553      0.416      0.413      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.533      0.419       0.41      0.232
                   0        738       1052      0.511      0.561      0.543      0.257
                   1        738         44      0.461      0.136      0.189     0.0823
                   2        738       8622      0.682      0.734      0.753      0.484
                   3        738        151      0.488      0.437      0.432      0.328
                   4        738        467      0.477      0.585       0.55      0.396
                   5        738         70      0.268      0.414      0.277      0.147
                   6        738         65      0.253     0.0923      0.158     0.0611
                   7        738       1619      0.547      0.624      0.589      0.242
                   8        738       2845      0.646      0.605      0.613      0.321
                   9        738          2          1          0   0.000323   0.000323

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:36:28.221547261 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31184 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round007_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round007_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client1_highway_night_stable_train' images and labels...4895 found, 2912 missing, 0 empty, 0 corrupted: 100%|██████████| 7807/7807 [00:00<00:00, 16554.81it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.32633738362001
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2912 missing, 0 empty, 0 corrupted: 100%|██████████| 7807/7807 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:36:45.771572262 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:36:45.796664405 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2061       640  0.003454   0.04245  0.004363     4.021:   2%|▎         | 1/40 [00:22<14:20, 22.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640  0.003472   0.04158  0.004612     3.973:   5%|▌         | 2/40 [00:23<06:07,  9.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640   0.00343   0.04189  0.004713     4.002:   8%|▊         | 3/40 [00:23<03:29,  5.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003414   0.04091  0.004806     3.931:  10%|█         | 4/40 [00:24<02:16,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1789       640  0.003377   0.04042   0.00476     3.885:  12%|█▎        | 5/40 [00:25<01:33,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003404   0.04042  0.004746     3.885:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2096       640  0.003399   0.04052  0.004675     3.887:  18%|█▊        | 7/40 [00:26<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640   0.00341   0.04041  0.004782     3.888:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003415   0.04018   0.00478      3.87:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003425    0.0399    0.0047     3.842:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2066       640  0.003433   0.03977  0.004701     3.832:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1885       640  0.003425   0.03935    0.0047     3.798:  30%|███       | 12/40 [00:30<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2179       640  0.003423   0.03941  0.004719     3.805:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640  0.003426   0.03934  0.004774     3.803:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1827       640  0.003421   0.03911  0.004782     3.785:  38%|███▊      | 15/40 [00:31<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003423   0.03888  0.004733     3.763:  40%|████      | 16/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003428   0.03877   0.00473     3.754:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003436   0.03863  0.004726     3.743:  45%|████▌     | 18/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1574       640  0.003436   0.03818  0.004731     3.708:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2203       640  0.003441   0.03816  0.004739     3.707:  50%|█████     | 20/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1892       640  0.003436   0.03804   0.00476     3.699:  52%|█████▎    | 21/40 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003437   0.03803  0.004758     3.698:  55%|█████▌    | 22/40 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2045       640   0.00344   0.03806  0.004789     3.703:  57%|█████▊    | 23/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640   0.00344   0.03797  0.004794     3.696:  60%|██████    | 24/40 [00:37<00:11,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1931       640  0.003443    0.0379  0.004808     3.692:  62%|██████▎   | 25/40 [00:38<00:10,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1944       640  0.003445   0.03784  0.004796     3.687:  65%|██████▌   | 26/40 [00:39<00:09,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.556      0.414      0.413      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.544      0.416       0.41      0.232
                   0        738       1052      0.555      0.528      0.533      0.255
                   1        738         44      0.541      0.134      0.203     0.0894
                   2        738       8622      0.656      0.737      0.751       0.48
                   3        738        151      0.442       0.43      0.434      0.334
                   4        738        467      0.452      0.597      0.545      0.394
                   5        738         70      0.289      0.414      0.276      0.141
                   6        738         65      0.321     0.0923       0.17     0.0671
                   7        738       1619      0.553      0.623      0.587      0.243
                   8        738       2845       0.63      0.601      0.602      0.312
                   9        738          2          1          0   0.000254   0.000229

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client1_highway_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:38:12.021227940 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31185 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round007_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round007_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 11149.79it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:38:29.681530440 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:38:29.726523662 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003541   0.05134    0.0048     4.774:   3%|▎         | 1/39 [00:21<13:40, 21.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003494   0.05065  0.005158     4.744:   5%|▌         | 2/39 [00:22<05:48,  9.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003457   0.04967  0.005167     4.663:   8%|▊         | 3/39 [00:23<03:18,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003467   0.04868  0.005062     4.577:  10%|█         | 4/39 [00:24<02:08,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003462   0.04808  0.004976     4.521:  13%|█▎        | 5/39 [00:24<01:28,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003424     0.047  0.004932     4.428:  15%|█▌        | 6/39 [00:25<01:03,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003434   0.04675  0.005002     4.415:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003423   0.04637   0.00495      4.38:  21%|██        | 8/39 [00:26<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003438   0.04638  0.004887     4.376:  23%|██▎       | 9/39 [00:27<00:31,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003422   0.04611  0.004874     4.352:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003425   0.04602  0.004871     4.346:  28%|██▊       | 11/39 [00:28<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640   0.00343   0.04555  0.004882     4.309:  31%|███       | 12/39 [00:29<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003437   0.04541  0.004847     4.296:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003447   0.04544  0.004815     4.296:  36%|███▌      | 14/39 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003448   0.04528   0.00479     4.281:  38%|███▊      | 15/39 [00:31<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003439   0.04496  0.004781     4.255:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640   0.00343   0.04474  0.004806     4.238:  44%|████▎     | 17/39 [00:32<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003422   0.04466  0.004794      4.23:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003424   0.04439  0.004775     4.207:  49%|████▊     | 19/39 [00:33<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003419   0.04438  0.004764     4.205:  51%|█████▏    | 20/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003411   0.04421  0.004746      4.19:  54%|█████▍    | 21/39 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003406   0.04413  0.004733     4.182:  56%|█████▋    | 22/39 [00:35<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003399   0.04402  0.004733     4.172:  59%|█████▉    | 23/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003396   0.04395  0.004722     4.166:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003392   0.04384   0.00472     4.157:  64%|██████▍   | 25/39 [00:37<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003387   0.04381  0.004705     4.152:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.518      0.432      0.412      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.526      0.418       0.41      0.232
                   0        738       1052      0.621       0.52       0.54      0.255
                   1        738         44      0.351      0.111      0.178     0.0819
                   2        738       8622      0.645      0.743      0.753      0.482
                   3        738        151      0.373       0.45       0.43      0.327
                   4        738        467      0.454      0.608      0.548      0.392
                   5        738         70      0.323      0.429      0.275      0.144
                   6        738         65      0.316     0.0923      0.182     0.0729
                   7        738       1619      0.557      0.616      0.586      0.242
                   8        738       2845      0.623       0.61      0.608      0.323
                   9        738          2          1          0   0.000264   0.000237

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:39:55.515541784 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31186 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round007_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round007_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7829 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client3_citystreet_night_stable_train' images and labels...4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<00:00, 16537.61it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:40:11.187556327 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:40:12.308068718 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1869       640    0.0035   0.04329  0.004519     4.105:   2%|▎         | 1/40 [00:22<14:20, 22.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003486   0.04323  0.005016     4.139:   5%|▌         | 2/40 [00:22<06:05,  9.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1962       640  0.003443   0.04334  0.004961      4.14:   8%|▊         | 3/40 [00:23<03:27,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1939       640  0.003423   0.04302  0.004861     4.105:  10%|█         | 4/40 [00:24<02:14,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1858       640  0.003401   0.04217  0.004783     4.029:  12%|█▎        | 5/40 [00:25<01:32,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1818       640  0.003412   0.04183  0.004768     4.001:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003418    0.0415  0.004735     3.972:  18%|█▊        | 7/40 [00:26<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003424   0.04137  0.004732     3.962:  20%|██        | 8/40 [00:27<00:41,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1917       640  0.003419   0.04121  0.004685     3.945:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1946       640  0.003432   0.04108  0.004659     3.934:  25%|██▌       | 10/40 [00:28<00:29,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003423   0.04084  0.004598     3.909:  28%|██▊       | 11/40 [00:29<00:25,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1625       640  0.003414   0.04048  0.004647     3.883:  30%|███       | 12/40 [00:30<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003413   0.04028  0.004633     3.866:  32%|███▎      | 13/40 [00:30<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2012       640  0.003415   0.04036  0.004642     3.873:  35%|███▌      | 14/40 [00:31<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1809       640  0.003412   0.04024  0.004686     3.867:  38%|███▊      | 15/40 [00:32<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003403   0.03993  0.004638     3.837:  40%|████      | 16/40 [00:32<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1651       640  0.003407   0.03961  0.004641     3.813:  42%|████▎     | 17/40 [00:33<00:15,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1908       640  0.003411   0.03941  0.004644     3.797:  45%|████▌     | 18/40 [00:34<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1756       640  0.003411    0.0391  0.004627     3.771:  48%|████▊     | 19/40 [00:34<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2277       640  0.003412   0.03915  0.004597     3.773:  50%|█████     | 20/40 [00:35<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1926       640  0.003419   0.03909  0.004609      3.77:  52%|█████▎    | 21/40 [00:36<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1760       640  0.003417   0.03889  0.004572      3.75:  55%|█████▌    | 22/40 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2155       640  0.003419   0.03889  0.004583     3.751:  57%|█████▊    | 23/40 [00:37<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1883       640  0.003418   0.03877  0.004597     3.742:  60%|██████    | 24/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640  0.003419   0.03869  0.004582     3.735:  62%|██████▎   | 25/40 [00:38<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003415   0.03858  0.004582     3.726:  65%|██████▌   | 26/40 [00:39<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.563      0.408      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]

                 all        738      14937      0.551       0.41      0.409       0.23
                   0        738       1052      0.595      0.506      0.528      0.251
                   1        738         44      0.549      0.111      0.201     0.0902
                   2        738       8622      0.654       0.73      0.744      0.474
                   3        738        151      0.434      0.437      0.432      0.326
                   4        738        467      0.444        0.6      0.544      0.388
                   5        738         70       0.33      0.414      0.275      0.144
                   6        738         65      0.333     0.0769      0.176       0.07
                   7        738       1619      0.541      0.619      0.586      0.242
                   8        738       2845      0.629      0.604      0.601      0.317
                   9        738          2          1          0   0.000214   0.000193

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:41:37.167157450 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31187 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round007_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round007_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 23323.94it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:41:53.211255302 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:41:53.226952199 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2210       640  0.003458   0.05168  0.004866     4.801:   3%|▎         | 1/39 [00:21<13:27, 21.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003421   0.05044   0.00528     4.731:   5%|▌         | 2/39 [00:22<05:43,  9.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1757       640  0.003359   0.04843  0.005163     4.556:   8%|▊         | 3/39 [00:23<03:16,  5.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003357   0.04792  0.005102      4.51:  10%|█         | 4/39 [00:23<02:07,  3.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2152       640   0.00336   0.04701  0.005071     4.435:  13%|█▎        | 5/39 [00:24<01:27,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1679       640  0.003351   0.04546  0.005148     4.317:  15%|█▌        | 6/39 [00:25<01:03,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003372   0.04518  0.005133     4.295:  18%|█▊        | 7/39 [00:25<00:47,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640   0.00338   0.04494   0.00501     4.267:  21%|██        | 8/39 [00:26<00:38,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2197       640  0.003379    0.0451  0.004958     4.275:  23%|██▎       | 9/39 [00:27<00:31,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003384   0.04507  0.004934     4.271:  26%|██▌       | 10/39 [00:27<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2162       640  0.003394   0.04503  0.004915     4.267:  28%|██▊       | 11/39 [00:28<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2149       640  0.003411   0.04498  0.004967     4.269:  31%|███       | 12/39 [00:29<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2024       640  0.003417   0.04496  0.004964     4.268:  33%|███▎      | 13/39 [00:29<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003422   0.04477  0.004964     4.252:  36%|███▌      | 14/39 [00:30<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003429   0.04447  0.004983     4.231:  38%|███▊      | 15/39 [00:30<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003423   0.04415  0.004975     4.204:  41%|████      | 16/39 [00:31<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003422   0.04405  0.004941     4.193:  44%|████▎     | 17/39 [00:32<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003418   0.04402  0.004898     4.187:  46%|████▌     | 18/39 [00:32<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1723       640   0.00342   0.04379  0.004896     4.168:  49%|████▊     | 19/39 [00:33<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640   0.00341   0.04376  0.004872     4.164:  51%|█████▏    | 20/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1821       640  0.003405   0.04364  0.004841     4.151:  54%|█████▍    | 21/39 [00:34<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1987       640  0.003402   0.04362  0.004857      4.15:  56%|█████▋    | 22/39 [00:35<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1940       640  0.003402    0.0436   0.00487      4.15:  59%|█████▉    | 23/39 [00:35<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003396   0.04347  0.004863     4.138:  62%|██████▏   | 24/39 [00:36<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1905       640  0.003399   0.04337  0.004854      4.13:  64%|██████▍   | 25/39 [00:37<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003398   0.04323   0.00483     4.117:  67%|██████▋   | 26/39 [00:37<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.472       0.47      0.412      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.477      0.451       0.41      0.232
                   0        738       1052      0.466      0.571       0.54      0.257
                   1        738         44      0.401       0.25      0.171     0.0766
                   2        738       8622      0.627      0.748      0.751       0.48
                   3        738        151      0.311      0.457      0.438      0.334
                   4        738        467      0.413      0.625       0.55      0.397
                   5        738         70       0.25      0.443      0.282      0.146
                   6        738         65      0.208      0.138      0.168     0.0646
                   7        738       1619      0.505      0.641      0.587      0.243
                   8        738       2845      0.586      0.634      0.611      0.325
                   9        738          2          1          0   0.000263   0.000237

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:43:19.854655312 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31188 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round007_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round007_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client5_residential_night_stable_train' images and labels...4885 found, 2954 missing, 0 empty, 0 corrupted: 100%|██████████| 7839/7839 [00:00<00:00, 12789.18it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.275715633847122
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round007_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2954 missing, 0 empty, 0 corrupted: 100%|██████████| 7839/7839 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:43:36.524368676 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:43:36.525257442 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1877       640  0.003521   0.04339  0.004998     4.153:   2%|▎         | 1/40 [00:21<14:10, 21.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003535   0.04294  0.005067     4.123:   5%|▌         | 2/40 [00:22<06:01,  9.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2137       640  0.003491   0.04379  0.004749     4.162:   8%|▊         | 3/40 [00:23<03:24,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2278       640  0.003488    0.0439  0.004696     4.167:  10%|█         | 4/40 [00:24<02:12,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003463   0.04336  0.004737     4.125:  12%|█▎        | 5/40 [00:24<01:30,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1709       640  0.003455   0.04243  0.004804     4.055:  15%|█▌        | 6/40 [00:25<01:05,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1788       640  0.003441   0.04186  0.004872     4.014:  18%|█▊        | 7/40 [00:26<00:49,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2099       640   0.00344   0.04191  0.004834     4.015:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003441   0.04169   0.00475      3.99:  22%|██▎       | 9/40 [00:27<00:32,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003436   0.04139  0.004772     3.968:  25%|██▌       | 10/40 [00:28<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003446   0.04128  0.004868     3.967:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1758       640  0.003432   0.04086  0.004804     3.928:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1791       640  0.003417   0.04039  0.004793     3.888:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640   0.00342   0.04033  0.004839     3.887:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1786       640  0.003424   0.04002  0.004853     3.864:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003423   0.03979  0.004871     3.847:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1990       640  0.003428   0.03965   0.00489     3.838:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2096       640  0.003432    0.0395  0.004895     3.826:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1750       640   0.00344   0.03917  0.004904     3.801:  48%|████▊     | 19/40 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003438   0.03899  0.004927     3.788:  50%|█████     | 20/40 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2202       640   0.00344   0.03889  0.004926      3.78:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003445   0.03876  0.004926      3.77:  55%|█████▌    | 22/40 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003443    0.0387  0.004918     3.765:  57%|█████▊    | 23/40 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640   0.00344   0.03859  0.004902     3.755:  60%|██████    | 24/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003441    0.0384  0.004919     3.741:  62%|██████▎   | 25/40 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1672       640   0.00344   0.03818  0.004919     3.723:  65%|██████▌   | 26/40 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.554      0.412       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.537      0.415      0.408      0.231
                   0        738       1052      0.575      0.525       0.53      0.254
                   1        738         44      0.489      0.131      0.201     0.0945
                   2        738       8622      0.662      0.728      0.746      0.477
                   3        738        151      0.457       0.43      0.427      0.326
                   4        738        467      0.455      0.591      0.545      0.391
                   5        738         70      0.308      0.429       0.27      0.138
                   6        738         65      0.246     0.0769      0.167     0.0643
                   7        738       1619      0.552      0.623      0.588      0.244
                   8        738       2845      0.622      0.612      0.606      0.321
                   9        738          2          1          0   0.000181   0.000163

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:45:02.870375975 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31189 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round007_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round007_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:45:18.054135264 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:45:18.155825278 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03225   0.03927  0.004296     6.065:   3%|▎         | 1/31 [00:32<16:23, 32.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03287   0.04006  0.004486     6.194:   6%|▋         | 2/31 [00:33<06:49, 14.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03233   0.03895    0.0044     6.054:  10%|▉         | 3/31 [00:34<03:44,  8.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03176   0.03733  0.004172     5.861:  13%|█▎        | 4/31 [00:35<02:19,  5.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03178   0.03753  0.004216     5.882:  16%|█▌        | 5/31 [00:35<01:31,  3.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03197   0.03753  0.004272     5.902:  19%|█▉        | 6/31 [00:36<01:02,  2.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03208   0.03731  0.004335     5.899:  23%|██▎       | 7/31 [00:37<00:45,  1.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03203   0.03741  0.004352     5.903:  26%|██▌       | 8/31 [00:37<00:33,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03209   0.03734  0.004255     5.895:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03209   0.03747   0.00423     5.903:  32%|███▏      | 10/31 [00:38<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03206   0.03752  0.004256     5.907:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03198   0.03726  0.004254      5.88:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03196   0.03729  0.004202     5.876:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03198   0.03716  0.004166     5.864:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03201    0.0371  0.004213     5.866:  48%|████▊     | 15/31 [00:41<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03201     0.037  0.004208     5.858:  52%|█████▏    | 16/31 [00:42<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03206   0.03706  0.004182     5.864:  55%|█████▍    | 17/31 [00:43<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03212   0.03714   0.00415     5.873:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03207   0.03703   0.00412     5.858:  61%|██████▏   | 19/31 [00:44<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03208   0.03727   0.00412     5.877:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03212   0.03733   0.00414     5.887:  68%|██████▊   | 21/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03213   0.03745  0.004113     5.896:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03213   0.03751  0.004094     5.899:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03216   0.03762  0.004083     5.909:  77%|███████▋  | 24/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03218    0.0376  0.004098      5.91:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03224   0.03766  0.004106     5.921:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.479      0.468      0.411      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.561      0.401      0.408      0.232
                   0        738       1052      0.591      0.533      0.544      0.259
                   1        738         44      0.488     0.0909      0.162      0.072
                   2        738       8622        0.7      0.726      0.755      0.488
                   3        738        151      0.513      0.424      0.435      0.326
                   4        738        467      0.505      0.572      0.551      0.397
                   5        738         70       0.28      0.417      0.279      0.142
                   6        738         65      0.285     0.0615      0.163     0.0653
                   7        738       1619      0.597      0.587      0.586      0.244
                   8        738       2845       0.65      0.598      0.609      0.323
                   9        738          2          1          0   0.000351   0.000351

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round007_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 15:46:57.890734502 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round008 phase_round=8 ===

02 head-to-full DQA:  22%|██▏       | 7/32 [1:39:39<5:54:51, 851.67s/round, elapsed=1h39m39s, eta=5h55m54s, phase=phase1_head, round=7]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round008 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round008 client0_highway_day: pseudo scan 250/1500 images, kept 2372 boxes
round008 client0_highway_day: pseudo scan 500/1500 images, kept 4827 boxes
round008 client0_highway_day: pseudo scan 750/1500 images, kept 7184 boxes
round008 client0_highway_day: pseudo scan 1000/1500 images, kept 9587 boxes
round008 client0_highway_day: pseudo scan 1250/1500 images, kept 11920 boxes
round008 client0_highway_day: pseudo scan 1500/1500 images, kept 14308 boxes
{
  "round": "round008",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round007_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11224,
  "boxes_per_kept_image": 7.517749497655727,
  "mean_conf": 0.804025136245015,
  "mean_stability": 0.9534111257459297,
  "mean_score": 0.7698238206526195,
  "class_counts": {
    "0": 158,
    "2": 6439,
    "3": 113,
    "4": 555,
    "5": 7,
    "7": 552,
    "8": 3400
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_client0_highway_day_stable_boxes.csv"
}
round008 client1_highway_night: pseudo scan 1/1500 images, kept 4 boxes
round008 client1_highway_night: pseudo scan 250/1500 images, kept 1678 boxes
round008 client1_highway_night: pseudo scan 500/1500 images, kept 3474 boxes
round008 client1_highway_night: pseudo scan 750/1500 images, kept 5272 boxes
round008 client1_highway_night: pseudo scan 1000/1500 images, kept 6963 boxes
round008 client1_highway_night: pseudo scan 1250/1500 images, kept 8733 boxes
round008 client1_highway_night: pseudo scan 1500/1500 images, kept 10420 boxes
{
  "round": "round008",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round007_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1464,
  "pseudo_boxes_kept": 8492,
  "boxes_per_kept_image": 5.800546448087432,
  "mean_conf": 0.7149898237142988,
  "mean_stability": 0.9375841178761526,
  "mean_score": 0.6744881080857866,
  "class_counts": {
    "0": 66,
    "2": 4689,
    "3": 29,
    "4": 139,
    "5": 8,
    "7": 556,
    "8": 3005
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_client1_highway_night_stable_boxes.csv"
}
round008 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round008 client2_citystreet_day: pseudo scan 250/1500 images, kept 2705 boxes
round008 client2_citystreet_day: pseudo scan 500/1500 images, kept 5439 boxes
round008 client2_citystreet_day: pseudo scan 750/1500 images, kept 8196 boxes
round008 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10960 boxes
round008 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13691 boxes
round008 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16358 boxes
{
  "round": "round008",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round007_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13768,
  "boxes_per_kept_image": 9.203208556149733,
  "mean_conf": 0.8024435811121404,
  "mean_stability": 0.9513368486388349,
  "mean_score": 0.7668716619169808,
  "class_counts": {
    "0": 1458,
    "2": 7362,
    "3": 191,
    "4": 605,
    "5": 70,
    "7": 1519,
    "8": 2563
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_client2_citystreet_day_stable_boxes.csv"
}
round008 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round008 client3_citystreet_night: pseudo scan 250/1500 images, kept 2397 boxes
round008 client3_citystreet_night: pseudo scan 500/1500 images, kept 4755 boxes
round008 client3_citystreet_night: pseudo scan 750/1500 images, kept 7083 boxes
round008 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9335 boxes
round008 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11766 boxes
round008 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14126 boxes
{
  "round": "round008",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round007_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1477,
  "pseudo_boxes_kept": 11843,
  "boxes_per_kept_image": 8.018280297901152,
  "mean_conf": 0.7127239580599529,
  "mean_stability": 0.9348173456841059,
  "mean_score": 0.6706387606955844,
  "class_counts": {
    "0": 541,
    "2": 6357,
    "3": 71,
    "4": 156,
    "5": 36,
    "7": 1966,
    "8": 2716
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_client3_citystreet_night_stable_boxes.csv"
}
round008 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round008 client4_residential_day: pseudo scan 250/1500 images, kept 2586 boxes
round008 client4_residential_day: pseudo scan 500/1500 images, kept 5197 boxes
round008 client4_residential_day: pseudo scan 750/1500 images, kept 7753 boxes
round008 client4_residential_day: pseudo scan 1000/1500 images, kept 10235 boxes
round008 client4_residential_day: pseudo scan 1250/1500 images, kept 12766 boxes
round008 client4_residential_day: pseudo scan 1500/1500 images, kept 15249 boxes
{
  "round": "round008",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round007_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9962,
  "boxes_per_kept_image": 6.685906040268456,
  "mean_conf": 0.8382905537531429,
  "mean_stability": 0.9597293386627359,
  "mean_score": 0.8079440363372584,
  "class_counts": {
    "0": 385,
    "2": 6863,
    "3": 64,
    "4": 305,
    "5": 48,
    "7": 536,
    "8": 1761
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_client4_residential_day_stable_boxes.csv"
}
round008 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round008 client5_residential_night: pseudo scan 250/1500 images, kept 2353 boxes
round008 client5_residential_night: pseudo scan 500/1500 images, kept 4685 boxes
round008 client5_residential_night: pseudo scan 750/1500 images, kept 7009 boxes
round008 client5_residential_night: pseudo scan 1000/1500 images, kept 9400 boxes
round008 client5_residential_night: pseudo scan 1250/1500 images, kept 11784 boxes
round008 client5_residential_night: pseudo scan 1500/1500 images, kept 14178 boxes
{
  "round": "round008",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round007_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 8794,
  "boxes_per_kept_image": 5.937879810938555,
  "mean_conf": 0.7882893533260139,
  "mean_stability": 0.9487694163864137,
  "mean_score": 0.7508214716631816,
  "class_counts": {
    "0": 131,
    "2": 6381,
    "3": 33,
    "4": 97,
    "5": 24,
    "7": 654,
    "8": 1474
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round008_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31190 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round008_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round008_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7867 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 25745.00it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:49:14.498806848 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:49:14.516455901 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2068       640  0.003438   0.04184  0.004669     3.996:   3%|▎         | 1/39 [00:22<14:02, 22.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003444   0.04218  0.004403     4.002:   5%|▌         | 2/39 [00:23<05:56,  9.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003477   0.04296  0.004524     4.077:   8%|▊         | 3/39 [00:23<03:22,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003439   0.04306  0.004698     4.096:  10%|█         | 4/39 [00:24<02:11,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003425   0.04245  0.004733     4.049:  13%|█▎        | 5/39 [00:25<01:30,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003418   0.04156  0.004686     3.973:  15%|█▌        | 6/39 [00:26<01:05,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003414    0.0416  0.004659     3.974:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003407   0.04193  0.004723     4.005:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003413   0.04249   0.00479     4.055:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003424   0.04281  0.004794     4.083:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003412    0.0427  0.004728     4.067:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003414   0.04253  0.004743     4.055:  31%|███       | 12/39 [00:30<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003419   0.04238  0.004738     4.043:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003426   0.04256  0.004699     4.055:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003417   0.04241  0.004672      4.04:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003422   0.04234  0.004682     4.035:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003422   0.04206  0.004683     4.013:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003425   0.04203  0.004681     4.011:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003421   0.04185  0.004688     3.996:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003424   0.04196  0.004693     4.006:  51%|█████▏    | 20/39 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003426     0.042  0.004676     4.008:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003427   0.04189  0.004651     3.997:  56%|█████▋    | 22/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003427   0.04193  0.004623     3.998:  59%|█████▉    | 23/39 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003429    0.0419  0.004615     3.995:  62%|██████▏   | 24/39 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003424    0.0418  0.004603     3.986:  64%|██████▍   | 25/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640  0.003423   0.04179  0.004597     3.985:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.552      0.417      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937       0.54      0.418      0.411      0.232
                   0        738       1052      0.509      0.558      0.542      0.259
                   1        738         44      0.486      0.129      0.189     0.0821
                   2        738       8622      0.687      0.734      0.754      0.484
                   3        738        151      0.501      0.437      0.433      0.327
                   4        738        467      0.477      0.587      0.548      0.394
                   5        738         70      0.271      0.414       0.28       0.15
                   6        738         65       0.26     0.0923      0.159     0.0608
                   7        738       1619      0.558      0.627      0.594      0.243
                   8        738       2845      0.647      0.605      0.612      0.321
                   9        738          2          1          0   0.000322   0.000322

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:50:39.157168590 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31191 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round008_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round008_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client1_highway_night_stable_train' images and labels...4895 found, 2914 missing, 0 empty, 0 corrupted: 100%|██████████| 7809/7809 [00:00<00:00, 9804.02it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.323919217418744
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2914 missing, 0 empty, 0 corrupted: 100%|██████████| 7809/7809 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:50:56.053750575 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:50:56.071708910 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1961       640  0.003428   0.03964  0.004659     3.818:   2%|▎         | 1/40 [00:22<14:36, 22.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003474   0.04003  0.004755      3.86:   5%|▌         | 2/40 [00:23<06:11,  9.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1936       640  0.003433   0.03973  0.004657     3.826:   8%|▊         | 3/40 [00:24<03:32,  5.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2039       640  0.003411    0.0392  0.004802     3.793:  10%|█         | 4/40 [00:25<02:17,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1861       640   0.00339    0.0393  0.004788     3.799:  12%|█▎        | 5/40 [00:25<01:33,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1785       640  0.003402   0.03918  0.004766     3.788:  15%|█▌        | 6/40 [00:26<01:07,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2059       640  0.003403   0.03915  0.004664     3.777:  18%|█▊        | 7/40 [00:27<00:51,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2131       640  0.003412   0.03942  0.004735     3.806:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003417    0.0394  0.004854     3.814:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1944       640  0.003421   0.03921  0.004824     3.796:  25%|██▌       | 10/40 [00:29<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2204       640  0.003431   0.03928  0.004816     3.803:  28%|██▊       | 11/40 [00:29<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1809       640  0.003425   0.03886  0.004746     3.762:  30%|███       | 12/40 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2130       640  0.003423   0.03892    0.0048     3.771:  32%|███▎      | 13/40 [00:31<00:20,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1940       640  0.003423   0.03875  0.004825      3.76:  35%|███▌      | 14/40 [00:31<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1885       640  0.003424   0.03852  0.004831     3.742:  38%|███▊      | 15/40 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640  0.003432   0.03828   0.00477     3.719:  40%|████      | 16/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2111       640  0.003442   0.03828  0.004761     3.719:  42%|████▎     | 17/40 [00:33<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003442   0.03806  0.004772     3.702:  45%|████▌     | 18/40 [00:34<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1605       640  0.003437   0.03768  0.004771     3.671:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003437    0.0376  0.004785     3.666:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003431   0.03751   0.00479     3.658:  52%|█████▎    | 21/40 [00:36<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1836       640  0.003431   0.03739  0.004819     3.651:  55%|█████▌    | 22/40 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640  0.003429   0.03739  0.004784     3.649:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2035       640   0.00343   0.03744  0.004786     3.652:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2182       640  0.003435    0.0375  0.004788     3.658:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003436   0.03746  0.004781     3.654:  65%|██████▌   | 26/40 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.545      0.418      0.415      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.534       0.42      0.412      0.233
                   0        738       1052      0.551      0.539      0.534      0.256
                   1        738         44      0.519      0.136      0.217      0.101
                   2        738       8622      0.657      0.739      0.751      0.481
                   3        738        151      0.409      0.437      0.435      0.336
                   4        738        467      0.436       0.61      0.545      0.392
                   5        738         70      0.302      0.414      0.278      0.141
                   6        738         65      0.291     0.0923      0.167     0.0683
                   7        738       1619      0.549      0.627      0.591      0.243
                   8        738       2845      0.622      0.602      0.599       0.31
                   9        738          2          1          0   0.000234   0.000187

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client1_highway_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:52:24.402314788 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31192 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round008_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round008_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 9334.43it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:52:41.950080163 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:52:41.954525891 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003537   0.05153  0.004748     4.785:   3%|▎         | 1/39 [00:21<13:48, 21.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003489   0.05079  0.005115     4.751:   5%|▌         | 2/39 [00:22<05:51,  9.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003452   0.04978  0.005123     4.668:   8%|▊         | 3/39 [00:23<03:20,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003463   0.04878  0.005023     4.581:  10%|█         | 4/39 [00:24<02:09,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003458   0.04816   0.00494     4.525:  13%|█▎        | 5/39 [00:25<01:28,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003421   0.04706  0.004897     4.431:  15%|█▌        | 6/39 [00:25<01:03,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003431   0.04681  0.004964     4.416:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640   0.00342   0.04642  0.004912      4.38:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003435   0.04642   0.00485     4.376:  23%|██▎       | 9/39 [00:27<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640   0.00342   0.04615  0.004838     4.352:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003423   0.04606  0.004833     4.345:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003427   0.04558  0.004845     4.308:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003434   0.04544   0.00481     4.294:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003444   0.04546  0.004777     4.295:  36%|███▌      | 14/39 [00:30<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003445   0.04529  0.004752     4.279:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003435   0.04497  0.004743     4.252:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003427   0.04474  0.004768     4.235:  44%|████▎     | 17/39 [00:32<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003419   0.04467  0.004756     4.227:  46%|████▌     | 18/39 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003421   0.04439  0.004738     4.204:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003416   0.04439  0.004727     4.202:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003408   0.04421  0.004708     4.186:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003403   0.04413  0.004695     4.178:  56%|█████▋    | 22/39 [00:35<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003396   0.04402  0.004696     4.169:  59%|█████▉    | 23/39 [00:36<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003392   0.04395  0.004685     4.162:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003389   0.04384  0.004683     4.153:  64%|██████▍   | 25/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003383    0.0438  0.004667     4.148:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.516      0.435      0.411      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.34it/s]

                 all        738      14937      0.531      0.414      0.409      0.231
                   0        738       1052      0.638      0.518      0.544      0.256
                   1        738         44      0.328     0.0909       0.18     0.0787
                   2        738       8622      0.651      0.741      0.752      0.481
                   3        738        151      0.386       0.45      0.431      0.328
                   4        738        467      0.451      0.604      0.546       0.39
                   5        738         70      0.339      0.414       0.27      0.141
                   6        738         65      0.324     0.0923      0.178     0.0725
                   7        738       1619      0.567      0.617      0.587      0.242
                   8        738       2845      0.628      0.608      0.608      0.323
                   9        738          2          1          0   0.000261   0.000235

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:54:04.113316694 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31193 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round008_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round008_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7835 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client3_citystreet_night_stable_train' images and labels...4883 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7835/7835 [00:00<00:00, 12865.02it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.278118609406953
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7835/7835 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:54:21.380347540 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:54:21.404674698 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1686       640  0.003309   0.04147  0.004806     3.967:   2%|▎         | 1/40 [00:22<14:19, 22.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1827       640   0.00341   0.04213  0.004726     4.021:   5%|▌         | 2/40 [00:22<06:05,  9.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003422   0.04228  0.004584     4.023:   8%|▊         | 3/40 [00:23<03:28,  5.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003399   0.04156  0.004662     3.969:  10%|█         | 4/40 [00:24<02:14,  3.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003409   0.04102   0.00461     3.923:  12%|█▎        | 5/40 [00:25<01:32,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1716       640  0.003383   0.04032  0.004555      3.86:  15%|█▌        | 6/40 [00:25<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2130       640  0.003397   0.04074   0.00462       3.9:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1671       640  0.003377   0.04038  0.004633     3.871:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1987       640  0.003378   0.04052   0.00464     3.883:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1959       640  0.003382   0.04035  0.004611     3.867:  25%|██▌       | 10/40 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1979       640  0.003392   0.04019  0.004567     3.852:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003383   0.03997  0.004552     3.833:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003378   0.03968  0.004594     3.812:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640  0.003376   0.03954  0.004587       3.8:  35%|███▌      | 14/40 [00:31<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1830       640  0.003369   0.03937  0.004567     3.785:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003369   0.03935  0.004536      3.78:  40%|████      | 16/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1597       640  0.003363   0.03905  0.004499     3.753:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2051       640  0.003367   0.03899  0.004489     3.747:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1822       640  0.003374   0.03878   0.00447      3.73:  48%|████▊     | 19/40 [00:34<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003379   0.03869  0.004509     3.726:  50%|█████     | 20/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003386   0.03865   0.00452     3.725:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1987       640   0.00339   0.03857  0.004532     3.719:  55%|█████▌    | 22/40 [00:36<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003395   0.03851  0.004531     3.715:  57%|█████▊    | 23/40 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2018       640  0.003405   0.03847  0.004557     3.715:  60%|██████    | 24/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1946       640  0.003406   0.03844  0.004542     3.711:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003401   0.03843  0.004548     3.711:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.581        0.4       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.561      0.402      0.408      0.231
                   0        738       1052      0.617      0.507      0.532      0.254
                   1        738         44      0.559      0.114      0.207     0.0951
                   2        738       8622      0.671      0.726      0.745      0.476
                   3        738        151      0.489      0.417      0.431      0.327
                   4        738        467      0.446      0.591      0.543      0.389
                   5        738         70      0.323      0.414       0.27      0.138
                   6        738         65      0.285     0.0614      0.166     0.0682
                   7        738       1619      0.567      0.603      0.584      0.243
                   8        738       2845      0.656      0.592      0.602      0.319
                   9        738          2          1          0    0.00023    0.00023

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 15:55:45.889385797 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31194 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round008_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round008_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client4_residential_day_stable_train' images and labels...:   0%|          | 0/7861 [00:00<?, ?it/s]

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 13513.52it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:56:01.600291211 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:56:01.636498710 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2210       640  0.003456   0.05178  0.004828     4.805:   3%|▎         | 1/39 [00:22<14:31, 22.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003418   0.05055  0.005247     4.737:   5%|▌         | 2/39 [00:23<06:09,  9.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1757       640  0.003356   0.04851   0.00513      4.56:   8%|▊         | 3/39 [00:24<03:29,  5.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003353   0.04798  0.005065     4.512:  10%|█         | 4/39 [00:25<02:15,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2152       640  0.003356   0.04705  0.005038     4.435:  13%|█▎        | 5/39 [00:26<01:32,  2.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1679       640  0.003348   0.04549  0.005118     4.317:  15%|█▌        | 6/39 [00:26<01:06,  2.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003369   0.04522    0.0051     4.295:  18%|█▊        | 7/39 [00:27<00:50,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003377   0.04497  0.004976     4.266:  21%|██        | 8/39 [00:28<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2197       640  0.003377   0.04512  0.004924     4.274:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003381   0.04509    0.0049     4.269:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2162       640  0.003391   0.04504   0.00488     4.265:  28%|██▊       | 11/39 [00:30<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2149       640  0.003409   0.04499  0.004932     4.266:  31%|███       | 12/39 [00:30<00:21,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2024       640  0.003414   0.04497   0.00493     4.265:  33%|███▎      | 13/39 [00:31<00:19,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640   0.00342   0.04477   0.00493     4.249:  36%|███▌      | 14/39 [00:32<00:18,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003426   0.04447  0.004948     4.227:  38%|███▊      | 15/39 [00:32<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640   0.00342   0.04415  0.004939     4.201:  41%|████      | 16/39 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003419   0.04404  0.004905     4.189:  44%|████▎     | 17/39 [00:34<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003415   0.04401  0.004862     4.183:  46%|████▌     | 18/39 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1723       640  0.003417   0.04377  0.004861     4.164:  49%|████▊     | 19/39 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003407   0.04375  0.004837     4.159:  51%|█████▏    | 20/39 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1821       640  0.003402   0.04362  0.004805     4.146:  54%|█████▍    | 21/39 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1987       640  0.003399    0.0436  0.004822     4.146:  56%|█████▋    | 22/39 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1940       640  0.003399   0.04358  0.004835     4.145:  59%|█████▉    | 23/39 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003393   0.04345  0.004829     4.134:  62%|██████▏   | 24/39 [00:38<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1905       640  0.003396   0.04335   0.00482     4.125:  64%|██████▍   | 25/39 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003395   0.04321  0.004795     4.112:  67%|██████▋   | 26/39 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.502      0.444      0.414      0.233
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.483      0.446      0.412      0.233
                   0        738       1052       0.47      0.566      0.541      0.257
                   1        738         44      0.439       0.25      0.185     0.0796
                   2        738       8622      0.636      0.746      0.751       0.48
                   3        738        151      0.317       0.45      0.439      0.335
                   4        738        467      0.417      0.625      0.548      0.395
                   5        738         70      0.253      0.429      0.282      0.144
                   6        738         65      0.191      0.123       0.17     0.0669
                   7        738       1619      0.516      0.642      0.589      0.244
                   8        738       2845      0.593      0.633       0.61      0.325
                   9        738          2          1          0   0.000258   0.000207

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client4_residential_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:57:28.110386751 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31195 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round008_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round008_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client5_residential_night_stable_train' images and labels...4885 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7843/7843 [00:00<00:00, 12040.43it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round008_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7843/7843 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 15:57:44.041523075 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 15:57:44.055113744 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2063       640   0.00353   0.04601  0.004866     4.352:   2%|▎         | 1/40 [00:22<14:33, 22.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003575   0.04493  0.005135     4.291:   5%|▌         | 2/40 [00:23<06:11,  9.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2108       640  0.003496   0.04501  0.004905     4.273:   8%|▊         | 3/40 [00:24<03:30,  5.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2041       640  0.003507   0.04457  0.004925      4.24:  10%|█         | 4/40 [00:25<02:16,  3.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2172       640  0.003496   0.04412  0.004905     4.202:  12%|█▎        | 5/40 [00:25<01:33,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1709       640  0.003471   0.04294  0.004827     4.099:  15%|█▌        | 6/40 [00:26<01:07,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1621       640  0.003446   0.04181  0.004801     4.004:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2099       640  0.003456   0.04166  0.004782     3.992:  20%|██        | 8/40 [00:27<00:40,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003446   0.04131   0.00464     3.952:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640  0.003452   0.04151   0.00473     3.975:  25%|██▌       | 10/40 [00:29<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2263       640  0.003452   0.04152  0.004756     3.978:  28%|██▊       | 11/40 [00:29<00:25,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1791       640  0.003439     0.041  0.004737     3.934:  30%|███       | 12/40 [00:30<00:22,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003435   0.04068  0.004728     3.907:  32%|███▎      | 13/40 [00:31<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2128       640   0.00344   0.04066  0.004745     3.907:  35%|███▌      | 14/40 [00:31<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003444    0.0404  0.004766     3.889:  38%|███▊      | 15/40 [00:32<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1765       640   0.00344   0.04005  0.004754     3.859:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640   0.00344   0.03996  0.004789     3.855:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2230       640  0.003448      0.04  0.004829     3.862:  45%|████▌     | 18/40 [00:34<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1863       640  0.003449   0.03971  0.004829     3.839:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640  0.003448   0.03945  0.004836     3.819:  50%|█████     | 20/40 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003452   0.03929  0.004834     3.806:  52%|█████▎    | 21/40 [00:36<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1653       640  0.003447   0.03901  0.004852     3.785:  55%|█████▌    | 22/40 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003446   0.03893  0.004865     3.779:  57%|█████▊    | 23/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003442   0.03874  0.004849     3.762:  60%|██████    | 24/40 [00:38<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003445   0.03869  0.004856     3.759:  62%|██████▎   | 25/40 [00:38<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1697       640  0.003446   0.03843  0.004839     3.737:  65%|██████▌   | 26/40 [00:39<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.553      0.405      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.543      0.404      0.409      0.231
                   0        738       1052      0.569      0.524       0.53      0.256
                   1        738         44      0.497      0.112      0.213     0.0974
                   2        738       8622      0.671      0.726      0.746      0.477
                   3        738        151      0.491      0.424      0.426      0.325
                   4        738        467      0.459      0.585      0.546      0.393
                   5        738         70      0.325        0.4      0.274      0.133
                   6        738         65      0.227       0.05      0.165     0.0651
                   7        738       1619      0.556      0.611      0.585      0.243
                   8        738       2845      0.634      0.609      0.606      0.322
                   9        738          2          1          0   0.000208   0.000187

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 15:59:12.568978955 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31196 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round008_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round008_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 15:59:29.766920021 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 15:59:29.887472153 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03191   0.03859  0.004188     5.975:   3%|▎         | 1/31 [00:32<16:27, 32.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03253   0.03938  0.004381     6.103:   6%|▋         | 2/31 [00:34<06:51, 14.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640     0.032   0.03828  0.004299     5.967:  10%|▉         | 3/31 [00:34<03:45,  8.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03144   0.03669  0.004072     5.776:  13%|█▎        | 4/31 [00:35<02:19,  5.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03146   0.03689  0.004113     5.797:  16%|█▌        | 5/31 [00:36<01:31,  3.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03165    0.0369  0.004165     5.817:  19%|█▉        | 6/31 [00:36<01:02,  2.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03176   0.03669  0.004226     5.814:  23%|██▎       | 7/31 [00:37<00:45,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03171   0.03678  0.004241     5.818:  26%|██▌       | 8/31 [00:37<00:33,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03177   0.03672  0.004147     5.812:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03177   0.03685  0.004122      5.82:  32%|███▏      | 10/31 [00:38<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03175    0.0369  0.004147     5.824:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03166   0.03665  0.004145     5.797:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03164   0.03668  0.004093     5.793:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03167   0.03655  0.004058     5.782:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03169   0.03649  0.004106     5.783:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640    0.0317   0.03639  0.004102     5.776:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03175   0.03645  0.004078     5.782:  55%|█████▍    | 17/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03183   0.03657  0.004049     5.796:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03178   0.03647   0.00402     5.782:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03179    0.0367  0.004019     5.801:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03183   0.03676   0.00404      5.81:  68%|██████▊   | 21/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03185   0.03688  0.004013     5.819:  71%|███████   | 22/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03185   0.03694  0.003994     5.822:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03188   0.03705  0.003983     5.833:  77%|███████▋  | 24/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640    0.0319   0.03703  0.003998     5.834:  81%|████████  | 25/31 [00:47<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03197    0.0371  0.004007     5.846:  84%|████████▍ | 26/31 [00:48<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.476      0.472      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937       0.56      0.401       0.41      0.231
                   0        738       1052      0.598       0.53      0.543      0.258
                   1        738         44      0.467     0.0909      0.181     0.0754
                   2        738       8622      0.704      0.726      0.754      0.488
                   3        738        151       0.51      0.424      0.435      0.326
                   4        738        467      0.504      0.576      0.549      0.393
                   5        738         70      0.289      0.414      0.279      0.142
                   6        738         65       0.28     0.0615      0.162     0.0615
                   7        738       1619      0.597      0.587      0.585      0.244
                   8        738       2845      0.649      0.599      0.607      0.323
                   9        738          2          1          0    0.00036    0.00036

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round008_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 16:01:09.712560826 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round009 phase_round=9 ===

02 head-to-full DQA:  25%|██▌       | 8/32 [1:53:50<5:40:39, 851.65s/round, elapsed=1h53m50s, eta=5h41m32s, phase=phase1_head, round=8]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round009 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round009 client0_highway_day: pseudo scan 250/1500 images, kept 2374 boxes
round009 client0_highway_day: pseudo scan 500/1500 images, kept 4817 boxes
round009 client0_highway_day: pseudo scan 750/1500 images, kept 7170 boxes
round009 client0_highway_day: pseudo scan 1000/1500 images, kept 9550 boxes
round009 client0_highway_day: pseudo scan 1250/1500 images, kept 11884 boxes
round009 client0_highway_day: pseudo scan 1500/1500 images, kept 14276 boxes
{
  "round": "round009",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round008_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11226,
  "boxes_per_kept_image": 7.519089082384461,
  "mean_conf": 0.8060074346616224,
  "mean_stability": 0.9530878335359622,
  "mean_score": 0.7715009697112606,
  "class_counts": {
    "0": 158,
    "2": 6425,
    "3": 113,
    "4": 560,
    "5": 8,
    "7": 563,
    "8": 3399
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_client0_highway_day_stable_boxes.csv"
}
round009 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round009 client1_highway_night: pseudo scan 250/1500 images, kept 1653 boxes
round009 client1_highway_night: pseudo scan 500/1500 images, kept 3432 boxes
round009 client1_highway_night: pseudo scan 750/1500 images, kept 5211 boxes
round009 client1_highway_night: pseudo scan 1000/1500 images, kept 6869 boxes
round009 client1_highway_night: pseudo scan 1250/1500 images, kept 8612 boxes
round009 client1_highway_night: pseudo scan 1500/1500 images, kept 10290 boxes
{
  "round": "round009",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round008_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1462,
  "pseudo_boxes_kept": 8405,
  "boxes_per_kept_image": 5.748974008207934,
  "mean_conf": 0.7187824649196661,
  "mean_stability": 0.9374511178656039,
  "mean_score": 0.6779586084086499,
  "class_counts": {
    "0": 65,
    "2": 4631,
    "3": 29,
    "4": 139,
    "5": 8,
    "7": 562,
    "8": 2971
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_client1_highway_night_stable_boxes.csv"
}
round009 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round009 client2_citystreet_day: pseudo scan 250/1500 images, kept 2709 boxes
round009 client2_citystreet_day: pseudo scan 500/1500 images, kept 5452 boxes
round009 client2_citystreet_day: pseudo scan 750/1500 images, kept 8205 boxes
round009 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10969 boxes
round009 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13700 boxes
round009 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16364 boxes
{
  "round": "round009",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round008_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13805,
  "boxes_per_kept_image": 9.227941176470589,
  "mean_conf": 0.8038624653216938,
  "mean_stability": 0.950923779592787,
  "mean_score": 0.7679268457999785,
  "class_counts": {
    "0": 1450,
    "2": 7364,
    "3": 189,
    "4": 611,
    "5": 71,
    "7": 1537,
    "8": 2583
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_client2_citystreet_day_stable_boxes.csv"
}
round009 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round009 client3_citystreet_night: pseudo scan 250/1500 images, kept 2378 boxes
round009 client3_citystreet_night: pseudo scan 500/1500 images, kept 4720 boxes
round009 client3_citystreet_night: pseudo scan 750/1500 images, kept 7040 boxes
round009 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9289 boxes
round009 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11714 boxes
round009 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14054 boxes
{
  "round": "round009",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round008_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1474,
  "pseudo_boxes_kept": 11817,
  "boxes_per_kept_image": 8.01696065128901,
  "mean_conf": 0.7145052150092351,
  "mean_stability": 0.9340443999783242,
  "mean_score": 0.6717874934242942,
  "class_counts": {
    "0": 548,
    "2": 6325,
    "3": 70,
    "4": 156,
    "5": 36,
    "7": 1960,
    "8": 2722
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_client3_citystreet_night_stable_boxes.csv"
}
round009 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round009 client4_residential_day: pseudo scan 250/1500 images, kept 2583 boxes
round009 client4_residential_day: pseudo scan 500/1500 images, kept 5191 boxes
round009 client4_residential_day: pseudo scan 750/1500 images, kept 7745 boxes
round009 client4_residential_day: pseudo scan 1000/1500 images, kept 10230 boxes
round009 client4_residential_day: pseudo scan 1250/1500 images, kept 12758 boxes
round009 client4_residential_day: pseudo scan 1500/1500 images, kept 15233 boxes
{
  "round": "round009",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round008_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9969,
  "boxes_per_kept_image": 6.686116700201207,
  "mean_conf": 0.8399008871715231,
  "mean_stability": 0.9591494680694621,
  "mean_score": 0.809092139423008,
  "class_counts": {
    "0": 383,
    "2": 6855,
    "3": 62,
    "4": 311,
    "5": 47,
    "7": 539,
    "8": 1772
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_client4_residential_day_stable_boxes.csv"
}
round009 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round009 client5_residential_night: pseudo scan 250/1500 images, kept 2344 boxes
round009 client5_residential_night: pseudo scan 500/1500 images, kept 4663 boxes
round009 client5_residential_night: pseudo scan 750/1500 images, kept 6971 boxes
round009 client5_residential_night: pseudo scan 1000/1500 images, kept 9355 boxes
round009 client5_residential_night: pseudo scan 1250/1500 images, kept 11734 boxes
round009 client5_residential_night: pseudo scan 1500/1500 images, kept 14113 boxes
{
  "round": "round009",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round008_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1481,
  "pseudo_boxes_kept": 8764,
  "boxes_per_kept_image": 5.917623227548954,
  "mean_conf": 0.7897412711894713,
  "mean_stability": 0.9479915565045551,
  "mean_score": 0.7516510246679122,
  "class_counts": {
    "0": 130,
    "2": 6351,
    "3": 33,
    "4": 99,
    "5": 24,
    "7": 661,
    "8": 1466
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round009_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31197 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round009_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round009_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7867 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 15652.82it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:03:21.243311878 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:03:21.265743247 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2068       640  0.003436   0.04194  0.004635     4.001:   3%|▎         | 1/39 [00:21<13:38, 21.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003444   0.04227  0.004364     4.007:   5%|▌         | 2/39 [00:22<05:48,  9.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003476   0.04304  0.004484      4.08:   8%|▊         | 3/39 [00:23<03:18,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003438   0.04312  0.004663     4.098:  10%|█         | 4/39 [00:24<02:09,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003423   0.04251  0.004697     4.051:  13%|█▎        | 5/39 [00:24<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003416   0.04161   0.00465     3.974:  15%|█▌        | 6/39 [00:25<01:04,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003412   0.04165  0.004626     3.975:  18%|█▊        | 7/39 [00:26<00:48,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003405   0.04198  0.004692     4.006:  21%|██        | 8/39 [00:26<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003411   0.04253  0.004758     4.056:  23%|██▎       | 9/39 [00:27<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003422   0.04285  0.004761     4.083:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640   0.00341   0.04272  0.004695     4.066:  28%|██▊       | 11/39 [00:28<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003412   0.04255  0.004709     4.054:  31%|███       | 12/39 [00:29<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003417   0.04239  0.004704     4.041:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003424   0.04258  0.004665     4.053:  36%|███▌      | 14/39 [00:30<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003415   0.04242  0.004637     4.038:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640   0.00342   0.04234  0.004649     4.033:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640   0.00342   0.04207   0.00465     4.011:  44%|████▎     | 17/39 [00:32<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003423   0.04204  0.004648     4.009:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003419   0.04185  0.004655     3.994:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003422   0.04196  0.004661     4.004:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003424   0.04201  0.004644     4.006:  54%|█████▍    | 21/39 [00:35<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003424   0.04189  0.004619     3.995:  56%|█████▋    | 22/39 [00:36<00:11,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003425   0.04193  0.004591     3.995:  59%|█████▉    | 23/39 [00:36<00:10,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003426   0.04189  0.004582     3.992:  62%|██████▏   | 24/39 [00:37<00:09,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003422   0.04179  0.004571     3.983:  64%|██████▍   | 25/39 [00:38<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640  0.003421   0.04179  0.004565     3.982:  67%|██████▋   | 26/39 [00:38<00:08,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.553      0.415      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.541      0.417      0.413      0.232
                   0        738       1052      0.508      0.554      0.542      0.259
                   1        738         44      0.498      0.135      0.213     0.0885
                   2        738       8622      0.689      0.733      0.754      0.484
                   3        738        151      0.502       0.43      0.433      0.327
                   4        738        467      0.476      0.589      0.546      0.393
                   5        738         70      0.277      0.414      0.275      0.144
                   6        738         65      0.256      0.085      0.162      0.062
                   7        738       1619      0.551      0.623      0.592      0.244
                   8        738       2845      0.651      0.605       0.61       0.32
                   9        738          2          1          0   0.000323    0.00029

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:04:44.216957016 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31198 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round009_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round009_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client1_highway_night_stable_train' images and labels...4895 found, 2910 missing, 0 empty, 0 corrupted: 100%|██████████| 7805/7805 [00:00<00:00, 14780.08it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.328756313131313
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2910 missing, 0 empty, 0 corrupted: 100%|██████████| 7805/7805 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:05:01.600741749 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:05:01.609755814 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1881       640  0.003388   0.04088  0.003982      3.86:   2%|▎         | 1/40 [00:22<14:34, 22.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1902       640  0.003388   0.03933  0.004384     3.768:   5%|▌         | 2/40 [00:23<06:10,  9.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1927       640  0.003395   0.03958  0.004313     3.783:   8%|▊         | 3/40 [00:24<03:30,  5.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1967       640  0.003398   0.03941  0.004556     3.789:  10%|█         | 4/40 [00:25<02:16,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1833       640  0.003381   0.03948  0.004407     3.782:  12%|█▎        | 5/40 [00:25<01:33,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640  0.003396   0.03904  0.004489     3.754:  15%|█▌        | 6/40 [00:26<01:07,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2231       640  0.003409   0.03945  0.004467     3.786:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640  0.003391   0.03913  0.004505     3.762:  20%|██        | 8/40 [00:27<00:41,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003386   0.03875  0.004538     3.734:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1665       640  0.003381   0.03835  0.004454     3.695:  25%|██▌       | 10/40 [00:29<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2090       640  0.003391   0.03844  0.004484     3.705:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1795       640  0.003387   0.03808  0.004488     3.676:  30%|███       | 12/40 [00:30<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003396   0.03809  0.004593     3.686:  32%|███▎      | 13/40 [00:30<00:20,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640  0.003399   0.03794  0.004624     3.677:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003391   0.03773  0.004573     3.656:  38%|███▊      | 15/40 [00:32<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003395   0.03758  0.004569     3.644:  40%|████      | 16/40 [00:32<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1773       640  0.003398   0.03738  0.004548     3.626:  42%|████▎     | 17/40 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003398   0.03723  0.004534     3.613:  45%|████▌     | 18/40 [00:34<00:14,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1512       640  0.003397   0.03681  0.004579     3.583:  48%|████▊     | 19/40 [00:34<00:14,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003403   0.03683  0.004576     3.585:  50%|█████     | 20/40 [00:35<00:13,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003406   0.03677  0.004605     3.582:  52%|█████▎    | 21/40 [00:36<00:12,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003407   0.03657   0.00462     3.568:  55%|█████▌    | 22/40 [00:36<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2082       640  0.003412   0.03667  0.004658     3.579:  57%|█████▊    | 23/40 [00:37<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1990       640  0.003411    0.0366  0.004656     3.573:  60%|██████    | 24/40 [00:38<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1804       640  0.003412   0.03644  0.004684     3.563:  62%|██████▎   | 25/40 [00:38<00:09,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640  0.003416   0.03641  0.004671      3.56:  65%|██████▌   | 26/40 [00:39<00:09,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.566      0.408      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.23it/s]

                 all        738      14937      0.552       0.41      0.409      0.231
                   0        738       1052      0.568      0.531      0.535      0.258
                   1        738         44      0.555      0.113      0.212     0.0961
                   2        738       8622      0.672      0.732       0.75      0.481
                   3        738        151      0.477      0.417       0.43       0.33
                   4        738        467       0.45      0.598      0.539      0.388
                   5        738         70       0.32      0.414      0.281      0.139
                   6        738         65       0.29     0.0769      0.163     0.0658
                   7        738       1619      0.563      0.615      0.586      0.242
                   8        738       2845      0.629      0.599      0.598      0.311
                   9        738          2          1          0   0.000222     0.0002

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:06:27.883804263 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31199 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round009_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round009_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client2_citystreet_day_stable_train' images and labels...:   0%|          | 0/7873 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 11240.71it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:06:42.184763758 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:06:42.187206269 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2066       640  0.003532   0.05164  0.004691     4.789:   3%|▎         | 1/39 [00:22<14:02, 22.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003485   0.05087  0.005065     4.754:   5%|▌         | 2/39 [00:23<05:56,  9.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003448   0.04985  0.005078      4.67:   8%|▊         | 3/39 [00:23<03:21,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003459   0.04884  0.004981     4.582:  10%|█         | 4/39 [00:24<02:10,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003455   0.04822  0.004902     4.526:  13%|█▎        | 5/39 [00:25<01:29,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003418   0.04712  0.004862     4.432:  15%|█▌        | 6/39 [00:25<01:04,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003428   0.04685  0.004931     4.417:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003417   0.04645  0.004879      4.38:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003432   0.04645  0.004814     4.376:  23%|██▎       | 9/39 [00:27<00:31,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003417   0.04617  0.004803     4.351:  26%|██▌       | 10/39 [00:28<00:26,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640   0.00342   0.04608  0.004799     4.344:  28%|██▊       | 11/39 [00:29<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003424   0.04559   0.00481     4.306:  31%|███       | 12/39 [00:29<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003431   0.04545  0.004776     4.292:  33%|███▎      | 13/39 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003441   0.04547  0.004743     4.292:  36%|███▌      | 14/39 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003442   0.04529  0.004718     4.276:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003433   0.04497  0.004709     4.249:  41%|████      | 16/39 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003424   0.04474  0.004733     4.232:  44%|████▎     | 17/39 [00:32<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003416   0.04466   0.00472     4.224:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003418   0.04439  0.004702     4.201:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003413   0.04438  0.004692     4.199:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003405   0.04421  0.004673     4.183:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640    0.0034   0.04412   0.00466     4.175:  56%|█████▋    | 22/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003393   0.04401  0.004661     4.165:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003389   0.04394   0.00465     4.159:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003386   0.04383  0.004648     4.149:  64%|██████▍   | 25/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003381   0.04379  0.004633     4.144:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.513      0.438      0.411      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937       0.53      0.417       0.41      0.231
                   0        738       1052      0.625      0.518      0.542      0.255
                   1        738         44      0.356      0.114      0.185     0.0851
                   2        738       8622      0.648      0.745      0.754      0.481
                   3        738        151      0.383       0.45      0.432      0.329
                   4        738        467      0.443       0.61      0.543      0.388
                   5        738         70      0.341      0.414      0.268      0.138
                   6        738         65      0.321     0.0923       0.18     0.0712
                   7        738       1619      0.565       0.62      0.589      0.242
                   8        738       2845      0.622      0.612      0.607      0.322
                   9        738          2          1          0   0.000263   0.000236

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:08:08.191156571 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31200 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round009_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round009_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client3_citystreet_night_stable_train' images and labels...4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<00:00, 9384.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:08:25.049492483 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:08:25.053037860 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1889       640  0.003492   0.04332  0.004468     4.102:   2%|▎         | 1/40 [00:21<14:14, 21.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1852       640  0.003483   0.04353  0.004963     4.158:   5%|▌         | 2/40 [00:22<06:02,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1948       640  0.003444   0.04359  0.004943     4.158:   8%|▊         | 3/40 [00:23<03:25,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1939       640  0.003423   0.04315   0.00484     4.113:  10%|█         | 4/40 [00:24<02:13,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1863       640    0.0034   0.04232   0.00478      4.04:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1843       640  0.003412   0.04201  0.004751     4.014:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1954       640  0.003416    0.0416  0.004715     3.979:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1971       640  0.003422   0.04143  0.004713     3.965:  20%|██        | 8/40 [00:27<00:40,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1917       640  0.003417   0.04124  0.004659     3.945:  22%|██▎       | 9/40 [00:27<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1946       640   0.00343   0.04109  0.004623     3.931:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1889       640  0.003421   0.04081  0.004559     3.904:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1655       640  0.003411   0.04046  0.004601     3.878:  30%|███       | 12/40 [00:29<00:21,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2023       640  0.003409    0.0403  0.004586     3.863:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1981       640   0.00341   0.04032  0.004598     3.867:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1793       640  0.003407   0.04014   0.00464     3.855:  38%|███▊      | 15/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1895       640    0.0034   0.03979  0.004592     3.823:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1651       640  0.003403   0.03945  0.004595     3.796:  42%|████▎     | 17/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1894       640  0.003407   0.03923  0.004601     3.779:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1757       640  0.003407   0.03891  0.004582     3.752:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2237       640  0.003408   0.03894  0.004552     3.752:  50%|█████     | 20/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1923       640  0.003416   0.03887  0.004563     3.748:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1802       640  0.003414   0.03868  0.004533      3.73:  55%|█████▌    | 22/40 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2165       640  0.003416   0.03867   0.00454      3.73:  57%|█████▊    | 23/40 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1875       640  0.003415   0.03855  0.004553     3.721:  60%|██████    | 24/40 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1942       640  0.003416   0.03846  0.004536     3.713:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1883       640  0.003412   0.03834  0.004534     3.703:  65%|██████▌   | 26/40 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.558      0.409       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.542      0.411      0.409      0.231
                   0        738       1052      0.588      0.509      0.531      0.253
                   1        738         44      0.527      0.114      0.208     0.0938
                   2        738       8622      0.661      0.731      0.746      0.476
                   3        738        151      0.434      0.437      0.433      0.331
                   4        738        467      0.438      0.606      0.541      0.385
                   5        738         70      0.337      0.414      0.276      0.142
                   6        738         65       0.27     0.0615      0.162      0.068
                   7        738       1619      0.541      0.628      0.589      0.243
                   8        738       2845      0.626      0.606        0.6      0.317
                   9        738          2          1          0    0.00022   0.000198

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:09:50.995244408 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31201 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round009_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round009_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 13715.52it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:10:07.552764990 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:10:07.553609500 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2084       640  0.003426   0.05045  0.004109     4.639:   3%|▎         | 1/39 [00:21<13:43, 21.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003461      0.05  0.004911      4.67:   5%|▌         | 2/39 [00:22<05:49,  9.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003402   0.04795  0.004858     4.497:   8%|▊         | 3/39 [00:23<03:19,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003416   0.04704   0.00499     4.435:  10%|█         | 4/39 [00:24<02:09,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003391   0.04581  0.004954     4.332:  13%|█▎        | 5/39 [00:24<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1735       640  0.003401    0.0445  0.005035     4.235:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003415   0.04425  0.005031     4.216:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640  0.003424   0.04399   0.00496      4.19:  21%|██        | 8/39 [00:26<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003418   0.04397  0.005019     4.193:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003428   0.04399  0.004993     4.193:  26%|██▌       | 10/39 [00:28<00:26,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2139       640  0.003428   0.04398   0.00498     4.191:  28%|██▊       | 11/39 [00:28<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2120       640  0.003426   0.04392   0.00495     4.184:  31%|███       | 12/39 [00:29<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003436   0.04399  0.004932     4.189:  33%|███▎      | 13/39 [00:30<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003444   0.04394  0.004915     4.184:  36%|███▌      | 14/39 [00:30<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003448   0.04364   0.00491      4.16:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640  0.003447   0.04338    0.0049     4.138:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640  0.003434   0.04317  0.004869     4.117:  44%|████▎     | 17/39 [00:32<00:14,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003431   0.04313  0.004834     4.112:  46%|████▌     | 18/39 [00:33<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1602       640  0.003423   0.04284  0.004828     4.088:  49%|████▊     | 19/39 [00:34<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2209       640  0.003425   0.04283  0.004812     4.086:  51%|█████▏    | 20/39 [00:34<00:12,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003424    0.0428  0.004784      4.08:  54%|█████▍    | 21/39 [00:35<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003422    0.0428  0.004783      4.08:  56%|█████▋    | 22/39 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640  0.003424   0.04282  0.004808     4.084:  59%|█████▉    | 23/39 [00:36<00:10,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003421   0.04273  0.004802     4.076:  62%|██████▏   | 24/39 [00:37<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640  0.003421   0.04273  0.004802     4.076:  64%|██████▍   | 25/39 [00:38<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640   0.00342   0.04254  0.004788      4.06:  67%|██████▋   | 26/39 [00:38<00:08,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.499      0.448      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.482      0.449      0.412      0.232
                   0        738       1052      0.466      0.576      0.541      0.256
                   1        738         44      0.457       0.25      0.197      0.082
                   2        738       8622      0.631      0.749      0.752       0.48
                   3        738        151      0.304      0.464      0.445      0.336
                   4        738        467        0.4      0.627      0.548      0.395
                   5        738         70      0.268      0.414      0.275      0.141
                   6        738         65      0.209      0.138      0.166     0.0643
                   7        738       1619      0.505      0.635      0.583      0.242
                   8        738       2845      0.584      0.632      0.608      0.323
                   9        738          2          1          0   0.000267   0.000241

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client4_residential_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 16:11:34.473536890 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31202 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round009_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round009_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client5_residential_night_stable_train' images and labels...4885 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7843/7843 [00:00<00:00, 9774.08it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.270911949685535
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round009_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2958 missing, 0 empty, 0 corrupted: 100%|██████████| 7843/7843 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:11:51.050760630 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:11:51.137720373 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2063       640  0.003526   0.04605  0.004841     4.354:   2%|▎         | 1/40 [00:21<13:59, 21.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003573   0.04497  0.005115     4.292:   5%|▌         | 2/40 [00:22<05:55,  9.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2108       640  0.003494     0.045  0.004887     4.271:   8%|▊         | 3/40 [00:23<03:22,  5.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2041       640  0.003504   0.04454  0.004906     4.236:  10%|█         | 4/40 [00:24<02:11,  3.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2172       640  0.003494   0.04409  0.004885     4.198:  12%|█▎        | 5/40 [00:24<01:30,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1709       640   0.00347    0.0429  0.004805     4.094:  15%|█▌        | 6/40 [00:25<01:05,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1621       640  0.003444   0.04175   0.00478     3.998:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2099       640  0.003455   0.04159  0.004759     3.985:  20%|██        | 8/40 [00:26<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003444   0.04124  0.004616     3.944:  22%|██▎       | 9/40 [00:27<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640   0.00345   0.04142  0.004706     3.966:  25%|██▌       | 10/40 [00:28<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2263       640   0.00345   0.04142  0.004731     3.968:  28%|██▊       | 11/40 [00:28<00:25,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1791       640  0.003437   0.04089  0.004712     3.923:  30%|███       | 12/40 [00:29<00:22,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003433   0.04055  0.004702     3.895:  32%|███▎      | 13/40 [00:30<00:20,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2128       640  0.003439   0.04053  0.004718     3.895:  35%|███▌      | 14/40 [00:30<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003442   0.04026  0.004738     3.875:  38%|███▊      | 15/40 [00:31<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1765       640  0.003438    0.0399  0.004726     3.845:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640  0.003438    0.0398   0.00476      3.84:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2230       640  0.003447   0.03985  0.004801     3.847:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1863       640  0.003447   0.03956    0.0048     3.825:  48%|████▊     | 19/40 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640  0.003446   0.03929  0.004808     3.803:  50%|█████     | 20/40 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640   0.00345   0.03913  0.004805      3.79:  52%|█████▎    | 21/40 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1653       640  0.003445   0.03885  0.004823     3.769:  55%|█████▌    | 22/40 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003444   0.03876  0.004834     3.763:  57%|█████▊    | 23/40 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640   0.00344   0.03857  0.004818     3.746:  60%|██████    | 24/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003443   0.03852  0.004826     3.743:  62%|██████▎   | 25/40 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1697       640  0.003444   0.03826  0.004808     3.721:  65%|██████▌   | 26/40 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.608       0.39      0.413       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.579      0.392      0.408       0.23
                   0        738       1052      0.605      0.511      0.531      0.256
                   1        738         44      0.596     0.0672      0.212     0.0955
                   2        738       8622      0.702      0.716      0.747      0.478
                   3        738        151      0.543      0.404      0.425      0.323
                   4        738        467      0.478      0.576      0.543       0.39
                   5        738         70      0.364        0.4      0.271      0.133
                   6        738         65      0.267     0.0462       0.16     0.0614
                   7        738       1619      0.579      0.602      0.587      0.245
                   8        738       2845      0.658      0.596      0.606      0.322
                   9        738          2          1          0   0.000216   0.000194

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:13:14.996789177 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31203 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round009_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round009_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:13:30.769938381 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:13:30.770396514 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.41G      2625       640   0.03159     0.038  0.004085     5.895:   3%|▎         | 1/31 [00:32<16:11, 32.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03221   0.03877  0.004284     6.021:   6%|▋         | 2/31 [00:33<06:40, 13.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03169   0.03769  0.004207     5.887:  10%|▉         | 3/31 [00:33<03:40,  7.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03122   0.03625  0.003997     5.718:  13%|█▎        | 4/31 [00:34<02:17,  5.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03122   0.03642  0.004032     5.734:  16%|█▌        | 5/31 [00:35<01:29,  3.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640    0.0314    0.0364  0.004078      5.75:  19%|█▉        | 6/31 [00:35<01:02,  2.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640    0.0315   0.03618  0.004135     5.745:  23%|██▎       | 7/31 [00:36<00:44,  1.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03144   0.03626   0.00415     5.748:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03151    0.0362  0.004057     5.741:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640    0.0315   0.03632  0.004031     5.748:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03147   0.03637  0.004055     5.752:  35%|███▌      | 11/31 [00:38<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03139   0.03611  0.004053     5.724:  39%|███▊      | 12/31 [00:39<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03137   0.03613     0.004      5.72:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03139   0.03601  0.003965     5.709:  45%|████▌     | 14/31 [00:40<00:11,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03142   0.03594  0.004014      5.71:  48%|████▊     | 15/31 [00:41<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03143   0.03584   0.00401     5.703:  52%|█████▏    | 16/31 [00:41<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03148    0.0359  0.003987     5.709:  55%|█████▍    | 17/31 [00:42<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03155   0.03602  0.003959     5.723:  58%|█████▊    | 18/31 [00:43<00:07,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03151   0.03592  0.003931     5.709:  61%|██████▏   | 19/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03152   0.03614  0.003929     5.727:  65%|██████▍   | 20/31 [00:44<00:06,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03156   0.03621  0.003948     5.738:  68%|██████▊   | 21/31 [00:44<00:05,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03158   0.03633  0.003923     5.747:  71%|███████   | 22/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03158   0.03639  0.003902      5.75:  74%|███████▍  | 23/31 [00:45<00:04,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03161    0.0365  0.003892      5.76:  77%|███████▋  | 24/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03163   0.03649  0.003906     5.762:  81%|████████  | 25/31 [00:47<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03171   0.03656  0.003916     5.775:  84%|████████▍ | 26/31 [00:47<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.492      0.459      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.476       0.46       0.41      0.231
                   0        738       1052      0.461      0.572      0.537      0.257
                   1        738         44       0.37      0.267      0.194     0.0794
                   2        738       8622       0.61      0.759      0.753      0.487
                   3        738        151      0.307       0.45      0.435      0.326
                   4        738        467      0.425      0.612      0.547      0.391
                   5        738         70      0.237      0.443      0.284      0.145
                   6        738         65      0.265      0.231       0.16     0.0604
                   7        738       1619      0.515      0.631      0.583      0.243
                   8        738       2845      0.568      0.637      0.606      0.321
                   9        738          2          1          0   0.000364   0.000364

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round009_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 16:15:10.621895641 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round010 phase_round=10 ===

02 head-to-full DQA:  28%|██▊       | 9/32 [2:07:52<5:25:13, 848.41s/round, elapsed=2h07m52s, eta=5h26m46s, phase=phase1_head, round=9]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round010 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round010 client0_highway_day: pseudo scan 250/1500 images, kept 2377 boxes
round010 client0_highway_day: pseudo scan 500/1500 images, kept 4824 boxes
round010 client0_highway_day: pseudo scan 750/1500 images, kept 7181 boxes
round010 client0_highway_day: pseudo scan 1000/1500 images, kept 9558 boxes
round010 client0_highway_day: pseudo scan 1250/1500 images, kept 11898 boxes
round010 client0_highway_day: pseudo scan 1500/1500 images, kept 14297 boxes
{
  "round": "round010",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round009_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11232,
  "boxes_per_kept_image": 7.523107836570663,
  "mean_conf": 0.8082058894769036,
  "mean_stability": 0.9527348710218726,
  "mean_score": 0.7733271246997064,
  "class_counts": {
    "0": 159,
    "2": 6434,
    "3": 114,
    "4": 554,
    "5": 8,
    "7": 552,
    "8": 3411
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_client0_highway_day_stable_boxes.csv"
}
round010 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round010 client1_highway_night: pseudo scan 250/1500 images, kept 1643 boxes
round010 client1_highway_night: pseudo scan 500/1500 images, kept 3412 boxes
round010 client1_highway_night: pseudo scan 750/1500 images, kept 5184 boxes
round010 client1_highway_night: pseudo scan 1000/1500 images, kept 6843 boxes
round010 client1_highway_night: pseudo scan 1250/1500 images, kept 8575 boxes
round010 client1_highway_night: pseudo scan 1500/1500 images, kept 10240 boxes
{
  "round": "round010",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round009_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1461,
  "pseudo_boxes_kept": 8357,
  "boxes_per_kept_image": 5.720054757015743,
  "mean_conf": 0.7217741458128125,
  "mean_stability": 0.9369573809248388,
  "mean_score": 0.6804349146488853,
  "class_counts": {
    "0": 66,
    "2": 4608,
    "3": 29,
    "4": 140,
    "5": 8,
    "7": 565,
    "8": 2941
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_client1_highway_night_stable_boxes.csv"
}
round010 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round010 client2_citystreet_day: pseudo scan 250/1500 images, kept 2707 boxes
round010 client2_citystreet_day: pseudo scan 500/1500 images, kept 5451 boxes
round010 client2_citystreet_day: pseudo scan 750/1500 images, kept 8203 boxes
round010 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10965 boxes
round010 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13698 boxes
round010 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16364 boxes
{
  "round": "round010",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round009_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13811,
  "boxes_per_kept_image": 9.231951871657754,
  "mean_conf": 0.8063038475749442,
  "mean_stability": 0.9505714043736432,
  "mean_score": 0.7699648495648368,
  "class_counts": {
    "0": 1452,
    "2": 7364,
    "3": 192,
    "4": 607,
    "5": 69,
    "7": 1530,
    "8": 2597
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_client2_citystreet_day_stable_boxes.csv"
}
round010 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round010 client3_citystreet_night: pseudo scan 250/1500 images, kept 2376 boxes
round010 client3_citystreet_night: pseudo scan 500/1500 images, kept 4708 boxes
round010 client3_citystreet_night: pseudo scan 750/1500 images, kept 7019 boxes
round010 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9260 boxes
round010 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11672 boxes
round010 client3_citystreet_night: pseudo scan 1500/1500 images, kept 14001 boxes
{
  "round": "round010",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round009_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 11790,
  "boxes_per_kept_image": 7.9932203389830505,
  "mean_conf": 0.7166750807874379,
  "mean_stability": 0.9337726299645438,
  "mean_score": 0.6736107016759376,
  "class_counts": {
    "0": 554,
    "2": 6301,
    "3": 70,
    "4": 158,
    "5": 36,
    "7": 1968,
    "8": 2703
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_client3_citystreet_night_stable_boxes.csv"
}
round010 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round010 client4_residential_day: pseudo scan 250/1500 images, kept 2589 boxes
round010 client4_residential_day: pseudo scan 500/1500 images, kept 5198 boxes
round010 client4_residential_day: pseudo scan 750/1500 images, kept 7756 boxes
round010 client4_residential_day: pseudo scan 1000/1500 images, kept 10245 boxes
round010 client4_residential_day: pseudo scan 1250/1500 images, kept 12765 boxes
round010 client4_residential_day: pseudo scan 1500/1500 images, kept 15241 boxes
{
  "round": "round010",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round009_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9990,
  "boxes_per_kept_image": 6.704697986577181,
  "mean_conf": 0.8413793248874886,
  "mean_stability": 0.9587341691399958,
  "mean_score": 0.8101296713092866,
  "class_counts": {
    "0": 383,
    "2": 6859,
    "3": 64,
    "4": 305,
    "5": 48,
    "7": 545,
    "8": 1786
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_client4_residential_day_stable_boxes.csv"
}
round010 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round010 client5_residential_night: pseudo scan 250/1500 images, kept 2337 boxes
round010 client5_residential_night: pseudo scan 500/1500 images, kept 4648 boxes
round010 client5_residential_night: pseudo scan 750/1500 images, kept 6952 boxes
round010 client5_residential_night: pseudo scan 1000/1500 images, kept 9316 boxes
round010 client5_residential_night: pseudo scan 1250/1500 images, kept 11686 boxes
round010 client5_residential_night: pseudo scan 1500/1500 images, kept 14044 boxes
{
  "round": "round010",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round009_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1478,
  "pseudo_boxes_kept": 8734,
  "boxes_per_kept_image": 5.909336941813261,
  "mean_conf": 0.7902186785378662,
  "mean_stability": 0.9471994160186352,
  "mean_score": 0.7515185638499415,
  "class_counts": {
    "0": 132,
    "2": 6320,
    "3": 33,
    "4": 98,
    "5": 26,
    "7": 657,
    "8": 1468
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round010_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31204 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round010_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round010_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 10693.16it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:17:27.329436230 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:17:27.338741677 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2068       640  0.003436   0.04205  0.004609     4.008:   3%|▎         | 1/39 [00:22<14:03, 22.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003444   0.04237  0.004335     4.012:   5%|▌         | 2/39 [00:23<05:58,  9.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003475   0.04313  0.004457     4.085:   8%|▊         | 3/39 [00:23<03:23,  5.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003437   0.04321   0.00464     4.103:  10%|█         | 4/39 [00:24<02:11,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003422    0.0426  0.004673     4.055:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003415   0.04168  0.004624     3.977:  15%|█▌        | 6/39 [00:26<01:04,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003411   0.04171  0.004599     3.978:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003404   0.04204  0.004667     4.009:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640   0.00341   0.04259  0.004732     4.058:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003421    0.0429  0.004735     4.085:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640   0.00341   0.04277  0.004668     4.068:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003412   0.04259   0.00468     4.054:  31%|███       | 12/39 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003417   0.04243  0.004675     4.042:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003423   0.04261  0.004635     4.053:  36%|███▌      | 14/39 [00:31<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003414   0.04245  0.004608     4.038:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003419   0.04237   0.00462     4.033:  41%|████      | 16/39 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003419   0.04209  0.004622     4.011:  44%|████▎     | 17/39 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003422   0.04206  0.004619     4.008:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003418   0.04187  0.004626     3.993:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003421   0.04198  0.004632     4.003:  51%|█████▏    | 20/39 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003423   0.04202  0.004615     4.005:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003424   0.04191  0.004591     3.994:  56%|█████▋    | 22/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003424   0.04194  0.004563     3.994:  59%|█████▉    | 23/39 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003426   0.04191  0.004553     3.991:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003421   0.04181  0.004542     3.982:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640   0.00342    0.0418  0.004536     3.981:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.518      0.435      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]

                 all        738      14937       0.54      0.414      0.412      0.232
                   0        738       1052      0.518      0.551       0.54      0.259
                   1        738         44      0.459      0.136      0.208     0.0884
                   2        738       8622      0.694      0.732      0.754      0.483
                   3        738        151      0.503      0.417      0.433      0.328
                   4        738        467      0.482      0.587      0.543      0.389
                   5        738         70      0.283      0.414      0.277      0.145
                   6        738         65      0.254     0.0769      0.163     0.0651
                   7        738       1619      0.554      0.624      0.592      0.243
                   8        738       2845      0.654      0.603      0.609       0.32
                   9        738          2          1          0   0.000327   0.000294

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:18:52.461961193 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31205 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round010_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round010_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client1_highway_night_stable_train' images and labels...4895 found, 2908 missing, 0 empty, 0 corrupted: 100%|██████████| 7803/7803 [00:00<00:00, 12286.45it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.331176006314127
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2908 missing, 0 empty, 0 corrupted: 100%|██████████| 7803/7803 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:19:08.372634353 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:19:08.445844279 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1949       640  0.003415   0.03967  0.004492     3.806:   2%|▎         | 1/40 [00:22<14:30, 22.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2047       640  0.003455   0.04004  0.004608     3.848:   5%|▌         | 2/40 [00:23<06:12,  9.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1964       640  0.003431   0.04004  0.004335     3.824:   8%|▊         | 3/40 [00:24<03:31,  5.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1757       640  0.003433   0.03915  0.004478     3.765:  10%|█         | 4/40 [00:25<02:16,  3.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1853       640  0.003412   0.03901  0.004419     3.748:  12%|█▎        | 5/40 [00:25<01:33,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1660       640  0.003418   0.03832  0.004607     3.708:  15%|█▌        | 6/40 [00:26<01:07,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1975       640   0.00343   0.03841  0.004607     3.716:  18%|█▊        | 7/40 [00:27<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1952       640  0.003416   0.03834  0.004544     3.704:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1988       640   0.00341   0.03824  0.004531     3.694:  22%|██▎       | 9/40 [00:28<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1640       640   0.00341   0.03793  0.004499     3.667:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2136       640   0.00342   0.03819  0.004538     3.692:  28%|██▊       | 11/40 [00:29<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1793       640   0.00341   0.03797  0.004629      3.68:  30%|███       | 12/40 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1874       640  0.003414   0.03794  0.004606     3.677:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1899       640  0.003417   0.03782  0.004654     3.672:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1843       640  0.003412   0.03763   0.00465     3.656:  38%|███▊      | 15/40 [00:32<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1930       640  0.003416   0.03744  0.004622     3.638:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1878       640  0.003416    0.0373  0.004605     3.625:  42%|████▎     | 17/40 [00:33<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1911       640  0.003417    0.0371  0.004574     3.607:  45%|████▌     | 18/40 [00:34<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1708       640  0.003414    0.0368  0.004601     3.585:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2171       640  0.003419   0.03682  0.004586     3.586:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1893       640  0.003419   0.03666  0.004617     3.575:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003421   0.03659  0.004612      3.57:  55%|█████▌    | 22/40 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2026       640  0.003419   0.03657  0.004624     3.569:  57%|█████▊    | 23/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2023       640  0.003422   0.03652  0.004599     3.563:  60%|██████    | 24/40 [00:37<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2033       640  0.003425   0.03645  0.004571     3.556:  62%|██████▎   | 25/40 [00:38<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1960       640  0.003425   0.03638  0.004568      3.55:  65%|██████▌   | 26/40 [00:39<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.538      0.415      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.523      0.416      0.408       0.23
                   0        738       1052      0.553      0.537      0.532      0.255
                   1        738         44      0.451      0.136      0.202      0.091
                   2        738       8622      0.661      0.735       0.75      0.481
                   3        738        151      0.414      0.417       0.43      0.327
                   4        738        467      0.437      0.604      0.541      0.386
                   5        738         70      0.295      0.414      0.282      0.141
                   6        738         65       0.25     0.0923      0.162      0.065
                   7        738       1619      0.542      0.622      0.586      0.243
                   8        738       2845      0.628      0.605      0.599      0.311
                   9        738          2          1          0   0.000256   0.000256

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:20:33.790840233 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31206 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round010_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round010_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 15584.75it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:20:50.243596354 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:20:50.257429824 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003529   0.05179  0.004644     4.797:   3%|▎         | 1/39 [00:21<13:47, 21.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003483   0.05098  0.005026     4.759:   5%|▌         | 2/39 [00:22<05:50,  9.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003446   0.04995  0.005044     4.676:   8%|▊         | 3/39 [00:23<03:20,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003457   0.04893  0.004951     4.587:  10%|█         | 4/39 [00:24<02:10,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003453   0.04831  0.004874     4.531:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003417    0.0472  0.004836     4.436:  15%|█▌        | 6/39 [00:25<01:04,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003426   0.04692  0.004902      4.42:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003416   0.04652  0.004851     4.383:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003431   0.04651  0.004787     4.378:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003416   0.04623  0.004777     4.353:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003419   0.04613  0.004772     4.346:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003423   0.04564  0.004783     4.308:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640   0.00343   0.04549  0.004748     4.293:  33%|███▎      | 13/39 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640   0.00344    0.0455  0.004715     4.292:  36%|███▌      | 14/39 [00:30<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003441   0.04532   0.00469     4.276:  38%|███▊      | 15/39 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003432     0.045  0.004681     4.249:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003423   0.04476  0.004704     4.231:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003415   0.04469  0.004692     4.223:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003417   0.04441  0.004674       4.2:  49%|████▊     | 19/39 [00:33<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003412    0.0444  0.004664     4.198:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003404   0.04423  0.004644     4.182:  54%|█████▍    | 21/39 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003399   0.04414  0.004632     4.173:  56%|█████▋    | 22/39 [00:35<00:10,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003392   0.04402  0.004633     4.164:  59%|█████▉    | 23/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003388   0.04396  0.004622     4.158:  62%|██████▏   | 24/39 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003385   0.04385  0.004621     4.148:  64%|██████▍   | 25/39 [00:37<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003379    0.0438  0.004605     4.143:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.517      0.438       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.501      0.441      0.409      0.231
                   0        738       1052      0.566      0.543      0.541      0.255
                   1        738         44      0.468       0.22      0.186     0.0875
                   2        738       8622      0.613      0.755      0.754      0.481
                   3        738        151      0.318      0.464      0.431      0.328
                   4        738        467      0.411      0.625      0.541      0.385
                   5        738         70      0.279      0.414       0.27      0.142
                   6        738         65      0.249      0.123      0.175     0.0722
                   7        738       1619      0.526      0.639      0.588      0.242
                   8        738       2845      0.583      0.625      0.605      0.322
                   9        738          2          1          0   0.000262   0.000236

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:22:14.257882153 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31207 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round010_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round010_phase1_head_client3_citystreet_night_start.pt

self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7831 [00:00<?, ?it/s]

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client3_citystreet_night_stable_train' images and labels...4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<00:00, 10207.36it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.282926829268293
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:22:30.052739498 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:22:30.111236927 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2028       640  0.003576   0.04515  0.004585     4.265:   2%|▎         | 1/40 [00:22<14:30, 22.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1936       640  0.003617   0.04437  0.004973     4.237:   5%|▌         | 2/40 [00:23<06:09,  9.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003577   0.04483  0.004851      4.26:   8%|▊         | 3/40 [00:24<03:29,  5.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003543    0.0439  0.004929     4.189:  10%|█         | 4/40 [00:25<02:17,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003521   0.04289  0.004844       4.1:  12%|█▎        | 5/40 [00:25<01:33,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1660       640   0.00349   0.04209  0.004754     4.026:  15%|█▌        | 6/40 [00:26<01:07,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003491   0.04155  0.004667     3.977:  18%|█▊        | 7/40 [00:27<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003483   0.04166  0.004715     3.988:  20%|██        | 8/40 [00:27<00:40,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003465   0.04148  0.004687     3.971:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003462   0.04131  0.004658     3.955:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003457   0.04109   0.00459     3.931:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1754       640  0.003443   0.04068  0.004585     3.897:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003436   0.04041  0.004572     3.874:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003434   0.04034  0.004601      3.87:  35%|███▌      | 14/40 [00:31<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003426    0.0401  0.004602      3.85:  38%|███▊      | 15/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003426   0.03992  0.004596     3.835:  40%|████      | 16/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1648       640  0.003431   0.03964  0.004618     3.815:  42%|████▎     | 17/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1961       640  0.003433   0.03946  0.004642     3.803:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1761       640  0.003431   0.03912  0.004636     3.775:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003431   0.03902  0.004628     3.766:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003432   0.03888   0.00462     3.754:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1778       640  0.003432   0.03869  0.004599     3.737:  55%|█████▌    | 22/40 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003431   0.03864    0.0046     3.734:  57%|█████▊    | 23/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003426   0.03842  0.004578     3.714:  60%|██████    | 24/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1705       640  0.003425   0.03819  0.004557     3.694:  62%|██████▎   | 25/40 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640   0.00342   0.03813   0.00454     3.687:  65%|██████▌   | 26/40 [00:39<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.581        0.4      0.412      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.558      0.403      0.409      0.232
                   0        738       1052      0.606      0.511       0.53      0.255
                   1        738         44      0.547     0.0909      0.211     0.0957
                   2        738       8622      0.685      0.726      0.748      0.479
                   3        738        151      0.463      0.404      0.433      0.332
                   4        738        467      0.446        0.6      0.538      0.384
                   5        738         70      0.359      0.414      0.276      0.143
                   6        738         65      0.274     0.0584      0.161     0.0682
                   7        738       1619      0.551      0.623      0.588      0.243
                   8        738       2845      0.646        0.6      0.603      0.319
                   9        738          2          1          0    0.00023   0.000207

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 16:23:57.997529420 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31208 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round010_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round010_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 11317.24it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:24:14.478294572 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:24:14.504029160 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2210       640  0.003453   0.05196   0.00476     4.814:   3%|▎         | 1/39 [00:22<14:27, 22.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2055       640  0.003413   0.05073  0.005172     4.745:   5%|▌         | 2/39 [00:23<06:06,  9.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1757       640  0.003351   0.04866  0.005073     4.566:   8%|▊         | 3/39 [00:24<03:27,  5.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2010       640  0.003348    0.0481  0.005001     4.516:  10%|█         | 4/39 [00:25<02:14,  3.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2152       640  0.003351   0.04715  0.004981     4.438:  13%|█▎        | 5/39 [00:26<01:31,  2.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1679       640  0.003344   0.04558  0.005064     4.319:  15%|█▌        | 6/39 [00:26<01:06,  2.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2053       640  0.003366    0.0453  0.005044     4.297:  18%|█▊        | 7/39 [00:27<00:50,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2113       640  0.003374   0.04504  0.004919     4.267:  21%|██        | 8/39 [00:28<00:40,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2197       640  0.003373   0.04519  0.004867     4.275:  23%|██▎       | 9/39 [00:28<00:32,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1884       640  0.003378   0.04515  0.004844      4.27:  26%|██▌       | 10/39 [00:29<00:27,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2162       640  0.003388    0.0451  0.004821     4.265:  28%|██▊       | 11/39 [00:30<00:24,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2149       640  0.003406   0.04504  0.004872     4.266:  31%|███       | 12/39 [00:30<00:21,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2024       640  0.003411   0.04501   0.00487     4.263:  33%|███▎      | 13/39 [00:31<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003417    0.0448  0.004872     4.247:  36%|███▌      | 14/39 [00:32<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1911       640  0.003423    0.0445  0.004888     4.225:  38%|███▊      | 15/39 [00:32<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1948       640  0.003418   0.04417   0.00488     4.197:  41%|████      | 16/39 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1868       640  0.003417   0.04406  0.004844     4.186:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2008       640  0.003412   0.04402  0.004802     4.179:  46%|████▌     | 18/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1723       640  0.003414   0.04378  0.004802      4.16:  49%|████▊     | 19/39 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2065       640  0.003404   0.04375  0.004778     4.154:  51%|█████▏    | 20/39 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1821       640  0.003399   0.04362  0.004746     4.141:  54%|█████▍    | 21/39 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1987       640  0.003396   0.04359  0.004763      4.14:  56%|█████▋    | 22/39 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1940       640  0.003396   0.04358  0.004777      4.14:  59%|█████▉    | 23/39 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1876       640   0.00339   0.04344  0.004771     4.128:  62%|██████▏   | 24/39 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1905       640  0.003393   0.04334  0.004762     4.119:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1975       640  0.003392    0.0432  0.004737     4.107:  67%|██████▋   | 26/39 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.517       0.44      0.414      0.233
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.499      0.441      0.411      0.233
                   0        738       1052       0.49      0.564      0.542      0.258
                   1        738         44      0.496       0.25      0.206     0.0917
                   2        738       8622      0.649      0.743      0.751      0.479
                   3        738        151       0.34       0.45      0.439      0.332
                   4        738        467      0.422      0.617      0.544       0.39
                   5        738         70      0.271      0.414      0.271      0.144
                   6        738         65      0.199      0.115      0.168     0.0675
                   7        738       1619      0.523      0.636      0.586      0.243
                   8        738       2845        0.6      0.625      0.606      0.324
                   9        738          2          1          0   0.000251   0.000226

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:25:39.780635308 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31209 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round010_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round010_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client5_residential_night_stable_train' images and labels...:   0%|          | 0/7837 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client5_residential_night_stable_train' images and labels...4885 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<00:00, 13678.80it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.278118609406953
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round010_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2952 missing, 0 empty, 0 corrupted: 100%|██████████| 7837/7837 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:25:55.477445684 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:25:55.482210862 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1792       640  0.003368    0.0423  0.004813     4.038:   2%|▎         | 1/40 [00:21<13:51, 21.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640  0.003422   0.04185  0.004619     3.991:   5%|▌         | 2/40 [00:22<05:52,  9.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003425   0.04213  0.004629     4.014:   8%|▊         | 3/40 [00:22<03:20,  5.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003405   0.04216  0.004535     4.008:  10%|█         | 4/40 [00:23<02:09,  3.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003404   0.04151  0.004544     3.956:  12%|█▎        | 5/40 [00:24<01:28,  2.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003411     0.041  0.004597     3.921:  15%|█▌        | 6/40 [00:25<01:04,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003411     0.041  0.004635     3.924:  18%|█▊        | 7/40 [00:25<00:48,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1892       640  0.003417   0.04083  0.004661     3.913:  20%|██        | 8/40 [00:26<00:38,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1793       640  0.003417   0.04045  0.004649     3.881:  22%|██▎       | 9/40 [00:26<00:31,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003417      0.04    0.0046     3.841:  25%|██▌       | 10/40 [00:27<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2085       640   0.00343   0.04002  0.004679      3.85:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1959       640  0.003428   0.03968  0.004604     3.817:  30%|███       | 12/40 [00:28<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003412   0.03912  0.004647     3.774:  32%|███▎      | 13/40 [00:29<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1999       640  0.003414   0.03897  0.004677     3.765:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003412   0.03878  0.004676      3.75:  38%|███▊      | 15/40 [00:30<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1830       640  0.003413   0.03853   0.00467     3.729:  40%|████      | 16/40 [00:31<00:16,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2059       640  0.003418   0.03853  0.004728     3.734:  42%|████▎     | 17/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003423   0.03844  0.004731     3.727:  45%|████▌     | 18/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1498       640  0.003429   0.03801  0.004714     3.692:  48%|████▊     | 19/40 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003431   0.03786  0.004704      3.68:  50%|█████     | 20/40 [00:33<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003429   0.03769  0.004709     3.666:  52%|█████▎    | 21/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003432   0.03761  0.004715     3.661:  55%|█████▌    | 22/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003432   0.03758  0.004732     3.659:  57%|█████▊    | 23/40 [00:35<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003434   0.03759  0.004704     3.658:  60%|██████    | 24/40 [00:36<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2114       640  0.003435   0.03762  0.004705     3.661:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1728       640  0.003436   0.03749  0.004725     3.652:  65%|██████▌   | 26/40 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.553      0.406      0.411      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.541      0.408      0.409      0.233
                   0        738       1052       0.58      0.521       0.53      0.256
                   1        738         44      0.484      0.107      0.212      0.101
                   2        738       8622       0.67      0.727      0.746      0.477
                   3        738        151      0.484      0.411      0.429       0.33
                   4        738        467      0.458      0.587      0.542       0.39
                   5        738         70      0.321      0.414      0.273       0.14
                   6        738         65      0.247     0.0615      0.167     0.0663
                   7        738       1619      0.552      0.627      0.589      0.243
                   8        738       2845      0.611       0.62      0.606      0.321
                   9        738          2          1          0   0.000228   0.000205

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:27:20.445789337 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31210 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round010_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round010_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:27:37.458664295 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:27:37.549585261 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640    0.0313   0.03741  0.003989     5.815:   3%|▎         | 1/31 [00:31<15:57, 31.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03192   0.03817  0.004189     5.942:   6%|▋         | 2/31 [00:32<06:34, 13.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640    0.0314   0.03711  0.004118     5.811:  10%|▉         | 3/31 [00:33<03:37,  7.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03102   0.03582  0.003927     5.661:  13%|█▎        | 4/31 [00:34<02:15,  5.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03101   0.03597  0.003955     5.674:  16%|█▌        | 5/31 [00:34<01:28,  3.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03117   0.03592  0.003996     5.687:  19%|█▉        | 6/31 [00:35<01:01,  2.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03125   0.03569   0.00405     5.679:  23%|██▎       | 7/31 [00:36<00:43,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03118   0.03576  0.004058      5.68:  26%|██▌       | 8/31 [00:36<00:32,  1.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03125   0.03568  0.003968     5.672:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03125   0.03579  0.003943     5.679:  32%|███▏      | 10/31 [00:37<00:20,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03122   0.03584  0.003965     5.682:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03114   0.03558  0.003963     5.654:  39%|███▊      | 12/31 [00:38<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03111    0.0356   0.00391     5.649:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03114   0.03548  0.003876     5.639:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03116   0.03541  0.003925      5.64:  48%|████▊     | 15/31 [00:40<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03117   0.03531  0.003922     5.632:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03122   0.03536    0.0039     5.638:  55%|█████▍    | 17/31 [00:41<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640    0.0313   0.03548  0.003872     5.652:  58%|█████▊    | 18/31 [00:42<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03125   0.03538  0.003845     5.638:  61%|██████▏   | 19/31 [00:42<00:07,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03126    0.0356  0.003842     5.657:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03131   0.03567  0.003862     5.667:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03133   0.03579  0.003836     5.676:  71%|███████   | 22/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03133   0.03585  0.003816     5.679:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03136   0.03596  0.003806     5.691:  77%|███████▋  | 24/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03139   0.03596   0.00382     5.693:  81%|████████  | 25/31 [00:46<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03146   0.03604   0.00383     5.706:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.498      0.459      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.484      0.461       0.41      0.231
                   0        738       1052      0.471      0.572      0.535      0.257
                   1        738         44      0.398      0.271      0.198     0.0817
                   2        738       8622      0.617      0.757      0.752      0.487
                   3        738        151      0.315      0.457      0.435      0.326
                   4        738        467      0.434      0.617      0.544       0.39
                   5        738         70      0.246      0.443      0.288      0.146
                   6        738         65      0.269      0.227      0.161     0.0634
                   7        738       1619      0.517      0.628      0.583      0.243
                   8        738       2845       0.57      0.635      0.603      0.319
                   9        738          2          1          0    0.00037   0.000333

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round010_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 16:29:15.778641752 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round011 phase_round=11 ===

02 head-to-full DQA:  31%|███▏      | 10/32 [2:21:56<5:10:40, 847.28s/round, elapsed=2h21m56s, eta=5h12m17s, phase=phase1_head, round=10]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round011 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round011 client0_highway_day: pseudo scan 250/1500 images, kept 2374 boxes
round011 client0_highway_day: pseudo scan 500/1500 images, kept 4824 boxes
round011 client0_highway_day: pseudo scan 750/1500 images, kept 7182 boxes
round011 client0_highway_day: pseudo scan 1000/1500 images, kept 9567 boxes
round011 client0_highway_day: pseudo scan 1250/1500 images, kept 11909 boxes
round011 client0_highway_day: pseudo scan 1500/1500 images, kept 14309 boxes
{
  "round": "round011",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round010_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11261,
  "boxes_per_kept_image": 7.542531815137307,
  "mean_conf": 0.809378453635818,
  "mean_stability": 0.9521012646924771,
  "mean_score": 0.7739798957952062,
  "class_counts": {
    "0": 154,
    "2": 6440,
    "3": 114,
    "4": 568,
    "5": 6,
    "7": 558,
    "8": 3421
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_client0_highway_day_stable_boxes.csv"
}
round011 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round011 client1_highway_night: pseudo scan 250/1500 images, kept 1635 boxes
round011 client1_highway_night: pseudo scan 500/1500 images, kept 3387 boxes
round011 client1_highway_night: pseudo scan 750/1500 images, kept 5157 boxes
round011 client1_highway_night: pseudo scan 1000/1500 images, kept 6806 boxes
round011 client1_highway_night: pseudo scan 1250/1500 images, kept 8518 boxes
round011 client1_highway_night: pseudo scan 1500/1500 images, kept 10178 boxes
{
  "round": "round011",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round010_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1461,
  "pseudo_boxes_kept": 8348,
  "boxes_per_kept_image": 5.713894592744696,
  "mean_conf": 0.7234005527735956,
  "mean_stability": 0.9361154216939203,
  "mean_score": 0.6812842041434376,
  "class_counts": {
    "0": 65,
    "2": 4581,
    "3": 29,
    "4": 143,
    "5": 8,
    "7": 577,
    "8": 2945
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_client1_highway_night_stable_boxes.csv"
}
round011 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round011 client2_citystreet_day: pseudo scan 250/1500 images, kept 2703 boxes
round011 client2_citystreet_day: pseudo scan 500/1500 images, kept 5450 boxes
round011 client2_citystreet_day: pseudo scan 750/1500 images, kept 8198 boxes
round011 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10960 boxes
round011 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13690 boxes
round011 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16359 boxes
{
  "round": "round011",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round010_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13812,
  "boxes_per_kept_image": 9.232620320855615,
  "mean_conf": 0.8087815310414411,
  "mean_stability": 0.9499744923692007,
  "mean_score": 0.7718639167414576,
  "class_counts": {
    "0": 1449,
    "2": 7362,
    "3": 198,
    "4": 604,
    "5": 69,
    "7": 1520,
    "8": 2610
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_client2_citystreet_day_stable_boxes.csv"
}
round011 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round011 client3_citystreet_night: pseudo scan 250/1500 images, kept 2368 boxes
round011 client3_citystreet_night: pseudo scan 500/1500 images, kept 4687 boxes
round011 client3_citystreet_night: pseudo scan 750/1500 images, kept 6994 boxes
round011 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9235 boxes
round011 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11647 boxes
round011 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13969 boxes
{
  "round": "round011",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round010_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 11798,
  "boxes_per_kept_image": 7.99864406779661,
  "mean_conf": 0.7182849032542609,
  "mean_stability": 0.9325369396973998,
  "mean_score": 0.6742811538262903,
  "class_counts": {
    "0": 545,
    "2": 6287,
    "3": 69,
    "4": 154,
    "5": 37,
    "7": 2009,
    "8": 2697
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_client3_citystreet_night_stable_boxes.csv"
}
round011 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round011 client4_residential_day: pseudo scan 250/1500 images, kept 2587 boxes
round011 client4_residential_day: pseudo scan 500/1500 images, kept 5198 boxes
round011 client4_residential_day: pseudo scan 750/1500 images, kept 7753 boxes
round011 client4_residential_day: pseudo scan 1000/1500 images, kept 10234 boxes
round011 client4_residential_day: pseudo scan 1250/1500 images, kept 12758 boxes
round011 client4_residential_day: pseudo scan 1500/1500 images, kept 15237 boxes
{
  "round": "round011",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round010_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 9992,
  "boxes_per_kept_image": 6.701542588866532,
  "mean_conf": 0.8433100362125638,
  "mean_stability": 0.9583926131908563,
  "mean_score": 0.8117010421470241,
  "class_counts": {
    "0": 382,
    "2": 6857,
    "3": 65,
    "4": 311,
    "5": 47,
    "7": 539,
    "8": 1791
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_client4_residential_day_stable_boxes.csv"
}
round011 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round011 client5_residential_night: pseudo scan 250/1500 images, kept 2331 boxes
round011 client5_residential_night: pseudo scan 500/1500 images, kept 4625 boxes
round011 client5_residential_night: pseudo scan 750/1500 images, kept 6921 boxes
round011 client5_residential_night: pseudo scan 1000/1500 images, kept 9258 boxes
round011 client5_residential_night: pseudo scan 1250/1500 images, kept 11619 boxes
round011 client5_residential_night: pseudo scan 1500/1500 images, kept 13969 boxes
{
  "round": "round011",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round010_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 8712,
  "boxes_per_kept_image": 5.906440677966102,
  "mean_conf": 0.7913630695361901,
  "mean_stability": 0.9467220967575648,
  "mean_score": 0.7522074024807017,
  "class_counts": {
    "0": 130,
    "2": 6287,
    "3": 33,
    "4": 98,
    "5": 26,
    "7": 667,
    "8": 1471
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round011_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31211 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round011_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round011_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 12534.15it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:31:32.386444995 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:31:32.395294443 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2068       640  0.003437    0.0422  0.004588     4.018:   3%|▎         | 1/39 [00:21<13:26, 21.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2014       640  0.003446   0.04252  0.004308     4.022:   5%|▌         | 2/39 [00:22<05:43,  9.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2013       640  0.003477   0.04325   0.00443     4.092:   8%|▊         | 3/39 [00:22<03:15,  5.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2081       640  0.003439   0.04332  0.004617      4.11:  10%|█         | 4/39 [00:23<02:07,  3.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1852       640  0.003423    0.0427  0.004651     4.062:  13%|█▎        | 5/39 [00:24<01:27,  2.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1711       640  0.003416   0.04177    0.0046     3.983:  15%|█▌        | 6/39 [00:25<01:03,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1997       640  0.003412    0.0418  0.004577     3.983:  18%|█▊        | 7/39 [00:25<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2084       640  0.003406   0.04212  0.004647     4.014:  21%|██        | 8/39 [00:26<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2135       640  0.003411   0.04266  0.004712     4.063:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2169       640  0.003423   0.04297  0.004714     4.089:  26%|██▌       | 10/39 [00:27<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2061       640  0.003411   0.04283  0.004647     4.071:  28%|██▊       | 11/39 [00:28<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1868       640  0.003413   0.04264  0.004657     4.057:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2072       640  0.003418   0.04248  0.004652     4.044:  33%|███▎      | 13/39 [00:29<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2233       640  0.003424   0.04266  0.004612     4.056:  36%|███▌      | 14/39 [00:30<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1954       640  0.003415    0.0425  0.004585      4.04:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2042       640   0.00342   0.04242  0.004598     4.035:  41%|████      | 16/39 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1766       640   0.00342   0.04213    0.0046     4.012:  44%|████▎     | 17/39 [00:32<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1986       640  0.003423    0.0421  0.004597     4.009:  46%|████▌     | 18/39 [00:32<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1720       640  0.003419   0.04191  0.004604     3.994:  49%|████▊     | 19/39 [00:33<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2386       640  0.003422   0.04202   0.00461     4.004:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2046       640  0.003424   0.04205  0.004592     4.006:  54%|█████▍    | 21/39 [00:34<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1853       640  0.003424   0.04194  0.004568     3.994:  56%|█████▋    | 22/39 [00:35<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2251       640  0.003425   0.04197   0.00454     3.995:  59%|█████▉    | 23/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2088       640  0.003426   0.04193   0.00453     3.991:  62%|██████▏   | 24/39 [00:36<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2046       640  0.003422   0.04183  0.004519     3.982:  64%|██████▍   | 25/39 [00:37<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2154       640   0.00342   0.04182  0.004512     3.981:  67%|██████▋   | 26/39 [00:37<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.557      0.413      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.543      0.414      0.412      0.232
                   0        738       1052      0.522       0.55       0.54      0.259
                   1        738         44       0.46      0.136      0.211     0.0849
                   2        738       8622      0.696      0.733      0.754      0.483
                   3        738        151      0.517      0.417      0.432      0.327
                   4        738        467       0.48      0.585      0.542       0.39
                   5        738         70       0.29      0.414      0.275      0.146
                   6        738         65      0.253     0.0769      0.166     0.0664
                   7        738       1619      0.557      0.626      0.593      0.244
                   8        738       2845      0.653      0.604       0.61       0.32
                   9        738          2          1          0   0.000326   0.000293

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client0_highway_day

1 epochs completed in 0.023 hours.
Destroying process group...
[rank0]:[W507 16:32:54.578959242 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31212 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round011_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round011_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client1_highway_night_stable_train' images and labels...4895 found, 2908 missing, 0 empty, 0 corrupted: 100%|██████████| 7803/7803 [00:00<00:00, 13749.06it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.331176006314127
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2908 missing, 0 empty, 0 corrupted: 100%|██████████| 7803/7803 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:33:10.531500633 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:33:10.573033913 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1949       640  0.003415   0.03977  0.004481     3.813:   2%|▎         | 1/40 [00:22<14:34, 22.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640  0.003456   0.04011  0.004597     3.853:   5%|▌         | 2/40 [00:23<06:10,  9.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003431   0.04009  0.004324     3.828:   8%|▊         | 3/40 [00:24<03:31,  5.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1757       640  0.003434    0.0392  0.004464     3.768:  10%|█         | 4/40 [00:25<02:16,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003412   0.03904    0.0044     3.748:  12%|█▎        | 5/40 [00:25<01:32,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1660       640  0.003418   0.03835   0.00459     3.709:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640   0.00343   0.03843   0.00459     3.716:  18%|█▊        | 7/40 [00:27<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1952       640  0.003417   0.03834  0.004529     3.703:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003411   0.03824  0.004515     3.693:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1640       640  0.003411   0.03791  0.004481     3.664:  25%|██▌       | 10/40 [00:29<00:28,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2136       640  0.003421   0.03816  0.004519     3.688:  28%|██▊       | 11/40 [00:29<00:25,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1793       640  0.003411   0.03793   0.00461     3.676:  30%|███       | 12/40 [00:30<00:22,  1.22it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003415    0.0379  0.004585     3.672:  32%|███▎      | 13/40 [00:31<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640  0.003418   0.03777  0.004634     3.666:  35%|███▌      | 14/40 [00:31<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003413   0.03758  0.004629      3.65:  38%|███▊      | 15/40 [00:32<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003417   0.03738  0.004601     3.632:  40%|████      | 16/40 [00:33<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1878       640  0.003417   0.03723  0.004583     3.618:  42%|████▎     | 17/40 [00:33<00:15,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003417   0.03703  0.004553       3.6:  45%|████▌     | 18/40 [00:34<00:15,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1708       640  0.003415   0.03672   0.00458     3.577:  48%|████▊     | 19/40 [00:35<00:14,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2171       640   0.00342   0.03675  0.004565     3.579:  50%|█████     | 20/40 [00:35<00:13,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640   0.00342   0.03658  0.004596     3.567:  52%|█████▎    | 21/40 [00:36<00:12,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003422   0.03651   0.00459     3.562:  55%|█████▌    | 22/40 [00:37<00:12,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2026       640   0.00342   0.03649  0.004603     3.561:  57%|█████▊    | 23/40 [00:37<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003422   0.03643  0.004579     3.555:  60%|██████    | 24/40 [00:38<00:10,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2033       640  0.003425   0.03636   0.00455     3.547:  62%|██████▎   | 25/40 [00:39<00:10,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003426    0.0363  0.004547     3.542:  65%|██████▌   | 26/40 [00:39<00:09,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.522      0.425       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.508      0.427      0.408       0.23
                   0        738       1052      0.536      0.544      0.533      0.256
                   1        738         44      0.444      0.182      0.202     0.0948
                   2        738       8622      0.649       0.74      0.751      0.481
                   3        738        151      0.381       0.43      0.428      0.328
                   4        738        467      0.429      0.612      0.537      0.383
                   5        738         70      0.288      0.429      0.284      0.145
                   6        738         65      0.206     0.0923      0.157     0.0633
                   7        738       1619      0.534      0.633      0.585      0.243
                   8        738       2845       0.61       0.61      0.598      0.311
                   9        738          2          1          0    0.00026    0.00026

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:34:36.509646593 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31213 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round011_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round011_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 13680.37it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:34:52.631502348 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:34:52.687501983 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003528   0.05199  0.004605     4.809:   3%|▎         | 1/39 [00:21<13:52, 21.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003482   0.05113  0.004986     4.768:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003445   0.05008  0.005008     4.683:   8%|▊         | 3/39 [00:23<03:21,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003456   0.04903  0.004922     4.593:  10%|█         | 4/39 [00:24<02:09,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003453   0.04842  0.004849     4.538:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003417    0.0473  0.004812     4.442:  15%|█▌        | 6/39 [00:25<01:03,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003427     0.047  0.004878     4.425:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003417    0.0466  0.004828     4.387:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003431   0.04658  0.004762     4.382:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003416   0.04629  0.004752     4.357:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640   0.00342   0.04619  0.004747     4.348:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003424   0.04569  0.004759      4.31:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003431   0.04554  0.004724     4.295:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640   0.00344   0.04554   0.00469     4.294:  36%|███▌      | 14/39 [00:30<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003441   0.04536  0.004665     4.277:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003432   0.04504  0.004656      4.25:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003423    0.0448   0.00468     4.232:  44%|████▎     | 17/39 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003416   0.04472  0.004667     4.224:  46%|████▌     | 18/39 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003417   0.04444  0.004649       4.2:  49%|████▊     | 19/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003412   0.04443  0.004639     4.198:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003404   0.04425   0.00462     4.182:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003399   0.04416  0.004607     4.173:  56%|█████▋    | 22/39 [00:35<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003392   0.04405  0.004609     4.164:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003388   0.04398  0.004598     4.157:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003385   0.04387  0.004596     4.148:  64%|██████▍   | 25/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003379   0.04383  0.004581     4.143:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.512      0.442      0.409      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]

                 all        738      14937       0.53      0.419      0.408      0.231
                   0        738       1052      0.619      0.515      0.537      0.254
                   1        738         44      0.398      0.136      0.188      0.089
                   2        738       8622      0.648      0.745      0.755      0.481
                   3        738        151      0.363      0.437      0.431      0.325
                   4        738        467      0.433      0.612      0.538      0.384
                   5        738         70      0.345      0.414      0.271      0.143
                   6        738         65      0.317     0.0923       0.17     0.0708
                   7        738       1619      0.563      0.623      0.586      0.242
                   8        738       2845      0.616       0.61      0.604      0.321
                   9        738          2          1          0   0.000261   0.000235

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:36:17.767404839 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31214 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round011_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round011_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client3_citystreet_night_stable_train' images and labels...4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<00:00, 9309.07it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.282926829268293
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:36:34.474603051 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:36:34.478012417 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2028       640  0.003574   0.04522  0.004584      4.27:   2%|▎         | 1/40 [00:21<14:11, 21.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1936       640  0.003615   0.04442  0.004957      4.24:   5%|▌         | 2/40 [00:22<06:01,  9.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003577   0.04488  0.004832     4.263:   8%|▊         | 3/40 [00:23<03:25,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003543   0.04395  0.004914     4.192:  10%|█         | 4/40 [00:24<02:12,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003521   0.04292  0.004829     4.102:  12%|█▎        | 5/40 [00:25<01:31,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1660       640   0.00349    0.0421  0.004742     4.026:  15%|█▌        | 6/40 [00:25<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003491   0.04156  0.004653     3.976:  18%|█▊        | 7/40 [00:26<00:50,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003483   0.04166    0.0047     3.987:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003465   0.04147  0.004669     3.969:  22%|██▎       | 9/40 [00:27<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003463   0.04128   0.00464     3.951:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003457   0.04105  0.004572     3.926:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1754       640  0.003443   0.04063  0.004567     3.891:  30%|███       | 12/40 [00:29<00:21,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003436   0.04035  0.004553     3.867:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003434   0.04027  0.004582     3.863:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003426   0.04002  0.004581     3.842:  38%|███▊      | 15/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003427   0.03983  0.004575     3.827:  40%|████      | 16/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1648       640  0.003432   0.03955  0.004598     3.806:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1961       640  0.003433   0.03936  0.004621     3.793:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1761       640  0.003431   0.03902  0.004616     3.765:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003432   0.03892  0.004607     3.756:  50%|█████     | 20/40 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003433   0.03877  0.004599     3.745:  52%|█████▎    | 21/40 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1778       640  0.003433   0.03858  0.004578     3.727:  55%|█████▌    | 22/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003432   0.03854  0.004579     3.724:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003426   0.03832  0.004557     3.704:  60%|██████    | 24/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1705       640  0.003426   0.03808  0.004536     3.684:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003421   0.03802   0.00452     3.677:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.575      0.401      0.411      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.575      0.397      0.409      0.232
                   0        738       1052      0.623      0.507       0.53      0.255
                   1        738         44      0.663     0.0896      0.212     0.0946
                   2        738       8622      0.696      0.721      0.747      0.479
                   3        738        151       0.51      0.404      0.432      0.333
                   4        738        467      0.454      0.593      0.537      0.383
                   5        738         70      0.363        0.4      0.276      0.147
                   6        738         65      0.233     0.0462      0.162      0.067
                   7        738       1619      0.558      0.616      0.587      0.243
                   8        738       2845      0.655      0.596      0.602      0.319
                   9        738          2          1          0   0.000236   0.000212

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 16:38:02.699346520 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31215 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round011_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round011_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 11233.24it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:38:19.776556717 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:38:19.800800814 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2084       640  0.003428   0.05082  0.004072     4.666:   3%|▎         | 1/39 [00:22<14:25, 22.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2054       640   0.00346   0.05032  0.004874     4.692:   5%|▌         | 2/39 [00:23<06:07,  9.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1903       640  0.003402   0.04819  0.004812     4.513:   8%|▊         | 3/39 [00:24<03:27,  5.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1904       640  0.003414   0.04724  0.004948     4.448:  10%|█         | 4/39 [00:25<02:13,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1942       640   0.00339   0.04597   0.00492     4.342:  13%|█▎        | 5/39 [00:25<01:30,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1735       640  0.003401   0.04465  0.004999     4.244:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1985       640  0.003415   0.04439  0.004995     4.224:  18%|█▊        | 7/39 [00:27<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1947       640  0.003425   0.04412  0.004922     4.197:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2072       640  0.003418   0.04408  0.004986     4.199:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1893       640  0.003428   0.04409  0.004958     4.198:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2139       640  0.003429   0.04407  0.004945     4.196:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2120       640  0.003427   0.04401  0.004913     4.188:  31%|███       | 12/39 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2089       640  0.003437   0.04406  0.004895     4.192:  33%|███▎      | 13/39 [00:31<00:19,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2027       640  0.003444   0.04401  0.004874     4.186:  36%|███▌      | 14/39 [00:31<00:18,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1824       640  0.003449    0.0437  0.004867     4.161:  38%|███▊      | 15/39 [00:32<00:17,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1768       640  0.003447   0.04343  0.004856     4.139:  41%|████      | 16/39 [00:33<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1747       640  0.003435   0.04321  0.004824     4.118:  44%|████▎     | 17/39 [00:33<00:15,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2019       640  0.003431   0.04317   0.00479     4.111:  46%|████▌     | 18/39 [00:34<00:14,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1602       640  0.003424   0.04288  0.004784     4.087:  49%|████▊     | 19/39 [00:35<00:13,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2209       640  0.003425   0.04286  0.004768     4.084:  51%|█████▏    | 20/39 [00:35<00:12,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1896       640  0.003424   0.04282   0.00474     4.079:  54%|█████▍    | 21/39 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1996       640  0.003422   0.04281  0.004739     4.078:  56%|█████▋    | 22/39 [00:37<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2001       640  0.003424   0.04284  0.004765     4.082:  59%|█████▉    | 23/39 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640  0.003421   0.04275  0.004759     4.074:  62%|██████▏   | 24/39 [00:38<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2030       640  0.003421   0.04274  0.004759     4.074:  64%|██████▍   | 25/39 [00:39<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1772       640  0.003419   0.04255  0.004746     4.057:  67%|██████▋   | 26/39 [00:39<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.512      0.442      0.415      0.233
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937       0.49      0.444      0.412      0.233
                   0        738       1052      0.477      0.568      0.539      0.256
                   1        738         44      0.477       0.25      0.201     0.0923
                   2        738       8622      0.643      0.745      0.751      0.479
                   3        738        151      0.313       0.45      0.442      0.337
                   4        738        467      0.409      0.627      0.547      0.392
                   5        738         70      0.277      0.414       0.28      0.144
                   6        738         65      0.199      0.123      0.169     0.0687
                   7        738       1619      0.515      0.632      0.583      0.242
                   8        738       2845      0.594      0.627      0.606      0.322
                   9        738          2          1          0   0.000257   0.000231

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client4_residential_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 16:39:47.728567281 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31216 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round011_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round011_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client5_residential_night_stable_train' images and labels...4885 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<00:00, 9722.33it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round011_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:40:03.049213295 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:40:04.395071911 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1930       640  0.003452   0.04392  0.004446     4.145:   2%|▎         | 1/40 [00:22<14:42, 22.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1942       640  0.003418   0.04269   0.00444     4.044:   5%|▌         | 2/40 [00:23<06:21, 10.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2018       640  0.003366   0.04246  0.004339     4.013:   8%|▊         | 3/40 [00:24<03:38,  5.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1939       640   0.00336   0.04191  0.004286     3.964:  10%|█         | 4/40 [00:25<02:21,  3.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1800       640  0.003345     0.041  0.004341     3.895:  12%|█▎        | 5/40 [00:26<01:36,  2.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1688       640  0.003339    0.0401  0.004362     3.824:  15%|█▌        | 6/40 [00:27<01:09,  2.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1820       640  0.003343   0.03963  0.004418     3.791:  18%|█▊        | 7/40 [00:27<00:52,  1.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1863       640  0.003343   0.03931  0.004427     3.767:  20%|██        | 8/40 [00:28<00:41,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1826       640  0.003355   0.03914  0.004383      3.75:  22%|██▎       | 9/40 [00:29<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1944       640  0.003377   0.03892  0.004463     3.741:  25%|██▌       | 10/40 [00:29<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2136       640  0.003381   0.03897  0.004469     3.746:  28%|██▊       | 11/40 [00:30<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1972       640  0.003373   0.03901  0.004504     3.751:  30%|███       | 12/40 [00:30<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1874       640  0.003379   0.03882  0.004548     3.739:  32%|███▎      | 13/40 [00:31<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2191       640  0.003384   0.03879  0.004553     3.738:  35%|███▌      | 14/40 [00:32<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1526       640  0.003382   0.03828  0.004531     3.696:  38%|███▊      | 15/40 [00:32<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1526       640  0.003374   0.03772  0.004485     3.646:  40%|████      | 16/40 [00:33<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1794       640  0.003385    0.0376  0.004574     3.645:  42%|████▎     | 17/40 [00:34<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1839       640  0.003389   0.03741  0.004611     3.633:  45%|████▌     | 18/40 [00:34<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1633       640  0.003396   0.03706  0.004649     3.608:  48%|████▊     | 19/40 [00:35<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1869       640  0.003397   0.03696  0.004636       3.6:  50%|█████     | 20/40 [00:36<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1934       640  0.003398   0.03683  0.004642     3.589:  52%|█████▎    | 21/40 [00:36<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1947       640    0.0034   0.03686  0.004626     3.591:  55%|█████▌    | 22/40 [00:37<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2066       640  0.003405   0.03688  0.004649     3.595:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1839       640  0.003403   0.03679  0.004658     3.588:  60%|██████    | 24/40 [00:38<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2008       640  0.003406   0.03671  0.004673     3.583:  62%|██████▎   | 25/40 [00:39<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1758       640  0.003402   0.03659  0.004661     3.572:  65%|██████▌   | 26/40 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.504      0.441      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.546      0.404       0.41      0.231
                   0        738       1052      0.588      0.519      0.533      0.255
                   1        738         44      0.452      0.112      0.221     0.0986
                   2        738       8622      0.684      0.721      0.746      0.477
                   3        738        151      0.477      0.411      0.427      0.328
                   4        738        467      0.455      0.589      0.538      0.385
                   5        738         70      0.349      0.414       0.28      0.143
                   6        738         65       0.25     0.0615      0.159     0.0618
                   7        738       1619      0.571      0.614      0.589      0.244
                   8        738       2845       0.64      0.602      0.604       0.32
                   9        738          2          1          0   0.000189    0.00017

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:41:30.255459608 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31217 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round011_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round011_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:41:46.777628794 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:41:46.778714236 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03102   0.03684  0.003897     5.741:   3%|▎         | 1/31 [00:32<16:04, 32.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03165   0.03759  0.004099     5.867:   6%|▋         | 2/31 [00:32<06:37, 13.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03115   0.03654  0.004033     5.738:  10%|▉         | 3/31 [00:33<03:37,  7.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03084    0.0354  0.003858     5.608:  13%|█▎        | 4/31 [00:34<02:15,  5.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03081   0.03552  0.003881     5.617:  16%|█▌        | 5/31 [00:34<01:28,  3.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03095   0.03546  0.003918     5.626:  19%|█▉        | 6/31 [00:35<01:01,  2.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.03103    0.0352  0.003969     5.616:  23%|██▎       | 7/31 [00:36<00:44,  1.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03095   0.03527  0.003973     5.615:  26%|██▌       | 8/31 [00:36<00:33,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03102   0.03519  0.003885     5.607:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03101   0.03529   0.00386     5.613:  32%|███▏      | 10/31 [00:37<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03098   0.03533  0.003881     5.616:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640    0.0309   0.03507  0.003879     5.588:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03087   0.03508  0.003827     5.582:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03089   0.03496  0.003794     5.572:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03092   0.03489  0.003843     5.572:  48%|████▊     | 15/31 [00:40<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03093   0.03479  0.003839     5.564:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03097   0.03483  0.003818     5.569:  55%|█████▍    | 17/31 [00:41<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.03105   0.03495   0.00379     5.583:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03101   0.03485  0.003764      5.57:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03102   0.03508  0.003761     5.589:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03106   0.03515  0.003781     5.599:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03109   0.03526  0.003756     5.608:  71%|███████   | 22/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03109   0.03533  0.003734     5.612:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03112   0.03545  0.003725     5.624:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03115   0.03544  0.003738     5.626:  81%|████████  | 25/31 [00:46<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03122   0.03553  0.003748      5.64:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.506      0.447      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.489       0.45       0.41      0.231
                   0        738       1052       0.48      0.563      0.531      0.257
                   1        738         44      0.388       0.25      0.196      0.084
                   2        738       8622      0.629      0.752      0.751      0.486
                   3        738        151       0.33      0.437      0.433      0.324
                   4        738        467       0.44       0.61      0.544      0.388
                   5        738         70      0.251      0.429      0.295      0.143
                   6        738         65      0.265        0.2      0.167     0.0643
                   7        738       1619      0.527      0.627      0.583      0.243
                   8        738       2845      0.577       0.63      0.601      0.317
                   9        738          2          1          0   0.000375   0.000337

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round011_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 16:43:25.968735459 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round012 phase_round=12 ===

02 head-to-full DQA:  34%|███▍      | 11/32 [2:36:07<4:56:52, 848.22s/round, elapsed=2h36m07s, eta=4h58m03s, phase=phase1_head, round=11]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round012 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round012 client0_highway_day: pseudo scan 250/1500 images, kept 2377 boxes
round012 client0_highway_day: pseudo scan 500/1500 images, kept 4824 boxes
round012 client0_highway_day: pseudo scan 750/1500 images, kept 7183 boxes
round012 client0_highway_day: pseudo scan 1000/1500 images, kept 9563 boxes
round012 client0_highway_day: pseudo scan 1250/1500 images, kept 11906 boxes
round012 client0_highway_day: pseudo scan 1500/1500 images, kept 14310 boxes
{
  "round": "round012",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round011_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11241,
  "boxes_per_kept_image": 7.5291359678499665,
  "mean_conf": 0.8121469332891664,
  "mean_stability": 0.9516416247571218,
  "mean_score": 0.7762362164440306,
  "class_counts": {
    "0": 155,
    "2": 6440,
    "3": 114,
    "4": 559,
    "5": 5,
    "7": 567,
    "8": 3401
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_client0_highway_day_stable_boxes.csv"
}
round012 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round012 client1_highway_night: pseudo scan 250/1500 images, kept 1622 boxes
round012 client1_highway_night: pseudo scan 500/1500 images, kept 3367 boxes
round012 client1_highway_night: pseudo scan 750/1500 images, kept 5131 boxes
round012 client1_highway_night: pseudo scan 1000/1500 images, kept 6774 boxes
round012 client1_highway_night: pseudo scan 1250/1500 images, kept 8472 boxes
round012 client1_highway_night: pseudo scan 1500/1500 images, kept 10122 boxes
{
  "round": "round012",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round011_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1458,
  "pseudo_boxes_kept": 8289,
  "boxes_per_kept_image": 5.685185185185185,
  "mean_conf": 0.7257608695856581,
  "mean_stability": 0.9353387670977755,
  "mean_score": 0.6829615250735243,
  "class_counts": {
    "0": 64,
    "2": 4555,
    "3": 29,
    "4": 143,
    "5": 8,
    "7": 582,
    "8": 2908
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_client1_highway_night_stable_boxes.csv"
}
round012 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round012 client2_citystreet_day: pseudo scan 250/1500 images, kept 2701 boxes
round012 client2_citystreet_day: pseudo scan 500/1500 images, kept 5437 boxes
round012 client2_citystreet_day: pseudo scan 750/1500 images, kept 8182 boxes
round012 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10943 boxes
round012 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13671 boxes
round012 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16331 boxes
{
  "round": "round012",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round011_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13789,
  "boxes_per_kept_image": 9.217245989304812,
  "mean_conf": 0.8113630345733268,
  "mean_stability": 0.9496391552407017,
  "mean_score": 0.7739654468064001,
  "class_counts": {
    "0": 1427,
    "2": 7349,
    "3": 197,
    "4": 604,
    "5": 65,
    "7": 1526,
    "8": 2621
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_client2_citystreet_day_stable_boxes.csv"
}
round012 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round012 client3_citystreet_night: pseudo scan 250/1500 images, kept 2356 boxes
round012 client3_citystreet_night: pseudo scan 500/1500 images, kept 4658 boxes
round012 client3_citystreet_night: pseudo scan 750/1500 images, kept 6959 boxes
round012 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9186 boxes
round012 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11578 boxes
round012 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13889 boxes
{
  "round": "round012",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round011_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 11744,
  "boxes_per_kept_image": 7.9620338983050845,
  "mean_conf": 0.72052113789994,
  "mean_stability": 0.9318136455496261,
  "mean_score": 0.6758492922698907,
  "class_counts": {
    "0": 549,
    "2": 6251,
    "3": 67,
    "4": 156,
    "5": 38,
    "7": 2004,
    "8": 2679
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_client3_citystreet_night_stable_boxes.csv"
}
round012 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round012 client4_residential_day: pseudo scan 250/1500 images, kept 2585 boxes
round012 client4_residential_day: pseudo scan 500/1500 images, kept 5196 boxes
round012 client4_residential_day: pseudo scan 750/1500 images, kept 7741 boxes
round012 client4_residential_day: pseudo scan 1000/1500 images, kept 10220 boxes
round012 client4_residential_day: pseudo scan 1250/1500 images, kept 12745 boxes
round012 client4_residential_day: pseudo scan 1500/1500 images, kept 15228 boxes
{
  "round": "round012",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round011_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 10003,
  "boxes_per_kept_image": 6.708920187793427,
  "mean_conf": 0.8449263174206355,
  "mean_stability": 0.9578989860678534,
  "mean_score": 0.8128262962996019,
  "class_counts": {
    "0": 387,
    "2": 6853,
    "3": 65,
    "4": 320,
    "5": 48,
    "7": 537,
    "8": 1793
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_client4_residential_day_stable_boxes.csv"
}
round012 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round012 client5_residential_night: pseudo scan 250/1500 images, kept 2305 boxes
round012 client5_residential_night: pseudo scan 500/1500 images, kept 4588 boxes
round012 client5_residential_night: pseudo scan 750/1500 images, kept 6871 boxes
round012 client5_residential_night: pseudo scan 1000/1500 images, kept 9192 boxes
round012 client5_residential_night: pseudo scan 1250/1500 images, kept 11541 boxes
round012 client5_residential_night: pseudo scan 1500/1500 images, kept 13878 boxes
{
  "round": "round012",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round011_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1476,
  "pseudo_boxes_kept": 8645,
  "boxes_per_kept_image": 5.857046070460704,
  "mean_conf": 0.7932245210390548,
  "mean_stability": 0.9458851929066704,
  "mean_score": 0.7533303325779509,
  "class_counts": {
    "0": 131,
    "2": 6246,
    "3": 33,
    "4": 100,
    "5": 26,
    "7": 665,
    "8": 1444
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round012_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31218 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round012_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round012_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 19021.01it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:45:42.462117994 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:45:42.476017049 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2068       640  0.003438   0.04233  0.004564     4.027:   3%|▎         | 1/39 [00:21<13:30, 21.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003446   0.04267  0.004287     4.032:   5%|▌         | 2/39 [00:22<05:44,  9.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003477   0.04338  0.004408     4.101:   8%|▊         | 3/39 [00:23<03:16,  5.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640   0.00344   0.04345    0.0046     4.119:  10%|█         | 4/39 [00:23<02:07,  3.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003424   0.04282  0.004633      4.07:  13%|█▎        | 5/39 [00:24<01:27,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003417   0.04187  0.004581     3.989:  15%|█▌        | 6/39 [00:25<01:03,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003413   0.04189  0.004557     3.989:  18%|█▊        | 7/39 [00:25<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003407    0.0422  0.004628     4.019:  21%|██        | 8/39 [00:26<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003413   0.04274  0.004693     4.068:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003424   0.04305  0.004696     4.093:  26%|██▌       | 10/39 [00:27<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003412    0.0429  0.004627     4.075:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003414   0.04271  0.004636     4.061:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003419   0.04255  0.004631     4.048:  33%|███▎      | 13/39 [00:29<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003425   0.04272  0.004592     4.059:  36%|███▌      | 14/39 [00:30<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003416   0.04255  0.004565     4.043:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003421   0.04247  0.004578     4.038:  41%|████      | 16/39 [00:31<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003421   0.04218  0.004581     4.015:  44%|████▎     | 17/39 [00:32<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003424   0.04215  0.004577     4.012:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640   0.00342   0.04195  0.004583     3.997:  49%|████▊     | 19/39 [00:33<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003423   0.04206  0.004589     4.006:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003425    0.0421  0.004572     4.007:  54%|█████▍    | 21/39 [00:34<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003425   0.04198  0.004548     3.996:  56%|█████▋    | 22/39 [00:35<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003426   0.04201   0.00452     3.997:  59%|█████▉    | 23/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003427   0.04197  0.004509     3.993:  62%|██████▏   | 24/39 [00:36<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003422   0.04187  0.004499     3.983:  64%|██████▍   | 25/39 [00:37<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640  0.003421   0.04186  0.004493     3.982:  67%|██████▋   | 26/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.508      0.443      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.542      0.414      0.413      0.232
                   0        738       1052      0.516      0.549       0.54      0.259
                   1        738         44      0.459      0.135      0.219     0.0877
                   2        738       8622      0.695      0.733      0.753      0.482
                   3        738        151      0.514      0.417      0.426      0.326
                   4        738        467      0.483      0.582      0.541      0.388
                   5        738         70      0.288      0.414      0.281      0.148
                   6        738         65      0.256     0.0769      0.169     0.0667
                   7        738       1619      0.556      0.625      0.593      0.244
                   8        738       2845      0.653      0.604       0.61       0.32
                   9        738          2          1          0   0.000328   0.000296

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:47:07.999916990 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31219 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round012_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round012_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client1_highway_night_stable_train' images and labels...4895 found, 2902 missing, 0 empty, 0 corrupted: 100%|██████████| 7797/7797 [00:00<00:00, 11861.00it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.338439671509791
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2902 missing, 0 empty, 0 corrupted: 100%|██████████| 7797/7797 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:47:24.375573905 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:47:24.385963971 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2111       640   0.00339   0.04037  0.004332     3.847:   2%|▎         | 1/40 [00:22<14:48, 22.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1829       640  0.003426   0.03937  0.004507     3.785:   5%|▌         | 2/40 [00:23<06:18,  9.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003427   0.03967  0.004197     3.784:   8%|▊         | 3/40 [00:24<03:34,  5.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640   0.00344   0.03911  0.004251     3.744:  10%|█         | 4/40 [00:25<02:18,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003417   0.03887  0.004266     3.724:  12%|█▎        | 5/40 [00:26<01:34,  2.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1607       640  0.003428   0.03798  0.004418     3.666:  15%|█▌        | 6/40 [00:26<01:08,  2.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2009       640  0.003433   0.03811  0.004432     3.678:  18%|█▊        | 7/40 [00:27<00:51,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1834       640  0.003439   0.03818  0.004523     3.692:  20%|██        | 8/40 [00:28<00:40,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1772       640  0.003431   0.03797  0.004567     3.678:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1809       640   0.00343   0.03782  0.004519     3.662:  25%|██▌       | 10/40 [00:29<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640  0.003424   0.03758  0.004541     3.644:  28%|██▊       | 11/40 [00:30<00:25,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640   0.00341   0.03728   0.00451     3.616:  30%|███       | 12/40 [00:30<00:22,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1883       640  0.003413   0.03727  0.004497     3.615:  32%|███▎      | 13/40 [00:31<00:20,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2011       640  0.003421   0.03726  0.004517     3.616:  35%|███▌      | 14/40 [00:32<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640   0.00343   0.03734  0.004539     3.625:  38%|███▊      | 15/40 [00:32<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640  0.003424   0.03722  0.004527     3.613:  40%|████      | 16/40 [00:33<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1807       640  0.003421   0.03708  0.004535     3.603:  42%|████▎     | 17/40 [00:33<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003418   0.03691   0.00453     3.589:  45%|████▌     | 18/40 [00:34<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1539       640  0.003422    0.0365  0.004526     3.556:  48%|████▊     | 19/40 [00:35<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003426   0.03647  0.004552     3.555:  50%|█████     | 20/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003423   0.03643  0.004556     3.553:  52%|█████▎    | 21/40 [00:36<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1736       640  0.003422   0.03632  0.004567     3.545:  55%|█████▌    | 22/40 [00:37<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003424   0.03639  0.004578     3.552:  57%|█████▊    | 23/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003433   0.03631  0.004618     3.549:  60%|██████    | 24/40 [00:38<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003437   0.03619   0.00459     3.538:  62%|██████▎   | 25/40 [00:38<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003432   0.03612  0.004593     3.532:  65%|██████▌   | 26/40 [00:39<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.517      0.434       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.509      0.435      0.409      0.231
                   0        738       1052      0.538      0.546      0.533      0.257
                   1        738         44      0.447      0.202      0.207     0.0976
                   2        738       8622       0.64      0.743      0.751       0.48
                   3        738        151      0.391       0.43      0.435      0.335
                   4        738        467      0.441      0.615      0.537      0.384
                   5        738         70      0.274      0.443      0.284       0.14
                   6        738         65       0.24      0.123      0.163     0.0659
                   7        738       1619      0.521      0.631      0.581      0.242
                   8        738       2845      0.592      0.614      0.596      0.312
                   9        738          2          1          0   0.000262   0.000236

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:48:49.831875186 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31220 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round012_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round012_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 18922.58it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:49:05.107013421 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:49:05.110854222 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003528   0.05219  0.004586     4.824:   3%|▎         | 1/39 [00:21<13:20, 21.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003482   0.05129  0.004969      4.78:   5%|▌         | 2/39 [00:21<05:40,  9.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003445   0.05023  0.004991     4.694:   8%|▊         | 3/39 [00:22<03:14,  5.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003455   0.04917  0.004907     4.603:  10%|█         | 4/39 [00:23<02:06,  3.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003452   0.04855  0.004834     4.547:  13%|█▎        | 5/39 [00:24<01:26,  2.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003417   0.04743  0.004797     4.451:  15%|█▌        | 6/39 [00:25<01:02,  1.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003427   0.04712  0.004859     4.432:  18%|█▊        | 7/39 [00:25<00:47,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003417   0.04671   0.00481     4.395:  21%|██        | 8/39 [00:26<00:38,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003432   0.04668  0.004746     4.388:  23%|██▎       | 9/39 [00:26<00:31,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003417   0.04638  0.004737     4.363:  26%|██▌       | 10/39 [00:27<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640   0.00342   0.04627  0.004731     4.354:  28%|██▊       | 11/39 [00:28<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003424   0.04577  0.004742     4.315:  31%|███       | 12/39 [00:28<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003431   0.04561  0.004706       4.3:  33%|███▎      | 13/39 [00:29<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003441   0.04561  0.004672     4.298:  36%|███▌      | 14/39 [00:30<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003442   0.04542  0.004646     4.281:  38%|███▊      | 15/39 [00:30<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003433   0.04509  0.004637     4.253:  41%|████      | 16/39 [00:31<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003423   0.04485   0.00466     4.235:  44%|████▎     | 17/39 [00:31<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003416   0.04477  0.004646     4.226:  46%|████▌     | 18/39 [00:32<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003417   0.04448  0.004629     4.202:  49%|████▊     | 19/39 [00:33<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003413   0.04447  0.004619       4.2:  51%|█████▏    | 20/39 [00:33<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003404   0.04429  0.004599     4.184:  54%|█████▍    | 21/39 [00:34<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640    0.0034    0.0442  0.004587     4.175:  56%|█████▋    | 22/39 [00:35<00:10,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003392   0.04409  0.004589     4.165:  59%|█████▉    | 23/39 [00:35<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003389   0.04402  0.004577     4.159:  62%|██████▏   | 24/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003385   0.04391  0.004576     4.149:  64%|██████▍   | 25/39 [00:36<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003379   0.04386   0.00456     4.144:  67%|██████▋   | 26/39 [00:37<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.512      0.442       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.498      0.444      0.409      0.231
                   0        738       1052      0.558      0.544      0.539      0.253
                   1        738         44      0.487      0.259      0.196     0.0926
                   2        738       8622      0.607      0.757      0.755       0.48
                   3        738        151        0.3       0.45      0.431      0.324
                   4        738        467      0.405      0.626      0.538      0.383
                   5        738         70      0.289      0.414      0.275      0.144
                   6        738         65      0.235      0.123      0.169     0.0705
                   7        738       1619      0.522      0.637      0.583      0.241
                   8        738       2845      0.578      0.626      0.604       0.32
                   9        738          2          1          0   0.000263   0.000237

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:50:31.893300564 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31221 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round012_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round012_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client3_citystreet_night_stable_train' images and labels...4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<00:00, 10018.08it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.282926829268293
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:50:48.913635735 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:50:48.009247353 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2028       640  0.003577   0.04534  0.004577     4.279:   2%|▎         | 1/40 [00:22<14:35, 22.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1936       640  0.003618   0.04452  0.004934     4.246:   5%|▌         | 2/40 [00:23<06:11,  9.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640   0.00358   0.04498   0.00481      4.27:   8%|▊         | 3/40 [00:24<03:30,  5.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003546   0.04403  0.004896     4.197:  10%|█         | 4/40 [00:25<02:15,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003524   0.04298  0.004811     4.105:  12%|█▎        | 5/40 [00:25<01:32,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1660       640  0.003492   0.04212  0.004725     4.027:  15%|█▌        | 6/40 [00:26<01:07,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003493   0.04157  0.004634     3.976:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003484   0.04166  0.004681     3.986:  20%|██        | 8/40 [00:27<00:40,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003467   0.04147  0.004648     3.967:  22%|██▎       | 9/40 [00:28<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003464   0.04126   0.00462     3.948:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003458   0.04102  0.004553     3.922:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1754       640  0.003445   0.04058  0.004549     3.886:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003437   0.04029  0.004534     3.861:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003436    0.0402  0.004563     3.856:  35%|███▌      | 14/40 [00:31<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003428   0.03995  0.004561     3.835:  38%|███▊      | 15/40 [00:32<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003429   0.03976  0.004555     3.819:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1648       640  0.003433   0.03946  0.004578     3.798:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1961       640  0.003435   0.03928  0.004602     3.785:  45%|████▌     | 18/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1761       640  0.003433   0.03893  0.004596     3.757:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003433   0.03883  0.004587     3.748:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003434   0.03868  0.004579     3.736:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1778       640  0.003435   0.03849  0.004557     3.719:  55%|█████▌    | 22/40 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003434   0.03844  0.004558     3.715:  57%|█████▊    | 23/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003428   0.03822  0.004536     3.695:  60%|██████    | 24/40 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1705       640  0.003427   0.03799  0.004516     3.674:  62%|██████▎   | 25/40 [00:38<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003423   0.03793  0.004499     3.668:  65%|██████▌   | 26/40 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.583      0.398       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.564        0.4      0.408      0.232
                   0        738       1052      0.625      0.506      0.528      0.253
                   1        738         44      0.494     0.0909      0.214     0.0953
                   2        738       8622      0.696      0.721      0.747      0.479
                   3        738        151      0.505      0.404      0.431      0.332
                   4        738        467      0.456        0.6      0.537      0.381
                   5        738         70      0.373        0.4      0.276      0.145
                   6        738         65      0.284     0.0615       0.16     0.0681
                   7        738       1619      0.559      0.619      0.587      0.243
                   8        738       2845      0.652      0.596      0.602      0.319
                   9        738          2          1          0   0.000236   0.000212

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:52:14.567719399 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31222 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round012_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round012_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 17594.13it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:52:30.484771193 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:52:30.511453626 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2084       640  0.003429   0.05105  0.004064     4.683:   3%|▎         | 1/39 [00:22<14:06, 22.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2054       640  0.003461   0.05052  0.004865     4.708:   5%|▌         | 2/39 [00:23<05:58,  9.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1903       640  0.003403   0.04835  0.004797     4.524:   8%|▊         | 3/39 [00:24<03:24,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1904       640  0.003414   0.04737  0.004932     4.457:  10%|█         | 4/39 [00:24<02:12,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1942       640   0.00339   0.04608  0.004907      4.35:  13%|█▎        | 5/39 [00:25<01:30,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1735       640  0.003402   0.04475  0.004985     4.251:  15%|█▌        | 6/39 [00:26<01:05,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1985       640  0.003416   0.04449  0.004982     4.231:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1947       640  0.003426    0.0442  0.004909     4.203:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2072       640   0.00342   0.04416  0.004975     4.204:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1893       640   0.00343   0.04417  0.004947     4.204:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2139       640  0.003431   0.04414  0.004933     4.201:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2120       640  0.003429   0.04408    0.0049     4.192:  31%|███       | 12/39 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2089       640  0.003439   0.04412  0.004881     4.195:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2027       640  0.003446   0.04406  0.004859     4.189:  36%|███▌      | 14/39 [00:31<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1824       640   0.00345   0.04375  0.004852     4.164:  38%|███▊      | 15/39 [00:32<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1768       640  0.003449   0.04347   0.00484     4.141:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1747       640  0.003436   0.04325  0.004808      4.12:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2019       640  0.003432    0.0432  0.004774     4.113:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1602       640  0.003425   0.04291  0.004769     4.088:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2209       640  0.003426   0.04289  0.004752     4.086:  51%|█████▏    | 20/39 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1896       640  0.003425   0.04284  0.004723     4.079:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1996       640  0.003423   0.04284  0.004722     4.079:  56%|█████▋    | 22/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2001       640  0.003425   0.04286  0.004748     4.083:  59%|█████▉    | 23/39 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640  0.003422   0.04277  0.004743     4.074:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2030       640  0.003422   0.04276  0.004742     4.074:  64%|██████▍   | 25/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1772       640   0.00342   0.04256  0.004729     4.057:  67%|██████▋   | 26/39 [00:39<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.511      0.448      0.416      0.233
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.494      0.448      0.413      0.234
                   0        738       1052      0.476       0.57       0.54      0.257
                   1        738         44      0.491      0.263      0.209     0.0954
                   2        738       8622      0.643      0.746      0.751      0.479
                   3        738        151      0.319       0.45      0.441      0.335
                   4        738        467      0.407      0.625      0.546       0.39
                   5        738         70      0.286      0.429      0.286      0.147
                   6        738         65      0.217      0.138       0.17     0.0696
                   7        738       1619      0.514      0.636      0.584      0.242
                   8        738       2845      0.591      0.625      0.605      0.321
                   9        738          2          1          0   0.000255   0.000204

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:53:54.171446082 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31223 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round012_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round012_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client5_residential_night_stable_train' images and labels...:   0%|          | 0/7833 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client5_residential_night_stable_train' images and labels...4885 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<00:00, 13698.93it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.282926829268293
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round012_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7833/7833 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:54:09.153295000 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:54:09.220532992 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1757       640   0.00343   0.04246  0.004416     4.024:   2%|▎         | 1/40 [00:21<14:05, 21.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003412   0.04181  0.004439     3.973:   5%|▌         | 2/40 [00:22<05:57,  9.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1967       640  0.003388    0.0418  0.004495     3.975:   8%|▊         | 3/40 [00:23<03:23,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003375   0.04204  0.004499     3.993:  10%|█         | 4/40 [00:24<02:12,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003376   0.04167  0.004538     3.967:  12%|█▎        | 5/40 [00:24<01:30,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1719       640  0.003396   0.04087  0.004446     3.897:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1770       640  0.003384   0.03997  0.004524      3.83:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003376   0.03962  0.004462     3.797:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1866       640  0.003376   0.03953  0.004401     3.784:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1819       640  0.003386   0.03924  0.004409     3.763:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2216       640  0.003398   0.03952  0.004476     3.791:  28%|██▊       | 11/40 [00:28<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1838       640  0.003399   0.03915  0.004457      3.76:  30%|███       | 12/40 [00:29<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1675       640   0.00339    0.0388  0.004446     3.731:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2057       640  0.003402   0.03872  0.004514     3.731:  35%|███▌      | 14/40 [00:30<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1805       640  0.003391   0.03844  0.004474     3.705:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1586       640   0.00338   0.03786  0.004484     3.658:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003387   0.03772  0.004531     3.651:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1978       640  0.003388   0.03764  0.004505     3.643:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1588       640  0.003396   0.03729  0.004543     3.618:  48%|████▊     | 19/40 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1984       640  0.003401   0.03718  0.004529     3.608:  50%|█████     | 20/40 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003407   0.03709  0.004541     3.603:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1895       640  0.003411   0.03705  0.004547     3.601:  55%|█████▌    | 22/40 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003404   0.03704  0.004584     3.602:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2024       640  0.003404   0.03709  0.004572     3.606:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003409   0.03703  0.004577     3.601:  62%|██████▎   | 25/40 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1820       640  0.003412   0.03691  0.004565     3.591:  65%|██████▌   | 26/40 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.506      0.436      0.409      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.562      0.397      0.408      0.231
                   0        738       1052      0.609       0.51      0.529      0.255
                   1        738         44      0.499     0.0909      0.205      0.094
                   2        738       8622      0.713      0.711      0.748      0.478
                   3        738        151      0.539      0.404      0.426      0.331
                   4        738        467       0.47      0.572      0.537      0.386
                   5        738         70      0.344      0.414      0.278      0.143
                   6        738         65      0.224     0.0462      0.167      0.064
                   7        738       1619      0.576      0.617      0.587      0.242
                   8        738       2845      0.652      0.602      0.606      0.321
                   9        738          2          1          0    0.00019   0.000171

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 16:55:34.274881487 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31224 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round012_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round012_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 16:55:50.702593394 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 16:55:50.818581159 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03076   0.03627  0.003819     5.668:   3%|▎         | 1/31 [00:32<16:08, 32.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03139   0.03703  0.004016     5.795:   6%|▋         | 2/31 [00:33<06:38, 13.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.03089   0.03599  0.003955     5.667:  10%|▉         | 3/31 [00:33<03:39,  7.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.03065     0.035  0.003796     5.556:  13%|█▎        | 4/31 [00:34<02:16,  5.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.03061   0.03508  0.003812      5.56:  16%|█▌        | 5/31 [00:35<01:29,  3.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.03073     0.035  0.003847     5.566:  19%|█▉        | 6/31 [00:35<01:01,  2.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640    0.0308   0.03472  0.003896     5.554:  23%|██▎       | 7/31 [00:36<00:44,  1.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.03072   0.03478  0.003894     5.551:  26%|██▌       | 8/31 [00:36<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.03078   0.03469  0.003807     5.543:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.03078   0.03479  0.003782     5.548:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.03074   0.03483  0.003803      5.55:  35%|███▌      | 11/31 [00:38<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.03066   0.03457    0.0038     5.523:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.03063   0.03457  0.003748     5.516:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.03065   0.03446  0.003717     5.506:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.03068   0.03438  0.003766     5.506:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.03068   0.03427  0.003763     5.498:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.03072   0.03431  0.003741     5.502:  55%|█████▍    | 17/31 [00:42<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640    0.0308   0.03444  0.003714     5.516:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.03077   0.03434  0.003688     5.503:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.03078   0.03456  0.003684     5.522:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.03082   0.03463  0.003704     5.532:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.03085   0.03475   0.00368     5.542:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.03085   0.03482  0.003658     5.546:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.03089   0.03494  0.003649     5.558:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.03091   0.03493  0.003662     5.561:  81%|████████  | 25/31 [00:46<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.03099   0.03502  0.003673     5.575:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.507      0.446      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.491      0.447      0.409       0.23
                   0        738       1052      0.485      0.558      0.532      0.255
                   1        738         44      0.401       0.25      0.197     0.0868
                   2        738       8622      0.633      0.752      0.752      0.486
                   3        738        151      0.329      0.437      0.432      0.322
                   4        738        467      0.447      0.606      0.542      0.386
                   5        738         70      0.245      0.414      0.287      0.144
                   6        738         65      0.268        0.2      0.163     0.0651
                   7        738       1619      0.525      0.626       0.58      0.243
                   8        738       2845      0.579      0.628      0.599      0.315
                   9        738          2          1          0   0.000376   0.000338

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round012_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 16:57:29.632925165 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round013 phase_round=13 ===

02 head-to-full DQA:  38%|███▊      | 12/32 [2:50:11<4:42:18, 846.91s/round, elapsed=2h50m11s, eta=4h43m38s, phase=phase1_head, round=12]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round013 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round013 client0_highway_day: pseudo scan 250/1500 images, kept 2381 boxes
round013 client0_highway_day: pseudo scan 500/1500 images, kept 4820 boxes
round013 client0_highway_day: pseudo scan 750/1500 images, kept 7183 boxes
round013 client0_highway_day: pseudo scan 1000/1500 images, kept 9573 boxes
round013 client0_highway_day: pseudo scan 1250/1500 images, kept 11913 boxes
round013 client0_highway_day: pseudo scan 1500/1500 images, kept 14316 boxes
{
  "round": "round013",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round012_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1493,
  "pseudo_boxes_kept": 11267,
  "boxes_per_kept_image": 7.54655056932351,
  "mean_conf": 0.8134435568313331,
  "mean_stability": 0.9509986012504847,
  "mean_score": 0.7769847204893582,
  "class_counts": {
    "0": 155,
    "2": 6443,
    "3": 116,
    "4": 564,
    "5": 7,
    "7": 565,
    "8": 3417
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_client0_highway_day_stable_boxes.csv"
}
round013 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round013 client1_highway_night: pseudo scan 250/1500 images, kept 1622 boxes
round013 client1_highway_night: pseudo scan 500/1500 images, kept 3352 boxes
round013 client1_highway_night: pseudo scan 750/1500 images, kept 5101 boxes
round013 client1_highway_night: pseudo scan 1000/1500 images, kept 6753 boxes
round013 client1_highway_night: pseudo scan 1250/1500 images, kept 8449 boxes
round013 client1_highway_night: pseudo scan 1500/1500 images, kept 10096 boxes
{
  "round": "round013",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round012_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1457,
  "pseudo_boxes_kept": 8294,
  "boxes_per_kept_image": 5.692518874399451,
  "mean_conf": 0.7276553486466897,
  "mean_stability": 0.9345422160174147,
  "mean_score": 0.6841868390772792,
  "class_counts": {
    "0": 65,
    "2": 4544,
    "3": 29,
    "4": 143,
    "5": 7,
    "7": 596,
    "8": 2910
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_client1_highway_night_stable_boxes.csv"
}
round013 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round013 client2_citystreet_day: pseudo scan 250/1500 images, kept 2704 boxes
round013 client2_citystreet_day: pseudo scan 500/1500 images, kept 5444 boxes
round013 client2_citystreet_day: pseudo scan 750/1500 images, kept 8190 boxes
round013 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10948 boxes
round013 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13676 boxes
round013 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16342 boxes
{
  "round": "round013",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round012_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13786,
  "boxes_per_kept_image": 9.21524064171123,
  "mean_conf": 0.8135424774547075,
  "mean_stability": 0.9491422228935614,
  "mean_score": 0.7756671191243923,
  "class_counts": {
    "0": 1433,
    "2": 7354,
    "3": 203,
    "4": 603,
    "5": 70,
    "7": 1534,
    "8": 2589
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_client2_citystreet_day_stable_boxes.csv"
}
round013 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round013 client3_citystreet_night: pseudo scan 250/1500 images, kept 2351 boxes
round013 client3_citystreet_night: pseudo scan 500/1500 images, kept 4649 boxes
round013 client3_citystreet_night: pseudo scan 750/1500 images, kept 6948 boxes
round013 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9165 boxes
round013 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11562 boxes
round013 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13861 boxes
{
  "round": "round013",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round012_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1473,
  "pseudo_boxes_kept": 11749,
  "boxes_per_kept_image": 7.9762389680923285,
  "mean_conf": 0.7226991064168614,
  "mean_stability": 0.9307985624330319,
  "mean_score": 0.6771826651907752,
  "class_counts": {
    "0": 543,
    "2": 6238,
    "3": 71,
    "4": 156,
    "5": 38,
    "7": 2046,
    "8": 2657
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_client3_citystreet_night_stable_boxes.csv"
}
round013 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round013 client4_residential_day: pseudo scan 250/1500 images, kept 2591 boxes
round013 client4_residential_day: pseudo scan 500/1500 images, kept 5200 boxes
round013 client4_residential_day: pseudo scan 750/1500 images, kept 7752 boxes
round013 client4_residential_day: pseudo scan 1000/1500 images, kept 10237 boxes
round013 client4_residential_day: pseudo scan 1250/1500 images, kept 12760 boxes
round013 client4_residential_day: pseudo scan 1500/1500 images, kept 15249 boxes
{
  "round": "round013",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round012_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 10006,
  "boxes_per_kept_image": 6.710932260228035,
  "mean_conf": 0.8470118653201208,
  "mean_stability": 0.9574425071090692,
  "mean_score": 0.8144623427732779,
  "class_counts": {
    "0": 389,
    "2": 6863,
    "3": 67,
    "4": 314,
    "5": 47,
    "7": 533,
    "8": 1793
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_client4_residential_day_stable_boxes.csv"
}
round013 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round013 client5_residential_night: pseudo scan 250/1500 images, kept 2299 boxes
round013 client5_residential_night: pseudo scan 500/1500 images, kept 4584 boxes
round013 client5_residential_night: pseudo scan 750/1500 images, kept 6861 boxes
round013 client5_residential_night: pseudo scan 1000/1500 images, kept 9177 boxes
round013 client5_residential_night: pseudo scan 1250/1500 images, kept 11509 boxes
round013 client5_residential_night: pseudo scan 1500/1500 images, kept 13841 boxes
{
  "round": "round013",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round012_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 8641,
  "boxes_per_kept_image": 5.858305084745763,
  "mean_conf": 0.7934961556463989,
  "mean_stability": 0.9452776184596338,
  "mean_score": 0.7531658737324067,
  "class_counts": {
    "0": 128,
    "2": 6229,
    "3": 33,
    "4": 96,
    "5": 24,
    "7": 689,
    "8": 1442
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round013_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31225 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round013_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round013_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client0_highway_day_stable_train' images and labels...5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<00:00, 14135.91it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7867/7867 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 16:59:43.218447972 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 16:59:43.230391512 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2068       640  0.003439   0.04249  0.004564     4.039:   3%|▎         | 1/39 [00:21<13:37, 21.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003449   0.04282  0.004278     4.044:   5%|▌         | 2/39 [00:22<05:48,  9.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640   0.00348    0.0435  0.004394      4.11:   8%|▊         | 3/39 [00:23<03:18,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003443   0.04357  0.004588     4.128:  10%|█         | 4/39 [00:24<02:08,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003427   0.04293  0.004622     4.078:  13%|█▎        | 5/39 [00:24<01:27,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003419   0.04197  0.004568     3.996:  15%|█▌        | 6/39 [00:25<01:03,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003415   0.04199  0.004544     3.996:  18%|█▊        | 7/39 [00:26<00:48,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003409   0.04229  0.004616     4.025:  21%|██        | 8/39 [00:26<00:38,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003415   0.04283   0.00468     4.074:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003427   0.04313  0.004685     4.099:  26%|██▌       | 10/39 [00:28<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003415   0.04297  0.004615      4.08:  28%|██▊       | 11/39 [00:28<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003416   0.04277  0.004624     4.065:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003421   0.04261  0.004619     4.052:  33%|███▎      | 13/39 [00:29<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003427   0.04278  0.004579     4.063:  36%|███▌      | 14/39 [00:30<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003418   0.04261  0.004552     4.046:  38%|███▊      | 15/39 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003423   0.04252  0.004566     4.041:  41%|████      | 16/39 [00:31<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003423   0.04223  0.004569     4.018:  44%|████▎     | 17/39 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003426   0.04219  0.004565     4.015:  46%|████▌     | 18/39 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003422     0.042  0.004571     3.999:  49%|████▊     | 19/39 [00:33<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003425    0.0421  0.004576     4.008:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003427   0.04213  0.004559     4.009:  54%|█████▍    | 21/39 [00:34<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003427   0.04201  0.004535     3.998:  56%|█████▋    | 22/39 [00:35<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003427   0.04205  0.004507     3.998:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003428     0.042  0.004495     3.994:  62%|██████▏   | 24/39 [00:36<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003424    0.0419  0.004484     3.985:  64%|██████▍   | 25/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640  0.003422   0.04189  0.004478     3.983:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.514      0.444      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.499      0.446      0.412      0.232
                   0        738       1052      0.468       0.58       0.54      0.258
                   1        738         44      0.458      0.273       0.21     0.0877
                   2        738       8622      0.647      0.747      0.754      0.482
                   3        738        151      0.378      0.434      0.426      0.327
                   4        738        467      0.441      0.606       0.54      0.388
                   5        738         70      0.257      0.414      0.285      0.147
                   6        738         65      0.224      0.138       0.17     0.0672
                   7        738       1619       0.51      0.644      0.591      0.243
                   8        738       2845      0.607      0.626       0.61       0.32
                   9        738          2          1          0   0.000336   0.000302

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:01:07.779841049 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31226 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round013_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round013_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client1_highway_night_stable_train' images and labels...4895 found, 2900 missing, 0 empty, 0 corrupted: 100%|██████████| 7795/7795 [00:00<00:00, 10006.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.340862422997947
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2900 missing, 0 empty, 0 corrupted: 100%|██████████| 7795/7795 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:01:23.114951916 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:01:23.119227047 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1965       640  0.003404   0.04112  0.003875     3.872:   2%|▎         | 1/40 [00:21<14:04, 21.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1821       640  0.003435   0.03978  0.004274     3.799:   5%|▌         | 2/40 [00:22<05:59,  9.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003422   0.04057  0.004208     3.856:   8%|▊         | 3/40 [00:23<03:23,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2058       640  0.003433   0.03994  0.004387     3.821:  10%|█         | 4/40 [00:24<02:11,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640   0.00342   0.03998  0.004324     3.818:  12%|█▎        | 5/40 [00:24<01:30,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003437   0.03961  0.004412     3.796:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003438   0.03905  0.004487     3.758:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2041       640  0.003429   0.03897  0.004454     3.748:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003426    0.0387   0.00452     3.731:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003422   0.03857  0.004503      3.72:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1885       640  0.003417   0.03842  0.004515     3.708:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1733       640  0.003413    0.0383  0.004545       3.7:  30%|███       | 12/40 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1863       640  0.003413   0.03801  0.004497     3.673:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640  0.003419   0.03792  0.004501     3.667:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003418   0.03767  0.004475     3.645:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1940       640  0.003414   0.03747  0.004514     3.632:  40%|████      | 16/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640  0.003414   0.03731    0.0045     3.618:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1891       640  0.003414   0.03714  0.004496     3.604:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1545       640  0.003418   0.03668   0.00449     3.567:  48%|████▊     | 19/40 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2157       640  0.003417   0.03669  0.004487     3.568:  50%|█████     | 20/40 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1858       640  0.003419   0.03651  0.004494     3.554:  52%|█████▎    | 21/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003407   0.03638  0.004447     3.539:  55%|█████▌    | 22/40 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2191       640  0.003412   0.03646  0.004467     3.547:  57%|█████▊    | 23/40 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003418   0.03638  0.004502     3.544:  60%|██████    | 24/40 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640  0.003419   0.03625  0.004483     3.532:  62%|██████▎   | 25/40 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1786       640  0.003416   0.03608  0.004485     3.518:  65%|██████▌   | 26/40 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.496       0.45       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]

                 all        738      14937      0.525      0.421      0.408      0.231
                   0        738       1052      0.538      0.546      0.535      0.258
                   1        738         44      0.492      0.159      0.216     0.0998
                   2        738       8622       0.67      0.733       0.75      0.481
                   3        738        151      0.429       0.43      0.428      0.331
                   4        738        467      0.453      0.608      0.532      0.381
                   5        738         70      0.296      0.429      0.285      0.136
                   6        738         65      0.217     0.0769      0.163     0.0662
                   7        738       1619      0.537      0.626      0.582      0.242
                   8        738       2845      0.622      0.607      0.595      0.311
                   9        738          2          1          0   0.000254   0.000228

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:02:48.590129648 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31227 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round013_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round013_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 15108.24it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:03:05.387786841 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:03:05.392333082 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003528   0.05237   0.00456     4.837:   3%|▎         | 1/39 [00:22<14:09, 22.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2187       640  0.003482   0.05144  0.004944     4.789:   5%|▌         | 2/39 [00:23<05:58,  9.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1974       640  0.003446   0.05037  0.004972     4.703:   8%|▊         | 3/39 [00:24<03:23,  5.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1957       640  0.003456   0.04928   0.00489      4.61:  10%|█         | 4/39 [00:24<02:12,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2145       640  0.003454   0.04866  0.004818     4.555:  13%|█▎        | 5/39 [00:25<01:30,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1780       640  0.003419   0.04753  0.004783     4.459:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1960       640  0.003429   0.04721  0.004845     4.438:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1897       640  0.003419   0.04679  0.004796     4.401:  21%|██        | 8/39 [00:27<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2025       640  0.003434   0.04676  0.004727     4.393:  23%|██▎       | 9/39 [00:28<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003419   0.04646  0.004718     4.367:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003422   0.04634  0.004712     4.358:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1792       640  0.003427   0.04583  0.004724     4.319:  31%|███       | 12/39 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2094       640  0.003433   0.04566  0.004687     4.303:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2134       640  0.003443   0.04566  0.004652       4.3:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1930       640  0.003444   0.04547  0.004627     4.283:  38%|███▊      | 15/39 [00:32<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1894       640  0.003435   0.04514  0.004618     4.255:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1504       640  0.003425   0.04489  0.004642     4.237:  44%|████▎     | 17/39 [00:33<00:14,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1920       640  0.003418   0.04481  0.004628     4.228:  46%|████▌     | 18/39 [00:33<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1718       640  0.003419   0.04452  0.004611     4.204:  49%|████▊     | 19/39 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640  0.003415   0.04451  0.004602     4.202:  51%|█████▏    | 20/39 [00:35<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1849       640  0.003406   0.04433  0.004582     4.185:  54%|█████▍    | 21/39 [00:35<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1707       640  0.003402   0.04423   0.00457     4.176:  56%|█████▋    | 22/39 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1860       640  0.003394   0.04412  0.004571     4.167:  59%|█████▉    | 23/39 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1900       640   0.00339   0.04405   0.00456      4.16:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1848       640  0.003387   0.04394  0.004559      4.15:  64%|██████▍   | 25/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2050       640  0.003381   0.04389  0.004542     4.145:  67%|██████▋   | 26/39 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.508      0.446      0.408       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.04it/s]

                 all        738      14937      0.498      0.446      0.408       0.23
                   0        738       1052      0.559      0.546      0.538      0.253
                   1        738         44      0.498      0.273      0.196     0.0924
                   2        738       8622      0.607      0.758      0.755       0.48
                   3        738        151      0.296       0.45      0.429      0.325
                   4        738        467      0.412      0.634      0.537      0.381
                   5        738         70      0.294      0.417      0.271      0.142
                   6        738         65      0.215      0.118      0.172     0.0703
                   7        738       1619      0.519      0.637      0.583       0.24
                   8        738       2845      0.577      0.625      0.603       0.32
                   9        738          2          1          0   0.000266   0.000239

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:04:31.098548555 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31228 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round013_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round013_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client3_citystreet_night_stable_train' images and labels...4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<00:00, 11184.21it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.287738076499291
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:04:48.035004404 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:04:48.054604400 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1810       640  0.003461   0.04373  0.003845     4.083:   2%|▎         | 1/40 [00:23<15:01, 23.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1693       640  0.003409   0.04302  0.004704     4.091:   5%|▌         | 2/40 [00:24<06:23, 10.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1961       640  0.003375   0.04286  0.004463     4.056:   8%|▊         | 3/40 [00:24<03:38,  5.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1869       640  0.003339   0.04225  0.004343     3.994:  10%|█         | 4/40 [00:25<02:21,  3.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1802       640  0.003332   0.04145  0.004508     3.943:  12%|█▎        | 5/40 [00:26<01:40,  2.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1832       640  0.003337   0.04088  0.004471     3.895:  15%|█▌        | 6/40 [00:27<01:11,  2.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2081       640  0.003339   0.04078  0.004442     3.885:  18%|█▊        | 7/40 [00:28<00:53,  1.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2100       640  0.003349   0.04099  0.004477     3.905:  20%|██        | 8/40 [00:28<00:42,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1911       640  0.003354    0.0408  0.004461     3.889:  22%|██▎       | 9/40 [00:29<00:34,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1813       640   0.00336   0.04046   0.00449     3.865:  25%|██▌       | 10/40 [00:30<00:28,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2113       640  0.003365   0.04032  0.004483     3.854:  28%|██▊       | 11/40 [00:30<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1859       640  0.003369   0.04019  0.004484     3.843:  30%|███       | 12/40 [00:31<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1904       640  0.003369   0.03997  0.004495     3.826:  32%|███▎      | 13/40 [00:32<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2168       640  0.003371   0.04006  0.004493     3.834:  35%|███▌      | 14/40 [00:32<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1774       640  0.003366   0.03971  0.004487     3.805:  38%|███▊      | 15/40 [00:33<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1833       640  0.003357   0.03949  0.004443     3.783:  40%|████      | 16/40 [00:33<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1640       640  0.003365   0.03907  0.004466     3.752:  42%|████▎     | 17/40 [00:34<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1873       640  0.003366   0.03885  0.004474     3.736:  45%|████▌     | 18/40 [00:35<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1732       640  0.003368   0.03854  0.004443     3.708:  48%|████▊     | 19/40 [00:35<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2086       640  0.003371    0.0385  0.004438     3.704:  50%|█████     | 20/40 [00:36<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1896       640  0.003383   0.03842  0.004463     3.701:  52%|█████▎    | 21/40 [00:37<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1858       640  0.003384   0.03838  0.004449     3.697:  55%|█████▌    | 22/40 [00:37<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2130       640  0.003384   0.03833  0.004449     3.693:  57%|█████▊    | 23/40 [00:38<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2040       640  0.003386   0.03829  0.004467     3.692:  60%|██████    | 24/40 [00:38<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2007       640  0.003386   0.03821  0.004453     3.684:  62%|██████▎   | 25/40 [00:39<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1956       640  0.003383   0.03806  0.004451     3.672:  65%|██████▌   | 26/40 [00:40<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.572      0.401       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]

                 all        738      14937      0.596      0.389      0.408      0.231
                   0        738       1052      0.648        0.5      0.531      0.255
                   1        738         44      0.664       0.09      0.219     0.0971
                   2        738       8622      0.715      0.708      0.746      0.477
                   3        738        151      0.512      0.404      0.434       0.33
                   4        738        467       0.46      0.589      0.533      0.378
                   5        738         70      0.418      0.371      0.278      0.142
                   6        738         65      0.295     0.0462      0.164     0.0673
                   7        738       1619      0.576      0.601      0.581      0.244
                   8        738       2845      0.675      0.579      0.598      0.317
                   9        738          2          1          0   0.000237   0.000213

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 17:06:16.059044423 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31229 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round013_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round013_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client4_residential_day_stable_train' images and labels...5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 10301.38it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.632222758731691
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2664 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:06:34.284568975 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:06:34.290602263 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2084       640   0.00343   0.05122  0.004054     4.696:   3%|▎         | 1/39 [00:22<14:18, 22.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2054       640  0.003461   0.05065  0.004848     4.717:   5%|▌         | 2/39 [00:23<06:03,  9.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1903       640  0.003404   0.04847  0.004783     4.533:   8%|▊         | 3/39 [00:24<03:26,  5.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1904       640  0.003414   0.04746  0.004921     4.464:  10%|█         | 4/39 [00:25<02:13,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1942       640  0.003391   0.04615  0.004898     4.355:  13%|█▎        | 5/39 [00:25<01:30,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1735       640  0.003403   0.04482  0.004975     4.256:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1985       640  0.003418   0.04457  0.004971     4.236:  18%|█▊        | 7/39 [00:27<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1947       640  0.003427   0.04427  0.004897     4.208:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2072       640  0.003421   0.04422  0.004961     4.208:  23%|██▎       | 9/39 [00:28<00:31,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1893       640  0.003432   0.04422  0.004933     4.207:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2139       640  0.003432   0.04419  0.004919     4.204:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2120       640  0.003431   0.04412  0.004886     4.195:  31%|███       | 12/39 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2089       640   0.00344   0.04416  0.004866     4.197:  33%|███▎      | 13/39 [00:30<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2027       640  0.003448   0.04409  0.004842     4.191:  36%|███▌      | 14/39 [00:31<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1824       640  0.003452   0.04378  0.004835     4.165:  38%|███▊      | 15/39 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1768       640   0.00345    0.0435  0.004823     4.142:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1747       640  0.003437   0.04328  0.004791      4.12:  44%|████▎     | 17/39 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2019       640  0.003434   0.04323  0.004757     4.113:  46%|████▌     | 18/39 [00:34<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1602       640  0.003426   0.04293  0.004753     4.089:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2209       640  0.003428   0.04291  0.004737     4.086:  51%|█████▏    | 20/39 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1896       640  0.003426   0.04286  0.004708      4.08:  54%|█████▍    | 21/39 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1996       640  0.003424   0.04285  0.004707     4.079:  56%|█████▋    | 22/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2001       640  0.003426   0.04288  0.004733     4.083:  59%|█████▉    | 23/39 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640  0.003423   0.04278  0.004729     4.074:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2030       640  0.003423   0.04277  0.004727     4.074:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1772       640  0.003421   0.04257  0.004715     4.057:  67%|██████▋   | 26/39 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.511      0.446      0.414      0.233
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.495      0.447      0.412      0.233
                   0        738       1052      0.479      0.565      0.537      0.257
                   1        738         44      0.486      0.258       0.21     0.0921
                   2        738       8622      0.646      0.745      0.751      0.478
                   3        738        151      0.328      0.464      0.442      0.335
                   4        738        467      0.406      0.627      0.546       0.39
                   5        738         70      0.276      0.414      0.283      0.143
                   6        738         65      0.224      0.138       0.17      0.069
                   7        738       1619      0.513      0.632      0.582      0.242
                   8        738       2845      0.595      0.625      0.603       0.32
                   9        738          2          1          0   0.000256    0.00023

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:08:00.314865016 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31230 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round013_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round013_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client5_residential_night_stable_train' images and labels...4885 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<00:00, 10300.14it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round013_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:08:16.203784804 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:08:16.209795692 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1747       640  0.003444    0.0429  0.005007     4.108:   2%|▎         | 1/40 [00:22<14:23, 22.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1905       640  0.003402   0.04186  0.004894     4.012:   5%|▌         | 2/40 [00:22<06:04,  9.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003379   0.04243  0.004637     4.036:   8%|▊         | 3/40 [00:23<03:27,  5.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003369    0.0419   0.00455     3.986:  10%|█         | 4/40 [00:24<02:14,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1838       640  0.003374   0.04109  0.004556     3.921:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1626       640  0.003384   0.04015  0.004572     3.848:  15%|█▌        | 6/40 [00:25<01:06,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003382   0.03977  0.004608     3.821:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640  0.003388   0.03967    0.0046     3.813:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1926       640  0.003389   0.03968  0.004538     3.808:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003407   0.03937  0.004517     3.783:  25%|██▌       | 10/40 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2196       640  0.003419   0.03941  0.004568     3.791:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003413    0.0393  0.004547     3.781:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1819       640  0.003416   0.03893  0.004589     3.755:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2308       640  0.003418   0.03894  0.004562     3.753:  35%|███▌      | 14/40 [00:31<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1752       640  0.003417   0.03862  0.004542     3.726:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1733       640  0.003414   0.03831  0.004503     3.699:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1817       640  0.003424    0.0381  0.004545     3.686:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003423   0.03796  0.004567     3.676:  45%|████▌     | 18/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1550       640  0.003426   0.03754  0.004552     3.641:  48%|████▊     | 19/40 [00:34<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003428   0.03743  0.004569     3.634:  50%|█████     | 20/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1938       640  0.003427   0.03728  0.004585     3.623:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640  0.003432   0.03722  0.004579     3.619:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003429   0.03715  0.004598     3.614:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1829       640  0.003427   0.03707  0.004595     3.608:  60%|██████    | 24/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003431   0.03696  0.004609       3.6:  62%|██████▎   | 25/40 [00:38<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1781       640  0.003429   0.03676  0.004596     3.583:  65%|██████▌   | 26/40 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.572      0.391      0.411      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.564      0.391      0.408      0.232
                   0        738       1052        0.6      0.511      0.528      0.256
                   1        738         44        0.5     0.0909      0.208     0.0972
                   2        738       8622      0.713      0.713      0.748      0.479
                   3        738        151      0.521      0.397      0.429      0.334
                   4        738        467      0.474       0.57       0.54      0.386
                   5        738         70      0.346      0.386      0.277      0.144
                   6        738         65      0.228     0.0462       0.16     0.0615
                   7        738       1619      0.587      0.602      0.584      0.243
                   8        738       2845       0.67      0.596      0.603       0.32
                   9        738          2          1          0   0.000232   0.000208

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:09:43.683150306 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31231 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round013_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round013_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:10:00.864352229 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:10:00.870578294 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03052   0.03572  0.003745     5.599:   3%|▎         | 1/31 [00:33<16:45, 33.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03115   0.03649  0.003937     5.726:   6%|▋         | 2/31 [00:34<06:53, 14.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03066   0.03548   0.00388     5.601:  10%|▉         | 3/31 [00:35<03:46,  8.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03037   0.03439  0.003706     5.477:  13%|█▎        | 4/31 [00:35<02:20,  5.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.03033   0.03449  0.003724     5.484:  16%|█▌        | 5/31 [00:36<01:31,  3.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03045   0.03442  0.003759      5.49:  19%|█▉        | 6/31 [00:36<01:03,  2.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.03052   0.03415   0.00381     5.479:  23%|██▎       | 7/31 [00:37<00:45,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.03044   0.03421  0.003806     5.477:  26%|██▌       | 8/31 [00:38<00:33,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.03051   0.03414  0.003722      5.47:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.03054    0.0343  0.003705     5.484:  32%|███▏      | 10/31 [00:39<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640    0.0305   0.03434  0.003726     5.485:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.03042   0.03408  0.003723     5.458:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.03039   0.03407  0.003672     5.451:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.03042   0.03396  0.003642     5.442:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.03044   0.03388  0.003691     5.441:  48%|████▊     | 15/31 [00:42<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.03044   0.03378  0.003688     5.433:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.03048   0.03381  0.003666     5.437:  55%|█████▍    | 17/31 [00:43<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03057   0.03394   0.00364     5.452:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.03053   0.03384  0.003615     5.439:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03054   0.03406  0.003612     5.458:  65%|██████▍   | 20/31 [00:45<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03059   0.03413  0.003631     5.468:  68%|██████▊   | 21/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03062   0.03425  0.003608     5.478:  71%|███████   | 22/31 [00:46<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03062   0.03432  0.003585     5.482:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03066   0.03444  0.003577     5.494:  77%|███████▋  | 24/31 [00:47<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03069   0.03444  0.003589     5.497:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03077   0.03453  0.003599     5.512:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.517      0.441      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.502      0.443      0.409       0.23
                   0        738       1052      0.492      0.554      0.529      0.255
                   1        738         44      0.437       0.25      0.201     0.0877
                   2        738       8622      0.641      0.746       0.75      0.485
                   3        738        151      0.344      0.444      0.432      0.324
                   4        738        467      0.457        0.6       0.54      0.386
                   5        738         70      0.256      0.414      0.294      0.143
                   6        738         65      0.275      0.169      0.166     0.0663
                   7        738       1619       0.53      0.627      0.581      0.243
                   8        738       2845      0.586      0.622      0.597      0.313
                   9        738          2          1          0   0.000377    0.00034

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round013_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 17:11:40.840145260 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round014 phase_round=14 ===

02 head-to-full DQA:  41%|████      | 13/32 [3:04:22<4:28:34, 848.12s/round, elapsed=3h04m22s, eta=4h29m27s, phase=phase1_head, round=13]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round014 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round014 client0_highway_day: pseudo scan 250/1500 images, kept 2381 boxes
round014 client0_highway_day: pseudo scan 500/1500 images, kept 4827 boxes
round014 client0_highway_day: pseudo scan 750/1500 images, kept 7185 boxes
round014 client0_highway_day: pseudo scan 1000/1500 images, kept 9571 boxes
round014 client0_highway_day: pseudo scan 1250/1500 images, kept 11915 boxes
round014 client0_highway_day: pseudo scan 1500/1500 images, kept 14321 boxes
{
  "round": "round014",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round013_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1494,
  "pseudo_boxes_kept": 11264,
  "boxes_per_kept_image": 7.539491298527443,
  "mean_conf": 0.8157456210147674,
  "mean_stability": 0.9506482297649861,
  "mean_score": 0.7788471623116332,
  "class_counts": {
    "0": 163,
    "2": 6445,
    "3": 118,
    "4": 563,
    "5": 6,
    "7": 565,
    "8": 3404
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_client0_highway_day_stable_boxes.csv"
}
round014 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round014 client1_highway_night: pseudo scan 250/1500 images, kept 1610 boxes
round014 client1_highway_night: pseudo scan 500/1500 images, kept 3325 boxes
round014 client1_highway_night: pseudo scan 750/1500 images, kept 5069 boxes
round014 client1_highway_night: pseudo scan 1000/1500 images, kept 6699 boxes
round014 client1_highway_night: pseudo scan 1250/1500 images, kept 8382 boxes
round014 client1_highway_night: pseudo scan 1500/1500 images, kept 10012 boxes
{
  "round": "round014",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round013_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1451,
  "pseudo_boxes_kept": 8243,
  "boxes_per_kept_image": 5.680909717436251,
  "mean_conf": 0.729797856919499,
  "mean_stability": 0.9336761088318057,
  "mean_score": 0.6856034324255811,
  "class_counts": {
    "0": 65,
    "2": 4506,
    "3": 30,
    "4": 146,
    "5": 7,
    "7": 596,
    "8": 2893
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_client1_highway_night_stable_boxes.csv"
}
round014 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round014 client2_citystreet_day: pseudo scan 250/1500 images, kept 2697 boxes
round014 client2_citystreet_day: pseudo scan 500/1500 images, kept 5434 boxes
round014 client2_citystreet_day: pseudo scan 750/1500 images, kept 8178 boxes
round014 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10941 boxes
round014 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13667 boxes
round014 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16328 boxes
{
  "round": "round014",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round013_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13794,
  "boxes_per_kept_image": 9.220588235294118,
  "mean_conf": 0.8156210973813462,
  "mean_stability": 0.9484622997011812,
  "mean_score": 0.7771249942914921,
  "class_counts": {
    "0": 1467,
    "2": 7348,
    "3": 200,
    "4": 597,
    "5": 68,
    "7": 1517,
    "8": 2597
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_client2_citystreet_day_stable_boxes.csv"
}
round014 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round014 client3_citystreet_night: pseudo scan 250/1500 images, kept 2344 boxes
round014 client3_citystreet_night: pseudo scan 500/1500 images, kept 4638 boxes
round014 client3_citystreet_night: pseudo scan 750/1500 images, kept 6923 boxes
round014 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9127 boxes
round014 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11524 boxes
round014 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13822 boxes
{
  "round": "round014",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round013_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1473,
  "pseudo_boxes_kept": 11715,
  "boxes_per_kept_image": 7.95315682281059,
  "mean_conf": 0.7246412237663326,
  "mean_stability": 0.9295866949711913,
  "mean_score": 0.6781528252808701,
  "class_counts": {
    "0": 545,
    "2": 6220,
    "3": 71,
    "4": 154,
    "5": 37,
    "7": 2058,
    "8": 2630
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_client3_citystreet_night_stable_boxes.csv"
}
round014 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round014 client4_residential_day: pseudo scan 250/1500 images, kept 2589 boxes
round014 client4_residential_day: pseudo scan 500/1500 images, kept 5191 boxes
round014 client4_residential_day: pseudo scan 750/1500 images, kept 7744 boxes
round014 client4_residential_day: pseudo scan 1000/1500 images, kept 10229 boxes
round014 client4_residential_day: pseudo scan 1250/1500 images, kept 12750 boxes
round014 client4_residential_day: pseudo scan 1500/1500 images, kept 15231 boxes
{
  "round": "round014",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round013_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 10009,
  "boxes_per_kept_image": 6.71744966442953,
  "mean_conf": 0.8483076941563255,
  "mean_stability": 0.9570886491299961,
  "mean_score": 0.8153649549986387,
  "class_counts": {
    "0": 389,
    "2": 6854,
    "3": 68,
    "4": 312,
    "5": 45,
    "7": 534,
    "8": 1807
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_client4_residential_day_stable_boxes.csv"
}
round014 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round014 client5_residential_night: pseudo scan 250/1500 images, kept 2277 boxes
round014 client5_residential_night: pseudo scan 500/1500 images, kept 4539 boxes
round014 client5_residential_night: pseudo scan 750/1500 images, kept 6797 boxes
round014 client5_residential_night: pseudo scan 1000/1500 images, kept 9106 boxes
round014 client5_residential_night: pseudo scan 1250/1500 images, kept 11433 boxes
round014 client5_residential_night: pseudo scan 1500/1500 images, kept 13750 boxes
{
  "round": "round014",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round013_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1474,
  "pseudo_boxes_kept": 8580,
  "boxes_per_kept_image": 5.82089552238806,
  "mean_conf": 0.7937984914143325,
  "mean_stability": 0.9446158641423934,
  "mean_score": 0.7529418535048843,
  "class_counts": {
    "0": 132,
    "2": 6188,
    "3": 33,
    "4": 101,
    "5": 24,
    "7": 676,
    "8": 1426
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round014_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31232 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round014_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round014_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7869 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client0_highway_day_stable_train' images and labels...5361 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<00:00, 13607.32it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:13:56.486355716 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:13:56.519636129 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2068       640  0.003442   0.04262   0.00455     4.049:   3%|▎         | 1/39 [00:22<14:14, 22.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2014       640   0.00345   0.04295  0.004267     4.054:   5%|▌         | 2/39 [00:23<06:02,  9.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2013       640  0.003482   0.04363  0.004382     4.119:   8%|▊         | 3/39 [00:24<03:25,  5.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2081       640  0.003445    0.0437  0.004579     4.138:  10%|█         | 4/39 [00:25<02:12,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1852       640  0.003429   0.04305  0.004619     4.088:  13%|█▎        | 5/39 [00:25<01:31,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1711       640  0.003421   0.04208  0.004558     4.005:  15%|█▌        | 6/39 [00:26<01:06,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1997       640  0.003418   0.04209   0.00453     4.003:  18%|█▊        | 7/39 [00:27<00:50,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2084       640  0.003411   0.04239  0.004604     4.032:  21%|██        | 8/39 [00:27<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2135       640  0.003417   0.04293  0.004668     4.081:  23%|██▎       | 9/39 [00:28<00:32,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2169       640  0.003429   0.04322  0.004675     4.106:  26%|██▌       | 10/39 [00:29<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2061       640  0.003417   0.04306  0.004604     4.086:  28%|██▊       | 11/39 [00:29<00:24,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1868       640  0.003418   0.04285  0.004612     4.071:  31%|███       | 12/39 [00:30<00:21,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2072       640  0.003424   0.04268  0.004607     4.057:  33%|███▎      | 13/39 [00:31<00:19,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2233       640   0.00343   0.04285  0.004566     4.068:  36%|███▌      | 14/39 [00:31<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1954       640   0.00342   0.04268  0.004539     4.051:  38%|███▊      | 15/39 [00:32<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2042       640  0.003425   0.04259  0.004554     4.046:  41%|████      | 16/39 [00:33<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1766       640  0.003425   0.04229  0.004557     4.022:  44%|████▎     | 17/39 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1986       640  0.003428   0.04225  0.004553     4.019:  46%|████▌     | 18/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1720       640  0.003424   0.04206  0.004559     4.003:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2386       640  0.003427   0.04216  0.004564     4.012:  51%|█████▏    | 20/39 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2046       640  0.003429   0.04219  0.004547     4.013:  54%|█████▍    | 21/39 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1853       640  0.003429   0.04207  0.004523     4.001:  56%|█████▋    | 22/39 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2251       640   0.00343    0.0421  0.004494     4.002:  59%|█████▉    | 23/39 [00:37<00:10,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2088       640  0.003431   0.04205  0.004482     3.997:  62%|██████▏   | 24/39 [00:38<00:09,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2046       640  0.003426   0.04195  0.004471     3.987:  64%|██████▍   | 25/39 [00:38<00:09,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2154       640  0.003424   0.04194  0.004465     3.986:  67%|██████▋   | 26/39 [00:39<00:08,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.514      0.443      0.414      0.233
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.545      0.414      0.413      0.233
                   0        738       1052      0.525      0.555       0.54       0.26
                   1        738         44      0.466      0.159      0.218     0.0914
                   2        738       8622      0.697      0.731      0.753      0.481
                   3        738        151      0.504      0.397      0.425      0.326
                   4        738        467      0.489       0.58       0.54      0.386
                   5        738         70      0.302      0.414      0.287      0.153
                   6        738         65       0.26     0.0769       0.17     0.0683
                   7        738       1619      0.554      0.624      0.591      0.243
                   8        738       2845       0.65      0.601      0.606       0.32
                   9        738          2          1          0    0.00034   0.000306

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:15:21.069892453 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31233 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round014_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round014_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client1_highway_night_stable_train' images and labels...556 found, 1480 missing, 0 empty, 0 corrupted:  26%|██▌       | 2036/7783 [00:00<00:00, 19665.72it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client1_highway_night_stable_train' images and labels...4895 found, 2888 missing, 0 empty, 0 corrupted: 100%|██████████| 7783/7783 [00:00<00:00, 11078.70it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.355415019762846
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2888 missing, 0 empty, 0 corrupted: 100%|██████████| 7783/7783 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:15:37.998478954 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:15:37.112761748 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2085       640  0.003413   0.04217  0.004388     3.998:   2%|▎         | 1/40 [00:22<14:39, 22.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003402    0.0422  0.004788     4.031:   5%|▌         | 2/40 [00:23<06:13,  9.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640   0.00339   0.04095  0.004684     3.922:   8%|▊         | 3/40 [00:24<03:32,  5.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640  0.003413      0.04  0.004733     3.851:  10%|█         | 4/40 [00:25<02:17,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003409   0.03976  0.004631     3.824:  12%|█▎        | 5/40 [00:25<01:33,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1763       640  0.003404   0.03928  0.004415     3.768:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2071       640  0.003413   0.03937  0.004625     3.793:  18%|█▊        | 7/40 [00:27<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640  0.003414   0.03931  0.004578     3.784:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003416   0.03917   0.00454      3.77:  22%|██▎       | 9/40 [00:28<00:33,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003417   0.03891  0.004558     3.751:  25%|██▌       | 10/40 [00:29<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2195       640  0.003427   0.03896  0.004584     3.758:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003427   0.03855  0.004576     3.724:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1813       640  0.003426    0.0382  0.004574     3.696:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1784       640  0.003428   0.03787  0.004566     3.669:  35%|███▌      | 14/40 [00:31<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1815       640  0.003427   0.03758   0.00458     3.647:  38%|███▊      | 15/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1888       640  0.003423   0.03745  0.004575     3.636:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1878       640  0.003424   0.03732  0.004541     3.623:  42%|████▎     | 17/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1932       640  0.003425   0.03711  0.004546     3.606:  45%|████▌     | 18/40 [00:34<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1693       640  0.003421   0.03676   0.00452     3.576:  48%|████▊     | 19/40 [00:34<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2112       640   0.00342   0.03686  0.004505     3.583:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1815       640  0.003425   0.03662  0.004488     3.562:  52%|█████▎    | 21/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1796       640  0.003421   0.03652  0.004486     3.554:  55%|█████▌    | 22/40 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1944       640   0.00342   0.03643  0.004466     3.545:  57%|█████▊    | 23/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003419   0.03639  0.004487     3.544:  60%|██████    | 24/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003419   0.03628  0.004483     3.535:  62%|██████▎   | 25/40 [00:38<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1953       640  0.003419   0.03625  0.004503     3.534:  65%|██████▌   | 26/40 [00:39<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.433      0.411      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.521      0.435      0.408      0.232
                   0        738       1052      0.528      0.549      0.533      0.257
                   1        738         44      0.478      0.229      0.207     0.0984
                   2        738       8622      0.652      0.739      0.751      0.481
                   3        738        151      0.405       0.43      0.428      0.331
                   4        738        467      0.451      0.606      0.535       0.38
                   5        738         70      0.289      0.429      0.276      0.146
                   6        738         65      0.249      0.123      0.165     0.0641
                   7        738       1619       0.54      0.632      0.586      0.243
                   8        738       2845      0.616      0.611      0.599      0.314
                   9        738          2          1          0   0.000266   0.000239

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:17:02.267986939 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31234 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round014_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round014_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 11533.83it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:17:18.674737367 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:17:18.677208331 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640   0.00353   0.05261  0.004591     4.859:   3%|▎         | 1/39 [00:21<13:50, 21.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003483   0.05162  0.004954     4.804:   5%|▌         | 2/39 [00:22<05:52,  9.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003446   0.05053  0.004976     4.717:   8%|▊         | 3/39 [00:23<03:20,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003456   0.04943  0.004893     4.623:  10%|█         | 4/39 [00:24<02:09,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003454   0.04881  0.004815     4.566:  13%|█▎        | 5/39 [00:25<01:29,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640   0.00342   0.04767  0.004779     4.469:  15%|█▌        | 6/39 [00:25<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003429   0.04734  0.004836     4.448:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640   0.00342   0.04691  0.004788      4.41:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003435   0.04687  0.004723     4.402:  23%|██▎       | 9/39 [00:27<00:32,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003421   0.04656  0.004714     4.376:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003424   0.04644  0.004708     4.365:  28%|██▊       | 11/39 [00:29<00:24,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003428   0.04593  0.004718     4.326:  31%|███       | 12/39 [00:29<00:21,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003435   0.04575  0.004681      4.31:  33%|███▎      | 13/39 [00:30<00:19,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003444   0.04574  0.004645     4.306:  36%|███▌      | 14/39 [00:31<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003445   0.04554  0.004619     4.289:  38%|███▊      | 15/39 [00:31<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003436   0.04521   0.00461      4.26:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003427   0.04496  0.004634     4.242:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003419   0.04487  0.004619     4.233:  46%|████▌     | 18/39 [00:33<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003421   0.04459  0.004602     4.209:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003416   0.04457  0.004594     4.206:  51%|█████▏    | 20/39 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003408   0.04439  0.004573     4.189:  54%|█████▍    | 21/39 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003403   0.04429  0.004561      4.18:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003395   0.04417  0.004561      4.17:  59%|█████▉    | 23/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003391    0.0441   0.00455     4.163:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003388   0.04399  0.004549     4.154:  64%|██████▍   | 25/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003382   0.04394  0.004532     4.148:  67%|██████▋   | 26/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.513      0.441       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]

                 all        738      14937      0.501      0.445      0.409       0.23
                   0        738       1052      0.561      0.542      0.537      0.253
                   1        738         44      0.496      0.273      0.197     0.0906
                   2        738       8622      0.611      0.757      0.755       0.48
                   3        738        151      0.302       0.45       0.43      0.325
                   4        738        467      0.412      0.625      0.535      0.381
                   5        738         70      0.298      0.414      0.277      0.144
                   6        738         65      0.227      0.122      0.171      0.072
                   7        738       1619      0.519      0.639      0.584       0.24
                   8        738       2845       0.58      0.623      0.602      0.319
                   9        738          2          1          0   0.000267    0.00024

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:18:44.363878897 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31235 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round014_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round014_phase1_head_client3_citystreet_night_start.pt

self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7827 [00:00<?, ?it/s]

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client3_citystreet_night_stable_train' images and labels...4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<00:00, 9150.19it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.287738076499291
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:19:01.648390893 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:19:01.707846895 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1810       640  0.003461   0.04391  0.003841     4.097:   2%|▎         | 1/40 [00:21<14:04, 21.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1693       640   0.00341   0.04316  0.004698     4.101:   5%|▌         | 2/40 [00:22<05:58,  9.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1961       640  0.003377   0.04298  0.004457     4.065:   8%|▊         | 3/40 [00:23<03:24,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1869       640  0.003341   0.04233   0.00434     4.001:  10%|█         | 4/40 [00:24<02:12,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003334   0.04152  0.004508     3.949:  12%|█▎        | 5/40 [00:24<01:30,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003339   0.04093  0.004467     3.898:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003342    0.0408  0.004433     3.886:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2100       640  0.003351     0.041  0.004467     3.906:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003356   0.04079   0.00445     3.888:  22%|██▎       | 9/40 [00:27<00:32,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1813       640  0.003362   0.04045  0.004477     3.863:  25%|██▌       | 10/40 [00:28<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003366   0.04029  0.004469      3.85:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1859       640  0.003371   0.04014  0.004469     3.838:  30%|███       | 12/40 [00:29<00:21,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003371   0.03991  0.004481     3.821:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2168       640  0.003373      0.04   0.00448     3.828:  35%|███▌      | 14/40 [00:30<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1774       640  0.003369   0.03964  0.004472     3.798:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1833       640   0.00336   0.03941  0.004427     3.776:  40%|████      | 16/40 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1640       640  0.003368   0.03899   0.00445     3.745:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1873       640  0.003369   0.03877  0.004459     3.728:  45%|████▌     | 18/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1732       640   0.00337   0.03845  0.004427       3.7:  48%|████▊     | 19/40 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003373   0.03841  0.004423     3.697:  50%|█████     | 20/40 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003386   0.03834  0.004449     3.694:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1858       640  0.003386    0.0383  0.004435     3.689:  55%|█████▌    | 22/40 [00:35<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2130       640  0.003386   0.03825  0.004434     3.686:  57%|█████▊    | 23/40 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003388   0.03821  0.004452     3.684:  60%|██████    | 24/40 [00:37<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2007       640  0.003388   0.03813  0.004438     3.676:  62%|██████▎   | 25/40 [00:37<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003386   0.03798  0.004436     3.664:  65%|██████▌   | 26/40 [00:38<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.578      0.398      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.564      0.401      0.408       0.23
                   0        738       1052      0.608      0.507      0.531      0.255
                   1        738         44       0.55      0.114       0.22     0.0986
                   2        738       8622      0.696      0.716      0.746      0.478
                   3        738        151      0.467      0.411      0.431      0.327
                   4        738        467      0.447      0.604      0.536      0.379
                   5        738         70      0.377        0.4      0.279      0.142
                   6        738         65       0.28     0.0615      0.158     0.0669
                   7        738       1619      0.562      0.611      0.583      0.243
                   8        738       2845      0.654      0.589      0.596      0.315
                   9        738          2          1          0   0.000238   0.000214

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:20:25.344886343 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31236 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round014_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round014_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 15497.63it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:20:40.196661083 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:20:40.212439884 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2153       640  0.003464   0.05166  0.004785     4.793:   3%|▎         | 1/39 [00:22<14:01, 22.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2109       640   0.00342   0.05038  0.005168     4.718:   5%|▌         | 2/39 [00:22<05:55,  9.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1782       640  0.003367   0.04855  0.005042     4.557:   8%|▊         | 3/39 [00:23<03:22,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003363   0.04798  0.004961     4.504:  10%|█         | 4/39 [00:24<02:11,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003354   0.04692  0.004956     4.418:  13%|█▎        | 5/39 [00:25<01:30,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1759       640   0.00335   0.04557  0.005036     4.316:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003369   0.04534  0.004985     4.295:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2179       640  0.003382   0.04509  0.004874     4.267:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2090       640  0.003383   0.04517  0.004818      4.27:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003387   0.04501  0.004805     4.256:  26%|██▌       | 10/39 [00:28<00:27,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640  0.003397   0.04501   0.00478     4.255:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2189       640  0.003413   0.04489  0.004823      4.25:  31%|███       | 12/39 [00:30<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003418   0.04483  0.004803     4.244:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003424   0.04472  0.004802     4.236:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640   0.00343   0.04447  0.004823     4.218:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003424   0.04415    0.0048      4.19:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003419   0.04398   0.00476     4.172:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003415   0.04396  0.004724     4.168:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003418   0.04364  0.004732     4.143:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003409    0.0436  0.004721     4.138:  51%|█████▏    | 20/39 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003403   0.04349  0.004688     4.126:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003402   0.04343  0.004689     4.122:  56%|█████▋    | 22/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003401    0.0434    0.0047      4.12:  59%|█████▉    | 23/39 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003396   0.04324  0.004691     4.106:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003397   0.04313  0.004684     4.097:  64%|██████▍   | 25/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003395   0.04301  0.004657     4.085:  67%|██████▋   | 26/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.518      0.444      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.25it/s]

                 all        738      14937      0.503      0.445      0.412      0.232
                   0        738       1052      0.493      0.567      0.539      0.257
                   1        738         44      0.496      0.273      0.212     0.0902
                   2        738       8622      0.652      0.743      0.751      0.478
                   3        738        151      0.345       0.45      0.438      0.329
                   4        738        467      0.425      0.616      0.542      0.385
                   5        738         70      0.271      0.414      0.286      0.152
                   6        738         65      0.226      0.135      0.167     0.0674
                   7        738       1619      0.527      0.637      0.585      0.241
                   8        738       2845      0.598       0.62        0.6       0.32
                   9        738          2          1          0   0.000244    0.00022

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:22:05.696749178 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31237 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round014_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round014_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client5_residential_night_stable_train' images and labels...:   0%|          | 0/7829 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client5_residential_night_stable_train' images and labels...4885 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<00:00, 10263.36it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.287738076499291
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round014_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:22:22.488625644 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:22:22.613830978 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1898       640  0.003522   0.04465  0.004285     4.196:   2%|▎         | 1/40 [00:22<14:27, 22.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1824       640  0.003419   0.04207  0.004267     3.981:   5%|▌         | 2/40 [00:23<06:07,  9.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1992       640  0.003384   0.04265  0.004321     4.028:   8%|▊         | 3/40 [00:24<03:30,  5.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1797       640   0.00335   0.04183  0.004301     3.958:  10%|█         | 4/40 [00:24<02:16,  3.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1760       640  0.003358   0.04076  0.004268     3.871:  12%|█▎        | 5/40 [00:25<01:33,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003377   0.04021  0.004334     3.834:  15%|█▌        | 6/40 [00:26<01:07,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1733       640  0.003381   0.03943  0.004426     3.779:  18%|█▊        | 7/40 [00:26<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1940       640  0.003381   0.03929  0.004411     3.766:  20%|██        | 8/40 [00:27<00:41,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1828       640  0.003377   0.03909  0.004354     3.746:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1831       640  0.003388   0.03881  0.004402     3.728:  25%|██▌       | 10/40 [00:28<00:28,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2069       640  0.003396   0.03899  0.004448     3.747:  28%|██▊       | 11/40 [00:29<00:25,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1935       640  0.003389   0.03897  0.004424     3.742:  30%|███       | 12/40 [00:30<00:22,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1996       640   0.00339   0.03875  0.004425     3.725:  32%|███▎      | 13/40 [00:30<00:20,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2103       640  0.003394   0.03886  0.004438     3.735:  35%|███▌      | 14/40 [00:31<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1920       640  0.003396   0.03857  0.004413      3.71:  38%|███▊      | 15/40 [00:32<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1653       640  0.003388   0.03813  0.004415     3.675:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1806       640  0.003391   0.03793  0.004465     3.663:  42%|████▎     | 17/40 [00:33<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1908       640  0.003392   0.03781  0.004468     3.653:  45%|████▌     | 18/40 [00:34<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1622       640  0.003398   0.03743  0.004467     3.623:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2036       640  0.003408    0.0374  0.004478     3.622:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2044       640  0.003415   0.03729  0.004524     3.619:  52%|█████▎    | 21/40 [00:36<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1960       640  0.003419   0.03732  0.004551     3.623:  55%|█████▌    | 22/40 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2087       640  0.003418   0.03734  0.004573     3.626:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1962       640  0.003425    0.0373  0.004601     3.626:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1938       640  0.003427   0.03716  0.004625     3.617:  62%|██████▎   | 25/40 [00:38<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1842       640  0.003427   0.03709  0.004632     3.612:  65%|██████▌   | 26/40 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.532      0.418      0.411      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.519      0.419      0.409      0.231
                   0        738       1052      0.557      0.527      0.532      0.255
                   1        738         44      0.497      0.202      0.209     0.0986
                   2        738       8622      0.669      0.728      0.747       0.48
                   3        738        151      0.403      0.411      0.426      0.325
                   4        738        467      0.437      0.602      0.541      0.383
                   5        738         70      0.272        0.4      0.282      0.141
                   6        738         65      0.201     0.0769      0.156     0.0622
                   7        738       1619      0.546      0.629       0.59      0.242
                   8        738       2845      0.614      0.618      0.604      0.319
                   9        738          2          1          0   0.000205   0.000184

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 17:23:50.305533411 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31238 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round014_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round014_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:24:07.255879084 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:24:07.260731669 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03059   0.03576  0.003739     5.607:   3%|▎         | 1/31 [00:31<15:46, 31.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03107   0.03624  0.003891     5.697:   6%|▋         | 2/31 [00:32<06:35, 13.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03053   0.03516  0.003825     5.561:  10%|▉         | 3/31 [00:33<03:37,  7.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03018   0.03398  0.003638     5.424:  13%|█▎        | 4/31 [00:34<02:14,  5.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.03013   0.03407  0.003652     5.428:  16%|█▌        | 5/31 [00:34<01:28,  3.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03023   0.03397  0.003686     5.431:  19%|█▉        | 6/31 [00:35<01:01,  2.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640    0.0303    0.0337  0.003736     5.419:  23%|██▎       | 7/31 [00:35<00:44,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.03021   0.03375  0.003732     5.415:  26%|██▌       | 8/31 [00:36<00:33,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.03028   0.03367   0.00365     5.408:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640    0.0303   0.03382  0.003631      5.42:  32%|███▏      | 10/31 [00:37<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.03027   0.03385  0.003651     5.421:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.03019   0.03359  0.003648     5.394:  39%|███▊      | 12/31 [00:38<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.03016   0.03358  0.003598     5.386:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.03018   0.03347  0.003569     5.377:  45%|████▌     | 14/31 [00:39<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640    0.0302   0.03338  0.003616     5.376:  48%|████▊     | 15/31 [00:40<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.03021   0.03327  0.003615     5.368:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.03024   0.03331  0.003593     5.371:  55%|█████▍    | 17/31 [00:41<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03033   0.03344  0.003566     5.386:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.03029   0.03333  0.003542     5.374:  61%|██████▏   | 19/31 [00:42<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03031   0.03356  0.003539     5.393:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03036   0.03363  0.003558     5.403:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03039   0.03375  0.003536     5.414:  71%|███████   | 22/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03039   0.03382  0.003514     5.418:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03043   0.03395  0.003506     5.431:  77%|███████▋  | 24/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03046   0.03394  0.003518     5.434:  81%|████████  | 25/31 [00:46<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03054   0.03404  0.003528     5.449:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.519      0.437      0.411      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]

                 all        738      14937      0.505      0.438      0.408      0.229
                   0        738       1052      0.495      0.548      0.527      0.253
                   1        738         44      0.411      0.227        0.2     0.0858
                   2        738       8622      0.647      0.743      0.749      0.484
                   3        738        151      0.361      0.444      0.433      0.325
                   4        738        467      0.459      0.591      0.537       0.38
                   5        738         70      0.276      0.414      0.294      0.141
                   6        738         65      0.282      0.169      0.168     0.0658
                   7        738       1619      0.532      0.626      0.582      0.242
                   8        738       2845       0.59      0.619      0.594      0.312
                   9        738          2          1          0   0.000385   0.000347

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round014_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 17:25:45.887088303 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round015 phase_round=15 ===

02 head-to-full DQA:  44%|████▍     | 14/32 [3:18:27<4:14:09, 847.19s/round, elapsed=3h18m27s, eta=4h15m09s, phase=phase1_head, round=14]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round015 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round015 client0_highway_day: pseudo scan 250/1500 images, kept 2373 boxes
round015 client0_highway_day: pseudo scan 500/1500 images, kept 4802 boxes
round015 client0_highway_day: pseudo scan 750/1500 images, kept 7153 boxes
round015 client0_highway_day: pseudo scan 1000/1500 images, kept 9535 boxes
round015 client0_highway_day: pseudo scan 1250/1500 images, kept 11873 boxes
round015 client0_highway_day: pseudo scan 1500/1500 images, kept 14272 boxes
{
  "round": "round015",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round014_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1494,
  "pseudo_boxes_kept": 11231,
  "boxes_per_kept_image": 7.517402945113789,
  "mean_conf": 0.8178696608396918,
  "mean_stability": 0.9500094938072281,
  "mean_score": 0.7803559134792969,
  "class_counts": {
    "0": 158,
    "2": 6423,
    "3": 118,
    "4": 566,
    "5": 8,
    "7": 562,
    "8": 3396
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_client0_highway_day_stable_boxes.csv"
}
round015 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round015 client1_highway_night: pseudo scan 250/1500 images, kept 1601 boxes
round015 client1_highway_night: pseudo scan 500/1500 images, kept 3307 boxes
round015 client1_highway_night: pseudo scan 750/1500 images, kept 5042 boxes
round015 client1_highway_night: pseudo scan 1000/1500 images, kept 6659 boxes
round015 client1_highway_night: pseudo scan 1250/1500 images, kept 8332 boxes
round015 client1_highway_night: pseudo scan 1500/1500 images, kept 9950 boxes
{
  "round": "round015",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round014_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1450,
  "pseudo_boxes_kept": 8213,
  "boxes_per_kept_image": 5.664137931034483,
  "mean_conf": 0.7317532572736988,
  "mean_stability": 0.9328832340911059,
  "mean_score": 0.6868253801236038,
  "class_counts": {
    "0": 65,
    "2": 4478,
    "3": 30,
    "4": 146,
    "5": 6,
    "7": 607,
    "8": 2881
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_client1_highway_night_stable_boxes.csv"
}
round015 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round015 client2_citystreet_day: pseudo scan 250/1500 images, kept 2699 boxes
round015 client2_citystreet_day: pseudo scan 500/1500 images, kept 5426 boxes
round015 client2_citystreet_day: pseudo scan 750/1500 images, kept 8165 boxes
round015 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10921 boxes
round015 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13645 boxes
round015 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16307 boxes
{
  "round": "round015",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round014_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13790,
  "boxes_per_kept_image": 9.217914438502675,
  "mean_conf": 0.817157184822651,
  "mean_stability": 0.9480464556063319,
  "mean_score": 0.7781937409461215,
  "class_counts": {
    "0": 1468,
    "2": 7339,
    "3": 206,
    "4": 597,
    "5": 62,
    "7": 1520,
    "8": 2598
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_client2_citystreet_day_stable_boxes.csv"
}
round015 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round015 client3_citystreet_night: pseudo scan 250/1500 images, kept 2325 boxes
round015 client3_citystreet_night: pseudo scan 500/1500 images, kept 4609 boxes
round015 client3_citystreet_night: pseudo scan 750/1500 images, kept 6870 boxes
round015 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9041 boxes
round015 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11422 boxes
round015 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13700 boxes
{
  "round": "round015",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round014_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 11655,
  "boxes_per_kept_image": 7.901694915254238,
  "mean_conf": 0.7265655922051,
  "mean_stability": 0.928821463494892,
  "mean_score": 0.679401079874441,
  "class_counts": {
    "0": 541,
    "2": 6165,
    "3": 73,
    "4": 156,
    "5": 35,
    "7": 2084,
    "8": 2601
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_client3_citystreet_night_stable_boxes.csv"
}
round015 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round015 client4_residential_day: pseudo scan 250/1500 images, kept 2589 boxes
round015 client4_residential_day: pseudo scan 500/1500 images, kept 5191 boxes
round015 client4_residential_day: pseudo scan 750/1500 images, kept 7745 boxes
round015 client4_residential_day: pseudo scan 1000/1500 images, kept 10230 boxes
round015 client4_residential_day: pseudo scan 1250/1500 images, kept 12749 boxes
round015 client4_residential_day: pseudo scan 1500/1500 images, kept 15223 boxes
{
  "round": "round015",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round014_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9995,
  "boxes_per_kept_image": 6.708053691275167,
  "mean_conf": 0.8498257470345605,
  "mean_stability": 0.9564432030084313,
  "mean_score": 0.8163108392323974,
  "class_counts": {
    "0": 382,
    "2": 6851,
    "3": 68,
    "4": 317,
    "5": 45,
    "7": 541,
    "8": 1791
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_client4_residential_day_stable_boxes.csv"
}
round015 client5_residential_night: pseudo scan 1/1500 images, kept 9 boxes
round015 client5_residential_night: pseudo scan 250/1500 images, kept 2264 boxes
round015 client5_residential_night: pseudo scan 500/1500 images, kept 4506 boxes
round015 client5_residential_night: pseudo scan 750/1500 images, kept 6742 boxes
round015 client5_residential_night: pseudo scan 1000/1500 images, kept 9034 boxes
round015 client5_residential_night: pseudo scan 1250/1500 images, kept 11338 boxes
round015 client5_residential_night: pseudo scan 1500/1500 images, kept 13624 boxes
{
  "round": "round015",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round014_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1473,
  "pseudo_boxes_kept": 8517,
  "boxes_per_kept_image": 5.782077393075356,
  "mean_conf": 0.7952214324398753,
  "mean_stability": 0.9439725174693361,
  "mean_score": 0.7537518725195641,
  "class_counts": {
    "0": 126,
    "2": 6131,
    "3": 34,
    "4": 97,
    "5": 22,
    "7": 684,
    "8": 1423
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round015_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31239 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round015_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round015_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client0_highway_day_stable_train' images and labels...5361 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<00:00, 13160.76it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:28:01.072835487 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:28:01.090509861 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2068       640  0.003447   0.04286  0.004538     4.067:   3%|▎         | 1/39 [00:21<13:45, 21.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003455   0.04314  0.004247     4.067:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003486   0.04378  0.004361      4.13:   8%|▊         | 3/39 [00:23<03:22,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640   0.00345   0.04384   0.00456     4.148:  10%|█         | 4/39 [00:24<02:11,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003433   0.04317  0.004601     4.096:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003425   0.04219  0.004541     4.012:  15%|█▌        | 6/39 [00:25<01:05,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003421   0.04219  0.004516      4.01:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003415   0.04248  0.004591     4.039:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003421   0.04303  0.004656     4.088:  23%|██▎       | 9/39 [00:27<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003433   0.04332  0.004662     4.113:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003421   0.04314  0.004591     4.092:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003422   0.04293    0.0046     4.076:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003427   0.04276  0.004595     4.063:  33%|███▎      | 13/39 [00:30<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003433   0.04293  0.004553     4.073:  36%|███▌      | 14/39 [00:31<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003424   0.04275  0.004528     4.056:  38%|███▊      | 15/39 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003429   0.04265  0.004542      4.05:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003428   0.04235  0.004545     4.026:  44%|████▎     | 17/39 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003432   0.04231   0.00454     4.023:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003428   0.04211  0.004546     4.007:  49%|████▊     | 19/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003431   0.04221   0.00455     4.015:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003432   0.04224  0.004533     4.016:  54%|█████▍    | 21/39 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003433   0.04212  0.004509     4.005:  56%|█████▋    | 22/39 [00:36<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003433   0.04214   0.00448     4.005:  59%|█████▉    | 23/39 [00:36<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003434    0.0421  0.004468         4:  62%|██████▏   | 24/39 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003429   0.04199  0.004457      3.99:  64%|██████▍   | 25/39 [00:37<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640  0.003427   0.04198  0.004451     3.989:  67%|██████▋   | 26/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.573       0.41      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.557      0.413      0.413      0.232
                   0        738       1052      0.532       0.55      0.538      0.258
                   1        738         44      0.535      0.157      0.223     0.0929
                   2        738       8622      0.703      0.729      0.752      0.481
                   3        738        151      0.518      0.404      0.424      0.325
                   4        738        467      0.492      0.576      0.537      0.384
                   5        738         70      0.303      0.414      0.289      0.152
                   6        738         65      0.274     0.0769      0.169     0.0688
                   7        738       1619       0.56      0.622      0.591      0.243
                   8        738       2845      0.656      0.596      0.604      0.319
                   9        738          2          1          0   0.000343   0.000309

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:29:27.444474068 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31240 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round015_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round015_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client1_highway_night_stable_train' images and labels...4895 found, 2886 missing, 0 empty, 0 corrupted: 100%|██████████| 7781/7781 [00:00<00:00, 13977.36it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.357843137254902
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2886 missing, 0 empty, 0 corrupted: 100%|██████████| 7781/7781 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:29:44.303359125 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:29:44.324730087 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2025       640  0.003432   0.04094  0.004962     3.947:   2%|▎         | 1/40 [00:21<14:11, 21.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2140       640  0.003422   0.04137  0.005271     4.005:   5%|▌         | 2/40 [00:22<06:01,  9.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1692       640  0.003409   0.04105  0.004975     3.955:   8%|▊         | 3/40 [00:23<03:25,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2189       640  0.003479   0.04119  0.005058     3.978:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640   0.00347   0.04096  0.004998     3.955:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1681       640  0.003451   0.03991  0.004739     3.848:  15%|█▌        | 6/40 [00:25<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1999       640  0.003447   0.03958   0.00476     3.823:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640  0.003447   0.03916  0.004701     3.785:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1891       640  0.003441   0.03878  0.004659      3.75:  22%|██▎       | 9/40 [00:27<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003442   0.03875  0.004681      3.75:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003443   0.03867  0.004679     3.743:  28%|██▊       | 11/40 [00:29<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2022       640  0.003456   0.03851  0.004662      3.73:  30%|███       | 12/40 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1902       640  0.003449    0.0382  0.004632     3.703:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640  0.003445   0.03806  0.004619      3.69:  35%|███▌      | 14/40 [00:30<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1629       640  0.003436   0.03759  0.004624     3.652:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003433   0.03748  0.004608     3.642:  40%|████      | 16/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003442   0.03752  0.004611     3.646:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2162       640  0.003447   0.03753  0.004602     3.646:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1745       640  0.003445   0.03726  0.004594     3.624:  48%|████▊     | 19/40 [00:34<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2097       640  0.003438   0.03723  0.004581      3.62:  50%|█████     | 20/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003443   0.03714  0.004573     3.612:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1648       640  0.003438   0.03696   0.00457     3.597:  55%|█████▌    | 22/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2078       640  0.003439   0.03693  0.004557     3.594:  57%|█████▊    | 23/40 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003436   0.03678  0.004566     3.583:  60%|██████    | 24/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1753       640  0.003433   0.03661  0.004537     3.567:  62%|██████▎   | 25/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2063       640  0.003433   0.03664  0.004532     3.569:  65%|██████▌   | 26/40 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.568      0.409      0.408       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937       0.55      0.411      0.406       0.23
                   0        738       1052      0.559      0.534      0.531      0.256
                   1        738         44      0.496      0.182      0.204     0.0934
                   2        738       8622      0.693      0.724      0.749      0.481
                   3        738        151      0.475      0.397      0.425      0.327
                   4        738        467      0.477      0.577       0.53      0.377
                   5        738         70      0.332      0.429      0.272      0.142
                   6        738         65      0.249     0.0769      0.168     0.0692
                   7        738       1619      0.569      0.605      0.584      0.242
                   8        738       2845      0.652      0.587      0.592      0.312
                   9        738          2          1          0   0.000269   0.000242

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:31:07.764969208 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31241 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round015_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round015_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 15788.99it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:31:23.556743689 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:31:23.560747426 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003532   0.05285  0.004557     4.875:   3%|▎         | 1/39 [00:22<14:17, 22.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2187       640  0.003485    0.0518   0.00493     4.817:   5%|▌         | 2/39 [00:23<06:08,  9.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1974       640  0.003449   0.05069  0.004955     4.727:   8%|▊         | 3/39 [00:24<03:30,  5.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1957       640  0.003459   0.04957  0.004874     4.632:  10%|█         | 4/39 [00:25<02:15,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2145       640  0.003456   0.04894  0.004798     4.575:  13%|█▎        | 5/39 [00:26<01:32,  2.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1780       640  0.003423   0.04778  0.004764     4.478:  15%|█▌        | 6/39 [00:26<01:07,  2.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1960       640  0.003432   0.04744  0.004822     4.455:  18%|█▊        | 7/39 [00:27<00:51,  1.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1897       640  0.003423   0.04702  0.004774     4.417:  21%|██        | 8/39 [00:28<00:40,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2025       640  0.003437   0.04696  0.004706     4.409:  23%|██▎       | 9/39 [00:28<00:33,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003423   0.04665  0.004698     4.382:  26%|██▌       | 10/39 [00:29<00:28,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003427   0.04652  0.004691     4.371:  28%|██▊       | 11/39 [00:30<00:24,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1792       640  0.003431     0.046  0.004702     4.331:  31%|███       | 12/39 [00:30<00:22,  1.22it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2094       640  0.003438   0.04582  0.004665     4.314:  33%|███▎      | 13/39 [00:31<00:19,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2134       640  0.003447    0.0458  0.004628      4.31:  36%|███▌      | 14/39 [00:32<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1930       640  0.003448    0.0456  0.004603     4.292:  38%|███▊      | 15/39 [00:32<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1894       640  0.003439   0.04526  0.004594     4.264:  41%|████      | 16/39 [00:33<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1504       640   0.00343   0.04501  0.004619     4.245:  44%|████▎     | 17/39 [00:34<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1920       640  0.003422   0.04492  0.004604     4.236:  46%|████▌     | 18/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1718       640  0.003424   0.04463  0.004588     4.211:  49%|████▊     | 19/39 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640  0.003419   0.04461   0.00458     4.209:  51%|█████▏    | 20/39 [00:36<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1849       640   0.00341   0.04443  0.004559     4.192:  54%|█████▍    | 21/39 [00:36<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1707       640  0.003406   0.04433  0.004548     4.183:  56%|█████▋    | 22/39 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1860       640  0.003398   0.04421  0.004548     4.173:  59%|█████▉    | 23/39 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1900       640  0.003394   0.04414  0.004537     4.165:  62%|██████▏   | 24/39 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1848       640  0.003391   0.04402  0.004536     4.156:  64%|██████▍   | 25/39 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2050       640  0.003385   0.04397  0.004519      4.15:  67%|██████▋   | 26/39 [00:39<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53      0.431       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.516      0.432       0.41      0.231
                   0        738       1052        0.6      0.525      0.536      0.253
                   1        738         44      0.471      0.222      0.209        0.1
                   2        738       8622      0.632       0.75      0.754      0.479
                   3        738        151      0.339       0.45       0.43      0.327
                   4        738        467       0.43      0.623      0.534      0.378
                   5        738         70      0.323      0.414      0.276      0.142
                   6        738         65      0.223     0.0923      0.174     0.0739
                   7        738       1619      0.545      0.631      0.582       0.24
                   8        738       2845      0.602      0.615      0.601      0.319
                   9        738          2          1          0    0.00027   0.000243

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:32:48.136020932 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31242 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round015_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round015_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client3_citystreet_night_stable_train' images and labels...4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<00:00, 13472.98it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.282926829268293
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:33:05.606854200 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:33:05.615384142 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2040       640  0.003608   0.04625  0.004571     4.354:   2%|▎         | 1/40 [00:21<14:03, 21.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1970       640  0.003644   0.04503  0.004956     4.291:   5%|▌         | 2/40 [00:22<05:59,  9.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2076       640  0.003602   0.04481  0.004796     4.256:   8%|▊         | 3/40 [00:23<03:25,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2021       640  0.003565    0.0442  0.004907     4.214:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1825       640  0.003537   0.04309  0.004814     4.115:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1779       640  0.003507   0.04215  0.004691     4.028:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1981       640  0.003509   0.04156  0.004592     3.973:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2026       640  0.003501    0.0415  0.004626      3.97:  20%|██        | 8/40 [00:26<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1984       640  0.003482   0.04128  0.004587     3.948:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1802       640  0.003477   0.04087  0.004552     3.912:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1889       640  0.003469   0.04048   0.00449     3.875:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1757       640  0.003456   0.04002  0.004493     3.837:  30%|███       | 12/40 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1938       640  0.003451   0.03978  0.004471     3.816:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1921       640  0.003449   0.03976    0.0045     3.817:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1758       640  0.003442   0.03938  0.004501     3.786:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1943       640  0.003443   0.03916  0.004512     3.769:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1656       640  0.003446   0.03887  0.004535     3.748:  42%|████▎     | 17/40 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1936       640  0.003449   0.03873  0.004561     3.739:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1734       640  0.003446   0.03836  0.004558     3.709:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1929       640  0.003445   0.03826  0.004546       3.7:  50%|█████     | 20/40 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2006       640  0.003446   0.03816  0.004532     3.691:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1755       640  0.003445   0.03801  0.004519     3.678:  55%|█████▌    | 22/40 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2099       640  0.003444   0.03799  0.004529     3.677:  57%|█████▊    | 23/40 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1844       640  0.003438   0.03781  0.004512     3.661:  60%|██████    | 24/40 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1671       640  0.003436   0.03755   0.00449     3.638:  62%|██████▎   | 25/40 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1950       640  0.003432   0.03753  0.004472     3.635:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.599      0.391      0.411      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.02it/s]

                 all        738      14937      0.586      0.389      0.409      0.231
                   0        738       1052      0.638      0.495      0.527      0.253
                   1        738         44      0.555     0.0909      0.212        0.1
                   2        738       8622      0.721      0.711      0.748      0.479
                   3        738        151       0.55      0.404      0.428      0.328
                   4        738        467      0.486      0.585      0.537      0.378
                   5        738         70      0.402      0.371       0.28      0.146
                   6        738         65       0.26     0.0462      0.176     0.0691
                   7        738       1619       0.58      0.604      0.588      0.244
                   8        738       2845      0.671       0.58      0.597      0.316
                   9        738          2          1          0   0.000246   0.000221

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:34:31.858608633 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31243 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round015_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round015_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 11742.73it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:34:48.151940521 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:34:48.161782525 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2153       640  0.003467   0.05186  0.004774     4.808:   3%|▎         | 1/39 [00:21<13:53, 21.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2109       640  0.003423   0.05053  0.005158     4.729:   5%|▌         | 2/39 [00:22<05:53,  9.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1782       640   0.00337   0.04869  0.005042     4.568:   8%|▊         | 3/39 [00:23<03:20,  5.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003366   0.04811  0.004955     4.514:  10%|█         | 4/39 [00:24<02:10,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003357   0.04704  0.004948     4.427:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1759       640  0.003353   0.04568  0.005026     4.325:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003372   0.04544  0.004975     4.303:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2179       640  0.003385   0.04518  0.004863     4.274:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2090       640  0.003386   0.04526  0.004805     4.276:  23%|██▎       | 9/39 [00:27<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640   0.00339    0.0451  0.004793     4.263:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640    0.0034    0.0451  0.004767     4.261:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2189       640  0.003416   0.04497  0.004811     4.256:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003421    0.0449  0.004789     4.249:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003428   0.04479  0.004788      4.24:  36%|███▌      | 14/39 [00:31<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003433   0.04453   0.00481     4.222:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003427   0.04421  0.004787     4.194:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003423   0.04403  0.004747     4.176:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003418   0.04402  0.004711     4.172:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003421   0.04369   0.00472     4.146:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003411   0.04365  0.004709     4.142:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003406   0.04354  0.004676     4.129:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003404   0.04348  0.004678     4.125:  56%|█████▋    | 22/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003403   0.04344  0.004688     4.123:  59%|█████▉    | 23/39 [00:36<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003399   0.04328   0.00468     4.108:  62%|██████▏   | 24/39 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640    0.0034   0.04316  0.004673     4.099:  64%|██████▍   | 25/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003397   0.04304  0.004645     4.086:  67%|██████▋   | 26/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.523      0.442      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.509      0.444      0.411      0.231
                   0        738       1052      0.503       0.56      0.538      0.257
                   1        738         44      0.498      0.271      0.214     0.0916
                   2        738       8622      0.658      0.741      0.751      0.477
                   3        738        151      0.348       0.45      0.438      0.329
                   4        738        467      0.435      0.615      0.541      0.381
                   5        738         70      0.278      0.414      0.282      0.145
                   6        738         65      0.242      0.138      0.168     0.0678
                   7        738       1619      0.525      0.631      0.584       0.24
                   8        738       2845      0.602      0.619      0.599      0.319
                   9        738          2          1          0   0.000247   0.000223

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:36:15.810300936 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31244 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round015_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round015_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client5_residential_night_stable_train' images and labels...4885 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<00:00, 8731.08it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29014483627204
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round015_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:36:32.295851074 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:36:32.298124219 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1994       640  0.003495   0.04481  0.004492     4.224:   2%|▎         | 1/40 [00:22<14:24, 22.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1831       640  0.003417   0.04399  0.004259     4.133:   5%|▌         | 2/40 [00:23<06:07,  9.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1836       640  0.003395   0.04338  0.004109     4.071:   8%|▊         | 3/40 [00:23<03:28,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1895       640  0.003392   0.04276  0.004155     4.025:  10%|█         | 4/40 [00:24<02:14,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003408   0.04189  0.004309     3.969:  12%|█▎        | 5/40 [00:25<01:32,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1795       640  0.003422   0.04098  0.004427     3.907:  15%|█▌        | 6/40 [00:26<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1800       640  0.003416   0.04024  0.004454     3.849:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1891       640  0.003415   0.03975  0.004459      3.81:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1976       640  0.003424   0.03973  0.004431     3.807:  22%|██▎       | 9/40 [00:28<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003422   0.03947  0.004457     3.788:  25%|██▌       | 10/40 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2051       640  0.003423    0.0394  0.004506     3.787:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003414   0.03913  0.004491     3.763:  30%|███       | 12/40 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003413   0.03881  0.004558     3.743:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2211       640  0.003416   0.03877   0.00453     3.737:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1702       640  0.003414    0.0383  0.004466     3.694:  38%|███▊      | 15/40 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1605       640  0.003401   0.03775  0.004452     3.648:  40%|████      | 16/40 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003407   0.03759  0.004525     3.641:  42%|████▎     | 17/40 [00:33<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1750       640  0.003405   0.03733  0.004519     3.621:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1730       640  0.003413     0.037  0.004529     3.595:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003414   0.03688  0.004499     3.583:  50%|█████     | 20/40 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2044       640  0.003416   0.03684  0.004521     3.582:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1805       640  0.003417   0.03679  0.004516     3.577:  55%|█████▌    | 22/40 [00:36<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003416   0.03679  0.004543      3.58:  57%|█████▊    | 23/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003417   0.03678  0.004539     3.579:  60%|██████    | 24/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640  0.003422    0.0367  0.004572     3.575:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1833       640   0.00342   0.03662  0.004571     3.569:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.545      0.415      0.413      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.538      0.413       0.41      0.231
                   0        738       1052      0.553      0.518      0.528      0.252
                   1        738         44      0.497      0.182      0.222      0.104
                   2        738       8622      0.673      0.727      0.747      0.479
                   3        738        151      0.447      0.404      0.426      0.323
                   4        738        467      0.469      0.589      0.536      0.381
                   5        738         70       0.32        0.4      0.283      0.146
                   6        738         65      0.244     0.0747      0.165     0.0625
                   7        738       1619      0.555      0.627      0.591      0.241
                   8        738       2845      0.623      0.613      0.601      0.317
                   9        738          2          1          0   0.000197   0.000177

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 17:37:59.308629427 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31245 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round015_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round015_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:38:16.353518414 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:38:16.404586476 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03067   0.03578  0.003723     5.613:   3%|▎         | 1/31 [00:31<15:59, 32.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640     0.031   0.03599  0.003843     5.666:   6%|▋         | 2/31 [00:32<06:35, 13.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03041   0.03482  0.003768      5.52:  10%|▉         | 3/31 [00:33<03:38,  7.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.03001   0.03357  0.003574     5.373:  13%|█▎        | 4/31 [00:34<02:15,  5.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02995   0.03364  0.003586     5.374:  16%|█▌        | 5/31 [00:34<01:28,  3.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.03004   0.03352  0.003618     5.375:  19%|█▉        | 6/31 [00:35<01:01,  2.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640    0.0301   0.03324  0.003668     5.361:  23%|██▎       | 7/31 [00:36<00:44,  1.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.03001   0.03328  0.003663     5.356:  26%|██▌       | 8/31 [00:36<00:33,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.03007    0.0332  0.003583     5.349:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.03009   0.03334  0.003561     5.359:  32%|███▏      | 10/31 [00:37<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.03006   0.03336  0.003581      5.36:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02997   0.03311  0.003578     5.332:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02994   0.03309  0.003529     5.324:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02996   0.03298  0.003501     5.315:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02998   0.03289  0.003547     5.314:  48%|████▊     | 15/31 [00:40<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02999   0.03278  0.003547     5.305:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.03002   0.03281  0.003525     5.309:  55%|█████▍    | 17/31 [00:41<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.03011   0.03294  0.003498     5.324:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.03008   0.03284  0.003474     5.311:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.03009   0.03306  0.003472      5.33:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.03014   0.03313  0.003491     5.341:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.03017   0.03325   0.00347     5.351:  71%|███████   | 22/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.03018   0.03332  0.003447     5.356:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03022   0.03345  0.003439     5.369:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03025   0.03345  0.003451     5.372:  81%|████████  | 25/31 [00:46<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03034   0.03355  0.003461     5.387:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.511      0.442       0.41      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.496      0.443      0.408      0.228
                   0        738       1052       0.48      0.548      0.522      0.252
                   1        738         44      0.419      0.246      0.203     0.0859
                   2        738       8622      0.637      0.747      0.749      0.483
                   3        738        151      0.335      0.444       0.43      0.321
                   4        738        467      0.455      0.606      0.538       0.38
                   5        738         70      0.261      0.414        0.3      0.138
                   6        738         65      0.264      0.169      0.167     0.0662
                   7        738       1619      0.525      0.634      0.582      0.242
                   8        738       2845      0.581      0.624      0.591       0.31
                   9        738          2          1          0   0.000388   0.000349

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round015_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 17:39:54.128392539 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round016 phase_round=16 ===

02 head-to-full DQA:  47%|████▋     | 15/32 [3:32:36<4:00:13, 847.84s/round, elapsed=3h32m36s, eta=4h00m57s, phase=phase1_head, round=15]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round016 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round016 client0_highway_day: pseudo scan 250/1500 images, kept 2373 boxes
round016 client0_highway_day: pseudo scan 500/1500 images, kept 4807 boxes
round016 client0_highway_day: pseudo scan 750/1500 images, kept 7157 boxes
round016 client0_highway_day: pseudo scan 1000/1500 images, kept 9537 boxes
round016 client0_highway_day: pseudo scan 1250/1500 images, kept 11871 boxes
round016 client0_highway_day: pseudo scan 1500/1500 images, kept 14274 boxes
{
  "round": "round016",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round015_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1494,
  "pseudo_boxes_kept": 11239,
  "boxes_per_kept_image": 7.522757697456493,
  "mean_conf": 0.8195710273938349,
  "mean_stability": 0.9496995627705085,
  "mean_score": 0.7816643809984635,
  "class_counts": {
    "0": 161,
    "2": 6424,
    "3": 121,
    "4": 566,
    "5": 7,
    "7": 559,
    "8": 3401
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_client0_highway_day_stable_boxes.csv"
}
round016 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round016 client1_highway_night: pseudo scan 250/1500 images, kept 1595 boxes
round016 client1_highway_night: pseudo scan 500/1500 images, kept 3304 boxes
round016 client1_highway_night: pseudo scan 750/1500 images, kept 5030 boxes
round016 client1_highway_night: pseudo scan 1000/1500 images, kept 6649 boxes
round016 client1_highway_night: pseudo scan 1250/1500 images, kept 8314 boxes
round016 client1_highway_night: pseudo scan 1500/1500 images, kept 9925 boxes
{
  "round": "round016",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round015_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1450,
  "pseudo_boxes_kept": 8192,
  "boxes_per_kept_image": 5.649655172413793,
  "mean_conf": 0.7339578022292699,
  "mean_stability": 0.9320658927244949,
  "mean_score": 0.6882949588082478,
  "class_counts": {
    "0": 66,
    "2": 4467,
    "3": 29,
    "4": 147,
    "5": 6,
    "7": 605,
    "8": 2872
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_client1_highway_night_stable_boxes.csv"
}
round016 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round016 client2_citystreet_day: pseudo scan 250/1500 images, kept 2693 boxes
round016 client2_citystreet_day: pseudo scan 500/1500 images, kept 5418 boxes
round016 client2_citystreet_day: pseudo scan 750/1500 images, kept 8159 boxes
round016 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10912 boxes
round016 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13626 boxes
round016 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16278 boxes
{
  "round": "round016",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round015_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13785,
  "boxes_per_kept_image": 9.21457219251337,
  "mean_conf": 0.81941713914086,
  "mean_stability": 0.947724300659693,
  "mean_score": 0.7800170904373503,
  "class_counts": {
    "0": 1461,
    "2": 7326,
    "3": 211,
    "4": 615,
    "5": 61,
    "7": 1522,
    "8": 2589
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_client2_citystreet_day_stable_boxes.csv"
}
round016 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round016 client3_citystreet_night: pseudo scan 250/1500 images, kept 2329 boxes
round016 client3_citystreet_night: pseudo scan 500/1500 images, kept 4610 boxes
round016 client3_citystreet_night: pseudo scan 750/1500 images, kept 6869 boxes
round016 client3_citystreet_night: pseudo scan 1000/1500 images, kept 9044 boxes
round016 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11425 boxes
round016 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13700 boxes
{
  "round": "round016",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round015_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 11637,
  "boxes_per_kept_image": 7.905570652173913,
  "mean_conf": 0.7291354076338048,
  "mean_stability": 0.9280331408515504,
  "mean_score": 0.6811895615745102,
  "class_counts": {
    "0": 546,
    "2": 6165,
    "3": 69,
    "4": 159,
    "5": 38,
    "7": 2067,
    "8": 2593
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_client3_citystreet_night_stable_boxes.csv"
}
round016 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round016 client4_residential_day: pseudo scan 250/1500 images, kept 2588 boxes
round016 client4_residential_day: pseudo scan 500/1500 images, kept 5193 boxes
round016 client4_residential_day: pseudo scan 750/1500 images, kept 7742 boxes
round016 client4_residential_day: pseudo scan 1000/1500 images, kept 10218 boxes
round016 client4_residential_day: pseudo scan 1250/1500 images, kept 12737 boxes
round016 client4_residential_day: pseudo scan 1500/1500 images, kept 15210 boxes
{
  "round": "round016",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round015_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9980,
  "boxes_per_kept_image": 6.697986577181208,
  "mean_conf": 0.8518025777353074,
  "mean_stability": 0.9559171913262599,
  "mean_score": 0.8177623171841468,
  "class_counts": {
    "0": 383,
    "2": 6845,
    "3": 67,
    "4": 322,
    "5": 45,
    "7": 537,
    "8": 1781
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_client4_residential_day_stable_boxes.csv"
}
round016 client5_residential_night: pseudo scan 1/1500 images, kept 8 boxes
round016 client5_residential_night: pseudo scan 250/1500 images, kept 2252 boxes
round016 client5_residential_night: pseudo scan 500/1500 images, kept 4488 boxes
round016 client5_residential_night: pseudo scan 750/1500 images, kept 6707 boxes
round016 client5_residential_night: pseudo scan 1000/1500 images, kept 9002 boxes
round016 client5_residential_night: pseudo scan 1250/1500 images, kept 11307 boxes
round016 client5_residential_night: pseudo scan 1500/1500 images, kept 13594 boxes
{
  "round": "round016",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round015_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1473,
  "pseudo_boxes_kept": 8503,
  "boxes_per_kept_image": 5.772572980312288,
  "mean_conf": 0.7954811234271177,
  "mean_stability": 0.9427542678751581,
  "mean_score": 0.7531018983440179,
  "class_counts": {
    "0": 127,
    "2": 6118,
    "3": 33,
    "4": 99,
    "5": 25,
    "7": 691,
    "8": 1410
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round016_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31246 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round016_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round016_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client0_highway_day_stable_train' images and labels...5361 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<00:00, 13684.03it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.830969845150774
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2508 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:42:11.074131763 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:42:11.101942628 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2068       640  0.003452   0.04304  0.004545     4.083:   3%|▎         | 1/39 [00:22<13:57, 22.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003459   0.04332  0.004252     4.082:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003492   0.04396  0.004366     4.145:   8%|▊         | 3/39 [00:23<03:20,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003456   0.04402  0.004568     4.163:  10%|█         | 4/39 [00:24<02:09,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003438   0.04333  0.004607      4.11:  13%|█▎        | 5/39 [00:25<01:28,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640   0.00343   0.04234  0.004541     4.025:  15%|█▌        | 6/39 [00:25<01:03,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003425   0.04234  0.004513     4.022:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640   0.00342   0.04262  0.004589      4.05:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003426   0.04316  0.004652     4.099:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003437   0.04344  0.004658     4.123:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003425   0.04326  0.004587     4.102:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003427   0.04304  0.004596     4.085:  31%|███       | 12/39 [00:29<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003432   0.04287   0.00459     4.071:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2233       640  0.003438   0.04303  0.004548     4.081:  36%|███▌      | 14/39 [00:31<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1954       640  0.003428   0.04285  0.004522     4.064:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003433   0.04275  0.004538     4.058:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003433   0.04244  0.004542     4.033:  44%|████▎     | 17/39 [00:32<00:14,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003436    0.0424  0.004537     4.029:  46%|████▌     | 18/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003432   0.04219  0.004542     4.013:  49%|████▊     | 19/39 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2386       640  0.003435   0.04229  0.004546     4.022:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003436   0.04231  0.004528     4.022:  54%|█████▍    | 21/39 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003437   0.04219  0.004505     4.011:  56%|█████▋    | 22/39 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2251       640  0.003437   0.04222  0.004475      4.01:  59%|█████▉    | 23/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003438   0.04217  0.004461     4.005:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003433   0.04206  0.004451     3.996:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2154       640  0.003431   0.04205  0.004444     3.994:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.566       0.41      0.413      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.553      0.411      0.412      0.232
                   0        738       1052      0.532      0.549      0.535      0.257
                   1        738         44      0.498      0.159       0.22     0.0924
                   2        738       8622      0.708      0.728      0.752      0.481
                   3        738        151      0.502      0.404      0.423      0.323
                   4        738        467      0.492      0.574      0.539      0.383
                   5        738         70        0.3      0.405      0.288      0.154
                   6        738         65      0.278     0.0769      0.171     0.0701
                   7        738       1619      0.565      0.623       0.59      0.242
                   8        738       2845      0.657      0.594      0.602      0.318
                   9        738          2          1          0   0.000354   0.000318

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:43:38.291030232 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31247 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round016_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round016_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client1_highway_night_stable_train' images and labels...4895 found, 2886 missing, 0 empty, 0 corrupted: 100%|██████████| 7781/7781 [00:00<00:00, 12411.69it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.357843137254902
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2886 missing, 0 empty, 0 corrupted: 100%|██████████| 7781/7781 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:43:54.237179904 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:43:55.253225269 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1996       640  0.003399   0.03987   0.00485      3.85:   2%|▎         | 1/40 [00:21<14:12, 21.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640  0.003422   0.04075  0.005285     3.957:   5%|▌         | 2/40 [00:22<06:02,  9.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1737       640  0.003424   0.04042  0.004996     3.907:   8%|▊         | 3/40 [00:23<03:25,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2131       640   0.00347   0.04086  0.005071     3.952:  10%|█         | 4/40 [00:24<02:12,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003469   0.04038  0.004927     3.902:  12%|█▎        | 5/40 [00:25<01:30,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1753       640  0.003459   0.03972  0.004745     3.834:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2096       640   0.00345   0.03964  0.004788      3.83:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640   0.00345    0.0392  0.004749     3.792:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003442   0.03881   0.00465     3.752:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1888       640  0.003446   0.03878  0.004674     3.752:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1902       640  0.003444   0.03851  0.004701     3.732:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003449   0.03826  0.004669      3.71:  30%|███       | 12/40 [00:29<00:21,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003445    0.0379  0.004629     3.678:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1965       640  0.003439   0.03785  0.004625     3.673:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1628       640  0.003434   0.03745  0.004627     3.641:  38%|███▊      | 15/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1888       640  0.003429    0.0373  0.004609     3.627:  40%|████      | 16/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2044       640  0.003439   0.03732  0.004623     3.631:  42%|████▎     | 17/40 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003438   0.03722  0.004615     3.622:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1749       640  0.003435   0.03694   0.00462       3.6:  48%|████▊     | 19/40 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2202       640  0.003432     0.037  0.004597     3.602:  50%|█████     | 20/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2002       640  0.003435    0.0369  0.004577     3.593:  52%|█████▎    | 21/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1595       640  0.003431   0.03661  0.004579      3.57:  55%|█████▌    | 22/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2226       640  0.003433   0.03669  0.004556     3.574:  57%|█████▊    | 23/40 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1873       640  0.003428   0.03655  0.004561     3.563:  60%|██████    | 24/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003424   0.03647  0.004548     3.555:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1914       640  0.003422   0.03637  0.004537     3.546:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.54      0.425      0.409      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.537      0.417      0.406       0.23
                   0        738       1052      0.551      0.531      0.528      0.255
                   1        738         44      0.472      0.205      0.213     0.0974
                   2        738       8622      0.679      0.731       0.75       0.48
                   3        738        151      0.445      0.409      0.428       0.33
                   4        738        467      0.467      0.587      0.531      0.379
                   5        738         70      0.339      0.429      0.273       0.14
                   6        738         65      0.219     0.0769      0.165     0.0709
                   7        738       1619      0.555      0.613       0.58      0.241
                   8        738       2845      0.644      0.593      0.592      0.311
                   9        738          2          1          0   0.000253   0.000228

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:45:21.626648353 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31248 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round016_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round016_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 11864.04it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:45:38.850649273 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:45:38.908154469 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003533   0.05307  0.004558     4.893:   3%|▎         | 1/39 [00:21<13:52, 21.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003487   0.05199  0.004929     4.833:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003451   0.05088  0.004954     4.743:   8%|▊         | 3/39 [00:23<03:21,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640   0.00346   0.04974  0.004869     4.645:  10%|█         | 4/39 [00:24<02:10,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003458    0.0491  0.004792     4.588:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003425   0.04795  0.004757      4.49:  15%|█▌        | 6/39 [00:25<01:04,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003435   0.04759  0.004813     4.467:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003426   0.04716  0.004766     4.428:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003441   0.04709  0.004698     4.419:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003427   0.04678  0.004689     4.392:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640   0.00343   0.04663  0.004682      4.38:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003435   0.04611  0.004693     4.339:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003441   0.04592  0.004655     4.322:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640   0.00345    0.0459  0.004618     4.317:  36%|███▌      | 14/39 [00:30<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003451   0.04569  0.004593     4.299:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003442   0.04535  0.004584      4.27:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003433    0.0451   0.00461     4.251:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003426     0.045  0.004594     4.242:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003427   0.04471  0.004577     4.217:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003422   0.04469  0.004569     4.215:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003414    0.0445  0.004548     4.197:  54%|█████▍    | 21/39 [00:35<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003409    0.0444  0.004538     4.188:  56%|█████▋    | 22/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003401   0.04428  0.004537     4.177:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003397    0.0442  0.004527      4.17:  62%|██████▏   | 24/39 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003394   0.04409  0.004526     4.161:  64%|██████▍   | 25/39 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003388   0.04404  0.004509     4.155:  67%|██████▋   | 26/39 [00:38<00:08,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53      0.434       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.517      0.434      0.409      0.231
                   0        738       1052      0.598      0.527      0.535      0.253
                   1        738         44      0.496      0.246      0.212      0.101
                   2        738       8622      0.631      0.751      0.754      0.479
                   3        738        151      0.336      0.444      0.428      0.326
                   4        738        467      0.427      0.623      0.535      0.377
                   5        738         70      0.324      0.414      0.275      0.142
                   6        738         65      0.212     0.0923      0.174     0.0724
                   7        738       1619      0.544      0.631      0.579       0.24
                   8        738       2845      0.604      0.616      0.599      0.317
                   9        738          2          1          0   0.000274   0.000247

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:47:05.445783679 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31249 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round016_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round016_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client3_citystreet_night_stable_train' images and labels...4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<00:00, 9878.60it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29014483627204
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:47:21.040505752 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:47:21.064581242 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1863       640  0.003514   0.04667   0.00445      4.37:   2%|▎         | 1/40 [00:21<14:03, 21.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003402   0.04376  0.004657     4.146:   5%|▌         | 2/40 [00:22<05:57,  9.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640    0.0034   0.04376  0.004363     4.122:   8%|▊         | 3/40 [00:23<03:23,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2143       640  0.003402    0.0432  0.004192     4.064:  10%|█         | 4/40 [00:24<02:12,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003395    0.0427  0.004117     4.017:  12%|█▎        | 5/40 [00:24<01:30,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1656       640   0.00338   0.04151  0.004136     3.922:  15%|█▌        | 6/40 [00:25<01:06,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1751       640  0.003369   0.04061  0.004162     3.852:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003366   0.04032  0.004098     3.823:  20%|██        | 8/40 [00:26<00:40,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1885       640  0.003365   0.04022  0.004076     3.813:  22%|██▎       | 9/40 [00:27<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003377   0.04022  0.004108     3.816:  25%|██▌       | 10/40 [00:28<00:28,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2128       640  0.003387   0.04017  0.004189     3.819:  28%|██▊       | 11/40 [00:28<00:25,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003389   0.03989  0.004148     3.794:  30%|███       | 12/40 [00:29<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003384   0.03963   0.00417     3.775:  32%|███▎      | 13/40 [00:30<00:20,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003383   0.03952  0.004197     3.768:  35%|███▌      | 14/40 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003379   0.03939  0.004204     3.758:  38%|███▊      | 15/40 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1891       640  0.003377   0.03921  0.004189     3.742:  40%|████      | 16/40 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1737       640  0.003384   0.03896  0.004251     3.728:  42%|████▎     | 17/40 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003381   0.03874  0.004295     3.713:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003384   0.03848  0.004268     3.691:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640   0.00339   0.03847  0.004298     3.692:  50%|█████     | 20/40 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1831       640  0.003401   0.03832  0.004288     3.681:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003404   0.03825  0.004255     3.673:  55%|█████▌    | 22/40 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2263       640  0.003404   0.03841  0.004267     3.687:  57%|█████▊    | 23/40 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1993       640  0.003407   0.03836  0.004313     3.686:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2105       640  0.003409   0.03831  0.004305     3.682:  62%|██████▎   | 25/40 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1829       640  0.003406   0.03818  0.004299     3.671:  65%|██████▌   | 26/40 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.601      0.392       0.41      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.582      0.394      0.407      0.231
                   0        738       1052      0.638      0.495      0.524      0.252
                   1        738         44      0.588      0.114      0.229      0.112
                   2        738       8622      0.706      0.715      0.746      0.477
                   3        738        151      0.496      0.391      0.424      0.323
                   4        738        467      0.464      0.597      0.536      0.379
                   5        738         70       0.41        0.4      0.284      0.139
                   6        738         65       0.27     0.0571      0.164     0.0688
                   7        738       1619      0.575      0.594      0.577      0.241
                   8        738       2845       0.67      0.576      0.592      0.313
                   9        738          2          1          0   0.000302   0.000272

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:48:47.415460594 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31250 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round016_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round016_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 10698.99it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:49:03.985068663 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:49:03.002146325 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2153       640   0.00347   0.05213  0.004771     4.829:   3%|▎         | 1/39 [00:22<14:09, 22.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2109       640  0.003425   0.05074  0.005152     4.746:   5%|▌         | 2/39 [00:23<05:58,  9.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1782       640  0.003373   0.04888  0.005042     4.584:   8%|▊         | 3/39 [00:24<03:23,  5.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003368   0.04828  0.004951     4.528:  10%|█         | 4/39 [00:24<02:11,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003359   0.04718  0.004945     4.439:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1759       640  0.003356   0.04582  0.005023     4.336:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003376   0.04558  0.004972     4.315:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2179       640  0.003389   0.04531  0.004858     4.285:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2090       640   0.00339   0.04538  0.004799     4.286:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003395   0.04522  0.004787     4.272:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640  0.003404    0.0452   0.00476      4.27:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2189       640   0.00342   0.04507  0.004804     4.264:  31%|███       | 12/39 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003425   0.04499   0.00478     4.256:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003432   0.04488  0.004779     4.247:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003437   0.04462  0.004801     4.228:  38%|███▊      | 15/39 [00:32<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003431   0.04428  0.004778       4.2:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003427   0.04411  0.004738     4.182:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003423   0.04409  0.004702     4.177:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003425   0.04376  0.004711     4.152:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003415   0.04372    0.0047     4.147:  51%|█████▏    | 20/39 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640   0.00341    0.0436  0.004668     4.134:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003408   0.04354  0.004671     4.129:  56%|█████▋    | 22/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003407    0.0435  0.004681     4.127:  59%|█████▉    | 23/39 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003402   0.04333  0.004672     4.113:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003404   0.04322  0.004664     4.103:  64%|██████▍   | 25/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003401   0.04309  0.004636      4.09:  67%|██████▋   | 26/39 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.523      0.442      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937       0.51      0.444      0.411      0.231
                   0        738       1052      0.504      0.561      0.537      0.256
                   1        738         44      0.496      0.273      0.216     0.0931
                   2        738       8622      0.658       0.74      0.751      0.477
                   3        738        151      0.355       0.45      0.437      0.327
                   4        738        467      0.435      0.615      0.542      0.382
                   5        738         70      0.279      0.414      0.287      0.145
                   6        738         65      0.242      0.138      0.163     0.0678
                   7        738       1619      0.525       0.63      0.581       0.24
                   8        738       2845      0.601      0.618      0.599      0.318
                   9        738          2          1          0   0.000253   0.000227

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:50:28.604269156 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31251 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round016_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round016_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client5_residential_night_stable_train' images and labels...4885 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<00:00, 14548.69it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29014483627204
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round016_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:50:44.313608217 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:50:44.316215267 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2027       640  0.003509   0.04385  0.004635      4.16:   2%|▎         | 1/40 [00:21<14:11, 21.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640  0.003401   0.04313  0.004275     4.065:   5%|▌         | 2/40 [00:22<06:03,  9.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003395    0.0426  0.004226     4.018:   8%|▊         | 3/40 [00:23<03:26,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640    0.0034   0.04273  0.004422     4.044:  10%|█         | 4/40 [00:24<02:13,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1855       640  0.003419   0.04188  0.004468     3.981:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1604       640  0.003419   0.04066  0.004534     3.889:  15%|█▌        | 6/40 [00:25<01:06,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003408   0.04004  0.004544     3.839:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640  0.003418   0.03966  0.004516     3.807:  20%|██        | 8/40 [00:27<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1983       640  0.003428   0.03956  0.004467     3.797:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003434   0.03918  0.004459     3.766:  25%|██▌       | 10/40 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003429   0.03913  0.004444     3.761:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1953       640  0.003418   0.03899  0.004447     3.748:  30%|███       | 12/40 [00:29<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003413   0.03863  0.004514     3.724:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2195       640  0.003414   0.03861  0.004482      3.72:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1653       640  0.003411   0.03812  0.004429     3.677:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1617       640  0.003399   0.03762  0.004394     3.633:  40%|████      | 16/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1728       640  0.003405   0.03738  0.004458     3.619:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1795       640  0.003402   0.03713   0.00447       3.6:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1762       640  0.003412   0.03687  0.004474      3.58:  48%|████▊     | 19/40 [00:34<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1925       640  0.003415   0.03676  0.004435     3.569:  50%|█████     | 20/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003416   0.03667  0.004468     3.564:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1776       640  0.003416   0.03663  0.004466     3.561:  55%|█████▌    | 22/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003413   0.03658  0.004504      3.56:  57%|█████▊    | 23/40 [00:36<00:10,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1863       640  0.003412   0.03654  0.004504     3.556:  60%|██████    | 24/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003418   0.03643  0.004548     3.551:  62%|██████▎   | 25/40 [00:37<00:09,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1812       640  0.003421   0.03632  0.004543     3.543:  65%|██████▌   | 26/40 [00:38<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.555      0.414      0.413      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.542      0.416      0.409       0.23
                   0        738       1052      0.561      0.516      0.524      0.253
                   1        738         44      0.493      0.199       0.22      0.103
                   2        738       8622      0.677      0.727      0.747      0.478
                   3        738        151      0.467      0.404      0.424      0.323
                   4        738        467      0.481      0.589       0.54       0.38
                   5        738         70      0.328      0.414      0.286      0.146
                   6        738         65       0.23     0.0769      0.163     0.0606
                   7        738       1619      0.556       0.62      0.585      0.241
                   8        738       2845      0.627       0.61      0.599      0.317
                   9        738          2          1          0   0.000227   0.000204

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:52:10.912765504 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31252 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round016_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round016_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:52:27.938804232 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:52:27.949925187 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03072   0.03576   0.00371     5.616:   3%|▎         | 1/31 [00:32<16:20, 32.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640    0.0309   0.03571  0.003796     5.633:   6%|▋         | 2/31 [00:33<06:43, 13.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03028   0.03448  0.003705     5.477:  10%|▉         | 3/31 [00:34<03:41,  7.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02983   0.03318  0.003505     5.321:  13%|█▎        | 4/31 [00:35<02:17,  5.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02976   0.03321  0.003514     5.319:  16%|█▌        | 5/31 [00:35<01:30,  3.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02985   0.03308  0.003545     5.318:  19%|█▉        | 6/31 [00:36<01:02,  2.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640    0.0299   0.03279  0.003596     5.303:  23%|██▎       | 7/31 [00:36<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640    0.0298   0.03282  0.003593     5.297:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02987   0.03274  0.003514      5.29:  29%|██▉       | 9/31 [00:37<00:26,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02989   0.03286  0.003485     5.298:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02985   0.03288  0.003506     5.299:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02977   0.03262  0.003502     5.271:  39%|███▊      | 12/31 [00:39<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02974   0.03259  0.003454     5.263:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02976   0.03249  0.003427     5.254:  45%|████▌     | 14/31 [00:40<00:11,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02978    0.0324  0.003475     5.253:  48%|████▊     | 15/31 [00:41<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02979   0.03229  0.003475     5.244:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02982   0.03232  0.003454     5.247:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02991   0.03245  0.003428     5.263:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02988   0.03234  0.003406      5.25:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640    0.0299   0.03257  0.003403      5.27:  65%|██████▍   | 20/31 [00:44<00:06,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02995   0.03264  0.003423     5.281:  68%|██████▊   | 21/31 [00:44<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02998   0.03276  0.003403     5.291:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02998   0.03283   0.00338     5.295:  74%|███████▍  | 23/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.03003   0.03296  0.003373     5.309:  77%|███████▋  | 24/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.03005   0.03296  0.003385     5.312:  81%|████████  | 25/31 [00:47<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.03014   0.03306  0.003394     5.327:  84%|████████▍ | 26/31 [00:47<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.511      0.441      0.409      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.14it/s]

                 all        738      14937      0.491      0.448      0.408      0.228
                   0        738       1052      0.468      0.551      0.523      0.252
                   1        738         44      0.391       0.25      0.199     0.0841
                   2        738       8622      0.633      0.748      0.748      0.482
                   3        738        151      0.333      0.444      0.431      0.326
                   4        738        467      0.465      0.615      0.532      0.376
                   5        738         70      0.267      0.429      0.314      0.145
                   6        738         65      0.264      0.185      0.165     0.0669
                   7        738       1619      0.519      0.635      0.579      0.241
                   8        738       2845      0.571      0.621      0.586      0.308
                   9        738          2          1          0   0.000404   0.000364

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round016_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 17:54:06.442218682 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round017 phase_round=17 ===

02 head-to-full DQA:  50%|█████     | 16/32 [3:46:48<3:46:23, 848.95s/round, elapsed=3h46m48s, eta=3h46m48s, phase=phase1_head, round=16]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round017 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round017 client0_highway_day: pseudo scan 250/1500 images, kept 2375 boxes
round017 client0_highway_day: pseudo scan 500/1500 images, kept 4811 boxes
round017 client0_highway_day: pseudo scan 750/1500 images, kept 7156 boxes
round017 client0_highway_day: pseudo scan 1000/1500 images, kept 9527 boxes
round017 client0_highway_day: pseudo scan 1250/1500 images, kept 11859 boxes
round017 client0_highway_day: pseudo scan 1500/1500 images, kept 14258 boxes
{
  "round": "round017",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round016_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 11240,
  "boxes_per_kept_image": 7.538564721663313,
  "mean_conf": 0.82175055669614,
  "mean_stability": 0.9487937739947513,
  "mean_score": 0.7830437393957058,
  "class_counts": {
    "0": 161,
    "2": 6417,
    "3": 122,
    "4": 558,
    "5": 9,
    "7": 557,
    "8": 3416
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_client0_highway_day_stable_boxes.csv"
}
round017 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round017 client1_highway_night: pseudo scan 250/1500 images, kept 1590 boxes
round017 client1_highway_night: pseudo scan 500/1500 images, kept 3274 boxes
round017 client1_highway_night: pseudo scan 750/1500 images, kept 4995 boxes
round017 client1_highway_night: pseudo scan 1000/1500 images, kept 6599 boxes
round017 client1_highway_night: pseudo scan 1250/1500 images, kept 8243 boxes
round017 client1_highway_night: pseudo scan 1500/1500 images, kept 9850 boxes
{
  "round": "round017",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round016_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1450,
  "pseudo_boxes_kept": 8180,
  "boxes_per_kept_image": 5.641379310344828,
  "mean_conf": 0.7351534594169165,
  "mean_stability": 0.9311216713455313,
  "mean_score": 0.688780751349073,
  "class_counts": {
    "0": 65,
    "2": 4433,
    "3": 30,
    "4": 144,
    "5": 8,
    "7": 618,
    "8": 2882
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_client1_highway_night_stable_boxes.csv"
}
round017 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round017 client2_citystreet_day: pseudo scan 250/1500 images, kept 2696 boxes
round017 client2_citystreet_day: pseudo scan 500/1500 images, kept 5424 boxes
round017 client2_citystreet_day: pseudo scan 750/1500 images, kept 8159 boxes
round017 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10912 boxes
round017 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13630 boxes
round017 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16289 boxes
{
  "round": "round017",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round016_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13761,
  "boxes_per_kept_image": 9.198529411764707,
  "mean_conf": 0.8216312159680929,
  "mean_stability": 0.946994342691165,
  "mean_score": 0.7815631200824721,
  "class_counts": {
    "0": 1485,
    "2": 7331,
    "3": 205,
    "4": 608,
    "5": 65,
    "7": 1515,
    "8": 2552
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_client2_citystreet_day_stable_boxes.csv"
}
round017 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round017 client3_citystreet_night: pseudo scan 250/1500 images, kept 2309 boxes
round017 client3_citystreet_night: pseudo scan 500/1500 images, kept 4582 boxes
round017 client3_citystreet_night: pseudo scan 750/1500 images, kept 6824 boxes
round017 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8989 boxes
round017 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11356 boxes
round017 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13612 boxes
{
  "round": "round017",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round016_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 11595,
  "boxes_per_kept_image": 7.877038043478261,
  "mean_conf": 0.7310101813928688,
  "mean_stability": 0.9268381085566479,
  "mean_score": 0.682121921994952,
  "class_counts": {
    "0": 555,
    "2": 6126,
    "3": 69,
    "4": 149,
    "5": 38,
    "7": 2084,
    "8": 2574
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_client3_citystreet_night_stable_boxes.csv"
}
round017 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round017 client4_residential_day: pseudo scan 250/1500 images, kept 2582 boxes
round017 client4_residential_day: pseudo scan 500/1500 images, kept 5179 boxes
round017 client4_residential_day: pseudo scan 750/1500 images, kept 7731 boxes
round017 client4_residential_day: pseudo scan 1000/1500 images, kept 10211 boxes
round017 client4_residential_day: pseudo scan 1250/1500 images, kept 12726 boxes
round017 client4_residential_day: pseudo scan 1500/1500 images, kept 15201 boxes
{
  "round": "round017",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round016_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9982,
  "boxes_per_kept_image": 6.699328859060403,
  "mean_conf": 0.853061764429194,
  "mean_stability": 0.9551266853256661,
  "mean_score": 0.818392332273728,
  "class_counts": {
    "0": 395,
    "2": 6841,
    "3": 69,
    "4": 319,
    "5": 44,
    "7": 535,
    "8": 1779
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_client4_residential_day_stable_boxes.csv"
}
round017 client5_residential_night: pseudo scan 1/1500 images, kept 8 boxes
round017 client5_residential_night: pseudo scan 250/1500 images, kept 2241 boxes
round017 client5_residential_night: pseudo scan 500/1500 images, kept 4446 boxes
round017 client5_residential_night: pseudo scan 750/1500 images, kept 6657 boxes
round017 client5_residential_night: pseudo scan 1000/1500 images, kept 8929 boxes
round017 client5_residential_night: pseudo scan 1250/1500 images, kept 11215 boxes
round017 client5_residential_night: pseudo scan 1500/1500 images, kept 13479 boxes
{
  "round": "round017",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round016_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1470,
  "pseudo_boxes_kept": 8439,
  "boxes_per_kept_image": 5.740816326530612,
  "mean_conf": 0.7964378212537652,
  "mean_stability": 0.9420045480822511,
  "mean_score": 0.7534274086107571,
  "class_counts": {
    "0": 128,
    "2": 6066,
    "3": 34,
    "4": 99,
    "5": 23,
    "7": 694,
    "8": 1395
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round017_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31253 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round017_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round017_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client0_highway_day_stable_train' images and labels...5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 14627.81it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:56:21.758270292 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:56:21.767014865 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2080       640  0.003587   0.04884  0.005006     4.594:   3%|▎         | 1/39 [00:21<13:34, 21.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1859       640  0.003479   0.04753  0.004308     4.426:   5%|▌         | 2/39 [00:22<05:44,  9.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1881       640  0.003509   0.04643  0.004589     4.362:   8%|▊         | 3/39 [00:23<03:16,  5.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2099       640  0.003512   0.04558  0.004558     4.292:  10%|█         | 4/39 [00:23<02:07,  3.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1997       640   0.00348   0.04508  0.004504     4.245:  13%|█▎        | 5/39 [00:24<01:27,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1763       640  0.003443   0.04411  0.004391     4.155:  15%|█▌        | 6/39 [00:25<01:03,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1961       640  0.003444   0.04384  0.004424     4.137:  18%|█▊        | 7/39 [00:25<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1955       640  0.003446   0.04349  0.004507     4.115:  21%|██        | 8/39 [00:26<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2155       640  0.003464   0.04355  0.004553     4.125:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2059       640  0.003474   0.04373  0.004558     4.141:  26%|██▌       | 10/39 [00:27<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2084       640  0.003477   0.04374  0.004576     4.143:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2004       640  0.003474   0.04368  0.004677     4.146:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1885       640  0.003459    0.0434  0.004658     4.122:  33%|███▎      | 13/39 [00:29<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2238       640  0.003455   0.04338  0.004615     4.116:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1945       640  0.003454   0.04325  0.004573     4.102:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1985       640  0.003453   0.04301  0.004541     4.081:  41%|████      | 16/39 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1690       640  0.003454   0.04277  0.004599     4.066:  44%|████▎     | 17/39 [00:32<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1947       640  0.003456   0.04262  0.004599     4.054:  46%|████▌     | 18/39 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1701       640   0.00345   0.04234  0.004589      4.03:  49%|████▊     | 19/39 [00:33<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2270       640  0.003449   0.04229  0.004588     4.026:  51%|█████▏    | 20/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2011       640  0.003447   0.04229  0.004577     4.025:  54%|█████▍    | 21/39 [00:34<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1780       640  0.003447    0.0422  0.004556     4.016:  56%|█████▋    | 22/39 [00:35<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1953       640  0.003443   0.04204  0.004529     4.001:  59%|█████▉    | 23/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1972       640  0.003442   0.04202   0.00454         4:  62%|██████▏   | 24/39 [00:36<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2009       640  0.003438   0.04195  0.004542     3.994:  64%|██████▍   | 25/39 [00:37<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1966       640  0.003437   0.04187  0.004533     3.987:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53      0.433      0.413      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.14it/s]

                 all        738      14937      0.515      0.435      0.411      0.231
                   0        738       1052       0.48      0.562      0.531      0.256
                   1        738         44      0.463       0.25      0.222     0.0974
                   2        738       8622      0.667      0.738       0.75      0.478
                   3        738        151      0.434      0.417      0.425      0.325
                   4        738        467      0.468      0.595      0.539      0.384
                   5        738         70      0.263      0.414      0.294      0.146
                   6        738         65      0.225      0.138      0.164     0.0676
                   7        738       1619      0.526      0.633      0.591      0.244
                   8        738       2845      0.628      0.606      0.598      0.315
                   9        738          2          1          0   0.000369   0.000332

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:57:44.219839005 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31254 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round017_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round017_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client1_highway_night_stable_train' images and labels...4895 found, 2886 missing, 0 empty, 0 corrupted: 100%|██████████| 7781/7781 [00:00<00:00, 10636.34it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.357843137254902
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2886 missing, 0 empty, 0 corrupted: 100%|██████████| 7781/7781 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 17:58:01.758372660 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 17:58:01.770471080 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1898       640  0.003422    0.0424  0.004896     4.058:   2%|▎         | 1/40 [00:21<14:11, 21.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640   0.00344   0.04229  0.005276      4.08:   5%|▌         | 2/40 [00:22<06:00,  9.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1770       640  0.003447   0.04138  0.005033     3.989:   8%|▊         | 3/40 [00:23<03:24,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2162       640  0.003491   0.04147  0.005128     4.007:  10%|█         | 4/40 [00:24<02:12,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1835       640  0.003479   0.04083  0.004975     3.943:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1681       640  0.003464    0.0399  0.004737     3.848:  15%|█▌        | 6/40 [00:25<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640  0.003467   0.03978  0.004749      3.84:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640   0.00346   0.03929  0.004682     3.795:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003453   0.03884  0.004602     3.752:  22%|██▎       | 9/40 [00:27<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1763       640  0.003454   0.03858  0.004609     3.731:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2107       640  0.003455    0.0385  0.004664     3.729:  28%|██▊       | 11/40 [00:29<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003458   0.03824  0.004653     3.708:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1809       640  0.003457   0.03787  0.004632     3.676:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003451   0.03768  0.004614      3.66:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1690       640   0.00344   0.03733  0.004609     3.631:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003436   0.03723  0.004584      3.62:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1983       640  0.003446   0.03721  0.004594      3.62:  42%|████▎     | 17/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003445   0.03714  0.004581     3.614:  45%|████▌     | 18/40 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1698       640  0.003439   0.03685  0.004561     3.588:  48%|████▊     | 19/40 [00:34<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2216       640  0.003435   0.03694  0.004538     3.593:  50%|█████     | 20/40 [00:34<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003437   0.03682   0.00454     3.584:  52%|█████▎    | 21/40 [00:35<00:12,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1620       640  0.003434   0.03655   0.00455     3.562:  55%|█████▌    | 22/40 [00:36<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2176       640  0.003433   0.03664  0.004525     3.568:  57%|█████▊    | 23/40 [00:36<00:11,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640   0.00343   0.03653  0.004547      3.56:  60%|██████    | 24/40 [00:37<00:10,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1754       640  0.003428   0.03635  0.004528     3.545:  62%|██████▎   | 25/40 [00:38<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1835       640  0.003426   0.03625  0.004517     3.536:  65%|██████▌   | 26/40 [00:38<00:09,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.548      0.424      0.408      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.533      0.427      0.406       0.23
                   0        738       1052      0.537       0.54      0.532      0.256
                   1        738         44      0.458      0.227       0.21     0.0989
                   2        738       8622      0.663      0.734       0.75       0.48
                   3        738        151      0.432      0.424      0.424      0.322
                   4        738        467      0.462      0.595       0.53      0.378
                   5        738         70      0.338      0.429      0.275      0.138
                   6        738         65       0.25      0.108       0.17     0.0713
                   7        738       1619      0.548      0.616      0.579      0.241
                   8        738       2845      0.637      0.596      0.591       0.31
                   9        738          2          1          0   0.000277    0.00025

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 17:59:25.715961655 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31255 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round017_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round017_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 11927.63it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 17:59:42.281726403 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 17:59:42.282392090 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003538   0.05338  0.004542     4.917:   3%|▎         | 1/39 [00:21<13:51, 21.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003491   0.05221  0.004912     4.849:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003455   0.05108   0.00493     4.757:   8%|▊         | 3/39 [00:23<03:21,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003464   0.04991  0.004852     4.658:  10%|█         | 4/39 [00:24<02:10,  3.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003462   0.04926  0.004773       4.6:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003429    0.0481  0.004739     4.501:  15%|█▌        | 6/39 [00:25<01:05,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003439   0.04773  0.004795     4.477:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640   0.00343   0.04729  0.004749     4.437:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003444   0.04722  0.004682     4.427:  23%|██▎       | 9/39 [00:27<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003431   0.04689  0.004675       4.4:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003434   0.04674  0.004668     4.388:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003439   0.04621  0.004679     4.347:  31%|███       | 12/39 [00:29<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003445   0.04602   0.00464     4.328:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003454   0.04598  0.004603     4.323:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003455   0.04578  0.004578     4.305:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003446   0.04543  0.004569     4.275:  41%|████      | 16/39 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003437   0.04517  0.004596     4.257:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640   0.00343   0.04507   0.00458     4.247:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003431   0.04478  0.004563     4.222:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003426   0.04476  0.004556     4.219:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003418   0.04457  0.004534     4.202:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003412   0.04446  0.004524     4.192:  56%|█████▋    | 22/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003405   0.04434  0.004523     4.181:  59%|█████▉    | 23/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003401   0.04426  0.004513     4.174:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003397   0.04415  0.004512     4.165:  64%|██████▍   | 25/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003391   0.04409  0.004496     4.158:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53      0.434       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.518      0.436      0.409       0.23
                   0        738       1052      0.594      0.525      0.534      0.253
                   1        738         44        0.5       0.25      0.212     0.0976
                   2        738       8622      0.633       0.75      0.753      0.478
                   3        738        151      0.345       0.45       0.43      0.326
                   4        738        467       0.43       0.63      0.534      0.376
                   5        738         70      0.325      0.414      0.279      0.144
                   6        738         65      0.207     0.0923      0.174      0.074
                   7        738       1619      0.547      0.632       0.58      0.239
                   8        738       2845      0.601      0.615      0.597      0.316
                   9        738          2          1          0   0.000275   0.000248

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:01:08.712566334 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31256 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round017_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round017_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client3_citystreet_night_stable_train' images and labels...4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<00:00, 13616.08it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29014483627204
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:01:25.342586247 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:01:25.351843101 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1885       640  0.003509   0.04667  0.004456     4.371:   2%|▎         | 1/40 [00:21<13:49, 21.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1730       640  0.003412   0.04352  0.004671     4.128:   5%|▌         | 2/40 [00:22<05:57,  9.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1998       640  0.003413   0.04364  0.004374     4.114:   8%|▊         | 3/40 [00:23<03:25,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2131       640  0.003417   0.04313  0.004198     4.059:  10%|█         | 4/40 [00:24<02:13,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2056       640   0.00341   0.04269  0.004125     4.018:  12%|█▎        | 5/40 [00:24<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1648       640  0.003392   0.04136  0.004146     3.912:  15%|█▌        | 6/40 [00:25<01:06,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1750       640  0.003376   0.04051  0.004168     3.844:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1936       640  0.003373   0.04022  0.004104     3.816:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1909       640  0.003373   0.04012  0.004091     3.806:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1990       640  0.003385   0.04013  0.004119      3.81:  25%|██▌       | 10/40 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2088       640  0.003391   0.04001  0.004205     3.809:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1905       640  0.003393   0.03972   0.00416     3.782:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1942       640   0.00339    0.0395  0.004187     3.766:  32%|███▎      | 13/40 [00:30<00:20,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1975       640  0.003388   0.03936  0.004213     3.757:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1888       640  0.003385   0.03922  0.004226     3.746:  38%|███▊      | 15/40 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1891       640  0.003382   0.03906  0.004209     3.732:  40%|████      | 16/40 [00:32<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1723       640   0.00339   0.03881  0.004271     3.718:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1943       640  0.003387   0.03857  0.004316     3.702:  45%|████▌     | 18/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1855       640  0.003391   0.03832  0.004291      3.68:  48%|████▊     | 19/40 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2084       640  0.003395   0.03828  0.004315     3.679:  50%|█████     | 20/40 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1870       640  0.003408   0.03817    0.0043      3.67:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1954       640  0.003408   0.03815   0.00428     3.667:  55%|█████▌    | 22/40 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2256       640  0.003409   0.03831  0.004289     3.681:  57%|█████▊    | 23/40 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2038       640  0.003412    0.0383  0.004335     3.684:  60%|██████    | 24/40 [00:37<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2162       640  0.003414   0.03828   0.00433     3.682:  62%|██████▎   | 25/40 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1825       640  0.003411   0.03817  0.004324     3.672:  65%|██████▌   | 26/40 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.585      0.397      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.575      0.399      0.408       0.23
                   0        738       1052      0.613        0.5      0.522      0.253
                   1        738         44      0.594      0.136      0.234      0.108
                   2        738       8622        0.7      0.717      0.746      0.477
                   3        738        151      0.495      0.397      0.422      0.322
                   4        738        467      0.465      0.604      0.536      0.378
                   5        738         70      0.403        0.4      0.289      0.143
                   6        738         65      0.245     0.0615      0.161     0.0683
                   7        738       1619      0.572      0.595      0.575       0.24
                   8        738       2845      0.667      0.575      0.591      0.313
                   9        738          2          1          0   0.000306   0.000275

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:02:49.732237762 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31257 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round017_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round017_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 11818.29it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:03:06.522447416 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:03:06.534085413 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2153       640  0.003473   0.05234  0.004758     4.846:   3%|▎         | 1/39 [00:21<13:37, 21.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2109       640  0.003428   0.05093   0.00515     4.761:   5%|▌         | 2/39 [00:22<05:47,  9.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1782       640  0.003376   0.04907  0.005034     4.599:   8%|▊         | 3/39 [00:23<03:18,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640   0.00337   0.04844  0.004944     4.541:  10%|█         | 4/39 [00:24<02:08,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003361   0.04734  0.004938     4.451:  13%|█▎        | 5/39 [00:24<01:27,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1759       640  0.003359   0.04597  0.005016     4.347:  15%|█▌        | 6/39 [00:25<01:03,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003379   0.04572  0.004965     4.325:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2179       640  0.003392   0.04544  0.004851     4.295:  21%|██        | 8/39 [00:26<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2090       640  0.003394    0.0455  0.004791     4.295:  23%|██▎       | 9/39 [00:27<00:31,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003398   0.04533  0.004779     4.281:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640  0.003408   0.04531  0.004751     4.278:  28%|██▊       | 11/39 [00:28<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2189       640  0.003424   0.04517  0.004794     4.271:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003429   0.04509  0.004772     4.263:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003436   0.04497  0.004769     4.254:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003441    0.0447  0.004792     4.235:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003435   0.04436  0.004767     4.205:  41%|████      | 16/39 [00:31<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003431   0.04419  0.004727     4.188:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003426   0.04416  0.004691     4.182:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003428   0.04383  0.004701     4.157:  49%|████▊     | 19/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003419   0.04378   0.00469     4.151:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003413   0.04366  0.004658     4.139:  54%|█████▍    | 21/39 [00:35<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003412    0.0436  0.004662     4.134:  56%|█████▋    | 22/39 [00:35<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003411   0.04356  0.004671     4.131:  59%|█████▉    | 23/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003406   0.04339  0.004663     4.117:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003407   0.04327  0.004655     4.107:  64%|██████▍   | 25/39 [00:37<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003404   0.04314  0.004626     4.094:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.521      0.441      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.507      0.442      0.411      0.231
                   0        738       1052      0.499      0.558      0.534      0.255
                   1        738         44      0.496      0.273      0.215     0.0939
                   2        738       8622      0.657      0.739       0.75      0.476
                   3        738        151      0.366       0.45      0.437      0.328
                   4        738        467      0.436      0.619      0.538       0.38
                   5        738         70      0.282      0.414      0.289      0.144
                   6        738         65      0.214      0.123      0.165       0.07
                   7        738       1619      0.524      0.631      0.582      0.239
                   8        738       2845        0.6      0.618      0.596      0.318
                   9        738          2          1          0   0.000253   0.000228

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:04:29.956129027 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31258 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round017_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round017_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client5_residential_night_stable_train' images and labels...4885 found, 2936 missing, 0 empty, 0 corrupted: 100%|██████████| 7821/7821 [00:00<00:00, 11412.41it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.297369664514097
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round017_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2936 missing, 0 empty, 0 corrupted: 100%|██████████| 7821/7821 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:04:46.656283310 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:04:46.674891639 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2269       640  0.003501   0.04754  0.005244     4.503:   2%|▎         | 1/40 [00:22<14:55, 22.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1806       640   0.00342   0.04453  0.004662     4.209:   5%|▌         | 2/40 [00:23<06:18,  9.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1691       640  0.003394    0.0432  0.004573     4.093:   8%|▊         | 3/40 [00:24<03:34,  5.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003408   0.04242  0.004561     4.031:  10%|█         | 4/40 [00:25<02:19,  3.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003396    0.0414  0.004447      3.94:  12%|█▎        | 5/40 [00:26<01:34,  2.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1648       640  0.003418   0.04071   0.00452     3.892:  15%|█▌        | 6/40 [00:26<01:08,  2.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640   0.00341   0.04001   0.00449     3.833:  18%|█▊        | 7/40 [00:27<00:51,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640  0.003413   0.04004  0.004418     3.829:  20%|██        | 8/40 [00:28<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1973       640   0.00343   0.03991  0.004419      3.82:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1967       640  0.003424   0.03957  0.004377     3.789:  25%|██▌       | 10/40 [00:29<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2209       640   0.00342   0.03962  0.004334      3.79:  28%|██▊       | 11/40 [00:30<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003414    0.0394    0.0044     3.777:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003423   0.03922  0.004448     3.768:  32%|███▎      | 13/40 [00:31<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2235       640  0.003428   0.03924  0.004398     3.766:  35%|███▌      | 14/40 [00:31<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1694       640   0.00342   0.03877  0.004379     3.726:  38%|███▊      | 15/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1668       640  0.003408   0.03829  0.004375     3.686:  40%|████      | 16/40 [00:33<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003418   0.03818  0.004413     3.681:  42%|████▎     | 17/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1931       640  0.003413    0.0381  0.004428     3.675:  45%|████▌     | 18/40 [00:34<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1498       640  0.003419   0.03758  0.004469     3.637:  48%|████▊     | 19/40 [00:35<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1978       640  0.003422   0.03746  0.004461     3.628:  50%|█████     | 20/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2039       640  0.003425   0.03739  0.004464     3.623:  52%|█████▎    | 21/40 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1672       640  0.003424   0.03718  0.004458     3.605:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003424   0.03706  0.004467     3.596:  57%|█████▊    | 23/40 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003423   0.03694  0.004475     3.587:  60%|██████    | 24/40 [00:38<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1939       640  0.003427   0.03684  0.004512     3.583:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003427    0.0367  0.004499      3.57:  65%|██████▌   | 26/40 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.558      0.411      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.24it/s]

                 all        738      14937      0.548      0.413      0.408       0.23
                   0        738       1052      0.573      0.519      0.529      0.254
                   1        738         44      0.526      0.205      0.223      0.101
                   2        738       8622      0.691      0.721      0.746      0.478
                   3        738        151      0.468      0.397      0.419      0.321
                   4        738        467      0.482      0.591      0.537       0.38
                   5        738         70      0.305        0.4      0.282      0.144
                   6        738         65      0.233     0.0747      0.159     0.0655
                   7        738       1619      0.571      0.617      0.587       0.24
                   8        738       2845      0.631      0.604      0.596      0.317
                   9        738          2          1          0   0.000243   0.000219

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:06:12.385232441 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31259 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round017_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round017_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:06:27.062033839 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:06:27.070884334 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03077   0.03576  0.003695     5.618:   3%|▎         | 1/31 [00:32<16:13, 32.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640    0.0308   0.03545  0.003746       5.6:   6%|▋         | 2/31 [00:33<06:44, 13.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03014   0.03415  0.003646     5.435:  10%|▉         | 3/31 [00:34<03:42,  7.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02966   0.03279  0.003444     5.271:  13%|█▎        | 4/31 [00:35<02:18,  5.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02957   0.03281  0.003452     5.266:  16%|█▌        | 5/31 [00:35<01:30,  3.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02965   0.03265  0.003474     5.262:  19%|█▉        | 6/31 [00:36<01:02,  2.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02971   0.03235  0.003527     5.246:  23%|██▎       | 7/31 [00:36<00:45,  1.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640    0.0296   0.03237  0.003526      5.24:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02966   0.03229  0.003449     5.232:  29%|██▉       | 9/31 [00:37<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02967    0.0324   0.00342      5.24:  32%|███▏      | 10/31 [00:38<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02964   0.03242   0.00344      5.24:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02956   0.03215  0.003435     5.212:  39%|███▊      | 12/31 [00:39<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02952   0.03211  0.003388     5.202:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02954   0.03201  0.003362     5.193:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02956   0.03192   0.00341     5.192:  48%|████▊     | 15/31 [00:41<00:10,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02957   0.03181  0.003411     5.183:  52%|█████▏    | 16/31 [00:42<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640    0.0296   0.03183   0.00339     5.186:  55%|█████▍    | 17/31 [00:42<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02969   0.03196  0.003364     5.201:  58%|█████▊    | 18/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02966   0.03186  0.003344     5.189:  61%|██████▏   | 19/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02968   0.03209  0.003341     5.209:  65%|██████▍   | 20/31 [00:44<00:06,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02973   0.03215  0.003361      5.22:  68%|██████▊   | 21/31 [00:45<00:05,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02977   0.03227  0.003342     5.231:  71%|███████   | 22/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02978   0.03235  0.003319     5.236:  74%|███████▍  | 23/31 [00:46<00:04,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02983   0.03248  0.003311      5.25:  77%|███████▋  | 24/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02986   0.03248  0.003322     5.253:  81%|████████  | 25/31 [00:47<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02994   0.03259   0.00333     5.269:  84%|████████▍ | 26/31 [00:48<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.534      0.422       0.41      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.03it/s]

                 all        738      14937       0.52      0.421      0.407      0.227
                   0        738       1052      0.517      0.533      0.519      0.252
                   1        738         44      0.389      0.159      0.201     0.0857
                   2        738       8622      0.674      0.732      0.747      0.481
                   3        738        151      0.425      0.444      0.431      0.326
                   4        738        467      0.478      0.589      0.532      0.375
                   5        738         70      0.308      0.414      0.315      0.142
                   6        738         65      0.249      0.123      0.164     0.0655
                   7        738       1619      0.553      0.619      0.579       0.24
                   8        738       2845      0.604      0.601      0.583      0.306
                   9        738          2          1          0   0.000418   0.000376

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round017_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 18:08:07.670727579 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round018 phase_round=18 ===

02 head-to-full DQA:  53%|█████▎    | 17/32 [4:00:48<3:31:38, 846.54s/round, elapsed=4h00m48s, eta=3h32m29s, phase=phase1_head, round=17]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round018 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round018 client0_highway_day: pseudo scan 250/1500 images, kept 2370 boxes
round018 client0_highway_day: pseudo scan 500/1500 images, kept 4803 boxes
round018 client0_highway_day: pseudo scan 750/1500 images, kept 7145 boxes
round018 client0_highway_day: pseudo scan 1000/1500 images, kept 9523 boxes
round018 client0_highway_day: pseudo scan 1250/1500 images, kept 11853 boxes
round018 client0_highway_day: pseudo scan 1500/1500 images, kept 14249 boxes
{
  "round": "round018",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round017_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 11224,
  "boxes_per_kept_image": 7.532885906040269,
  "mean_conf": 0.8236305905706485,
  "mean_stability": 0.9482576382251526,
  "mean_score": 0.7843906784822005,
  "class_counts": {
    "0": 159,
    "2": 6413,
    "3": 120,
    "4": 565,
    "5": 8,
    "7": 567,
    "8": 3392
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_client0_highway_day_stable_boxes.csv"
}
round018 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round018 client1_highway_night: pseudo scan 250/1500 images, kept 1562 boxes
round018 client1_highway_night: pseudo scan 500/1500 images, kept 3231 boxes
round018 client1_highway_night: pseudo scan 750/1500 images, kept 4937 boxes
round018 client1_highway_night: pseudo scan 1000/1500 images, kept 6533 boxes
round018 client1_highway_night: pseudo scan 1250/1500 images, kept 8167 boxes
round018 client1_highway_night: pseudo scan 1500/1500 images, kept 9761 boxes
{
  "round": "round018",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round017_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1446,
  "pseudo_boxes_kept": 8110,
  "boxes_per_kept_image": 5.608575380359612,
  "mean_conf": 0.737877301656803,
  "mean_stability": 0.9301515529761332,
  "mean_score": 0.6905384542706041,
  "class_counts": {
    "0": 65,
    "2": 4393,
    "3": 27,
    "4": 146,
    "5": 8,
    "7": 610,
    "8": 2861
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_client1_highway_night_stable_boxes.csv"
}
round018 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round018 client2_citystreet_day: pseudo scan 250/1500 images, kept 2688 boxes
round018 client2_citystreet_day: pseudo scan 500/1500 images, kept 5421 boxes
round018 client2_citystreet_day: pseudo scan 750/1500 images, kept 8153 boxes
round018 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10916 boxes
round018 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13631 boxes
round018 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16297 boxes
{
  "round": "round018",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round017_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13783,
  "boxes_per_kept_image": 9.213235294117647,
  "mean_conf": 0.8227291978522135,
  "mean_stability": 0.946299433245469,
  "mean_score": 0.7820757025429826,
  "class_counts": {
    "0": 1493,
    "2": 7334,
    "3": 206,
    "4": 593,
    "5": 64,
    "7": 1520,
    "8": 2573
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_client2_citystreet_day_stable_boxes.csv"
}
round018 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round018 client3_citystreet_night: pseudo scan 250/1500 images, kept 2302 boxes
round018 client3_citystreet_night: pseudo scan 500/1500 images, kept 4575 boxes
round018 client3_citystreet_night: pseudo scan 750/1500 images, kept 6817 boxes
round018 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8970 boxes
round018 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11338 boxes
round018 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13591 boxes
{
  "round": "round018",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round017_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1474,
  "pseudo_boxes_kept": 11569,
  "boxes_per_kept_image": 7.848710990502036,
  "mean_conf": 0.7329630108271816,
  "mean_stability": 0.9252751240395193,
  "mean_score": 0.6828567358000348,
  "class_counts": {
    "0": 556,
    "2": 6116,
    "3": 66,
    "4": 151,
    "5": 38,
    "7": 2079,
    "8": 2563
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_client3_citystreet_night_stable_boxes.csv"
}
round018 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round018 client4_residential_day: pseudo scan 250/1500 images, kept 2581 boxes
round018 client4_residential_day: pseudo scan 500/1500 images, kept 5177 boxes
round018 client4_residential_day: pseudo scan 750/1500 images, kept 7723 boxes
round018 client4_residential_day: pseudo scan 1000/1500 images, kept 10197 boxes
round018 client4_residential_day: pseudo scan 1250/1500 images, kept 12703 boxes
round018 client4_residential_day: pseudo scan 1500/1500 images, kept 15173 boxes
{
  "round": "round018",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round017_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9965,
  "boxes_per_kept_image": 6.6879194630872485,
  "mean_conf": 0.8548894641839615,
  "mean_stability": 0.9548575128374899,
  "mean_score": 0.8198302667898406,
  "class_counts": {
    "0": 394,
    "2": 6828,
    "3": 68,
    "4": 317,
    "5": 46,
    "7": 535,
    "8": 1777
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_client4_residential_day_stable_boxes.csv"
}
round018 client5_residential_night: pseudo scan 1/1500 images, kept 8 boxes
round018 client5_residential_night: pseudo scan 250/1500 images, kept 2224 boxes
round018 client5_residential_night: pseudo scan 500/1500 images, kept 4430 boxes
round018 client5_residential_night: pseudo scan 750/1500 images, kept 6625 boxes
round018 client5_residential_night: pseudo scan 1000/1500 images, kept 8886 boxes
round018 client5_residential_night: pseudo scan 1250/1500 images, kept 11151 boxes
round018 client5_residential_night: pseudo scan 1500/1500 images, kept 13410 boxes
{
  "round": "round018",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round017_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1468,
  "pseudo_boxes_kept": 8403,
  "boxes_per_kept_image": 5.724114441416893,
  "mean_conf": 0.797227146372857,
  "mean_stability": 0.9408155846607114,
  "mean_score": 0.7532365377590714,
  "class_counts": {
    "0": 128,
    "2": 6035,
    "3": 32,
    "4": 97,
    "5": 24,
    "7": 685,
    "8": 1402
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round018_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31260 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round018_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round018_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7861 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client0_highway_day_stable_train' images and labels...5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 13977.88it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:10:21.624224703 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:10:21.695677846 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1992       640  0.003503   0.04645  0.005371     4.426:   3%|▎         | 1/39 [00:21<13:48, 21.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2082       640  0.003456   0.04614  0.004645     4.339:   5%|▌         | 2/39 [00:22<05:52,  9.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1944       640  0.003456   0.04492  0.004722     4.248:   8%|▊         | 3/39 [00:23<03:20,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1749       640  0.003419   0.04426  0.004698      4.19:  10%|█         | 4/39 [00:24<02:09,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1846       640  0.003415   0.04429  0.004741     4.196:  13%|█▎        | 5/39 [00:25<01:29,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1885       640  0.003412   0.04338  0.004637     4.114:  15%|█▌        | 6/39 [00:25<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2111       640  0.003413    0.0432  0.004546     4.092:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2087       640  0.003418   0.04331  0.004524       4.1:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2059       640  0.003427   0.04349  0.004542     4.117:  23%|██▎       | 9/39 [00:27<00:32,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2010       640  0.003443   0.04347  0.004566     4.118:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1989       640  0.003443   0.04322  0.004535     4.096:  28%|██▊       | 11/39 [00:29<00:24,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1940       640  0.003447   0.04337  0.004618     4.115:  31%|███       | 12/39 [00:29<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2212       640  0.003445   0.04331  0.004635     4.111:  33%|███▎      | 13/39 [00:30<00:19,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2141       640  0.003447   0.04331  0.004586     4.108:  36%|███▌      | 14/39 [00:31<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1883       640  0.003451   0.04309  0.004548     4.087:  38%|███▊      | 15/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1994       640  0.003452   0.04287  0.004525     4.067:  41%|████      | 16/39 [00:32<00:15,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1890       640  0.003454   0.04279  0.004545     4.063:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2241       640  0.003453   0.04265  0.004503     4.048:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1757       640  0.003452   0.04238  0.004513     4.027:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2061       640  0.003446   0.04234  0.004488     4.022:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2138       640  0.003449   0.04242  0.004473     4.027:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2087       640  0.003451   0.04238  0.004449     4.023:  56%|█████▋    | 22/39 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1992       640  0.003442   0.04225  0.004425     4.009:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2257       640  0.003445   0.04238  0.004404     4.018:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2066       640  0.003444   0.04229  0.004421     4.012:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1932       640  0.003445   0.04219  0.004404     4.003:  67%|██████▋   | 26/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.517      0.443      0.413      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.505      0.445      0.411      0.231
                   0        738       1052      0.448      0.571      0.531      0.255
                   1        738         44      0.444      0.273      0.214     0.0971
                   2        738       8622      0.659      0.741      0.752       0.48
                   3        738        151       0.38      0.417      0.429      0.321
                   4        738        467      0.459      0.612      0.539      0.384
                   5        738         70      0.268      0.414      0.293      0.149
                   6        738         65      0.248      0.169      0.169     0.0709
                   7        738       1619      0.521      0.641      0.591      0.242
                   8        738       2845       0.62      0.608      0.597      0.314
                   9        738          2          1          0   0.000409   0.000368

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:11:44.151273207 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31261 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round018_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round018_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client1_highway_night_stable_train' images and labels...4895 found, 2878 missing, 0 empty, 0 corrupted: 100%|██████████| 7773/7773 [00:00<00:00, 13827.07it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.367563291139241
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2878 missing, 0 empty, 0 corrupted: 100%|██████████| 7773/7773 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:12:01.482062331 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:12:01.488732166 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2280       640  0.003561   0.04646   0.00478     4.384:   2%|▎         | 1/40 [00:22<14:20, 22.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003525   0.04275  0.004686     4.077:   5%|▌         | 2/40 [00:22<06:04,  9.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640   0.00346    0.0421  0.004469     4.002:   8%|▊         | 3/40 [00:23<03:27,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1888       640  0.003452   0.04099  0.004515     3.917:  10%|█         | 4/40 [00:24<02:14,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1836       640  0.003429   0.04045  0.004586     3.877:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1758       640  0.003433   0.03986   0.00457     3.829:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1857       640  0.003434   0.03955  0.004625     3.808:  18%|█▊        | 7/40 [00:26<00:49,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2390       640  0.003431   0.04002  0.004652     3.848:  20%|██        | 8/40 [00:27<00:39,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003438   0.03963  0.004663     3.818:  22%|██▎       | 9/40 [00:27<00:32,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640   0.00344    0.0394  0.004654       3.8:  25%|██▌       | 10/40 [00:28<00:27,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2285       640  0.003445   0.03933  0.004661     3.795:  28%|██▊       | 11/40 [00:28<00:23,  1.22it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003442   0.03887  0.004655     3.758:  30%|███       | 12/40 [00:29<00:21,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640   0.00344   0.03881   0.00464     3.751:  32%|███▎      | 13/40 [00:30<00:19,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1809       640  0.003446   0.03852  0.004575     3.723:  35%|███▌      | 14/40 [00:30<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1955       640   0.00344   0.03829  0.004581     3.705:  38%|███▊      | 15/40 [00:31<00:16,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003443   0.03825   0.00459     3.703:  40%|████      | 16/40 [00:32<00:15,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1715       640  0.003442   0.03803  0.004611     3.686:  42%|████▎     | 17/40 [00:32<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003445    0.0379  0.004627     3.678:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1523       640  0.003446    0.0374  0.004631     3.638:  48%|████▊     | 19/40 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1888       640  0.003441   0.03723   0.00461     3.623:  50%|█████     | 20/40 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2060       640  0.003446   0.03716  0.004633     3.619:  52%|█████▎    | 21/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003451   0.03712   0.00463     3.616:  55%|█████▌    | 22/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1816       640  0.003445    0.0369  0.004626     3.598:  57%|█████▊    | 23/40 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2170       640  0.003448   0.03692  0.004673     3.603:  60%|██████    | 24/40 [00:37<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640   0.00345   0.03675  0.004664     3.589:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1946       640  0.003446    0.0367  0.004623     3.581:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53      0.425      0.414      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.531      0.417      0.412      0.232
                   0        738       1052      0.523      0.546      0.529      0.256
                   1        738         44      0.491      0.182      0.227      0.104
                   2        738       8622      0.665      0.734      0.749      0.481
                   3        738        151      0.424      0.404      0.422      0.321
                   4        738        467       0.47      0.587      0.537      0.383
                   5        738         70      0.342      0.414      0.295      0.148
                   6        738         65      0.226     0.0769      0.175      0.071
                   7        738       1619      0.543      0.631       0.59      0.242
                   8        738       2845      0.625      0.599      0.593       0.31
                   9        738          2          1          0   0.000367    0.00033

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:13:24.136423668 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31262 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round018_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round018_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 16751.69it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:13:40.905772964 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:13:40.979068148 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2066       640  0.003541   0.05359  0.004547     4.935:   3%|▎         | 1/39 [00:21<13:47, 21.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2187       640  0.003495   0.05242  0.004912     4.866:   5%|▌         | 2/39 [00:22<05:49,  9.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1974       640  0.003459   0.05127  0.004937     4.773:   8%|▊         | 3/39 [00:23<03:20,  5.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1957       640  0.003468   0.05008  0.004856     4.672:  10%|█         | 4/39 [00:24<02:10,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2145       640  0.003466   0.04942  0.004776     4.613:  13%|█▎        | 5/39 [00:25<01:29,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1780       640  0.003434   0.04824  0.004741     4.513:  15%|█▌        | 6/39 [00:25<01:04,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1960       640  0.003444   0.04786  0.004795     4.488:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1897       640  0.003435   0.04742  0.004749     4.448:  21%|██        | 8/39 [00:27<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2025       640  0.003449   0.04734  0.004682     4.438:  23%|██▎       | 9/39 [00:27<00:32,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003436   0.04701  0.004673     4.409:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003439   0.04685  0.004666     4.396:  28%|██▊       | 11/39 [00:29<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1792       640  0.003444   0.04632  0.004676     4.355:  31%|███       | 12/39 [00:29<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2094       640   0.00345   0.04611  0.004637     4.336:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2134       640  0.003459   0.04607  0.004599      4.33:  36%|███▌      | 14/39 [00:31<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1930       640  0.003459   0.04586  0.004574     4.311:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1894       640  0.003451   0.04551  0.004564     4.282:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1504       640  0.003442   0.04525  0.004592     4.263:  44%|████▎     | 17/39 [00:33<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1920       640  0.003434   0.04515  0.004575     4.253:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1718       640  0.003435   0.04485  0.004558     4.228:  49%|████▊     | 19/39 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640   0.00343   0.04483  0.004551     4.225:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1849       640  0.003422   0.04463  0.004529     4.207:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1707       640  0.003417   0.04453  0.004519     4.197:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1860       640  0.003409    0.0444  0.004518     4.186:  59%|█████▉    | 23/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1900       640  0.003405   0.04432  0.004508     4.179:  62%|██████▏   | 24/39 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1848       640  0.003401   0.04421  0.004507     4.169:  64%|██████▍   | 25/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2050       640  0.003395   0.04415  0.004491     4.163:  67%|██████▋   | 26/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.534      0.426       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.522      0.427       0.41      0.231
                   0        738       1052      0.611       0.52      0.531      0.252
                   1        738         44      0.476      0.227      0.213        0.1
                   2        738       8622      0.645      0.746      0.753      0.478
                   3        738        151      0.356      0.437       0.43      0.324
                   4        738        467      0.435      0.617      0.534      0.375
                   5        738         70       0.35      0.414      0.284      0.148
                   6        738         65      0.191     0.0769      0.176     0.0743
                   7        738       1619       0.55      0.626      0.579      0.239
                   8        738       2845      0.611      0.611      0.596      0.315
                   9        738          2          1          0   0.000291   0.000262

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:15:06.299277032 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31263 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round018_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round018_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client3_citystreet_night_stable_train' images and labels...4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<00:00, 13015.73it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:15:22.440551939 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:15:22.442699756 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1933       640  0.003559   0.04584  0.004496     4.312:   2%|▎         | 1/40 [00:21<14:06, 21.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003533   0.04442  0.004875     4.226:   5%|▌         | 2/40 [00:22<05:58,  9.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1984       640  0.003511   0.04465   0.00489     4.244:   8%|▊         | 3/40 [00:23<03:23,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003484   0.04378  0.004824     4.167:  10%|█         | 4/40 [00:24<02:12,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1833       640  0.003452   0.04278  0.004771      4.08:  12%|█▎        | 5/40 [00:24<01:30,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003458   0.04224  0.004687     4.031:  15%|█▌        | 6/40 [00:25<01:06,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003463   0.04171  0.004641     3.985:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2016       640  0.003466   0.04144  0.004638     3.963:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003454   0.04106  0.004553     3.925:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003468    0.0409  0.004517     3.911:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003457   0.04054  0.004443     3.875:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1669       640  0.003447   0.04008  0.004486     3.841:  30%|███       | 12/40 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003443   0.03985   0.00449     3.823:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003444    0.0398  0.004495     3.819:  35%|███▌      | 14/40 [00:30<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1771       640  0.003439   0.03953  0.004507     3.798:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640  0.003431    0.0392  0.004452     3.767:  40%|████      | 16/40 [00:31<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1607       640  0.003434   0.03879  0.004459     3.735:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003438   0.03862  0.004462     3.721:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1791       640  0.003437   0.03829   0.00444     3.693:  48%|████▊     | 19/40 [00:33<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2210       640  0.003437   0.03829  0.004402      3.69:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003444   0.03818  0.004412     3.683:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1812       640  0.003444   0.03796  0.004377     3.663:  55%|█████▌    | 22/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640  0.003445   0.03794  0.004382     3.661:  57%|█████▊    | 23/40 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1804       640  0.003442   0.03776  0.004386     3.647:  60%|██████    | 24/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003442   0.03769  0.004374     3.641:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1815       640  0.003438   0.03755  0.004369     3.628:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.584      0.393      0.408       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.573      0.394      0.407       0.23
                   0        738       1052      0.615      0.499       0.52      0.252
                   1        738         44        0.5      0.114      0.212     0.0993
                   2        738       8622      0.701      0.716      0.747      0.478
                   3        738        151      0.503      0.397      0.426      0.327
                   4        738        467       0.48      0.591      0.535      0.375
                   5        738         70      0.415      0.386      0.292      0.147
                   6        738         65      0.282     0.0615      0.166     0.0709
                   7        738       1619      0.569      0.603      0.579       0.24
                   8        738       2845      0.662      0.575       0.59      0.312
                   9        738          2          1          0   0.000323   0.000291

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:16:46.473132453 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31264 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round018_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round018_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 13057.87it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:17:02.984331025 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:17:02.986345738 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2153       640  0.003475   0.05257  0.004757     4.864:   3%|▎         | 1/39 [00:22<13:58, 22.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2109       640  0.003431   0.05111  0.005147     4.775:   5%|▌         | 2/39 [00:22<05:56,  9.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1782       640   0.00338   0.04923  0.005041     4.612:   8%|▊         | 3/39 [00:23<03:22,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003374    0.0486  0.004948     4.554:  10%|█         | 4/39 [00:24<02:11,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003366   0.04748  0.004939     4.463:  13%|█▎        | 5/39 [00:25<01:29,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1759       640  0.003364    0.0461  0.005014     4.358:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003384   0.04586  0.004963     4.336:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2179       640  0.003396   0.04556  0.004851     4.305:  21%|██        | 8/39 [00:27<00:38,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2090       640  0.003398   0.04562  0.004789     4.304:  23%|██▎       | 9/39 [00:28<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003403   0.04544  0.004774     4.289:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640  0.003412   0.04542  0.004747     4.286:  28%|██▊       | 11/39 [00:29<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2189       640  0.003428   0.04527  0.004789     4.279:  31%|███       | 12/39 [00:30<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003433   0.04518  0.004764      4.27:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640   0.00344   0.04505  0.004761      4.26:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003445   0.04478  0.004784     4.241:  38%|███▊      | 15/39 [00:31<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003439   0.04444   0.00476     4.211:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003435   0.04426   0.00472     4.193:  44%|████▎     | 17/39 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003431   0.04423  0.004684     4.188:  46%|████▌     | 18/39 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003432    0.0439  0.004694     4.162:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003423   0.04385  0.004684     4.157:  51%|█████▏    | 20/39 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003418   0.04373  0.004652     4.144:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003416   0.04366  0.004656     4.138:  56%|█████▋    | 22/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003415   0.04362  0.004665     4.136:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640   0.00341   0.04345  0.004656     4.121:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003411   0.04333  0.004648     4.111:  64%|██████▍   | 25/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003408    0.0432  0.004619     4.098:  67%|██████▋   | 26/39 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.555      0.416      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.35it/s]

                 all        738      14937       0.54      0.418      0.411      0.231
                   0        738       1052      0.553      0.534      0.531      0.254
                   1        738         44      0.442      0.182      0.217     0.0969
                   2        738       8622      0.706       0.72      0.749      0.476
                   3        738        151      0.431      0.437      0.437      0.328
                   4        738        467      0.467      0.597       0.54       0.38
                   5        738         70      0.345      0.414      0.288      0.146
                   6        738         65       0.25     0.0769      0.168     0.0703
                   7        738       1619      0.559      0.614      0.582       0.24
                   8        738       2845      0.646        0.6      0.596      0.317
                   9        738          2          1          0   0.000259   0.000233

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:18:27.327620443 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31265 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round018_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round018_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client5_residential_night_stable_train' images and labels...4885 found, 2932 missing, 0 empty, 0 corrupted: 100%|██████████| 7817/7817 [00:00<00:00, 9971.33it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.302190011028832
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round018_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2932 missing, 0 empty, 0 corrupted: 100%|██████████| 7817/7817 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:18:43.959421048 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:18:43.963534959 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2043       640  0.003491   0.04666  0.005195     4.428:   2%|▎         | 1/40 [00:21<14:12, 21.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1972       640  0.003437    0.0443  0.004677     4.193:   5%|▌         | 2/40 [00:22<06:01,  9.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1965       640  0.003421   0.04387  0.004525     4.145:   8%|▊         | 3/40 [00:23<03:25,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1820       640  0.003403    0.0428  0.004332     4.043:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003404   0.04196  0.004347     3.977:  12%|█▎        | 5/40 [00:25<01:31,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1835       640  0.003414   0.04107  0.004389      3.91:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1787       640  0.003432   0.04026  0.004367     3.845:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003429   0.03993  0.004323     3.814:  20%|██        | 8/40 [00:27<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003429   0.03998   0.00435      3.82:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003436   0.03958   0.00434     3.788:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640   0.00344   0.03934  0.004429     3.777:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003433   0.03915  0.004448     3.762:  30%|███       | 12/40 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003435   0.03903  0.004488     3.757:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2161       640  0.003442   0.03907  0.004476     3.759:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003442   0.03891  0.004483     3.747:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1721       640  0.003429   0.03841  0.004508     3.708:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003436   0.03826  0.004551       3.7:  42%|████▎     | 17/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1966       640  0.003428   0.03811  0.004539     3.686:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1489       640  0.003433   0.03768  0.004547     3.653:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003439   0.03763  0.004532     3.648:  50%|█████     | 20/40 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003443   0.03746  0.004541     3.635:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1838       640  0.003442    0.0373  0.004518     3.621:  55%|█████▌    | 22/40 [00:36<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640  0.003441   0.03719  0.004508     3.611:  57%|█████▊    | 23/40 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2212       640  0.003443   0.03724  0.004516     3.616:  60%|██████    | 24/40 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1932       640  0.003445   0.03719  0.004518     3.612:  62%|██████▎   | 25/40 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640  0.003444   0.03705  0.004514       3.6:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.545       0.42      0.411      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.563      0.407       0.41      0.231
                   0        738       1052      0.569      0.524      0.527      0.253
                   1        738         44      0.568      0.179      0.239      0.114
                   2        738       8622      0.694      0.721      0.747      0.478
                   3        738        151      0.512      0.411      0.425      0.324
                   4        738        467      0.484      0.589      0.539      0.378
                   5        738         70      0.341      0.386      0.286       0.15
                   6        738         65      0.239     0.0615      0.161     0.0622
                   7        738       1619      0.574      0.608      0.586      0.239
                   8        738       2845      0.647      0.594      0.594      0.316
                   9        738          2          1          0   0.000325   0.000293

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_client5_residential_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 18:20:10.973597763 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31266 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round018_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round018_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:20:27.052386123 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:20:27.055494435 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03084   0.03579  0.003695     5.626:   3%|▎         | 1/31 [00:32<16:25, 32.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03073   0.03522  0.003706     5.572:   6%|▋         | 2/31 [00:33<06:45, 13.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.03003   0.03385  0.003598     5.398:  10%|▉         | 3/31 [00:34<03:43,  7.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02951   0.03244  0.003388     5.227:  13%|█▎        | 4/31 [00:35<02:18,  5.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02941   0.03243  0.003392     5.219:  16%|█▌        | 5/31 [00:35<01:30,  3.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02948   0.03226  0.003415     5.213:  19%|█▉        | 6/31 [00:36<01:02,  2.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02954   0.03196  0.003468     5.198:  23%|██▎       | 7/31 [00:37<00:45,  1.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02944   0.03198  0.003469     5.191:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02951   0.03189  0.003393     5.184:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02952     0.032  0.003364     5.191:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02949     0.032  0.003383      5.19:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640    0.0294   0.03174  0.003376     5.161:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02936   0.03169  0.003329     5.151:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02939   0.03159  0.003304     5.143:  45%|████▌     | 14/31 [00:41<00:11,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02942    0.0315  0.003353     5.141:  48%|████▊     | 15/31 [00:41<00:10,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02943   0.03138  0.003355     5.133:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02946    0.0314  0.003334     5.135:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02954   0.03153  0.003308      5.15:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02952   0.03142  0.003288     5.138:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02953   0.03165  0.003286     5.157:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02958   0.03171  0.003306     5.168:  68%|██████▊   | 21/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02961   0.03183  0.003288     5.178:  71%|███████   | 22/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02963    0.0319  0.003265     5.183:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02967   0.03204  0.003258     5.197:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640    0.0297   0.03204  0.003265       5.2:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02978   0.03214  0.003273     5.216:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.532      0.421      0.407      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.05it/s]

                 all        738      14937      0.517      0.421      0.406      0.226
                   0        738       1052      0.502      0.535      0.516       0.25
                   1        738         44      0.385      0.159      0.202     0.0836
                   2        738       8622       0.67      0.732      0.746       0.48
                   3        738        151      0.422      0.444      0.431      0.325
                   4        738        467      0.478      0.589       0.53       0.37
                   5        738         70      0.315      0.414      0.315      0.142
                   6        738         65      0.249      0.123      0.162      0.064
                   7        738       1619      0.547      0.615      0.576      0.239
                   8        738       2845      0.602      0.601      0.579      0.305
                   9        738          2          1          0   0.000416   0.000375

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round018_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 18:22:07.503957417 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round019 phase_round=19 ===

02 head-to-full DQA:  56%|█████▋    | 18/32 [4:14:48<3:17:03, 844.51s/round, elapsed=4h14m48s, eta=3h18m11s, phase=phase1_head, round=18]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round019 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round019 client0_highway_day: pseudo scan 250/1500 images, kept 2371 boxes
round019 client0_highway_day: pseudo scan 500/1500 images, kept 4796 boxes
round019 client0_highway_day: pseudo scan 750/1500 images, kept 7138 boxes
round019 client0_highway_day: pseudo scan 1000/1500 images, kept 9519 boxes
round019 client0_highway_day: pseudo scan 1250/1500 images, kept 11850 boxes
round019 client0_highway_day: pseudo scan 1500/1500 images, kept 14249 boxes
{
  "round": "round019",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round018_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 11221,
  "boxes_per_kept_image": 7.530872483221477,
  "mean_conf": 0.825942004752684,
  "mean_stability": 0.9474542308338143,
  "mean_score": 0.785919673169197,
  "class_counts": {
    "0": 155,
    "2": 6413,
    "3": 123,
    "4": 569,
    "5": 6,
    "7": 567,
    "8": 3388
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_client0_highway_day_stable_boxes.csv"
}
round019 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round019 client1_highway_night: pseudo scan 250/1500 images, kept 1565 boxes
round019 client1_highway_night: pseudo scan 500/1500 images, kept 3238 boxes
round019 client1_highway_night: pseudo scan 750/1500 images, kept 4940 boxes
round019 client1_highway_night: pseudo scan 1000/1500 images, kept 6542 boxes
round019 client1_highway_night: pseudo scan 1250/1500 images, kept 8175 boxes
round019 client1_highway_night: pseudo scan 1500/1500 images, kept 9773 boxes
{
  "round": "round019",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round018_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1447,
  "pseudo_boxes_kept": 8121,
  "boxes_per_kept_image": 5.612301313061507,
  "mean_conf": 0.7409357068324643,
  "mean_stability": 0.9289093328482294,
  "mean_score": 0.6925269483279857,
  "class_counts": {
    "0": 67,
    "2": 4398,
    "3": 27,
    "4": 145,
    "5": 8,
    "7": 631,
    "8": 2845
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_client1_highway_night_stable_boxes.csv"
}
round019 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round019 client2_citystreet_day: pseudo scan 250/1500 images, kept 2694 boxes
round019 client2_citystreet_day: pseudo scan 500/1500 images, kept 5422 boxes
round019 client2_citystreet_day: pseudo scan 750/1500 images, kept 8160 boxes
round019 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10918 boxes
round019 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13626 boxes
round019 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16287 boxes
{
  "round": "round019",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round018_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13748,
  "boxes_per_kept_image": 9.189839572192513,
  "mean_conf": 0.825781820632966,
  "mean_stability": 0.9456632901346195,
  "mean_score": 0.7844399571395124,
  "class_counts": {
    "0": 1497,
    "2": 7330,
    "3": 203,
    "4": 595,
    "5": 65,
    "7": 1491,
    "8": 2567
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_client2_citystreet_day_stable_boxes.csv"
}
round019 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round019 client3_citystreet_night: pseudo scan 250/1500 images, kept 2298 boxes
round019 client3_citystreet_night: pseudo scan 500/1500 images, kept 4558 boxes
round019 client3_citystreet_night: pseudo scan 750/1500 images, kept 6802 boxes
round019 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8945 boxes
round019 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11319 boxes
round019 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13573 boxes
{
  "round": "round019",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round018_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1474,
  "pseudo_boxes_kept": 11568,
  "boxes_per_kept_image": 7.848032564450475,
  "mean_conf": 0.7355305609753147,
  "mean_stability": 0.924235391254082,
  "mean_score": 0.6844578236746858,
  "class_counts": {
    "0": 560,
    "2": 6108,
    "3": 64,
    "4": 151,
    "5": 37,
    "7": 2120,
    "8": 2528
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_client3_citystreet_night_stable_boxes.csv"
}
round019 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round019 client4_residential_day: pseudo scan 250/1500 images, kept 2577 boxes
round019 client4_residential_day: pseudo scan 500/1500 images, kept 5179 boxes
round019 client4_residential_day: pseudo scan 750/1500 images, kept 7729 boxes
round019 client4_residential_day: pseudo scan 1000/1500 images, kept 10198 boxes
round019 client4_residential_day: pseudo scan 1250/1500 images, kept 12711 boxes
round019 client4_residential_day: pseudo scan 1500/1500 images, kept 15170 boxes
{
  "round": "round019",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round018_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9954,
  "boxes_per_kept_image": 6.680536912751678,
  "mean_conf": 0.8575275388525891,
  "mean_stability": 0.9542943368972198,
  "mean_score": 0.821836776581775,
  "class_counts": {
    "0": 396,
    "2": 6827,
    "3": 66,
    "4": 316,
    "5": 45,
    "7": 543,
    "8": 1761
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_client4_residential_day_stable_boxes.csv"
}
round019 client5_residential_night: pseudo scan 1/1500 images, kept 8 boxes
round019 client5_residential_night: pseudo scan 250/1500 images, kept 2219 boxes
round019 client5_residential_night: pseudo scan 500/1500 images, kept 4418 boxes
round019 client5_residential_night: pseudo scan 750/1500 images, kept 6610 boxes
round019 client5_residential_night: pseudo scan 1000/1500 images, kept 8851 boxes
round019 client5_residential_night: pseudo scan 1250/1500 images, kept 11104 boxes
round019 client5_residential_night: pseudo scan 1500/1500 images, kept 13354 boxes
{
  "round": "round019",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round018_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1468,
  "pseudo_boxes_kept": 8359,
  "boxes_per_kept_image": 5.694141689373297,
  "mean_conf": 0.7993220261287313,
  "mean_stability": 0.9399664134040291,
  "mean_score": 0.7545386713157427,
  "class_counts": {
    "0": 129,
    "2": 6010,
    "3": 31,
    "4": 95,
    "5": 22,
    "7": 694,
    "8": 1378
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round019_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31267 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round019_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round019_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client0_highway_day_stable_train' images and labels...5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 11859.80it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:24:24.344636475 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:24:24.394525187 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1981       640  0.003501   0.04676  0.005365      4.45:   3%|▎         | 1/39 [00:22<13:59, 22.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2086       640  0.003457   0.04649  0.004634     4.366:   5%|▌         | 2/39 [00:22<05:56,  9.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1932       640  0.003451   0.04545  0.004716      4.29:   8%|▊         | 3/39 [00:23<03:22,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1760       640  0.003418   0.04467  0.004692     4.222:  10%|█         | 4/39 [00:24<02:10,  3.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1854       640  0.003415   0.04465  0.004733     4.224:  13%|█▎        | 5/39 [00:25<01:29,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1909       640  0.003412   0.04374  0.004629     4.142:  15%|█▌        | 6/39 [00:26<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2111       640  0.003414   0.04351  0.004538     4.117:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2103       640   0.00342   0.04364  0.004516     4.126:  21%|██        | 8/39 [00:27<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2076       640  0.003429   0.04384   0.00453     4.144:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1997       640  0.003444   0.04378  0.004554     4.142:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2008       640  0.003444    0.0435  0.004524     4.117:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1931       640  0.003448    0.0436  0.004609     4.132:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2193       640  0.003445   0.04352  0.004629     4.128:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2169       640  0.003446   0.04354  0.004576     4.125:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1849       640   0.00345   0.04328  0.004537     4.101:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1980       640   0.00345   0.04306  0.004516     4.082:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1886       640  0.003452   0.04298  0.004538     4.078:  44%|████▎     | 17/39 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2237       640  0.003452   0.04283  0.004494     4.062:  46%|████▌     | 18/39 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1753       640  0.003451   0.04253  0.004515      4.04:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2048       640  0.003444    0.0425  0.004488     4.034:  51%|█████▏    | 20/39 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2156       640  0.003448   0.04257  0.004474      4.04:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2087       640  0.003451   0.04253   0.00445     4.035:  56%|█████▋    | 22/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1974       640  0.003442   0.04239  0.004426      4.02:  59%|█████▉    | 23/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2266       640  0.003445   0.04252  0.004406     4.029:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2072       640  0.003443   0.04244  0.004422     4.024:  64%|██████▍   | 25/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1913       640  0.003445   0.04233  0.004405     4.015:  67%|██████▋   | 26/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.521      0.442      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.508      0.444      0.412      0.231
                   0        738       1052       0.45      0.574      0.532      0.256
                   1        738         44      0.456      0.267      0.217      0.099
                   2        738       8622      0.657      0.742      0.751      0.479
                   3        738        151      0.395      0.417      0.428      0.321
                   4        738        467      0.462      0.612       0.54      0.384
                   5        738         70      0.273      0.414      0.293      0.147
                   6        738         65      0.255      0.169      0.171     0.0708
                   7        738       1619      0.515      0.636      0.589      0.242
                   8        738       2845       0.62      0.607      0.595      0.313
                   9        738          2          1          0   0.000407   0.000366

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:25:48.709255067 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31268 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round019_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round019_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client1_highway_night_stable_train' images and labels...4895 found, 2880 missing, 0 empty, 0 corrupted: 100%|██████████| 7775/7775 [00:00<00:00, 13803.02it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.365132099351369
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2880 missing, 0 empty, 0 corrupted: 100%|██████████| 7775/7775 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:26:04.233806874 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:26:05.250120436 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2318       640  0.003558   0.04561  0.004369     4.283:   2%|▎         | 1/40 [00:21<14:02, 21.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003543    0.0433  0.005003     4.148:   5%|▌         | 2/40 [00:22<05:57,  9.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1608       640  0.003454   0.04188  0.004897     4.019:   8%|▊         | 3/40 [00:23<03:24,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003473   0.04065  0.004742     3.909:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2029       640  0.003478   0.04026  0.004656     3.871:  12%|█▎        | 5/40 [00:24<01:31,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1754       640  0.003485   0.03958   0.00462     3.815:  15%|█▌        | 6/40 [00:25<01:06,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003484   0.03926  0.004708     3.796:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2302       640  0.003483   0.03964  0.004668     3.823:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003485   0.03927  0.004669     3.794:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2164       640   0.00348    0.0394  0.004698     3.806:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2237       640  0.003486   0.03952  0.004661     3.813:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003489   0.03925  0.004736     3.798:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2097       640  0.003495   0.03918  0.004743     3.793:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003495   0.03891  0.004705     3.769:  35%|███▌      | 14/40 [00:30<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003488   0.03852  0.004678     3.735:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2038       640  0.003481   0.03841  0.004693     3.727:  40%|████      | 16/40 [00:31<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640   0.00348    0.0383   0.00469     3.717:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003478   0.03815  0.004706     3.707:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1497       640  0.003476   0.03764  0.004676     3.663:  48%|████▊     | 19/40 [00:33<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1866       640   0.00347   0.03746  0.004671     3.648:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640  0.003476   0.03737  0.004713     3.645:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003473   0.03717  0.004704     3.628:  55%|█████▌    | 22/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640   0.00347   0.03706  0.004686     3.617:  57%|█████▊    | 23/40 [00:36<00:10,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003466   0.03694  0.004709     3.609:  60%|██████    | 24/40 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003462    0.0369  0.004662     3.602:  62%|██████▎   | 25/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003462   0.03693  0.004638     3.602:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.556      0.416      0.413      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.562      0.409      0.412      0.231
                   0        738       1052      0.543      0.534      0.526      0.254
                   1        738         44      0.583      0.159      0.238      0.109
                   2        738       8622       0.68      0.728      0.748       0.48
                   3        738        151      0.473      0.411      0.423       0.32
                   4        738        467      0.481      0.581      0.538      0.381
                   5        738         70      0.404      0.398      0.286      0.139
                   6        738         65      0.269     0.0615      0.177     0.0706
                   7        738       1619      0.551       0.62      0.587      0.242
                   8        738       2845      0.637      0.596      0.592      0.309
                   9        738          2          1          0   0.000381   0.000343

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:27:28.766744084 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31269 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round019_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round019_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 14122.10it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:27:44.917260833 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:27:44.921463136 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003548   0.05392  0.004525     4.959:   3%|▎         | 1/39 [00:21<13:34, 21.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2187       640  0.003499   0.05266  0.004894     4.885:   5%|▌         | 2/39 [00:22<05:46,  9.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1974       640  0.003464   0.05149  0.004919      4.79:   8%|▊         | 3/39 [00:23<03:17,  5.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1957       640  0.003473   0.05029  0.004842     4.688:  10%|█         | 4/39 [00:24<02:08,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2145       640  0.003471   0.04962  0.004761     4.628:  13%|█▎        | 5/39 [00:24<01:27,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1780       640  0.003439   0.04842  0.004724     4.526:  15%|█▌        | 6/39 [00:25<01:03,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1960       640  0.003449   0.04803  0.004778       4.5:  18%|█▊        | 7/39 [00:26<00:48,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1897       640  0.003439   0.04756  0.004732     4.459:  21%|██        | 8/39 [00:26<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2025       640  0.003454   0.04748  0.004665     4.448:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003441   0.04714  0.004659     4.419:  26%|██▌       | 10/39 [00:27<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1991       640  0.003444   0.04697  0.004651     4.405:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1792       640  0.003449   0.04643  0.004663     4.364:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2094       640  0.003455   0.04622  0.004624     4.344:  33%|███▎      | 13/39 [00:29<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2134       640  0.003464   0.04618  0.004586     4.338:  36%|███▌      | 14/39 [00:30<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1930       640  0.003464   0.04596  0.004561     4.319:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1894       640  0.003455    0.0456  0.004552     4.289:  41%|████      | 16/39 [00:31<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1504       640  0.003447   0.04534  0.004581      4.27:  44%|████▎     | 17/39 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1920       640  0.003439   0.04523  0.004565     4.259:  46%|████▌     | 18/39 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1718       640   0.00344   0.04493  0.004548     4.234:  49%|████▊     | 19/39 [00:33<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2032       640  0.003435    0.0449  0.004541      4.23:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1849       640  0.003427   0.04471   0.00452     4.212:  54%|█████▍    | 21/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1707       640  0.003421    0.0446   0.00451     4.203:  56%|█████▋    | 22/39 [00:35<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1860       640  0.003414   0.04447  0.004509     4.192:  59%|█████▉    | 23/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1900       640   0.00341   0.04439  0.004498     4.184:  62%|██████▏   | 24/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1848       640  0.003406   0.04428  0.004497     4.174:  64%|██████▍   | 25/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2050       640    0.0034   0.04422  0.004481     4.168:  67%|██████▋   | 26/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.423      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.524      0.425      0.408       0.23
                   0        738       1052      0.606      0.516      0.528      0.251
                   1        738         44      0.476      0.227       0.21        0.1
                   2        738       8622      0.648      0.744      0.752      0.477
                   3        738        151      0.367       0.43      0.429      0.326
                   4        738        467      0.437      0.619      0.533      0.374
                   5        738         70      0.346        0.4       0.28      0.146
                   6        738         65      0.192     0.0769      0.178     0.0736
                   7        738       1619      0.552      0.621      0.577      0.238
                   8        738       2845      0.616      0.609      0.596      0.314
                   9        738          2          1          0   0.000301   0.000271

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:29:10.497266123 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31270 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round019_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round019_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client3_citystreet_night_stable_train' images and labels...4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<00:00, 19053.77it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:29:26.787695382 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:29:26.788392489 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1933       640  0.003561   0.04608  0.004496     4.331:   2%|▎         | 1/40 [00:21<13:59, 21.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003536    0.0446  0.004879     4.241:   5%|▌         | 2/40 [00:22<05:57,  9.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1984       640  0.003514   0.04478  0.004897     4.255:   8%|▊         | 3/40 [00:23<03:24,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640   0.00349   0.04389  0.004833     4.177:  10%|█         | 4/40 [00:24<02:12,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1833       640  0.003457   0.04286  0.004776     4.088:  12%|█▎        | 5/40 [00:24<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003463    0.0423  0.004691     4.036:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003469   0.04176  0.004641      3.99:  18%|█▊        | 7/40 [00:26<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2016       640  0.003471   0.04147  0.004639     3.967:  20%|██        | 8/40 [00:26<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640   0.00346   0.04108  0.004553     3.927:  22%|██▎       | 9/40 [00:27<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003473   0.04091  0.004516     3.912:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003462   0.04053  0.004442     3.875:  28%|██▊       | 11/40 [00:28<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1669       640  0.003453   0.04007  0.004485      3.84:  30%|███       | 12/40 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003448   0.03983  0.004489     3.821:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003449   0.03977   0.00449     3.817:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1771       640  0.003444    0.0395  0.004503     3.796:  38%|███▊      | 15/40 [00:31<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640  0.003437   0.03917  0.004447     3.764:  40%|████      | 16/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1607       640  0.003439   0.03876  0.004454     3.732:  42%|████▎     | 17/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003444   0.03859  0.004457     3.719:  45%|████▌     | 18/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1791       640  0.003442   0.03826  0.004435     3.691:  48%|████▊     | 19/40 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2210       640  0.003442   0.03826  0.004396     3.688:  50%|█████     | 20/40 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003448   0.03814  0.004406      3.68:  52%|█████▎    | 21/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1812       640  0.003448   0.03793  0.004371      3.66:  55%|█████▌    | 22/40 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640  0.003449    0.0379  0.004376     3.658:  57%|█████▊    | 23/40 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1804       640  0.003446   0.03772  0.004381     3.644:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003446   0.03766  0.004369     3.638:  62%|██████▎   | 25/40 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1815       640  0.003442   0.03752  0.004364     3.626:  65%|██████▌   | 26/40 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.573      0.397      0.408      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.561        0.4      0.407       0.23
                   0        738       1052      0.599      0.504      0.519      0.252
                   1        738         44      0.489      0.136      0.217     0.0986
                   2        738       8622      0.692      0.719      0.746      0.477
                   3        738        151      0.479      0.404      0.425      0.325
                   4        738        467      0.481        0.6      0.535      0.374
                   5        738         70        0.4      0.386      0.295       0.15
                   6        738         65      0.252     0.0615      0.167     0.0712
                   7        738       1619      0.566      0.607      0.581       0.24
                   8        738       2845      0.653       0.58       0.59      0.312
                   9        738          2          1          0   0.000345   0.000311

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:30:51.197069801 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31271 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round019_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round019_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client4_residential_day_stable_train' images and labels...5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 23613.81it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2662 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:31:08.250407028 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:31:08.258540036 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2155       640  0.003471   0.05262   0.00459     4.854:   3%|▎         | 1/39 [00:21<13:39, 21.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2131       640  0.003453   0.05126  0.005108     4.786:   5%|▌         | 2/39 [00:22<05:46,  9.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1790       640  0.003395   0.04968   0.00502     4.648:   8%|▊         | 3/39 [00:23<03:17,  5.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640   0.00338   0.04899  0.004912     4.583:  10%|█         | 4/39 [00:24<02:07,  3.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2100       640  0.003372   0.04792  0.004911     4.496:  13%|█▎        | 5/39 [00:24<01:27,  2.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1736       640  0.003367   0.04657  0.004975     4.393:  15%|█▌        | 6/39 [00:25<01:02,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2063       640  0.003387   0.04626   0.00493     4.366:  18%|█▊        | 7/39 [00:26<00:47,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2170       640    0.0034   0.04597  0.004822     4.335:  21%|██        | 8/39 [00:26<00:37,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003402   0.04601   0.00476     4.334:  23%|██▎       | 9/39 [00:27<00:31,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1862       640  0.003407   0.04583  0.004742     4.318:  26%|██▌       | 10/39 [00:27<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2172       640  0.003419   0.04575  0.004721     4.311:  28%|██▊       | 11/39 [00:28<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2180       640  0.003434   0.04556  0.004767     4.301:  31%|███       | 12/39 [00:29<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1972       640   0.00344   0.04543  0.004747     4.289:  33%|███▎      | 13/39 [00:29<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003444   0.04531  0.004745      4.28:  36%|███▌      | 14/39 [00:30<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003451    0.0451  0.004765     4.265:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640  0.003446   0.04474  0.004736     4.234:  41%|████      | 16/39 [00:31<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640  0.003443   0.04454  0.004699     4.215:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1938       640  0.003437   0.04446  0.004666     4.205:  46%|████▌     | 18/39 [00:32<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1729       640   0.00344   0.04411  0.004671     4.178:  49%|████▊     | 19/39 [00:33<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2036       640  0.003431   0.04404  0.004657      4.17:  51%|█████▏    | 20/39 [00:34<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003423   0.04389  0.004624     4.155:  54%|█████▍    | 21/39 [00:34<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003422   0.04378  0.004627     4.146:  56%|█████▋    | 22/39 [00:35<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003421   0.04372  0.004639     4.143:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003416   0.04356  0.004628     4.129:  62%|██████▏   | 24/39 [00:36<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003417   0.04344  0.004626     4.118:  64%|██████▍   | 25/39 [00:37<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640  0.003415    0.0433  0.004603     4.105:  67%|██████▋   | 26/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.562      0.413      0.411      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.548      0.414       0.41       0.23
                   0        738       1052      0.566      0.534      0.532      0.255
                   1        738         44      0.469      0.182      0.213     0.0975
                   2        738       8622       0.72      0.715      0.748      0.475
                   3        738        151      0.451       0.43      0.435      0.324
                   4        738        467      0.482      0.597      0.536      0.377
                   5        738         70      0.349      0.414       0.29      0.144
                   6        738         65      0.226     0.0674      0.168      0.071
                   7        738       1619      0.569       0.61      0.583       0.24
                   8        738       2845      0.653      0.594      0.593      0.316
                   9        738          2          1          0   0.000274   0.000246

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:32:33.735957794 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31272 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round019_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round019_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client5_residential_night_stable_train' images and labels...4885 found, 2932 missing, 0 empty, 0 corrupted: 100%|██████████| 7817/7817 [00:00<00:00, 12751.97it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.302190011028832
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round019_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2932 missing, 0 empty, 0 corrupted: 100%|██████████| 7817/7817 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:32:49.674536462 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:32:49.735744488 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1951       640  0.003469   0.04723  0.005168     4.469:   2%|▎         | 1/40 [00:21<14:04, 21.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1908       640  0.003437   0.04416  0.004655      4.18:   5%|▌         | 2/40 [00:22<05:57,  9.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1965       640  0.003392   0.04366  0.004511     4.125:   8%|▊         | 3/40 [00:23<03:23,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1965       640  0.003398   0.04301   0.00434      4.06:  10%|█         | 4/40 [00:24<02:12,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1878       640    0.0034   0.04198  0.004435     3.985:  12%|█▎        | 5/40 [00:24<01:30,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1837       640   0.00341   0.04118  0.004513     3.928:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1919       640  0.003435   0.04054  0.004499     3.878:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1847       640  0.003425   0.04003  0.004498     3.836:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003417   0.03984  0.004456     3.817:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003425   0.03955  0.004462     3.795:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2100       640  0.003433   0.03951   0.00453     3.798:  28%|██▊       | 11/40 [00:28<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1965       640   0.00343   0.03934   0.00451     3.783:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003427     0.039  0.004554     3.759:  32%|███▎      | 13/40 [00:30<00:20,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003432   0.03894  0.004508     3.751:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1898       640  0.003428   0.03866   0.00449     3.726:  38%|███▊      | 15/40 [00:31<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1767       640   0.00342   0.03823  0.004502     3.693:  40%|████      | 16/40 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1836       640  0.003431   0.03803  0.004557     3.682:  42%|████▎     | 17/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1924       640  0.003425   0.03786  0.004559     3.668:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1414       640  0.003431   0.03739  0.004582     3.632:  48%|████▊     | 19/40 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003434   0.03736  0.004579      3.63:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1867       640  0.003437    0.0372  0.004564     3.616:  52%|█████▎    | 21/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1796       640  0.003435   0.03702  0.004541       3.6:  55%|█████▌    | 22/40 [00:35<00:11,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003434   0.03692  0.004532     3.591:  57%|█████▊    | 23/40 [00:36<00:10,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2152       640  0.003437   0.03694  0.004532     3.592:  60%|██████    | 24/40 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2026       640   0.00344   0.03697  0.004548     3.596:  62%|██████▎   | 25/40 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1935       640  0.003437   0.03687  0.004539     3.588:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.552      0.417      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.541      0.419      0.407      0.231
                   0        738       1052      0.537      0.537      0.527      0.252
                   1        738         44      0.505      0.205      0.222      0.109
                   2        738       8622      0.675      0.727      0.747      0.477
                   3        738        151      0.472      0.411      0.426      0.324
                   4        738        467      0.466      0.604      0.538      0.379
                   5        738         70      0.294        0.4      0.285       0.15
                   6        738         65      0.272     0.0923      0.153     0.0659
                   7        738       1619      0.558      0.611      0.582      0.238
                   8        738       2845      0.629      0.604      0.592      0.315
                   9        738          2          1          0   0.000393   0.000354

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:34:12.114385137 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31273 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round019_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round019_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:34:30.360325945 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:34:30.500990340 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03088   0.03581  0.003678      5.63:   3%|▎         | 1/31 [00:32<16:11, 32.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03065   0.03497  0.003653     5.542:   6%|▋         | 2/31 [00:33<06:45, 13.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640    0.0299   0.03353  0.003547     5.358:  10%|▉         | 3/31 [00:34<03:42,  7.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02944   0.03221  0.003349       5.2:  13%|█▎        | 4/31 [00:35<02:18,  5.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640    0.0293   0.03215  0.003349     5.184:  16%|█▌        | 5/31 [00:35<01:30,  3.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02934   0.03194   0.00337     5.172:  19%|█▉        | 6/31 [00:36<01:02,  2.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02938   0.03161  0.003423     5.153:  23%|██▎       | 7/31 [00:36<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02926    0.0316  0.003423     5.143:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02931    0.0315  0.003348     5.133:  29%|██▉       | 9/31 [00:37<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02931   0.03159  0.003318     5.138:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02928   0.03159  0.003335     5.136:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02918   0.03132  0.003326     5.107:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02914   0.03126  0.003279     5.095:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02917   0.03115  0.003254     5.086:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02918   0.03105  0.003302     5.083:  48%|████▊     | 15/31 [00:41<00:11,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02919   0.03093  0.003304     5.074:  52%|█████▏    | 16/31 [00:42<00:10,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02921   0.03095  0.003283     5.076:  55%|█████▍    | 17/31 [00:42<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640    0.0293   0.03107  0.003258     5.091:  58%|█████▊    | 18/31 [00:43<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02928   0.03097  0.003239     5.079:  61%|██████▏   | 19/31 [00:43<00:07,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640    0.0293   0.03119  0.003237     5.098:  65%|██████▍   | 20/31 [00:44<00:06,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02935   0.03125  0.003257     5.109:  68%|██████▊   | 21/31 [00:45<00:06,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02939   0.03137  0.003239     5.119:  71%|███████   | 22/31 [00:45<00:05,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640    0.0294   0.03144  0.003215     5.124:  74%|███████▍  | 23/31 [00:46<00:04,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02944   0.03158  0.003208     5.138:  77%|███████▋  | 24/31 [00:46<00:04,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02948   0.03158  0.003213     5.142:  81%|████████  | 25/31 [00:47<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02956   0.03168  0.003221     5.157:  84%|████████▍ | 26/31 [00:48<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.541      0.419      0.408      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.528      0.418      0.405      0.225
                   0        738       1052      0.507      0.529      0.515      0.248
                   1        738         44       0.41      0.158      0.211     0.0865
                   2        738       8622      0.681      0.726      0.745       0.48
                   3        738        151      0.427      0.437      0.431      0.323
                   4        738        467      0.476      0.582      0.528      0.367
                   5        738         70      0.338      0.414      0.315      0.145
                   6        738         65       0.29      0.123      0.158     0.0638
                   7        738       1619      0.552      0.614      0.576      0.238
                   8        738       2845      0.601      0.596      0.575      0.302
                   9        738          2          1          0   0.000432   0.000388

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round019_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 18:36:08.208917785 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round020 phase_round=20 ===

02 head-to-full DQA:  59%|█████▉    | 19/32 [4:28:50<3:02:48, 843.71s/round, elapsed=4h28m50s, eta=3h03m56s, phase=phase1_head, round=19]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round020 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round020 client0_highway_day: pseudo scan 250/1500 images, kept 2378 boxes
round020 client0_highway_day: pseudo scan 500/1500 images, kept 4801 boxes
round020 client0_highway_day: pseudo scan 750/1500 images, kept 7140 boxes
round020 client0_highway_day: pseudo scan 1000/1500 images, kept 9518 boxes
round020 client0_highway_day: pseudo scan 1250/1500 images, kept 11857 boxes
round020 client0_highway_day: pseudo scan 1500/1500 images, kept 14258 boxes
{
  "round": "round020",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round019_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 11247,
  "boxes_per_kept_image": 7.543259557344064,
  "mean_conf": 0.8275120236867903,
  "mean_stability": 0.9467123146373834,
  "mean_score": 0.7868143818984608,
  "class_counts": {
    "0": 165,
    "2": 6417,
    "3": 122,
    "4": 569,
    "5": 5,
    "7": 558,
    "8": 3411
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_client0_highway_day_stable_boxes.csv"
}
round020 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round020 client1_highway_night: pseudo scan 250/1500 images, kept 1537 boxes
round020 client1_highway_night: pseudo scan 500/1500 images, kept 3201 boxes
round020 client1_highway_night: pseudo scan 750/1500 images, kept 4886 boxes
round020 client1_highway_night: pseudo scan 1000/1500 images, kept 6478 boxes
round020 client1_highway_night: pseudo scan 1250/1500 images, kept 8097 boxes
round020 client1_highway_night: pseudo scan 1500/1500 images, kept 9686 boxes
{
  "round": "round020",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round019_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1445,
  "pseudo_boxes_kept": 8111,
  "boxes_per_kept_image": 5.613148788927336,
  "mean_conf": 0.7407894555450353,
  "mean_stability": 0.9278280924242795,
  "mean_score": 0.6916728565491619,
  "class_counts": {
    "0": 65,
    "2": 4359,
    "3": 27,
    "4": 149,
    "5": 7,
    "7": 648,
    "8": 2856
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_client1_highway_night_stable_boxes.csv"
}
round020 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round020 client2_citystreet_day: pseudo scan 250/1500 images, kept 2697 boxes
round020 client2_citystreet_day: pseudo scan 500/1500 images, kept 5437 boxes
round020 client2_citystreet_day: pseudo scan 750/1500 images, kept 8171 boxes
round020 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10924 boxes
round020 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13633 boxes
round020 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16303 boxes
{
  "round": "round020",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round019_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13817,
  "boxes_per_kept_image": 9.23596256684492,
  "mean_conf": 0.8266972505991078,
  "mean_stability": 0.9450352858848265,
  "mean_score": 0.7847626007431466,
  "class_counts": {
    "0": 1499,
    "2": 7337,
    "3": 206,
    "4": 601,
    "5": 69,
    "7": 1506,
    "8": 2599
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_client2_citystreet_day_stable_boxes.csv"
}
round020 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round020 client3_citystreet_night: pseudo scan 250/1500 images, kept 2287 boxes
round020 client3_citystreet_night: pseudo scan 500/1500 images, kept 4541 boxes
round020 client3_citystreet_night: pseudo scan 750/1500 images, kept 6776 boxes
round020 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8906 boxes
round020 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11270 boxes
round020 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13514 boxes
{
  "round": "round020",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round019_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1475,
  "pseudo_boxes_kept": 11607,
  "boxes_per_kept_image": 7.869152542372881,
  "mean_conf": 0.7350305075268315,
  "mean_stability": 0.9228890764730747,
  "mean_score": 0.683016046340903,
  "class_counts": {
    "0": 563,
    "2": 6082,
    "3": 63,
    "4": 153,
    "5": 35,
    "7": 2154,
    "8": 2557
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_client3_citystreet_night_stable_boxes.csv"
}
round020 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round020 client4_residential_day: pseudo scan 250/1500 images, kept 2578 boxes
round020 client4_residential_day: pseudo scan 500/1500 images, kept 5173 boxes
round020 client4_residential_day: pseudo scan 750/1500 images, kept 7714 boxes
round020 client4_residential_day: pseudo scan 1000/1500 images, kept 10190 boxes
round020 client4_residential_day: pseudo scan 1250/1500 images, kept 12705 boxes
round020 client4_residential_day: pseudo scan 1500/1500 images, kept 15172 boxes
{
  "round": "round020",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round019_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 9989,
  "boxes_per_kept_image": 6.704026845637584,
  "mean_conf": 0.857871830809497,
  "mean_stability": 0.9535858660432142,
  "mean_score": 0.8216331663645563,
  "class_counts": {
    "0": 404,
    "2": 6828,
    "3": 67,
    "4": 321,
    "5": 44,
    "7": 540,
    "8": 1785
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_client4_residential_day_stable_boxes.csv"
}
round020 client5_residential_night: pseudo scan 1/1500 images, kept 8 boxes
round020 client5_residential_night: pseudo scan 250/1500 images, kept 2211 boxes
round020 client5_residential_night: pseudo scan 500/1500 images, kept 4375 boxes
round020 client5_residential_night: pseudo scan 750/1500 images, kept 6535 boxes
round020 client5_residential_night: pseudo scan 1000/1500 images, kept 8748 boxes
round020 client5_residential_night: pseudo scan 1250/1500 images, kept 10979 boxes
round020 client5_residential_night: pseudo scan 1500/1500 images, kept 13206 boxes
{
  "round": "round020",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round019_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1465,
  "pseudo_boxes_kept": 8306,
  "boxes_per_kept_image": 5.669624573378839,
  "mean_conf": 0.7991828186997672,
  "mean_stability": 0.9389251263463695,
  "mean_score": 0.7537352783293957,
  "class_counts": {
    "0": 131,
    "2": 5943,
    "3": 31,
    "4": 93,
    "5": 20,
    "7": 703,
    "8": 1385
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round020_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31274 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round020_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round020_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client0_highway_day_stable_train' images and labels...5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 17686.30it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:38:24.212634708 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:38:24.219868270 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2179       640  0.003675   0.05081  0.005144      4.77:   3%|▎         | 1/39 [00:21<13:42, 21.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1845       640  0.003547   0.04772  0.004652     4.474:   5%|▌         | 2/39 [00:22<05:49,  9.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1899       640  0.003556   0.04676   0.00477     4.407:   8%|▊         | 3/39 [00:23<03:18,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1842       640  0.003539    0.0461  0.004723     4.349:  10%|█         | 4/39 [00:24<02:08,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1938       640  0.003511   0.04607  0.004694     4.342:  13%|█▎        | 5/39 [00:24<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1733       640  0.003465   0.04455  0.004548     4.205:  15%|█▌        | 6/39 [00:25<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1943       640  0.003463   0.04412  0.004549      4.17:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2088       640  0.003475   0.04412  0.004692     4.183:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2233       640  0.003488   0.04447  0.004703     4.213:  23%|██▎       | 9/39 [00:27<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2070       640  0.003496    0.0445  0.004713     4.217:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2084       640  0.003495   0.04427  0.004697     4.197:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1981       640  0.003491   0.04437  0.004793     4.212:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1866       640  0.003479   0.04404  0.004776     4.183:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2227       640  0.003475   0.04399  0.004725     4.175:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1871       640  0.003478   0.04379  0.004688     4.156:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2019       640  0.003477   0.04353  0.004654     4.133:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1765       640  0.003477   0.04331  0.004692     4.118:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2089       640  0.003476    0.0431  0.004674       4.1:  46%|████▌     | 18/39 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1696       640  0.003468   0.04273  0.004656     4.068:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2177       640  0.003464   0.04266  0.004659     4.063:  51%|█████▏    | 20/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2058       640   0.00346   0.04267  0.004643     4.062:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1931       640   0.00346   0.04253  0.004635      4.05:  56%|█████▋    | 22/39 [00:35<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2055       640  0.003456    0.0424    0.0046     4.036:  59%|█████▉    | 23/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2016       640  0.003457   0.04241  0.004598     4.037:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2039       640  0.003454   0.04237  0.004598     4.034:  64%|██████▍   | 25/39 [00:37<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1953       640  0.003453   0.04232  0.004588     4.029:  67%|██████▋   | 26/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.608      0.389      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937        0.6       0.39       0.41       0.23
                   0        738       1052      0.567      0.527       0.53      0.254
                   1        738         44      0.543      0.136      0.219     0.0952
                   2        738       8622      0.753      0.707      0.751      0.478
                   3        738        151      0.639      0.391      0.423      0.322
                   4        738        467      0.525      0.544      0.536      0.382
                   5        738         70      0.389      0.386      0.285      0.145
                   6        738         65      0.299     0.0615      0.172      0.072
                   7        738       1619      0.591      0.591       0.59      0.243
                   8        738       2845      0.694      0.556      0.594      0.313
                   9        738          2          1          0   0.000438   0.000394

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:39:48.774174927 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31275 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round020_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round020_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client1_highway_night_stable_train' images and labels...:   0%|          | 0/7771 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client1_highway_night_stable_train' images and labels...4895 found, 2876 missing, 0 empty, 0 corrupted: 100%|██████████| 7771/7771 [00:00<00:00, 14000.01it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.369995252413357
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2876 missing, 0 empty, 0 corrupted: 100%|██████████| 7771/7771 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:40:04.764018514 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:40:04.871148374 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2165       640  0.003545   0.04404  0.004905     4.199:   2%|▎         | 1/40 [00:22<14:24, 22.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003468    0.0428  0.004593     4.069:   5%|▌         | 2/40 [00:23<06:08,  9.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1820       640  0.003481   0.04261  0.004557     4.051:   8%|▊         | 3/40 [00:23<03:29,  5.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640   0.00344   0.04085  0.004601     3.911:  10%|█         | 4/40 [00:24<02:15,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003437   0.04055  0.004524     3.881:  12%|█▎        | 5/40 [00:25<01:32,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640  0.003448   0.04002  0.004517     3.839:  15%|█▌        | 6/40 [00:26<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003463   0.04001  0.004663     3.851:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640  0.003466   0.04001  0.004596     3.846:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2085       640  0.003465   0.03979  0.004562     3.825:  22%|██▎       | 9/40 [00:28<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003464   0.03975  0.004608     3.826:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2033       640  0.003473   0.03957  0.004623     3.813:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1885       640  0.003475   0.03923  0.004595     3.784:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003464   0.03889  0.004601     3.756:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003466    0.0387  0.004551     3.737:  35%|███▌      | 14/40 [00:31<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1716       640  0.003458   0.03821  0.004533     3.696:  38%|███▊      | 15/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003462    0.0381  0.004581     3.692:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1750       640  0.003459   0.03787  0.004592     3.674:  42%|████▎     | 17/40 [00:33<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003463   0.03763  0.004611     3.656:  45%|████▌     | 18/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1627       640  0.003463   0.03721  0.004607     3.622:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1959       640  0.003457   0.03705  0.004596     3.609:  50%|█████     | 20/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003457    0.0369  0.004587     3.595:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640  0.003457   0.03672  0.004604     3.583:  55%|█████▌    | 22/40 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1907       640  0.003451    0.0366  0.004592     3.572:  57%|█████▊    | 23/40 [00:37<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2022       640  0.003454   0.03655  0.004644     3.572:  60%|██████    | 24/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1717       640  0.003452   0.03636  0.004642     3.556:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003451   0.03638  0.004644     3.558:  65%|██████▌   | 26/40 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.563      0.412      0.415      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.25it/s]

                 all        738      14937       0.55      0.414      0.411      0.231
                   0        738       1052      0.548      0.533      0.527      0.255
                   1        738         44      0.495      0.205      0.246      0.115
                   2        738       8622      0.699      0.723      0.749       0.48
                   3        738        151      0.496      0.404      0.424      0.322
                   4        738        467      0.475      0.595      0.534      0.379
                   5        738         70      0.348      0.412      0.286      0.146
                   6        738         65      0.234     0.0615      0.171     0.0679
                   7        738       1619      0.558      0.616      0.586       0.24
                   8        738       2845      0.649      0.587       0.59      0.308
                   9        738          2          1          0   0.000418   0.000376

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:41:29.075434890 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31276 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round020_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round020_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 10639.25it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:41:46.732362068 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:41:46.801747435 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2066       640  0.003556   0.05419  0.004596     4.987:   3%|▎         | 1/39 [00:22<14:00, 22.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2169       640  0.003502   0.05305  0.004936     4.919:   5%|▌         | 2/39 [00:23<05:57,  9.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1975       640  0.003467   0.05163  0.004937     4.803:   8%|▊         | 3/39 [00:23<03:24,  5.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1957       640  0.003477   0.05026  0.004858     4.688:  10%|█         | 4/39 [00:24<02:11,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2141       640  0.003475   0.04974  0.004777      4.64:  13%|█▎        | 5/39 [00:25<01:29,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1783       640  0.003446   0.04857  0.004749     4.541:  15%|█▌        | 6/39 [00:26<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1977       640  0.003455   0.04817  0.004797     4.514:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1897       640  0.003445    0.0477   0.00475     4.472:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2023       640  0.003458   0.04761  0.004672     4.459:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1832       640  0.003444   0.04726  0.004664      4.43:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1989       640  0.003448   0.04708  0.004662     4.415:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1803       640  0.003453   0.04656  0.004672     4.375:  31%|███       | 12/39 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2081       640  0.003459   0.04633  0.004631     4.353:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2115       640  0.003468   0.04634  0.004593     4.352:  36%|███▌      | 14/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1949       640  0.003469   0.04615  0.004568     4.335:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1922       640   0.00346   0.04582  0.004558     4.307:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1503       640  0.003451   0.04552  0.004586     4.285:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1948       640  0.003443    0.0454   0.00457     4.273:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1728       640  0.003445   0.04508  0.004552     4.246:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1998       640  0.003439   0.04504  0.004544     4.242:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1837       640  0.003431   0.04485  0.004522     4.224:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1717       640  0.003426   0.04475  0.004514     4.215:  56%|█████▋    | 22/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1826       640  0.003419    0.0446  0.004505     4.202:  59%|█████▉    | 23/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1890       640  0.003415   0.04453  0.004495     4.195:  62%|██████▏   | 24/39 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1811       640  0.003411    0.0444  0.004485     4.184:  64%|██████▍   | 25/39 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2050       640  0.003405   0.04434  0.004469     4.177:  67%|██████▋   | 26/39 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.521      0.435      0.408      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.528      0.421      0.407       0.23
                   0        738       1052      0.619      0.512      0.527      0.252
                   1        738         44      0.449      0.204      0.204     0.0943
                   2        738       8622      0.655      0.743      0.752      0.477
                   3        738        151      0.371       0.43      0.427      0.324
                   4        738        467      0.435      0.608       0.53      0.373
                   5        738         70      0.367      0.414      0.289      0.152
                   6        738         65      0.207     0.0769      0.171     0.0728
                   7        738       1619      0.556      0.613      0.577      0.237
                   8        738       2845      0.619      0.604      0.594      0.315
                   9        738          2          1          0   0.000308   0.000277

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:43:10.901848650 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31277 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round020_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round020_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client3_citystreet_night_stable_train' images and labels...4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<00:00, 11662.99it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.282926829268293
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2948 missing, 0 empty, 0 corrupted: 100%|██████████| 7831/7831 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:43:27.528510378 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:43:27.536697120 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2027       640  0.003614   0.04691  0.004626     4.412:   2%|▎         | 1/40 [00:22<14:21, 22.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1932       640  0.003658    0.0456  0.004904     4.333:   5%|▌         | 2/40 [00:22<06:04,  9.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2066       640  0.003622   0.04574  0.004762      4.33:   8%|▊         | 3/40 [00:23<03:26,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2004       640  0.003588   0.04469  0.004925     4.256:  10%|█         | 4/40 [00:24<02:14,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1797       640   0.00356   0.04338  0.004821     4.141:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1723       640  0.003532   0.04224   0.00472     4.039:  15%|█▌        | 6/40 [00:25<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2001       640  0.003534   0.04175  0.004608     3.992:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003525   0.04169  0.004645     3.989:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1972       640  0.003507   0.04144  0.004596     3.964:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1817       640  0.003505   0.04103  0.004572     3.928:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1918       640  0.003498   0.04067  0.004495     3.893:  28%|██▊       | 11/40 [00:29<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1734       640  0.003485   0.04012  0.004497     3.848:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003479   0.03981  0.004472     3.821:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1885       640  0.003477   0.03971  0.004498     3.815:  35%|███▌      | 14/40 [00:31<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1827       640  0.003468    0.0394  0.004487     3.788:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003468   0.03917  0.004478     3.769:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003471   0.03886  0.004503     3.747:  42%|████▎     | 17/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003473   0.03869  0.004526     3.735:  45%|████▌     | 18/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640   0.00347   0.03833  0.004521     3.706:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1927       640  0.003471   0.03824   0.00451     3.698:  50%|█████     | 20/40 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003471    0.0381  0.004501     3.685:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1742       640   0.00347    0.0379  0.004482     3.668:  55%|█████▌    | 22/40 [00:36<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2093       640  0.003468   0.03788  0.004481     3.666:  57%|█████▊    | 23/40 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003461   0.03768  0.004461     3.648:  60%|██████    | 24/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1664       640  0.003458   0.03741   0.00444     3.625:  62%|██████▎   | 25/40 [00:38<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003453   0.03738  0.004423      3.62:  65%|██████▌   | 26/40 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.583      0.396      0.406      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.573      0.397      0.405       0.23
                   0        738       1052      0.609      0.503      0.522      0.252
                   1        738         44      0.528      0.127      0.213      0.102
                   2        738       8622      0.709      0.712      0.746      0.477
                   3        738        151      0.525      0.411      0.426      0.324
                   4        738        467      0.476      0.593      0.532      0.373
                   5        738         70      0.403      0.386      0.276      0.147
                   6        738         65      0.249     0.0615      0.169     0.0672
                   7        738       1619      0.571      0.599      0.577       0.24
                   8        738       2845       0.66      0.575       0.59      0.312
                   9        738          2          1          0   0.000366   0.000329

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:44:53.904965734 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31278 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round020_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round020_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client4_residential_day_stable_train' images and labels...5201 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 15458.57it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client4_residential_day_stable_train.cache' images and labels... 5201 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:45:10.352366511 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:45:10.364518740 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1950       640   0.00352   0.05472  0.004686     5.034:   3%|▎         | 1/39 [00:21<13:53, 21.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003509   0.05259  0.004902      4.88:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640   0.00348   0.05075  0.004922     4.732:   8%|▊         | 3/39 [00:23<03:21,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003496   0.04963  0.004799     4.634:  10%|█         | 4/39 [00:24<02:10,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2216       640  0.003495   0.04899   0.00473     4.577:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003471   0.04782  0.004713     4.481:  15%|█▌        | 6/39 [00:25<01:04,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2137       640  0.003485   0.04747  0.004727     4.454:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003486   0.04686  0.004662     4.401:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640   0.00348   0.04688  0.004601     4.397:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003471   0.04655  0.004616     4.371:  26%|██▌       | 10/39 [00:28<00:26,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003469   0.04608   0.00458      4.33:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003474   0.04573    0.0046     4.304:  31%|███       | 12/39 [00:29<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640   0.00348   0.04544  0.004553     4.278:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640   0.00348   0.04524  0.004552     4.262:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640   0.00348   0.04496  0.004538     4.238:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003477   0.04464  0.004538     4.213:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003481   0.04443  0.004572     4.199:  44%|████▎     | 17/39 [00:32<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003472   0.04435  0.004541     4.189:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003471   0.04409  0.004544     4.169:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640   0.00346   0.04395  0.004539     4.156:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640   0.00345   0.04377  0.004504     4.138:  54%|█████▍    | 21/39 [00:35<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003452   0.04373  0.004489     4.134:  56%|█████▋    | 22/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003442   0.04366  0.004482     4.127:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003433   0.04356  0.004486     4.119:  62%|██████▏   | 24/39 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003429   0.04341  0.004473     4.105:  64%|██████▍   | 25/39 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003424   0.04337  0.004464       4.1:  67%|██████▋   | 26/39 [00:38<00:08,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.422       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.522      0.424       0.41      0.231
                   0        738       1052       0.53      0.539      0.529      0.254
                   1        738         44      0.499      0.227      0.216      0.102
                   2        738       8622      0.688      0.725      0.748      0.475
                   3        738        151      0.385      0.422      0.436      0.328
                   4        738        467      0.447      0.617      0.534      0.376
                   5        738         70      0.333      0.406      0.292      0.147
                   6        738         65      0.191     0.0769      0.171     0.0711
                   7        738       1619      0.542      0.614      0.578       0.24
                   8        738       2845      0.611      0.607      0.592      0.315
                   9        738          2          1          0   0.000273   0.000246

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:46:35.355355953 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31279 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round020_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round020_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client5_residential_night_stable_train' images and labels...4885 found, 2926 missing, 0 empty, 0 corrupted: 100%|██████████| 7811/7811 [00:00<00:00, 13183.35it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.309426229508198
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round020_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2926 missing, 0 empty, 0 corrupted: 100%|██████████| 7811/7811 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:46:51.978189925 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:46:51.983187617 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1915       640  0.003529   0.04651  0.005116     4.412:   2%|▎         | 1/40 [00:21<14:04, 21.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1987       640  0.003475   0.04449  0.004768     4.219:   5%|▌         | 2/40 [00:22<05:58,  9.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003458   0.04386  0.004379     4.136:   8%|▊         | 3/40 [00:23<03:23,  5.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003428   0.04271   0.00432     4.037:  10%|█         | 4/40 [00:24<02:11,  3.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1837       640  0.003416   0.04181  0.004313     3.963:  12%|█▎        | 5/40 [00:24<01:30,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1847       640   0.00344   0.04099  0.004259     3.895:  15%|█▌        | 6/40 [00:25<01:05,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003451   0.04004   0.00437     3.828:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1806       640  0.003437    0.0397  0.004299     3.795:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003446   0.03972  0.004321     3.799:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003442    0.0392  0.004336     3.758:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640   0.00345   0.03906  0.004378     3.751:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003443   0.03867  0.004413     3.722:  30%|███       | 12/40 [00:29<00:21,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1978       640  0.003455    0.0385   0.00443     3.711:  32%|███▎      | 13/40 [00:29<00:19,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2079       640   0.00346   0.03854   0.00448     3.718:  35%|███▌      | 14/40 [00:30<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1747       640   0.00345   0.03812  0.004487     3.685:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1878       640  0.003447   0.03792  0.004504      3.67:  40%|████      | 16/40 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1922       640  0.003449   0.03779  0.004545     3.663:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003445   0.03756  0.004527     3.643:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1627       640  0.003445   0.03719  0.004509     3.611:  48%|████▊     | 19/40 [00:33<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1862       640  0.003454   0.03711  0.004488     3.604:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1822       640  0.003454   0.03696  0.004492     3.593:  52%|█████▎    | 21/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1626       640  0.003447   0.03669  0.004479     3.569:  55%|█████▌    | 22/40 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1978       640  0.003448   0.03668  0.004493      3.57:  57%|█████▊    | 23/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003449   0.03664  0.004499     3.567:  60%|██████    | 24/40 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1855       640   0.00345    0.0365  0.004522     3.557:  62%|██████▎   | 25/40 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1708       640  0.003447   0.03632  0.004531     3.544:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.569      0.405      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.22it/s]

                 all        738      14937      0.558      0.406      0.409       0.23
                   0        738       1052      0.561      0.525      0.524      0.252
                   1        738         44      0.525      0.201      0.239       0.11
                   2        738       8622      0.698      0.715      0.743      0.475
                   3        738        151      0.513      0.377      0.425      0.322
                   4        738        467      0.488      0.587      0.538      0.377
                   5        738         70      0.344        0.4      0.288       0.15
                   6        738         65      0.227     0.0615      0.158     0.0625
                   7        738       1619      0.575      0.605      0.585       0.24
                   8        738       2845      0.652      0.587      0.592      0.312
                   9        738          2          1          0   0.000363   0.000327

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:48:16.125437655 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31280 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round020_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round020_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:48:33.369149363 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:48:33.687762238 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03092   0.03586  0.003671     5.636:   3%|▎         | 1/31 [00:32<16:21, 32.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03056   0.03475  0.003602     5.513:   6%|▋         | 2/31 [00:33<06:43, 13.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02976   0.03325  0.003493      5.32:  10%|▉         | 3/31 [00:34<03:42,  7.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02935   0.03201  0.003305     5.173:  13%|█▎        | 4/31 [00:35<02:17,  5.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02918   0.03187  0.003299     5.148:  16%|█▌        | 5/31 [00:35<01:30,  3.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02921   0.03162   0.00332     5.131:  19%|█▉        | 6/31 [00:36<01:02,  2.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02924   0.03127  0.003373      5.11:  23%|██▎       | 7/31 [00:36<00:44,  1.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02912   0.03124  0.003372     5.099:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02917   0.03113  0.003297     5.088:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02917   0.03121  0.003267     5.092:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02913    0.0312  0.003282     5.089:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02903   0.03092  0.003272     5.058:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02899   0.03086  0.003226     5.046:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02901   0.03074  0.003201     5.036:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02902   0.03064  0.003249     5.033:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02903   0.03051  0.003252     5.024:  52%|█████▏    | 16/31 [00:42<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02906   0.03053   0.00323     5.025:  55%|█████▍    | 17/31 [00:42<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02914   0.03065  0.003205      5.04:  58%|█████▊    | 18/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02913   0.03055  0.003188     5.029:  61%|██████▏   | 19/31 [00:43<00:07,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02915   0.03077  0.003185     5.048:  65%|██████▍   | 20/31 [00:44<00:06,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02921   0.03083  0.003206     5.059:  68%|██████▊   | 21/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02924   0.03094  0.003189      5.07:  71%|███████   | 22/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02925   0.03101  0.003165     5.074:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02929   0.03115  0.003158     5.088:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02932   0.03116  0.003162     5.091:  81%|████████  | 25/31 [00:47<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02941   0.03126   0.00317     5.107:  84%|████████▍ | 26/31 [00:47<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.537      0.418      0.406      0.224
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.05it/s]

                 all        738      14937      0.522       0.42      0.405      0.225
                   0        738       1052      0.503      0.529      0.512      0.247
                   1        738         44      0.408      0.173      0.207     0.0879
                   2        738       8622      0.676      0.729      0.744      0.479
                   3        738        151      0.425       0.43      0.435      0.325
                   4        738        467      0.479      0.593      0.529       0.37
                   5        738         70      0.323      0.414      0.315      0.136
                   6        738         65      0.258      0.123      0.161     0.0632
                   7        738       1619      0.552      0.612      0.573      0.237
                   8        738       2845      0.601      0.594      0.571        0.3
                   9        738          2          1          0   0.000446   0.000402

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round020_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 18:50:13.739823757 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round021 phase_round=21 ===

02 head-to-full DQA:  62%|██████▎   | 20/32 [4:42:55<2:48:47, 843.98s/round, elapsed=4h42m55s, eta=2h49m45s, phase=phase1_head, round=20]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round021 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round021 client0_highway_day: pseudo scan 250/1500 images, kept 2376 boxes
round021 client0_highway_day: pseudo scan 500/1500 images, kept 4806 boxes
round021 client0_highway_day: pseudo scan 750/1500 images, kept 7143 boxes
round021 client0_highway_day: pseudo scan 1000/1500 images, kept 9514 boxes
round021 client0_highway_day: pseudo scan 1250/1500 images, kept 11846 boxes
round021 client0_highway_day: pseudo scan 1500/1500 images, kept 14235 boxes
{
  "round": "round021",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round020_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1489,
  "pseudo_boxes_kept": 11212,
  "boxes_per_kept_image": 7.529885829415715,
  "mean_conf": 0.830369477330724,
  "mean_stability": 0.9462291848604227,
  "mean_score": 0.7891385507767233,
  "class_counts": {
    "0": 154,
    "2": 6406,
    "3": 121,
    "4": 567,
    "5": 5,
    "7": 565,
    "8": 3394
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_client0_highway_day_stable_boxes.csv"
}
round021 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round021 client1_highway_night: pseudo scan 250/1500 images, kept 1541 boxes
round021 client1_highway_night: pseudo scan 500/1500 images, kept 3190 boxes
round021 client1_highway_night: pseudo scan 750/1500 images, kept 4864 boxes
round021 client1_highway_night: pseudo scan 1000/1500 images, kept 6455 boxes
round021 client1_highway_night: pseudo scan 1250/1500 images, kept 8059 boxes
round021 client1_highway_night: pseudo scan 1500/1500 images, kept 9647 boxes
{
  "round": "round021",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round020_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1442,
  "pseudo_boxes_kept": 8015,
  "boxes_per_kept_image": 5.558252427184466,
  "mean_conf": 0.7466666550132087,
  "mean_stability": 0.9267268138309604,
  "mean_score": 0.6962934728176566,
  "class_counts": {
    "0": 64,
    "2": 4342,
    "3": 26,
    "4": 145,
    "5": 7,
    "7": 633,
    "8": 2798
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_client1_highway_night_stable_boxes.csv"
}
round021 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round021 client2_citystreet_day: pseudo scan 250/1500 images, kept 2693 boxes
round021 client2_citystreet_day: pseudo scan 500/1500 images, kept 5426 boxes
round021 client2_citystreet_day: pseudo scan 750/1500 images, kept 8156 boxes
round021 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10906 boxes
round021 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13611 boxes
round021 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16272 boxes
{
  "round": "round021",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round020_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13753,
  "boxes_per_kept_image": 9.19933110367893,
  "mean_conf": 0.8302127221974513,
  "mean_stability": 0.9442311004015487,
  "mean_score": 0.7874617512069568,
  "class_counts": {
    "0": 1501,
    "2": 7323,
    "3": 205,
    "4": 594,
    "5": 68,
    "7": 1486,
    "8": 2576
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_client2_citystreet_day_stable_boxes.csv"
}
round021 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round021 client3_citystreet_night: pseudo scan 250/1500 images, kept 2269 boxes
round021 client3_citystreet_night: pseudo scan 500/1500 images, kept 4508 boxes
round021 client3_citystreet_night: pseudo scan 750/1500 images, kept 6728 boxes
round021 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8848 boxes
round021 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11190 boxes
round021 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13412 boxes
{
  "round": "round021",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round020_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1474,
  "pseudo_boxes_kept": 11434,
  "boxes_per_kept_image": 7.757123473541384,
  "mean_conf": 0.7405126669856454,
  "mean_stability": 0.9223208503381594,
  "mean_score": 0.687633737003356,
  "class_counts": {
    "0": 550,
    "2": 6036,
    "3": 62,
    "4": 152,
    "5": 34,
    "7": 2101,
    "8": 2499
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_client3_citystreet_night_stable_boxes.csv"
}
round021 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round021 client4_residential_day: pseudo scan 250/1500 images, kept 2575 boxes
round021 client4_residential_day: pseudo scan 500/1500 images, kept 5174 boxes
round021 client4_residential_day: pseudo scan 750/1500 images, kept 7724 boxes
round021 client4_residential_day: pseudo scan 1000/1500 images, kept 10186 boxes
round021 client4_residential_day: pseudo scan 1250/1500 images, kept 12701 boxes
round021 client4_residential_day: pseudo scan 1500/1500 images, kept 15160 boxes
{
  "round": "round021",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round020_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1489,
  "pseudo_boxes_kept": 9952,
  "boxes_per_kept_image": 6.683680322364003,
  "mean_conf": 0.8608156758183882,
  "mean_stability": 0.9533147103066325,
  "mean_score": 0.8241001978242934,
  "class_counts": {
    "0": 403,
    "2": 6822,
    "3": 68,
    "4": 320,
    "5": 47,
    "7": 524,
    "8": 1768
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_client4_residential_day_stable_boxes.csv"
}
round021 client5_residential_night: pseudo scan 1/1500 images, kept 8 boxes
round021 client5_residential_night: pseudo scan 250/1500 images, kept 2195 boxes
round021 client5_residential_night: pseudo scan 500/1500 images, kept 4349 boxes
round021 client5_residential_night: pseudo scan 750/1500 images, kept 6509 boxes
round021 client5_residential_night: pseudo scan 1000/1500 images, kept 8720 boxes
round021 client5_residential_night: pseudo scan 1250/1500 images, kept 10944 boxes
round021 client5_residential_night: pseudo scan 1500/1500 images, kept 13149 boxes
{
  "round": "round021",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round020_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1465,
  "pseudo_boxes_kept": 8227,
  "boxes_per_kept_image": 5.615699658703072,
  "mean_conf": 0.8020709759883028,
  "mean_stability": 0.9380170606430817,
  "mean_score": 0.7556162665469316,
  "class_counts": {
    "0": 124,
    "2": 5918,
    "3": 33,
    "4": 91,
    "5": 22,
    "7": 686,
    "8": 1353
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round021_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31281 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round021_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round021_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7859 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client0_highway_day_stable_train' images and labels...5359 found, 2500 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<00:00, 16512.87it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.841298320013049
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2500 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:52:30.884568706 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:52:30.940648476 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2117       640  0.003518   0.04761  0.005411     4.523:   3%|▎         | 1/39 [00:21<13:48, 21.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003585   0.04971  0.005202      4.68:   5%|▌         | 2/39 [00:22<05:52,  9.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2059       640  0.003555   0.04757  0.005208     4.507:   8%|▊         | 3/39 [00:23<03:20,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1831       640  0.003526   0.04679  0.005011     4.426:  10%|█         | 4/39 [00:24<02:09,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003529   0.04667  0.004959     4.413:  13%|█▎        | 5/39 [00:25<01:28,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003501   0.04529  0.004877     4.294:  15%|█▌        | 6/39 [00:25<01:03,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003477   0.04458  0.004839     4.232:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003475   0.04492  0.004853      4.26:  21%|██        | 8/39 [00:26<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2193       640  0.003476   0.04509   0.00478     4.268:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1987       640  0.003476     0.045  0.004788     4.261:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003471   0.04479   0.00476     4.241:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003462   0.04466  0.004841     4.237:  31%|███       | 12/39 [00:29<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2069       640  0.003461   0.04451  0.004853     4.226:  33%|███▎      | 13/39 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2148       640   0.00346   0.04429  0.004787     4.203:  36%|███▌      | 14/39 [00:30<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1828       640  0.003458   0.04396  0.004756     4.174:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003455    0.0437  0.004761     4.153:  41%|████      | 16/39 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640   0.00346   0.04357  0.004728     4.141:  44%|████▎     | 17/39 [00:32<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2299       640  0.003464   0.04345  0.004697     4.129:  46%|████▌     | 18/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1615       640  0.003463   0.04311  0.004709     4.102:  49%|████▊     | 19/39 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2231       640  0.003459   0.04312  0.004685     4.101:  51%|█████▏    | 20/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1976       640  0.003459   0.04307  0.004686     4.097:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003464   0.04299  0.004699     4.092:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2007       640  0.003459   0.04292  0.004668     4.084:  59%|█████▉    | 23/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2127       640  0.003459    0.0429  0.004645      4.08:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1966       640  0.003457    0.0428  0.004651     4.072:  64%|██████▍   | 25/39 [00:37<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2069       640  0.003459   0.04279  0.004656     4.072:  67%|██████▋   | 26/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.522       0.44      0.412      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.509      0.443      0.411      0.231
                   0        738       1052      0.463      0.568      0.532      0.257
                   1        738         44      0.438      0.273      0.218        0.1
                   2        738       8622      0.654      0.743      0.752      0.479
                   3        738        151      0.422      0.424       0.43      0.322
                   4        738        467       0.47      0.593      0.535      0.379
                   5        738         70      0.252      0.414      0.291      0.147
                   6        738         65      0.253      0.167      0.174     0.0741
                   7        738       1619      0.519      0.634      0.585      0.241
                   8        738       2845       0.62      0.612      0.594      0.314
                   9        738          2          1          0   0.000434   0.000391

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:53:55.575808678 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31282 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round021_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round021_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client1_highway_night_stable_train' images and labels...4895 found, 2870 missing, 0 empty, 0 corrupted: 100%|██████████| 7765/7765 [00:00<00:00, 10659.98it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.377295756808106
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2870 missing, 0 empty, 0 corrupted: 100%|██████████| 7765/7765 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:54:11.021518953 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:54:11.056008800 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      2133       640  0.003308   0.04337  0.004372     4.084:   2%|▎         | 1/40 [00:22<14:30, 22.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003396   0.04202  0.004627     4.004:   5%|▌         | 2/40 [00:23<06:08,  9.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003427   0.04167  0.004782      3.99:   8%|▊         | 3/40 [00:24<03:28,  5.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1908       640  0.003389   0.04079  0.004623     3.904:  10%|█         | 4/40 [00:24<02:14,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003386   0.04001  0.004575     3.838:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1647       640  0.003385   0.03869  0.004739     3.745:  15%|█▌        | 6/40 [00:26<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003375     0.039  0.004854     3.778:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2150       640  0.003382   0.03932  0.004788     3.799:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2106       640  0.003394   0.03943  0.004703     3.802:  22%|██▎       | 9/40 [00:28<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1862       640  0.003413   0.03924   0.00474     3.792:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2208       640  0.003426   0.03938   0.00473     3.803:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003444   0.03909   0.00478     3.786:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1987       640  0.003446   0.03868  0.004749      3.75:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2011       640  0.003445   0.03848  0.004693     3.729:  35%|███▌      | 14/40 [00:31<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640   0.00344    0.0382  0.004693     3.707:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003447   0.03802  0.004664      3.69:  40%|████      | 16/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1867       640  0.003454   0.03783  0.004683     3.678:  42%|████▎     | 17/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2068       640  0.003459   0.03785  0.004708     3.681:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1671       640  0.003467   0.03748  0.004697     3.652:  48%|████▊     | 19/40 [00:34<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2182       640  0.003463   0.03751  0.004693     3.653:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1828       640  0.003462   0.03725  0.004678     3.631:  52%|█████▎    | 21/40 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1714       640  0.003454   0.03702  0.004654      3.61:  55%|█████▌    | 22/40 [00:36<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1819       640  0.003453   0.03691  0.004608     3.598:  57%|█████▊    | 23/40 [00:36<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003445    0.0368  0.004597     3.587:  60%|██████    | 24/40 [00:37<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2003       640   0.00345   0.03676   0.00462     3.587:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003442   0.03655  0.004598     3.567:  65%|██████▌   | 26/40 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.596      0.401      0.414      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.586      0.402      0.412      0.231
                   0        738       1052      0.563      0.529      0.527      0.254
                   1        738         44      0.613       0.18       0.25      0.109
                   2        738       8622      0.729      0.708      0.748      0.478
                   3        738        151      0.547      0.416       0.43      0.329
                   4        738        467      0.492      0.567      0.532      0.377
                   5        738         70      0.403        0.4      0.289      0.142
                   6        738         65      0.247     0.0615      0.166     0.0695
                   7        738       1619      0.583        0.6       0.59      0.243
                   8        738       2845      0.685      0.559      0.588       0.31
                   9        738          2          1          0   0.000441   0.000397

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client1_highway_night

1 epochs completed in 0.023 hours.
Destroying process group...
[rank0]:[W507 18:55:34.693393877 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31283 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round021_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round021_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client2_citystreet_day_stable_train' images and labels...:   0%|          | 0/7871 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client2_citystreet_day_stable_train' images and labels...5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 11397.65it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:55:51.933562676 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:55:51.935727749 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1949       640  0.003444   0.05458  0.004565     5.007:   3%|▎         | 1/39 [00:21<13:48, 21.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003463   0.05505  0.004669     5.055:   5%|▌         | 2/39 [00:22<05:52,  9.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003438   0.05282  0.004584     4.867:   8%|▊         | 3/39 [00:23<03:19,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003433    0.0511  0.004651     4.734:  10%|█         | 4/39 [00:24<02:09,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2180       640  0.003434   0.05043  0.004556     4.674:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1564       640  0.003413   0.04847  0.004504     4.511:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003442   0.04833  0.004643     4.513:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003431   0.04771  0.004612     4.461:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003441    0.0478  0.004529     4.461:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003429   0.04731   0.00451      4.42:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003436   0.04708  0.004531     4.404:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003441   0.04665   0.00458     4.374:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003451   0.04667   0.00455     4.373:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640   0.00346   0.04654  0.004514     4.361:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003463   0.04639  0.004526      4.35:  38%|███▊      | 15/39 [00:31<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003467   0.04617  0.004526     4.333:  41%|████      | 16/39 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003468   0.04609  0.004527     4.327:  44%|████▎     | 17/39 [00:32<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003461     0.046  0.004495     4.317:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640  0.003459   0.04571  0.004459      4.29:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003458    0.0457  0.004471     4.291:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640   0.00345   0.04557  0.004436     4.276:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003446   0.04561  0.004421     4.278:  56%|█████▋    | 22/39 [00:35<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003445   0.04549  0.004433     4.269:  59%|█████▉    | 23/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003444   0.04551  0.004413     4.269:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2034       640  0.003442   0.04544  0.004399     4.263:  64%|██████▍   | 25/39 [00:37<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003442   0.04535  0.004415     4.257:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.543      0.415      0.409      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.532      0.418      0.408       0.23
                   0        738       1052      0.616      0.504      0.522      0.252
                   1        738         44      0.404       0.17      0.215        0.1
                   2        738       8622      0.655      0.741      0.751      0.477
                   3        738        151      0.417      0.417      0.429      0.321
                   4        738        467      0.447      0.615      0.527      0.372
                   5        738         70      0.368      0.429      0.292      0.151
                   6        738         65       0.23     0.0769      0.167     0.0709
                   7        738       1619      0.558       0.62      0.578      0.238
                   8        738       2845      0.619      0.609      0.594      0.314
                   9        738          2          1          0   0.000289    0.00026

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:57:18.347973276 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31284 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round021_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round021_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client3_citystreet_night_stable_train' images and labels...4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<00:00, 12076.42it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 18:57:34.689562254 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 18:57:34.697498920 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1937       640  0.003565    0.0463  0.004468     4.346:   2%|▎         | 1/40 [00:23<14:57, 23.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003555   0.04419  0.004798     4.203:   5%|▌         | 2/40 [00:23<06:20, 10.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003526   0.04464  0.004761     4.234:   8%|▊         | 3/40 [00:24<03:36,  5.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003516   0.04405  0.004715     4.183:  10%|█         | 4/40 [00:25<02:19,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1825       640  0.003484   0.04311   0.00465     4.099:  12%|█▎        | 5/40 [00:26<01:35,  2.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1800       640  0.003487   0.04235  0.004586     4.034:  15%|█▌        | 6/40 [00:26<01:08,  2.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003491   0.04171  0.004542      3.98:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003489   0.04151  0.004542     3.963:  20%|██        | 8/40 [00:28<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640   0.00348   0.04114   0.00447     3.928:  22%|██▎       | 9/40 [00:28<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003493   0.04103  0.004443     3.917:  25%|██▌       | 10/40 [00:29<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640   0.00348   0.04058  0.004387     3.876:  28%|██▊       | 11/40 [00:30<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1600       640  0.003471   0.04002  0.004439     3.834:  30%|███       | 12/40 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2051       640  0.003469   0.03973  0.004443     3.811:  32%|███▎      | 13/40 [00:31<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640   0.00347   0.03974  0.004443     3.812:  35%|███▌      | 14/40 [00:32<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003464   0.03942  0.004457     3.787:  38%|███▊      | 15/40 [00:32<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1880       640  0.003454   0.03905  0.004397     3.752:  40%|████      | 16/40 [00:33<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1611       640  0.003456   0.03862  0.004412     3.719:  42%|████▎     | 17/40 [00:33<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003459   0.03841  0.004417     3.703:  45%|████▌     | 18/40 [00:34<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003458   0.03807  0.004397     3.674:  48%|████▊     | 19/40 [00:35<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2257       640  0.003457   0.03809  0.004357     3.672:  50%|█████     | 20/40 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1806       640  0.003462   0.03793  0.004375     3.662:  52%|█████▎    | 21/40 [00:36<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1705       640  0.003458   0.03771  0.004349     3.641:  55%|█████▌    | 22/40 [00:37<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2191       640  0.003458   0.03772  0.004352     3.642:  57%|█████▊    | 23/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003454   0.03758   0.00436     3.632:  60%|██████    | 24/40 [00:38<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003455   0.03746  0.004347     3.621:  62%|██████▎   | 25/40 [00:39<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003452   0.03734  0.004344     3.611:  65%|██████▌   | 26/40 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.584      0.394      0.406      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.575      0.395      0.406       0.23
                   0        738       1052      0.598      0.502      0.518       0.25
                   1        738         44      0.544      0.136      0.215      0.102
                   2        738       8622      0.699      0.714      0.744      0.476
                   3        738        151      0.515      0.397      0.426      0.325
                   4        738        467      0.476      0.593      0.533      0.375
                   5        738         70      0.404      0.371      0.295      0.151
                   6        738         65       0.29     0.0615      0.166     0.0693
                   7        738       1619      0.573        0.6      0.578      0.239
                   8        738       2845      0.653      0.574      0.585      0.309
                   9        738          2          1          0   0.000338   0.000304

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 18:59:00.998005404 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31285 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round021_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round021_phase1_head_client4_residential_day_start.pt

self imgsz: 640
self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client4_residential_day_stable_train' images and labels...5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<00:00, 9691.48it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 18:59:17.993778307 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 18:59:17.010490237 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1950       640  0.003525     0.055  0.004683     5.057:   3%|▎         | 1/39 [00:22<13:56, 22.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003515   0.05282  0.004899     4.899:   5%|▌         | 2/39 [00:22<05:53,  9.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003486   0.05095  0.004921     4.749:   8%|▊         | 3/39 [00:23<03:20,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003503   0.04982  0.004798      4.65:  10%|█         | 4/39 [00:24<02:10,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2216       640  0.003501   0.04916  0.004731     4.591:  13%|█▎        | 5/39 [00:25<01:28,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003477   0.04798  0.004713     4.494:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2137       640  0.003492   0.04762  0.004725     4.467:  18%|█▊        | 7/39 [00:26<00:48,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003493     0.047  0.004656     4.412:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003487   0.04701  0.004596     4.408:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003478   0.04668  0.004612     4.382:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003475    0.0462  0.004572      4.34:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640   0.00348   0.04585  0.004593     4.314:  31%|███       | 12/39 [00:29<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003486   0.04555  0.004546     4.287:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003486   0.04534  0.004544      4.27:  36%|███▌      | 14/39 [00:31<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003486   0.04506  0.004529     4.246:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003483   0.04474   0.00453      4.22:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003487   0.04452  0.004565     4.206:  44%|████▎     | 17/39 [00:32<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003478   0.04443  0.004534     4.196:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003477   0.04418  0.004538     4.176:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640  0.003465   0.04403  0.004533     4.162:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003456   0.04386  0.004499     4.145:  54%|█████▍    | 21/39 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003457   0.04381  0.004484      4.14:  56%|█████▋    | 22/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003447   0.04374  0.004477     4.133:  59%|█████▉    | 23/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003438   0.04364  0.004481     4.125:  62%|██████▏   | 24/39 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003434   0.04348  0.004467      4.11:  64%|██████▍   | 25/39 [00:37<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003429   0.04344  0.004459     4.106:  67%|██████▋   | 26/39 [00:38<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.423      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.527      0.422       0.41       0.23
                   0        738       1052      0.537      0.537      0.529      0.253
                   1        738         44      0.482      0.211      0.222      0.103
                   2        738       8622      0.697      0.723      0.747      0.474
                   3        738        151      0.396      0.424      0.435      0.328
                   4        738        467      0.447      0.612      0.534      0.374
                   5        738         70      0.341      0.414      0.293      0.145
                   6        738         65      0.206     0.0769      0.171     0.0698
                   7        738       1619      0.547      0.611      0.578      0.239
                   8        738       2845      0.618      0.605      0.593      0.314
                   9        738          2          1          0   0.000278    0.00025

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:00:41.834674054 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31286 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round021_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round021_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client5_residential_night_stable_train' images and labels...4885 found, 2926 missing, 0 empty, 0 corrupted: 100%|██████████| 7811/7811 [00:00<00:00, 10517.45it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.309426229508198
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round021_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2926 missing, 0 empty, 0 corrupted: 100%|██████████| 7811/7811 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:00:58.513361165 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:00:58.561540967 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1815       640  0.003502   0.04636  0.005411     4.422:   2%|▎         | 1/40 [00:23<14:59, 23.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2045       640   0.00347   0.04421  0.005024     4.217:   5%|▌         | 2/40 [00:23<06:21, 10.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2160       640   0.00343   0.04427  0.004916      4.21:   8%|▊         | 3/40 [00:24<03:36,  5.84s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1972       640  0.003407   0.04299   0.00467     4.085:  10%|█         | 4/40 [00:25<02:19,  3.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1936       640  0.003413   0.04229  0.004738     4.035:  12%|█▎        | 5/40 [00:26<01:35,  2.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003433   0.04166  0.004655      3.98:  15%|█▌        | 6/40 [00:27<01:08,  2.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003456   0.04079  0.004718     3.917:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003448   0.04011  0.004645     3.856:  20%|██        | 8/40 [00:28<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003448   0.04003  0.004582     3.845:  22%|██▎       | 9/40 [00:28<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1929       640  0.003451   0.03966  0.004597     3.817:  25%|██▌       | 10/40 [00:29<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2117       640  0.003461   0.03953  0.004688     3.814:  28%|██▊       | 11/40 [00:30<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003462   0.03927  0.004652     3.791:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003467   0.03905  0.004639     3.772:  32%|███▎      | 13/40 [00:31<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003474   0.03888   0.00466     3.761:  35%|███▌      | 14/40 [00:32<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1736       640  0.003469   0.03853  0.004653     3.732:  38%|███▊      | 15/40 [00:32<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1830       640   0.00346    0.0383  0.004658     3.713:  40%|████      | 16/40 [00:33<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003463     0.038  0.004709     3.694:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2129       640  0.003463   0.03795  0.004715      3.69:  45%|████▌     | 18/40 [00:34<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1495       640  0.003465   0.03745  0.004696     3.649:  48%|████▊     | 19/40 [00:35<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003467   0.03739  0.004679     3.643:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1770       640  0.003466   0.03721  0.004644     3.626:  52%|█████▎    | 21/40 [00:36<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1678       640   0.00346   0.03695  0.004619     3.603:  55%|█████▌    | 22/40 [00:37<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003456   0.03687  0.004597     3.594:  57%|█████▊    | 23/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2024       640  0.003456   0.03683  0.004587      3.59:  60%|██████    | 24/40 [00:38<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1990       640  0.003459   0.03676  0.004608     3.586:  62%|██████▎   | 25/40 [00:39<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003453   0.03663  0.004604     3.575:  65%|██████▌   | 26/40 [00:39<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.576      0.403       0.41      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.571      0.404      0.409      0.229
                   0        738       1052      0.572      0.514      0.522      0.252
                   1        738         44        0.6      0.204      0.236      0.101
                   2        738       8622      0.709      0.709      0.742      0.475
                   3        738        151      0.529      0.388      0.429      0.322
                   4        738        467      0.493      0.589       0.54       0.38
                   5        738         70      0.336        0.4      0.294      0.152
                   6        738         65      0.239     0.0615      0.152      0.063
                   7        738       1619      0.582      0.594      0.584      0.238
                   8        738       2845      0.652      0.583       0.59      0.312
                   9        738          2          1          0   0.000439   0.000395

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:02:23.720094182 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31287 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round021_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round021_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:02:41.389973881 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:02:41.425466902 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03099   0.03589  0.003661     5.644:   3%|▎         | 1/31 [00:33<16:41, 33.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640    0.0305   0.03455  0.003558     5.489:   6%|▋         | 2/31 [00:34<06:51, 14.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02967   0.03297  0.003447     5.287:  10%|▉         | 3/31 [00:34<03:46,  8.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02919   0.03163  0.003254     5.126:  13%|█▎        | 4/31 [00:35<02:20,  5.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02901   0.03149  0.003247       5.1:  16%|█▌        | 5/31 [00:36<01:32,  3.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02904   0.03122  0.003268     5.082:  19%|█▉        | 6/31 [00:36<01:03,  2.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02908   0.03087  0.003322     5.062:  23%|██▎       | 7/31 [00:37<00:45,  1.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02895   0.03084  0.003323      5.05:  26%|██▌       | 8/31 [00:38<00:33,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02902   0.03073  0.003249      5.04:  29%|██▉       | 9/31 [00:38<00:26,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02902    0.0308  0.003219     5.043:  32%|███▏      | 10/31 [00:39<00:21,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02899   0.03079  0.003231     5.041:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02891   0.03052  0.003221     5.012:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640    0.0289   0.03051  0.003178     5.007:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02892   0.03039  0.003154     4.997:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02893   0.03027  0.003201     4.992:  48%|████▊     | 15/31 [00:42<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02893   0.03014  0.003205     4.982:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02895   0.03015  0.003184     4.983:  55%|█████▍    | 17/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02904   0.03027   0.00316     4.997:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02902   0.03016  0.003142     4.986:  61%|██████▏   | 19/31 [00:44<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02904   0.03037   0.00314     5.004:  65%|██████▍   | 20/31 [00:45<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02909   0.03043  0.003161     5.014:  68%|██████▊   | 21/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02912   0.03054  0.003145     5.024:  71%|███████   | 22/31 [00:46<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02912   0.03061  0.003121     5.028:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02917   0.03074  0.003114     5.042:  77%|███████▋  | 24/31 [00:47<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02919   0.03075  0.003119     5.045:  81%|████████  | 25/31 [00:47<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02928   0.03084  0.003126      5.06:  84%|████████▍ | 26/31 [00:48<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.535      0.426      0.408      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.517      0.427      0.405      0.224
                   0        738       1052      0.491      0.536      0.512      0.246
                   1        738         44      0.448      0.203      0.215     0.0887
                   2        738       8622      0.665      0.732      0.744      0.478
                   3        738        151      0.419      0.444      0.431      0.322
                   4        738        467      0.464      0.597      0.527      0.368
                   5        738         70      0.309      0.414      0.314      0.139
                   6        738         65      0.246      0.123      0.163     0.0662
                   7        738       1619       0.54       0.62      0.574      0.235
                   8        738       2845      0.588      0.598      0.569      0.299
                   9        738          2          1          0   0.000457   0.000411

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round021_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 19:04:21.367910267 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round022 phase_round=22 ===

02 head-to-full DQA:  66%|██████▌   | 21/32 [4:57:02<2:34:55, 845.04s/round, elapsed=4h57m02s, eta=2h35m35s, phase=phase1_head, round=21]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round022 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round022 client0_highway_day: pseudo scan 250/1500 images, kept 2383 boxes
round022 client0_highway_day: pseudo scan 500/1500 images, kept 4805 boxes
round022 client0_highway_day: pseudo scan 750/1500 images, kept 7143 boxes
round022 client0_highway_day: pseudo scan 1000/1500 images, kept 9517 boxes
round022 client0_highway_day: pseudo scan 1250/1500 images, kept 11855 boxes
round022 client0_highway_day: pseudo scan 1500/1500 images, kept 14250 boxes
{
  "round": "round022",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round021_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 11250,
  "boxes_per_kept_image": 7.545271629778672,
  "mean_conf": 0.8304637532472611,
  "mean_stability": 0.9455343504852719,
  "mean_score": 0.7886234635177377,
  "class_counts": {
    "0": 163,
    "2": 6413,
    "3": 123,
    "4": 582,
    "5": 4,
    "7": 567,
    "8": 3398
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_client0_highway_day_stable_boxes.csv"
}
round022 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round022 client1_highway_night: pseudo scan 250/1500 images, kept 1534 boxes
round022 client1_highway_night: pseudo scan 500/1500 images, kept 3182 boxes
round022 client1_highway_night: pseudo scan 750/1500 images, kept 4852 boxes
round022 client1_highway_night: pseudo scan 1000/1500 images, kept 6436 boxes
round022 client1_highway_night: pseudo scan 1250/1500 images, kept 8043 boxes
round022 client1_highway_night: pseudo scan 1500/1500 images, kept 9611 boxes
{
  "round": "round022",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round021_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1441,
  "pseudo_boxes_kept": 8003,
  "boxes_per_kept_image": 5.553782095766828,
  "mean_conf": 0.7480997497791442,
  "mean_stability": 0.9262163877472287,
  "mean_score": 0.6971902256558293,
  "class_counts": {
    "0": 67,
    "2": 4325,
    "3": 25,
    "4": 152,
    "5": 7,
    "7": 640,
    "8": 2787
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_client1_highway_night_stable_boxes.csv"
}
round022 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round022 client2_citystreet_day: pseudo scan 250/1500 images, kept 2684 boxes
round022 client2_citystreet_day: pseudo scan 500/1500 images, kept 5414 boxes
round022 client2_citystreet_day: pseudo scan 750/1500 images, kept 8154 boxes
round022 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10907 boxes
round022 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13617 boxes
round022 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16282 boxes
{
  "round": "round022",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round021_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13790,
  "boxes_per_kept_image": 9.224080267558529,
  "mean_conf": 0.8305968943197196,
  "mean_stability": 0.9436982777950295,
  "mean_score": 0.7873398011565295,
  "class_counts": {
    "0": 1502,
    "2": 7327,
    "3": 206,
    "4": 605,
    "5": 65,
    "7": 1487,
    "8": 2598
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_client2_citystreet_day_stable_boxes.csv"
}
round022 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round022 client3_citystreet_night: pseudo scan 250/1500 images, kept 2262 boxes
round022 client3_citystreet_night: pseudo scan 500/1500 images, kept 4500 boxes
round022 client3_citystreet_night: pseudo scan 750/1500 images, kept 6711 boxes
round022 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8831 boxes
round022 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11175 boxes
round022 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13384 boxes
{
  "round": "round022",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round021_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1473,
  "pseudo_boxes_kept": 11437,
  "boxes_per_kept_image": 7.764426340801086,
  "mean_conf": 0.7412150157199432,
  "mean_stability": 0.9210194450862301,
  "mean_score": 0.6873290337683965,
  "class_counts": {
    "0": 549,
    "2": 6023,
    "3": 64,
    "4": 154,
    "5": 33,
    "7": 2112,
    "8": 2502
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_client3_citystreet_night_stable_boxes.csv"
}
round022 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round022 client4_residential_day: pseudo scan 250/1500 images, kept 2577 boxes
round022 client4_residential_day: pseudo scan 500/1500 images, kept 5167 boxes
round022 client4_residential_day: pseudo scan 750/1500 images, kept 7712 boxes
round022 client4_residential_day: pseudo scan 1000/1500 images, kept 10181 boxes
round022 client4_residential_day: pseudo scan 1250/1500 images, kept 12692 boxes
round022 client4_residential_day: pseudo scan 1500/1500 images, kept 15161 boxes
{
  "round": "round022",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round021_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1489,
  "pseudo_boxes_kept": 9946,
  "boxes_per_kept_image": 6.679650772330423,
  "mean_conf": 0.8624328514944972,
  "mean_stability": 0.9527804334530906,
  "mean_score": 0.8251760343251806,
  "class_counts": {
    "0": 405,
    "2": 6823,
    "3": 67,
    "4": 322,
    "5": 44,
    "7": 533,
    "8": 1752
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_client4_residential_day_stable_boxes.csv"
}
round022 client5_residential_night: pseudo scan 1/1500 images, kept 7 boxes
round022 client5_residential_night: pseudo scan 250/1500 images, kept 2172 boxes
round022 client5_residential_night: pseudo scan 500/1500 images, kept 4307 boxes
round022 client5_residential_night: pseudo scan 750/1500 images, kept 6446 boxes
round022 client5_residential_night: pseudo scan 1000/1500 images, kept 8638 boxes
round022 client5_residential_night: pseudo scan 1250/1500 images, kept 10837 boxes
round022 client5_residential_night: pseudo scan 1500/1500 images, kept 13041 boxes
{
  "round": "round022",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round021_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1462,
  "pseudo_boxes_kept": 8173,
  "boxes_per_kept_image": 5.590287277701778,
  "mean_conf": 0.803060197037465,
  "mean_stability": 0.9371648236323378,
  "mean_score": 0.7558570079213263,
  "class_counts": {
    "0": 126,
    "2": 5869,
    "3": 30,
    "4": 95,
    "5": 19,
    "7": 680,
    "8": 1354
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round022_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31288 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round022_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round022_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client0_highway_day_stable_train' images and labels...5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 18003.15it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 19:06:37.895584377 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 19:06:37.916171381 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2150       640  0.003659   0.05131   0.00493     4.792:   3%|▎         | 1/39 [00:22<14:15, 22.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003558   0.04808   0.00455     4.495:   5%|▌         | 2/39 [00:23<06:02,  9.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640  0.003562   0.04705   0.00473     4.427:   8%|▊         | 3/39 [00:24<03:26,  5.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1776       640  0.003558   0.04649  0.004701      4.38:  10%|█         | 4/39 [00:25<02:13,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003532   0.04628   0.00467     4.359:  13%|█▎        | 5/39 [00:25<01:31,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1760       640  0.003487   0.04487  0.004477     4.227:  15%|█▌        | 6/39 [00:26<01:05,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003485   0.04428  0.004495     4.181:  18%|█▊        | 7/39 [00:27<00:49,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1958       640  0.003493   0.04393  0.004633     4.165:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640  0.003507   0.04423  0.004666     4.192:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2108       640  0.003515   0.04436  0.004681     4.204:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2066       640  0.003513   0.04412  0.004656     4.183:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003511   0.04417  0.004763     4.196:  31%|███       | 12/39 [00:30<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003496   0.04383  0.004737     4.165:  33%|███▎      | 13/39 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003491   0.04379  0.004688     4.158:  36%|███▌      | 14/39 [00:31<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003492   0.04364  0.004656     4.143:  38%|███▊      | 15/39 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003492    0.0434  0.004627     4.121:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003491   0.04316  0.004672     4.106:  44%|████▎     | 17/39 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003491   0.04295  0.004653     4.087:  46%|████▌     | 18/39 [00:34<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1710       640  0.003484   0.04257  0.004628     4.055:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2250       640  0.003485   0.04259  0.004635     4.057:  51%|█████▏    | 20/39 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2110       640   0.00348   0.04263  0.004621     4.058:  54%|█████▍    | 21/39 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640   0.00348   0.04252  0.004609     4.049:  56%|█████▋    | 22/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003475    0.0424  0.004577     4.036:  59%|█████▉    | 23/39 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003475   0.04233  0.004576     4.031:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003471   0.04227  0.004581     4.026:  64%|██████▍   | 25/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003468   0.04223  0.004563     4.021:  67%|██████▋   | 26/39 [00:39<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.614      0.387       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.606      0.389      0.409       0.23
                   0        738       1052      0.575      0.519      0.524      0.253
                   1        738         44      0.533      0.136      0.221      0.101
                   2        738       8622       0.76      0.701       0.75      0.476
                   3        738        151      0.647      0.397      0.425      0.323
                   4        738        467      0.519      0.549      0.537       0.38
                   5        738         70      0.403      0.386      0.279      0.143
                   6        738         65      0.317     0.0615      0.171     0.0696
                   7        738       1619      0.598      0.583       0.59      0.241
                   8        738       2845      0.706      0.553      0.591      0.312
                   9        738          2          1          0   0.000488   0.000439

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:08:03.245762627 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31289 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round022_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round022_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client1_highway_night_stable_train' images and labels...4895 found, 2868 missing, 0 empty, 0 corrupted: 100%|██████████| 7763/7763 [00:00<00:00, 12702.74it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.379730799683294
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2868 missing, 0 empty, 0 corrupted: 100%|██████████| 7763/7763 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:08:19.800263786 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:08:19.815086607 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1996       640  0.003388   0.04348  0.004359     4.098:   2%|▎         | 1/40 [00:21<13:42, 21.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1845       640  0.003354   0.04183  0.004521     3.976:   5%|▌         | 2/40 [00:21<05:49,  9.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1759       640  0.003401    0.0417  0.005062     4.013:   8%|▊         | 3/40 [00:22<03:18,  5.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003399   0.04074  0.004954     3.927:  10%|█         | 4/40 [00:23<02:08,  3.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2049       640  0.003424    0.0406  0.004836     3.909:  12%|█▎        | 5/40 [00:24<01:28,  2.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1660       640  0.003424   0.03938  0.004893     3.816:  15%|█▌        | 6/40 [00:24<01:04,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640   0.00342   0.03944  0.004849     3.817:  18%|█▊        | 7/40 [00:25<00:49,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2121       640  0.003435   0.03968    0.0048     3.833:  20%|██        | 8/40 [00:26<00:39,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2218       640  0.003453   0.03987  0.004744     3.846:  22%|██▎       | 9/40 [00:26<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003462   0.03961  0.004755     3.826:  25%|██▌       | 10/40 [00:27<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2207       640  0.003461   0.03953  0.004737     3.818:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640  0.003471   0.03907  0.004753     3.784:  30%|███       | 12/40 [00:28<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2045       640  0.003471   0.03872  0.004762     3.756:  32%|███▎      | 13/40 [00:29<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640   0.00347   0.03828  0.004724     3.718:  35%|███▌      | 14/40 [00:30<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640   0.00347     0.038  0.004767     3.699:  38%|███▊      | 15/40 [00:30<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1952       640  0.003475   0.03781    0.0048     3.686:  40%|████      | 16/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1863       640  0.003482   0.03762  0.004807     3.673:  42%|████▎     | 17/40 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2128       640  0.003484   0.03764  0.004818     3.676:  45%|████▌     | 18/40 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1813       640  0.003493   0.03734  0.004864     3.656:  48%|████▊     | 19/40 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2170       640  0.003488   0.03735  0.004838     3.654:  50%|█████     | 20/40 [00:33<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1820       640  0.003487   0.03714  0.004822     3.636:  52%|█████▎    | 21/40 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1556       640  0.003483   0.03685  0.004807     3.611:  55%|█████▌    | 22/40 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1853       640  0.003479   0.03668  0.004784     3.596:  57%|█████▊    | 23/40 [00:35<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1745       640  0.003474   0.03654  0.004797     3.585:  60%|██████    | 24/40 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1745       640  0.003469   0.03635   0.00479     3.568:  62%|██████▎   | 25/40 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1944       640  0.003464   0.03622  0.004751     3.555:  65%|██████▌   | 26/40 [00:37<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.596      0.398      0.411      0.232
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]

                 all        738      14937      0.588      0.397       0.41      0.232
                   0        738       1052      0.565      0.523      0.524      0.256
                   1        738         44      0.614      0.182      0.252      0.116
                   2        738       8622      0.721      0.711      0.748      0.479
                   3        738        151      0.533      0.404      0.425      0.328
                   4        738        467      0.491      0.564       0.53      0.376
                   5        738         70      0.395      0.371      0.275      0.143
                   6        738         65      0.307     0.0547      0.173      0.072
                   7        738       1619      0.583      0.591      0.583      0.243
                   8        738       2845      0.675      0.572      0.591      0.311
                   9        738          2          1          0   0.000522   0.000469

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:09:43.323046550 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31290 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round022_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round022_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client2_citystreet_day_stable_train' images and labels...5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 9994.45it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:09:59.424951920 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:09:59.439427646 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1949       640  0.003446   0.05479  0.004551     5.023:   3%|▎         | 1/39 [00:22<14:00, 22.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003468   0.05529  0.004669     5.074:   5%|▌         | 2/39 [00:23<05:56,  9.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003443   0.05304  0.004574     4.885:   8%|▊         | 3/39 [00:23<03:22,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003438    0.0513  0.004646     4.751:  10%|█         | 4/39 [00:24<02:11,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2180       640   0.00344   0.05064  0.004552     4.691:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1564       640   0.00342   0.04867  0.004502     4.527:  15%|█▌        | 6/39 [00:26<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003448   0.04851  0.004641     4.528:  18%|█▊        | 7/39 [00:26<00:48,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003437   0.04788  0.004608     4.474:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003447   0.04794  0.004523     4.473:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003435   0.04745  0.004503     4.431:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003442   0.04721  0.004525     4.414:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003446   0.04678  0.004573     4.384:  31%|███       | 12/39 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003456   0.04678  0.004544     4.382:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003465   0.04665  0.004508      4.37:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003468   0.04649   0.00452     4.358:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003472   0.04627  0.004519     4.341:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003474   0.04618  0.004521     4.334:  44%|████▎     | 17/39 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003466   0.04609  0.004488     4.324:  46%|████▌     | 18/39 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640  0.003464    0.0458  0.004452     4.297:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003463   0.04579  0.004464     4.297:  51%|█████▏    | 20/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640  0.003456   0.04565  0.004429     4.283:  54%|█████▍    | 21/39 [00:35<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003451   0.04569  0.004414     4.285:  56%|█████▋    | 22/39 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640   0.00345   0.04556  0.004427     4.275:  59%|█████▉    | 23/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003449   0.04559  0.004406     4.275:  62%|██████▏   | 24/39 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2034       640  0.003447   0.04551  0.004393     4.268:  64%|██████▍   | 25/39 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003447   0.04542  0.004409     4.262:  67%|██████▋   | 26/39 [00:38<00:08,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.542      0.417      0.409      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937       0.53       0.42      0.407      0.229
                   0        738       1052      0.606      0.504      0.522      0.253
                   1        738         44      0.429      0.205      0.213      0.101
                   2        738       8622      0.652      0.743      0.751      0.477
                   3        738        151      0.415      0.411      0.426      0.317
                   4        738        467      0.443      0.608      0.526      0.371
                   5        738         70      0.373      0.429      0.298      0.155
                   6        738         65      0.215     0.0769      0.167     0.0713
                   7        738       1619      0.553       0.62      0.574      0.237
                   8        738       2845      0.611      0.606       0.59      0.312
                   9        738          2          1          0   0.000309   0.000278

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:11:25.952640903 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31291 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round022_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round022_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client3_citystreet_night_stable_train' images and labels...4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<00:00, 14520.04it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.287738076499291
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:11:42.671821571 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:11:42.675904700 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1951       640  0.003579   0.04784  0.003902     4.425:   2%|▎         | 1/40 [00:21<14:05, 21.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1752       640  0.003512   0.04557  0.004732     4.305:   5%|▌         | 2/40 [00:22<05:59,  9.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003483   0.04495  0.004574     4.241:   8%|▊         | 3/40 [00:23<03:25,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003439   0.04382  0.004421     4.134:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1740       640  0.003419   0.04274  0.004561     4.058:  12%|█▎        | 5/40 [00:25<01:31,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640  0.003416   0.04161  0.004506     3.962:  15%|█▌        | 6/40 [00:25<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640   0.00342   0.04126  0.004472     3.932:  18%|█▊        | 7/40 [00:26<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2132       640  0.003426   0.04138  0.004515     3.946:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003428   0.04112  0.004482     3.922:  22%|██▎       | 9/40 [00:27<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003435   0.04071  0.004497     3.891:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2068       640  0.003431    0.0404  0.004496     3.866:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1828       640  0.003435   0.04012  0.004491     3.843:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003435   0.03986  0.004507     3.824:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2192       640  0.003434   0.03998  0.004502     3.833:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1788       640  0.003429   0.03956  0.004472     3.797:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1755       640  0.003419   0.03923  0.004425     3.766:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1628       640  0.003425   0.03879  0.004454     3.734:  42%|████▎     | 17/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003427   0.03858  0.004447     3.716:  45%|████▌     | 18/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1662       640  0.003424   0.03823  0.004406     3.685:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2116       640  0.003425   0.03818  0.004396      3.68:  50%|█████     | 20/40 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1776       640  0.003435     0.038  0.004414     3.668:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1859       640  0.003433   0.03798  0.004398     3.665:  55%|█████▌    | 22/40 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2109       640  0.003433   0.03794  0.004403     3.662:  57%|█████▊    | 23/40 [00:36<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003433   0.03786  0.004415     3.656:  60%|██████    | 24/40 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003436   0.03783  0.004406     3.654:  62%|██████▎   | 25/40 [00:37<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1931       640  0.003434   0.03769  0.004404     3.642:  65%|██████▌   | 26/40 [00:38<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.595       0.39      0.407      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.582      0.391      0.406      0.229
                   0        738       1052      0.619      0.499       0.52      0.251
                   1        738         44      0.537      0.159      0.237      0.104
                   2        738       8622      0.717      0.706      0.742      0.474
                   3        738        151      0.513      0.391      0.427      0.321
                   4        738        467      0.479      0.587      0.535      0.375
                   5        738         70      0.407      0.363      0.275      0.145
                   6        738         65      0.299     0.0615      0.165      0.069
                   7        738       1619      0.578      0.586      0.569      0.237
                   8        738       2845      0.671      0.561      0.584      0.309
                   9        738          2          1          0   0.000401   0.000361

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:13:07.787485904 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31292 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round022_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round022_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client4_residential_day_stable_train' images and labels...5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<00:00, 10570.56it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:13:24.284304293 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:13:24.308447063 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1950       640  0.003528   0.05537  0.004679     5.086:   3%|▎         | 1/39 [00:21<13:47, 21.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003521   0.05313  0.004898     4.924:   5%|▌         | 2/39 [00:22<05:51,  9.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003493   0.05124  0.004917     4.772:   8%|▊         | 3/39 [00:23<03:19,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003509   0.05006  0.004794     4.669:  10%|█         | 4/39 [00:24<02:09,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2216       640  0.003508   0.04939  0.004728      4.61:  13%|█▎        | 5/39 [00:25<01:28,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003483   0.04819  0.004709     4.511:  15%|█▌        | 6/39 [00:25<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2137       640  0.003498   0.04782  0.004723     4.483:  18%|█▊        | 7/39 [00:26<00:49,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003499   0.04719  0.004653     4.427:  21%|██        | 8/39 [00:27<00:39,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003493   0.04718  0.004592     4.421:  23%|██▎       | 9/39 [00:27<00:32,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003484   0.04684  0.004607     4.394:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003481   0.04635   0.00457     4.352:  28%|██▊       | 11/39 [00:29<00:24,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003486   0.04599   0.00459     4.325:  31%|███       | 12/39 [00:29<00:21,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003491   0.04568  0.004542     4.297:  33%|███▎      | 13/39 [00:30<00:19,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003491   0.04547  0.004539      4.28:  36%|███▌      | 14/39 [00:31<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003491   0.04517  0.004523     4.255:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003489   0.04485  0.004523     4.229:  41%|████      | 16/39 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003492   0.04463  0.004558     4.214:  44%|████▎     | 17/39 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003483   0.04453  0.004528     4.203:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003482   0.04427  0.004531     4.183:  49%|████▊     | 19/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640  0.003471   0.04412  0.004527      4.17:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003461   0.04395  0.004493     4.152:  54%|█████▍    | 21/39 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003462   0.04389  0.004479     4.147:  56%|█████▋    | 22/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003453   0.04382  0.004471      4.14:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003444   0.04372  0.004475     4.131:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003439   0.04356  0.004462     4.117:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003434   0.04351  0.004453     4.112:  67%|██████▋   | 26/39 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.53      0.422      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.515      0.423      0.408       0.23
                   0        738       1052      0.518      0.535      0.523      0.252
                   1        738         44      0.454      0.227      0.222      0.105
                   2        738       8622      0.685      0.726      0.746      0.474
                   3        738        151      0.385       0.43      0.433      0.327
                   4        738        467      0.441      0.612      0.533      0.374
                   5        738         70      0.327        0.4       0.28      0.144
                   6        738         65      0.189     0.0769      0.174     0.0722
                   7        738       1619      0.538      0.618      0.577      0.238
                   8        738       2845      0.611      0.608       0.59      0.313
                   9        738          2          1          0   0.000291   0.000262

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:14:48.044464851 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31293 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round022_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round022_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client5_residential_night_stable_train' images and labels...4885 found, 2920 missing, 0 empty, 0 corrupted: 100%|██████████| 7805/7805 [00:00<00:00, 18388.27it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.31666929506387
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round022_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2920 missing, 0 empty, 0 corrupted: 100%|██████████| 7805/7805 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:15:05.461278417 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:15:05.515725849 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2029       640   0.00352   0.04637    0.0046      4.36:   2%|▎         | 1/40 [00:21<14:04, 21.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003552   0.04593  0.004706     4.335:   5%|▌         | 2/40 [00:22<06:00,  9.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003502   0.04517  0.004472     4.251:   8%|▊         | 3/40 [00:23<03:25,  5.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003464   0.04324  0.004506     4.097:  10%|█         | 4/40 [00:24<02:13,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003474   0.04271  0.004484     4.053:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003484   0.04169  0.004469     3.972:  15%|█▌        | 6/40 [00:25<01:06,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2038       640  0.003507   0.04129   0.00461     3.953:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1712       640  0.003501   0.04065  0.004533     3.894:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2282       640  0.003511     0.041  0.004551     3.925:  22%|██▎       | 9/40 [00:27<00:32,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640    0.0035   0.04069  0.004496     3.895:  25%|██▌       | 10/40 [00:28<00:27,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2230       640    0.0035   0.04048  0.004472     3.876:  28%|██▊       | 11/40 [00:28<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003496   0.04027  0.004511     3.862:  30%|███       | 12/40 [00:29<00:21,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003505   0.04015  0.004567     3.858:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003498    0.0398  0.004573      3.83:  35%|███▌      | 14/40 [00:30<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1740       640  0.003495    0.0393   0.00462     3.793:  38%|███▊      | 15/40 [00:31<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1969       640  0.003491   0.03905  0.004623     3.773:  40%|████      | 16/40 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2189       640  0.003497   0.03906  0.004622     3.775:  42%|████▎     | 17/40 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003494   0.03877  0.004608      3.75:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1636       640  0.003493   0.03834   0.00461     3.716:  48%|████▊     | 19/40 [00:33<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003502   0.03825   0.00459     3.708:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2179       640  0.003501   0.03829  0.004588      3.71:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1754       640  0.003497   0.03805  0.004549     3.688:  55%|█████▌    | 22/40 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1752       640  0.003488   0.03777  0.004546     3.665:  57%|█████▊    | 23/40 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003483   0.03755  0.004539     3.646:  60%|██████    | 24/40 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640  0.003481    0.0374  0.004564     3.636:  62%|██████▎   | 25/40 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1790       640  0.003482    0.0372  0.004568      3.62:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.576      0.402      0.409      0.231
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.562      0.402      0.407      0.231
                   0        738       1052      0.572       0.52      0.524      0.253
                   1        738         44      0.529      0.205       0.24      0.109
                   2        738       8622      0.706      0.711      0.743      0.474
                   3        738        151      0.526      0.391      0.426      0.328
                   4        738        467      0.489      0.582      0.537      0.379
                   5        738         70      0.336      0.386      0.281      0.152
                   6        738         65      0.229     0.0615      0.159     0.0649
                   7        738       1619      0.582      0.589      0.576      0.237
                   8        738       2845      0.654       0.58      0.587       0.31
                   9        738          2          1          0   0.000397   0.000357

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:16:28.222104753 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31294 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round022_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round022_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:16:45.890012511 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:16:45.907354947 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03103   0.03599  0.003656     5.653:   3%|▎         | 1/31 [00:32<16:04, 32.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03042   0.03437  0.003524     5.465:   6%|▋         | 2/31 [00:32<06:37, 13.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02954   0.03271  0.003408     5.253:  10%|▉         | 3/31 [00:33<03:38,  7.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02912   0.03145  0.003225     5.103:  13%|█▎        | 4/31 [00:34<02:16,  5.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02891   0.03122  0.003211     5.067:  16%|█▌        | 5/31 [00:35<01:29,  3.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02889    0.0309  0.003231     5.042:  19%|█▉        | 6/31 [00:35<01:01,  2.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02891   0.03053  0.003283     5.018:  23%|██▎       | 7/31 [00:36<00:44,  1.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02877   0.03049  0.003282     5.003:  26%|██▌       | 8/31 [00:36<00:33,  1.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02881   0.03037  0.003209     4.991:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02881   0.03043  0.003179     4.993:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02876    0.0304  0.003187     4.988:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02867   0.03013  0.003176     4.958:  39%|███▊      | 12/31 [00:39<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02864   0.03008  0.003133     4.948:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02865   0.02996  0.003108     4.937:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02867   0.02984  0.003154     4.933:  48%|████▊     | 15/31 [00:40<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02868   0.02971  0.003158     4.924:  52%|█████▏    | 16/31 [00:41<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02871   0.02972  0.003137     4.925:  55%|█████▍    | 17/31 [00:42<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640    0.0288   0.02984  0.003113      4.94:  58%|█████▊    | 18/31 [00:42<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02878   0.02973  0.003097     4.928:  61%|██████▏   | 19/31 [00:43<00:07,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640    0.0288   0.02994  0.003094     4.947:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02886   0.02999  0.003115     4.957:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02889    0.0301  0.003099     4.967:  71%|███████   | 22/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02891   0.03018  0.003075     4.973:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02896   0.03031  0.003068     4.988:  77%|███████▋  | 24/31 [00:46<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640     0.029   0.03032  0.003072     4.991:  81%|████████  | 25/31 [00:46<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02908   0.03042   0.00308     5.007:  84%|████████▍ | 26/31 [00:47<00:02,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.538      0.424      0.407      0.223
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.25it/s]

                 all        738      14937      0.521      0.425      0.404      0.223
                   0        738       1052       0.49      0.532      0.511      0.246
                   1        738         44       0.45      0.205      0.214     0.0877
                   2        738       8622      0.673      0.728      0.742      0.476
                   3        738        151      0.425      0.444      0.432       0.32
                   4        738        467      0.475      0.595      0.525      0.365
                   5        738         70      0.306      0.414      0.318      0.138
                   6        738         65      0.245      0.123      0.161     0.0628
                   7        738       1619      0.546      0.615      0.573      0.234
                   8        738       2845      0.597      0.594      0.565      0.296
                   9        738          2          1          0   0.000482   0.000434

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round022_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 19:18:23.407983579 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round023 phase_round=23 ===

02 head-to-full DQA:  69%|██████▉   | 22/32 [5:11:04<2:20:41, 844.18s/round, elapsed=5h11m04s, eta=2h21m24s, phase=phase1_head, round=22]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round023 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round023 client0_highway_day: pseudo scan 250/1500 images, kept 2369 boxes
round023 client0_highway_day: pseudo scan 500/1500 images, kept 4795 boxes
round023 client0_highway_day: pseudo scan 750/1500 images, kept 7129 boxes
round023 client0_highway_day: pseudo scan 1000/1500 images, kept 9500 boxes
round023 client0_highway_day: pseudo scan 1250/1500 images, kept 11833 boxes
round023 client0_highway_day: pseudo scan 1500/1500 images, kept 14227 boxes
{
  "round": "round023",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round022_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 11230,
  "boxes_per_kept_image": 7.5369127516778525,
  "mean_conf": 0.8323388841809275,
  "mean_stability": 0.9449627368023432,
  "mean_score": 0.7898946745911191,
  "class_counts": {
    "0": 165,
    "2": 6403,
    "3": 122,
    "4": 568,
    "5": 7,
    "7": 573,
    "8": 3392
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_client0_highway_day_stable_boxes.csv"
}
round023 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round023 client1_highway_night: pseudo scan 250/1500 images, kept 1502 boxes
round023 client1_highway_night: pseudo scan 500/1500 images, kept 3115 boxes
round023 client1_highway_night: pseudo scan 750/1500 images, kept 4761 boxes
round023 client1_highway_night: pseudo scan 1000/1500 images, kept 6311 boxes
round023 client1_highway_night: pseudo scan 1250/1500 images, kept 7893 boxes
round023 client1_highway_night: pseudo scan 1500/1500 images, kept 9428 boxes
{
  "round": "round023",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round022_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1436,
  "pseudo_boxes_kept": 7869,
  "boxes_per_kept_image": 5.479805013927576,
  "mean_conf": 0.7507068825723983,
  "mean_stability": 0.925144062599425,
  "mean_score": 0.6988002768727526,
  "class_counts": {
    "0": 65,
    "2": 4243,
    "3": 25,
    "4": 150,
    "5": 7,
    "7": 639,
    "8": 2740
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_client1_highway_night_stable_boxes.csv"
}
round023 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round023 client2_citystreet_day: pseudo scan 250/1500 images, kept 2682 boxes
round023 client2_citystreet_day: pseudo scan 500/1500 images, kept 5411 boxes
round023 client2_citystreet_day: pseudo scan 750/1500 images, kept 8142 boxes
round023 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10882 boxes
round023 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13583 boxes
round023 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16249 boxes
{
  "round": "round023",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round022_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13768,
  "boxes_per_kept_image": 9.209364548494984,
  "mean_conf": 0.8324215874500153,
  "mean_stability": 0.9427170159034366,
  "mean_score": 0.7883091573707993,
  "class_counts": {
    "0": 1489,
    "2": 7313,
    "3": 213,
    "4": 597,
    "5": 68,
    "7": 1499,
    "8": 2589
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_client2_citystreet_day_stable_boxes.csv"
}
round023 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round023 client3_citystreet_night: pseudo scan 250/1500 images, kept 2241 boxes
round023 client3_citystreet_night: pseudo scan 500/1500 images, kept 4458 boxes
round023 client3_citystreet_night: pseudo scan 750/1500 images, kept 6649 boxes
round023 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8753 boxes
round023 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11077 boxes
round023 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13270 boxes
{
  "round": "round023",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round022_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1474,
  "pseudo_boxes_kept": 11363,
  "boxes_per_kept_image": 7.708955223880597,
  "mean_conf": 0.7426684113452313,
  "mean_stability": 0.9198561757370209,
  "mean_score": 0.6877730311379229,
  "class_counts": {
    "0": 557,
    "2": 5972,
    "3": 62,
    "4": 147,
    "5": 33,
    "7": 2126,
    "8": 2466
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_client3_citystreet_night_stable_boxes.csv"
}
round023 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round023 client4_residential_day: pseudo scan 250/1500 images, kept 2568 boxes
round023 client4_residential_day: pseudo scan 500/1500 images, kept 5162 boxes
round023 client4_residential_day: pseudo scan 750/1500 images, kept 7706 boxes
round023 client4_residential_day: pseudo scan 1000/1500 images, kept 10166 boxes
round023 client4_residential_day: pseudo scan 1250/1500 images, kept 12678 boxes
round023 client4_residential_day: pseudo scan 1500/1500 images, kept 15144 boxes
{
  "round": "round023",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round022_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1489,
  "pseudo_boxes_kept": 9927,
  "boxes_per_kept_image": 6.666890530557421,
  "mean_conf": 0.8640267536114671,
  "mean_stability": 0.9520700117174419,
  "mean_score": 0.8261011071180585,
  "class_counts": {
    "0": 412,
    "2": 6815,
    "3": 69,
    "4": 310,
    "5": 46,
    "7": 532,
    "8": 1743
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_client4_residential_day_stable_boxes.csv"
}
round023 client5_residential_night: pseudo scan 1/1500 images, kept 6 boxes
round023 client5_residential_night: pseudo scan 250/1500 images, kept 2136 boxes
round023 client5_residential_night: pseudo scan 500/1500 images, kept 4231 boxes
round023 client5_residential_night: pseudo scan 750/1500 images, kept 6327 boxes
round023 client5_residential_night: pseudo scan 1000/1500 images, kept 8478 boxes
round023 client5_residential_night: pseudo scan 1250/1500 images, kept 10634 boxes
round023 client5_residential_night: pseudo scan 1500/1500 images, kept 12778 boxes
{
  "round": "round023",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round022_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1461,
  "pseudo_boxes_kept": 8032,
  "boxes_per_kept_image": 5.49760438056126,
  "mean_conf": 0.8031640755517252,
  "mean_stability": 0.9358564286726523,
  "mean_score": 0.754928677408573,
  "class_counts": {
    "0": 127,
    "2": 5751,
    "3": 32,
    "4": 90,
    "5": 22,
    "7": 699,
    "8": 1311
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round023_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31295 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round023_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round023_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7861 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client0_highway_day_stable_train' images and labels...5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 17220.27it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 19:20:40.159798952 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 19:20:40.180530329 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1955       640   0.00349    0.0479  0.005339     4.538:   3%|▎         | 1/39 [00:21<13:49, 21.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2076       640  0.003462   0.04769  0.004586     4.459:   5%|▌         | 2/39 [00:22<05:52,  9.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003458   0.04669  0.004687     4.387:   8%|▊         | 3/39 [00:23<03:20,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1743       640  0.003441   0.04595   0.00462     4.321:  10%|█         | 4/39 [00:24<02:09,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640   0.00344   0.04581  0.004642     4.312:  13%|█▎        | 5/39 [00:25<01:28,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003442   0.04482  0.004506     4.221:  15%|█▌        | 6/39 [00:25<01:03,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640  0.003441   0.04444  0.004427     4.185:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003446   0.04428  0.004417     4.172:  21%|██        | 8/39 [00:26<00:38,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2064       640  0.003452   0.04439  0.004462     4.184:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003466   0.04442  0.004487      4.19:  26%|██▌       | 10/39 [00:28<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003469   0.04408   0.00448     4.162:  28%|██▊       | 11/39 [00:28<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003476   0.04413  0.004578     4.174:  31%|███       | 12/39 [00:29<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2146       640  0.003472   0.04396  0.004604     4.163:  33%|███▎      | 13/39 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640  0.003473   0.04399  0.004555     4.161:  36%|███▌      | 14/39 [00:30<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003476   0.04375  0.004527      4.14:  38%|███▊      | 15/39 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003477   0.04358  0.004511     4.125:  41%|████      | 16/39 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003479    0.0435  0.004537     4.121:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2205       640   0.00348   0.04335  0.004496     4.106:  46%|████▌     | 18/39 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640   0.00348   0.04301  0.004517      4.08:  49%|████▊     | 19/39 [00:33<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2122       640  0.003477   0.04295  0.004483     4.073:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2158       640  0.003479   0.04299  0.004465     4.074:  54%|█████▍    | 21/39 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003482   0.04296  0.004448     4.071:  56%|█████▋    | 22/39 [00:35<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003473    0.0428  0.004425     4.056:  59%|█████▉    | 23/39 [00:36<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003474   0.04283  0.004402     4.057:  62%|██████▏   | 24/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003472   0.04272  0.004421     4.049:  64%|██████▍   | 25/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003471   0.04264  0.004397      4.04:  67%|██████▋   | 26/39 [00:38<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.591        0.4      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.588      0.397       0.41      0.231
                   0        738       1052      0.556      0.531      0.527      0.254
                   1        738         44       0.55      0.167      0.232      0.104
                   2        738       8622      0.743      0.709       0.75      0.476
                   3        738        151      0.594      0.404       0.43      0.321
                   4        738        467      0.502      0.557      0.535      0.381
                   5        738         70      0.381      0.386      0.287       0.15
                   6        738         65       0.28     0.0615      0.169     0.0708
                   7        738       1619      0.585      0.595      0.585      0.241
                   8        738       2845      0.689      0.556      0.587       0.31
                   9        738          2          1          0   0.000471   0.000424

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client0_highway_day

1 epochs completed in 0.023 hours.
Destroying process group...
[rank0]:[W507 19:22:02.699404446 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31296 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round023_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round023_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client1_highway_night_stable_train' images and labels...4895 found, 2858 missing, 0 empty, 0 corrupted: 100%|██████████| 7753/7753 [00:00<00:00, 11710.15it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.391917591125198
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2858 missing, 0 empty, 0 corrupted: 100%|██████████| 7753/7753 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 19:22:18.881394923 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 19:22:18.905596381 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2092       640  0.003495   0.04308  0.005346     4.154:   2%|▎         | 1/40 [00:21<14:08, 21.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003482   0.04308  0.005225     4.143:   5%|▌         | 2/40 [00:22<05:59,  9.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1902       640  0.003459   0.04216  0.005039     4.053:   8%|▊         | 3/40 [00:23<03:24,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2063       640  0.003477   0.04224  0.004919     4.051:  10%|█         | 4/40 [00:24<02:12,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003485   0.04199  0.004915     4.031:  12%|█▎        | 5/40 [00:24<01:30,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1681       640  0.003485   0.04077  0.004798     3.924:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1858       640  0.003497   0.04021  0.004798     3.881:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2030       640  0.003496   0.04001  0.004779     3.863:  20%|██        | 8/40 [00:26<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003502   0.03947   0.00482     3.824:  22%|██▎       | 9/40 [00:27<00:33,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2078       640  0.003503   0.03949  0.004796     3.823:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2235       640  0.003512   0.03946  0.004843     3.825:  28%|██▊       | 11/40 [00:28<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003514   0.03902  0.004812     3.788:  30%|███       | 12/40 [00:29<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1905       640  0.003524   0.03865  0.004833     3.761:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1788       640  0.003517   0.03835  0.004804     3.734:  35%|███▌      | 14/40 [00:30<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1828       640  0.003511   0.03803  0.004799     3.707:  38%|███▊      | 15/40 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003511   0.03802  0.004812     3.707:  40%|████      | 16/40 [00:32<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640  0.003516   0.03782  0.004817     3.692:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2141       640  0.003517   0.03782  0.004804     3.692:  45%|████▌     | 18/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1589       640  0.003509   0.03742  0.004848     3.662:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2038       640  0.003512   0.03736  0.004823     3.655:  50%|█████     | 20/40 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1981       640  0.003509   0.03715  0.004824     3.639:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1761       640  0.003505     0.037  0.004811     3.625:  55%|█████▌    | 22/40 [00:36<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1883       640  0.003498   0.03688  0.004787     3.613:  57%|█████▊    | 23/40 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003494   0.03682  0.004775     3.607:  60%|██████    | 24/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1788       640  0.003488   0.03664  0.004761     3.591:  62%|██████▎   | 25/40 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003485   0.03647  0.004729     3.575:  65%|██████▌   | 26/40 [00:38<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.592      0.398      0.408       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]

                 all        738      14937      0.584      0.399      0.408       0.23
                   0        738       1052      0.568      0.524      0.525      0.254
                   1        738         44      0.571      0.182      0.244      0.114
                   2        738       8622      0.711      0.713      0.746      0.478
                   3        738        151      0.582      0.384      0.423      0.322
                   4        738        467      0.495       0.55      0.527      0.374
                   5        738         70      0.393        0.4      0.286      0.147
                   6        738         65       0.29     0.0615       0.16     0.0673
                   7        738       1619      0.573      0.602      0.583      0.238
                   8        738       2845      0.653      0.575      0.582      0.305
                   9        738          2          1          0   0.000492   0.000443

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:23:42.595349637 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31297 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round023_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round023_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client2_citystreet_day_stable_train' images and labels...5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 12623.38it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:23:59.336272529 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:23:59.338702682 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1949       640  0.003454   0.05505  0.004544     5.044:   3%|▎         | 1/39 [00:21<13:50, 21.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003474   0.05556  0.004653     5.095:   5%|▌         | 2/39 [00:22<05:52,  9.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003451   0.05329  0.004572     4.905:   8%|▊         | 3/39 [00:23<03:20,  5.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003446   0.05152  0.004642     4.769:  10%|█         | 4/39 [00:24<02:09,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2180       640  0.003446   0.05083  0.004547     4.706:  13%|█▎        | 5/39 [00:25<01:27,  2.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1564       640  0.003426   0.04883  0.004499     4.541:  15%|█▌        | 6/39 [00:25<01:03,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003455   0.04867  0.004641     4.541:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003443   0.04802  0.004613     4.486:  21%|██        | 8/39 [00:26<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003453   0.04807   0.00453     4.484:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003441   0.04757   0.00451     4.441:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003449   0.04732  0.004532     4.424:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003453   0.04688   0.00458     4.393:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003463   0.04688  0.004551     4.391:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003472   0.04675  0.004514     4.379:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003475   0.04658  0.004524     4.367:  38%|███▊      | 15/39 [00:31<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003478   0.04636  0.004523     4.349:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640   0.00348   0.04627  0.004524     4.342:  44%|████▎     | 17/39 [00:32<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003473   0.04618  0.004491     4.331:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640   0.00347   0.04588  0.004455     4.304:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003469   0.04587  0.004467     4.304:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640  0.003461   0.04572  0.004432     4.289:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003457   0.04577  0.004417     4.291:  56%|█████▋    | 22/39 [00:35<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003456   0.04564  0.004429     4.282:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003454   0.04566  0.004408     4.281:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2034       640  0.003453   0.04558  0.004394     4.274:  64%|██████▍   | 25/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003452   0.04549  0.004411     4.268:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.544      0.417       0.41      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.531       0.42      0.407      0.229
                   0        738       1052      0.604      0.503      0.523      0.251
                   1        738         44       0.43      0.206      0.211        0.1
                   2        738       8622      0.655      0.742       0.75      0.476
                   3        738        151      0.423      0.411      0.426      0.317
                   4        738        467      0.439      0.606      0.525      0.369
                   5        738         70      0.376      0.429      0.303      0.155
                   6        738         65       0.21     0.0769      0.166     0.0697
                   7        738       1619      0.558      0.619       0.58      0.237
                   8        738       2845      0.613      0.605      0.589      0.312
                   9        738          2          1          0   0.000311    0.00028

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:25:24.126391035 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31298 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round023_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round023_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7829 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client3_citystreet_night_stable_train' images and labels...4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<00:00, 11267.15it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.285332074283916
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2946 missing, 0 empty, 0 corrupted: 100%|██████████| 7829/7829 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:25:41.914625158 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:25:41.953651418 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1937       640  0.003579   0.04684  0.004455      4.39:   2%|▎         | 1/40 [00:21<14:10, 21.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003567   0.04462  0.004788     4.238:   5%|▌         | 2/40 [00:22<06:00,  9.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003538   0.04497  0.004752     4.261:   8%|▊         | 3/40 [00:23<03:24,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640   0.00353    0.0443  0.004715     4.204:  10%|█         | 4/40 [00:24<02:12,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1825       640  0.003499   0.04332   0.00465     4.117:  12%|█▎        | 5/40 [00:24<01:30,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1800       640  0.003503   0.04251  0.004582     4.047:  15%|█▌        | 6/40 [00:25<01:05,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003508   0.04185   0.00454     3.991:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2067       640  0.003505   0.04163   0.00454     3.974:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003497   0.04123  0.004467     3.936:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003509    0.0411   0.00444     3.924:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003495   0.04063  0.004384      3.88:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1600       640  0.003486   0.04004  0.004437     3.837:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2051       640  0.003484   0.03975   0.00444     3.814:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640  0.003485   0.03976  0.004439     3.815:  35%|███▌      | 14/40 [00:30<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003479   0.03943  0.004455     3.789:  38%|███▊      | 15/40 [00:31<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1880       640  0.003469   0.03906  0.004393     3.754:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1611       640   0.00347   0.03863  0.004407      3.72:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003474   0.03841  0.004411     3.704:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003472   0.03807  0.004391     3.675:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2257       640  0.003471   0.03809  0.004352     3.673:  50%|█████     | 20/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1806       640  0.003476   0.03793  0.004369     3.662:  52%|█████▎    | 21/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1705       640  0.003471    0.0377  0.004341     3.641:  55%|█████▌    | 22/40 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2191       640   0.00347   0.03771  0.004344     3.642:  57%|█████▊    | 23/40 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1876       640  0.003467   0.03757  0.004353     3.631:  60%|██████    | 24/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003467   0.03745   0.00434      3.62:  62%|██████▎   | 25/40 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003464   0.03733  0.004336      3.61:  65%|██████▌   | 26/40 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.589       0.39      0.406      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.586      0.389      0.404      0.229
                   0        738       1052      0.614      0.499      0.518       0.25
                   1        738         44      0.542      0.136      0.225      0.106
                   2        738       8622      0.706       0.71      0.743      0.474
                   3        738        151      0.555      0.397      0.425      0.322
                   4        738        467      0.495      0.593      0.533      0.374
                   5        738         70      0.387      0.343      0.275      0.148
                   6        738         65      0.327     0.0615      0.166     0.0705
                   7        738       1619      0.577      0.588      0.573      0.237
                   8        738       2845      0.659      0.565      0.581      0.307
                   9        738          2          1          0   0.000399   0.000359

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:27:05.195559276 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31299 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round023_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round023_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client4_residential_day_stable_train' images and labels...5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<00:00, 11664.77it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 19:27:22.808137945 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 19:27:22.822352039 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1950       640  0.003533   0.05556  0.004664     5.101:   3%|▎         | 1/39 [00:22<13:56, 22.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003525   0.05329  0.004875     4.935:   5%|▌         | 2/39 [00:22<05:55,  9.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003498   0.05138  0.004903     4.782:   8%|▊         | 3/39 [00:23<03:21,  5.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003515    0.0502  0.004794     4.681:  10%|█         | 4/39 [00:24<02:10,  3.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2216       640  0.003514   0.04951   0.00473      4.62:  13%|█▎        | 5/39 [00:25<01:29,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640   0.00349   0.04833  0.004712     4.522:  15%|█▌        | 6/39 [00:26<01:05,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2137       640  0.003505   0.04794  0.004725     4.493:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003506   0.04729  0.004656     4.437:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003499   0.04729  0.004596     4.431:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640   0.00349   0.04694  0.004609     4.403:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003488   0.04644  0.004571      4.36:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003493   0.04608  0.004591     4.333:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003498   0.04578  0.004543     4.305:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003498   0.04555  0.004539     4.287:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003497   0.04526  0.004524     4.262:  38%|███▊      | 15/39 [00:31<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003495   0.04494  0.004523     4.236:  41%|████      | 16/39 [00:32<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003498   0.04471  0.004559     4.221:  44%|████▎     | 17/39 [00:33<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003489   0.04461  0.004528      4.21:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003488   0.04435  0.004532      4.19:  49%|████▊     | 19/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640  0.003477    0.0442  0.004527     4.176:  51%|█████▏    | 20/39 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003467   0.04402  0.004493     4.158:  54%|█████▍    | 21/39 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003468   0.04397  0.004479     4.153:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003458   0.04389   0.00447     4.146:  59%|█████▉    | 23/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003449   0.04378  0.004474     4.137:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003444   0.04362  0.004461     4.122:  64%|██████▍   | 25/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640   0.00344   0.04358  0.004453     4.118:  67%|██████▋   | 26/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.534      0.421       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.595      0.388      0.409       0.23
                   0        738       1052      0.599      0.508      0.527      0.253
                   1        738         44      0.563     0.0883      0.222      0.104
                   2        738       8622      0.757      0.694      0.746      0.473
                   3        738        151      0.524      0.404      0.434      0.328
                   4        738        467        0.5      0.582      0.532      0.372
                   5        738         70      0.438      0.386      0.297      0.151
                   6        738         65      0.298     0.0615      0.167     0.0705
                   7        738       1619      0.597       0.58      0.579      0.238
                   8        738       2845       0.67       0.58       0.59      0.311
                   9        738          2          1          0   0.000298   0.000268

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:28:47.561123064 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31300 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round023_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round023_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client5_residential_night_stable_train' images and labels...4885 found, 2918 missing, 0 empty, 0 corrupted: 100%|██████████| 7803/7803 [00:00<00:00, 11548.45it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.319085173501577
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round023_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2918 missing, 0 empty, 0 corrupted: 100%|██████████| 7803/7803 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:29:03.501843152 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:29:03.568096994 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2210       640  0.003477   0.04745    0.0044     4.426:   2%|▎         | 1/40 [00:22<14:41, 22.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2010       640   0.00346   0.04676  0.004376     4.367:   5%|▌         | 2/40 [00:23<06:13,  9.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1860       640  0.003422   0.04577  0.004416     4.289:   8%|▊         | 3/40 [00:24<03:32,  5.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2089       640  0.003432   0.04459   0.00431     4.186:  10%|█         | 4/40 [00:25<02:17,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1740       640  0.003411   0.04311   0.00431     4.067:  12%|█▎        | 5/40 [00:25<01:33,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1811       640  0.003436   0.04222  0.004361     4.001:  15%|█▌        | 6/40 [00:26<01:08,  2.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2052       640  0.003455   0.04159   0.00447     3.961:  18%|█▊        | 7/40 [00:27<00:51,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2009       640   0.00347   0.04128  0.004472     3.938:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2340       640   0.00349   0.04153    0.0045     3.961:  22%|██▎       | 9/40 [00:28<00:33,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2005       640  0.003483   0.04106  0.004409     3.916:  25%|██▌       | 10/40 [00:29<00:28,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2215       640  0.003492   0.04077  0.004507     3.901:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1906       640  0.003487   0.04053   0.00457     3.887:  30%|███       | 12/40 [00:30<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2064       640  0.003491   0.04015  0.004573     3.857:  32%|███▎      | 13/40 [00:31<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1980       640   0.00349   0.03999  0.004576     3.844:  35%|███▌      | 14/40 [00:31<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1822       640  0.003485   0.03953  0.004591     3.809:  38%|███▊      | 15/40 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1899       640  0.003478   0.03912  0.004559     3.773:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2154       640  0.003487   0.03906  0.004536     3.767:  42%|████▎     | 17/40 [00:33<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1955       640  0.003479   0.03884    0.0045     3.746:  45%|████▌     | 18/40 [00:34<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1535       640  0.003476   0.03837  0.004499     3.707:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1886       640  0.003481   0.03821  0.004488     3.694:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2105       640  0.003484   0.03824  0.004502     3.698:  52%|█████▎    | 21/40 [00:36<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1676       640  0.003484   0.03795  0.004498     3.674:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1990       640  0.003483   0.03781  0.004501     3.663:  57%|█████▊    | 23/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1771       640  0.003476   0.03752  0.004496     3.639:  60%|██████    | 24/40 [00:38<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1769       640  0.003475   0.03726  0.004501     3.619:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1715       640  0.003472   0.03705  0.004512     3.603:  65%|██████▌   | 26/40 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.603      0.395       0.41      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.594      0.396      0.409      0.229
                   0        738       1052      0.593      0.506      0.522      0.251
                   1        738         44      0.613       0.18      0.252      0.111
                   2        738       8622      0.723      0.703      0.742      0.473
                   3        738        151      0.589      0.404      0.427      0.322
                   4        738        467      0.499      0.561      0.536      0.377
                   5        738         70      0.402      0.384      0.283      0.146
                   6        738         65      0.254     0.0615      0.157     0.0673
                   7        738       1619      0.601      0.585      0.579      0.237
                   8        738       2845      0.666      0.575      0.586       0.31
                   9        738          2          1          0   0.000444     0.0004

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:30:30.389893693 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31301 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round023_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round023_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:30:47.906967894 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:30:47.925926538 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03111   0.03607  0.003654     5.667:   3%|▎         | 1/31 [00:33<16:37, 33.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.03043   0.03421  0.003491     5.451:   6%|▋         | 2/31 [00:34<06:50, 14.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.02952   0.03249  0.003371     5.231:  10%|▉         | 3/31 [00:34<03:46,  8.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.02902   0.03113  0.003176     5.066:  13%|█▎        | 4/31 [00:35<02:19,  5.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.02879   0.03091  0.003162     5.029:  16%|█▌        | 5/31 [00:36<01:31,  3.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.02878   0.03059  0.003184     5.004:  19%|█▉        | 6/31 [00:36<01:03,  2.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.02884   0.03028  0.003243     4.989:  23%|██▎       | 7/31 [00:37<00:45,  1.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.02869   0.03022  0.003244     4.972:  26%|██▌       | 8/31 [00:37<00:33,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.02873   0.03009  0.003172     4.959:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.02872   0.03014   0.00314     4.959:  32%|███▏      | 10/31 [00:39<00:21,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.02866    0.0301  0.003146     4.953:  35%|███▌      | 11/31 [00:39<00:17,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.02856   0.02982  0.003136     4.922:  39%|███▊      | 12/31 [00:40<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.02853   0.02976  0.003092      4.91:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.02854   0.02963  0.003067     4.899:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.02855   0.02951  0.003113     4.894:  48%|████▊     | 15/31 [00:42<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.02856   0.02937  0.003117     4.884:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.02858   0.02937  0.003097     4.884:  55%|█████▍    | 17/31 [00:43<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.02867   0.02948  0.003073     4.898:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.02864   0.02938  0.003057     4.886:  61%|██████▏   | 19/31 [00:44<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.02866   0.02957  0.003055     4.903:  65%|██████▍   | 20/31 [00:44<00:06,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.02871   0.02962  0.003076     4.913:  68%|██████▊   | 21/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.02874   0.02973   0.00306     4.922:  71%|███████   | 22/31 [00:46<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.02875   0.02979  0.003037     4.927:  74%|███████▍  | 23/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640    0.0288   0.02993   0.00303     4.941:  77%|███████▋  | 24/31 [00:47<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.02883   0.02993  0.003033     4.944:  81%|████████  | 25/31 [00:47<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.02892   0.03003  0.003041     4.959:  84%|████████▍ | 26/31 [00:48<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.543      0.412      0.403      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.528      0.415      0.401      0.222
                   0        738       1052      0.509      0.528      0.507      0.242
                   1        738         44      0.393      0.159       0.21     0.0838
                   2        738       8622      0.685      0.722      0.742      0.476
                   3        738        151      0.463      0.427      0.431      0.322
                   4        738        467      0.478       0.58      0.521      0.363
                   5        738         70      0.334      0.429      0.312      0.139
                   6        738         65      0.266      0.108      0.157     0.0653
                   7        738       1619      0.552      0.606      0.569      0.232
                   8        738       2845      0.601      0.588      0.563      0.294
                   9        738          2          1          0   0.000503   0.000452

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round023_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 19:32:27.501160254 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round024 phase_round=24 ===

02 head-to-full DQA:  72%|███████▏  | 23/32 [5:25:08<2:06:36, 844.08s/round, elapsed=5h25m08s, eta=2h07m13s, phase=phase1_head, round=23]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round024 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round024 client0_highway_day: pseudo scan 250/1500 images, kept 2361 boxes
round024 client0_highway_day: pseudo scan 500/1500 images, kept 4786 boxes
round024 client0_highway_day: pseudo scan 750/1500 images, kept 7113 boxes
round024 client0_highway_day: pseudo scan 1000/1500 images, kept 9476 boxes
round024 client0_highway_day: pseudo scan 1250/1500 images, kept 11806 boxes
round024 client0_highway_day: pseudo scan 1500/1500 images, kept 14186 boxes
{
  "round": "round024",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round023_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 11198,
  "boxes_per_kept_image": 7.515436241610738,
  "mean_conf": 0.8342979674755324,
  "mean_stability": 0.9446964593130811,
  "mean_score": 0.7915126860861155,
  "class_counts": {
    "0": 163,
    "2": 6384,
    "3": 122,
    "4": 566,
    "5": 5,
    "7": 562,
    "8": 3396
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_client0_highway_day_stable_boxes.csv"
}
round024 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round024 client1_highway_night: pseudo scan 250/1500 images, kept 1486 boxes
round024 client1_highway_night: pseudo scan 500/1500 images, kept 3082 boxes
round024 client1_highway_night: pseudo scan 750/1500 images, kept 4711 boxes
round024 client1_highway_night: pseudo scan 1000/1500 images, kept 6262 boxes
round024 client1_highway_night: pseudo scan 1250/1500 images, kept 7835 boxes
round024 client1_highway_night: pseudo scan 1500/1500 images, kept 9347 boxes
{
  "round": "round024",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round023_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1435,
  "pseudo_boxes_kept": 7808,
  "boxes_per_kept_image": 5.441114982578397,
  "mean_conf": 0.7530342034774176,
  "mean_stability": 0.9247404751291529,
  "mean_score": 0.7006109256591353,
  "class_counts": {
    "0": 68,
    "2": 4207,
    "3": 25,
    "4": 146,
    "5": 7,
    "7": 650,
    "8": 2705
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_client1_highway_night_stable_boxes.csv"
}
round024 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round024 client2_citystreet_day: pseudo scan 250/1500 images, kept 2683 boxes
round024 client2_citystreet_day: pseudo scan 500/1500 images, kept 5414 boxes
round024 client2_citystreet_day: pseudo scan 750/1500 images, kept 8145 boxes
round024 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10885 boxes
round024 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13579 boxes
round024 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16242 boxes
{
  "round": "round024",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round023_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13775,
  "boxes_per_kept_image": 9.207887700534759,
  "mean_conf": 0.834313583789417,
  "mean_stability": 0.9422846746141811,
  "mean_score": 0.789664906934017,
  "class_counts": {
    "0": 1497,
    "2": 7309,
    "3": 211,
    "4": 596,
    "5": 67,
    "7": 1497,
    "8": 2598
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_client2_citystreet_day_stable_boxes.csv"
}
round024 client3_citystreet_night: pseudo scan 1/1500 images, kept 7 boxes
round024 client3_citystreet_night: pseudo scan 250/1500 images, kept 2212 boxes
round024 client3_citystreet_night: pseudo scan 500/1500 images, kept 4417 boxes
round024 client3_citystreet_night: pseudo scan 750/1500 images, kept 6595 boxes
round024 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8693 boxes
round024 client3_citystreet_night: pseudo scan 1250/1500 images, kept 11017 boxes
round024 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13200 boxes
{
  "round": "round024",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round023_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1473,
  "pseudo_boxes_kept": 11302,
  "boxes_per_kept_image": 7.6727766463000675,
  "mean_conf": 0.7442222758824373,
  "mean_stability": 0.9185685398483293,
  "mean_score": 0.6883502729507572,
  "class_counts": {
    "0": 551,
    "2": 5940,
    "3": 62,
    "4": 154,
    "5": 34,
    "7": 2117,
    "8": 2444
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_client3_citystreet_night_stable_boxes.csv"
}
round024 client4_residential_day: pseudo scan 1/1500 images, kept 9 boxes
round024 client4_residential_day: pseudo scan 250/1500 images, kept 2572 boxes
round024 client4_residential_day: pseudo scan 500/1500 images, kept 5159 boxes
round024 client4_residential_day: pseudo scan 750/1500 images, kept 7695 boxes
round024 client4_residential_day: pseudo scan 1000/1500 images, kept 10154 boxes
round024 client4_residential_day: pseudo scan 1250/1500 images, kept 12667 boxes
round024 client4_residential_day: pseudo scan 1500/1500 images, kept 15123 boxes
{
  "round": "round024",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round023_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1489,
  "pseudo_boxes_kept": 9918,
  "boxes_per_kept_image": 6.660846205507052,
  "mean_conf": 0.8656614097971473,
  "mean_stability": 0.9517332308593838,
  "mean_score": 0.8273238814563642,
  "class_counts": {
    "0": 403,
    "2": 6806,
    "3": 68,
    "4": 314,
    "5": 45,
    "7": 549,
    "8": 1733
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_client4_residential_day_stable_boxes.csv"
}
round024 client5_residential_night: pseudo scan 1/1500 images, kept 6 boxes
round024 client5_residential_night: pseudo scan 250/1500 images, kept 2120 boxes
round024 client5_residential_night: pseudo scan 500/1500 images, kept 4210 boxes
round024 client5_residential_night: pseudo scan 750/1500 images, kept 6305 boxes
round024 client5_residential_night: pseudo scan 1000/1500 images, kept 8441 boxes
round024 client5_residential_night: pseudo scan 1250/1500 images, kept 10582 boxes
round024 client5_residential_night: pseudo scan 1500/1500 images, kept 12709 boxes
{
  "round": "round024",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round023_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1459,
  "pseudo_boxes_kept": 7988,
  "boxes_per_kept_image": 5.474982864976011,
  "mean_conf": 0.8037092641413839,
  "mean_stability": 0.935012937218891,
  "mean_score": 0.7548350679808398,
  "class_counts": {
    "0": 124,
    "2": 5720,
    "3": 30,
    "4": 92,
    "5": 21,
    "7": 687,
    "8": 1314
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round024_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31302 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round024_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round024_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7861 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client0_highway_day_stable_train' images and labels...5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 22956.09it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007

world_size: 2
rank: 0
world_size: 2
rank: 1

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:34:41.139349091 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:34:41.195996773 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1955       640  0.003491   0.04809  0.005334     4.553:   3%|▎         | 1/39 [00:21<13:28, 21.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2076       640  0.003466   0.04792  0.004579     4.478:   5%|▌         | 2/39 [00:22<05:43,  9.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003461   0.04691  0.004671     4.403:   8%|▊         | 3/39 [00:23<03:16,  5.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1743       640  0.003445   0.04616  0.004609     4.337:  10%|█         | 4/39 [00:23<02:07,  3.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003445     0.046  0.004639     4.327:  13%|█▎        | 5/39 [00:24<01:27,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003446   0.04499    0.0045     4.235:  15%|█▌        | 6/39 [00:25<01:03,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640  0.003445    0.0446  0.004418     4.197:  18%|█▊        | 7/39 [00:25<00:47,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640   0.00345   0.04442  0.004408     4.182:  21%|██        | 8/39 [00:26<00:38,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2064       640  0.003456   0.04452  0.004457     4.194:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640   0.00347   0.04454  0.004481     4.199:  26%|██▌       | 10/39 [00:27<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003473   0.04419  0.004474     4.171:  28%|██▊       | 11/39 [00:28<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640   0.00348   0.04424  0.004573     4.183:  31%|███       | 12/39 [00:29<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2146       640  0.003476   0.04407  0.004602     4.172:  33%|███▎      | 13/39 [00:29<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640  0.003478   0.04409  0.004552      4.17:  36%|███▌      | 14/39 [00:30<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003481   0.04385  0.004523     4.149:  38%|███▊      | 15/39 [00:30<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003482   0.04367  0.004506     4.133:  41%|████      | 16/39 [00:31<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003484    0.0436  0.004531     4.129:  44%|████▎     | 17/39 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2205       640  0.003484   0.04344   0.00449     4.114:  46%|████▌     | 18/39 [00:32<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003485    0.0431  0.004511     4.087:  49%|████▊     | 19/39 [00:33<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2122       640  0.003482   0.04304  0.004477      4.08:  51%|█████▏    | 20/39 [00:34<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2158       640  0.003483   0.04307  0.004459     4.081:  54%|█████▍    | 21/39 [00:34<00:11,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003487   0.04304  0.004442     4.078:  56%|█████▋    | 22/39 [00:35<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003478   0.04289  0.004419     4.063:  59%|█████▉    | 23/39 [00:35<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003478   0.04291  0.004396     4.063:  62%|██████▏   | 24/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003476    0.0428  0.004415     4.055:  64%|██████▍   | 25/39 [00:37<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003476   0.04271  0.004391     4.046:  67%|██████▋   | 26/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.601      0.393      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937       0.59      0.395       0.41       0.23
                   0        738       1052      0.559      0.525      0.526      0.254
                   1        738         44      0.554       0.17      0.235      0.109
                   2        738       8622      0.746      0.704      0.749      0.476
                   3        738        151      0.593      0.397      0.428       0.32
                   4        738        467      0.502      0.559      0.538      0.383
                   5        738         70      0.393      0.386      0.281      0.137
                   6        738         65      0.273     0.0615       0.17     0.0722
                   7        738       1619      0.589      0.592      0.585       0.24
                   8        738       2845      0.692      0.553      0.586      0.308
                   9        738          2          1          0   0.000493   0.000444

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:36:05.328100724 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31303 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round024_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round024_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client1_highway_night_stable_train' images and labels...4895 found, 2856 missing, 0 empty, 0 corrupted: 100%|██████████| 7751/7751 [00:00<00:00, 11125.94it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.394357267395783
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2856 missing, 0 empty, 0 corrupted: 100%|██████████| 7751/7751 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:36:21.320647008 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:36:21.329427706 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1982       640  0.003339   0.04352  0.003825     4.055:   2%|▎         | 1/40 [00:22<14:23, 22.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2087       640  0.003379   0.04318   0.00432      4.07:   5%|▌         | 2/40 [00:23<06:06,  9.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1878       640  0.003394   0.04209   0.00435     3.987:   8%|▊         | 3/40 [00:23<03:28,  5.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1821       640  0.003412   0.04123  0.004508     3.932:  10%|█         | 4/40 [00:24<02:15,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2113       640  0.003443   0.04104  0.004476     3.917:  12%|█▎        | 5/40 [00:25<01:32,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003432   0.04027  0.004504     3.856:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1972       640  0.003446   0.04013  0.004557     3.851:  18%|█▊        | 7/40 [00:26<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2107       640  0.003452   0.04014  0.004508     3.848:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1795       640  0.003454   0.03971  0.004501     3.813:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1854       640  0.003461   0.03951  0.004519       3.8:  25%|██▌       | 10/40 [00:28<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2052       640  0.003461   0.03922   0.00457      3.78:  28%|██▊       | 11/40 [00:29<00:25,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1711       640  0.003467   0.03863  0.004541     3.731:  30%|███       | 12/40 [00:30<00:22,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2183       640  0.003481   0.03873  0.004551     3.741:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003475   0.03859  0.004536     3.728:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1719       640  0.003463   0.03817  0.004539     3.694:  38%|███▊      | 15/40 [00:32<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003469   0.03814  0.004542     3.692:  40%|████      | 16/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003471   0.03787  0.004535      3.67:  42%|████▎     | 17/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003469   0.03779  0.004541     3.664:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1613       640  0.003468   0.03743  0.004574     3.638:  48%|████▊     | 19/40 [00:34<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1902       640  0.003463   0.03728  0.004566     3.625:  50%|█████     | 20/40 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2046       640  0.003458   0.03712   0.00459     3.614:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640   0.00346   0.03696  0.004597     3.602:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1812       640  0.003452   0.03679  0.004565     3.585:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2029       640  0.003456   0.03675  0.004575     3.582:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1813       640  0.003454   0.03657  0.004574     3.568:  62%|██████▎   | 25/40 [00:38<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1967       640  0.003451    0.0364  0.004559     3.553:  65%|██████▌   | 26/40 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.576      0.404       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.605      0.388      0.407      0.229
                   0        738       1052      0.594      0.513      0.527      0.253
                   1        738         44      0.635      0.158      0.244      0.112
                   2        738       8622      0.733      0.704      0.745      0.477
                   3        738        151      0.605      0.377      0.418      0.317
                   4        738        467      0.514      0.546      0.523      0.374
                   5        738         70      0.378      0.371      0.279      0.144
                   6        738         65      0.319     0.0615      0.171      0.072
                   7        738       1619      0.595       0.59       0.58      0.237
                   8        738       2845      0.676       0.56      0.586      0.307
                   9        738          2          1          0   0.000564   0.000508

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:37:45.691707199 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31304 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round024_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round024_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 12802.33it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:38:00.818198604 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:38:00.924641574 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003578   0.05526  0.004598     5.075:   3%|▎         | 1/39 [00:22<14:00, 22.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003525   0.05404  0.004924     4.999:   5%|▌         | 2/39 [00:23<05:56,  9.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003493   0.05255  0.004914     4.877:   8%|▊         | 3/39 [00:23<03:23,  5.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003502   0.05108  0.004842     4.754:  10%|█         | 4/39 [00:24<02:11,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2141       640  0.003499   0.05051   0.00476     4.701:  13%|█▎        | 5/39 [00:25<01:30,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1783       640  0.003471   0.04931  0.004733     4.601:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640   0.00348   0.04886   0.00478      4.57:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003469   0.04832  0.004734     4.522:  21%|██        | 8/39 [00:27<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003481   0.04819  0.004655     4.506:  23%|██▎       | 9/39 [00:28<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003468    0.0478  0.004647     4.473:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003472   0.04757  0.004646     4.455:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003476   0.04702  0.004656     4.412:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003482   0.04676  0.004612     4.388:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640   0.00349   0.04675  0.004571     4.385:  36%|███▌      | 14/39 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003491   0.04654  0.004545     4.366:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1922       640  0.003482    0.0462  0.004535     4.337:  41%|████      | 16/39 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1503       640  0.003473   0.04589  0.004565     4.314:  44%|████▎     | 17/39 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003465   0.04575  0.004548     4.301:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1728       640  0.003466   0.04542  0.004529     4.273:  49%|████▊     | 19/39 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640   0.00346   0.04536  0.004523     4.268:  51%|█████▏    | 20/39 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1837       640  0.003451   0.04516  0.004502     4.249:  54%|█████▍    | 21/39 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1717       640  0.003446   0.04505  0.004493     4.239:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1826       640  0.003439   0.04489  0.004482     4.225:  59%|█████▉    | 23/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003435   0.04481  0.004473     4.218:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003431   0.04468  0.004461     4.206:  64%|██████▍   | 25/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003424   0.04461  0.004447     4.198:  67%|██████▋   | 26/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.57      0.402      0.407      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.558      0.405      0.405      0.228
                   0        738       1052      0.646      0.489      0.517      0.249
                   1        738         44      0.469       0.18      0.213     0.0967
                   2        738       8622      0.681      0.732       0.75      0.476
                   3        738        151       0.43      0.397      0.425      0.323
                   4        738        467      0.449        0.6      0.527      0.372
                   5        738         70      0.416      0.414      0.291       0.15
                   6        738         65      0.267     0.0615      0.164     0.0677
                   7        738       1619      0.581      0.592      0.579      0.236
                   8        738       2845      0.641      0.581      0.587       0.31
                   9        738          2          1          0   0.000348   0.000314

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:39:25.247838975 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31305 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round024_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round024_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client3_citystreet_night_stable_train' images and labels...4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<00:00, 13894.03it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.287738076499291
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2944 missing, 0 empty, 0 corrupted: 100%|██████████| 7827/7827 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:39:41.605332835 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:39:41.608771846 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1926       640  0.003561   0.04683  0.003847     4.339:   2%|▎         | 1/40 [00:21<13:59, 21.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1724       640  0.003506   0.04527  0.004753     4.282:   5%|▌         | 2/40 [00:22<05:56,  9.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1932       640  0.003467   0.04464  0.004546     4.212:   8%|▊         | 3/40 [00:23<03:23,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003429   0.04355    0.0044      4.11:  10%|█         | 4/40 [00:24<02:12,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1754       640  0.003413   0.04252  0.004529     4.037:  12%|█▎        | 5/40 [00:24<01:30,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1815       640  0.003415   0.04156  0.004472     3.956:  15%|█▌        | 6/40 [00:25<01:05,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2069       640  0.003423   0.04137  0.004449      3.94:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2118       640   0.00343   0.04151  0.004489     3.954:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003435   0.04131  0.004462     3.937:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1869       640  0.003446   0.04089  0.004479     3.905:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2039       640  0.003442   0.04049  0.004483     3.873:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1835       640  0.003448   0.04024  0.004478     3.853:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003448   0.03993  0.004485     3.829:  32%|███▎      | 13/40 [00:29<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003448      0.04  0.004484     3.834:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1800       640  0.003442   0.03957  0.004463     3.798:  38%|███▊      | 15/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1789       640  0.003431    0.0393  0.004415     3.772:  40%|████      | 16/40 [00:31<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003435   0.03886  0.004429     3.738:  42%|████▎     | 17/40 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1828       640  0.003435   0.03859  0.004423     3.716:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1676       640  0.003434   0.03826   0.00439     3.686:  48%|████▊     | 19/40 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2084       640  0.003435   0.03821  0.004382     3.682:  50%|█████     | 20/40 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003446   0.03806  0.004402     3.673:  52%|█████▎    | 21/40 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1880       640  0.003443   0.03807  0.004382     3.671:  55%|█████▌    | 22/40 [00:35<00:11,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2106       640  0.003443   0.03801  0.004384     3.667:  57%|█████▊    | 23/40 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2087       640  0.003444   0.03797  0.004405     3.666:  60%|██████    | 24/40 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003447   0.03794  0.004393     3.662:  62%|██████▎   | 25/40 [00:37<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1929       640  0.003444   0.03778   0.00439     3.649:  65%|██████▌   | 26/40 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.603      0.389      0.405      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.587      0.391      0.405      0.228
                   0        738       1052      0.602        0.5      0.518      0.248
                   1        738         44      0.536      0.157      0.229      0.103
                   2        738       8622      0.722      0.704      0.742      0.473
                   3        738        151      0.545      0.391      0.426       0.32
                   4        738        467      0.478       0.58      0.532      0.372
                   5        738         70      0.415      0.371      0.275      0.146
                   6        738         65      0.317     0.0615      0.173     0.0696
                   7        738       1619      0.583      0.585      0.568      0.236
                   8        738       2845      0.674      0.558      0.584      0.308
                   9        738          2          1          0   0.000485   0.000437

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:41:07.612313381 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31306 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round024_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round024_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client4_residential_day_stable_train' images and labels...:   0%|          | 0/7859 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client4_residential_day_stable_train' images and labels...5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<00:00, 9750.19it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:41:24.818152418 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:41:24.836202840 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1950       640  0.003537   0.05582  0.004698     5.124:   3%|▎         | 1/39 [00:21<13:42, 21.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003529   0.05351  0.004886     4.954:   5%|▌         | 2/39 [00:22<05:49,  9.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003504   0.05163  0.004907     4.803:   8%|▊         | 3/39 [00:23<03:18,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640   0.00352   0.05042  0.004782     4.698:  10%|█         | 4/39 [00:24<02:08,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2216       640  0.003519   0.04972  0.004724     4.637:  13%|█▎        | 5/39 [00:24<01:27,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003495   0.04853  0.004704     4.538:  15%|█▌        | 6/39 [00:25<01:03,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2137       640   0.00351   0.04813  0.004716     4.509:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003511   0.04747  0.004646      4.45:  21%|██        | 8/39 [00:26<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003504   0.04746  0.004586     4.444:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003495    0.0471    0.0046     4.415:  26%|██▌       | 10/39 [00:28<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003492   0.04659  0.004562     4.371:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003497   0.04621  0.004583     4.343:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003502    0.0459  0.004535     4.315:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003502   0.04567  0.004529     4.296:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003502   0.04537  0.004513     4.271:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003499   0.04504  0.004512     4.244:  41%|████      | 16/39 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003502   0.04481  0.004549     4.229:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003493   0.04471  0.004518     4.218:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003492   0.04445  0.004521     4.197:  49%|████▊     | 19/39 [00:33<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640  0.003481   0.04429  0.004517     4.183:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1799       640  0.003471   0.04411  0.004484     4.165:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003472   0.04405  0.004471      4.16:  56%|█████▋    | 22/39 [00:35<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003462   0.04398  0.004461     4.152:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003453   0.04387  0.004465     4.143:  62%|██████▏   | 24/39 [00:36<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003448    0.0437  0.004451     4.128:  64%|██████▍   | 25/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003443   0.04365  0.004444     4.123:  67%|██████▋   | 26/39 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.589      0.399      0.412       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.578      0.401       0.41       0.23
                   0        738       1052      0.571      0.516      0.525      0.252
                   1        738         44      0.621      0.159      0.239      0.111
                   2        738       8622      0.733      0.705      0.745      0.472
                   3        738        151      0.468      0.397      0.433      0.327
                   4        738        467       0.48      0.591      0.529      0.371
                   5        738         70      0.394        0.4       0.29      0.148
                   6        738         65      0.289     0.0615      0.172     0.0716
                   7        738       1619      0.576       0.59      0.577      0.238
                   8        738       2845       0.65      0.587      0.588      0.311
                   9        738          2          1          0   0.000306   0.000275

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:42:48.983654169 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31307 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round024_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round024_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client5_residential_night_stable_train' images and labels...4885 found, 2914 missing, 0 empty, 0 corrupted: 100%|██████████| 7799/7799 [00:00<00:00, 14528.36it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.323919217418744
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round024_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2914 missing, 0 empty, 0 corrupted: 100%|██████████| 7799/7799 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:43:04.217495047 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:43:04.223714892 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2048       640  0.003437   0.04392   0.00461     4.157:   2%|▎         | 1/40 [00:21<14:06, 21.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003416   0.04384  0.004491     4.139:   5%|▌         | 2/40 [00:22<05:59,  9.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1721       640  0.003385   0.04375  0.004433     4.126:   8%|▊         | 3/40 [00:23<03:24,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003384   0.04197  0.004521      3.99:  10%|█         | 4/40 [00:24<02:13,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1758       640  0.003388   0.04104   0.00467     3.928:  12%|█▎        | 5/40 [00:24<01:30,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003402   0.04056  0.004544      3.88:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2060       640  0.003422   0.04029   0.00455     3.861:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003432   0.04014  0.004671     3.859:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2196       640  0.003459   0.04026  0.004638     3.869:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1984       640  0.003461   0.03996  0.004556     3.838:  25%|██▌       | 10/40 [00:28<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2136       640  0.003468   0.03972  0.004553     3.819:  28%|██▊       | 11/40 [00:28<00:24,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003464   0.03933  0.004528     3.786:  30%|███       | 12/40 [00:29<00:21,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003463   0.03893  0.004526     3.754:  32%|███▎      | 13/40 [00:30<00:19,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2139       640  0.003464   0.03895  0.004529     3.756:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003457   0.03866  0.004533     3.732:  38%|███▊      | 15/40 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1700       640  0.003456   0.03821  0.004461      3.69:  40%|████      | 16/40 [00:31<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1962       640  0.003465   0.03804  0.004445     3.676:  42%|████▎     | 17/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003461   0.03783  0.004441     3.659:  45%|████▌     | 18/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1689       640  0.003457    0.0375  0.004459     3.633:  48%|████▊     | 19/40 [00:33<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2057       640   0.00346   0.03749  0.004456     3.632:  50%|█████     | 20/40 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2100       640   0.00346    0.0375  0.004456     3.633:  52%|█████▎    | 21/40 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1671       640  0.003464   0.03725  0.004455     3.613:  55%|█████▌    | 22/40 [00:35<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003463   0.03709  0.004481     3.602:  57%|█████▊    | 23/40 [00:36<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003465   0.03698  0.004487     3.594:  60%|██████    | 24/40 [00:37<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1723       640  0.003461   0.03675   0.00448     3.575:  62%|██████▎   | 25/40 [00:37<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1805       640  0.003458   0.03658  0.004485     3.562:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.571      0.408      0.408      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.561      0.409      0.407       0.23
                   0        738       1052      0.558      0.524       0.52      0.252
                   1        738         44      0.517      0.205       0.25      0.118
                   2        738       8622      0.693      0.716      0.743      0.474
                   3        738        151      0.526      0.397      0.423      0.324
                   4        738        467      0.474      0.585      0.536      0.378
                   5        738         70      0.348        0.4      0.278      0.141
                   6        738         65       0.26     0.0769       0.16     0.0665
                   7        738       1619      0.583      0.598      0.579      0.238
                   8        738       2845      0.652      0.589      0.583      0.308
                   9        738          2          1          0   0.000439   0.000395

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:44:30.006538909 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31308 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round024_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round024_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:44:48.494279342 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:44:48.496448193 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03047   0.03443  0.003489     5.471:   3%|▎         | 1/31 [00:32<16:10, 32.34s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03009   0.03339  0.003406     5.351:   6%|▋         | 2/31 [00:33<06:42, 13.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02928   0.03193  0.003313     5.162:  10%|▉         | 3/31 [00:34<03:41,  7.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02876   0.03057  0.003118     4.996:  13%|█▎        | 4/31 [00:34<02:17,  5.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02856   0.03035  0.003105     4.961:  16%|█▌        | 5/31 [00:35<01:29,  3.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02855   0.03004  0.003129     4.938:  19%|█▉        | 6/31 [00:35<01:01,  2.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02862   0.02974  0.003189     4.924:  23%|██▎       | 7/31 [00:36<00:44,  1.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02847   0.02968   0.00319     4.908:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02851   0.02957  0.003119     4.896:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640    0.0285   0.02962   0.00309     4.897:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02846   0.02959  0.003095     4.891:  35%|███▌      | 11/31 [00:38<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02836   0.02931  0.003086     4.861:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02834   0.02925  0.003043     4.851:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02835   0.02913  0.003017      4.84:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02837   0.02901  0.003063     4.835:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02837   0.02888  0.003069     4.825:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02839   0.02888  0.003049     4.826:  55%|█████▍    | 17/31 [00:42<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02849     0.029  0.003026     4.841:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02848    0.0289   0.00301     4.831:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640    0.0285   0.02909  0.003008     4.848:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02855   0.02915   0.00303     4.859:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02858   0.02925  0.003015     4.868:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02859   0.02932  0.002991     4.872:  74%|███████▍  | 23/31 [00:45<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02864   0.02945  0.002984     4.886:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02867   0.02946  0.002988      4.89:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02875   0.02956  0.002995     4.905:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.541      0.419      0.402       0.22
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.524      0.422        0.4      0.219
                   0        738       1052      0.496      0.533      0.507      0.241
                   1        738         44      0.441      0.205      0.207     0.0833
                   2        738       8622       0.68      0.727      0.743      0.475
                   3        738        151      0.446      0.437      0.431      0.321
                   4        738        467      0.469      0.587       0.52       0.36
                   5        738         70      0.315      0.414      0.306      0.131
                   6        738         65      0.253       0.12      0.157     0.0604
                   7        738       1619      0.548      0.607      0.566      0.232
                   8        738       2845      0.593      0.588      0.558      0.291
                   9        738          2          1          0    0.00051   0.000459

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round024_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 19:46:25.933739133 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round025 phase_round=25 ===

02 head-to-full DQA:  75%|███████▌  | 24/32 [5:39:07<1:52:19, 842.49s/round, elapsed=5h39m07s, eta=1h53m02s, phase=phase1_head, round=24]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round025 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round025 client0_highway_day: pseudo scan 250/1500 images, kept 2358 boxes
round025 client0_highway_day: pseudo scan 500/1500 images, kept 4772 boxes
round025 client0_highway_day: pseudo scan 750/1500 images, kept 7097 boxes
round025 client0_highway_day: pseudo scan 1000/1500 images, kept 9458 boxes
round025 client0_highway_day: pseudo scan 1250/1500 images, kept 11788 boxes
round025 client0_highway_day: pseudo scan 1500/1500 images, kept 14174 boxes
{
  "round": "round025",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round024_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 11188,
  "boxes_per_kept_image": 7.5087248322147655,
  "mean_conf": 0.8356188856941655,
  "mean_stability": 0.9437947190997001,
  "mean_score": 0.7920405136237221,
  "class_counts": {
    "0": 166,
    "2": 6379,
    "3": 116,
    "4": 566,
    "5": 7,
    "7": 554,
    "8": 3400
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_client0_highway_day_stable_boxes.csv"
}
round025 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round025 client1_highway_night: pseudo scan 250/1500 images, kept 1472 boxes
round025 client1_highway_night: pseudo scan 500/1500 images, kept 3038 boxes
round025 client1_highway_night: pseudo scan 750/1500 images, kept 4638 boxes
round025 client1_highway_night: pseudo scan 1000/1500 images, kept 6143 boxes
round025 client1_highway_night: pseudo scan 1250/1500 images, kept 7691 boxes
round025 client1_highway_night: pseudo scan 1500/1500 images, kept 9181 boxes
{
  "round": "round025",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round024_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1433,
  "pseudo_boxes_kept": 7686,
  "boxes_per_kept_image": 5.363572923935799,
  "mean_conf": 0.7563528846459807,
  "mean_stability": 0.9237929469373367,
  "mean_score": 0.7029608499685456,
  "class_counts": {
    "0": 68,
    "2": 4132,
    "3": 25,
    "4": 146,
    "5": 8,
    "7": 633,
    "8": 2674
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_client1_highway_night_stable_boxes.csv"
}
round025 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round025 client2_citystreet_day: pseudo scan 250/1500 images, kept 2677 boxes
round025 client2_citystreet_day: pseudo scan 500/1500 images, kept 5399 boxes
round025 client2_citystreet_day: pseudo scan 750/1500 images, kept 8123 boxes
round025 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10859 boxes
round025 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13553 boxes
round025 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16209 boxes
{
  "round": "round025",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round024_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13739,
  "boxes_per_kept_image": 9.189966555183947,
  "mean_conf": 0.8359087468000538,
  "mean_stability": 0.9415726757646518,
  "mean_score": 0.7906087152277631,
  "class_counts": {
    "0": 1498,
    "2": 7295,
    "3": 212,
    "4": 593,
    "5": 65,
    "7": 1492,
    "8": 2584
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_client2_citystreet_day_stable_boxes.csv"
}
round025 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round025 client3_citystreet_night: pseudo scan 250/1500 images, kept 2189 boxes
round025 client3_citystreet_night: pseudo scan 500/1500 images, kept 4374 boxes
round025 client3_citystreet_night: pseudo scan 750/1500 images, kept 6524 boxes
round025 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8595 boxes
round025 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10890 boxes
round025 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13058 boxes
{
  "round": "round025",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round024_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 11217,
  "boxes_per_kept_image": 7.620244565217392,
  "mean_conf": 0.745471154768284,
  "mean_stability": 0.9178454880622169,
  "mean_score": 0.6889201239423888,
  "class_counts": {
    "0": 556,
    "2": 5877,
    "3": 60,
    "4": 149,
    "5": 31,
    "7": 2118,
    "8": 2426
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_client3_citystreet_night_stable_boxes.csv"
}
round025 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round025 client4_residential_day: pseudo scan 250/1500 images, kept 2563 boxes
round025 client4_residential_day: pseudo scan 500/1500 images, kept 5145 boxes
round025 client4_residential_day: pseudo scan 750/1500 images, kept 7677 boxes
round025 client4_residential_day: pseudo scan 1000/1500 images, kept 10126 boxes
round025 client4_residential_day: pseudo scan 1250/1500 images, kept 12629 boxes
round025 client4_residential_day: pseudo scan 1500/1500 images, kept 15083 boxes
{
  "round": "round025",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round024_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1489,
  "pseudo_boxes_kept": 9883,
  "boxes_per_kept_image": 6.637340496977838,
  "mean_conf": 0.8670993243937525,
  "mean_stability": 0.9509738177637044,
  "mean_score": 0.8280607091919148,
  "class_counts": {
    "0": 407,
    "2": 6788,
    "3": 67,
    "4": 315,
    "5": 43,
    "7": 534,
    "8": 1729
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_client4_residential_day_stable_boxes.csv"
}
round025 client5_residential_night: pseudo scan 1/1500 images, kept 5 boxes
round025 client5_residential_night: pseudo scan 250/1500 images, kept 2075 boxes
round025 client5_residential_night: pseudo scan 500/1500 images, kept 4136 boxes
round025 client5_residential_night: pseudo scan 750/1500 images, kept 6194 boxes
round025 client5_residential_night: pseudo scan 1000/1500 images, kept 8294 boxes
round025 client5_residential_night: pseudo scan 1250/1500 images, kept 10404 boxes
round025 client5_residential_night: pseudo scan 1500/1500 images, kept 12499 boxes
{
  "round": "round025",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round024_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1454,
  "pseudo_boxes_kept": 7865,
  "boxes_per_kept_image": 5.409215955983494,
  "mean_conf": 0.8054183946509158,
  "mean_stability": 0.9338814735867306,
  "mean_score": 0.755585178356698,
  "class_counts": {
    "0": 127,
    "2": 5625,
    "3": 31,
    "4": 92,
    "5": 20,
    "7": 687,
    "8": 1283
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round025_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31309 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round025_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round025_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client0_highway_day_stable_train' images and labels...724 found, 1276 missing, 0 empty, 0 corrupted:  25%|██▌       | 2000/7861 [00:00<00:00, 18476.78it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client0_highway_day_stable_train' images and labels...5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 17142.90it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:48:41.827500155 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:48:41.838079460 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1955       640  0.003498   0.04834  0.005372     4.577:   3%|▎         | 1/39 [00:21<13:42, 21.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2076       640  0.003474   0.04811  0.004607     4.495:   5%|▌         | 2/39 [00:22<05:49,  9.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003468    0.0471  0.004701     4.422:   8%|▊         | 3/39 [00:23<03:19,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1743       640  0.003454   0.04634  0.004632     4.354:  10%|█         | 4/39 [00:24<02:09,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003454   0.04617  0.004656     4.343:  13%|█▎        | 5/39 [00:24<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003455   0.04515  0.004515      4.25:  15%|█▌        | 6/39 [00:25<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640  0.003453   0.04475  0.004429      4.21:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003458   0.04456  0.004416     4.195:  21%|██        | 8/39 [00:27<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2064       640  0.003464   0.04464  0.004465     4.206:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003478   0.04466  0.004488      4.21:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003481   0.04431  0.004483     4.182:  28%|██▊       | 11/39 [00:28<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003488   0.04434  0.004584     4.193:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2146       640  0.003484   0.04417   0.00461     4.181:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640  0.003485   0.04419  0.004562     4.179:  36%|███▌      | 14/39 [00:30<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003489   0.04395  0.004533     4.157:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003489   0.04376  0.004516     4.141:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003491   0.04368  0.004542     4.137:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2205       640  0.003492   0.04353    0.0045     4.122:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003492   0.04317   0.00452     4.095:  49%|████▊     | 19/39 [00:33<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2122       640  0.003489   0.04311  0.004485     4.087:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2158       640  0.003491   0.04314  0.004465     4.088:  54%|█████▍    | 21/39 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003494   0.04311  0.004449     4.084:  56%|█████▋    | 22/39 [00:35<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003485   0.04295  0.004425     4.069:  59%|█████▉    | 23/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003486   0.04298  0.004402     4.069:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003483   0.04286   0.00442     4.061:  64%|██████▍   | 25/39 [00:37<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003483   0.04277  0.004395     4.052:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.582      0.402      0.413       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.573      0.403       0.41       0.23
                   0        738       1052       0.54      0.536      0.528      0.253
                   1        738         44      0.562      0.204      0.241      0.107
                   2        738       8622      0.732      0.713      0.749      0.474
                   3        738        151      0.556      0.397      0.428      0.321
                   4        738        467      0.489      0.563      0.536      0.381
                   5        738         70      0.377        0.4      0.284      0.142
                   6        738         65      0.222     0.0615       0.17     0.0728
                   7        738       1619      0.577      0.599      0.583      0.239
                   8        738       2845      0.676      0.561      0.583      0.307
                   9        738          2          1          0   0.000513   0.000462

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:50:06.197593201 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31310 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round025_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round025_phase1_head_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client1_highway_night_stable_train' images and labels...4895 found, 2852 missing, 0 empty, 0 corrupted: 100%|██████████| 7747/7747 [00:00<00:00, 10015.01it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.399238940859362
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2852 missing, 0 empty, 0 corrupted: 100%|██████████| 7747/7747 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:50:23.707713810 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:50:23.728472590 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1931       640  0.003386   0.04441  0.004557     4.189:   2%|▎         | 1/40 [00:22<14:31, 22.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003405   0.04387  0.004748     4.162:   5%|▌         | 2/40 [00:23<06:10,  9.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003437   0.04342  0.004643      4.12:   8%|▊         | 3/40 [00:24<03:31,  5.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1891       640  0.003446   0.04271   0.00454     4.056:  10%|█         | 4/40 [00:25<02:17,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003444   0.04186  0.004538     3.987:  12%|█▎        | 5/40 [00:25<01:33,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1563       640  0.003453   0.04039   0.00468     3.881:  15%|█▌        | 6/40 [00:26<01:07,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2062       640  0.003467    0.0401  0.004699     3.861:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003471   0.03993  0.004742     3.851:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1908       640  0.003473   0.03943  0.004728     3.811:  22%|██▎       | 9/40 [00:28<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1841       640  0.003474     0.039  0.004629     3.769:  25%|██▌       | 10/40 [00:29<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2093       640  0.003464   0.03887  0.004607     3.756:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1934       640  0.003471   0.03848  0.004533     3.718:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1993       640  0.003475   0.03829  0.004568     3.707:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003479   0.03817  0.004596     3.699:  35%|███▌      | 14/40 [00:31<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1641       640  0.003471   0.03779  0.004581     3.667:  38%|███▊      | 15/40 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1908       640  0.003467   0.03758  0.004612     3.653:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1768       640   0.00347    0.0374  0.004612     3.638:  42%|████▎     | 17/40 [00:33<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003473   0.03731  0.004625     3.633:  45%|████▌     | 18/40 [00:34<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1613       640  0.003476   0.03692  0.004627     3.602:  48%|████▊     | 19/40 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003468   0.03695  0.004619     3.603:  50%|█████     | 20/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1994       640  0.003465   0.03685  0.004579     3.591:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003464   0.03674  0.004577     3.583:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1926       640  0.003458   0.03675   0.00456     3.582:  57%|█████▊    | 23/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2119       640   0.00346   0.03673  0.004574     3.581:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1815       640  0.003465   0.03656  0.004566     3.567:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640   0.00346   0.03634  0.004552     3.549:  65%|██████▌   | 26/40 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.599      0.399      0.411       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]

                 all        738      14937       0.59        0.4       0.41       0.23
                   0        738       1052      0.597      0.511      0.522      0.251
                   1        738         44      0.561      0.205      0.266      0.124
                   2        738       8622      0.729      0.706      0.745      0.476
                   3        738        151        0.6      0.391      0.424      0.322
                   4        738        467      0.505      0.548      0.527      0.374
                   5        738         70      0.371      0.414      0.284      0.139
                   6        738         65      0.267     0.0769      0.168     0.0702
                   7        738       1619      0.597      0.587      0.581      0.236
                   8        738       2845      0.673       0.56      0.581      0.305
                   9        738          2          1          0   0.000587   0.000528

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:51:48.808417395 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31311 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round025_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round025_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client2_citystreet_day_stable_train' images and labels...5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 17755.77it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:52:04.773490479 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:52:04.843562785 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1949       640  0.003465   0.05557  0.004563     5.088:   3%|▎         | 1/39 [00:22<14:27, 22.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003488   0.05607  0.004656     5.137:   5%|▌         | 2/39 [00:23<06:07,  9.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003468   0.05378  0.004574     4.945:   8%|▊         | 3/39 [00:24<03:27,  5.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003462   0.05195   0.00464     4.804:  10%|█         | 4/39 [00:25<02:13,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2180       640  0.003462   0.05125  0.004548     4.741:  13%|█▎        | 5/39 [00:26<01:30,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1564       640  0.003441   0.04922  0.004499     4.573:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003469   0.04902  0.004638      4.57:  18%|█▊        | 7/39 [00:27<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003457   0.04835  0.004609     4.513:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003467   0.04836  0.004524     4.508:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003455   0.04784  0.004505     4.464:  26%|██▌       | 10/39 [00:29<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003462   0.04757  0.004527     4.445:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003466   0.04712  0.004572     4.413:  31%|███       | 12/39 [00:30<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003476    0.0471  0.004542      4.41:  33%|███▎      | 13/39 [00:31<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003485   0.04696  0.004504     4.396:  36%|███▌      | 14/39 [00:31<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003487   0.04678  0.004515     4.383:  38%|███▊      | 15/39 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003491   0.04656  0.004514     4.365:  41%|████      | 16/39 [00:33<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003492   0.04645  0.004513     4.357:  44%|████▎     | 17/39 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003485   0.04636   0.00448     4.346:  46%|████▌     | 18/39 [00:34<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640  0.003482   0.04605  0.004444     4.318:  49%|████▊     | 19/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003481   0.04604  0.004457     4.318:  51%|█████▏    | 20/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640  0.003473   0.04588  0.004422     4.302:  54%|█████▍    | 21/39 [00:36<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003468   0.04592  0.004409     4.304:  56%|█████▋    | 22/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003467   0.04579  0.004422     4.294:  59%|█████▉    | 23/39 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003466   0.04581  0.004402     4.294:  62%|██████▏   | 24/39 [00:38<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2034       640  0.003464   0.04572  0.004387     4.286:  64%|██████▍   | 25/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003463   0.04563  0.004404      4.28:  67%|██████▋   | 26/39 [00:39<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.561      0.409      0.408      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.549       0.41      0.406      0.228
                   0        738       1052      0.642      0.493      0.518       0.25
                   1        738         44      0.467        0.2      0.214      0.105
                   2        738       8622      0.672      0.735      0.748      0.475
                   3        738        151      0.475      0.404      0.427      0.315
                   4        738        467      0.449      0.595      0.524      0.368
                   5        738         70      0.383      0.414      0.303      0.153
                   6        738         65      0.205     0.0615      0.165     0.0699
                   7        738       1619       0.57      0.602      0.577      0.237
                   8        738       2845      0.628      0.592      0.586      0.309
                   9        738          2          1          0   0.000342   0.000308

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client2_citystreet_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 19:53:31.757155434 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31312 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round025_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round025_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client3_citystreet_night_stable_train' images and labels...4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<00:00, 10326.00it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29014483627204
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:53:48.638457140 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:53:48.669406275 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1863       640  0.003598   0.04923   0.00467       4.6:   2%|▎         | 1/40 [00:22<14:36, 22.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1719       640  0.003482   0.04511  0.004765     4.268:   5%|▌         | 2/40 [00:23<06:12,  9.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003484   0.04501  0.004445     4.235:   8%|▊         | 3/40 [00:24<03:31,  5.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003478   0.04429  0.004282     4.164:  10%|█         | 4/40 [00:25<02:16,  3.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003465   0.04377  0.004214     4.116:  12%|█▎        | 5/40 [00:25<01:33,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1671       640  0.003449   0.04214   0.00424     3.986:  15%|█▌        | 6/40 [00:26<01:07,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1688       640  0.003436   0.04116  0.004255     3.908:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003433   0.04081  0.004191     3.875:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003435   0.04086  0.004149     3.876:  22%|██▎       | 9/40 [00:28<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003449   0.04067  0.004164     3.863:  25%|██▌       | 10/40 [00:29<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003452   0.04039  0.004251     3.847:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003459   0.04001  0.004213     3.815:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003451   0.03973  0.004221     3.792:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2007       640  0.003449   0.03954  0.004256      3.78:  35%|███▌      | 14/40 [00:31<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003445   0.03934  0.004258     3.764:  38%|███▊      | 15/40 [00:32<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1855       640  0.003444   0.03912  0.004238     3.744:  40%|████      | 16/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1703       640  0.003449   0.03884  0.004304     3.727:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003444   0.03857   0.00434     3.708:  45%|████▌     | 18/40 [00:34<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1779       640  0.003446   0.03831  0.004309     3.685:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003451   0.03826  0.004335     3.684:  50%|█████     | 20/40 [00:35<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1819       640  0.003461   0.03808  0.004314     3.669:  52%|█████▎    | 21/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1936       640  0.003459   0.03804   0.00428     3.662:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2243       640  0.003459   0.03824  0.004286     3.679:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003462   0.03822  0.004329     3.681:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003462   0.03819  0.004324     3.678:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640   0.00346   0.03812  0.004316     3.672:  65%|██████▌   | 26/40 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.615      0.389      0.407      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.23it/s]

                 all        738      14937      0.605       0.39      0.406      0.228
                   0        738       1052      0.642       0.49      0.514      0.249
                   1        738         44      0.663      0.179      0.255      0.117
                   2        738       8622      0.718      0.704      0.742      0.472
                   3        738        151      0.578      0.391      0.423      0.319
                   4        738        467      0.485       0.58      0.532      0.373
                   5        738         70      0.419      0.371      0.282      0.141
                   6        738         65      0.272     0.0615      0.164     0.0704
                   7        738       1619      0.592      0.569      0.571      0.235
                   8        738       2845      0.682      0.555      0.579      0.306
                   9        738          2          1          0   0.000545    0.00049

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:55:14.446981888 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31313 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round025_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round025_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client4_residential_day_stable_train' images and labels...5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<00:00, 11301.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7859/7859 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:55:31.315044884 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 19:55:31.664457755 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1950       640  0.003542   0.05611   0.00469     5.147:   3%|▎         | 1/39 [00:22<14:24, 22.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2177       640  0.003536   0.05375  0.004873     4.973:   5%|▌         | 2/39 [00:24<06:14, 10.12s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2017       640  0.003512   0.05183  0.004901      4.82:   8%|▊         | 3/39 [00:24<03:33,  5.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1986       640  0.003528   0.05061  0.004791     4.714:  10%|█         | 4/39 [00:25<02:16,  3.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2216       640  0.003527   0.04989  0.004735     4.652:  13%|█▎        | 5/39 [00:26<01:33,  2.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1874       640  0.003503   0.04869  0.004715     4.553:  15%|█▌        | 6/39 [00:27<01:06,  2.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2137       640  0.003519   0.04828  0.004722     4.522:  18%|█▊        | 7/39 [00:27<00:50,  1.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2053       640  0.003519   0.04761  0.004654     4.463:  21%|██        | 8/39 [00:28<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2177       640  0.003512   0.04759  0.004595     4.455:  23%|██▎       | 9/39 [00:29<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1909       640  0.003503   0.04722  0.004605     4.426:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1872       640  0.003501   0.04671  0.004568     4.382:  28%|██▊       | 11/39 [00:30<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2094       640  0.003505   0.04633  0.004586     4.353:  31%|███       | 12/39 [00:30<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1949       640  0.003511   0.04601  0.004538     4.325:  33%|███▎      | 13/39 [00:31<00:18,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1963       640   0.00351   0.04577  0.004534     4.305:  36%|███▌      | 14/39 [00:32<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1884       640  0.003509   0.04547  0.004518      4.28:  38%|███▊      | 15/39 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1982       640  0.003507   0.04514  0.004517     4.253:  41%|████      | 16/39 [00:33<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1850       640   0.00351    0.0449  0.004553     4.237:  44%|████▎     | 17/39 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1964       640  0.003501    0.0448  0.004522     4.226:  46%|████▌     | 18/39 [00:34<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1844       640    0.0035   0.04453  0.004526     4.205:  49%|████▊     | 19/39 [00:35<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2047       640  0.003488   0.04437  0.004521      4.19:  51%|█████▏    | 20/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1799       640  0.003478   0.04419  0.004488     4.172:  54%|█████▍    | 21/39 [00:36<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1864       640  0.003479   0.04413  0.004474     4.167:  56%|█████▋    | 22/39 [00:37<00:10,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1841       640  0.003469   0.04405  0.004465     4.159:  59%|█████▉    | 23/39 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1890       640   0.00346   0.04394  0.004469     4.149:  62%|██████▏   | 24/39 [00:38<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1727       640  0.003455   0.04377  0.004454     4.134:  64%|██████▍   | 25/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1980       640   0.00345   0.04372  0.004446     4.129:  67%|██████▋   | 26/39 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.601      0.393       0.41       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.592      0.395      0.409       0.23
                   0        738       1052      0.588      0.505      0.524      0.253
                   1        738         44      0.636      0.159      0.237      0.111
                   2        738       8622      0.749      0.698      0.745      0.472
                   3        738        151      0.506      0.394      0.433      0.326
                   4        738        467      0.489      0.585      0.532      0.372
                   5        738         70      0.416      0.386      0.295      0.152
                   6        738         65      0.291     0.0615      0.165     0.0698
                   7        738       1619      0.588      0.581      0.576      0.237
                   8        738       2845      0.658      0.581      0.585      0.309
                   9        738          2          1          0   0.000319   0.000287

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client4_residential_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 19:56:58.920852433 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31314 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round025_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round025_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client5_residential_night_stable_train' images and labels...4885 found, 2904 missing, 0 empty, 0 corrupted: 100%|██████████| 7789/7789 [00:00<00:00, 13272.19it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.336017685141323
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round025_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2904 missing, 0 empty, 0 corrupted: 100%|██████████| 7789/7789 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:57:15.372143278 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:57:15.407933184 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.6G      1956       640  0.003448    0.0469  0.004983     4.426:   2%|▎         | 1/40 [00:22<14:32, 22.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1792       640   0.00346   0.04598  0.004561      4.32:   5%|▌         | 2/40 [00:23<06:10,  9.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1698       640  0.003456   0.04513   0.00433     4.233:   8%|▊         | 3/40 [00:24<03:30,  5.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1848       640  0.003463   0.04346  0.004299     4.097:  10%|█         | 4/40 [00:24<02:15,  3.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1874       640  0.003444     0.042  0.004245     3.975:  12%|█▎        | 5/40 [00:25<01:32,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1653       640  0.003437   0.04072  0.004245     3.872:  15%|█▌        | 6/40 [00:26<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2120       640  0.003463   0.04084  0.004372     3.894:  18%|█▊        | 7/40 [00:26<00:49,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1812       640  0.003462   0.04031  0.004411     3.855:  20%|██        | 8/40 [00:27<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2205       640  0.003466   0.04063  0.004391     3.879:  22%|██▎       | 9/40 [00:28<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1874       640  0.003461    0.0402  0.004361     3.842:  25%|██▌       | 10/40 [00:28<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2021       640  0.003456   0.03977  0.004347     3.806:  28%|██▊       | 11/40 [00:29<00:24,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2093       640  0.003447   0.03949  0.004361     3.784:  30%|███       | 12/40 [00:29<00:21,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2050       640  0.003453   0.03935  0.004377     3.775:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1894       640  0.003451   0.03916  0.004435     3.764:  35%|███▌      | 14/40 [00:31<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1940       640  0.003455   0.03885  0.004476     3.743:  38%|███▊      | 15/40 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1605       640   0.00345   0.03833  0.004455     3.699:  40%|████      | 16/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2220       640  0.003454   0.03836  0.004423     3.699:  42%|████▎     | 17/40 [00:33<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1800       640  0.003453   0.03803   0.00447     3.677:  45%|████▌     | 18/40 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1768       640  0.003457   0.03767  0.004465     3.647:  48%|████▊     | 19/40 [00:34<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2069       640  0.003464   0.03762  0.004477     3.644:  50%|█████     | 20/40 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1976       640  0.003463   0.03753  0.004488     3.639:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1844       640  0.003467   0.03739  0.004457     3.625:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1863       640  0.003468   0.03719  0.004451     3.609:  57%|█████▊    | 23/40 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      2026       640  0.003469   0.03711  0.004465     3.603:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1863       640  0.003466    0.0369  0.004461     3.586:  62%|██████▎   | 25/40 [00:38<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.3G      1844       640  0.003465    0.0368   0.00445     3.577:  65%|██████▌   | 26/40 [00:38<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.554      0.408      0.406      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.14it/s]

                 all        738      14937      0.548      0.409      0.405      0.229
                   0        738       1052       0.54      0.526       0.52       0.25
                   1        738         44      0.529      0.204      0.238      0.111
                   2        738       8622      0.689      0.716      0.742      0.472
                   3        738        151      0.498      0.391      0.422      0.321
                   4        738        467      0.468      0.582      0.537      0.378
                   5        738         70      0.317      0.386      0.274      0.146
                   6        738         65      0.254     0.0733      0.157     0.0646
                   7        738       1619      0.556      0.617      0.583      0.239
                   8        738       2845      0.628      0.594      0.579      0.306
                   9        738          2          1          0   0.000403   0.000363

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 19:58:41.487357327 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31315 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round025_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round025_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 19:58:59.368757658 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 19:58:59.412680877 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.03057   0.03452  0.003499     5.487:   3%|▎         | 1/31 [00:32<16:25, 32.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.03002   0.03317  0.003387     5.326:   6%|▋         | 2/31 [00:33<06:45, 13.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02927   0.03179  0.003299     5.148:  10%|▉         | 3/31 [00:34<03:42,  7.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640    0.0287   0.03032  0.003091     4.969:  13%|█▎        | 4/31 [00:35<02:18,  5.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02845   0.03007  0.003075     4.928:  16%|█▌        | 5/31 [00:35<01:30,  3.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02843   0.02973  0.003097       4.9:  19%|█▉        | 6/31 [00:36<01:02,  2.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02849   0.02941  0.003156     4.884:  23%|██▎       | 7/31 [00:36<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02834   0.02935  0.003157     4.867:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02839   0.02922  0.003087     4.856:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02837   0.02926  0.003055     4.855:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02832   0.02922  0.003059     4.848:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02822   0.02894  0.003049     4.817:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02819   0.02887  0.003006     4.805:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02819   0.02874  0.002981     4.793:  45%|████▌     | 14/31 [00:41<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640    0.0282   0.02861  0.003027     4.787:  48%|████▊     | 15/31 [00:41<00:10,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02819   0.02848  0.003032     4.776:  52%|█████▏    | 16/31 [00:42<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02821   0.02848  0.003013     4.777:  55%|█████▍    | 17/31 [00:42<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640    0.0283   0.02859  0.002989      4.79:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02827   0.02849  0.002974     4.778:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02828   0.02867  0.002973     4.794:  65%|██████▍   | 20/31 [00:44<00:06,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02833   0.02873  0.002994     4.804:  68%|██████▊   | 21/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02836   0.02883  0.002977     4.813:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02837   0.02889  0.002953     4.817:  74%|███████▍  | 23/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02842   0.02903  0.002947     4.831:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02845   0.02903  0.002949     4.835:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02853   0.02913  0.002957      4.85:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.516      0.425      0.398      0.218
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.533      0.404      0.396      0.218
                   0        738       1052      0.502      0.525      0.506       0.24
                   1        738         44      0.415      0.136      0.206     0.0788
                   2        738       8622        0.7      0.718      0.741      0.474
                   3        738        151      0.459      0.404      0.428      0.319
                   4        738        467      0.489      0.576      0.521      0.359
                   5        738         70      0.316        0.4      0.285       0.13
                   6        738         65      0.273      0.104      0.152     0.0599
                   7        738       1619      0.567      0.602      0.567       0.23
                   8        738       2845      0.607      0.578      0.555      0.288
                   9        738          2          1          0   0.000505   0.000454

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round025_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 20:00:38.083235163 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round026 phase_round=26 ===

02 head-to-full DQA:  78%|███████▊  | 25/32 [5:53:20<1:38:39, 845.65s/round, elapsed=5h53m20s, eta=1h38m56s, phase=phase1_head, round=25]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round026 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round026 client0_highway_day: pseudo scan 250/1500 images, kept 2354 boxes
round026 client0_highway_day: pseudo scan 500/1500 images, kept 4769 boxes
round026 client0_highway_day: pseudo scan 750/1500 images, kept 7092 boxes
round026 client0_highway_day: pseudo scan 1000/1500 images, kept 9441 boxes
round026 client0_highway_day: pseudo scan 1250/1500 images, kept 11770 boxes
round026 client0_highway_day: pseudo scan 1500/1500 images, kept 14157 boxes
{
  "round": "round026",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round025_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 11194,
  "boxes_per_kept_image": 7.512751677852349,
  "mean_conf": 0.8370372651143864,
  "mean_stability": 0.942983827895302,
  "mean_score": 0.7927112059286706,
  "class_counts": {
    "0": 165,
    "2": 6371,
    "3": 117,
    "4": 564,
    "5": 6,
    "7": 562,
    "8": 3409
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_client0_highway_day_stable_boxes.csv"
}
round026 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round026 client1_highway_night: pseudo scan 250/1500 images, kept 1482 boxes
round026 client1_highway_night: pseudo scan 500/1500 images, kept 3059 boxes
round026 client1_highway_night: pseudo scan 750/1500 images, kept 4686 boxes
round026 client1_highway_night: pseudo scan 1000/1500 images, kept 6212 boxes
round026 client1_highway_night: pseudo scan 1250/1500 images, kept 7784 boxes
round026 client1_highway_night: pseudo scan 1500/1500 images, kept 9277 boxes
{
  "round": "round026",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round025_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1433,
  "pseudo_boxes_kept": 7751,
  "boxes_per_kept_image": 5.408932309839497,
  "mean_conf": 0.757945038148502,
  "mean_stability": 0.9225173961607168,
  "mean_score": 0.7033730990122373,
  "class_counts": {
    "0": 67,
    "2": 4175,
    "3": 26,
    "4": 148,
    "5": 8,
    "7": 647,
    "8": 2680
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_client1_highway_night_stable_boxes.csv"
}
round026 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round026 client2_citystreet_day: pseudo scan 250/1500 images, kept 2679 boxes
round026 client2_citystreet_day: pseudo scan 500/1500 images, kept 5399 boxes
round026 client2_citystreet_day: pseudo scan 750/1500 images, kept 8135 boxes
round026 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10871 boxes
round026 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13563 boxes
round026 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16220 boxes
{
  "round": "round026",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round025_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13760,
  "boxes_per_kept_image": 9.197860962566844,
  "mean_conf": 0.8377768183798464,
  "mean_stability": 0.9409255769277035,
  "mean_score": 0.7918151241890531,
  "class_counts": {
    "0": 1509,
    "2": 7299,
    "3": 204,
    "4": 603,
    "5": 65,
    "7": 1510,
    "8": 2570
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_client2_citystreet_day_stable_boxes.csv"
}
round026 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round026 client3_citystreet_night: pseudo scan 250/1500 images, kept 2205 boxes
round026 client3_citystreet_night: pseudo scan 500/1500 images, kept 4388 boxes
round026 client3_citystreet_night: pseudo scan 750/1500 images, kept 6541 boxes
round026 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8619 boxes
round026 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10923 boxes
round026 client3_citystreet_night: pseudo scan 1500/1500 images, kept 13093 boxes
{
  "round": "round026",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round025_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 11199,
  "boxes_per_kept_image": 7.608016304347826,
  "mean_conf": 0.749475609211424,
  "mean_stability": 0.9170212598025389,
  "mean_score": 0.6920084185963118,
  "class_counts": {
    "0": 557,
    "2": 5892,
    "3": 62,
    "4": 151,
    "5": 32,
    "7": 2116,
    "8": 2389
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_client3_citystreet_night_stable_boxes.csv"
}
round026 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round026 client4_residential_day: pseudo scan 250/1500 images, kept 2573 boxes
round026 client4_residential_day: pseudo scan 500/1500 images, kept 5150 boxes
round026 client4_residential_day: pseudo scan 750/1500 images, kept 7676 boxes
round026 client4_residential_day: pseudo scan 1000/1500 images, kept 10127 boxes
round026 client4_residential_day: pseudo scan 1250/1500 images, kept 12634 boxes
round026 client4_residential_day: pseudo scan 1500/1500 images, kept 15085 boxes
{
  "round": "round026",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round025_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9886,
  "boxes_per_kept_image": 6.643817204301075,
  "mean_conf": 0.8685706281062685,
  "mean_stability": 0.9503250732526541,
  "mean_score": 0.8289166388097211,
  "class_counts": {
    "0": 406,
    "2": 6789,
    "3": 65,
    "4": 312,
    "5": 43,
    "7": 544,
    "8": 1727
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_client4_residential_day_stable_boxes.csv"
}
round026 client5_residential_night: pseudo scan 1/1500 images, kept 5 boxes
round026 client5_residential_night: pseudo scan 250/1500 images, kept 2073 boxes
round026 client5_residential_night: pseudo scan 500/1500 images, kept 4138 boxes
round026 client5_residential_night: pseudo scan 750/1500 images, kept 6197 boxes
round026 client5_residential_night: pseudo scan 1000/1500 images, kept 8302 boxes
round026 client5_residential_night: pseudo scan 1250/1500 images, kept 10410 boxes
round026 client5_residential_night: pseudo scan 1500/1500 images, kept 12503 boxes
{
  "round": "round026",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round025_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1455,
  "pseudo_boxes_kept": 7854,
  "boxes_per_kept_image": 5.397938144329897,
  "mean_conf": 0.8068468135627196,
  "mean_stability": 0.9327447574907264,
  "mean_score": 0.75603534582726,
  "class_counts": {
    "0": 124,
    "2": 5627,
    "3": 29,
    "4": 92,
    "5": 21,
    "7": 688,
    "8": 1273
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round026_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31316 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round026_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round026_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7861 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client0_highway_day_stable_train' images and labels...5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 14592.64it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 20:02:54.289657525 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 20:02:54.294293423 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1955       640  0.003501   0.04863  0.005376       4.6:   3%|▎         | 1/39 [00:21<13:37, 21.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2076       640  0.003478   0.04848  0.004605     4.525:   5%|▌         | 2/39 [00:22<05:47,  9.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2053       640  0.003474   0.04745    0.0047      4.45:   8%|▊         | 3/39 [00:23<03:17,  5.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1743       640   0.00346   0.04664  0.004637     4.379:  10%|█         | 4/39 [00:24<02:07,  3.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1886       640   0.00346   0.04644  0.004663     4.365:  13%|█▎        | 5/39 [00:24<01:27,  2.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1864       640  0.003461   0.04539  0.004519      4.27:  15%|█▌        | 6/39 [00:25<01:02,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2123       640  0.003459   0.04497   0.00443     4.229:  18%|█▊        | 7/39 [00:26<00:47,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2048       640  0.003464   0.04476  0.004417     4.211:  21%|██        | 8/39 [00:26<00:37,  1.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2064       640   0.00347   0.04483  0.004465     4.221:  23%|██▎       | 9/39 [00:27<00:31,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2048       640  0.003484   0.04484  0.004488     4.225:  26%|██▌       | 10/39 [00:27<00:26,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2015       640  0.003487   0.04448  0.004483     4.196:  28%|██▊       | 11/39 [00:28<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1957       640  0.003494    0.0445  0.004581     4.206:  31%|███       | 12/39 [00:29<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2146       640   0.00349   0.04432  0.004609     4.194:  33%|███▎      | 13/39 [00:29<00:18,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2126       640  0.003492   0.04434  0.004559     4.191:  36%|███▌      | 14/39 [00:30<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1945       640  0.003495   0.04409  0.004529     4.169:  38%|███▊      | 15/39 [00:31<00:16,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1998       640  0.003496    0.0439  0.004513     4.153:  41%|████      | 16/39 [00:31<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1881       640  0.003498   0.04382  0.004537     4.148:  44%|████▎     | 17/39 [00:32<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2205       640  0.003499   0.04366  0.004496     4.132:  46%|████▌     | 18/39 [00:32<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1766       640  0.003499    0.0433  0.004516     4.105:  49%|████▊     | 19/39 [00:33<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2122       640  0.003495   0.04323  0.004481     4.097:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2158       640  0.003497   0.04326  0.004462     4.098:  54%|█████▍    | 21/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2075       640  0.003501   0.04323  0.004445     4.094:  56%|█████▋    | 22/39 [00:35<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2025       640  0.003491   0.04307  0.004421     4.079:  59%|█████▉    | 23/39 [00:35<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2188       640  0.003492   0.04309  0.004399     4.079:  62%|██████▏   | 24/39 [00:36<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2005       640  0.003489   0.04297  0.004418     4.071:  64%|██████▍   | 25/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1933       640  0.003489   0.04289  0.004394     4.061:  67%|██████▋   | 26/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.599      0.394      0.411      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937       0.59      0.395      0.408      0.229
                   0        738       1052      0.559      0.525      0.526      0.252
                   1        738         44      0.568      0.182       0.23      0.104
                   2        738       8622      0.746      0.703      0.747      0.474
                   3        738        151      0.589      0.391      0.428      0.321
                   4        738        467       0.51      0.561      0.539      0.382
                   5        738         70      0.386      0.386      0.281       0.14
                   6        738         65      0.253     0.0615      0.167     0.0712
                   7        738       1619      0.594      0.589      0.582      0.238
                   8        738       2845      0.693      0.552      0.582      0.306
                   9        738          2          1          0   0.000527   0.000475

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client0_highway_day

1 epochs completed in 0.023 hours.
Destroying process group...
[rank0]:[W507 20:04:16.131124238 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31317 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round026_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round026_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client1_highway_night_stable_train' images and labels...4895 found, 2852 missing, 0 empty, 0 corrupted: 100%|██████████| 7747/7747 [00:00<00:00, 12513.15it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.399238940859362
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2852 missing, 0 empty, 0 corrupted: 100%|██████████| 7747/7747 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:04:33.617243487 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:04:33.624595462 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1929       640  0.003409    0.0445  0.004459      4.19:   2%|▎         | 1/40 [00:22<14:39, 22.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2068       640  0.003434   0.04422  0.004739     4.192:   5%|▌         | 2/40 [00:23<06:11,  9.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1939       640  0.003462   0.04359  0.004574      4.13:   8%|▊         | 3/40 [00:24<03:31,  5.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003465   0.04304  0.004495      4.08:  10%|█         | 4/40 [00:25<02:16,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003471   0.04237  0.004542     4.031:  12%|█▎        | 5/40 [00:25<01:33,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1518       640   0.00347   0.04067  0.004757     3.912:  15%|█▌        | 6/40 [00:26<01:07,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640   0.00348   0.04032  0.004728     3.883:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003476   0.04009  0.004745     3.865:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640   0.00348   0.03953  0.004722     3.818:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003481   0.03903  0.004628     3.771:  25%|██▌       | 10/40 [00:29<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2057       640  0.003471   0.03883  0.004616     3.753:  28%|██▊       | 11/40 [00:29<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1873       640  0.003477   0.03841  0.004573     3.717:  30%|███       | 12/40 [00:30<00:22,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003482   0.03819  0.004594     3.701:  32%|███▎      | 13/40 [00:31<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003487   0.03814  0.004616     3.699:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1575       640   0.00348   0.03768  0.004584     3.659:  38%|███▊      | 15/40 [00:32<00:17,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003479   0.03753  0.004621      3.65:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1840       640  0.003482   0.03746  0.004621     3.645:  42%|████▎     | 17/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2064       640  0.003485   0.03736  0.004648     3.639:  45%|████▌     | 18/40 [00:34<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1691       640  0.003489   0.03707  0.004622     3.614:  48%|████▊     | 19/40 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003482   0.03713   0.00463      3.62:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640   0.00348   0.03703  0.004581     3.607:  52%|█████▎    | 21/40 [00:36<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640   0.00348   0.03695  0.004581     3.601:  55%|█████▌    | 22/40 [00:36<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1942       640  0.003475   0.03698   0.00457     3.602:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2155       640  0.003478   0.03698  0.004584     3.603:  60%|██████    | 24/40 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003484    0.0368  0.004576     3.588:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640   0.00348    0.0366  0.004559     3.571:  65%|██████▌   | 26/40 [00:39<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.588      0.398      0.408      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.579      0.399      0.406      0.228
                   0        738       1052      0.585      0.516      0.521      0.251
                   1        738         44      0.512      0.182       0.26      0.119
                   2        738       8622      0.721      0.709      0.744      0.475
                   3        738        151      0.574      0.377      0.416      0.314
                   4        738        467        0.5      0.561      0.527      0.375
                   5        738         70      0.357        0.4      0.276      0.137
                   6        738         65      0.298     0.0916      0.168     0.0697
                   7        738       1619      0.583      0.587      0.574      0.236
                   8        738       2845      0.659       0.57      0.578      0.304
                   9        738          2          1          0    0.00059   0.000531

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:05:58.126209379 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31318 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round026_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round026_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 11280.76it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:06:15.418935012 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:06:15.768069328 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003582     0.056  0.004569     5.132:   3%|▎         | 1/39 [00:21<13:32, 21.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2187       640  0.003537   0.05451  0.004894     5.036:   5%|▌         | 2/39 [00:22<05:44,  9.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003505   0.05317  0.004909     4.926:   8%|▊         | 3/39 [00:23<03:16,  5.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003514   0.05177  0.004843      4.81:  10%|█         | 4/39 [00:23<02:07,  3.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2145       640  0.003512   0.05101  0.004755     4.742:  13%|█▎        | 5/39 [00:24<01:27,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003481   0.04974  0.004716     4.635:  15%|█▌        | 6/39 [00:25<01:03,  1.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1960       640  0.003492   0.04925  0.004756       4.6:  18%|█▊        | 7/39 [00:25<00:47,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003482   0.04869  0.004713     4.551:  21%|██        | 8/39 [00:26<00:38,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003496   0.04854  0.004649     4.535:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003483   0.04812   0.00464     4.499:  26%|██▌       | 10/39 [00:27<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003487   0.04788  0.004634      4.48:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003491   0.04728  0.004644     4.433:  31%|███       | 12/39 [00:29<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2094       640  0.003496   0.04701  0.004601     4.409:  33%|███▎      | 13/39 [00:29<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2134       640  0.003505   0.04693   0.00456     4.399:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003504   0.04668  0.004531     4.377:  38%|███▊      | 15/39 [00:31<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003495   0.04631  0.004521     4.346:  41%|████      | 16/39 [00:31<00:15,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1504       640  0.003487   0.04601  0.004554     4.324:  44%|████▎     | 17/39 [00:32<00:14,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1920       640  0.003479   0.04588  0.004537     4.312:  46%|████▌     | 18/39 [00:33<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1718       640  0.003479   0.04555  0.004519     4.284:  49%|████▊     | 19/39 [00:33<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2032       640  0.003474    0.0455  0.004512     4.279:  51%|█████▏    | 20/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003465   0.04528   0.00449     4.259:  54%|█████▍    | 21/39 [00:34<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003459   0.04516   0.00448     4.248:  56%|█████▋    | 22/39 [00:35<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1860       640  0.003451   0.04501  0.004479     4.236:  59%|█████▉    | 23/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1900       640  0.003447   0.04492  0.004467     4.227:  62%|██████▏   | 24/39 [00:36<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003442   0.04479  0.004465     4.216:  64%|██████▍   | 25/39 [00:37<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003436   0.04472  0.004451     4.209:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.584      0.399      0.407      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.574        0.4      0.405      0.227
                   0        738       1052      0.668      0.477      0.515      0.247
                   1        738         44      0.496      0.182      0.228      0.102
                   2        738       8622      0.695      0.727      0.749      0.474
                   3        738        151      0.481      0.404      0.426      0.322
                   4        738        467      0.453      0.589      0.528      0.372
                   5        738         70      0.427      0.404      0.289       0.14
                   6        738         65      0.289     0.0615      0.158     0.0678
                   7        738       1619      0.588      0.582      0.576      0.235
                   8        738       2845       0.65       0.57      0.583      0.308
                   9        738          2          1          0   0.000378    0.00034

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:07:39.694800671 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31319 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round026_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round026_phase1_head_client3_citystreet_night_start.pt

self imgsz: 640
self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client3_citystreet_night_stable_train' images and labels...4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<00:00, 8989.91it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29014483627204
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:07:56.538701124 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:07:56.568449833 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1893       640  0.003603   0.04927  0.004598     4.598:   2%|▎         | 1/40 [00:21<14:01, 21.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1728       640  0.003484   0.04546  0.004723     4.293:   5%|▌         | 2/40 [00:22<05:57,  9.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2022       640  0.003492   0.04532  0.004437      4.26:   8%|▊         | 3/40 [00:23<03:23,  5.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003486    0.0446  0.004276     4.189:  10%|█         | 4/40 [00:24<02:11,  3.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003478   0.04403  0.004196     4.136:  12%|█▎        | 5/40 [00:24<01:30,  2.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1652       640  0.003457   0.04232  0.004182     3.996:  15%|█▌        | 6/40 [00:25<01:05,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1767       640  0.003453   0.04144  0.004203     3.928:  18%|█▊        | 7/40 [00:26<00:49,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003449   0.04107  0.004147     3.893:  20%|██        | 8/40 [00:26<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003449   0.04099  0.004112     3.884:  22%|██▎       | 9/40 [00:27<00:32,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1985       640  0.003463   0.04078  0.004129      3.87:  25%|██▌       | 10/40 [00:28<00:27,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2041       640  0.003465    0.0405  0.004219     3.855:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1917       640  0.003469    0.0401  0.004177     3.819:  30%|███       | 12/40 [00:29<00:21,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1926       640   0.00346   0.03984  0.004185     3.799:  32%|███▎      | 13/40 [00:29<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003458   0.03969  0.004221     3.789:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003454   0.03949  0.004225     3.774:  38%|███▊      | 15/40 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1857       640  0.003452   0.03926  0.004208     3.754:  40%|████      | 16/40 [00:31<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1700       640  0.003459   0.03896  0.004282     3.736:  42%|████▎     | 17/40 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1917       640  0.003454   0.03873  0.004315     3.719:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1765       640  0.003457   0.03847   0.00429     3.697:  48%|████▊     | 19/40 [00:33<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003461   0.03842  0.004314     3.696:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1810       640  0.003471   0.03823  0.004292      3.68:  52%|█████▎    | 21/40 [00:34<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1979       640  0.003469   0.03823  0.004264     3.677:  55%|█████▌    | 22/40 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2286       640  0.003469   0.03842  0.004277     3.694:  57%|█████▊    | 23/40 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2044       640  0.003471   0.03839  0.004321     3.695:  60%|██████    | 24/40 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640  0.003472    0.0384   0.00431     3.695:  62%|██████▎   | 25/40 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1825       640  0.003469   0.03828  0.004302     3.684:  65%|██████▌   | 26/40 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.616      0.383      0.405      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.608      0.384      0.404      0.227
                   0        738       1052      0.638      0.476      0.514      0.248
                   1        738         44      0.624      0.159      0.252      0.115
                   2        738       8622      0.726        0.7      0.742      0.472
                   3        738        151      0.588      0.384      0.423      0.318
                   4        738        467      0.489      0.572      0.529      0.374
                   5        738         70      0.441      0.371      0.273      0.137
                   6        738         65      0.302     0.0615      0.166     0.0698
                   7        738       1619      0.596      0.565      0.567      0.235
                   8        738       2845      0.681      0.548      0.576      0.305
                   9        738          2          1          0   0.000572   0.000515

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:09:21.654663421 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31320 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round026_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round026_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client4_residential_day_stable_train' images and labels...5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<00:00, 10778.50it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:09:37.933691123 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:09:37.993694492 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.74G      1976       640  0.003586   0.05535  0.004668     5.088:   3%|▎         | 1/39 [00:23<14:48, 23.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640  0.003545   0.05514  0.004575     5.061:   5%|▌         | 2/39 [00:24<06:18, 10.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640   0.00351   0.05221  0.004646      4.83:   8%|▊         | 3/39 [00:25<03:33,  5.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640    0.0035   0.05062  0.004712     4.707:  10%|█         | 4/39 [00:26<02:17,  3.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2226       640   0.00349   0.05011  0.004663     4.661:  13%|█▎        | 5/39 [00:26<01:33,  2.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1721       640   0.00347   0.04841  0.004569     4.516:  15%|█▌        | 6/39 [00:27<01:06,  2.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2003       640  0.003494   0.04805  0.004634     4.494:  18%|█▊        | 7/39 [00:28<00:50,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640   0.00349    0.0475  0.004609     4.448:  21%|██        | 8/39 [00:28<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2107       640  0.003489   0.04738  0.004479     4.428:  23%|██▎       | 9/39 [00:29<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003485   0.04707  0.004551     4.409:  26%|██▌       | 10/39 [00:29<00:27,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003481   0.04649   0.00455     4.361:  28%|██▊       | 11/39 [00:30<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003479   0.04617  0.004568     4.337:  31%|███       | 12/39 [00:31<00:21,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2165       640  0.003491   0.04615  0.004509     4.332:  33%|███▎      | 13/39 [00:31<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003488   0.04577  0.004471     4.298:  36%|███▌      | 14/39 [00:32<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003494   0.04561  0.004478     4.286:  38%|███▊      | 15/39 [00:33<00:16,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003498   0.04532  0.004494     4.265:  41%|████      | 16/39 [00:33<00:15,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003496   0.04508  0.004513     4.247:  44%|████▎     | 17/39 [00:34<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003491   0.04484  0.004477     4.224:  46%|████▌     | 18/39 [00:35<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640  0.003487   0.04454  0.004447     4.198:  49%|████▊     | 19/39 [00:35<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003482   0.04452  0.004442     4.195:  51%|█████▏    | 20/39 [00:36<00:12,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003475   0.04433  0.004435     4.179:  54%|█████▍    | 21/39 [00:37<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003476   0.04438  0.004433     4.183:  56%|█████▋    | 22/39 [00:37<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003473   0.04431  0.004433     4.177:  59%|█████▉    | 23/39 [00:38<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003469   0.04424  0.004421      4.17:  62%|██████▏   | 24/39 [00:38<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003468   0.04413  0.004404      4.16:  64%|██████▍   | 25/39 [00:39<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1969       640  0.003463   0.04404  0.004419     4.154:  67%|██████▋   | 26/39 [00:40<00:08,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.604      0.386      0.408      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.596      0.387      0.408      0.227
                   0        738       1052      0.603        0.5      0.522       0.25
                   1        738         44      0.542      0.114      0.239      0.104
                   2        738       8622      0.749      0.694      0.741      0.469
                   3        738        151      0.561      0.397      0.429      0.323
                   4        738        467      0.493      0.578      0.529      0.369
                   5        738         70       0.45      0.371      0.289      0.144
                   6        738         65      0.292     0.0615      0.165     0.0686
                   7        738       1619      0.598      0.579      0.575      0.238
                   8        738       2845      0.674      0.576      0.586      0.309
                   9        738          2          1          0   0.000298   0.000268

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client4_residential_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 20:11:04.407061946 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31321 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round026_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round026_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client5_residential_night_stable_train' images and labels...4885 found, 2906 missing, 0 empty, 0 corrupted: 100%|██████████| 7791/7791 [00:00<00:00, 12868.29it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.333596463530155
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round026_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2906 missing, 0 empty, 0 corrupted: 100%|██████████| 7791/7791 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:11:20.707280039 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:11:20.708458798 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2179       640  0.003491    0.0477  0.005008     4.496:   2%|▎         | 1/40 [00:22<14:21, 22.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1944       640  0.003488   0.04635  0.004809     4.372:   5%|▌         | 2/40 [00:23<06:08,  9.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1888       640  0.003463   0.04549  0.004791     4.299:   8%|▊         | 3/40 [00:23<03:28,  5.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1842       640  0.003492   0.04428  0.004761     4.203:  10%|█         | 4/40 [00:24<02:14,  3.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003466   0.04327  0.004693     4.114:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1793       640  0.003475   0.04251  0.004767      4.06:  15%|█▌        | 6/40 [00:26<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2130       640   0.00348   0.04232  0.004608     4.033:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2007       640  0.003478   0.04187  0.004582     3.994:  20%|██        | 8/40 [00:27<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2166       640  0.003487   0.04176  0.004521     3.981:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1773       640   0.00347   0.04117  0.004445     3.927:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640  0.003484    0.0409  0.004435     3.905:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1990       640  0.003473   0.04057  0.004436     3.879:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1999       640  0.003473   0.04034  0.004414     3.858:  32%|███▎      | 13/40 [00:30<00:20,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2158       640  0.003472   0.04008  0.004413     3.837:  35%|███▌      | 14/40 [00:31<00:18,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1800       640  0.003468   0.03959  0.004394     3.796:  38%|███▊      | 15/40 [00:31<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1839       640  0.003476   0.03926  0.004389      3.77:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003476   0.03905  0.004367     3.752:  42%|████▎     | 17/40 [00:33<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2060       640  0.003475    0.0389  0.004374      3.74:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1581       640  0.003475    0.0385   0.00442     3.712:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2099       640  0.003476   0.03849  0.004444     3.713:  50%|█████     | 20/40 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640   0.00348    0.0384   0.00447     3.708:  52%|█████▎    | 21/40 [00:35<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1863       640  0.003481   0.03822  0.004439     3.691:  55%|█████▌    | 22/40 [00:36<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2029       640  0.003482   0.03813  0.004471     3.687:  57%|█████▊    | 23/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640  0.003478   0.03797  0.004498     3.676:  60%|██████    | 24/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640   0.00348   0.03786  0.004525     3.669:  62%|██████▎   | 25/40 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1827       640  0.003475   0.03767  0.004536     3.654:  65%|██████▌   | 26/40 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.584      0.401      0.407      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.30it/s]

                 all        738      14937      0.571      0.403      0.405      0.229
                   0        738       1052      0.578      0.511       0.52       0.25
                   1        738         44      0.521      0.182      0.231      0.109
                   2        738       8622      0.709      0.708      0.741      0.472
                   3        738        151      0.548      0.384      0.425      0.321
                   4        738        467      0.486       0.58      0.538       0.38
                   5        738         70       0.38      0.414      0.288      0.144
                   6        738         65      0.266     0.0726      0.154      0.067
                   7        738       1619      0.573      0.595      0.578      0.238
                   8        738       2845      0.654      0.579      0.578      0.306
                   9        738          2          1          0   0.000491   0.000442

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:12:45.606112100 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31322 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round026_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round026_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:13:01.116417206 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:13:01.136483291 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03062   0.03463  0.003499       5.5:   3%|▎         | 1/31 [00:32<16:19, 32.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.02999   0.03302  0.003356     5.309:   6%|▋         | 2/31 [00:33<06:42, 13.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.02928    0.0317  0.003275     5.141:  10%|▉         | 3/31 [00:34<03:40,  7.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.02864   0.03014  0.003061     4.948:  13%|█▎        | 4/31 [00:34<02:16,  5.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.02837   0.02984  0.003041     4.901:  16%|█▌        | 5/31 [00:35<01:29,  3.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.02833   0.02948  0.003062      4.87:  19%|█▉        | 6/31 [00:36<01:01,  2.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.02838   0.02914   0.00312     4.851:  23%|██▎       | 7/31 [00:36<00:44,  1.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.02822   0.02905  0.003121     4.831:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.02824   0.02892   0.00305     4.817:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.02822   0.02894  0.003019     4.815:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.02815   0.02889  0.003022     4.806:  35%|███▌      | 11/31 [00:38<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.02805   0.02861  0.003011     4.774:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640     0.028   0.02853  0.002968      4.76:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.02801    0.0284  0.002942     4.748:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.02802   0.02826  0.002987     4.742:  48%|████▊     | 15/31 [00:41<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.02803   0.02813  0.002995     4.732:  52%|█████▏    | 16/31 [00:41<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.02805   0.02813  0.002975     4.733:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.02814   0.02824  0.002952     4.747:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.02812   0.02814  0.002937     4.736:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.02814   0.02831  0.002936     4.751:  65%|██████▍   | 20/31 [00:44<00:06,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.02819   0.02836  0.002958      4.76:  68%|██████▊   | 21/31 [00:44<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.02822   0.02846  0.002939     4.769:  71%|███████   | 22/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.02824   0.02853  0.002914     4.774:  74%|███████▍  | 23/31 [00:46<00:04,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.02829   0.02866  0.002908     4.789:  77%|███████▋  | 24/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.02832   0.02867   0.00291     4.792:  81%|████████  | 25/31 [00:47<00:03,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640    0.0284   0.02876  0.002917     4.807:  84%|████████▍ | 26/31 [00:47<00:02,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.546      0.414      0.401      0.219
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.529      0.416      0.398      0.218
                   0        738       1052      0.489       0.53      0.504      0.238
                   1        738         44      0.472      0.205      0.218     0.0925
                   2        738       8622      0.689      0.723       0.74      0.473
                   3        738        151      0.453      0.424      0.432      0.319
                   4        738        467      0.476      0.578      0.517      0.358
                   5        738         70      0.311      0.414      0.302      0.125
                   6        738         65      0.246      0.108      0.161     0.0619
                   7        738       1619      0.558      0.599      0.561       0.23
                   8        738       2845        0.6      0.578      0.549      0.286
                   9        738          2          1          0   0.000517   0.000465

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round026_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 20:14:40.507693812 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round027 phase_round=27 ===

02 head-to-full DQA:  81%|████████▏ | 26/32 [6:07:22<1:24:26, 844.41s/round, elapsed=6h07m22s, eta=1h24m46s, phase=phase1_head, round=26]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round027 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round027 client0_highway_day: pseudo scan 250/1500 images, kept 2351 boxes
round027 client0_highway_day: pseudo scan 500/1500 images, kept 4759 boxes
round027 client0_highway_day: pseudo scan 750/1500 images, kept 7077 boxes
round027 client0_highway_day: pseudo scan 1000/1500 images, kept 9431 boxes
round027 client0_highway_day: pseudo scan 1250/1500 images, kept 11746 boxes
round027 client0_highway_day: pseudo scan 1500/1500 images, kept 14130 boxes
{
  "round": "round027",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round026_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 11138,
  "boxes_per_kept_image": 7.470154258886653,
  "mean_conf": 0.8404198339060792,
  "mean_stability": 0.9423309531732443,
  "mean_score": 0.7952942568971835,
  "class_counts": {
    "0": 161,
    "2": 6359,
    "3": 117,
    "4": 572,
    "5": 8,
    "7": 561,
    "8": 3360
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_client0_highway_day_stable_boxes.csv"
}
round027 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round027 client1_highway_night: pseudo scan 250/1500 images, kept 1462 boxes
round027 client1_highway_night: pseudo scan 500/1500 images, kept 3017 boxes
round027 client1_highway_night: pseudo scan 750/1500 images, kept 4607 boxes
round027 client1_highway_night: pseudo scan 1000/1500 images, kept 6090 boxes
round027 client1_highway_night: pseudo scan 1250/1500 images, kept 7631 boxes
round027 client1_highway_night: pseudo scan 1500/1500 images, kept 9110 boxes
{
  "round": "round027",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round026_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1432,
  "pseudo_boxes_kept": 7650,
  "boxes_per_kept_image": 5.342178770949721,
  "mean_conf": 0.7607279300339082,
  "mean_stability": 0.9214395688561832,
  "mean_score": 0.7052563027097114,
  "class_counts": {
    "0": 69,
    "2": 4100,
    "3": 25,
    "4": 150,
    "5": 8,
    "7": 644,
    "8": 2654
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_client1_highway_night_stable_boxes.csv"
}
round027 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round027 client2_citystreet_day: pseudo scan 250/1500 images, kept 2676 boxes
round027 client2_citystreet_day: pseudo scan 500/1500 images, kept 5388 boxes
round027 client2_citystreet_day: pseudo scan 750/1500 images, kept 8116 boxes
round027 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10853 boxes
round027 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13540 boxes
round027 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16196 boxes
{
  "round": "round027",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round026_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1496,
  "pseudo_boxes_kept": 13738,
  "boxes_per_kept_image": 9.183155080213904,
  "mean_conf": 0.840496856096114,
  "mean_stability": 0.9398652986158431,
  "mean_score": 0.79350021290092,
  "class_counts": {
    "0": 1510,
    "2": 7289,
    "3": 206,
    "4": 590,
    "5": 73,
    "7": 1509,
    "8": 2561
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_client2_citystreet_day_stable_boxes.csv"
}
round027 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round027 client3_citystreet_night: pseudo scan 250/1500 images, kept 2179 boxes
round027 client3_citystreet_night: pseudo scan 500/1500 images, kept 4352 boxes
round027 client3_citystreet_night: pseudo scan 750/1500 images, kept 6478 boxes
round027 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8517 boxes
round027 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10786 boxes
round027 client3_citystreet_night: pseudo scan 1500/1500 images, kept 12940 boxes
{
  "round": "round027",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round026_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1472,
  "pseudo_boxes_kept": 11128,
  "boxes_per_kept_image": 7.559782608695652,
  "mean_conf": 0.7502219204306817,
  "mean_stability": 0.915194052514586,
  "mean_score": 0.6913784202971887,
  "class_counts": {
    "0": 572,
    "2": 5823,
    "3": 58,
    "4": 147,
    "5": 34,
    "7": 2125,
    "8": 2369
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_client3_citystreet_night_stable_boxes.csv"
}
round027 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round027 client4_residential_day: pseudo scan 250/1500 images, kept 2564 boxes
round027 client4_residential_day: pseudo scan 500/1500 images, kept 5133 boxes
round027 client4_residential_day: pseudo scan 750/1500 images, kept 7654 boxes
round027 client4_residential_day: pseudo scan 1000/1500 images, kept 10103 boxes
round027 client4_residential_day: pseudo scan 1250/1500 images, kept 12605 boxes
round027 client4_residential_day: pseudo scan 1500/1500 images, kept 15056 boxes
{
  "round": "round027",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round026_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9837,
  "boxes_per_kept_image": 6.610887096774194,
  "mean_conf": 0.8713992443028488,
  "mean_stability": 0.9500073829753449,
  "mean_score": 0.8313148226795193,
  "class_counts": {
    "0": 416,
    "2": 6776,
    "3": 65,
    "4": 306,
    "5": 44,
    "7": 537,
    "8": 1693
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_client4_residential_day_stable_boxes.csv"
}
round027 client5_residential_night: pseudo scan 1/1500 images, kept 5 boxes
round027 client5_residential_night: pseudo scan 250/1500 images, kept 2045 boxes
round027 client5_residential_night: pseudo scan 500/1500 images, kept 4068 boxes
round027 client5_residential_night: pseudo scan 750/1500 images, kept 6080 boxes
round027 client5_residential_night: pseudo scan 1000/1500 images, kept 8165 boxes
round027 client5_residential_night: pseudo scan 1250/1500 images, kept 10220 boxes
round027 client5_residential_night: pseudo scan 1500/1500 images, kept 12261 boxes
{
  "round": "round027",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round026_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1451,
  "pseudo_boxes_kept": 7717,
  "boxes_per_kept_image": 5.318401102687801,
  "mean_conf": 0.8086485079112751,
  "mean_stability": 0.9312640485853764,
  "mean_score": 0.7565098155924516,
  "class_counts": {
    "0": 124,
    "2": 5518,
    "3": 29,
    "4": 91,
    "5": 22,
    "7": 690,
    "8": 1243
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round027_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31323 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round027_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round027_phase1_head_client0_highway_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7863 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client0_highway_day_stable_train' images and labels...5361 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 11625.48it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 20:16:56.301346669 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 20:16:56.326196763 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1955       640  0.003507   0.04902   0.00538     4.632:   3%|▎         | 1/39 [00:21<13:55, 21.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2076       640  0.003484   0.04879  0.004612     4.551:   5%|▌         | 2/39 [00:22<05:55,  9.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640   0.00348   0.04772  0.004695     4.472:   8%|▊         | 3/39 [00:23<03:22,  5.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1743       640  0.003466   0.04689  0.004627     4.398:  10%|█         | 4/39 [00:24<02:10,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003467   0.04666  0.004659     4.383:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003467    0.0456  0.004516     4.287:  15%|█▌        | 6/39 [00:25<01:03,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640  0.003465   0.04516   0.00443     4.245:  18%|█▊        | 7/39 [00:26<00:48,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640   0.00347   0.04494  0.004418     4.227:  21%|██        | 8/39 [00:27<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2064       640  0.003477     0.045  0.004466     4.235:  23%|██▎       | 9/39 [00:27<00:31,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640   0.00349   0.04499  0.004489     4.238:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003493   0.04462  0.004484     4.208:  28%|██▊       | 11/39 [00:29<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640    0.0035   0.04463  0.004587     4.217:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2146       640  0.003496   0.04444  0.004613     4.204:  33%|███▎      | 13/39 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640  0.003498   0.04445  0.004564     4.201:  36%|███▌      | 14/39 [00:30<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003501    0.0442  0.004534     4.179:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003502   0.04401  0.004517     4.162:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003504   0.04392  0.004543     4.157:  44%|████▎     | 17/39 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2205       640  0.003505   0.04376  0.004502     4.141:  46%|████▌     | 18/39 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003505   0.04339   0.00452     4.113:  49%|████▊     | 19/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2122       640  0.003501   0.04332  0.004485     4.105:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2158       640  0.003503   0.04335  0.004466     4.106:  54%|█████▍    | 21/39 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003506   0.04332  0.004449     4.102:  56%|█████▋    | 22/39 [00:35<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003497   0.04315  0.004425     4.086:  59%|█████▉    | 23/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003497   0.04317  0.004402     4.086:  62%|██████▏   | 24/39 [00:37<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003494   0.04305  0.004421     4.077:  64%|██████▍   | 25/39 [00:37<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003494   0.04296  0.004396     4.068:  67%|██████▋   | 26/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.602      0.391      0.411      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.595      0.392      0.409      0.229
                   0        738       1052      0.562       0.52      0.523      0.251
                   1        738         44      0.571      0.182      0.241      0.108
                   2        738       8622       0.75      0.701      0.748      0.473
                   3        738        151      0.596      0.397       0.43      0.319
                   4        738        467      0.509      0.559      0.535       0.38
                   5        738         70        0.4      0.371      0.283      0.142
                   6        738         65      0.277     0.0615      0.171     0.0724
                   7        738       1619      0.594      0.581      0.581      0.239
                   8        738       2845      0.694      0.544      0.581      0.304
                   9        738          2          1          0   0.000554   0.000499

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client0_highway_day

1 epochs completed in 0.023 hours.
Destroying process group...
[rank0]:[W507 20:18:19.433257675 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31324 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round027_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round027_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client1_highway_night_stable_train' images and labels...4895 found, 2850 missing, 0 empty, 0 corrupted: 100%|██████████| 7745/7745 [00:00<00:00, 14670.93it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.401680938788456
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2850 missing, 0 empty, 0 corrupted: 100%|██████████| 7745/7745 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:18:35.227004169 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:18:36.284689785 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1861       640  0.003405   0.04514  0.004349     4.232:   2%|▎         | 1/40 [00:22<14:33, 22.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640  0.003423    0.0442  0.004722     4.187:   5%|▌         | 2/40 [00:23<06:10,  9.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003448   0.04448  0.004669     4.208:   8%|▊         | 3/40 [00:24<03:30,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1971       640   0.00343   0.04323  0.004541     4.096:  10%|█         | 4/40 [00:25<02:15,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1856       640  0.003424   0.04239  0.004593     4.032:  12%|█▎        | 5/40 [00:25<01:33,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1685       640  0.003438   0.04096  0.004654     3.924:  15%|█▌        | 6/40 [00:26<01:08,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1917       640  0.003455   0.04043  0.004717     3.888:  18%|█▊        | 7/40 [00:27<00:52,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003465   0.04009   0.00474     3.863:  20%|██        | 8/40 [00:27<00:41,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003468   0.03977  0.004629     3.829:  22%|██▎       | 9/40 [00:28<00:34,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003475   0.03935  0.004578     3.792:  25%|██▌       | 10/40 [00:29<00:29,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640  0.003473    0.0391  0.004673      3.78:  28%|██▊       | 11/40 [00:29<00:25,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1997       640  0.003474    0.0386  0.004645     3.737:  30%|███       | 12/40 [00:30<00:22,  1.22it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003478   0.03845  0.004727     3.732:  32%|███▎      | 13/40 [00:31<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2039       640  0.003492   0.03838  0.004775     3.732:  35%|███▌      | 14/40 [00:31<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1629       640  0.003481   0.03788  0.004748     3.689:  38%|███▊      | 15/40 [00:32<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640   0.00348   0.03769  0.004735     3.672:  40%|████      | 16/40 [00:33<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1858       640  0.003482   0.03756  0.004736     3.662:  42%|████▎     | 17/40 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1805       640  0.003484   0.03731  0.004741     3.643:  45%|████▌     | 18/40 [00:34<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1745       640  0.003487   0.03704  0.004701     3.618:  48%|████▊     | 19/40 [00:35<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003478   0.03701  0.004705     3.615:  50%|█████     | 20/40 [00:35<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1952       640  0.003479   0.03686   0.00467     3.601:  52%|█████▎    | 21/40 [00:36<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1687       640  0.003476   0.03669  0.004654     3.586:  55%|█████▌    | 22/40 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2098       640  0.003473   0.03678  0.004643     3.592:  57%|█████▊    | 23/40 [00:37<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2044       640   0.00347   0.03671  0.004638     3.585:  60%|██████    | 24/40 [00:38<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003474   0.03655  0.004623     3.572:  62%|██████▎   | 25/40 [00:38<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1863       640  0.003469    0.0364  0.004603     3.558:  65%|██████▌   | 26/40 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.591      0.394      0.408       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.581      0.396      0.406       0.23
                   0        738       1052      0.589      0.507       0.52      0.252
                   1        738         44      0.517      0.205      0.255      0.124
                   2        738       8622      0.726      0.705      0.745      0.475
                   3        738        151      0.592      0.394      0.426      0.324
                   4        738        467      0.516      0.543       0.53      0.376
                   5        738         70      0.393      0.371       0.26      0.134
                   6        738         65      0.235     0.0769      0.174     0.0751
                   7        738       1619      0.585      0.592      0.577      0.237
                   8        738       2845       0.66      0.564      0.577      0.304
                   9        738          2          1          0   0.000578    0.00052

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client1_highway_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 20:20:03.505842033 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31325 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round027_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round027_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client2_citystreet_day_stable_train' images and labels...5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<00:00, 10710.05it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.637256480437932
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2660 missing, 0 empty, 0 corrupted: 100%|██████████| 7873/7873 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:20:19.841115278 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:20:19.873836981 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2066       640  0.003594   0.05621  0.004619     5.154:   3%|▎         | 1/39 [00:22<14:08, 22.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2169       640  0.003543   0.05487  0.004923     5.067:   5%|▌         | 2/39 [00:23<05:59,  9.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003513   0.05329  0.004909     4.937:   8%|▊         | 3/39 [00:24<03:24,  5.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003523   0.05171  0.004847     4.806:  10%|█         | 4/39 [00:25<02:13,  3.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2141       640   0.00352   0.05109  0.004762      4.75:  13%|█▎        | 5/39 [00:25<01:30,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1783       640  0.003492   0.04986  0.004733     4.647:  15%|█▌        | 6/39 [00:26<01:05,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003501   0.04936  0.004775     4.611:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003491   0.04879  0.004731     4.561:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003502   0.04862  0.004657     4.542:  23%|██▎       | 9/39 [00:28<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003489    0.0482  0.004646     4.507:  26%|██▌       | 10/39 [00:28<00:27,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003493   0.04795  0.004645     4.487:  28%|██▊       | 11/39 [00:29<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003498   0.04738  0.004654     4.443:  31%|███       | 12/39 [00:30<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003503    0.0471  0.004608     4.417:  33%|███▎      | 13/39 [00:30<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003511   0.04707  0.004567     4.412:  36%|███▌      | 14/39 [00:31<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640  0.003511   0.04685  0.004541     4.392:  38%|███▊      | 15/39 [00:32<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1922       640  0.003502    0.0465  0.004531     4.363:  41%|████      | 16/39 [00:32<00:15,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1503       640  0.003493   0.04617  0.004561     4.338:  44%|████▎     | 17/39 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1948       640  0.003485   0.04603  0.004544     4.325:  46%|████▌     | 18/39 [00:34<00:14,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1728       640  0.003485   0.04568  0.004526     4.295:  49%|████▊     | 19/39 [00:34<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003479   0.04562  0.004518     4.289:  51%|█████▏    | 20/39 [00:35<00:12,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1837       640   0.00347   0.04541  0.004497      4.27:  54%|█████▍    | 21/39 [00:36<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1717       640  0.003465   0.04529  0.004488     4.259:  56%|█████▋    | 22/39 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1826       640  0.003458   0.04512  0.004477     4.244:  59%|█████▉    | 23/39 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003454   0.04504  0.004467     4.237:  62%|██████▏   | 24/39 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1811       640  0.003449    0.0449  0.004455     4.225:  64%|██████▍   | 25/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003443   0.04482  0.004442     4.217:  67%|██████▋   | 26/39 [00:39<00:08,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.582      0.396      0.406      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.581      0.393      0.404      0.227
                   0        738       1052      0.669      0.474      0.513      0.246
                   1        738         44      0.538      0.159      0.221        0.1
                   2        738       8622      0.696      0.726      0.748      0.474
                   3        738        151      0.477      0.391      0.427      0.322
                   4        738        467      0.467      0.585      0.526       0.37
                   5        738         70      0.421      0.386       0.29      0.148
                   6        738         65      0.289     0.0615      0.158     0.0672
                   7        738       1619      0.593      0.577      0.575      0.234
                   8        738       2845      0.655       0.57      0.582      0.307
                   9        738          2          1          0   0.000401   0.000361

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:21:45.619929570 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31326 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round027_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round027_phase1_head_client3_citystreet_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client3_citystreet_night_stable_train' images and labels...4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<00:00, 14188.65it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29014483627204
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2942 missing, 0 empty, 0 corrupted: 100%|██████████| 7825/7825 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 20:22:01.056009422 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 20:22:01.058864231 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1863       640  0.003604   0.04983  0.004676     4.648:   2%|▎         | 1/40 [00:21<14:17, 21.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1719       640  0.003491   0.04556  0.004753     4.304:   5%|▌         | 2/40 [00:23<06:08,  9.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003496   0.04541  0.004446     4.268:   8%|▊         | 3/40 [00:23<03:29,  5.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640   0.00349   0.04463  0.004293     4.193:  10%|█         | 4/40 [00:24<02:15,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003479   0.04408  0.004225     4.143:  12%|█▎        | 5/40 [00:25<01:32,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1671       640  0.003464   0.04241  0.004249      4.01:  15%|█▌        | 6/40 [00:26<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1688       640  0.003452   0.04139  0.004263     3.928:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003449   0.04102  0.004199     3.894:  20%|██        | 8/40 [00:27<00:40,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640  0.003451   0.04106  0.004159     3.894:  22%|██▎       | 9/40 [00:28<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003464   0.04082   0.00417     3.877:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003467   0.04053  0.004257      3.86:  28%|██▊       | 11/40 [00:29<00:24,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003474   0.04013  0.004218     3.826:  30%|███       | 12/40 [00:29<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1877       640  0.003465   0.03984  0.004226     3.802:  32%|███▎      | 13/40 [00:30<00:20,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2007       640  0.003462   0.03965   0.00426      3.79:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003458   0.03944  0.004261     3.773:  38%|███▊      | 15/40 [00:31<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1855       640  0.003457   0.03922  0.004241     3.753:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1703       640  0.003462   0.03893  0.004305     3.736:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003458   0.03866  0.004342     3.717:  45%|████▌     | 18/40 [00:33<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1779       640   0.00346   0.03839  0.004311     3.693:  48%|████▊     | 19/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003464   0.03835  0.004336     3.692:  50%|█████     | 20/40 [00:35<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1819       640  0.003474   0.03816  0.004314     3.676:  52%|█████▎    | 21/40 [00:35<00:12,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1936       640  0.003472   0.03811  0.004281     3.669:  55%|█████▌    | 22/40 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2243       640  0.003471   0.03831  0.004286     3.685:  57%|█████▊    | 23/40 [00:37<00:11,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2091       640  0.003474   0.03829  0.004329     3.688:  60%|██████    | 24/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003474   0.03826  0.004324     3.684:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640  0.003472   0.03819  0.004317     3.678:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.611      0.386      0.407      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.605      0.387      0.405      0.227
                   0        738       1052      0.629      0.481      0.513      0.247
                   1        738         44      0.665      0.181      0.254      0.114
                   2        738       8622      0.722      0.702      0.741      0.471
                   3        738        151       0.58      0.384      0.424      0.317
                   4        738        467      0.496      0.577      0.534      0.375
                   5        738         70      0.422      0.371      0.284       0.14
                   6        738         65      0.266     0.0615      0.162     0.0692
                   7        738       1619      0.593      0.565      0.567      0.234
                   8        738       2845       0.68      0.549      0.574      0.304
                   9        738          2          1          0   0.000608   0.000547

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:23:27.293222444 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31327 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round027_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

self imgsz: 640
self imgsz: 640

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round027_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client4_residential_day_stable_train' images and labels...5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<00:00, 23520.35it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:23:42.566067698 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:23:42.673928882 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1976       640  0.003593   0.05561  0.004658     5.109:   3%|▎         | 1/39 [00:21<13:50, 21.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640  0.003553   0.05542  0.004566     5.083:   5%|▌         | 2/39 [00:22<05:52,  9.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003519   0.05246   0.00464     4.849:   8%|▊         | 3/39 [00:23<03:21,  5.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003509   0.05085   0.00471     4.725:  10%|█         | 4/39 [00:24<02:10,  3.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2226       640  0.003498   0.05031  0.004667     4.678:  13%|█▎        | 5/39 [00:25<01:29,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1721       640  0.003478   0.04858  0.004573     4.531:  15%|█▌        | 6/39 [00:25<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2003       640  0.003502   0.04821  0.004639     4.508:  18%|█▊        | 7/39 [00:26<00:49,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640  0.003497   0.04765  0.004612     4.461:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2107       640  0.003496   0.04751  0.004481     4.439:  23%|██▎       | 9/39 [00:27<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003492    0.0472  0.004551     4.419:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003488   0.04661   0.00455     4.371:  28%|██▊       | 11/39 [00:29<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003486   0.04629  0.004568     4.347:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2165       640  0.003498   0.04626   0.00451     4.342:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003495   0.04588  0.004471     4.307:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640    0.0035   0.04571   0.00448     4.295:  38%|███▊      | 15/39 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003504   0.04541  0.004495     4.273:  41%|████      | 16/39 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003503   0.04517  0.004513     4.255:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003497   0.04493  0.004478     4.232:  46%|████▌     | 18/39 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640  0.003493   0.04463  0.004449     4.205:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003488    0.0446  0.004443     4.202:  51%|█████▏    | 20/39 [00:34<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003481   0.04441  0.004437     4.186:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003482   0.04446  0.004435      4.19:  56%|█████▋    | 22/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003479   0.04438  0.004433     4.184:  59%|█████▉    | 23/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003475   0.04431  0.004422     4.176:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003473    0.0442  0.004405     4.166:  64%|██████▍   | 25/39 [00:37<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1969       640  0.003468   0.04411   0.00442      4.16:  67%|██████▋   | 26/39 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.583      0.398      0.409      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.573      0.399      0.407      0.228
                   0        738       1052      0.573      0.515      0.522       0.25
                   1        738         44      0.531      0.159      0.235      0.107
                   2        738       8622      0.723      0.705      0.742      0.469
                   3        738        151      0.516      0.404      0.434      0.323
                   4        738        467      0.481      0.585      0.527      0.369
                   5        738         70      0.403      0.386       0.29      0.147
                   6        738         65      0.272     0.0615      0.164     0.0689
                   7        738       1619      0.579       0.59      0.575      0.239
                   8        738       2845      0.653      0.585      0.585      0.309
                   9        738          2          1          0    0.00032   0.000288

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:25:08.922610441 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31328 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round027_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round027_phase1_head_client5_residential_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client5_residential_night_stable_train' images and labels...4885 found, 2898 missing, 0 empty, 0 corrupted: 100%|██████████| 7783/7783 [00:00<00:00, 11113.30it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.343285939968405
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round027_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2898 missing, 0 empty, 0 corrupted: 100%|██████████| 7783/7783 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:25:25.384270793 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:25:25.399961227 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2007       640  0.003531   0.04793  0.004928     4.511:   2%|▎         | 1/40 [00:21<14:08, 21.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640  0.003515   0.04595    0.0046     4.325:   5%|▌         | 2/40 [00:22<05:59,  9.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1689       640  0.003475   0.04458  0.004428     4.199:   8%|▊         | 3/40 [00:23<03:24,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003485   0.04372  0.004481     4.135:  10%|█         | 4/40 [00:24<02:12,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003488   0.04283  0.004541     4.069:  12%|█▎        | 5/40 [00:24<01:30,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1762       640  0.003487   0.04209  0.004592     4.014:  15%|█▌        | 6/40 [00:25<01:05,  1.92s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1873       640  0.003499   0.04116  0.004656     3.945:  18%|█▊        | 7/40 [00:26<00:49,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1994       640  0.003497   0.04104  0.004597      3.93:  20%|██        | 8/40 [00:26<00:39,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1962       640  0.003492   0.04077  0.004535     3.904:  22%|██▎       | 9/40 [00:27<00:32,  1.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1963       640  0.003484   0.04038  0.004482     3.868:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2069       640  0.003487   0.04013  0.004501     3.849:  28%|██▊       | 11/40 [00:28<00:24,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1882       640   0.00348   0.03969  0.004549     3.818:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1889       640  0.003476   0.03935  0.004498     3.786:  32%|███▎      | 13/40 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640   0.00348   0.03906  0.004509     3.764:  35%|███▌      | 14/40 [00:30<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640   0.00348   0.03871  0.004501     3.735:  38%|███▊      | 15/40 [00:31<00:17,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003479   0.03842  0.004474      3.71:  40%|████      | 16/40 [00:32<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1797       640  0.003477   0.03812  0.004456     3.684:  42%|████▎     | 17/40 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003483   0.03813   0.00445     3.685:  45%|████▌     | 18/40 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1695       640  0.003479   0.03773  0.004442     3.652:  48%|████▊     | 19/40 [00:33<00:13,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640  0.003478   0.03768  0.004456     3.649:  50%|█████     | 20/40 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003473   0.03754  0.004465     3.638:  52%|█████▎    | 21/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1674       640  0.003473   0.03736   0.00444     3.622:  55%|█████▌    | 22/40 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1919       640  0.003471   0.03724  0.004449     3.613:  57%|█████▊    | 23/40 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640   0.00347   0.03718  0.004473      3.61:  60%|██████    | 24/40 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1748       640  0.003469   0.03692   0.00448     3.589:  62%|██████▎   | 25/40 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1880       640  0.003469   0.03678  0.004484     3.579:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.638      0.378      0.409       0.23
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.623      0.379      0.407      0.229
                   0        738       1052      0.628      0.485      0.521      0.249
                   1        738         44      0.695      0.159      0.246      0.124
                   2        738       8622      0.757      0.689      0.742      0.472
                   3        738        151      0.625      0.384      0.424       0.32
                   4        738        467      0.537      0.546       0.54      0.378
                   5        738         70      0.425      0.357      0.292       0.15
                   6        738         65      0.282     0.0462      0.154     0.0615
                   7        738       1619      0.597       0.57       0.57      0.236
                   8        738       2845      0.681      0.556      0.577      0.304
                   9        738          2          1          0   0.000559   0.000503

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:26:50.050618964 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31329 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round027_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round027_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:27:08.647987969 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:27:08.975720742 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.03009   0.03326  0.003355     5.337:   3%|▎         | 1/31 [00:32<16:23, 32.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.02979   0.03235  0.003286     5.234:   6%|▋         | 2/31 [00:33<06:44, 13.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.02905   0.03105   0.00321     5.065:  10%|▉         | 3/31 [00:34<03:42,  7.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.02848   0.02967  0.003012     4.893:  13%|█▎        | 4/31 [00:35<02:18,  5.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640    0.0282   0.02937  0.002993     4.844:  16%|█▌        | 5/31 [00:35<01:30,  3.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.02813     0.029  0.003017     4.812:  19%|█▉        | 6/31 [00:36<01:02,  2.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.02816   0.02866  0.003075     4.792:  23%|██▎       | 7/31 [00:36<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640     0.028   0.02858  0.003076     4.772:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.02802   0.02845  0.003008     4.758:  29%|██▉       | 9/31 [00:38<00:26,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.02802   0.02847  0.002976     4.757:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.02797   0.02843  0.002979      4.75:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.02787   0.02815  0.002968     4.719:  39%|███▊      | 12/31 [00:39<00:14,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.02783   0.02808  0.002926     4.707:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.02785   0.02796    0.0029     4.696:  45%|████▌     | 14/31 [00:41<00:11,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.02785   0.02782  0.002946      4.69:  48%|████▊     | 15/31 [00:41<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.02786   0.02769  0.002954      4.68:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.02788   0.02769  0.002935     4.681:  55%|█████▍    | 17/31 [00:42<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.02797   0.02781  0.002911     4.695:  58%|█████▊    | 18/31 [00:43<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.02795   0.02771  0.002897     4.685:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.02796   0.02788  0.002896     4.699:  65%|██████▍   | 20/31 [00:44<00:06,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.02801   0.02793  0.002918     4.709:  68%|██████▊   | 21/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.02804   0.02803  0.002899     4.717:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.02805   0.02809  0.002875     4.722:  74%|███████▍  | 23/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640    0.0281   0.02822   0.00287     4.735:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.02813   0.02823  0.002872     4.739:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.02821   0.02832  0.002879     4.753:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.542      0.411      0.398      0.216
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.532      0.413      0.397      0.217
                   0        738       1052      0.487      0.534      0.503      0.238
                   1        738         44      0.469      0.182      0.202     0.0823
                   2        738       8622      0.687      0.721      0.738      0.472
                   3        738        151      0.462      0.417      0.429      0.317
                   4        738        467      0.473      0.578      0.517      0.358
                   5        738         70      0.333      0.414      0.312      0.128
                   6        738         65      0.265      0.108      0.157     0.0593
                   7        738       1619      0.552      0.602      0.562      0.229
                   8        738       2845      0.594      0.574      0.545      0.284
                   9        738          2          1          0   0.000543   0.000489

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round027_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 20:28:48.278517469 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round028 phase_round=28 ===

02 head-to-full DQA:  84%|████████▍ | 27/32 [6:21:29<1:10:26, 845.39s/round, elapsed=6h21m29s, eta=1h10m38s, phase=phase1_head, round=27]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round028 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round028 client0_highway_day: pseudo scan 250/1500 images, kept 2342 boxes
round028 client0_highway_day: pseudo scan 500/1500 images, kept 4750 boxes
round028 client0_highway_day: pseudo scan 750/1500 images, kept 7060 boxes
round028 client0_highway_day: pseudo scan 1000/1500 images, kept 9410 boxes
round028 client0_highway_day: pseudo scan 1250/1500 images, kept 11725 boxes
round028 client0_highway_day: pseudo scan 1500/1500 images, kept 14105 boxes
{
  "round": "round028",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round027_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 11110,
  "boxes_per_kept_image": 7.451374916163648,
  "mean_conf": 0.8423515624419512,
  "mean_stability": 0.9417353289927801,
  "mean_score": 0.7966065218734023,
  "class_counts": {
    "0": 159,
    "2": 6348,
    "3": 115,
    "4": 565,
    "5": 8,
    "7": 559,
    "8": 3356
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_client0_highway_day_stable_boxes.csv"
}
round028 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round028 client1_highway_night: pseudo scan 250/1500 images, kept 1429 boxes
round028 client1_highway_night: pseudo scan 500/1500 images, kept 2958 boxes
round028 client1_highway_night: pseudo scan 750/1500 images, kept 4533 boxes
round028 client1_highway_night: pseudo scan 1000/1500 images, kept 5991 boxes
round028 client1_highway_night: pseudo scan 1250/1500 images, kept 7499 boxes
round028 client1_highway_night: pseudo scan 1500/1500 images, kept 8954 boxes
{
  "round": "round028",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round027_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1431,
  "pseudo_boxes_kept": 7552,
  "boxes_per_kept_image": 5.277428371767995,
  "mean_conf": 0.762102865179906,
  "mean_stability": 0.9206290469757454,
  "mean_score": 0.7059223046303171,
  "class_counts": {
    "0": 71,
    "2": 4030,
    "3": 26,
    "4": 150,
    "5": 8,
    "7": 648,
    "8": 2619
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_client1_highway_night_stable_boxes.csv"
}
round028 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round028 client2_citystreet_day: pseudo scan 250/1500 images, kept 2671 boxes
round028 client2_citystreet_day: pseudo scan 500/1500 images, kept 5375 boxes
round028 client2_citystreet_day: pseudo scan 750/1500 images, kept 8103 boxes
round028 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10842 boxes
round028 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13530 boxes
round028 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16176 boxes
{
  "round": "round028",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round027_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13698,
  "boxes_per_kept_image": 9.162541806020068,
  "mean_conf": 0.8423567099943007,
  "mean_stability": 0.93917621347326,
  "mean_score": 0.794683932431644,
  "class_counts": {
    "0": 1527,
    "2": 7280,
    "3": 199,
    "4": 584,
    "5": 63,
    "7": 1495,
    "8": 2550
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_client2_citystreet_day_stable_boxes.csv"
}
round028 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round028 client3_citystreet_night: pseudo scan 250/1500 images, kept 2151 boxes
round028 client3_citystreet_night: pseudo scan 500/1500 images, kept 4298 boxes
round028 client3_citystreet_night: pseudo scan 750/1500 images, kept 6388 boxes
round028 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8420 boxes
round028 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10677 boxes
round028 client3_citystreet_night: pseudo scan 1500/1500 images, kept 12804 boxes
{
  "round": "round028",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round027_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1469,
  "pseudo_boxes_kept": 11035,
  "boxes_per_kept_image": 7.511912865895167,
  "mean_conf": 0.7524656156635846,
  "mean_stability": 0.9148473723257727,
  "mean_score": 0.6930959690353937,
  "class_counts": {
    "0": 565,
    "2": 5762,
    "3": 58,
    "4": 154,
    "5": 32,
    "7": 2107,
    "8": 2357
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_client3_citystreet_night_stable_boxes.csv"
}
round028 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round028 client4_residential_day: pseudo scan 250/1500 images, kept 2570 boxes
round028 client4_residential_day: pseudo scan 500/1500 images, kept 5143 boxes
round028 client4_residential_day: pseudo scan 750/1500 images, kept 7660 boxes
round028 client4_residential_day: pseudo scan 1000/1500 images, kept 10094 boxes
round028 client4_residential_day: pseudo scan 1250/1500 images, kept 12598 boxes
round028 client4_residential_day: pseudo scan 1500/1500 images, kept 15038 boxes
{
  "round": "round028",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round027_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9830,
  "boxes_per_kept_image": 6.606182795698925,
  "mean_conf": 0.8729444439480287,
  "mean_stability": 0.949168852241454,
  "mean_score": 0.8320531074591331,
  "class_counts": {
    "0": 420,
    "2": 6768,
    "3": 63,
    "4": 310,
    "5": 44,
    "7": 531,
    "8": 1694
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_client4_residential_day_stable_boxes.csv"
}
round028 client5_residential_night: pseudo scan 1/1500 images, kept 5 boxes
round028 client5_residential_night: pseudo scan 250/1500 images, kept 2000 boxes
round028 client5_residential_night: pseudo scan 500/1500 images, kept 4003 boxes
round028 client5_residential_night: pseudo scan 750/1500 images, kept 5956 boxes
round028 client5_residential_night: pseudo scan 1000/1500 images, kept 7991 boxes
round028 client5_residential_night: pseudo scan 1250/1500 images, kept 9996 boxes
round028 client5_residential_night: pseudo scan 1500/1500 images, kept 12002 boxes
{
  "round": "round028",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round027_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1448,
  "pseudo_boxes_kept": 7606,
  "boxes_per_kept_image": 5.252762430939226,
  "mean_conf": 0.8082802045464421,
  "mean_stability": 0.9306533606999678,
  "mean_score": 0.7557303740696988,
  "class_counts": {
    "0": 123,
    "2": 5401,
    "3": 29,
    "4": 98,
    "5": 21,
    "7": 688,
    "8": 1246
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round028_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31330 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round028_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round028_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client0_highway_day_stable_train' images and labels...5361 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 12112.19it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client0_highway_day_stable_train.cache' images and labels... 5361 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 20:31:04.530139635 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 20:31:04.619529904 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1955       640  0.003508   0.04923  0.005387      4.65:   3%|▎         | 1/39 [00:21<13:36, 21.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2076       640  0.003487   0.04903  0.004613      4.57:   5%|▌         | 2/39 [00:22<05:46,  9.37s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003483   0.04795  0.004703     4.491:   8%|▊         | 3/39 [00:23<03:17,  5.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1743       640   0.00347    0.0471   0.00464     4.417:  10%|█         | 4/39 [00:24<02:08,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1886       640  0.003471   0.04687  0.004674     4.401:  13%|█▎        | 5/39 [00:24<01:27,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1864       640  0.003473   0.04579  0.004529     4.304:  15%|█▌        | 6/39 [00:25<01:04,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2123       640   0.00347   0.04534  0.004436      4.26:  18%|█▊        | 7/39 [00:26<00:48,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003475    0.0451  0.004423      4.24:  21%|██        | 8/39 [00:26<00:38,  1.24s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2064       640  0.003482   0.04515  0.004469     4.248:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003495   0.04513  0.004492      4.25:  26%|██▌       | 10/39 [00:28<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640  0.003499   0.04476  0.004489     4.219:  28%|██▊       | 11/39 [00:28<00:23,  1.18it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1957       640  0.003507   0.04476   0.00459     4.228:  31%|███       | 12/39 [00:29<00:21,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2146       640  0.003503   0.04457  0.004617     4.215:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2126       640  0.003505   0.04458  0.004568     4.212:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1945       640  0.003508   0.04432  0.004538     4.189:  38%|███▊      | 15/39 [00:31<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003509   0.04412  0.004522     4.172:  41%|████      | 16/39 [00:31<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003511   0.04403  0.004547     4.167:  44%|████▎     | 17/39 [00:32<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2205       640  0.003512   0.04387  0.004507     4.151:  46%|████▌     | 18/39 [00:33<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1766       640  0.003512    0.0435  0.004525     4.123:  49%|████▊     | 19/39 [00:33<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2122       640  0.003508   0.04342  0.004489     4.114:  51%|█████▏    | 20/39 [00:34<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2158       640   0.00351   0.04345   0.00447     4.114:  54%|█████▍    | 21/39 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003513   0.04341  0.004452      4.11:  56%|█████▋    | 22/39 [00:35<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2025       640  0.003504   0.04324  0.004428     4.094:  59%|█████▉    | 23/39 [00:36<00:10,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003504   0.04326  0.004405     4.094:  62%|██████▏   | 24/39 [00:37<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2005       640  0.003501   0.04314  0.004424     4.085:  64%|██████▍   | 25/39 [00:37<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003501   0.04305  0.004399     4.076:  67%|██████▋   | 26/39 [00:38<00:08,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.599      0.391      0.411      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.589      0.392      0.409      0.228
                   0        738       1052       0.55      0.521      0.521      0.251
                   1        738         44      0.569      0.182       0.24      0.106
                   2        738       8622      0.746      0.702      0.747      0.472
                   3        738        151      0.599      0.391      0.426      0.318
                   4        738        467      0.508      0.559      0.537      0.381
                   5        738         70       0.39      0.371      0.286      0.143
                   6        738         65      0.253     0.0615      0.171     0.0715
                   7        738       1619      0.587      0.585       0.58      0.239
                   8        738       2845      0.685      0.548      0.578      0.303
                   9        738          2          1          0   0.000558   0.000502

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client0_highway_day

1 epochs completed in 0.023 hours.
Destroying process group...
[rank0]:[W507 20:32:27.434828211 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31331 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round028_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round028_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client1_highway_night_stable_train' images and labels...4895 found, 2848 missing, 0 empty, 0 corrupted: 100%|██████████| 7743/7743 [00:00<00:00, 13440.86it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.404123711340207
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2848 missing, 0 empty, 0 corrupted: 100%|██████████| 7743/7743 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:32:43.678880693 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:32:43.698563768 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2123       640  0.003518   0.04633  0.004803     4.372:   2%|▎         | 1/40 [00:21<14:09, 21.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003436   0.04461  0.004436     4.198:   5%|▌         | 2/40 [00:22<06:00,  9.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1938       640  0.003469   0.04407  0.004176     4.137:   8%|▊         | 3/40 [00:23<03:26,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003434   0.04286  0.004175     4.037:  10%|█         | 4/40 [00:24<02:13,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1812       640  0.003441   0.04193   0.00429     3.973:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640  0.003456   0.04078  0.004294     3.883:  15%|█▌        | 6/40 [00:25<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003473   0.04042  0.004386     3.862:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003483   0.04045  0.004407     3.867:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003489   0.04002  0.004403     3.833:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1798       640  0.003492   0.03954  0.004418     3.796:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2060       640  0.003492   0.03923  0.004513     3.779:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003496    0.0387  0.004523     3.738:  30%|███       | 12/40 [00:29<00:22,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003496   0.03871  0.004531     3.739:  32%|███▎      | 13/40 [00:30<00:20,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2059       640  0.003504    0.0387  0.004509     3.737:  35%|███▌      | 14/40 [00:30<00:18,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1919       640  0.003505   0.03839  0.004523     3.714:  38%|███▊      | 15/40 [00:31<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1832       640  0.003511   0.03813  0.004526     3.693:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1760       640  0.003514   0.03783  0.004541     3.671:  42%|████▎     | 17/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1844       640  0.003515   0.03765  0.004512     3.654:  45%|████▌     | 18/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1678       640  0.003513   0.03727  0.004476     3.621:  48%|████▊     | 19/40 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1977       640  0.003509   0.03724  0.004496      3.62:  50%|█████     | 20/40 [00:34<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1810       640  0.003507   0.03698  0.004492     3.599:  52%|█████▎    | 21/40 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1603       640  0.003502   0.03677  0.004465     3.579:  55%|█████▌    | 22/40 [00:36<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2178       640  0.003502   0.03686  0.004458     3.586:  57%|█████▊    | 23/40 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2026       640  0.003499   0.03681  0.004464     3.582:  60%|██████    | 24/40 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003497   0.03669  0.004466     3.572:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003495   0.03662   0.00446     3.566:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.613      0.378      0.406      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.604      0.378      0.404      0.228
                   0        738       1052      0.616      0.502      0.523      0.252
                   1        738         44      0.581      0.159      0.232      0.104
                   2        738       8622      0.747      0.698      0.744      0.475
                   3        738        151      0.606      0.377      0.418      0.316
                   4        738        467      0.533      0.535      0.526      0.372
                   5        738         70      0.384      0.329      0.262      0.145
                   6        738         65      0.287     0.0615      0.179     0.0748
                   7        738       1619      0.603      0.574      0.578      0.236
                   8        738       2845       0.68      0.548      0.576      0.304
                   9        738          2          1          0   0.000526   0.000474

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:34:07.727288001 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31332 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round028_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round028_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client2_citystreet_day_stable_train' images and labels...5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 12223.96it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:34:23.129502328 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:34:23.172559552 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1949       640  0.003487   0.05651  0.004611     5.168:   3%|▎         | 1/39 [00:21<13:44, 21.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003506   0.05701  0.004667     5.215:   5%|▌         | 2/39 [00:22<05:50,  9.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640   0.00349   0.05465  0.004574     5.017:   8%|▊         | 3/39 [00:23<03:18,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003484   0.05275  0.004643      4.87:  10%|█         | 4/39 [00:24<02:08,  3.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2180       640  0.003483   0.05198  0.004548     4.801:  13%|█▎        | 5/39 [00:24<01:28,  2.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1564       640  0.003462   0.04987  0.004501     4.627:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003491   0.04963  0.004644     4.621:  18%|█▊        | 7/39 [00:26<00:48,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003479    0.0489  0.004614      4.56:  21%|██        | 8/39 [00:27<00:38,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003488   0.04888  0.004528     4.552:  23%|██▎       | 9/39 [00:27<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003476   0.04832  0.004509     4.505:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003483   0.04802  0.004533     4.483:  28%|██▊       | 11/39 [00:29<00:24,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003487   0.04754  0.004576     4.448:  31%|███       | 12/39 [00:29<00:21,  1.23it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003498    0.0475  0.004547     4.444:  33%|███▎      | 13/39 [00:30<00:19,  1.32it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003507   0.04734  0.004508     4.429:  36%|███▌      | 14/39 [00:30<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003509   0.04715  0.004517     4.414:  38%|███▊      | 15/39 [00:31<00:16,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003512   0.04691  0.004513     4.395:  41%|████      | 16/39 [00:32<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003514   0.04679  0.004512     4.385:  44%|████▎     | 17/39 [00:32<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003506   0.04668  0.004478     4.374:  46%|████▌     | 18/39 [00:33<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640  0.003503   0.04636  0.004444     4.345:  49%|████▊     | 19/39 [00:34<00:12,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003502   0.04634  0.004455     4.344:  51%|█████▏    | 20/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640  0.003494   0.04617   0.00442     4.327:  54%|█████▍    | 21/39 [00:35<00:11,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003488   0.04621  0.004408     4.328:  56%|█████▋    | 22/39 [00:36<00:10,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003487   0.04606   0.00442     4.318:  59%|█████▉    | 23/39 [00:36<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003485   0.04608  0.004399     4.317:  62%|██████▏   | 24/39 [00:37<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2034       640  0.003483   0.04599  0.004384     4.308:  64%|██████▍   | 25/39 [00:37<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003482   0.04588  0.004402     4.301:  67%|██████▋   | 26/39 [00:38<00:08,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.555      0.405      0.405      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.34it/s]

                 all        738      14937      0.542      0.406      0.403      0.226
                   0        738       1052      0.631      0.494      0.516      0.249
                   1        738         44      0.445      0.201      0.215     0.0988
                   2        738       8622      0.671      0.734      0.748      0.474
                   3        738        151      0.472      0.397      0.425      0.315
                   4        738        467      0.449      0.589      0.522      0.367
                   5        738         70      0.369        0.4      0.285      0.148
                   6        738         65      0.195     0.0615      0.162     0.0681
                   7        738       1619      0.566      0.601      0.571      0.237
                   8        738       2845      0.623      0.586      0.581      0.307
                   9        738          2          1          0   0.000366    0.00033

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:35:48.828224155 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31333 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round028_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round028_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/7819 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client3_citystreet_night_stable_train' images and labels...4883 found, 2936 missing, 0 empty, 0 corrupted: 100%|██████████| 7819/7819 [00:00<00:00, 12331.37it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.297369664514097
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2936 missing, 0 empty, 0 corrupted: 100%|██████████| 7819/7819 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:36:04.926727820 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:36:04.942262538 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1878       640  0.003414   0.04693  0.004811     4.412:   2%|▎         | 1/40 [00:22<14:27, 22.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1894       640  0.003501   0.04601  0.004672     4.335:   5%|▌         | 2/40 [00:23<06:08,  9.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1825       640  0.003499    0.0456   0.00456     4.293:   8%|▊         | 3/40 [00:24<03:29,  5.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1884       640  0.003494   0.04466  0.004619     4.222:  10%|█         | 4/40 [00:24<02:15,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1983       640  0.003514    0.0439  0.004764     4.174:  12%|█▎        | 5/40 [00:25<01:32,  2.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1666       640  0.003495    0.0427  0.004794     4.079:  15%|█▌        | 6/40 [00:26<01:06,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1754       640  0.003496   0.04171  0.004681     3.991:  18%|█▊        | 7/40 [00:26<00:50,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2078       640  0.003496   0.04167  0.004696     3.989:  20%|██        | 8/40 [00:27<00:39,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2047       640  0.003508   0.04148  0.004629     3.969:  22%|██▎       | 9/40 [00:28<00:32,  1.04s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1944       640  0.003513   0.04116  0.004634     3.944:  25%|██▌       | 10/40 [00:28<00:27,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2077       640  0.003517   0.04081  0.004663      3.92:  28%|██▊       | 11/40 [00:29<00:23,  1.22it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1673       640  0.003508   0.04016  0.004708      3.87:  30%|███       | 12/40 [00:29<00:21,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1949       640   0.00351   0.03981  0.004778     3.848:  32%|███▎      | 13/40 [00:30<00:19,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2112       640  0.003519   0.03975  0.004827     3.847:  35%|███▌      | 14/40 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1856       640  0.003521   0.03933  0.004809     3.813:  38%|███▊      | 15/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1944       640  0.003515   0.03917  0.004751     3.795:  40%|████      | 16/40 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1866       640  0.003521   0.03896  0.004807     3.783:  42%|████▎     | 17/40 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2110       640  0.003518   0.03882   0.00483     3.773:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1573       640  0.003514   0.03838  0.004809     3.736:  48%|████▊     | 19/40 [00:34<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2054       640  0.003516   0.03835  0.004811     3.734:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2074       640  0.003525   0.03835  0.004812     3.735:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1928       640  0.003527   0.03826  0.004798     3.727:  55%|█████▌    | 22/40 [00:36<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1851       640  0.003523   0.03814  0.004774     3.715:  57%|█████▊    | 23/40 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1790       640  0.003517   0.03796  0.004766     3.699:  60%|██████    | 24/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1801       640  0.003514   0.03782  0.004754     3.687:  62%|██████▎   | 25/40 [00:37<00:09,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2019       640  0.003513   0.03779  0.004714     3.681:  65%|██████▌   | 26/40 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.643      0.377      0.407      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.633       0.38      0.406      0.228
                   0        738       1052      0.649      0.465      0.508      0.244
                   1        738         44      0.723      0.159      0.248      0.118
                   2        738       8622       0.75      0.693      0.742      0.471
                   3        738        151      0.607      0.384      0.423      0.317
                   4        738        467      0.529      0.549      0.532      0.378
                   5        738         70      0.447      0.371      0.293      0.149
                   6        738         65      0.338     0.0615      0.171     0.0697
                   7        738       1619      0.599      0.573      0.569      0.233
                   8        738       2845      0.686      0.544      0.574      0.304
                   9        738          2          1          0   0.000592   0.000533

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client3_citystreet_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:37:29.352483272 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31334 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round028_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round028_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client4_residential_day_stable_train' images and labels...5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<00:00, 12923.27it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:37:45.439128145 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:37:45.780645984 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1976       640  0.003599   0.05595  0.004689     5.139:   3%|▎         | 1/39 [00:22<13:58, 22.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640  0.003559   0.05573  0.004565     5.108:   5%|▌         | 2/39 [00:22<05:55,  9.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003526   0.05276  0.004643     4.875:   8%|▊         | 3/39 [00:23<03:21,  5.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003516   0.05114   0.00472      4.75:  10%|█         | 4/39 [00:24<02:10,  3.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2226       640  0.003506   0.05059  0.004676     4.702:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1721       640  0.003484   0.04884  0.004579     4.552:  15%|█▌        | 6/39 [00:25<01:04,  1.94s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2003       640  0.003509   0.04845  0.004645     4.528:  18%|█▊        | 7/39 [00:26<00:48,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640  0.003505   0.04787  0.004614     4.479:  21%|██        | 8/39 [00:27<00:38,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2107       640  0.003503   0.04772  0.004482     4.456:  23%|██▎       | 9/39 [00:27<00:31,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640    0.0035   0.04738  0.004553     4.435:  26%|██▌       | 10/39 [00:28<00:26,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003495   0.04678  0.004553     4.386:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003494   0.04646   0.00457     4.362:  31%|███       | 12/39 [00:29<00:20,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2165       640  0.003506   0.04642  0.004511     4.355:  33%|███▎      | 13/39 [00:30<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003502   0.04603  0.004472      4.32:  36%|███▌      | 14/39 [00:31<00:17,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003508   0.04585  0.004481     4.307:  38%|███▊      | 15/39 [00:31<00:16,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003512   0.04555  0.004495     4.285:  41%|████      | 16/39 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003511    0.0453  0.004514     4.266:  44%|████▎     | 17/39 [00:32<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003505   0.04506  0.004478     4.243:  46%|████▌     | 18/39 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640  0.003501   0.04475  0.004448     4.216:  49%|████▊     | 19/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640  0.003496   0.04472  0.004443     4.213:  51%|█████▏    | 20/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003489   0.04452  0.004436     4.196:  54%|█████▍    | 21/39 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003489   0.04457  0.004435     4.199:  56%|█████▋    | 22/39 [00:36<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640  0.003486   0.04449  0.004433     4.193:  59%|█████▉    | 23/39 [00:36<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003482   0.04441  0.004421     4.185:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640   0.00348    0.0443  0.004404     4.175:  64%|██████▍   | 25/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1969       640  0.003475    0.0442   0.00442     4.168:  67%|██████▋   | 26/39 [00:38<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.608      0.384      0.408      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.599      0.385      0.406      0.228
                   0        738       1052      0.598      0.502      0.519       0.25
                   1        738         44      0.581      0.127      0.239      0.108
                   2        738       8622      0.748      0.691       0.74      0.468
                   3        738        151       0.56      0.384      0.432      0.325
                   4        738        467      0.497       0.57      0.526      0.368
                   5        738         70      0.449      0.371      0.289      0.144
                   6        738         65      0.283     0.0615      0.162     0.0681
                   7        738       1619      0.597      0.576      0.574      0.238
                   8        738       2845      0.672      0.572      0.582      0.307
                   9        738          2          1          0   0.000311    0.00028

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:39:12.253950218 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31335 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round028_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round028_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client5_residential_night_stable_train' images and labels...4885 found, 2892 missing, 0 empty, 0 corrupted: 100%|██████████| 7777/7777 [00:00<00:00, 17678.40it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.350561087403193
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round028_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2892 missing, 0 empty, 0 corrupted: 100%|██████████| 7777/7777 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:39:28.848536359 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:39:28.889176747 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1944       640  0.003539   0.04706  0.004914     4.441:   2%|▎         | 1/40 [00:21<14:07, 21.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1794       640  0.003476   0.04459  0.004731     4.223:   5%|▌         | 2/40 [00:22<05:58,  9.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1761       640  0.003475   0.04356  0.004691     4.138:   8%|▊         | 3/40 [00:23<03:24,  5.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1875       640  0.003474   0.04259  0.004657     4.058:  10%|█         | 4/40 [00:24<02:12,  3.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2110       640  0.003478   0.04262   0.00477     4.069:  12%|█▎        | 5/40 [00:24<01:30,  2.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1869       640  0.003494   0.04176  0.004713     3.997:  15%|█▌        | 6/40 [00:25<01:05,  1.93s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2173       640  0.003507   0.04204   0.00476     4.025:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2003       640  0.003513   0.04179  0.004706         4:  20%|██        | 8/40 [00:26<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1942       640  0.003507   0.04147  0.004703     3.974:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1987       640  0.003508   0.04109  0.004642     3.939:  25%|██▌       | 10/40 [00:28<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2117       640  0.003515   0.04079   0.00463     3.915:  28%|██▊       | 11/40 [00:28<00:25,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1827       640  0.003517    0.0403  0.004708     3.882:  30%|███       | 12/40 [00:29<00:22,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1976       640  0.003514   0.03997  0.004667     3.852:  32%|███▎      | 13/40 [00:30<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1975       640  0.003511   0.03973  0.004693     3.835:  35%|███▌      | 14/40 [00:30<00:19,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1961       640  0.003506   0.03942   0.00468     3.808:  38%|███▊      | 15/40 [00:31<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1611       640  0.003495   0.03892  0.004626     3.763:  40%|████      | 16/40 [00:32<00:16,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1808       640  0.003499   0.03866  0.004558     3.737:  42%|████▎     | 17/40 [00:32<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1998       640  0.003503   0.03846  0.004578     3.723:  45%|████▌     | 18/40 [00:33<00:14,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1649       640  0.003499   0.03804  0.004584      3.69:  48%|████▊     | 19/40 [00:34<00:14,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1928       640  0.003492    0.0378  0.004563     3.668:  50%|█████     | 20/40 [00:34<00:13,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1860       640   0.00349   0.03763   0.00459     3.657:  52%|█████▎    | 21/40 [00:35<00:12,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1803       640  0.003491   0.03741  0.004571     3.637:  55%|█████▌    | 22/40 [00:36<00:11,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      2000       640  0.003486   0.03725  0.004586     3.626:  57%|█████▊    | 23/40 [00:36<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1982       640  0.003485    0.0372    0.0046     3.623:  60%|██████    | 24/40 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1861       640   0.00348   0.03707   0.00462     3.614:  62%|██████▎   | 25/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.4G      1845       640  0.003476    0.0369  0.004621       3.6:  65%|██████▌   | 26/40 [00:38<00:09,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.571        0.4      0.406      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.561      0.401      0.404      0.228
                   0        738       1052      0.572       0.51      0.517      0.249
                   1        738         44       0.47      0.202      0.233      0.115
                   2        738       8622      0.714      0.705       0.74      0.471
                   3        738        151      0.558      0.391      0.423      0.318
                   4        738        467      0.489      0.589      0.539      0.377
                   5        738         70      0.328      0.377      0.289      0.149
                   6        738         65      0.237     0.0769       0.15     0.0608
                   7        738       1619      0.576      0.595      0.574      0.235
                   8        738       2845      0.661      0.567      0.574      0.305
                   9        738          2          1          0   0.000625   0.000563

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:40:54.378406742 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31336 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round028_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round028_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:41:11.417525846 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:41:11.469825744 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.02965    0.0323  0.003284     5.219:   3%|▎         | 1/31 [00:32<16:21, 32.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.02954   0.03188  0.003249     5.174:   6%|▋         | 2/31 [00:33<06:45, 13.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02888   0.03073  0.003184     5.024:  10%|▉         | 3/31 [00:34<03:42,  7.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02829   0.02927  0.002976     4.843:  13%|█▎        | 4/31 [00:35<02:18,  5.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640     0.028   0.02895  0.002954     4.792:  16%|█▌        | 5/31 [00:35<01:30,  3.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02794   0.02857  0.002978     4.759:  19%|█▉        | 6/31 [00:36<01:02,  2.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02797   0.02823  0.003037     4.739:  23%|██▎       | 7/31 [00:36<00:44,  1.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640    0.0278   0.02814  0.003041     4.718:  26%|██▌       | 8/31 [00:37<00:33,  1.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02784   0.02801  0.002973     4.706:  29%|██▉       | 9/31 [00:38<00:26,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02784   0.02804  0.002942     4.705:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02781     0.028  0.002943       4.7:  35%|███▌      | 11/31 [00:39<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02771   0.02773  0.002932      4.67:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02768   0.02766   0.00289     4.658:  42%|████▏     | 13/31 [00:40<00:13,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02769   0.02753  0.002864     4.647:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640   0.02769   0.02739  0.002909      4.64:  48%|████▊     | 15/31 [00:41<00:10,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640    0.0277   0.02727  0.002917     4.631:  52%|█████▏    | 16/31 [00:42<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02772   0.02727  0.002899     4.631:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02781   0.02738  0.002875     4.645:  58%|█████▊    | 18/31 [00:43<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640    0.0278   0.02728  0.002862     4.635:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02781   0.02745   0.00286      4.65:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02786   0.02751  0.002882      4.66:  68%|██████▊   | 21/31 [00:45<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02789    0.0276  0.002864     4.669:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640    0.0279   0.02767   0.00284     4.673:  74%|███████▍  | 23/31 [00:46<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02795    0.0278  0.002834     4.686:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02798   0.02781  0.002837      4.69:  81%|████████  | 25/31 [00:47<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02806    0.0279  0.002843     4.705:  84%|████████▍ | 26/31 [00:48<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.552      0.408      0.395      0.215
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.539      0.409      0.393      0.215
                   0        738       1052       0.49      0.525      0.499      0.235
                   1        738         44      0.469      0.182      0.206     0.0832
                   2        738       8622      0.697      0.715      0.737       0.47
                   3        738        151      0.479      0.417      0.427      0.317
                   4        738        467      0.475      0.582      0.516      0.353
                   5        738         70      0.324        0.4      0.292      0.128
                   6        738         65      0.288      0.108      0.154      0.056
                   7        738       1619      0.566      0.593      0.557      0.227
                   8        738       2845      0.602      0.572      0.547      0.282
                   9        738          2          1          0   0.000553   0.000497

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round028_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 20:42:50.510898952 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round029 phase_round=29 ===

02 head-to-full DQA:  88%|████████▊ | 28/32 [6:35:31<56:17, 844.45s/round, elapsed=6h35m31s, eta=56m30s, phase=phase1_head, round=28]  EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round029 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round029 client0_highway_day: pseudo scan 250/1500 images, kept 2331 boxes
round029 client0_highway_day: pseudo scan 500/1500 images, kept 4741 boxes
round029 client0_highway_day: pseudo scan 750/1500 images, kept 7048 boxes
round029 client0_highway_day: pseudo scan 1000/1500 images, kept 9378 boxes
round029 client0_highway_day: pseudo scan 1250/1500 images, kept 11681 boxes
round029 client0_highway_day: pseudo scan 1500/1500 images, kept 14042 boxes
{
  "round": "round029",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round028_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1490,
  "pseudo_boxes_kept": 11060,
  "boxes_per_kept_image": 7.422818791946309,
  "mean_conf": 0.8444583131839095,
  "mean_stability": 0.9412700541142314,
  "mean_score": 0.7981428545375557,
  "class_counts": {
    "0": 161,
    "2": 6319,
    "3": 116,
    "4": 560,
    "5": 7,
    "7": 552,
    "8": 3345
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_client0_highway_day_stable_boxes.csv"
}
round029 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round029 client1_highway_night: pseudo scan 250/1500 images, kept 1409 boxes
round029 client1_highway_night: pseudo scan 500/1500 images, kept 2896 boxes
round029 client1_highway_night: pseudo scan 750/1500 images, kept 4419 boxes
round029 client1_highway_night: pseudo scan 1000/1500 images, kept 5854 boxes
round029 client1_highway_night: pseudo scan 1250/1500 images, kept 7335 boxes
round029 client1_highway_night: pseudo scan 1500/1500 images, kept 8762 boxes
{
  "round": "round029",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round028_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1425,
  "pseudo_boxes_kept": 7427,
  "boxes_per_kept_image": 5.211929824561404,
  "mean_conf": 0.7656530535355927,
  "mean_stability": 0.9197783017280494,
  "mean_score": 0.7085693213952656,
  "class_counts": {
    "0": 68,
    "2": 3943,
    "3": 26,
    "4": 149,
    "5": 9,
    "7": 635,
    "8": 2597
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_client1_highway_night_stable_boxes.csv"
}
round029 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round029 client2_citystreet_day: pseudo scan 250/1500 images, kept 2662 boxes
round029 client2_citystreet_day: pseudo scan 500/1500 images, kept 5360 boxes
round029 client2_citystreet_day: pseudo scan 750/1500 images, kept 8083 boxes
round029 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10818 boxes
round029 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13497 boxes
round029 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16135 boxes
{
  "round": "round029",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round028_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13666,
  "boxes_per_kept_image": 9.14113712374582,
  "mean_conf": 0.8442933614918171,
  "mean_stability": 0.9385917220320827,
  "mean_score": 0.7960380845187621,
  "class_counts": {
    "0": 1523,
    "2": 7261,
    "3": 207,
    "4": 580,
    "5": 68,
    "7": 1482,
    "8": 2545
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_client2_citystreet_day_stable_boxes.csv"
}
round029 client3_citystreet_night: pseudo scan 1/1500 images, kept 5 boxes
round029 client3_citystreet_night: pseudo scan 250/1500 images, kept 2118 boxes
round029 client3_citystreet_night: pseudo scan 500/1500 images, kept 4229 boxes
round029 client3_citystreet_night: pseudo scan 750/1500 images, kept 6276 boxes
round029 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8269 boxes
round029 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10485 boxes
round029 client3_citystreet_night: pseudo scan 1500/1500 images, kept 12558 boxes
{
  "round": "round029",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round028_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1468,
  "pseudo_boxes_kept": 10844,
  "boxes_per_kept_image": 7.386920980926431,
  "mean_conf": 0.7558303568903831,
  "mean_stability": 0.9139083301733008,
  "mean_score": 0.6954833126808726,
  "class_counts": {
    "0": 564,
    "2": 5652,
    "3": 57,
    "4": 148,
    "5": 32,
    "7": 2086,
    "8": 2305
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_client3_citystreet_night_stable_boxes.csv"
}
round029 client4_residential_day: pseudo scan 1/1500 images, kept 8 boxes
round029 client4_residential_day: pseudo scan 250/1500 images, kept 2572 boxes
round029 client4_residential_day: pseudo scan 500/1500 images, kept 5132 boxes
round029 client4_residential_day: pseudo scan 750/1500 images, kept 7643 boxes
round029 client4_residential_day: pseudo scan 1000/1500 images, kept 10075 boxes
round029 client4_residential_day: pseudo scan 1250/1500 images, kept 12564 boxes
round029 client4_residential_day: pseudo scan 1500/1500 images, kept 15000 boxes
{
  "round": "round029",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round028_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1487,
  "pseudo_boxes_kept": 9802,
  "boxes_per_kept_image": 6.591795561533289,
  "mean_conf": 0.8745040971389767,
  "mean_stability": 0.9486560853761791,
  "mean_score": 0.8331185838014998,
  "class_counts": {
    "0": 410,
    "2": 6750,
    "3": 65,
    "4": 307,
    "5": 44,
    "7": 523,
    "8": 1703
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_client4_residential_day_stable_boxes.csv"
}
round029 client5_residential_night: pseudo scan 1/1500 images, kept 5 boxes
round029 client5_residential_night: pseudo scan 250/1500 images, kept 1963 boxes
round029 client5_residential_night: pseudo scan 500/1500 images, kept 3932 boxes
round029 client5_residential_night: pseudo scan 750/1500 images, kept 5843 boxes
round029 client5_residential_night: pseudo scan 1000/1500 images, kept 7840 boxes
round029 client5_residential_night: pseudo scan 1250/1500 images, kept 9809 boxes
round029 client5_residential_night: pseudo scan 1500/1500 images, kept 11759 boxes
{
  "round": "round029",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round028_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1447,
  "pseudo_boxes_kept": 7448,
  "boxes_per_kept_image": 5.147201105736006,
  "mean_conf": 0.8119708183236524,
  "mean_stability": 0.9304353054272757,
  "mean_score": 0.7589039071399754,
  "class_counts": {
    "0": 122,
    "2": 5292,
    "3": 29,
    "4": 95,
    "5": 22,
    "7": 668,
    "8": 1220
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round029_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31337 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round029_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round029_phase1_head_client0_highway_day_start.pt

self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7861 [00:00<?, ?it/s]

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client0_highway_day_stable_train' images and labels...5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<00:00, 11863.32it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.838714938030007
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2502 missing, 0 empty, 0 corrupted: 100%|██████████| 7861/7861 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 20:45:05.380065022 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 20:45:05.415322372 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1970       640   0.00346   0.04549  0.005646     4.368:   3%|▎         | 1/39 [00:21<13:28, 21.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003466   0.04845  0.004857     4.542:   5%|▌         | 2/39 [00:22<05:43,  9.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640   0.00348   0.04723  0.004807     4.441:   8%|▊         | 3/39 [00:23<03:16,  5.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1758       640  0.003453   0.04661  0.004685      4.38:  10%|█         | 4/39 [00:23<02:07,  3.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1914       640  0.003463   0.04659  0.004701      4.38:  13%|█▎        | 5/39 [00:24<01:26,  2.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1796       640  0.003467   0.04567  0.004551     4.295:  15%|█▌        | 6/39 [00:25<01:02,  1.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2129       640  0.003471   0.04533  0.004463     4.261:  18%|█▊        | 7/39 [00:25<00:47,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2017       640  0.003488   0.04515  0.004517     4.252:  21%|██        | 8/39 [00:26<00:37,  1.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2047       640  0.003494   0.04508  0.004548      4.25:  23%|██▎       | 9/39 [00:27<00:30,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2133       640  0.003507   0.04517  0.004556     4.259:  26%|██▌       | 10/39 [00:27<00:26,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2056       640   0.00351   0.04478  0.004555     4.228:  28%|██▊       | 11/39 [00:28<00:23,  1.21it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2000       640  0.003515   0.04477  0.004645     4.234:  31%|███       | 12/39 [00:28<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2124       640  0.003508   0.04457  0.004652     4.219:  33%|███▎      | 13/39 [00:29<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2125       640   0.00351   0.04454  0.004597     4.211:  36%|███▌      | 14/39 [00:30<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1919       640  0.003514   0.04429  0.004547     4.188:  38%|███▊      | 15/39 [00:30<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1994       640  0.003518   0.04403  0.004546     4.167:  41%|████      | 16/39 [00:31<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1846       640  0.003519   0.04393  0.004577     4.162:  44%|████▎     | 17/39 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2168       640  0.003518   0.04377  0.004538     4.146:  46%|████▌     | 18/39 [00:32<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003517   0.04344  0.004541      4.12:  49%|████▊     | 19/39 [00:33<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2125       640  0.003512   0.04337  0.004505     4.111:  51%|█████▏    | 20/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2184       640  0.003513    0.0434  0.004478     4.111:  54%|█████▍    | 21/39 [00:34<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2061       640  0.003517   0.04334   0.00446     4.106:  56%|█████▋    | 22/39 [00:35<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1999       640  0.003509   0.04325  0.004442     4.096:  59%|█████▉    | 23/39 [00:35<00:10,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2144       640  0.003506   0.04322  0.004423     4.092:  62%|██████▏   | 24/39 [00:36<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1904       640  0.003505   0.04308  0.004434     4.081:  64%|██████▍   | 25/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003504   0.04296  0.004402     4.069:  67%|██████▋   | 26/39 [00:37<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.601      0.393       0.41      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937       0.59      0.394      0.407      0.227
                   0        738       1052      0.556      0.524      0.524      0.249
                   1        738         44      0.568      0.182      0.237      0.105
                   2        738       8622      0.745      0.702      0.745      0.472
                   3        738        151      0.591      0.391      0.429      0.318
                   4        738        467      0.504      0.561      0.533      0.375
                   5        738         70      0.403        0.4      0.287      0.145
                   6        738         65      0.253     0.0615      0.164     0.0669
                   7        738       1619      0.587      0.579      0.576      0.236
                   8        738       2845      0.694      0.542      0.579      0.303
                   9        738          2          1          0   0.000574   0.000517

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:46:30.434686034 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31338 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round029_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round029_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client1_highway_night_stable_train' images and labels...:   0%|          | 0/7731 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client1_highway_night_stable_train' images and labels...4895 found, 2836 missing, 0 empty, 0 corrupted: 100%|██████████| 7731/7731 [00:00<00:00, 9928.25it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.41879663438641
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2836 missing, 0 empty, 0 corrupted: 100%|██████████| 7731/7731 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:46:47.626323080 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:46:47.652121240 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1885       640  0.003673    0.0454  0.005399     4.358:   2%|▎         | 1/40 [00:22<14:28, 22.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1953       640  0.003557   0.04378  0.004807     4.171:   5%|▌         | 2/40 [00:23<06:09,  9.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1738       640   0.00352   0.04312  0.004483      4.09:   8%|▊         | 3/40 [00:24<03:30,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003474   0.04152  0.004625      3.97:  10%|█         | 4/40 [00:24<02:15,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1862       640  0.003444   0.04078  0.004536     3.901:  12%|█▎        | 5/40 [00:25<01:32,  2.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1790       640  0.003468   0.04015  0.004546     3.853:  15%|█▌        | 6/40 [00:26<01:06,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2016       640  0.003462   0.03994  0.004608     3.841:  18%|█▊        | 7/40 [00:27<00:52,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1847       640  0.003442   0.03948  0.004586       3.8:  20%|██        | 8/40 [00:27<00:40,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003444   0.03903  0.004545     3.762:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1965       640  0.003441   0.03892  0.004496     3.748:  25%|██▌       | 10/40 [00:28<00:28,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2102       640  0.003463   0.03869  0.004568     3.738:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640   0.00347   0.03833   0.00466     3.717:  30%|███       | 12/40 [00:30<00:22,  1.27it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1819       640  0.003474   0.03799  0.004591     3.684:  32%|███▎      | 13/40 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2015       640   0.00348   0.03792  0.004612     3.681:  35%|███▌      | 14/40 [00:31<00:18,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003485   0.03785  0.004603     3.675:  38%|███▊      | 15/40 [00:32<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2038       640   0.00348   0.03768  0.004589      3.66:  40%|████      | 16/40 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1803       640   0.00349   0.03759  0.004593     3.654:  42%|████▎     | 17/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640   0.00349   0.03747  0.004599     3.645:  45%|████▌     | 18/40 [00:33<00:14,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1556       640  0.003489   0.03708  0.004568     3.611:  48%|████▊     | 19/40 [00:34<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640  0.003483   0.03697  0.004535     3.599:  50%|█████     | 20/40 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003481   0.03686  0.004509     3.588:  52%|█████▎    | 21/40 [00:35<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003486   0.03683  0.004493     3.585:  55%|█████▌    | 22/40 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640  0.003479   0.03681  0.004495     3.582:  57%|█████▊    | 23/40 [00:37<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2039       640  0.003482   0.03681  0.004511     3.584:  60%|██████    | 24/40 [00:37<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2073       640  0.003479   0.03674  0.004519     3.579:  62%|██████▎   | 25/40 [00:38<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1847       640  0.003477   0.03664  0.004517     3.571:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.632      0.382      0.405      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.622      0.383      0.404      0.228
                   0        738       1052      0.635      0.491      0.513      0.249
                   1        738         44      0.663      0.182      0.251      0.121
                   2        738       8622      0.749      0.696      0.744      0.473
                   3        738        151      0.579      0.391      0.418      0.313
                   4        738        467      0.515      0.565      0.537      0.379
                   5        738         70      0.445      0.343      0.276      0.139
                   6        738         65      0.344     0.0615      0.163     0.0667
                   7        738       1619      0.603      0.563      0.567      0.234
                   8        738       2845      0.692       0.54      0.575      0.301
                   9        738          2          1          0   0.000649   0.000584

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:48:13.955919174 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31339 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round029_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round029_phase1_head_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client2_citystreet_day_stable_train' images and labels...5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<00:00, 10407.10it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7871/7871 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:48:30.508619016 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:48:30.560055235 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1949       640  0.003493   0.05677  0.004592     5.188:   3%|▎         | 1/39 [00:21<13:41, 21.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2115       640  0.003513   0.05727  0.004662     5.236:   5%|▌         | 2/39 [00:22<05:48,  9.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1890       640  0.003497   0.05485  0.004578     5.034:   8%|▊         | 3/39 [00:23<03:19,  5.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003492   0.05291  0.004642     4.883:  10%|█         | 4/39 [00:24<02:09,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2180       640   0.00349   0.05213  0.004552     4.813:  13%|█▎        | 5/39 [00:25<01:29,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1564       640  0.003469   0.05001  0.004505     4.639:  15%|█▌        | 6/39 [00:25<01:04,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003497   0.04976  0.004646     4.632:  18%|█▊        | 7/39 [00:26<00:49,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1879       640  0.003485   0.04902  0.004617      4.57:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003495   0.04898  0.004532     4.561:  23%|██▎       | 9/39 [00:27<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1851       640  0.003483   0.04842  0.004514     4.514:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2053       640   0.00349   0.04811  0.004538     4.491:  28%|██▊       | 11/39 [00:29<00:24,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1720       640  0.003494   0.04763  0.004583     4.457:  31%|███       | 12/39 [00:29<00:21,  1.26it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2188       640  0.003505   0.04758  0.004553     4.451:  33%|███▎      | 13/39 [00:30<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2065       640  0.003514   0.04742  0.004514     4.436:  36%|███▌      | 14/39 [00:30<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1968       640  0.003516   0.04722  0.004523     4.421:  38%|███▊      | 15/39 [00:31<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003519   0.04698  0.004518     4.401:  41%|████      | 16/39 [00:32<00:15,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003521   0.04686  0.004517     4.392:  44%|████▎     | 17/39 [00:32<00:14,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2086       640  0.003513   0.04675  0.004484      4.38:  46%|████▌     | 18/39 [00:33<00:13,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640   0.00351   0.04642   0.00445      4.35:  49%|████▊     | 19/39 [00:34<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2175       640  0.003509    0.0464  0.004461      4.35:  51%|█████▏    | 20/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1871       640  0.003501   0.04623  0.004427     4.333:  54%|█████▍    | 21/39 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1933       640  0.003495   0.04626  0.004414     4.334:  56%|█████▋    | 22/39 [00:35<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640  0.003494   0.04612  0.004425     4.323:  59%|█████▉    | 23/39 [00:36<00:10,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2081       640  0.003492   0.04613  0.004404     4.322:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2034       640   0.00349   0.04604  0.004388     4.314:  64%|██████▍   | 25/39 [00:37<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003489   0.04594  0.004406     4.306:  67%|██████▋   | 26/39 [00:38<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.554      0.404      0.404      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.568      0.395      0.402      0.226
                   0        738       1052      0.667      0.478       0.52      0.247
                   1        738         44      0.437      0.159      0.215     0.0992
                   2        738       8622      0.691      0.726      0.747      0.473
                   3        738        151      0.542      0.391      0.427      0.316
                   4        738        467      0.472      0.587      0.523      0.366
                   5        738         70      0.402      0.386      0.287       0.15
                   6        738         65      0.247     0.0615      0.151     0.0673
                   7        738       1619      0.578      0.585      0.568      0.235
                   8        738       2845      0.641      0.576       0.58      0.306
                   9        738          2          1          0    0.00039   0.000351

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client2_citystreet_day

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 20:49:56.101259985 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31340 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round029_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round029_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client3_citystreet_night_stable_train' images and labels...4883 found, 2934 missing, 0 empty, 0 corrupted: 100%|██████████| 7817/7817 [00:00<00:00, 10507.83it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.299779458097039
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2934 missing, 0 empty, 0 corrupted: 100%|██████████| 7817/7817 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:50:13.863723317 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:50:13.885802289 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1882       640  0.003436   0.04562  0.005063     4.329:   2%|▎         | 1/40 [00:22<14:34, 22.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003392   0.04491  0.004934     4.259:   5%|▌         | 2/40 [00:23<06:10,  9.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1778       640   0.00341   0.04419  0.004924     4.202:   8%|▊         | 3/40 [00:24<03:30,  5.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1769       640  0.003421    0.0436  0.004805     4.146:  10%|█         | 4/40 [00:25<02:16,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1818       640  0.003432   0.04283   0.00473     4.079:  12%|█▎        | 5/40 [00:25<01:33,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003449   0.04231  0.004741      4.04:  15%|█▌        | 6/40 [00:26<01:07,  1.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003441   0.04148  0.004658     3.966:  18%|█▊        | 7/40 [00:26<00:50,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1959       640  0.003454   0.04146   0.00468     3.968:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640  0.003469   0.04131  0.004622     3.952:  22%|██▎       | 9/40 [00:28<00:33,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1892       640  0.003466    0.0409  0.004618     3.919:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1996       640  0.003477   0.04067  0.004666     3.905:  28%|██▊       | 11/40 [00:29<00:24,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1881       640  0.003482   0.04041  0.004648     3.883:  30%|███       | 12/40 [00:30<00:22,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2128       640  0.003489   0.04033  0.004679      3.88:  32%|███▎      | 13/40 [00:30<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003506   0.04009  0.004684     3.862:  35%|███▌      | 14/40 [00:31<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2104       640  0.003506   0.03987  0.004686     3.845:  38%|███▊      | 15/40 [00:32<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1937       640  0.003507   0.03965  0.004653     3.825:  40%|████      | 16/40 [00:32<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1641       640   0.00351   0.03927  0.004637     3.793:  42%|████▎     | 17/40 [00:33<00:15,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003512   0.03912  0.004655     3.783:  45%|████▌     | 18/40 [00:34<00:14,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1704       640  0.003514   0.03872  0.004659     3.751:  48%|████▊     | 19/40 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1995       640  0.003511   0.03869  0.004631     3.746:  50%|█████     | 20/40 [00:35<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2087       640  0.003516    0.0386  0.004687     3.744:  52%|█████▎    | 21/40 [00:36<00:12,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1802       640  0.003512   0.03844  0.004679      3.73:  55%|█████▌    | 22/40 [00:36<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2177       640  0.003512   0.03844  0.004671      3.73:  57%|█████▊    | 23/40 [00:37<00:11,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003508   0.03832  0.004643     3.718:  60%|██████    | 24/40 [00:38<00:10,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1892       640  0.003505    0.0382  0.004643     3.708:  62%|██████▎   | 25/40 [00:38<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2080       640  0.003508   0.03823  0.004618     3.709:  65%|██████▌   | 26/40 [00:39<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.63      0.379      0.401      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.21it/s]

                 all        738      14937       0.62       0.38        0.4      0.227
                   0        738       1052      0.621      0.482      0.506      0.244
                   1        738         44      0.698      0.158      0.245      0.123
                   2        738       8622      0.717      0.699      0.739      0.469
                   3        738        151      0.567       0.39      0.424      0.317
                   4        738        467      0.503      0.552      0.528      0.371
                   5        738         70      0.478      0.329      0.267      0.139
                   6        738         65      0.361     0.0615      0.153     0.0682
                   7        738       1619      0.589      0.578      0.567      0.232
                   8        738       2845      0.669      0.547      0.572      0.303
                   9        738          2          1          0   0.000668   0.000601

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 20:51:40.778395708 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31341 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round029_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round029_phase1_head_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client4_residential_day_stable_train' images and labels...:   0%|          | 0/7855 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client4_residential_day_stable_train' images and labels...5199 found, 2656 missing, 0 empty, 0 corrupted: 100%|██████████| 7855/7855 [00:00<00:00, 13485.92it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.642293444999195
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2656 missing, 0 empty, 0 corrupted: 100%|██████████| 7855/7855 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:51:56.092687974 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:51:56.178060775 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      1941       640  0.003635   0.05663  0.004981      5.22:   3%|▎         | 1/39 [00:22<14:20, 22.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2040       640  0.003531   0.05377  0.004529     4.946:   5%|▌         | 2/39 [00:23<06:04,  9.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1901       640  0.003507   0.05219  0.004938     4.851:   8%|▊         | 3/39 [00:24<03:27,  5.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2149       640  0.003506   0.05045  0.004896     4.708:  10%|█         | 4/39 [00:25<02:14,  3.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2011       640  0.003522   0.04958  0.004721     4.626:  13%|█▎        | 5/39 [00:25<01:31,  2.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1604       640  0.003507   0.04788  0.004647     4.483:  15%|█▌        | 6/39 [00:26<01:05,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1912       640   0.00352   0.04741  0.004654     4.447:  18%|█▊        | 7/39 [00:27<00:49,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2038       640  0.003525   0.04702  0.004677     4.418:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2215       640  0.003513    0.0473   0.00464     4.436:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1910       640  0.003501   0.04716  0.004595     4.421:  26%|██▌       | 10/39 [00:29<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1792       640  0.003504   0.04651  0.004546     4.365:  28%|██▊       | 11/39 [00:29<00:23,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1928       640  0.003505   0.04608  0.004614     4.336:  31%|███       | 12/39 [00:30<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2021       640   0.00351   0.04595  0.004566     4.322:  33%|███▎      | 13/39 [00:31<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2107       640  0.003514   0.04575   0.00453     4.303:  36%|███▌      | 14/39 [00:31<00:17,  1.41it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1956       640  0.003513   0.04538  0.004495     4.271:  38%|███▊      | 15/39 [00:32<00:16,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1899       640  0.003516   0.04515    0.0045     4.253:  41%|████      | 16/39 [00:32<00:15,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003508   0.04494   0.00448     4.234:  44%|████▎     | 17/39 [00:33<00:14,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2019       640   0.00351   0.04475  0.004479     4.219:  46%|████▌     | 18/39 [00:34<00:13,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1828       640  0.003505   0.04443  0.004446      4.19:  49%|████▊     | 19/39 [00:34<00:12,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003499   0.04437    0.0044     4.181:  51%|█████▏    | 20/39 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2089       640  0.003495   0.04426  0.004358     4.169:  54%|█████▍    | 21/39 [00:36<00:11,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003493   0.04414  0.004339     4.158:  56%|█████▋    | 22/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1967       640  0.003491   0.04406  0.004312     4.149:  59%|█████▉    | 23/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003486   0.04399  0.004333     4.145:  62%|██████▏   | 24/39 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1911       640  0.003486   0.04386  0.004325     4.134:  64%|██████▍   | 25/39 [00:38<00:08,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2101       640  0.003484   0.04382  0.004341     4.132:  67%|██████▋   | 26/39 [00:39<00:08,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.546      0.411      0.406      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937       0.55      0.401      0.404      0.227
                   0        738       1052      0.551       0.52       0.52      0.247
                   1        738         44      0.435      0.159      0.225      0.102
                   2        738       8622      0.722      0.704      0.741      0.468
                   3        738        151      0.501      0.397       0.43      0.326
                   4        738        467      0.473      0.595      0.528      0.371
                   5        738         70      0.382      0.386        0.3      0.157
                   6        738         65      0.247     0.0615      0.141     0.0606
                   7        738       1619      0.557      0.599      0.569      0.237
                   8        738       2845      0.632      0.588      0.583      0.307
                   9        738          2          1          0   0.000342   0.000308

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:53:22.311645394 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31342 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round029_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round029_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client5_residential_night_stable_train' images and labels...4885 found, 2890 missing, 0 empty, 0 corrupted: 100%|██████████| 7775/7775 [00:00<00:00, 14212.84it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.352987669933608
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round029_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2890 missing, 0 empty, 0 corrupted: 100%|██████████| 7775/7775 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 20:53:37.185534411 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 20:53:37.189600183 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2069       640  0.003522    0.0488  0.004138     4.517:   2%|▎         | 1/40 [00:22<14:24, 22.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1780       640  0.003481   0.04576   0.00442     4.293:   5%|▌         | 2/40 [00:23<06:07,  9.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1915       640  0.003476   0.04487  0.004535     4.231:   8%|▊         | 3/40 [00:23<03:29,  5.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1823       640  0.003463     0.044  0.004508     4.158:  10%|█         | 4/40 [00:24<02:15,  3.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1707       640  0.003443   0.04235  0.004376     4.013:  12%|█▎        | 5/40 [00:25<01:33,  2.66s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003459   0.04167  0.004349     3.958:  15%|█▌        | 6/40 [00:26<01:07,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2029       640  0.003478   0.04185  0.004415     3.979:  18%|█▊        | 7/40 [00:26<00:51,  1.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1883       640   0.00349   0.04147  0.004455     3.953:  20%|██        | 8/40 [00:27<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1978       640  0.003495   0.04112  0.004495     3.929:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2241       640  0.003501   0.04108   0.00452     3.928:  25%|██▌       | 10/40 [00:28<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2072       640  0.003506   0.04086  0.004515      3.91:  28%|██▊       | 11/40 [00:29<00:25,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1618       640  0.003506    0.0401  0.004518      3.85:  30%|███       | 12/40 [00:30<00:22,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2044       640  0.003513   0.03999  0.004536     3.843:  32%|███▎      | 13/40 [00:30<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1806       640  0.003505   0.03951  0.004532     3.804:  35%|███▌      | 14/40 [00:31<00:19,  1.36it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2042       640  0.003512    0.0394  0.004525     3.795:  38%|███▊      | 15/40 [00:32<00:17,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003509   0.03926  0.004514     3.783:  40%|████      | 16/40 [00:32<00:16,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1817       640   0.00351   0.03906  0.004482     3.764:  42%|████▎     | 17/40 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1849       640  0.003505   0.03872  0.004482     3.737:  45%|████▌     | 18/40 [00:34<00:14,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1848       640  0.003501   0.03841  0.004484     3.712:  48%|████▊     | 19/40 [00:34<00:14,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2116       640  0.003498   0.03842  0.004488     3.713:  50%|█████     | 20/40 [00:35<00:13,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1983       640  0.003496   0.03825  0.004492     3.699:  52%|█████▎    | 21/40 [00:36<00:12,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2191       640  0.003498   0.03825  0.004465     3.697:  55%|█████▌    | 22/40 [00:36<00:12,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1827       640  0.003493     0.038  0.004485     3.678:  57%|█████▊    | 23/40 [00:37<00:11,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1925       640  0.003489   0.03789  0.004493      3.67:  60%|██████    | 24/40 [00:38<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1808       640  0.003484   0.03767  0.004483     3.651:  62%|██████▎   | 25/40 [00:38<00:09,  1.56it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2101       640  0.003478   0.03759  0.004476     3.643:  65%|██████▌   | 26/40 [00:39<00:08,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.613      0.388      0.406      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.29it/s]

                 all        738      14937      0.599      0.388      0.403      0.227
                   0        738       1052      0.624      0.497      0.518      0.247
                   1        738         44       0.57      0.182       0.23      0.103
                   2        738       8622      0.739      0.694       0.74       0.47
                   3        738        151      0.627      0.384       0.42      0.315
                   4        738        467      0.528      0.555      0.539      0.381
                   5        738         70       0.37      0.386      0.286      0.152
                   6        738         65      0.259     0.0615       0.15     0.0624
                   7        738       1619      0.595      0.575      0.573      0.236
                   8        738       2845      0.681       0.55      0.574      0.304
                   9        738          2          1          0   0.000686   0.000617

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 20:55:02.963974738 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31343 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round029_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round029_phase1_head_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 20:55:19.461413453 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 20:55:19.461588840 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.02977   0.03243  0.003292     5.239:   3%|▎         | 1/31 [00:32<16:12, 32.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.02946   0.03165  0.003228     5.147:   6%|▋         | 2/31 [00:33<06:40, 13.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02876   0.03042  0.003151     4.986:  10%|▉         | 3/31 [00:34<03:41,  7.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02824   0.02906   0.00295     4.821:  13%|█▎        | 4/31 [00:34<02:17,  5.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02796   0.02873  0.002927     4.769:  16%|█▌        | 5/31 [00:35<01:30,  3.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02789   0.02833   0.00295     4.734:  19%|█▉        | 6/31 [00:36<01:02,  2.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02792   0.02798  0.003008     4.713:  23%|██▎       | 7/31 [00:36<00:44,  1.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02774   0.02787  0.003009      4.69:  26%|██▌       | 8/31 [00:37<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02777   0.02772  0.002943     4.675:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02775   0.02773  0.002911     4.671:  32%|███▏      | 10/31 [00:38<00:20,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02768   0.02767  0.002911     4.661:  35%|███▌      | 11/31 [00:38<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02757   0.02739    0.0029     4.629:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02751    0.0273  0.002858     4.614:  42%|████▏     | 13/31 [00:40<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640    0.0275   0.02717  0.002833       4.6:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640    0.0275   0.02702  0.002878     4.592:  48%|████▊     | 15/31 [00:41<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640   0.02749    0.0269  0.002886     4.582:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02751    0.0269  0.002868     4.582:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02759   0.02701  0.002844     4.596:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02757   0.02691  0.002831     4.585:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02759   0.02707  0.002829     4.598:  65%|██████▍   | 20/31 [00:44<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02764   0.02712  0.002851     4.609:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02767   0.02722  0.002833     4.617:  71%|███████   | 22/31 [00:45<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02768   0.02728  0.002809     4.622:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640   0.02773   0.02741  0.002803     4.635:  77%|███████▋  | 24/31 [00:46<00:04,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02777   0.02742  0.002806      4.64:  81%|████████  | 25/31 [00:47<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02785   0.02751  0.002812     4.654:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.559      0.402      0.396      0.214
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.06it/s]

                 all        738      14937      0.547      0.404      0.395      0.214
                   0        738       1052      0.506      0.523      0.496      0.234
                   1        738         44      0.466      0.159      0.206     0.0819
                   2        738       8622      0.703      0.709      0.734      0.469
                   3        738        151      0.465      0.417      0.431      0.319
                   4        738        467      0.479       0.57      0.514      0.354
                   5        738         70      0.351        0.4      0.315      0.122
                   6        738         65      0.324      0.108      0.156     0.0567
                   7        738       1619      0.567      0.587      0.555      0.227
                   8        738       2845      0.611      0.562       0.54      0.279
                   9        738          2          1          0   0.000561   0.000505

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round029_phase1_head_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 20:56:58.597381650 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 1 head-only DQA: round030 phase_round=30 ===

02 head-to-full DQA:  91%|█████████ | 29/32 [6:49:39<42:16, 845.52s/round, elapsed=6h49m39s, eta=42m22s, phase=phase1_head, round=29]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round030 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round030 client0_highway_day: pseudo scan 250/1500 images, kept 2337 boxes
round030 client0_highway_day: pseudo scan 500/1500 images, kept 4749 boxes
round030 client0_highway_day: pseudo scan 750/1500 images, kept 7053 boxes
round030 client0_highway_day: pseudo scan 1000/1500 images, kept 9391 boxes
round030 client0_highway_day: pseudo scan 1250/1500 images, kept 11691 boxes
round030 client0_highway_day: pseudo scan 1500/1500 images, kept 14067 boxes
{
  "round": "round030",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round029_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1491,
  "pseudo_boxes_kept": 11069,
  "boxes_per_kept_image": 7.423876592890678,
  "mean_conf": 0.84626074558147,
  "mean_stability": 0.9401141938957293,
  "mean_score": 0.798932961791683,
  "class_counts": {
    "0": 162,
    "2": 6331,
    "3": 116,
    "4": 558,
    "5": 8,
    "7": 565,
    "8": 3329
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_client0_highway_day_stable_boxes.csv"
}
round030 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round030 client1_highway_night: pseudo scan 250/1500 images, kept 1406 boxes
round030 client1_highway_night: pseudo scan 500/1500 images, kept 2910 boxes
round030 client1_highway_night: pseudo scan 750/1500 images, kept 4433 boxes
round030 client1_highway_night: pseudo scan 1000/1500 images, kept 5850 boxes
round030 client1_highway_night: pseudo scan 1250/1500 images, kept 7354 boxes
round030 client1_highway_night: pseudo scan 1500/1500 images, kept 8772 boxes
{
  "round": "round030",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round029_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1428,
  "pseudo_boxes_kept": 7422,
  "boxes_per_kept_image": 5.197478991596639,
  "mean_conf": 0.76642450954483,
  "mean_stability": 0.9181151760456473,
  "mean_score": 0.7080187271698825,
  "class_counts": {
    "0": 71,
    "2": 3948,
    "3": 27,
    "4": 151,
    "5": 9,
    "7": 645,
    "8": 2571
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_client1_highway_night_stable_boxes.csv"
}
round030 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round030 client2_citystreet_day: pseudo scan 250/1500 images, kept 2667 boxes
round030 client2_citystreet_day: pseudo scan 500/1500 images, kept 5363 boxes
round030 client2_citystreet_day: pseudo scan 750/1500 images, kept 8086 boxes
round030 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10815 boxes
round030 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13496 boxes
round030 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16130 boxes
{
  "round": "round030",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round029_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1494,
  "pseudo_boxes_kept": 13630,
  "boxes_per_kept_image": 9.123159303882195,
  "mean_conf": 0.8463258898835452,
  "mean_stability": 0.9376878207908863,
  "mean_score": 0.7971726729237384,
  "class_counts": {
    "0": 1522,
    "2": 7259,
    "3": 210,
    "4": 588,
    "5": 66,
    "7": 1489,
    "8": 2496
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_client2_citystreet_day_stable_boxes.csv"
}
round030 client3_citystreet_night: pseudo scan 1/1500 images, kept 6 boxes
round030 client3_citystreet_night: pseudo scan 250/1500 images, kept 2118 boxes
round030 client3_citystreet_night: pseudo scan 500/1500 images, kept 4230 boxes
round030 client3_citystreet_night: pseudo scan 750/1500 images, kept 6282 boxes
round030 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8277 boxes
round030 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10486 boxes
round030 client3_citystreet_night: pseudo scan 1500/1500 images, kept 12583 boxes
{
  "round": "round030",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round029_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1470,
  "pseudo_boxes_kept": 10891,
  "boxes_per_kept_image": 7.408843537414966,
  "mean_conf": 0.7553729648110011,
  "mean_stability": 0.9120481615004795,
  "mean_score": 0.6937443538884448,
  "class_counts": {
    "0": 559,
    "2": 5663,
    "3": 59,
    "4": 156,
    "5": 28,
    "7": 2120,
    "8": 2306
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_client3_citystreet_night_stable_boxes.csv"
}
round030 client4_residential_day: pseudo scan 1/1500 images, kept 7 boxes
round030 client4_residential_day: pseudo scan 250/1500 images, kept 2581 boxes
round030 client4_residential_day: pseudo scan 500/1500 images, kept 5141 boxes
round030 client4_residential_day: pseudo scan 750/1500 images, kept 7658 boxes
round030 client4_residential_day: pseudo scan 1000/1500 images, kept 10084 boxes
round030 client4_residential_day: pseudo scan 1250/1500 images, kept 12573 boxes
round030 client4_residential_day: pseudo scan 1500/1500 images, kept 15002 boxes
{
  "round": "round030",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round029_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9766,
  "boxes_per_kept_image": 6.563172043010753,
  "mean_conf": 0.8765492113568415,
  "mean_stability": 0.9477840418603707,
  "mean_score": 0.8343069275978848,
  "class_counts": {
    "0": 407,
    "2": 6751,
    "3": 68,
    "4": 306,
    "5": 43,
    "7": 531,
    "8": 1660
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_client4_residential_day_stable_boxes.csv"
}
round030 client5_residential_night: pseudo scan 1/1500 images, kept 4 boxes
round030 client5_residential_night: pseudo scan 250/1500 images, kept 1956 boxes
round030 client5_residential_night: pseudo scan 500/1500 images, kept 3910 boxes
round030 client5_residential_night: pseudo scan 750/1500 images, kept 5826 boxes
round030 client5_residential_night: pseudo scan 1000/1500 images, kept 7818 boxes
round030 client5_residential_night: pseudo scan 1250/1500 images, kept 9745 boxes
round030 client5_residential_night: pseudo scan 1500/1500 images, kept 11697 boxes
{
  "round": "round030",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round029_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1443,
  "pseudo_boxes_kept": 7416,
  "boxes_per_kept_image": 5.139293139293139,
  "mean_conf": 0.8110559127839059,
  "mean_stability": 0.9290465971669976,
  "mean_score": 0.7569941026879023,
  "class_counts": {
    "0": 122,
    "2": 5264,
    "3": 29,
    "4": 94,
    "5": 20,
    "7": 681,
    "8": 1206
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round030_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31344 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round030_phase1_head_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round030_phase1_head_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client0_highway_day_stable_train' images and labels...:   0%|          | 0/7863 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client0_highway_day_stable_train' images and labels...5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<00:00, 20545.15it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client0_highway_day_stable_train.cache' images and labels... 5359 found, 2504 missing, 0 empty, 0 corrupted: 100%|██████████| 7863/7863 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 20:59:14.819327082 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 20:59:14.859934825 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2150       640   0.00371   0.05417  0.004982     5.029:   3%|▎         | 1/39 [00:21<13:45, 21.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003613   0.05073  0.004592     4.715:   5%|▌         | 2/39 [00:22<05:50,  9.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2028       640  0.003616   0.04936  0.004811     4.623:   8%|▊         | 3/39 [00:23<03:19,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1776       640  0.003617    0.0486  0.004786      4.56:  10%|█         | 4/39 [00:24<02:09,  3.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1991       640  0.003591   0.04822  0.004752     4.525:  13%|█▎        | 5/39 [00:25<01:28,  2.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1760       640  0.003546   0.04664  0.004541     4.378:  15%|█▌        | 6/39 [00:25<01:04,  1.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003543    0.0459  0.004543     4.319:  18%|█▊        | 7/39 [00:26<00:48,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1958       640  0.003551   0.04538  0.004678     4.288:  21%|██        | 8/39 [00:27<00:39,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2214       640  0.003563   0.04556  0.004704     4.307:  23%|██▎       | 9/39 [00:27<00:32,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2108       640   0.00357   0.04559  0.004718      4.31:  26%|██▌       | 10/39 [00:28<00:27,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2066       640  0.003567   0.04527  0.004692     4.283:  28%|██▊       | 11/39 [00:29<00:24,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003566   0.04525  0.004804      4.29:  31%|███       | 12/39 [00:29<00:22,  1.22it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1843       640  0.003551   0.04487  0.004776     4.256:  33%|███▎      | 13/39 [00:30<00:20,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2135       640  0.003547    0.0448  0.004723     4.246:  36%|███▌      | 14/39 [00:31<00:18,  1.34it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003548   0.04461  0.004684     4.227:  38%|███▊      | 15/39 [00:31<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003547   0.04433  0.004653     4.202:  41%|████      | 16/39 [00:32<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1686       640  0.003547   0.04406  0.004696     4.184:  44%|████▎     | 17/39 [00:33<00:15,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2088       640  0.003546   0.04382   0.00468     4.164:  46%|████▌     | 18/39 [00:33<00:14,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1710       640  0.003538    0.0434  0.004653     4.128:  49%|████▊     | 19/39 [00:34<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2250       640  0.003538    0.0434   0.00466     4.128:  51%|█████▏    | 20/39 [00:35<00:12,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2110       640  0.003533   0.04342  0.004644     4.128:  54%|█████▍    | 21/39 [00:35<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003532   0.04329   0.00463     4.116:  56%|█████▋    | 22/39 [00:36<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003527   0.04315  0.004596     4.102:  59%|█████▉    | 23/39 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1941       640  0.003526   0.04306  0.004591     4.094:  62%|██████▏   | 24/39 [00:37<00:09,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2023       640  0.003522   0.04299  0.004593     4.088:  64%|██████▍   | 25/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1980       640  0.003518   0.04293  0.004573     4.082:  67%|██████▋   | 26/39 [00:38<00:08,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.593      0.392      0.406      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.592      0.388      0.404      0.226
                   0        738       1052      0.558      0.514      0.516      0.248
                   1        738         44      0.522      0.159      0.225     0.0978
                   2        738       8622      0.753      0.698      0.744       0.47
                   3        738        151      0.635      0.397      0.423       0.32
                   4        738        467       0.52      0.548      0.533      0.376
                   5        738         70       0.39      0.384      0.272      0.139
                   6        738         65      0.258     0.0615       0.17     0.0673
                   7        738       1619      0.586      0.574      0.574      0.234
                   8        738       2845      0.695      0.548       0.58      0.303
                   9        738          2          1          0   0.000651   0.000586

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client0_highway_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 21:00:38.843997038 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31345 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round030_phase1_head_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round030_phase1_head_client1_highway_night_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client1_highway_night_stable_train' images and labels...:   0%|          | 0/7737 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client1_highway_night_stable_train' images and labels...4895 found, 2842 missing, 0 empty, 0 corrupted: 100%|██████████| 7737/7737 [00:00<00:00, 14103.28it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.411456680418915
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client1_highway_night_stable_train.cache' images and labels... 4895 found, 2842 missing, 0 empty, 0 corrupted: 100%|██████████| 7737/7737 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:00:53.954488993 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:00:53.971364245 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2166       640  0.003442    0.0469  0.004422     4.381:   2%|▎         | 1/40 [00:21<14:06, 21.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1993       640  0.003429   0.04491  0.004402     4.219:   5%|▌         | 2/40 [00:22<05:59,  9.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1998       640  0.003467    0.0449  0.004303     4.214:   8%|▊         | 3/40 [00:23<03:24,  5.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1831       640  0.003463   0.04343  0.004227      4.09:  10%|█         | 4/40 [00:24<02:13,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003486   0.04333   0.00442     4.099:  12%|█▎        | 5/40 [00:25<01:31,  2.62s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1776       640  0.003488    0.0418  0.004436     3.978:  15%|█▌        | 6/40 [00:25<01:06,  1.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1932       640  0.003503   0.04126  0.004459     3.938:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2079       640  0.003521   0.04151  0.004581     3.969:  20%|██        | 8/40 [00:27<00:39,  1.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2054       640  0.003535   0.04117  0.004563     3.941:  22%|██▎       | 9/40 [00:27<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2128       640  0.003536   0.04096  0.004612     3.928:  25%|██▌       | 10/40 [00:28<00:27,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2076       640   0.00354   0.04063  0.004609     3.902:  28%|██▊       | 11/40 [00:28<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003533   0.04008  0.004598     3.857:  30%|███       | 12/40 [00:29<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640   0.00353    0.0398  0.004567     3.831:  32%|███▎      | 13/40 [00:30<00:19,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003527   0.03964  0.004562     3.819:  35%|███▌      | 14/40 [00:30<00:18,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1902       640  0.003529   0.03936   0.00453     3.793:  38%|███▊      | 15/40 [00:31<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2006       640  0.003524    0.0391  0.004484     3.769:  40%|████      | 16/40 [00:32<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003529   0.03891  0.004487     3.754:  42%|████▎     | 17/40 [00:32<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1946       640  0.003523   0.03866  0.004457     3.731:  45%|████▌     | 18/40 [00:33<00:14,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1725       640   0.00352   0.03829   0.00447     3.702:  48%|████▊     | 19/40 [00:33<00:13,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1976       640  0.003517   0.03808  0.004467     3.685:  50%|█████     | 20/40 [00:34<00:12,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1825       640  0.003512   0.03778  0.004461      3.66:  52%|█████▎    | 21/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1704       640  0.003509   0.03745  0.004457     3.633:  55%|█████▌    | 22/40 [00:35<00:11,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2018       640  0.003505   0.03741  0.004433     3.628:  57%|█████▊    | 23/40 [00:36<00:10,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1949       640    0.0035   0.03738  0.004445     3.626:  60%|██████    | 24/40 [00:37<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1801       640  0.003496   0.03721   0.00444     3.611:  62%|██████▎   | 25/40 [00:37<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1820       640  0.003491   0.03702  0.004439     3.596:  65%|██████▌   | 26/40 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.593      0.396      0.407      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.583      0.397      0.406      0.226
                   0        738       1052      0.586       0.51      0.519      0.248
                   1        738         44      0.598      0.203      0.253      0.112
                   2        738       8622      0.716      0.709      0.741      0.471
                   3        738        151      0.559      0.397      0.425      0.316
                   4        738        467      0.505      0.557      0.539      0.378
                   5        738         70       0.37      0.386      0.271      0.134
                   6        738         65      0.234     0.0705      0.167     0.0686
                   7        738       1619      0.588      0.579      0.566      0.232
                   8        738       2845      0.674      0.556      0.575      0.301
                   9        738          2          1          0   0.000601   0.000541

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client1_highway_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 21:02:19.165780363 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31346 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round030_phase1_head_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round030_phase1_head_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client2_citystreet_day_stable_train' images and labels...5213 found, 2656 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<00:00, 12952.10it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.642293444999195
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client2_citystreet_day_stable_train.cache' images and labels... 5213 found, 2656 missing, 0 empty, 0 corrupted: 100%|██████████| 7869/7869 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 21:02:35.163292540 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 21:02:35.167284561 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0      5.8G      2090       640  0.003659    0.0569  0.004633     5.216:   3%|▎         | 1/39 [00:22<14:16, 22.55s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1913       640  0.003557   0.05524  0.004421     5.057:   5%|▌         | 2/39 [00:23<06:03,  9.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1892       640  0.003528   0.05333  0.004671     4.923:   8%|▊         | 3/39 [00:24<03:25,  5.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1891       640  0.003514   0.05152    0.0046     4.771:  10%|█         | 4/39 [00:25<02:12,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2035       640  0.003524   0.05084  0.004502     4.709:  13%|█▎        | 5/39 [00:25<01:30,  2.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1574       640  0.003495   0.04909  0.004483     4.565:  15%|█▌        | 6/39 [00:26<01:05,  1.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2055       640  0.003511   0.04894  0.004543     4.559:  18%|█▊        | 7/39 [00:27<00:49,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1970       640  0.003516   0.04858   0.00456     4.532:  21%|██        | 8/39 [00:27<00:39,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1967       640   0.00352   0.04851  0.004612     4.532:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1790       640  0.003505   0.04809  0.004565     4.492:  26%|██▌       | 10/39 [00:29<00:26,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2093       640  0.003517   0.04776  0.004552     4.466:  28%|██▊       | 11/39 [00:29<00:23,  1.20it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1847       640  0.003512   0.04736  0.004607     4.439:  31%|███       | 12/39 [00:30<00:20,  1.30it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003512   0.04724  0.004599     4.428:  33%|███▎      | 13/39 [00:30<00:18,  1.38it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1975       640  0.003519   0.04709   0.00453     4.411:  36%|███▌      | 14/39 [00:31<00:17,  1.45it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1986       640  0.003516   0.04682  0.004536     4.389:  38%|███▊      | 15/39 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1961       640  0.003515   0.04658  0.004533     4.371:  41%|████      | 16/39 [00:32<00:15,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1887       640  0.003515   0.04646  0.004526      4.36:  44%|████▎     | 17/39 [00:33<00:14,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1897       640  0.003515   0.04622  0.004529     4.341:  46%|████▌     | 18/39 [00:33<00:13,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1627       640  0.003513   0.04587  0.004487     4.309:  49%|████▊     | 19/39 [00:34<00:12,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2203       640  0.003512     0.046  0.004451     4.317:  51%|█████▏    | 20/39 [00:35<00:12,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2007       640  0.003512   0.04584  0.004424     4.302:  54%|█████▍    | 21/39 [00:35<00:11,  1.58it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1883       640  0.003508   0.04571  0.004425     4.291:  56%|█████▋    | 22/39 [00:36<00:10,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2049       640  0.003512   0.04559  0.004429     4.282:  59%|█████▉    | 23/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2070       640  0.003508    0.0456  0.004448     4.285:  62%|██████▏   | 24/39 [00:37<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1838       640  0.003508   0.04548  0.004429     4.274:  64%|██████▍   | 25/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1979       640  0.003506   0.04537   0.00445     4.266:  67%|██████▋   | 26/39 [00:38<00:08,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.557      0.403      0.403      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

                 all        738      14937      0.542      0.404        0.4      0.225
                   0        738       1052      0.618       0.49      0.511      0.245
                   1        738         44      0.407      0.187        0.2     0.0948
                   2        738       8622      0.684      0.726      0.746      0.472
                   3        738        151      0.487      0.397      0.423      0.316
                   4        738        467      0.458      0.587      0.524      0.368
                   5        738         70      0.357        0.4      0.299      0.152
                   6        738         65      0.222     0.0769      0.159      0.066
                   7        738       1619      0.564      0.591      0.565      0.234
                   8        738       2845      0.626      0.581      0.577      0.303
                   9        738          2          1          0   0.000439   0.000395

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client2_citystreet_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 21:04:02.329559954 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31347 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round030_phase1_head_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round030_phase1_head_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client3_citystreet_night_stable_train' images and labels...4883 found, 2938 missing, 0 empty, 0 corrupted: 100%|██████████| 7821/7821 [00:00<00:00, 9802.75it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.29496062992126
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client3_citystreet_night_stable_train.cache' images and labels... 4883 found, 2938 missing, 0 empty, 0 corrupted: 100%|██████████| 7821/7821 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:04:18.113722042 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:04:18.176444176 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2056       640  0.003693   0.05112  0.004834     4.772:   2%|▎         | 1/40 [00:22<14:51, 22.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1824       640  0.003617   0.04771  0.004991     4.506:   5%|▌         | 2/40 [00:23<06:18,  9.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2008       640   0.00357   0.04664   0.00463     4.387:   8%|▊         | 3/40 [00:24<03:34,  5.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1947       640  0.003543   0.04548    0.0046      4.29:  10%|█         | 4/40 [00:25<02:18,  3.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1821       640  0.003543   0.04427    0.0046     4.193:  12%|█▎        | 5/40 [00:26<01:34,  2.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1732       640   0.00352   0.04265  0.004609     4.062:  15%|█▌        | 6/40 [00:26<01:07,  2.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1850       640  0.003519   0.04176  0.004635     3.993:  18%|█▊        | 7/40 [00:27<00:51,  1.56s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1909       640  0.003511   0.04127  0.004619     3.952:  20%|██        | 8/40 [00:28<00:40,  1.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003516   0.04113   0.00461     3.941:  22%|██▎       | 9/40 [00:28<00:33,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1896       640  0.003516   0.04079    0.0046     3.912:  25%|██▌       | 10/40 [00:29<00:28,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640  0.003517   0.04047  0.004604     3.887:  28%|██▊       | 11/40 [00:30<00:25,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1771       640  0.003512    0.0399  0.004584      3.84:  30%|███       | 12/40 [00:30<00:22,  1.24it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1874       640  0.003513   0.03955  0.004619     3.814:  32%|███▎      | 13/40 [00:31<00:20,  1.31it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1964       640  0.003514    0.0393   0.00462     3.794:  35%|███▌      | 14/40 [00:32<00:19,  1.35it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1893       640  0.003514   0.03894  0.004653     3.769:  38%|███▊      | 15/40 [00:32<00:17,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2050       640  0.003511   0.03892   0.00464     3.765:  40%|████      | 16/40 [00:33<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1812       640  0.003513   0.03862   0.00463     3.741:  42%|████▎     | 17/40 [00:34<00:15,  1.44it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1992       640  0.003507   0.03848  0.004672     3.733:  45%|████▌     | 18/40 [00:34<00:15,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1801       640  0.003508   0.03823  0.004654     3.712:  48%|████▊     | 19/40 [00:35<00:14,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1873       640  0.003501   0.03804  0.004625     3.693:  50%|█████     | 20/40 [00:36<00:13,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1961       640  0.003504   0.03797  0.004608     3.686:  52%|█████▎    | 21/40 [00:36<00:12,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2079       640  0.003501    0.0379  0.004582     3.679:  55%|█████▌    | 22/40 [00:37<00:12,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1938       640  0.003498   0.03787  0.004579     3.676:  57%|█████▊    | 23/40 [00:38<00:11,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1740       640  0.003498    0.0377  0.004616     3.665:  60%|██████    | 24/40 [00:38<00:10,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2027       640  0.003494   0.03768  0.004604     3.662:  62%|██████▎   | 25/40 [00:39<00:09,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1930       640  0.003491    0.0376  0.004595     3.655:  65%|██████▌   | 26/40 [00:40<00:09,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.609      0.387      0.406      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.596      0.388      0.403      0.228
                   0        738       1052      0.597      0.481      0.506      0.246
                   1        738         44      0.607      0.182      0.238      0.124
                   2        738       8622      0.729      0.701      0.741      0.471
                   3        738        151      0.594      0.397      0.426      0.318
                   4        738        467      0.506      0.557      0.535      0.379
                   5        738         70      0.422      0.365      0.278       0.14
                   6        738         65      0.256     0.0615      0.164     0.0674
                   7        738       1619      0.586      0.578      0.571      0.233
                   8        738       2845      0.668      0.559      0.573      0.302
                   9        738          2          1          0    0.00069   0.000621

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client3_citystreet_night

1 epochs completed in 0.025 hours.
Destroying process group...
[rank0]:[W507 21:05:47.092633549 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31348 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round030_phase1_head_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round030_phase1_head_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client4_residential_day_stable_train' images and labels...5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<00:00, 9646.24it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client4_residential_day_stable_train.cache' images and labels... 5199 found, 2658 missing, 0 empty, 0 corrupted: 100%|██████████| 7857/7857 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:06:05.460269700 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:06:05.461299483 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      1976       640  0.003615   0.05656  0.004712     5.191:   3%|▎         | 1/39 [00:22<14:29, 22.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2142       640  0.003574   0.05629  0.004565     5.154:   5%|▌         | 2/39 [00:23<06:08,  9.96s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1988       640  0.003543   0.05327  0.004652     4.917:   8%|▊         | 3/39 [00:24<03:29,  5.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2075       640  0.003533   0.05158  0.004731     4.787:  10%|█         | 4/39 [00:25<02:14,  3.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2226       640  0.003522   0.05101  0.004687     4.737:  13%|█▎        | 5/39 [00:26<01:32,  2.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1721       640    0.0035   0.04923  0.004589     4.585:  15%|█▌        | 6/39 [00:26<01:06,  2.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2003       640  0.003524   0.04881  0.004653     4.559:  18%|█▊        | 7/39 [00:27<00:50,  1.58s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640   0.00352   0.04821  0.004625     4.508:  21%|██        | 8/39 [00:28<00:39,  1.28s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2107       640  0.003518   0.04803  0.004494     4.483:  23%|██▎       | 9/39 [00:28<00:32,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1894       640  0.003514   0.04768  0.004564      4.46:  26%|██▌       | 10/39 [00:29<00:27,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1872       640   0.00351   0.04706  0.004563      4.41:  28%|██▊       | 11/39 [00:30<00:23,  1.17it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1943       640  0.003508   0.04672  0.004581     4.384:  31%|███       | 12/39 [00:30<00:21,  1.25it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2165       640   0.00352   0.04667  0.004522     4.377:  33%|███▎      | 13/39 [00:31<00:19,  1.33it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003517   0.04626  0.004479      4.34:  36%|███▌      | 14/39 [00:32<00:17,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2013       640  0.003522   0.04608  0.004486     4.327:  38%|███▊      | 15/39 [00:32<00:16,  1.42it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1974       640  0.003527   0.04577  0.004501     4.304:  41%|████      | 16/39 [00:33<00:15,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1906       640  0.003525   0.04551  0.004517     4.285:  44%|████▎     | 17/39 [00:34<00:14,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1868       640  0.003519   0.04526  0.004482     4.261:  46%|████▌     | 18/39 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1870       640  0.003515   0.04495  0.004452     4.233:  49%|████▊     | 19/39 [00:35<00:13,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2048       640   0.00351   0.04491  0.004447     4.229:  51%|█████▏    | 20/39 [00:35<00:12,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1921       640  0.003502   0.04471   0.00444     4.212:  54%|█████▍    | 21/39 [00:36<00:11,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1989       640  0.003503   0.04475   0.00444     4.215:  56%|█████▋    | 22/39 [00:37<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2010       640    0.0035   0.04466  0.004439     4.208:  59%|█████▉    | 23/39 [00:37<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003496   0.04458  0.004427       4.2:  62%|██████▏   | 24/39 [00:38<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1923       640  0.003494   0.04446  0.004409     4.189:  64%|██████▍   | 25/39 [00:39<00:09,  1.53it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1969       640  0.003489   0.04436  0.004425     4.182:  67%|██████▋   | 26/39 [00:39<00:08,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.596      0.387      0.406      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.587      0.391      0.406      0.227
                   0        738       1052      0.584      0.502      0.518      0.249
                   1        738         44      0.538      0.159      0.243      0.107
                   2        738       8622      0.739      0.692      0.738      0.466
                   3        738        151      0.571      0.397       0.43      0.324
                   4        738        467      0.498      0.572      0.527       0.37
                   5        738         70      0.411      0.371      0.291      0.144
                   6        738         65      0.273     0.0615      0.159      0.069
                   7        738       1619      0.591      0.578      0.574      0.236
                   8        738       2845      0.664      0.572      0.579      0.306
                   9        738          2          1          0   0.000324   0.000291

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client4_residential_day

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 21:07:31.461026398 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31349 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round030_phase1_head_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round030_phase1_head_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client5_residential_night_stable_train' images and labels...:   0%|          | 0/7767 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client5_residential_night_stable_train' images and labels...4885 found, 2882 missing, 0 empty, 0 corrupted: 100%|██████████| 7767/7767 [00:00<00:00, 12551.32it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.362701676684594
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round030_client5_residential_night_stable_train.cache' images and labels... 4885 found, 2882 missing, 0 empty, 0 corrupted: 100%|██████████| 7767/7767 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:07:47.174415806 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:07:47.185966489 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     5.87G      2010       640  0.003427   0.04781  0.003861     4.408:   2%|▎         | 1/40 [00:22<14:34, 22.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2097       640  0.003437   0.04601  0.004365     4.305:   5%|▌         | 2/40 [00:23<06:11,  9.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1847       640  0.003436   0.04469  0.004613     4.219:   8%|▊         | 3/40 [00:24<03:31,  5.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1982       640  0.003471   0.04401  0.004684     4.173:  10%|█         | 4/40 [00:25<02:16,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1865       640  0.003466   0.04266  0.004658     4.063:  12%|█▎        | 5/40 [00:25<01:32,  2.65s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1624       640   0.00347   0.04143   0.00462     3.961:  15%|█▌        | 6/40 [00:26<01:06,  1.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2076       640  0.003476   0.04129  0.004523     3.943:  18%|█▊        | 7/40 [00:26<00:50,  1.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1951       640  0.003488     0.041  0.004515      3.92:  20%|██        | 8/40 [00:27<00:40,  1.26s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1806       640  0.003479   0.04024  0.004501     3.858:  22%|██▎       | 9/40 [00:28<00:32,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2092       640  0.003484   0.03997   0.00445     3.832:  25%|██▌       | 10/40 [00:28<00:28,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2037       640  0.003491   0.03981  0.004425     3.818:  28%|██▊       | 11/40 [00:29<00:24,  1.19it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1727       640  0.003483   0.03923  0.004447     3.772:  30%|███       | 12/40 [00:30<00:21,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1924       640  0.003489   0.03897  0.004516     3.758:  32%|███▎      | 13/40 [00:30<00:19,  1.37it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2097       640  0.003493   0.03886  0.004474     3.746:  35%|███▌      | 14/40 [00:31<00:18,  1.43it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1907       640  0.003497   0.03861  0.004455     3.725:  38%|███▊      | 15/40 [00:32<00:17,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2097       640    0.0035   0.03862  0.004487     3.729:  40%|████      | 16/40 [00:32<00:16,  1.49it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1875       640  0.003499   0.03843  0.004472     3.712:  42%|████▎     | 17/40 [00:33<00:15,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1994       640  0.003501   0.03835  0.004511     3.709:  45%|████▌     | 18/40 [00:33<00:14,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2004       640  0.003509   0.03828  0.004519     3.705:  48%|████▊     | 19/40 [00:34<00:13,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2173       640  0.003509   0.03839  0.004534     3.715:  50%|█████     | 20/40 [00:35<00:13,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2014       640  0.003504   0.03823   0.00453     3.701:  52%|█████▎    | 21/40 [00:35<00:12,  1.51it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1884       640  0.003502   0.03807  0.004508     3.687:  55%|█████▌    | 22/40 [00:36<00:11,  1.50it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1852       640  0.003503    0.0379  0.004511     3.673:  57%|█████▊    | 23/40 [00:37<00:11,  1.46it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2151       640  0.003498   0.03799  0.004526     3.681:  60%|██████    | 24/40 [00:38<00:10,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      1903       640  0.003499   0.03778   0.00451     3.663:  62%|██████▎   | 25/40 [00:38<00:10,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     14.5G      2060       640    0.0035   0.03772  0.004522      3.66:  65%|██████▌   | 26/40 [00:39<00:09,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.595       0.39      0.406      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937       0.62       0.38      0.404      0.228
                   0        738       1052      0.617       0.49       0.52       0.25
                   1        738         44      0.699      0.159      0.257      0.112
                   2        738       8622      0.741      0.695       0.74      0.469
                   3        738        151      0.606      0.391      0.424      0.318
                   4        738        467      0.531      0.555      0.545      0.378
                   5        738         70      0.383      0.343      0.252      0.145
                   6        738         65      0.333     0.0615      0.155     0.0663
                   7        738       1619      0.598       0.56      0.566      0.232
                   8        738       2845      0.691      0.549      0.576      0.305
                   9        738          2          1          0    0.00064   0.000576

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_client5_residential_night

1 epochs completed in 0.024 hours.
Destroying process group...
[rank0]:[W507 21:09:14.631285177 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31350 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round030_phase1_head_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round030_phase1_head_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:09:31.381535714 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:09:31.392327167 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.02985   0.03252  0.003288     5.253:   3%|▎         | 1/31 [00:32<16:05, 32.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.02945   0.03146  0.003195     5.129:   6%|▋         | 2/31 [00:32<06:37, 13.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.02876    0.0303  0.003127     4.975:  10%|▉         | 3/31 [00:33<03:38,  7.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.02815   0.02883  0.002915     4.792:  13%|█▎        | 4/31 [00:34<02:16,  5.05s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.02783   0.02845  0.002892     4.734:  16%|█▌        | 5/31 [00:35<01:29,  3.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.02777   0.02806  0.002913     4.699:  19%|█▉        | 6/31 [00:35<01:01,  2.46s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.02785   0.02771  0.002973     4.683:  23%|██▎       | 7/31 [00:36<00:44,  1.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.02769    0.0276  0.002972     4.662:  26%|██▌       | 8/31 [00:36<00:33,  1.45s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.02774   0.02746  0.002906     4.649:  29%|██▉       | 9/31 [00:37<00:25,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.02774   0.02747  0.002876     4.647:  32%|███▏      | 10/31 [00:38<00:20,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.02769   0.02741  0.002876     4.638:  35%|███▌      | 11/31 [00:38<00:17,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.02758   0.02714  0.002865     4.607:  39%|███▊      | 12/31 [00:39<00:14,  1.28it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640   0.02753   0.02704  0.002823     4.592:  42%|████▏     | 13/31 [00:39<00:12,  1.39it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.02753   0.02691  0.002797     4.579:  45%|████▌     | 14/31 [00:40<00:11,  1.47it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.02753   0.02676  0.002843     4.571:  48%|████▊     | 15/31 [00:40<00:10,  1.54it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.02752   0.02664  0.002851     4.561:  52%|█████▏    | 16/31 [00:41<00:09,  1.59it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.02753   0.02664  0.002833      4.56:  55%|█████▍    | 17/31 [00:42<00:08,  1.62it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.02761   0.02674   0.00281     4.573:  58%|█████▊    | 18/31 [00:42<00:07,  1.65it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.02758   0.02664  0.002797     4.561:  61%|██████▏   | 19/31 [00:43<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.02759   0.02679  0.002795     4.573:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.02763   0.02683  0.002817     4.582:  68%|██████▊   | 21/31 [00:44<00:05,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.02765   0.02692  0.002799      4.59:  71%|███████   | 22/31 [00:45<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.02766   0.02698  0.002775     4.594:  74%|███████▍  | 23/31 [00:45<00:04,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.02771    0.0271   0.00277     4.607:  77%|███████▋  | 24/31 [00:46<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.02774   0.02712  0.002773      4.61:  81%|████████  | 25/31 [00:46<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.02781    0.0272  0.002779     4.624:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.557      0.395      0.393      0.214
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.33it/s]

                 all        738      14937      0.548      0.396      0.391      0.214
                   0        738       1052        0.5      0.529      0.496      0.234
                   1        738         44      0.443      0.136      0.214     0.0886
                   2        738       8622      0.709      0.709      0.734      0.468
                   3        738        151      0.492      0.411       0.43      0.316
                   4        738        467      0.474      0.561      0.513      0.353
                   5        738         70      0.348      0.386      0.287      0.126
                   6        738         65      0.333     0.0923       0.15     0.0534
                   7        738       1619      0.571       0.58      0.552      0.224
                   8        738       2845      0.613      0.561      0.538      0.278
                   9        738          2          1          0   0.000579   0.000521

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round030_phase1_head_server_repair

1 epochs completed in 0.027 hours.
Destroying process group...
[rank0]:[W507 21:11:07.740671694 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 2 full-model burst DQA: round031 phase_round=1 ===

02 head-to-full DQA:  94%|█████████▍| 30/32 [7:03:49<28:13, 846.57s/round, elapsed=7h03m49s, eta=28m15s, phase=phase1_head, round=30]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round031 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round031 client0_highway_day: pseudo scan 250/1500 images, kept 2330 boxes
round031 client0_highway_day: pseudo scan 500/1500 images, kept 4733 boxes
round031 client0_highway_day: pseudo scan 750/1500 images, kept 7038 boxes
round031 client0_highway_day: pseudo scan 1000/1500 images, kept 9379 boxes
round031 client0_highway_day: pseudo scan 1250/1500 images, kept 11670 boxes
round031 client0_highway_day: pseudo scan 1500/1500 images, kept 14024 boxes
{
  "round": "round031",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1492,
  "pseudo_boxes_kept": 11027,
  "boxes_per_kept_image": 7.390750670241287,
  "mean_conf": 0.8483453729059275,
  "mean_stability": 0.939595791617233,
  "mean_score": 0.8004372066419907,
  "class_counts": {
    "0": 169,
    "2": 6311,
    "3": 115,
    "4": 558,
    "5": 8,
    "7": 562,
    "8": 3304
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_client0_highway_day_stable_boxes.csv"
}
round031 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round031 client1_highway_night: pseudo scan 250/1500 images, kept 1401 boxes
round031 client1_highway_night: pseudo scan 500/1500 images, kept 2890 boxes
round031 client1_highway_night: pseudo scan 750/1500 images, kept 4411 boxes
round031 client1_highway_night: pseudo scan 1000/1500 images, kept 5836 boxes
round031 client1_highway_night: pseudo scan 1250/1500 images, kept 7317 boxes
round031 client1_highway_night: pseudo scan 1500/1500 images, kept 8743 boxes
{
  "round": "round031",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1424,
  "pseudo_boxes_kept": 7383,
  "boxes_per_kept_image": 5.184691011235955,
  "mean_conf": 0.7697017703835564,
  "mean_stability": 0.9172515747638539,
  "mean_score": 0.7103396304156677,
  "class_counts": {
    "0": 73,
    "2": 3935,
    "3": 26,
    "4": 148,
    "5": 8,
    "7": 646,
    "8": 2547
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_client1_highway_night_stable_boxes.csv"
}
round031 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round031 client2_citystreet_day: pseudo scan 250/1500 images, kept 2660 boxes
round031 client2_citystreet_day: pseudo scan 500/1500 images, kept 5363 boxes
round031 client2_citystreet_day: pseudo scan 750/1500 images, kept 8089 boxes
round031 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10818 boxes
round031 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13501 boxes
round031 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16135 boxes
{
  "round": "round031",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1495,
  "pseudo_boxes_kept": 13686,
  "boxes_per_kept_image": 9.154515050167223,
  "mean_conf": 0.8472938440826123,
  "mean_stability": 0.9368192381970666,
  "mean_score": 0.797313971707556,
  "class_counts": {
    "0": 1556,
    "2": 7261,
    "3": 204,
    "4": 588,
    "5": 66,
    "7": 1488,
    "8": 2523
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_client2_citystreet_day_stable_boxes.csv"
}
round031 client3_citystreet_night: pseudo scan 1/1500 images, kept 5 boxes
round031 client3_citystreet_night: pseudo scan 250/1500 images, kept 2105 boxes
round031 client3_citystreet_night: pseudo scan 500/1500 images, kept 4215 boxes
round031 client3_citystreet_night: pseudo scan 750/1500 images, kept 6261 boxes
round031 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8254 boxes
round031 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10463 boxes
round031 client3_citystreet_night: pseudo scan 1500/1500 images, kept 12557 boxes
{
  "round": "round031",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1469,
  "pseudo_boxes_kept": 10854,
  "boxes_per_kept_image": 7.388699795779441,
  "mean_conf": 0.7575690367971092,
  "mean_stability": 0.9110981861607506,
  "mean_score": 0.695032370549374,
  "class_counts": {
    "0": 568,
    "2": 5651,
    "3": 52,
    "4": 154,
    "5": 30,
    "7": 2117,
    "8": 2282
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_client3_citystreet_night_stable_boxes.csv"
}
round031 client4_residential_day: pseudo scan 1/1500 images, kept 9 boxes
round031 client4_residential_day: pseudo scan 250/1500 images, kept 2584 boxes
round031 client4_residential_day: pseudo scan 500/1500 images, kept 5141 boxes
round031 client4_residential_day: pseudo scan 750/1500 images, kept 7650 boxes
round031 client4_residential_day: pseudo scan 1000/1500 images, kept 10080 boxes
round031 client4_residential_day: pseudo scan 1250/1500 images, kept 12565 boxes
round031 client4_residential_day: pseudo scan 1500/1500 images, kept 15003 boxes
{
  "round": "round031",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1488,
  "pseudo_boxes_kept": 9804,
  "boxes_per_kept_image": 6.588709677419355,
  "mean_conf": 0.8763913948990188,
  "mean_stability": 0.9470109836464753,
  "mean_score": 0.8335999653750545,
  "class_counts": {
    "0": 431,
    "2": 6752,
    "3": 67,
    "4": 296,
    "5": 42,
    "7": 530,
    "8": 1686
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_client4_residential_day_stable_boxes.csv"
}
round031 client5_residential_night: pseudo scan 1/1500 images, kept 5 boxes
round031 client5_residential_night: pseudo scan 250/1500 images, kept 1933 boxes
round031 client5_residential_night: pseudo scan 500/1500 images, kept 3860 boxes
round031 client5_residential_night: pseudo scan 750/1500 images, kept 5753 boxes
round031 client5_residential_night: pseudo scan 1000/1500 images, kept 7728 boxes
round031 client5_residential_night: pseudo scan 1250/1500 images, kept 9626 boxes
round031 client5_residential_night: pseudo scan 1500/1500 images, kept 11551 boxes
{
  "round": "round031",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1437,
  "pseudo_boxes_kept": 7348,
  "boxes_per_kept_image": 5.1134307585247045,
  "mean_conf": 0.8130508735775948,
  "mean_stability": 0.928000610275118,
  "mean_score": 0.7580440189250983,
  "class_counts": {
    "0": 129,
    "2": 5198,
    "3": 28,
    "4": 92,
    "5": 19,
    "7": 678,
    "8": 1204
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round031_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31351 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round031_phase2_full_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round031_phase2_full_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client0_highway_day_stable_train' images and labels...5121 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 6373/6373 [00:00<00:00, 15717.23it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client0_highway_day_stable_train.cache' images and labels... 5121 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 6373/6373 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 21:13:22.681506147 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:13:22.846042907 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2150       640  0.007434   0.05454  0.005017     5.359:   3%|▎         | 1/39 [00:31<20:15, 32.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1887       640   0.00724   0.05137  0.004622     5.058:   5%|▌         | 2/39 [00:33<08:32, 13.86s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2028       640  0.007242   0.05019  0.004803     4.979:   8%|▊         | 3/39 [00:34<04:49,  8.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1776       640  0.007237   0.04973  0.004779      4.94:  10%|█         | 4/39 [00:35<03:05,  5.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1991       640  0.007183   0.04958  0.004756     4.922:  13%|█▎        | 5/39 [00:36<02:06,  3.71s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1760       640  0.007092   0.04803  0.004548     4.773:  15%|█▌        | 6/39 [00:37<01:31,  2.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640  0.007083   0.04734  0.004556     4.718:  18%|█▊        | 7/39 [00:38<01:09,  2.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1958       640  0.007095   0.04682  0.004689     4.689:  21%|██        | 8/39 [00:39<00:54,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2214       640  0.007118     0.047  0.004703     4.706:  23%|██▎       | 9/39 [00:39<00:45,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2108       640  0.007129   0.04702  0.004718      4.71:  26%|██▌       | 10/39 [00:40<00:38,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2066       640  0.007119   0.04667   0.00469     4.679:  28%|██▊       | 11/39 [00:41<00:32,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1941       640  0.007117   0.04673  0.004801     4.692:  31%|███       | 12/39 [00:42<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1843       640   0.00708   0.04628  0.004768      4.65:  33%|███▎      | 13/39 [00:43<00:26,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2135       640  0.007068   0.04616  0.004712     4.635:  36%|███▌      | 14/39 [00:44<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1975       640  0.007066   0.04595  0.004666     4.615:  38%|███▊      | 15/39 [00:45<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2006       640  0.007065   0.04565  0.004633     4.588:  41%|████      | 16/39 [00:46<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1686       640  0.007064   0.04533  0.004677     4.566:  44%|████▎     | 17/39 [00:46<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2088       640  0.007063   0.04506  0.004656     4.542:  46%|████▌     | 18/39 [00:47<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1710       640  0.007048   0.04461  0.004629     4.503:  49%|████▊     | 19/39 [00:48<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2250       640   0.00705   0.04455  0.004638     4.499:  51%|█████▏    | 20/39 [00:49<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2110       640   0.00704   0.04454  0.004621     4.496:  54%|█████▍    | 21/39 [00:50<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1923       640   0.00704   0.04438  0.004607     4.482:  56%|█████▋    | 22/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2055       640   0.00703    0.0442  0.004572     4.464:  59%|█████▉    | 23/39 [00:52<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1941       640  0.007029   0.04408   0.00457     4.455:  62%|██████▏   | 24/39 [00:53<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2023       640  0.007019   0.04396  0.004567     4.443:  64%|██████▍   | 25/39 [00:54<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640  0.007012   0.04387  0.004546     4.434:  67%|██████▋   | 26/39 [00:54<00:11,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.524      0.436      0.407      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]

                 all        738      14937      0.587      0.391      0.405      0.226
                   0        738       1052      0.562      0.522      0.517      0.245
                   1        738         44      0.544      0.136      0.239      0.106
                   2        738       8622      0.756      0.689      0.739      0.468
                   3        738        151      0.619      0.397      0.418      0.315
                   4        738        467      0.498       0.57      0.525      0.374
                   5        738         70      0.406      0.386      0.298      0.153
                   6        738         65       0.25     0.0615      0.174     0.0684
                   7        738       1619      0.583      0.579      0.571       0.23
                   8        738       2845      0.655      0.575      0.569      0.298
                   9        738          2          1          0   0.000501   0.000451

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client0_highway_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W507 21:15:17.199581158 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31352 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round031_phase2_full_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round031_phase2_full_client1_highway_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client1_highway_night_stable_train' images and labels...4888 found, 1417 missing, 0 empty, 0 corrupted: 100%|██████████| 6305/6305 [00:00<00:00, 11918.02it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.42124483963163
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client1_highway_night_stable_train.cache' images and labels... 4888 found, 1417 missing, 0 empty, 0 corrupted: 100%|██████████| 6305/6305 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:15:34.714633217 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:15:34.766607377 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2134       640  0.007441   0.05004  0.004994     4.998:   2%|▎         | 1/40 [00:33<21:55, 33.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2005       640  0.007211   0.04563  0.004567     4.593:   5%|▌         | 2/40 [00:35<09:17, 14.67s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1790       640  0.007051   0.04438   0.00426     4.455:   8%|▊         | 3/40 [00:36<05:15,  8.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2090       640  0.007037   0.04375  0.004412     4.416:  10%|█         | 4/40 [00:37<03:21,  5.60s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1728       640  0.007007   0.04294  0.004456     4.352:  12%|█▎        | 5/40 [00:38<02:16,  3.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1870       640  0.007002   0.04205   0.00455     4.288:  15%|█▌        | 6/40 [00:39<01:37,  2.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1864       640  0.006987   0.04161  0.004575     4.254:  18%|█▊        | 7/40 [00:40<01:13,  2.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1985       640  0.006978    0.0416  0.004583     4.252:  20%|██        | 8/40 [00:40<00:57,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1975       640  0.006981   0.04133  0.004456     4.221:  22%|██▎       | 9/40 [00:41<00:46,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1960       640  0.006995   0.04098  0.004391     4.189:  25%|██▌       | 10/40 [00:42<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2281       640  0.007024   0.04088   0.00447      4.19:  28%|██▊       | 11/40 [00:43<00:34,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1865       640  0.007012   0.04034  0.004534     4.151:  30%|███       | 12/40 [00:44<00:30,  1.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2005       640  0.007001   0.03997  0.004577     4.124:  32%|███▎      | 13/40 [00:45<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640  0.007013    0.0398  0.004618     4.114:  35%|███▌      | 14/40 [00:46<00:25,  1.00it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1880       640  0.007013   0.03957  0.004645     4.098:  38%|███▊      | 15/40 [00:47<00:24,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1811       640  0.007012   0.03921  0.004678     4.072:  40%|████      | 16/40 [00:48<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1816       640   0.00703   0.03893  0.004703     4.053:  42%|████▎     | 17/40 [00:48<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1978       640  0.007031   0.03869  0.004694     4.033:  45%|████▌     | 18/40 [00:49<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1547       640  0.007019    0.0383  0.004663     3.998:  48%|████▊     | 19/40 [00:50<00:19,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1949       640  0.007003   0.03811  0.004654     3.981:  50%|█████     | 20/40 [00:51<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1829       640  0.007002   0.03784   0.00462     3.957:  52%|█████▎    | 21/40 [00:52<00:17,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1955       640  0.007011   0.03771    0.0046     3.945:  55%|█████▌    | 22/40 [00:53<00:16,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2120       640  0.006998   0.03764   0.00457     3.937:  57%|█████▊    | 23/40 [00:54<00:15,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1888       640  0.007005   0.03749  0.004603     3.928:  60%|██████    | 24/40 [00:55<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2014       640  0.007005   0.03734  0.004632     3.918:  62%|██████▎   | 25/40 [00:56<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2021       640  0.007004   0.03729  0.004632     3.914:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.561      0.411      0.404      0.228
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]

                 all        738      14937      0.548      0.412      0.403      0.228
                   0        738       1052      0.549      0.517      0.513      0.243
                   1        738         44      0.447      0.205       0.22      0.102
                   2        738       8622      0.705      0.714      0.741      0.471
                   3        738        151      0.545      0.417      0.429       0.33
                   4        738        467       0.47        0.6      0.533      0.378
                   5        738         70      0.321        0.4      0.288      0.153
                   6        738         65      0.238     0.0923      0.168     0.0738
                   7        738       1619      0.556      0.602      0.568      0.232
                   8        738       2845      0.645      0.576      0.573      0.301
                   9        738          2          1          0    0.00044   0.000396

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client1_highway_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W507 21:17:32.603396485 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31353 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round031_phase2_full_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round031_phase2_full_client2_citystreet_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client2_citystreet_day_stable_train' images and labels...5047 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 6376/6376 [00:00<00:00, 11016.25it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client2_citystreet_day_stable_train.cache' images and labels... 5047 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 6376/6376 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:17:49.527378047 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:17:49.537744761 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1949       640   0.00701   0.05718   0.00463     5.505:   3%|▎         | 1/39 [00:32<20:27, 32.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2115       640  0.007049   0.05837  0.004684     5.608:   5%|▌         | 2/39 [00:33<08:41, 14.10s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1890       640  0.007015   0.05637  0.004581     5.437:   8%|▊         | 3/39 [00:34<04:54,  8.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2037       640     0.007   0.05466  0.004643     5.304:  10%|█         | 4/39 [00:35<03:08,  5.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2180       640  0.006991    0.0539  0.004542     5.234:  13%|█▎        | 5/39 [00:36<02:08,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1564       640  0.006945     0.052  0.004503     5.076:  15%|█▌        | 6/39 [00:37<01:32,  2.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1915       640  0.006999   0.05195  0.004652     5.088:  18%|█▊        | 7/39 [00:38<01:09,  2.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1879       640  0.006969   0.05114  0.004625     5.019:  21%|██        | 8/39 [00:39<00:54,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2075       640  0.006982   0.05102  0.004536     5.003:  23%|██▎       | 9/39 [00:40<00:44,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1851       640  0.006953   0.05031  0.004507     4.941:  26%|██▌       | 10/39 [00:41<00:37,  1.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2053       640  0.006964   0.04994  0.004529     4.915:  28%|██▊       | 11/39 [00:42<00:32,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1720       640  0.006969   0.04942  0.004573     4.877:  31%|███       | 12/39 [00:43<00:29,  1.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2188       640   0.00699   0.04933  0.004534     4.869:  33%|███▎      | 13/39 [00:43<00:26,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2065       640  0.007007   0.04913  0.004499     4.851:  36%|███▌      | 14/39 [00:44<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1968       640  0.007012   0.04893  0.004506     4.836:  38%|███▊      | 15/39 [00:45<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640  0.007019   0.04865  0.004504     4.814:  41%|████      | 16/39 [00:46<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640  0.007025   0.04847  0.004504       4.8:  44%|████▎     | 17/39 [00:47<00:20,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2086       640  0.007013   0.04832  0.004471     4.784:  46%|████▌     | 18/39 [00:48<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1725       640   0.00701   0.04794  0.004433      4.75:  49%|████▊     | 19/39 [00:49<00:18,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2175       640  0.007008   0.04788  0.004441     4.746:  51%|█████▏    | 20/39 [00:50<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1871       640  0.006993   0.04766  0.004406     4.725:  54%|█████▍    | 21/39 [00:51<00:16,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1933       640  0.006981   0.04765  0.004394     4.722:  56%|█████▋    | 22/39 [00:51<00:15,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1912       640   0.00698   0.04747    0.0044     4.708:  59%|█████▉    | 23/39 [00:52<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2081       640  0.006977   0.04744  0.004375     4.703:  62%|██████▏   | 24/39 [00:53<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2034       640  0.006972   0.04731  0.004359     4.691:  64%|██████▍   | 25/39 [00:54<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1910       640   0.00697   0.04717  0.004368      4.68:  67%|██████▋   | 26/39 [00:55<00:11,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.501      0.445      0.401      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.23it/s]

                 all        738      14937      0.545        0.4      0.399      0.225
                   0        738       1052      0.633      0.481      0.503      0.239
                   1        738         44      0.435      0.158      0.213     0.0985
                   2        738       8622      0.688       0.72      0.742      0.471
                   3        738        151      0.517      0.411      0.424      0.322
                   4        738        467      0.458      0.585      0.517      0.364
                   5        738         70      0.353      0.398      0.298      0.157
                   6        738         65      0.171     0.0615      0.165     0.0751
                   7        738       1619      0.572      0.592      0.557      0.228
                   8        738       2845      0.622      0.591       0.57      0.299
                   9        738          2          1          0   0.000248   0.000223

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client2_citystreet_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W507 21:19:45.750981391 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31354 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round031_phase2_full_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round031_phase2_full_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client3_citystreet_night_stable_train' images and labels...:   0%|          | 0/6350 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client3_citystreet_night_stable_train' images and labels...4882 found, 1468 missing, 0 empty, 0 corrupted: 100%|██████████| 6350/6350 [00:00<00:00, 14656.46it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.297369664514097
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client3_citystreet_night_stable_train.cache' images and labels... 4882 found, 1468 missing, 0 empty, 0 corrupted: 100%|██████████| 6350/6350 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 21:20:01.665509189 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 21:20:01.676084420 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1810       640  0.006867   0.04774  0.004749     4.749:   2%|▎         | 1/40 [00:32<21:23, 32.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1958       640   0.00704   0.04767   0.00474     4.756:   5%|▌         | 2/40 [00:34<09:03, 14.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1818       640  0.007048   0.04738  0.004682     4.729:   8%|▊         | 3/40 [00:35<05:06,  8.30s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1824       640  0.007021   0.04649  0.004614      4.65:  10%|█         | 4/40 [00:36<03:15,  5.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1936       640  0.007045   0.04565   0.00476     4.596:  12%|█▎        | 5/40 [00:37<02:13,  3.81s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1701       640  0.007002   0.04458  0.004797      4.51:  15%|█▌        | 6/40 [00:38<01:36,  2.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1709       640  0.007003    0.0435  0.004657     4.413:  18%|█▊        | 7/40 [00:39<01:12,  2.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2052       640  0.007001   0.04322  0.004658      4.39:  20%|██        | 8/40 [00:40<00:57,  1.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1976       640  0.007023   0.04279  0.004582     4.352:  22%|██▎       | 9/40 [00:40<00:46,  1.51s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1946       640  0.007033   0.04256  0.004599     4.335:  25%|██▌       | 10/40 [00:41<00:39,  1.32s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1971       640  0.007035   0.04212  0.004619     4.302:  28%|██▊       | 11/40 [00:42<00:34,  1.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1677       640  0.007011   0.04143  0.004632     4.246:  30%|███       | 12/40 [00:43<00:31,  1.11s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640  0.007016   0.04108  0.004717     4.225:  32%|███▎      | 13/40 [00:44<00:28,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2065       640  0.007031   0.04096   0.00477     4.221:  35%|███▌      | 14/40 [00:45<00:26,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1850       640  0.007032   0.04045  0.004763      4.18:  38%|███▊      | 15/40 [00:46<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1965       640   0.00702   0.04032  0.004691     4.162:  40%|████      | 16/40 [00:47<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1813       640  0.007039   0.04002   0.00473     4.143:  42%|████▎     | 17/40 [00:48<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2168       640  0.007037   0.03988  0.004756     4.134:  45%|████▌     | 18/40 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1605       640  0.007027    0.0394  0.004729     4.093:  48%|████▊     | 19/40 [00:49<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2111       640  0.007036   0.03935  0.004732     4.089:  50%|█████     | 20/40 [00:50<00:17,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2061       640  0.007053   0.03924  0.004736     4.082:  52%|█████▎    | 21/40 [00:51<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1953       640  0.007053   0.03911  0.004723     4.071:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1888       640  0.007046   0.03891  0.004714     4.054:  57%|█████▊    | 23/40 [00:53<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1902       640  0.007038   0.03875  0.004709      4.04:  60%|██████    | 24/40 [00:54<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1800       640  0.007027   0.03855  0.004696     4.022:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2050       640  0.007024    0.0385   0.00466     4.015:  65%|██████▌   | 26/40 [00:55<00:12,  1.15it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.548      0.417      0.403      0.226
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.536      0.418        0.4      0.226
                   0        738       1052      0.561      0.502      0.493      0.236
                   1        738         44      0.496      0.227       0.22      0.108
                   2        738       8622      0.673      0.714      0.735      0.467
                   3        738        151      0.515      0.397      0.426      0.324
                   4        738        467      0.444      0.615       0.53      0.371
                   5        738         70       0.33        0.4      0.298      0.155
                   6        738         65      0.226      0.108      0.175     0.0703
                   7        738       1619      0.522      0.612      0.558      0.229
                   8        738       2845      0.587        0.6      0.568        0.3
                   9        738          2          1          0   0.000486   0.000437

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client3_citystreet_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W507 21:21:59.071503388 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31355 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round031_phase2_full_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round031_phase2_full_client4_residential_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client4_residential_day_stable_train' images and labels...5040 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 6369/6369 [00:00<00:00, 12084.09it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.639774557165861
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client4_residential_day_stable_train.cache' images and labels... 5040 found, 1329 missing, 0 empty, 0 corrupted: 100%|██████████| 6369/6369 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:22:16.658089766 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:22:16.738490707 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1976       640  0.007245   0.05684  0.004716     5.504:   3%|▎         | 1/39 [00:33<21:25, 33.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2142       640  0.007158   0.05708  0.004573     5.505:   5%|▌         | 2/39 [00:35<09:03, 14.68s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1988       640   0.00709   0.05424  0.004654     5.279:   8%|▊         | 3/39 [00:36<05:06,  8.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2075       640   0.00707   0.05276  0.004726     5.165:  10%|█         | 4/39 [00:37<03:14,  5.57s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2226       640  0.007044   0.05231  0.004674     5.122:  13%|█▎        | 5/39 [00:38<02:12,  3.88s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1721       640  0.006996   0.05068  0.004589     4.981:  15%|█▌        | 6/39 [00:39<01:34,  2.87s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2003       640  0.007042   0.05042  0.004655      4.97:  18%|█▊        | 7/39 [00:40<01:11,  2.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2092       640  0.007025   0.04972  0.004632      4.91:  21%|██        | 8/39 [00:40<00:55,  1.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2107       640  0.007017   0.04954  0.004497     4.884:  23%|██▎       | 9/39 [00:41<00:45,  1.52s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1894       640  0.007004   0.04921  0.004558     4.862:  26%|██▌       | 10/39 [00:42<00:38,  1.33s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1872       640  0.006992   0.04856  0.004551     4.808:  28%|██▊       | 11/39 [00:43<00:33,  1.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1943       640  0.006987   0.04817  0.004567     4.778:  31%|███       | 12/39 [00:44<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2165       640   0.00701    0.0481  0.004506     4.769:  33%|███▎      | 13/39 [00:45<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1868       640  0.007003   0.04765  0.004467      4.73:  36%|███▌      | 14/39 [00:46<00:24,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2013       640  0.007014   0.04746  0.004471     4.716:  38%|███▊      | 15/39 [00:47<00:22,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1974       640  0.007023   0.04714  0.004487     4.692:  41%|████      | 16/39 [00:48<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640  0.007022   0.04685  0.004502      4.67:  44%|████▎     | 17/39 [00:48<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1868       640  0.007012   0.04655  0.004462     4.642:  46%|████▌     | 18/39 [00:49<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1870       640  0.007008   0.04621  0.004432     4.612:  49%|████▊     | 19/39 [00:50<00:17,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640  0.006995   0.04612  0.004421     4.603:  51%|█████▏    | 20/39 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1921       640  0.006981   0.04589  0.004415     4.583:  54%|█████▍    | 21/39 [00:52<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1989       640  0.006982    0.0459   0.00441     4.583:  56%|█████▋    | 22/39 [00:53<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2010       640  0.006979   0.04579  0.004404     4.574:  59%|█████▉    | 23/39 [00:54<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1982       640  0.006971   0.04566   0.00439     4.562:  62%|██████▏   | 24/39 [00:55<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1923       640  0.006967    0.0455  0.004371     4.547:  64%|██████▍   | 25/39 [00:55<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1969       640  0.006955   0.04536  0.004383     4.536:  67%|██████▋   | 26/39 [00:56<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.54      0.415      0.403      0.224
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.527      0.416      0.402      0.225
                   0        738       1052       0.53      0.522      0.513      0.243
                   1        738         44      0.454      0.227      0.221      0.105
                   2        738       8622      0.707      0.704      0.736      0.464
                   3        738        151      0.476      0.417      0.438      0.332
                   4        738        467      0.439      0.603      0.517      0.362
                   5        738         70      0.313      0.414      0.278      0.136
                   6        738         65      0.185     0.0769      0.171     0.0713
                   7        738       1619      0.552      0.607      0.568      0.234
                   8        738       2845      0.617      0.594      0.578      0.302
                   9        738          2          1          0   0.000296   0.000267

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client4_residential_day

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W507 21:24:15.668196170 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31356 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round031_phase2_full_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round031_phase2_full_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client5_residential_night_stable_train' images and labels...4883 found, 1435 missing, 0 empty, 0 corrupted: 100%|██████████| 6318/6318 [00:00<00:00, 14541.78it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.377295756808106
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round031_client5_residential_night_stable_train.cache' images and labels... 4883 found, 1435 missing, 0 empty, 0 corrupted: 100%|██████████| 6318/6318 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 21:24:31.953433008 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 21:24:31.997725328 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2255       640  0.006982   0.04986  0.004147     4.879:   2%|▎         | 1/40 [00:32<21:09, 32.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1810       640  0.006903   0.04684  0.004106     4.628:   5%|▌         | 2/40 [00:33<08:55, 14.08s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2022       640  0.006937   0.04594  0.004075     4.556:   8%|▊         | 3/40 [00:34<05:03,  8.21s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1928       640  0.006898   0.04519  0.004147     4.499:  10%|█         | 4/40 [00:36<03:14,  5.41s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1849       640  0.006948   0.04415  0.004167     4.421:  12%|█▎        | 5/40 [00:36<02:12,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1626       640  0.006939   0.04349  0.004143     4.366:  15%|█▌        | 6/40 [00:37<01:35,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2057       640  0.006986    0.0434  0.004362      4.38:  18%|█▊        | 7/40 [00:38<01:11,  2.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2216       640  0.007012   0.04351  0.004339     4.389:  20%|██        | 8/40 [00:39<00:56,  1.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1759       640  0.007011   0.04264   0.00431     4.317:  22%|██▎       | 9/40 [00:40<00:45,  1.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1666       640  0.006989   0.04187  0.004363     4.258:  25%|██▌       | 10/40 [00:41<00:38,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2127       640  0.007009   0.04162   0.00436     4.239:  28%|██▊       | 11/40 [00:42<00:33,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1924       640  0.006997   0.04134  0.004383     4.218:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1811       640  0.006984   0.04078  0.004403     4.173:  32%|███▎      | 13/40 [00:43<00:27,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1888       640  0.006996   0.04045  0.004435     4.151:  35%|███▌      | 14/40 [00:44<00:25,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1810       640     0.007   0.04008  0.004401     4.119:  38%|███▊      | 15/40 [00:45<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1995       640  0.007013   0.03996  0.004399      4.11:  40%|████      | 16/40 [00:46<00:22,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1758       640   0.00701    0.0397  0.004379     4.087:  42%|████▎     | 17/40 [00:47<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1969       640  0.007017   0.03965  0.004381     4.084:  45%|████▌     | 18/40 [00:48<00:19,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1929       640  0.007028   0.03941  0.004357     4.063:  48%|████▊     | 19/40 [00:49<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2185       640  0.007019   0.03927  0.004359     4.052:  50%|█████     | 20/40 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1938       640  0.007002   0.03902  0.004321     4.027:  52%|█████▎    | 21/40 [00:51<00:16,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1650       640  0.007011   0.03878  0.004313     4.008:  55%|█████▌    | 22/40 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1833       640  0.006996   0.03855  0.004296     3.988:  57%|█████▊    | 23/40 [00:52<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1969       640  0.006979   0.03838   0.00429     3.972:  60%|██████    | 24/40 [00:53<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1954       640  0.006977   0.03825  0.004303     3.962:  62%|██████▎   | 25/40 [00:54<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1789       640  0.006975   0.03802  0.004308     3.944:  65%|██████▌   | 26/40 [00:55<00:12,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937       0.57      0.406      0.404      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.558      0.407      0.403      0.229
                   0        738       1052      0.546      0.515      0.505      0.244
                   1        738         44      0.502      0.205      0.212      0.103
                   2        738       8622      0.705      0.706      0.736      0.469
                   3        738        151      0.593      0.411      0.432      0.335
                   4        738        467      0.483      0.582      0.533      0.378
                   5        738         70      0.328      0.386      0.289      0.158
                   6        738         65      0.238     0.0722      0.183     0.0758
                   7        738       1619       0.56      0.597      0.565       0.23
                   8        738       2845      0.622      0.595      0.575      0.301
                   9        738          2          1          0   0.000459   0.000413

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_client5_residential_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W507 21:26:28.983586717 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31357 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round031_phase2_full_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round031_phase2_full_server_repair_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:26:46.341850687 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:26:46.342406347 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.21G      2625       640   0.02938   0.03134  0.003229     5.116:   3%|▎         | 1/31 [00:31<15:59, 31.98s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2744       640   0.02924   0.03085  0.003169     5.061:   6%|▋         | 2/31 [00:32<06:35, 13.63s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2517       640   0.02853   0.02966  0.003091     4.903:  10%|▉         | 3/31 [00:33<03:37,  7.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2094       640   0.02802   0.02835  0.002888      4.74:  13%|█▎        | 4/31 [00:34<02:14,  4.99s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2510       640   0.02769   0.02797  0.002863     4.681:  16%|█▌        | 5/31 [00:34<01:28,  3.40s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2440       640   0.02759   0.02756  0.002884     4.643:  19%|█▉        | 6/31 [00:35<01:00,  2.44s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2376       640   0.02763    0.0272  0.002942     4.621:  23%|██▎       | 7/31 [00:36<00:43,  1.83s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2580       640   0.02744   0.02707   0.00294     4.596:  26%|██▌       | 8/31 [00:36<00:32,  1.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2477       640   0.02749   0.02693  0.002876     4.584:  29%|██▉       | 9/31 [00:37<00:25,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2577       640   0.02748   0.02694  0.002843     4.581:  32%|███▏      | 10/31 [00:37<00:20,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2687       640   0.02744   0.02689  0.002843     4.573:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2320       640   0.02734   0.02662  0.002832     4.543:  39%|███▊      | 12/31 [00:38<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2397       640    0.0273   0.02654   0.00279     4.531:  42%|████▏     | 13/31 [00:39<00:12,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2399       640   0.02732   0.02642  0.002765      4.52:  45%|████▌     | 14/31 [00:40<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2329       640   0.02731   0.02627   0.00281     4.512:  48%|████▊     | 15/31 [00:40<00:10,  1.52it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2332       640   0.02731   0.02615  0.002818     4.503:  52%|█████▏    | 16/31 [00:41<00:09,  1.57it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2460       640   0.02734   0.02616  0.002801     4.504:  55%|█████▍    | 17/31 [00:41<00:08,  1.61it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2634       640   0.02744   0.02628  0.002778      4.52:  58%|█████▊    | 18/31 [00:42<00:07,  1.64it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2299       640   0.02743   0.02618  0.002766      4.51:  61%|██████▏   | 19/31 [00:43<00:07,  1.67it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2671       640   0.02744   0.02634  0.002764     4.523:  65%|██████▍   | 20/31 [00:43<00:06,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2597       640   0.02748   0.02639  0.002786     4.532:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2430       640   0.02751   0.02648  0.002769     4.541:  71%|███████   | 22/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2485       640   0.02751   0.02654  0.002746     4.544:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2627       640   0.02756   0.02666  0.002741     4.557:  77%|███████▋  | 24/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2364       640   0.02759   0.02668  0.002744      4.56:  81%|████████  | 25/31 [00:46<00:03,  1.71it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2523       640   0.02766   0.02676   0.00275     4.574:  84%|████████▍ | 26/31 [00:47<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.542      0.406      0.388      0.211
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.531      0.407      0.386      0.211
                   0        738       1052      0.488      0.526      0.489       0.23
                   1        738         44      0.441      0.182      0.196     0.0756
                   2        738       8622      0.693      0.712      0.731      0.466
                   3        738        151      0.465      0.411      0.429      0.313
                   4        738        467      0.464      0.572       0.51      0.349
                   5        738         70      0.316        0.4      0.287      0.124
                   6        738         65      0.283      0.121      0.139     0.0516
                   7        738       1619      0.558      0.588      0.551      0.223
                   8        738       2845      0.602       0.56      0.532      0.274
                   9        738          2          1          0   0.000626   0.000564

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round031_phase2_full_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 21:28:24.162989465 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB

=== Phase 2 full-model burst DQA: round032 phase_round=2 ===

02 head-to-full DQA:  97%|█████████▋| 31/32 [7:21:06<15:03, 903.95s/round, elapsed=7h21m06s, eta=14m13s, phase=phase2_full, round=1]EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients

round032 client0_highway_day: pseudo scan 1/1500 images, kept 12 boxes
round032 client0_highway_day: pseudo scan 250/1500 images, kept 2325 boxes
round032 client0_highway_day: pseudo scan 500/1500 images, kept 4730 boxes
round032 client0_highway_day: pseudo scan 750/1500 images, kept 7037 boxes
round032 client0_highway_day: pseudo scan 1000/1500 images, kept 9359 boxes
round032 client0_highway_day: pseudo scan 1250/1500 images, kept 11650 boxes
round032 client0_highway_day: pseudo scan 1500/1500 images, kept 14015 boxes
{
  "round": "round032",
  "client": "client0_highway_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round031_phase2_full_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1492,
  "pseudo_boxes_kept": 10981,
  "boxes_per_kept_image": 7.359919571045577,
  "mean_conf": 0.848979591047728,
  "mean_stability": 0.9393865797658857,
  "mean_score": 0.8008161602071039,
  "class_counts": {
    "0": 166,
    "2": 6307,
    "3": 115,
    "4": 563,
    "5": 8,
    "7": 568,
    "8": 3254
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client0_highway_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_client0_highway_day_stable_boxes.csv"
}
round032 client1_highway_night: pseudo scan 1/1500 images, kept 3 boxes
round032 client1_highway_night: pseudo scan 250/1500 images, kept 1345 boxes
round032 client1_highway_night: pseudo scan 500/1500 images, kept 2762 boxes
round032 client1_highway_night: pseudo scan 750/1500 images, kept 4223 boxes
round032 client1_highway_night: pseudo scan 1000/1500 images, kept 5581 boxes
round032 client1_highway_night: pseudo scan 1250/1500 images, kept 7014 boxes
round032 client1_highway_night: pseudo scan 1500/1500 images, kept 8374 boxes
{
  "round": "round032",
  "client": "client1_highway_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round031_phase2_full_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1410,
  "pseudo_boxes_kept": 7077,
  "boxes_per_kept_image": 5.019148936170213,
  "mean_conf": 0.7745851627620108,
  "mean_stability": 0.9168642508085795,
  "mean_score": 0.7145556044811519,
  "class_counts": {
    "0": 72,
    "2": 3769,
    "3": 27,
    "4": 148,
    "5": 9,
    "7": 617,
    "8": 2435
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client1_highway_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_client1_highway_night_stable_boxes.csv"
}
round032 client2_citystreet_day: pseudo scan 1/1500 images, kept 6 boxes
round032 client2_citystreet_day: pseudo scan 250/1500 images, kept 2660 boxes
round032 client2_citystreet_day: pseudo scan 500/1500 images, kept 5352 boxes
round032 client2_citystreet_day: pseudo scan 750/1500 images, kept 8068 boxes
round032 client2_citystreet_day: pseudo scan 1000/1500 images, kept 10779 boxes
round032 client2_citystreet_day: pseudo scan 1250/1500 images, kept 13459 boxes
round032 client2_citystreet_day: pseudo scan 1500/1500 images, kept 16092 boxes
{
  "round": "round032",
  "client": "client2_citystreet_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round031_phase2_full_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1497,
  "pseudo_boxes_kept": 13606,
  "boxes_per_kept_image": 9.088844355377422,
  "mean_conf": 0.84869950139293,
  "mean_stability": 0.9362244483751005,
  "mean_score": 0.798151892894892,
  "class_counts": {
    "0": 1537,
    "2": 7242,
    "3": 204,
    "4": 584,
    "5": 69,
    "7": 1484,
    "8": 2486
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client2_citystreet_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_client2_citystreet_day_stable_boxes.csv"
}
round032 client3_citystreet_night: pseudo scan 1/1500 images, kept 4 boxes
round032 client3_citystreet_night: pseudo scan 250/1500 images, kept 2054 boxes
round032 client3_citystreet_night: pseudo scan 500/1500 images, kept 4092 boxes
round032 client3_citystreet_night: pseudo scan 750/1500 images, kept 6054 boxes
round032 client3_citystreet_night: pseudo scan 1000/1500 images, kept 8003 boxes
round032 client3_citystreet_night: pseudo scan 1250/1500 images, kept 10166 boxes
round032 client3_citystreet_night: pseudo scan 1500/1500 images, kept 12209 boxes
{
  "round": "round032",
  "client": "client3_citystreet_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round031_phase2_full_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1465,
  "pseudo_boxes_kept": 10552,
  "boxes_per_kept_image": 7.202730375426621,
  "mean_conf": 0.760668135131621,
  "mean_stability": 0.9108191984532636,
  "mean_score": 0.6975404780781268,
  "class_counts": {
    "0": 551,
    "2": 5495,
    "3": 56,
    "4": 151,
    "5": 36,
    "7": 2058,
    "8": 2205
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client3_citystreet_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_client3_citystreet_night_stable_boxes.csv"
}
round032 client4_residential_day: pseudo scan 1/1500 images, kept 9 boxes
round032 client4_residential_day: pseudo scan 250/1500 images, kept 2569 boxes
round032 client4_residential_day: pseudo scan 500/1500 images, kept 5127 boxes
round032 client4_residential_day: pseudo scan 750/1500 images, kept 7643 boxes
round032 client4_residential_day: pseudo scan 1000/1500 images, kept 10062 boxes
round032 client4_residential_day: pseudo scan 1250/1500 images, kept 12549 boxes
round032 client4_residential_day: pseudo scan 1500/1500 images, kept 14978 boxes
{
  "round": "round032",
  "client": "client4_residential_day",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round031_phase2_full_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1487,
  "pseudo_boxes_kept": 9748,
  "boxes_per_kept_image": 6.555480833893745,
  "mean_conf": 0.8778179399867894,
  "mean_stability": 0.9467247743977354,
  "mean_score": 0.8346179643521722,
  "class_counts": {
    "0": 419,
    "2": 6741,
    "3": 66,
    "4": 297,
    "5": 42,
    "7": 538,
    "8": 1645
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client4_residential_day_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_client4_residential_day_stable_boxes.csv"
}
round032 client5_residential_night: pseudo scan 1/1500 images, kept 5 boxes
round032 client5_residential_night: pseudo scan 250/1500 images, kept 1853 boxes
round032 client5_residential_night: pseudo scan 500/1500 images, kept 3704 boxes
round032 client5_residential_night: pseudo scan 750/1500 images, kept 5518 boxes
round032 client5_residential_night: pseudo scan 1000/1500 images, kept 7432 boxes
round032 client5_residential_night: pseudo scan 1250/1500 images, kept 9257 boxes
round032 client5_residential_night: pseudo scan 1500/1500 images, kept 11108 boxes
{
  "round": "round032",
  "client": "client5_residential_night",
  "teacher": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round031_phase2_full_server_repair.pt",
  "source_images_scanned": 1500,
  "pseudo_images_kept": 1435,
  "pseudo_boxes_kept": 7053,
  "boxes_per_kept_image": 4.914982578397213,
  "mean_conf": 0.8160137880969078,
  "mean_stability": 0.9279627810805026,
  "mean_score": 0.7607832669918155,
  "class_counts": {
    "0": 122,
    "2": 4999,
    "3": 27,
    "4": 95,
    "5": 19,
    "7": 657,
    "8": 1134
  },
  "train_list": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client5_residential_night_stable_train.txt",
  "box_table": "/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_client5_residential_night_stable_boxes.csv"
}
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_pseudo_label_stats.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/03_round032_pseudo_label_stats.json
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31358 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round032_phase2_full_client0_highway_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round032_phase2_full_client0_highway_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client0_highway_day_stable_train' images and labels...5121 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 6373/6373 [00:00<00:00, 14514.32it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client0_highway_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.836132398499918
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client0_highway_day_stable_train.cache' images and labels... 5121 found, 1252 missing, 0 empty, 0 corrupted: 100%|██████████| 6373/6373 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client0_highway_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 21:30:40.559979133 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 21:30:40.866658614 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.67G      2150       640  0.007442    0.0546  0.004986     5.362:   3%|▎         | 1/39 [00:32<20:43, 32.72s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1887       640  0.007251   0.05152  0.004609      5.07:   5%|▌         | 2/39 [00:33<08:44, 14.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2028       640  0.007253   0.05035  0.004813     4.994:   8%|▊         | 3/39 [00:34<04:55,  8.20s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1776       640   0.00725   0.04989  0.004788     4.954:  10%|█         | 4/39 [00:36<03:08,  5.38s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1991       640  0.007196   0.04972  0.004763     4.934:  13%|█▎        | 5/39 [00:36<02:07,  3.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1760       640  0.007103   0.04817  0.004555     4.786:  15%|█▌        | 6/39 [00:37<01:31,  2.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1906       640  0.007096   0.04748  0.004555      4.73:  18%|█▊        | 7/39 [00:38<01:09,  2.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1958       640  0.007108   0.04695  0.004694       4.7:  21%|██        | 8/39 [00:39<00:54,  1.75s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2214       640   0.00713   0.04712  0.004709     4.717:  23%|██▎       | 9/39 [00:40<00:44,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2108       640  0.007141   0.04714  0.004723      4.72:  26%|██▌       | 10/39 [00:41<00:37,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2066       640  0.007131   0.04678  0.004694     4.689:  28%|██▊       | 11/39 [00:42<00:32,  1.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1941       640  0.007128   0.04682  0.004802       4.7:  31%|███       | 12/39 [00:43<00:28,  1.07s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1843       640  0.007091   0.04638   0.00477     4.659:  33%|███▎      | 13/39 [00:43<00:26,  1.01s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2135       640  0.007079   0.04627  0.004713     4.645:  36%|███▌      | 14/39 [00:44<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1975       640  0.007078   0.04605  0.004668     4.624:  38%|███▊      | 15/39 [00:45<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2006       640  0.007075   0.04574  0.004636     4.596:  41%|████      | 16/39 [00:46<00:21,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1686       640  0.007074   0.04541  0.004678     4.573:  44%|████▎     | 17/39 [00:47<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2088       640  0.007074   0.04513  0.004657     4.549:  46%|████▌     | 18/39 [00:48<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1710       640  0.007058   0.04468   0.00463     4.509:  49%|████▊     | 19/39 [00:49<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2250       640   0.00706   0.04462  0.004639     4.506:  51%|█████▏    | 20/39 [00:50<00:16,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2110       640  0.007049   0.04461  0.004622     4.503:  54%|█████▍    | 21/39 [00:50<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1923       640  0.007049   0.04444  0.004609     4.488:  56%|█████▋    | 22/39 [00:51<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2055       640  0.007039   0.04426  0.004574      4.47:  59%|█████▉    | 23/39 [00:52<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1941       640  0.007038   0.04415  0.004571      4.46:  62%|██████▏   | 24/39 [00:53<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2023       640  0.007028   0.04402  0.004568     4.449:  64%|██████▍   | 25/39 [00:54<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640  0.007021   0.04393  0.004545      4.44:  67%|██████▋   | 26/39 [00:55<00:11,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.528       0.43      0.406      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client0_highway_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client0_highway_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client0_highway_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.613       0.38      0.404      0.225
                   0        738       1052      0.598      0.515      0.517      0.245
                   1        738         44      0.529     0.0909       0.23      0.104
                   2        738       8622      0.781      0.679      0.739      0.467
                   3        738        151      0.649      0.392       0.42      0.317
                   4        738        467      0.517      0.552      0.525      0.372
                   5        738         70      0.445      0.386        0.3      0.148
                   6        738         65      0.322     0.0615      0.174     0.0675
                   7        738       1619      0.611      0.562      0.571      0.229
                   8        738       2845      0.675      0.558      0.568      0.298
                   9        738          2          1          0   0.000462   0.000416

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client0_highway_day

1 epochs completed in 0.032 hours.
Destroying process group...
[rank0]:[W507 21:32:33.566234122 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31359 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round032_phase2_full_client1_highway_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round032_phase2_full_client1_highway_night_start.pt

self imgsz: 640

Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client1_highway_night_stable_train' images and labels...:   0%|          | 0/6291 [00:00<?, ?it/s]

self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client1_highway_night_stable_train' images and labels...4888 found, 1403 missing, 0 empty, 0 corrupted: 100%|██████████| 6291/6291 [00:00<00:00, 13689.57it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client1_highway_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.45560152768937
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client1_highway_night_stable_train.cache' images and labels... 4888 found, 1403 missing, 0 empty, 0 corrupted: 100%|██████████| 6291/6291 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client1_highway_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:32:49.892926113 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:32:49.900942027 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2192       640  0.007353    0.0487   0.00471     4.861:   2%|▎         | 1/40 [00:33<21:36, 33.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1915       640  0.007123   0.04576  0.004947     4.626:   5%|▌         | 2/40 [00:34<09:10, 14.48s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1965       640  0.007152   0.04568  0.004932     4.621:   8%|▊         | 3/40 [00:35<05:09,  8.36s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1888       640  0.007177    0.0449  0.004926     4.561:  10%|█         | 4/40 [00:36<03:17,  5.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1909       640  0.007172   0.04424  0.004893     4.504:  12%|█▎        | 5/40 [00:37<02:13,  3.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1800       640  0.007085   0.04306  0.004679     4.386:  15%|█▌        | 6/40 [00:38<01:35,  2.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1972       640  0.007095   0.04248   0.00468      4.34:  18%|█▊        | 7/40 [00:39<01:12,  2.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1976       640   0.00708    0.0422  0.004663     4.315:  20%|██        | 8/40 [00:40<00:56,  1.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2006       640  0.007054   0.04198  0.004675     4.296:  22%|██▎       | 9/40 [00:41<00:46,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640  0.007057   0.04148  0.004673     4.257:  25%|██▌       | 10/40 [00:42<00:39,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2170       640  0.007062   0.04117  0.004677     4.232:  28%|██▊       | 11/40 [00:42<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1741       640  0.007054   0.04072  0.004716     4.199:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1839       640  0.007048   0.04026   0.00467     4.158:  32%|███▎      | 13/40 [00:44<00:27,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1883       640  0.007048   0.03995  0.004636     4.131:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2010       640  0.007064   0.03977  0.004652     4.119:  38%|███▊      | 15/40 [00:46<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1953       640  0.007063   0.03964  0.004693     4.111:  40%|████      | 16/40 [00:47<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1911       640  0.007073   0.03948  0.004718     4.101:  42%|████▎     | 17/40 [00:48<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2154       640   0.00708   0.03936  0.004714     4.092:  45%|████▌     | 18/40 [00:49<00:19,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1395       640  0.007059   0.03873  0.004684     4.038:  48%|████▊     | 19/40 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2075       640  0.007061   0.03862  0.004638     4.025:  50%|█████     | 20/40 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640  0.007054   0.03842  0.004641     4.009:  52%|█████▎    | 21/40 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2073       640  0.007064   0.03839  0.004609     4.005:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1986       640  0.007065   0.03834  0.004629     4.003:  57%|█████▊    | 23/40 [00:53<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2051       640  0.007062   0.03822  0.004639     3.994:  60%|██████    | 24/40 [00:54<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1854       640  0.007068   0.03806  0.004676     3.985:  62%|██████▎   | 25/40 [00:55<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1877       640  0.007061   0.03785  0.004644     3.964:  65%|██████▌   | 26/40 [00:56<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.555       0.42      0.408      0.229
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client1_highway_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client1_highway_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client1_highway_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.31it/s]

                 all        738      14937      0.545      0.421      0.407       0.23
                   0        738       1052      0.533      0.527      0.512      0.244
                   1        738         44      0.434      0.227      0.228      0.107
                   2        738       8622      0.692      0.718       0.74      0.471
                   3        738        151      0.504      0.424      0.436      0.333
                   4        738        467      0.466      0.595      0.536      0.379
                   5        738         70      0.346        0.4      0.288      0.151
                   6        738         65      0.295      0.123      0.187     0.0774
                   7        738       1619      0.568      0.598      0.568      0.231
                   8        738       2845      0.618      0.598      0.574      0.301
                   9        738          2          1          0   0.000354   0.000319

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client1_highway_night

1 epochs completed in 0.032 hours.
Destroying process group...
[rank0]:[W507 21:34:43.220466686 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31360 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round032_phase2_full_client2_citystreet_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round032_phase2_full_client2_citystreet_day_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client2_citystreet_day_stable_train' images and labels...5047 found, 1331 missing, 0 empty, 0 corrupted: 100%|██████████| 6378/6378 [00:00<00:00, 19591.33it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client2_citystreet_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.634739214423696
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client2_citystreet_day_stable_train.cache' images and labels... 5047 found, 1331 missing, 0 empty, 0 corrupted: 100%|██████████| 6378/6378 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client2_citystreet_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 21:34:59.787421893 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 21:34:59.819253578 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2035       640   0.00716   0.05754  0.004615     5.545:   3%|▎         | 1/39 [00:31<20:02, 31.64s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2167       640  0.007082   0.05808  0.004983     5.612:   5%|▌         | 2/39 [00:32<08:29, 13.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1936       640  0.006972   0.05642   0.00494     5.466:   8%|▊         | 3/39 [00:34<04:48,  8.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1939       640  0.006985   0.05556  0.004948     5.399:  10%|█         | 4/39 [00:35<03:04,  5.27s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2124       640  0.006953   0.05443   0.00484     5.298:  13%|█▎        | 5/39 [00:36<02:05,  3.69s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1730       640  0.006938   0.05279  0.004909     5.171:  15%|█▌        | 6/39 [00:36<01:30,  2.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1903       640  0.006984   0.05233  0.004901     5.137:  18%|█▊        | 7/39 [00:37<01:08,  2.14s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1889       640  0.006981   0.05141  0.004794     5.055:  21%|██        | 8/39 [00:38<00:53,  1.74s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640  0.006998    0.0513   0.00478     5.046:  23%|██▎       | 9/39 [00:39<00:44,  1.47s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1946       640  0.006989   0.05111  0.004792     5.031:  26%|██▌       | 10/39 [00:40<00:37,  1.29s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2225       640  0.007016   0.05087  0.004766     5.012:  28%|██▊       | 11/39 [00:41<00:32,  1.17s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1861       640  0.007035   0.05036  0.004809     4.977:  31%|███       | 12/39 [00:42<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2085       640  0.007035    0.0499  0.004825     4.941:  33%|███▎      | 13/39 [00:43<00:26,  1.03s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2100       640  0.007043   0.04976  0.004792     4.928:  36%|███▌      | 14/39 [00:44<00:24,  1.01it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1909       640  0.007054   0.04936  0.004816     4.898:  38%|███▊      | 15/39 [00:44<00:22,  1.04it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2013       640  0.007049   0.04898  0.004794     4.866:  41%|████      | 16/39 [00:45<00:21,  1.07it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1553       640  0.007028   0.04848  0.004725     4.818:  44%|████▎     | 17/39 [00:46<00:20,  1.09it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2049       640   0.00702   0.04847  0.004689     4.814:  46%|████▌     | 18/39 [00:47<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1802       640  0.007022    0.0481  0.004672     4.783:  49%|████▊     | 19/39 [00:48<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2077       640  0.007005   0.04793  0.004647     4.766:  51%|█████▏    | 20/39 [00:49<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1902       640  0.006999   0.04774  0.004642     4.751:  54%|█████▍    | 21/39 [00:50<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1870       640  0.006986   0.04756  0.004629     4.734:  56%|█████▋    | 22/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2005       640  0.006991   0.04746   0.00465     4.728:  59%|█████▉    | 23/39 [00:51<00:14,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1979       640  0.006994   0.04726  0.004635     4.711:  62%|██████▏   | 24/39 [00:52<00:13,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2069       640  0.006994   0.04711  0.004639     4.699:  64%|██████▍   | 25/39 [00:53<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1897       640  0.006982    0.0469  0.004601     4.678:  67%|██████▋   | 26/39 [00:54<00:11,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.536      0.421      0.401      0.222
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client2_citystreet_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client2_citystreet_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client2_citystreet_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.10it/s]

                 all        738      14937      0.522      0.424      0.399      0.222
                   0        738       1052      0.603      0.498      0.502      0.237
                   1        738         44      0.382      0.227       0.21     0.0914
                   2        738       8622      0.654      0.731      0.738      0.467
                   3        738        151      0.422      0.437      0.421       0.32
                   4        738        467      0.463      0.597      0.517      0.365
                   5        738         70      0.324      0.414      0.315      0.151
                   6        738         65      0.242      0.133      0.168     0.0664
                   7        738       1619      0.532      0.608      0.553      0.224
                   8        738       2845      0.594      0.598      0.568      0.298
                   9        738          2          1          0   0.000314   0.000282

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client2_citystreet_day

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W507 21:36:56.532732288 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31361 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round032_phase2_full_client3_citystreet_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round032_phase2_full_client3_citystreet_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client3_citystreet_night_stable_train' images and labels...4882 found, 1464 missing, 0 empty, 0 corrupted: 100%|██████████| 6346/6346 [00:00<00:00, 10761.53it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client3_citystreet_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.3070133963751
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client3_citystreet_night_stable_train.cache' images and labels... 4882 found, 1464 missing, 0 empty, 0 corrupted: 100%|██████████| 6346/6346 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client3_citystreet_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank1]:[W507 21:37:12.873616067 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W507 21:37:12.902103406 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1808       640  0.006678   0.04727  0.004677      4.69:   2%|▎         | 1/40 [00:33<22:01, 33.90s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2045       640  0.006899   0.04802  0.004321      4.74:   5%|▌         | 2/40 [00:35<09:18, 14.70s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1944       640  0.006863   0.04658  0.004165     4.609:   8%|▊         | 3/40 [00:36<05:15,  8.53s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1866       640  0.006923   0.04575  0.004325      4.56:  10%|█         | 4/40 [00:37<03:21,  5.61s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1638       640   0.00691    0.0441  0.004318     4.426:  12%|█▎        | 5/40 [00:38<02:17,  3.91s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1706       640   0.00694   0.04315  0.004395     4.359:  15%|█▌        | 6/40 [00:39<01:38,  2.89s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1976       640  0.006962   0.04267  0.004388     4.321:  18%|█▊        | 7/40 [00:40<01:14,  2.25s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1858       640  0.006995   0.04219  0.004323     4.281:  20%|██        | 8/40 [00:41<00:58,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1935       640  0.007012   0.04175  0.004303     4.245:  22%|██▎       | 9/40 [00:42<00:47,  1.54s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1811       640  0.007008   0.04118  0.004296     4.198:  25%|██▌       | 10/40 [00:42<00:40,  1.35s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2016       640  0.007027   0.04098  0.004327     4.187:  28%|██▊       | 11/40 [00:43<00:35,  1.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1754       640  0.007021   0.04047  0.004375     4.149:  30%|███       | 12/40 [00:44<00:31,  1.13s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1992       640  0.007043   0.04047  0.004385     4.152:  32%|███▎      | 13/40 [00:45<00:28,  1.06s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2002       640  0.007053   0.04036  0.004389     4.144:  35%|███▌      | 14/40 [00:46<00:26,  1.00s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1887       640  0.007055   0.04004  0.004358     4.116:  38%|███▊      | 15/40 [00:47<00:24,  1.03it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2115       640   0.00707   0.04015  0.004398     4.129:  40%|████      | 16/40 [00:48<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1511       640  0.007061    0.0396  0.004431     4.087:  42%|████▎     | 17/40 [00:49<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2029       640   0.00707   0.03953  0.004454     4.085:  45%|████▌     | 18/40 [00:50<00:20,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1685       640  0.007069   0.03911  0.004456     4.051:  48%|████▊     | 19/40 [00:51<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1983       640  0.007057   0.03893  0.004443     4.035:  50%|█████     | 20/40 [00:51<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2054       640  0.007076   0.03883  0.004441     4.028:  52%|█████▎    | 21/40 [00:52<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1630       640  0.007058   0.03861   0.00446      4.01:  55%|█████▌    | 22/40 [00:53<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1929       640  0.007059   0.03851  0.004466     4.003:  57%|█████▊    | 23/40 [00:54<00:15,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1899       640  0.007048   0.03834   0.00446     3.988:  60%|██████    | 24/40 [00:55<00:14,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2007       640  0.007049   0.03824  0.004439     3.978:  62%|██████▎   | 25/40 [00:56<00:13,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2034       640  0.007051   0.03822  0.004435     3.976:  65%|██████▌   | 26/40 [00:57<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.515      0.436      0.402      0.225
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client3_citystreet_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client3_citystreet_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client3_citystreet_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

                 all        738      14937      0.541      0.409        0.4      0.226
                   0        738       1052      0.531      0.505      0.498      0.239
                   1        738         44       0.42      0.182      0.207     0.0967
                   2        738       8622      0.692      0.709      0.735      0.468
                   3        738        151      0.573      0.397       0.42      0.321
                   4        738        467      0.457      0.597      0.536      0.377
                   5        738         70      0.344        0.4      0.308       0.16
                   6        738         65      0.263     0.0923      0.166     0.0648
                   7        738       1619      0.542      0.603       0.56      0.229
                   8        738       2845      0.593      0.603      0.569      0.299
                   9        738          2          1          0   0.000506   0.000456

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client3_citystreet_night

1 epochs completed in 0.034 hours.
Destroying process group...
[rank0]:[W507 21:39:12.097968154 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31362 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round032_phase2_full_client4_residential_day.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round032_phase2_full_client4_residential_day_start.pt
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client4_residential_day_stable_train' images and labels...5040 found, 1328 missing, 0 empty, 0 corrupted: 100%|██████████| 6368/6368 [00:00<00:00, 10397.95it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client4_residential_day_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.642293444999195
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client4_residential_day_stable_train.cache' images and labels... 5040 found, 1328 missing, 0 empty, 0 corrupted: 100%|██████████| 6368/6368 [00:00<?, ?it/s]

world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client4_residential_day
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:39:29.806475181 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:39:29.168748457 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/39 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      1941       640  0.007329   0.05766  0.005011       5.6:   3%|▎         | 1/39 [00:32<20:43, 32.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2040       640  0.007109   0.05517  0.004538     5.345:   5%|▌         | 2/39 [00:33<08:43, 14.15s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1901       640  0.007055   0.05385  0.004947     5.268:   8%|▊         | 3/39 [00:34<04:54,  8.19s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2149       640  0.007042   0.05216  0.004915     5.129:  10%|█         | 4/39 [00:36<03:08,  5.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2011       640   0.00707   0.05145   0.00472     5.059:  13%|█▎        | 5/39 [00:36<02:08,  3.78s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1604       640  0.007035   0.04988  0.004638     4.924:  15%|█▌        | 6/39 [00:37<01:32,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1912       640  0.007059    0.0495  0.004641     4.896:  18%|█▊        | 7/39 [00:38<01:09,  2.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2038       640  0.007064   0.04902   0.00467     4.861:  21%|██        | 8/39 [00:39<00:54,  1.76s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2215       640  0.007033   0.04921  0.004632      4.87:  23%|██▎       | 9/39 [00:40<00:44,  1.49s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1910       640  0.007006   0.04904  0.004585      4.85:  26%|██▌       | 10/39 [00:41<00:37,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1792       640  0.007007   0.04835  0.004531     4.791:  28%|██▊       | 11/39 [00:42<00:32,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1928       640  0.007008   0.04787  0.004594     4.758:  31%|███       | 12/39 [00:43<00:29,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2021       640  0.007014   0.04773  0.004544     4.743:  33%|███▎      | 13/39 [00:44<00:26,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2107       640  0.007024   0.04749  0.004509     4.722:  36%|███▌      | 14/39 [00:44<00:24,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1956       640   0.00702   0.04705   0.00447     4.683:  38%|███▊      | 15/39 [00:45<00:22,  1.06it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1899       640  0.007025   0.04678  0.004478     4.663:  41%|████      | 16/39 [00:46<00:21,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1980       640  0.007012   0.04651   0.00446     4.638:  44%|████▎     | 17/39 [00:47<00:19,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2019       640  0.007017   0.04631  0.004452     4.622:  46%|████▌     | 18/39 [00:48<00:18,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1828       640  0.007009   0.04594  0.004417     4.589:  49%|████▊     | 19/39 [00:49<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2027       640  0.006996   0.04585  0.004369     4.577:  51%|█████▏    | 20/39 [00:50<00:16,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2089       640  0.006987   0.04569  0.004326      4.56:  54%|█████▍    | 21/39 [00:51<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1884       640  0.006983   0.04553  0.004304     4.545:  56%|█████▋    | 22/39 [00:51<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1967       640  0.006982   0.04542  0.004276     4.534:  59%|█████▉    | 23/39 [00:52<00:14,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1893       640  0.006973   0.04528  0.004293     4.523:  62%|██████▏   | 24/39 [00:53<00:13,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1911       640  0.006971   0.04511  0.004291      4.51:  64%|██████▍   | 25/39 [00:54<00:12,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2101       640  0.006966   0.04502  0.004304     4.503:  67%|██████▋   | 26/39 [00:55<00:11,  1.14it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.551      0.413      0.405      0.224
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client4_residential_day/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client4_residential_day/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client4_residential_day/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:03<00:00,  1.32it/s]

                 all        738      14937      0.538      0.414      0.403      0.224
                   0        738       1052      0.556      0.523      0.509      0.242
                   1        738         44      0.376      0.182      0.221     0.0929
                   2        738       8622      0.721        0.7      0.737      0.464
                   3        738        151      0.539       0.43      0.442      0.333
                   4        738        467      0.461      0.593      0.517      0.365
                   5        738         70      0.302        0.4      0.288      0.144
                   6        738         65      0.261      0.109      0.175     0.0726
                   7        738       1619      0.552      0.601      0.562       0.23
                   8        738       2845       0.61        0.6      0.575        0.3
                   9        738          2          1          0   0.000291   0.000262

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client4_residential_day

1 epochs completed in 0.032 hours.
Destroying process group...
[rank0]:[W507 21:41:24.910089475 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31363 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round032_phase2_full_client5_residential_night.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/
Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/client_states/02_round032_phase2_full_client5_residential_night_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client5_residential_night_stable_train' images and labels...:   0%|          | 0/6316 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640

train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client5_residential_night_stable_train' images and labels...4883 found, 1433 missing, 0 empty, 0 corrupted: 100%|██████████| 6316/6316 [00:00<00:00, 16695.04it/s]
train: New cache created: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client5_residential_night_stable_train.cache
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 15.382166613873931
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/pl03_round032_client5_residential_night_stable_train.cache' images and labels... 4883 found, 1433 missing, 0 empty, 0 corrupted: 100%|██████████| 6316/6316 [00:00<?, ?it/s]
val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

world_size: 2
rank: 0
world_size: 2
rank: 1
Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client5_residential_night
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:41:40.654088729 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:41:40.694069228 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/40 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.48G      2156       640  0.007008   0.04687  0.004238     4.649:   2%|▎         | 1/40 [00:32<21:21, 32.85s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1713       640  0.007016   0.04614   0.00426     4.594:   5%|▌         | 2/40 [00:34<09:00, 14.22s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1951       640  0.007002   0.04589  0.004391     4.583:   8%|▊         | 3/40 [00:35<05:04,  8.23s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1902       640  0.006962   0.04524  0.004344     4.523:  10%|█         | 4/40 [00:36<03:15,  5.42s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1845       640  0.006994   0.04396  0.004425      4.43:  12%|█▎        | 5/40 [00:37<02:12,  3.79s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1801       640  0.007007    0.0431  0.004419     4.362:  15%|█▌        | 6/40 [00:38<01:35,  2.80s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1780       640  0.007025   0.04238  0.004555     4.317:  18%|█▊        | 7/40 [00:38<01:11,  2.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2095       640   0.00704   0.04269  0.004591     4.346:  20%|██        | 8/40 [00:39<00:56,  1.77s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1957       640  0.007034   0.04221  0.004481     4.298:  22%|██▎       | 9/40 [00:40<00:46,  1.50s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1683       640  0.007001   0.04133  0.004514     4.228:  25%|██▌       | 10/40 [00:41<00:39,  1.31s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1969       640  0.007013   0.04093  0.004495     4.195:  28%|██▊       | 11/40 [00:42<00:34,  1.18s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2008       640  0.007019   0.04088  0.004499     4.192:  30%|███       | 12/40 [00:43<00:30,  1.09s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1877       640  0.006999   0.04045  0.004457     4.152:  32%|███▎      | 13/40 [00:44<00:27,  1.02s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1870       640  0.007003   0.04008  0.004506     4.127:  35%|███▌      | 14/40 [00:45<00:25,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1842       640  0.006996   0.03979  0.004488     4.102:  38%|███▊      | 15/40 [00:45<00:23,  1.05it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1944       640  0.007012   0.03956  0.004493     4.086:  40%|████      | 16/40 [00:46<00:22,  1.08it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1959       640  0.007012   0.03934  0.004505     4.068:  42%|████▎     | 17/40 [00:47<00:21,  1.10it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2048       640  0.007015   0.03929  0.004507     4.065:  45%|████▌     | 18/40 [00:48<00:19,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1922       640  0.007015   0.03894  0.004514     4.037:  48%|████▊     | 19/40 [00:49<00:18,  1.11it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2080       640  0.007019   0.03888  0.004519     4.034:  50%|█████     | 20/40 [00:50<00:17,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      2151       640  0.007023   0.03882  0.004518     4.029:  52%|█████▎    | 21/40 [00:51<00:16,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1765       640  0.007016   0.03864  0.004489     4.012:  55%|█████▌    | 22/40 [00:52<00:15,  1.13it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1924       640  0.007008   0.03843  0.004463     3.992:  57%|█████▊    | 23/40 [00:53<00:15,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1762       640  0.006989    0.0382  0.004449     3.971:  60%|██████    | 24/40 [00:53<00:14,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1951       640   0.00698    0.0381  0.004418      3.96:  62%|██████▎   | 25/40 [00:54<00:13,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.8G      1728       640  0.006971   0.03779  0.004422     3.935:  65%|██████▌   | 26/40 [00:55<00:12,  1.12it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.562      0.412      0.404      0.227
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client5_residential_night/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client5_residential_night/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client5_residential_night/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.08it/s]

                 all        738      14937      0.544      0.413      0.402      0.227
                   0        738       1052      0.538      0.522      0.506      0.241
                   1        738         44      0.445      0.201      0.213      0.101
                   2        738       8622      0.686      0.714      0.734      0.467
                   3        738        151      0.538      0.404      0.432       0.33
                   4        738        467      0.487      0.595      0.536      0.376
                   5        738         70      0.326      0.386      0.287      0.155
                   6        738         65      0.279      0.108      0.176     0.0723
                   7        738       1619       0.54        0.6      0.558       0.23
                   8        738       2845      0.601      0.599      0.572      0.301
                   9        738          2          1          0   0.000409   0.000368

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_client5_residential_night

1 epochs completed in 0.033 hours.
Destroying process group...
[rank0]:[W507 21:43:37.779865821 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 31364 train.py --cfg /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/configs/pl03_round032_phase2_full_server_repair.yaml

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False

EfficientTeacher  618670a torch 2.8.0+cu128 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 48508.9375MB)

TensorBoard: Start with 'tensorboard --logdir /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs', view at http://localhost:6006/

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)

Model summary: 466 layers, 46186759 parameters, 46186759 gradients

Transferred 612/613 items from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/02_round032_phase2_full_server_repair_start.pt
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
Scaled weight_decay = 0.00125
optimizer: SGD with parameter groups 104 weight, 101 weight (no decay), 104 bias
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:251: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.cuda)
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]
cls gt ratio(positive): (6370.00-0) (376.00-1) (55752.00-2) (1112.00-3) (2993.00-4) (488.00-5) (270.00-6) (11415.00-7) (18325.00-8) (22.00-9)
cls gt total number: 97123.0 label number per image: 19.89817660315509
train: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_train.cache' images and labels... 4881 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 4881/4881 [00:00<?, ?it/s]

self imgsz: 640
self imgsz: 640
world_size: 2
rank: 0
world_size: 2
rank: 1

val: Scanning '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/data_lists/server_cloudy_val.cache' images and labels... 738 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 738/738 [00:00<?, ?it/s]
cls gt ratio(positive): (1052.00-0) (44.00-1) (8622.00-2) (151.00-3) (467.00-4) (70.00-5) (65.00-6) (1619.00-7) (2845.00-8) (2.00-9)
cls gt total number: 14937.0 label number per image: 20.239837398373982

Plotting labels...

Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_server_repair
Starting training for 1 epochs...
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:351: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
[rank0]:[W507 21:43:54.672868521 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank1]:[W507 21:43:54.677446610 reducer.cpp:1457] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())

     Epoch   gpu_mem    labels  img_size       box       obj       cls      loss
  0%|          | 0/31 [00:00<?, ?it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     6.16G      2625       640   0.02898   0.03045  0.003149     5.006:   3%|▎         | 1/31 [00:31<15:58, 31.95s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2744       640   0.02906   0.03044  0.003126      5.01:   6%|▋         | 2/31 [00:32<06:34, 13.59s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2517       640   0.02833   0.02924  0.003048      4.85:  10%|▉         | 3/31 [00:33<03:36,  7.73s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2094       640   0.02791   0.02806  0.002855     4.705:  13%|█▎        | 4/31 [00:34<02:14,  4.97s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2510       640   0.02755   0.02763  0.002828     4.641:  16%|█▌        | 5/31 [00:34<01:28,  3.39s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2440       640   0.02748   0.02721  0.002849     4.603:  19%|█▉        | 6/31 [00:35<01:00,  2.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2376       640   0.02749   0.02684  0.002908     4.579:  23%|██▎       | 7/31 [00:35<00:43,  1.82s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2580       640   0.02727    0.0267  0.002906     4.551:  26%|██▌       | 8/31 [00:36<00:32,  1.43s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2477       640   0.02729   0.02655  0.002843     4.535:  29%|██▉       | 9/31 [00:37<00:25,  1.16s/it]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2577       640   0.02727   0.02655  0.002812      4.53:  32%|███▏      | 10/31 [00:37<00:20,  1.02it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2687       640   0.02719   0.02648   0.00281     4.519:  35%|███▌      | 11/31 [00:38<00:17,  1.16it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2320       640   0.02708    0.0262  0.002799     4.486:  39%|███▊      | 12/31 [00:38<00:14,  1.29it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2397       640   0.02702   0.02611   0.00276     4.471:  42%|████▏     | 13/31 [00:39<00:12,  1.40it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2399       640   0.02701   0.02598  0.002734     4.458:  45%|████▌     | 14/31 [00:39<00:11,  1.48it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2329       640     0.027   0.02584  0.002778      4.45:  48%|████▊     | 15/31 [00:40<00:10,  1.55it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2332       640     0.027   0.02572  0.002787     4.441:  52%|█████▏    | 16/31 [00:41<00:09,  1.60it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2460       640   0.02703   0.02573  0.002769     4.442:  55%|█████▍    | 17/31 [00:41<00:08,  1.63it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2634       640   0.02712   0.02584  0.002746     4.456:  58%|█████▊    | 18/31 [00:42<00:07,  1.66it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2299       640   0.02711   0.02575  0.002734     4.447:  61%|██████▏   | 19/31 [00:42<00:07,  1.68it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2671       640   0.02713    0.0259  0.002732     4.462:  65%|██████▍   | 20/31 [00:43<00:06,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2597       640   0.02719   0.02596  0.002754     4.472:  68%|██████▊   | 21/31 [00:44<00:05,  1.69it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2430       640   0.02723   0.02605  0.002737     4.481:  71%|███████   | 22/31 [00:44<00:05,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2485       640   0.02725   0.02611  0.002714     4.486:  74%|███████▍  | 23/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2627       640    0.0273   0.02624  0.002709       4.5:  77%|███████▋  | 24/31 [00:45<00:04,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2364       640   0.02734   0.02626  0.002711     4.505:  81%|████████  | 25/31 [00:46<00:03,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
       0/0     42.6G      2523       640   0.02742   0.02635  0.002716     4.519:  84%|████████▍ | 26/31 [00:46<00:02,  1.70it/s]/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):
/app/Object_Detection/navigating_data_heterogeneity/vendor/efficientteacher/trainer/trainer.py:439: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(enabled=self.cuda):

                 all        738      14937      0.552      0.398      0.386      0.211
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_server_repair/weights/last.pt, 93.0MB
Optimizer stripped from /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_server_repair/weights/best.pt, 93.0MB

Validating /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_server_repair/weights/best.pt...
Fusing layers...
Model summary: 365 layers, 46156743 parameters, 0 gradients
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 5/5 [00:04<00:00,  1.09it/s]

                 all        738      14937      0.541      0.397      0.385      0.211
                   0        738       1052      0.504      0.517      0.487      0.229
                   1        738         44      0.456      0.159      0.205     0.0841
                   2        738       8622      0.702      0.706      0.731      0.466
                   3        738        151      0.503      0.411       0.43      0.314
                   4        738        467      0.466      0.565      0.509      0.349
                   5        738         70      0.317      0.371       0.28      0.122
                   6        738         65      0.301     0.0997      0.141     0.0507
                   7        738       1619      0.563      0.577      0.539      0.219
                   8        738       2845      0.602      0.559      0.531      0.273
                   9        738          2          1          0   0.000617   0.000556

Results saved to /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/runs/pl03_round032_phase2_full_server_repair

1 epochs completed in 0.028 hours.
Destroying process group...
[rank0]:[W507 21:45:33.902225788 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Cleaned 3 training artifact(s), freed 0.26 GiB
/root/micromamba/envs/al_yolov8/bin/python /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/evaluate_scene_daynight_protocol.py --workspace /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa --splits highway_day,highway_night,citystreet_day,citystreet_night,residential_day,residential_night,total --batch-size 16 --no-plots --verbose --checkpoint warmup_global=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/global_checkpoints/round000_warmup.pt --checkpoint phase1_final_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_dqa_aggregate.pt --checkpoint phase1_final_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round030_phase1_head_server_repair.pt --checkpoint phase2_final_aggregate=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round032_phase2_full_dqa_aggregate.pt --checkpoint phase2_final_repair=/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/checkpoints/round032_phase2_full_server_repair.pt

02 head-to-full DQA: 100%|██████████| 32/32 [7:38:15<00:00, 859.23s/round, elapsed=7h38m15s, eta=0s, phase=phase2_full, round=2]

Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/validation_reports/paper_protocol_eval_manifest.json
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/validation_reports/paper_protocol_eval_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/validation_reports/paper_protocol_classwise_summary.csv
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/validation_reports/paper_protocol_eval_summary.md
Saved: /app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa/stats/02_head_to_full_final_metrics.csv
DiscordNotifyResult(ok=True, chunks_sent=1, status_codes=(204,), dry_run=False, error=None)

CompletedProcess(args=['/root/micromamba/envs/al_yolov8/bin/python', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/scripts/run_scene_daynight_dqa_02_head_to_full.py', '--workspace-root', '/app/Object_Detection/dynamic_quality_aware_classwise_aggregation/scene_daynight_dqa/output/02_head_to_full_long_dqa', '--client-limit', '1500', '--phase1-rounds', '30', '--phase2-rounds', '2', '--batch-size', '160', '--workers', '8', '--gpus', '2', '--device', '', '--master-port', '31141', '--max-images-per-client', '0', '--estimated-phase1-round-minutes', '19.0', '--estimated-phase2-round-minutes', '23.0', '--estimated-eval-minutes', '60.0', '--evaluate', '--classwise', '--no-eval-plots', '--notify'], returncode=0)

## Progress

In [6]:
progress_csv = WORKSPACE / "stats" / "02_head_to_full_progress.csv"
if progress_csv.exists():
    progress_df = pd.read_csv(progress_csv)
    display(progress_df.tail(10))
    latest = progress_df.tail(1).iloc[0]
    print(f"elapsed={latest['elapsed_hms']} eta={latest['eta_hms']} completed={latest['completed_rounds']}/{latest['total_rounds']}")
else:
    print("No progress CSV yet:", progress_csv)

,created_utc,phase,phase_round,global_round,completed_rounds,total_rounds,elapsed_seconds,avg_seconds_per_round,eta_seconds,elapsed_hms,eta_hms,checkpoint
22,2026-05-07T19:32:29.914805+00:00,phase1_head,23,23,23,32,19508.704,848.205,7633.841,5h25m08s,2h07m13s,/app/Object_Detection/dynamic_quality_aware_cl...
23,2026-05-07T19:46:28.714540+00:00,phase1_head,24,24,24,32,20347.504,847.813,6782.501,5h39m07s,1h53m02s,/app/Object_Detection/dynamic_quality_aware_cl...
24,2026-05-07T20:00:41.739039+00:00,phase1_head,25,25,25,32,21200.529,848.021,5936.148,5h53m20s,1h38m56s,/app/Object_Detection/dynamic_quality_aware_cl...
25,2026-05-07T20:14:43.248973+00:00,phase1_head,26,26,26,32,22042.039,847.771,5086.624,6h07m22s,1h24m46s,/app/Object_Detection/dynamic_quality_aware_cl...
26,2026-05-07T20:28:50.911590+00:00,phase1_head,27,27,27,32,22889.701,847.767,4238.834,6h21m29s,1h10m38s,/app/Object_Detection/dynamic_quality_aware_cl...
27,2026-05-07T20:42:53.172144+00:00,phase1_head,28,28,28,32,23731.962,847.570,3390.280,6h35m31s,56m30s,/app/Object_Detection/dynamic_quality_aware_cl...
28,2026-05-07T20:57:01.195053+00:00,phase1_head,29,29,29,32,24579.985,847.586,2542.757,6h49m39s,42m22s,/app/Object_Detection/dynamic_quality_aware_cl...
29,2026-05-07T21:11:10.229287+00:00,phase1_head,30,30,30,32,25429.019,847.634,1695.268,7h03m49s,28m15s,/app/Object_Detection/dynamic_quality_aware_cl...
30,2026-05-07T21:28:28.060720+00:00,phase2_full,1,31,31,32,26466.850,853.769,853.769,7h21m06s,14m13s,/app/Object_Detection/dynamic_quality_aware_cl...
31,2026-05-07T21:45:36.580847+00:00,phase2_full,2,32,32,32,27495.370,859.230,0.000,7h38m15s,0s,/app/Object_Detection/dynamic_quality_aware_cl...

elapsed=7h38m15s eta=0s completed=32/32

## Final Metrics

In [7]:
final_metrics = WORKSPACE / "stats" / "02_head_to_full_final_metrics.csv"
if final_metrics.exists():
    final_df = pd.read_csv(final_metrics)
    display(final_df)
else:
    print("No final metrics yet:", final_metrics)

,checkpoint_label,kind,phase,phase_round,global_round,precision,recall,map50,map50_95,gain_vs_warmup_map50_95,delta_vs_repair_only_r3_map50_95,worst_split,worst_split_map50_95,worst_delta_vs_repair_only_r3_map50_95,day_avg_map50_95,night_avg_map50_95,night_delta_vs_repair_only_r3_map50_95,day_night_gap_map50_95
0,warmup_global,warmup,warmup,NaN,NaN,0.531,0.336,0.350,0.188,0.000,-0.024,highway_night,0.130,-0.022,0.208000,0.150000,-0.023333,0.058000
1,phase1_final_aggregate,aggregate,phase1_head,30.0,30.0,0.519,0.368,0.350,0.190,0.002,-0.022,highway_night,0.121,-0.031,0.214000,0.140667,-0.032666,0.073333
2,phase1_final_repair,server_repair,phase1_head,30.0,30.0,0.505,0.369,0.345,0.187,-0.001,-0.025,highway_night,0.120,-0.032,0.210000,0.137667,-0.035666,0.072333
3,phase2_final_aggregate,aggregate,phase2_full,2.0,32.0,0.515,0.364,0.345,0.186,-0.002,-0.026,highway_night,0.117,-0.035,0.210333,0.134333,-0.039000,0.076000
4,phase2_final_repair,server_repair,phase2_full,2.0,32.0,0.507,0.367,0.342,0.185,-0.003,-0.027,highway_night,0.118,-0.034,0.208000,0.133333,-0.040000,0.074667

## Split-Level Final Evaluation

In [8]:
split_metrics = WORKSPACE / "stats" / "02_head_to_full_split_metrics.csv"
if split_metrics.exists():
    split_df = pd.read_csv(split_metrics)
    cols = ["checkpoint_label", "split", "images", "labels", "precision", "recall", "map50", "map50_95"]
    display(split_df[cols].sort_values(["split", "checkpoint_label"]))
else:
    print("No split metrics yet:", split_metrics)

,checkpoint_label,split,images,labels,precision,recall,map50,map50_95
9,phase1_final_aggregate,citystreet_day,3067.0,69855.0,0.532,0.409,0.393,0.217
16,phase1_final_repair,citystreet_day,3067.0,69855.0,0.523,0.406,0.388,0.214
23,phase2_final_aggregate,citystreet_day,3067.0,69855.0,0.527,0.407,0.389,0.214
30,phase2_final_repair,citystreet_day,3067.0,69855.0,0.524,0.404,0.385,0.211
2,warmup_global,citystreet_day,3067.0,69855.0,0.558,0.336,0.383,0.209
10,phase1_final_aggregate,citystreet_night,2582.0,47259.0,0.471,0.317,0.278,0.143
17,phase1_final_repair,citystreet_night,2582.0,47259.0,0.464,0.310,0.273,0.140
24,phase2_final_aggregate,citystreet_night,2582.0,47259.0,0.460,0.315,0.270,0.138
31,phase2_final_repair,citystreet_night,2582.0,47259.0,0.475,0.309,0.269,0.137
3,warmup_global,citystreet_night,2582.0,47259.0,0.462,0.314,0.293,0.149
7,phase1_final_aggregate,highway_day,1290.0,20532.0,0.492,0.366,0.343,0.193
14,phase1_final_repair,highway_day,1290.0,20532.0,0.497,0.360,0.339,0.189
21,phase2_final_aggregate,highway_day,1290.0,20532.0,0.494,0.365,0.339,0.189
28,phase2_final_repair,highway_day,1290.0,20532.0,0.543,0.335,0.336,0.188
0,warmup_global,highway_day,1290.0,20532.0,0.710,0.314,0.337,0.187
8,phase1_final_aggregate,highway_night,1007.0,12708.0,0.443,0.245,0.224,0.121
15,phase1_final_repair,highway_night,1007.0,12708.0,0.450,0.244,0.225,0.120
22,phase2_final_aggregate,highway_night,1007.0,12708.0,0.465,0.224,0.218,0.117
29,phase2_final_repair,highway_night,1007.0,12708.0,0.463,0.233,0.219,0.118
1,warmup_global,highway_night,1007.0,12708.0,0.625,0.255,0.246,0.130
11,phase1_final_aggregate,residential_day,862.0,14881.0,0.459,0.428,0.411,0.232
18,phase1_final_repair,residential_day,862.0,14881.0,0.429,0.441,0.403,0.227
25,phase2_final_aggregate,residential_day,862.0,14881.0,0.447,0.435,0.406,0.228
32,phase2_final_repair,residential_day,862.0,14881.0,0.443,0.424,0.399,0.225
4,warmup_global,residential_day,862.0,14881.0,0.453,0.423,0.407,0.228
12,phase1_final_aggregate,residential_night,279.0,4184.0,0.376,0.331,0.300,0.158
19,phase1_final_repair,residential_night,279.0,4184.0,0.404,0.305,0.296,0.153
26,phase2_final_aggregate,residential_night,279.0,4184.0,0.368,0.324,0.287,0.148
33,phase2_final_repair,residential_night,279.0,4184.0,0.401,0.299,0.285,0.145
5,warmup_global,residential_night,279.0,4184.0,0.732,0.268,0.336,0.171
13,phase1_final_aggregate,scene_daynight_total,9087.0,169419.0,0.519,0.368,0.350,0.190
20,phase1_final_repair,scene_daynight_total,9087.0,169419.0,0.505,0.369,0.345,0.187
27,phase2_final_aggregate,scene_daynight_total,9087.0,169419.0,0.515,0.364,0.345,0.186
34,phase2_final_repair,scene_daynight_total,9087.0,169419.0,0.507,0.367,0.342,0.185
6,warmup_global,scene_daynight_total,9087.0,169419.0,0.531,0.336,0.350,0.188

## Compare Against 01_0 Repair-Only Summary

In [9]:
baseline = PROJECT_ROOT / "output" / "01_0_repair_baseline_comparison" / "stats" / "01_0_all_condition_metrics.csv"
if final_metrics.exists() and baseline.exists():
    base = pd.read_csv(baseline)
    repair_only = base[base["condition"].eq("repair_only")].sort_values("round").tail(1)
    display(repair_only)
    cols = [
        "checkpoint_label",
        "map50",
        "map50_95",
        "delta_vs_repair_only_r3_map50_95",
        "worst_split",
        "worst_split_map50_95",
        "worst_delta_vs_repair_only_r3_map50_95",
        "night_avg_map50_95",
        "night_delta_vs_repair_only_r3_map50_95",
    ]
    display(final_df[cols])
else:
    print("Missing final metrics or baseline.")

,condition,round,aggregate_map50,aggregate_map50_95,repaired_map50,repaired_map50_95,repair_gain_map50_95,retained_gain_map50_95,round_delta_map50_95,worst_split,worst_split_map50_95,day_avg_map50_95,night_avg_map50_95,day_night_gap_map50_95
2,repair_only,3,NaN,NaN,0.381,0.212,NaN,0.024,0.002,highway_night,0.152,0.232333,0.173333,0.059

,checkpoint_label,map50,map50_95,delta_vs_repair_only_r3_map50_95,worst_split,worst_split_map50_95,worst_delta_vs_repair_only_r3_map50_95,night_avg_map50_95,night_delta_vs_repair_only_r3_map50_95
0,warmup_global,0.350,0.188,-0.024,highway_night,0.130,-0.022,0.150000,-0.023333
1,phase1_final_aggregate,0.350,0.190,-0.022,highway_night,0.121,-0.031,0.140667,-0.032666
2,phase1_final_repair,0.345,0.187,-0.025,highway_night,0.120,-0.032,0.137667,-0.035666
3,phase2_final_aggregate,0.345,0.186,-0.026,highway_night,0.117,-0.035,0.134333,-0.039000
4,phase2_final_repair,0.342,0.185,-0.027,highway_night,0.118,-0.034,0.133333,-0.040000

## PseudoGT Signal Trend

In [10]:
pseudo_rows = []
stats_dir = WORKSPACE / "stats"
if stats_dir.exists():
    for path in sorted(stats_dir.glob("03_round*_pseudo_label_stats.csv")):
        part = pd.read_csv(path)
        part["source_csv"] = path.name
        pseudo_rows.append(part)
if pseudo_rows:
    pseudo_df = pd.concat(pseudo_rows, ignore_index=True)
    summary_cols = [c for c in [
        "round", "client", "images", "kept_images", "boxes",
        "mean_conf", "mean_stability", "mean_score", "source_csv",
    ] if c in pseudo_df.columns]
    display(pseudo_df[summary_cols].tail(30))
else:
    print("No pseudoGT stats yet.")

,round,client,mean_conf,mean_stability,mean_score,source_csv
162,round028,client0_highway_day,0.842352,0.941735,0.796607,03_round028_pseudo_label_stats.csv
163,round028,client1_highway_night,0.762103,0.920629,0.705922,03_round028_pseudo_label_stats.csv
164,round028,client2_citystreet_day,0.842357,0.939176,0.794684,03_round028_pseudo_label_stats.csv
165,round028,client3_citystreet_night,0.752466,0.914847,0.693096,03_round028_pseudo_label_stats.csv
166,round028,client4_residential_day,0.872944,0.949169,0.832053,03_round028_pseudo_label_stats.csv
167,round028,client5_residential_night,0.808280,0.930653,0.755730,03_round028_pseudo_label_stats.csv
168,round029,client0_highway_day,0.844458,0.941270,0.798143,03_round029_pseudo_label_stats.csv
169,round029,client1_highway_night,0.765653,0.919778,0.708569,03_round029_pseudo_label_stats.csv
170,round029,client2_citystreet_day,0.844293,0.938592,0.796038,03_round029_pseudo_label_stats.csv
171,round029,client3_citystreet_night,0.755830,0.913908,0.695483,03_round029_pseudo_label_stats.csv
172,round029,client4_residential_day,0.874504,0.948656,0.833119,03_round029_pseudo_label_stats.csv
173,round029,client5_residential_night,0.811971,0.930435,0.758904,03_round029_pseudo_label_stats.csv
174,round030,client0_highway_day,0.846261,0.940114,0.798933,03_round030_pseudo_label_stats.csv
175,round030,client1_highway_night,0.766425,0.918115,0.708019,03_round030_pseudo_label_stats.csv
176,round030,client2_citystreet_day,0.846326,0.937688,0.797173,03_round030_pseudo_label_stats.csv
177,round030,client3_citystreet_night,0.755373,0.912048,0.693744,03_round030_pseudo_label_stats.csv
178,round030,client4_residential_day,0.876549,0.947784,0.834307,03_round030_pseudo_label_stats.csv
179,round030,client5_residential_night,0.811056,0.929047,0.756994,03_round030_pseudo_label_stats.csv
180,round031,client0_highway_day,0.848345,0.939596,0.800437,03_round031_pseudo_label_stats.csv
181,round031,client1_highway_night,0.769702,0.917252,0.710340,03_round031_pseudo_label_stats.csv
182,round031,client2_citystreet_day,0.847294,0.936819,0.797314,03_round031_pseudo_label_stats.csv
183,round031,client3_citystreet_night,0.757569,0.911098,0.695032,03_round031_pseudo_label_stats.csv
184,round031,client4_residential_day,0.876391,0.947011,0.833600,03_round031_pseudo_label_stats.csv
185,round031,client5_residential_night,0.813051,0.928001,0.758044,03_round031_pseudo_label_stats.csv
186,round032,client0_highway_day,0.848980,0.939387,0.800816,03_round032_pseudo_label_stats.csv
187,round032,client1_highway_night,0.774585,0.916864,0.714556,03_round032_pseudo_label_stats.csv
188,round032,client2_citystreet_day,0.848700,0.936224,0.798152,03_round032_pseudo_label_stats.csv
189,round032,client3_citystreet_night,0.760668,0.910819,0.697540,03_round032_pseudo_label_stats.csv
190,round032,client4_residential_day,0.877818,0.946725,0.834618,03_round032_pseudo_label_stats.csv
191,round032,client5_residential_night,0.816014,0.927963,0.760783,03_round032_pseudo_label_stats.csv